
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jpype
import neqsim.process.equipment
import neqsim.process.equipment.pipeline
import neqsim.process.equipment.stream
import neqsim.thermo.system
import typing



class SimpleFlowLine(neqsim.process.equipment.TwoPortEquipment):
    length: float = ...
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: neqsim.process.equipment.stream.StreamInterface): ...
    def getHeight(self) -> float: ...
    def getPipeline(self) -> neqsim.process.equipment.pipeline.AdiabaticTwoPhasePipe: ...
    def getThermoSystem(self) -> neqsim.thermo.system.SystemInterface: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setHeight(self, double: float) -> None: ...

class SubseaWell(neqsim.process.equipment.TwoPortEquipment):
    height: float = ...
    length: float = ...
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: neqsim.process.equipment.stream.StreamInterface): ...
    def getPipeline(self) -> neqsim.process.equipment.pipeline.AdiabaticTwoPhasePipe: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("neqsim.process.equipment.subsea")``.

    SimpleFlowLine: typing.Type[SimpleFlowLine]
    SubseaWell: typing.Type[SubseaWell]
