
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jneqsim.chemicalreactions.chemicalequilibrium
import jneqsim.chemicalreactions.chemicalreaction
import jneqsim.chemicalreactions.kinetics
import jneqsim.thermo
import jneqsim.thermo.component
import jneqsim.thermo.phase
import jneqsim.thermo.system
import typing



class ChemicalReactionOperations(jneqsim.thermo.ThermodynamicConstantsInterface, java.lang.Cloneable):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def addNewComponents(self) -> None: ...
    def calcAmatrix(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def calcBVector(self) -> typing.MutableSequence[float]: ...
    def calcChemRefPot(self, int: int) -> typing.MutableSequence[float]: ...
    def calcInertMoles(self, int: int) -> float: ...
    def calcNVector(self) -> typing.MutableSequence[float]: ...
    def clone(self) -> 'ChemicalReactionOperations': ...
    def getAllElements(self) -> typing.MutableSequence[java.lang.String]: ...
    def getAmatrix(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getComponents(self) -> typing.MutableSequence[jneqsim.thermo.component.ComponentInterface]: ...
    def getDeltaReactionHeat(self) -> float: ...
    def getKinetics(self) -> jneqsim.chemicalreactions.kinetics.Kinetics: ...
    def getReactionList(self) -> jneqsim.chemicalreactions.chemicalreaction.ChemicalReactionList: ...
    def hasReactions(self) -> bool: ...
    def reacHeat(self, int: int, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def setComponents(self) -> None: ...
    @typing.overload
    def setComponents(self, int: int) -> None: ...
    def setDeltaReactionHeat(self, double: float) -> None: ...
    def setReactionList(self, chemicalReactionList: jneqsim.chemicalreactions.chemicalreaction.ChemicalReactionList) -> None: ...
    @typing.overload
    def setReactiveComponents(self) -> None: ...
    @typing.overload
    def setReactiveComponents(self, int: int) -> None: ...
    def setSystem(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    @typing.overload
    def solveChemEq(self, int: int) -> bool: ...
    @typing.overload
    def solveChemEq(self, int: int, int2: int) -> bool: ...
    def solveKinetics(self, int: int, phaseInterface: jneqsim.thermo.phase.PhaseInterface, int2: int) -> float: ...
    def sortReactiveComponents(self) -> None: ...
    def updateMoles(self, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.chemicalreactions")``.

    ChemicalReactionOperations: typing.Type[ChemicalReactionOperations]
    chemicalequilibrium: jneqsim.chemicalreactions.chemicalequilibrium.__module_protocol__
    chemicalreaction: jneqsim.chemicalreactions.chemicalreaction.__module_protocol__
    kinetics: jneqsim.chemicalreactions.kinetics.__module_protocol__
