import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.equipment.distillation
import typing

class ColumnInternalsDesigner(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        distillationColumn: jneqsim.process.equipment.distillation.DistillationColumn,
    ): ...
    def calculate(self) -> None: ...
    def getAverageTrayEfficiency(self) -> float: ...
    def getControllingTrayIndex(self) -> int: ...
    def getMaxPercentFlood(self) -> float: ...
    def getMinPercentFlood(self) -> float: ...
    def getPackingResult(self) -> "PackingHydraulicsCalculator": ...
    def getRequiredDiameter(self) -> float: ...
    def getTotalPressureDrop(self) -> float: ...
    def getTotalPressureDropMbar(self) -> float: ...
    def getTrayResults(self) -> java.util.List["TrayHydraulicsCalculator"]: ...
    def isDesignOk(self) -> bool: ...
    def setColumn(
        self,
        distillationColumn: jneqsim.process.equipment.distillation.DistillationColumn,
    ) -> None: ...
    def setColumnDiameterOverride(self, double: float) -> None: ...
    def setDesignFloodFraction(self, double: float) -> None: ...
    def setDowncommerAreaFraction(self, double: float) -> None: ...
    def setHoleAreaFraction(self, double: float) -> None: ...
    def setHoleDiameter(self, double: float) -> None: ...
    def setInternalsType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPackedHeight(self, double: float) -> None: ...
    def setPackingPreset(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setStructuredPacking(self, boolean: bool) -> None: ...
    def setTraySpacing(self, double: float) -> None: ...
    def setWeirHeight(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...

class PackingHydraulicsCalculator(java.io.Serializable):
    def __init__(self): ...
    def calculate(self) -> None: ...
    def getActualVelocity(self) -> float: ...
    def getColumnDiameter(self) -> float: ...
    def getFloodingVelocity(self) -> float: ...
    def getFsFactor(self) -> float: ...
    def getHETP(self) -> float: ...
    def getHtuG(self) -> float: ...
    def getHtuL(self) -> float: ...
    def getHtuOG(self) -> float: ...
    def getKGa(self) -> float: ...
    def getKLa(self) -> float: ...
    def getNumberOfTheoreticalStages(self) -> float: ...
    def getPackedHeight(self) -> float: ...
    def getPackingCategory(self) -> java.lang.String: ...
    def getPackingFactor(self) -> float: ...
    def getPackingName(self) -> java.lang.String: ...
    def getPercentFlood(self) -> float: ...
    def getPressureDropPerMeter(self) -> float: ...
    def getSpecificSurfaceArea(self) -> float: ...
    def getTotalPressureDrop(self) -> float: ...
    def getVoidFraction(self) -> float: ...
    def getWettedArea(self) -> float: ...
    def isDesignOk(self) -> bool: ...
    def isWettingOk(self) -> bool: ...
    def setColumnDiameter(self, double: float) -> None: ...
    def setCriticalSurfaceTension(self, double: float) -> None: ...
    def setDesignFloodFraction(self, double: float) -> None: ...
    def setLiquidDensity(self, double: float) -> None: ...
    def setLiquidDiffusivity(self, double: float) -> None: ...
    def setLiquidMassFlow(self, double: float) -> None: ...
    def setLiquidViscosity(self, double: float) -> None: ...
    def setNominalSize(self, double: float) -> None: ...
    def setPackedHeight(self, double: float) -> None: ...
    def setPackingCategory(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setPackingFactor(self, double: float) -> None: ...
    def setPackingName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPackingPreset(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPackingSpecification(
        self, packingSpecification: "PackingSpecification"
    ) -> None: ...
    def setSpecificSurfaceArea(self, double: float) -> None: ...
    def setStructuredPackingPreset(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setSurfaceTension(self, double: float) -> None: ...
    def setVaporDensity(self, double: float) -> None: ...
    def setVaporDiffusivity(self, double: float) -> None: ...
    def setVaporMassFlow(self, double: float) -> None: ...
    def setVaporViscosity(self, double: float) -> None: ...
    def setVoidFraction(self, double: float) -> None: ...
    def sizeColumnDiameter(self) -> float: ...

class PackingSpecification(java.io.Serializable):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        string3: typing.Union[java.lang.String, str],
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        string4: typing.Union[java.lang.String, str],
    ): ...
    def getBilletGasConstant(self) -> float: ...
    def getBilletLiquidConstant(self) -> float: ...
    def getCategory(self) -> java.lang.String: ...
    def getCriticalSurfaceTension(self) -> float: ...
    def getMaterial(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getNominalSizeM(self) -> float: ...
    def getNominalSizeMm(self) -> float: ...
    def getPackingFactor(self) -> float: ...
    def getSource(self) -> java.lang.String: ...
    def getSpecificSurfaceArea(self) -> float: ...
    def getVoidFraction(self) -> float: ...
    def isStructured(self) -> bool: ...

class PackingSpecificationLibrary:
    @staticmethod
    def contains(string: typing.Union[java.lang.String, str]) -> bool: ...
    @staticmethod
    def get(string: typing.Union[java.lang.String, str]) -> PackingSpecification: ...
    @staticmethod
    def getOrDefault(
        string: typing.Union[java.lang.String, str]
    ) -> PackingSpecification: ...
    @staticmethod
    def getPackingNames() -> java.util.List[java.lang.String]: ...
    @staticmethod
    def register(packingSpecification: PackingSpecification) -> None: ...
    @staticmethod
    def registerAlias(
        string: typing.Union[java.lang.String, str],
        packingSpecification: PackingSpecification,
    ) -> None: ...

class TrayHydraulicsCalculator(java.io.Serializable):
    def __init__(self): ...
    def calculate(self) -> None: ...
    def getActiveArea(self) -> float: ...
    def getActualVaporVelocity(self) -> float: ...
    def getCalculatedWeirLength(self) -> float: ...
    def getColumnDiameter(self) -> float: ...
    def getDowncommerArea(self) -> float: ...
    def getDowncommerAreaFraction(self) -> float: ...
    def getDowncommerBackup(self) -> float: ...
    def getDowncommerBackupFraction(self) -> float: ...
    def getDryTrayPressureDrop(self) -> float: ...
    def getEntrainment(self) -> float: ...
    def getFloodingVelocity(self) -> float: ...
    def getFsFactor(self) -> float: ...
    def getHoleArea(self) -> float: ...
    def getLiquidHeadPressureDrop(self) -> float: ...
    def getMinimumVaporVelocity(self) -> float: ...
    def getPercentFlood(self) -> float: ...
    def getResidualHeadPressureDrop(self) -> float: ...
    def getTotalArea(self) -> float: ...
    def getTotalTrayPressureDrop(self) -> float: ...
    def getTotalTrayPressureDropMbar(self) -> float: ...
    def getTrayEfficiency(self) -> float: ...
    def getTraySpacing(self) -> float: ...
    def getTrayType(self) -> java.lang.String: ...
    def getTurndownRatio(self) -> float: ...
    def getWeirHeight(self) -> float: ...
    def isDesignOk(self) -> bool: ...
    def isDowncommerBackupOk(self) -> bool: ...
    def isEntrainmentOk(self) -> bool: ...
    def isWeepingOk(self) -> bool: ...
    def setColumnDiameter(self, double: float) -> None: ...
    def setDesignFloodFraction(self, double: float) -> None: ...
    def setDowncommerAreaFraction(self, double: float) -> None: ...
    def setHoleAreaFraction(self, double: float) -> None: ...
    def setHoleDiameter(self, double: float) -> None: ...
    def setLiquidDensity(self, double: float) -> None: ...
    def setLiquidMassFlow(self, double: float) -> None: ...
    def setLiquidViscosity(self, double: float) -> None: ...
    def setRelativeVolatility(self, double: float) -> None: ...
    def setSurfaceTension(self, double: float) -> None: ...
    def setTraySpacing(self, double: float) -> None: ...
    def setTrayType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setVaporDensity(self, double: float) -> None: ...
    def setVaporMassFlow(self, double: float) -> None: ...
    def setWeirHeight(self, double: float) -> None: ...
    def setWeirLength(self, double: float) -> None: ...
    def sizeColumnDiameter(self) -> float: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.distillation.internals")``.

    ColumnInternalsDesigner: typing.Type[ColumnInternalsDesigner]
    PackingHydraulicsCalculator: typing.Type[PackingHydraulicsCalculator]
    PackingSpecification: typing.Type[PackingSpecification]
    PackingSpecificationLibrary: typing.Type[PackingSpecificationLibrary]
    TrayHydraulicsCalculator: typing.Type[TrayHydraulicsCalculator]
