
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import neqsim.process.alarm
import neqsim.process.conditionmonitor
import neqsim.process.controllerdevice
import neqsim.process.costestimation
import neqsim.process.equipment
import neqsim.process.logic
import neqsim.process.measurementdevice
import neqsim.process.mechanicaldesign
import neqsim.process.processmodel
import neqsim.process.safety
import neqsim.process.util
import neqsim.util
import typing



class SimulationInterface(neqsim.util.NamedInterface, java.lang.Runnable, java.io.Serializable):
    def getCalculateSteadyState(self) -> bool: ...
    def getCalculationIdentifier(self) -> java.util.UUID: ...
    def getReport_json(self) -> java.lang.String: ...
    def getTime(self) -> float: ...
    def increaseTime(self, double: float) -> None: ...
    def isRunInSteps(self) -> bool: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def run_step(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def run_step(self) -> None: ...
    def setCalculateSteadyState(self, boolean: bool) -> None: ...
    def setCalculationIdentifier(self, uUID: java.util.UUID) -> None: ...
    def setRunInSteps(self, boolean: bool) -> None: ...
    def setTime(self, double: float) -> None: ...
    def solved(self) -> bool: ...

class SimulationBaseClass(neqsim.util.NamedBaseClass, SimulationInterface):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def getCalculateSteadyState(self) -> bool: ...
    def getCalculationIdentifier(self) -> java.util.UUID: ...
    def getTime(self) -> float: ...
    def increaseTime(self, double: float) -> None: ...
    def isRunInSteps(self) -> bool: ...
    def setCalculateSteadyState(self, boolean: bool) -> None: ...
    def setCalculationIdentifier(self, uUID: java.util.UUID) -> None: ...
    def setRunInSteps(self, boolean: bool) -> None: ...
    def setTime(self, double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("neqsim.process")``.

    SimulationBaseClass: typing.Type[SimulationBaseClass]
    SimulationInterface: typing.Type[SimulationInterface]
    alarm: neqsim.process.alarm.__module_protocol__
    conditionmonitor: neqsim.process.conditionmonitor.__module_protocol__
    controllerdevice: neqsim.process.controllerdevice.__module_protocol__
    costestimation: neqsim.process.costestimation.__module_protocol__
    equipment: neqsim.process.equipment.__module_protocol__
    logic: neqsim.process.logic.__module_protocol__
    measurementdevice: neqsim.process.measurementdevice.__module_protocol__
    mechanicaldesign: neqsim.process.mechanicaldesign.__module_protocol__
    processmodel: neqsim.process.processmodel.__module_protocol__
    safety: neqsim.process.safety.__module_protocol__
    util: neqsim.process.util.__module_protocol__
