
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import typing



class CO2Electrolyzer(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getGasProductStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getLiquidProductStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setCO2Conversion(self, double: float) -> None: ...
    def setCellVoltage(self, double: float) -> None: ...
    def setCo2ComponentName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setCurrentEfficiency(self, double: float) -> None: ...
    def setElectronsPerMoleProduct(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setGasProductSelectivity(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setLiquidProductSelectivity(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setProductFaradaicEfficiency(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setUseSelectivityModel(self, boolean: bool) -> None: ...

class Electrolyzer(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getActiveCellArea(self) -> float: ...
    def getAuxiliaryLoadFraction(self) -> float: ...
    def getAvailablePower(self) -> float: ...
    def getCellVoltage(self) -> float: ...
    def getCurrentDensity(self) -> float: ...
    def getCurtailedPower(self) -> float: ...
    def getFaradaicEfficiency(self) -> float: ...
    def getHydrogenCompressionPower(self) -> float: ...
    def getHydrogenDeliveryPressure(self) -> float: ...
    def getHydrogenOutStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getIVCharacteristic(self) -> 'ElectrolyzerIVCharacteristic': ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMaxRampRate(self) -> float: ...
    def getMinimumLoadFraction(self) -> float: ...
    def getNominalCurrentDensity(self) -> float: ...
    def getNumberOfCells(self) -> int: ...
    def getOperatingPower(self) -> float: ...
    def getOperationMode(self) -> 'Electrolyzer.OperationMode': ...
    def getOxygenOutStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getRatedPower(self) -> float: ...
    def getRectifierEfficiency(self) -> float: ...
    def getSpecificEnergyConsumption_kWh_per_kg_H2(self) -> float: ...
    def getStackActiveArea(self) -> float: ...
    def getStackCurrent(self) -> float: ...
    def getStackPower(self) -> float: ...
    def getStandbyPowerFraction(self) -> float: ...
    def getSystemPower(self) -> float: ...
    def getSystemSpecificEnergyConsumption_kWh_per_kg_H2(self) -> float: ...
    def getTechnology(self) -> 'ElectrolyzerTechnology': ...
    def getWasteHeat(self) -> float: ...
    def getWaterConsumption(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def isStandby(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setActiveCellArea(self, double: float) -> None: ...
    def setAuxiliaryLoadFraction(self, double: float) -> None: ...
    def setAvailablePower(self, double: float) -> None: ...
    def setCellVoltage(self, double: float) -> None: ...
    def setCurrentDensity(self, double: float) -> None: ...
    def setFaradaicEfficiency(self, double: float) -> None: ...
    def setHydrogenDeliveryPressure(self, double: float) -> None: ...
    def setIVCharacteristic(self, electrolyzerIVCharacteristic: 'ElectrolyzerIVCharacteristic') -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setMaxRampRate(self, double: float) -> None: ...
    def setMinimumLoadFraction(self, double: float) -> None: ...
    def setNominalCurrentDensity(self, double: float) -> None: ...
    def setNumberOfCells(self, int: int) -> None: ...
    def setOperationMode(self, operationMode: 'Electrolyzer.OperationMode') -> None: ...
    def setRatedPower(self, double: float) -> None: ...
    def setRectifierEfficiency(self, double: float) -> None: ...
    def setStackActiveArea(self, double: float) -> None: ...
    def setStandbyPowerFraction(self, double: float) -> None: ...
    def setTechnology(self, electrolyzerTechnology: 'ElectrolyzerTechnology') -> None: ...
    @typing.overload
    def sizeStack(self, double: float) -> None: ...
    @typing.overload
    def sizeStack(self, double: float, double2: float, double3: float) -> None: ...
    class OperationMode(java.lang.Enum['Electrolyzer.OperationMode']):
        WATER_FEED: typing.ClassVar['Electrolyzer.OperationMode'] = ...
        POWER: typing.ClassVar['Electrolyzer.OperationMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Electrolyzer.OperationMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['Electrolyzer.OperationMode']: ...

class ElectrolyzerIVCharacteristic(java.io.Serializable):
    def __init__(self, electrolyzerTechnology: 'ElectrolyzerTechnology'): ...
    def getAreaSpecificResistance(self) -> float: ...
    def getCellVoltage(self, double: float, double2: float) -> float: ...
    def getExchangeCurrentDensity(self) -> float: ...
    def getReversibleVoltage(self, double: float) -> float: ...
    def getTafelSlope(self) -> float: ...
    def getTechnology(self) -> 'ElectrolyzerTechnology': ...
    def setAreaSpecificResistance(self, double: float) -> None: ...
    def setExchangeCurrentDensity(self, double: float) -> None: ...
    def setTafelSlope(self, double: float) -> None: ...

class ElectrolyzerTechnology(java.lang.Enum['ElectrolyzerTechnology']):
    PEM: typing.ClassVar['ElectrolyzerTechnology'] = ...
    ALKALINE: typing.ClassVar['ElectrolyzerTechnology'] = ...
    SOEC: typing.ClassVar['ElectrolyzerTechnology'] = ...
    AEM: typing.ClassVar['ElectrolyzerTechnology'] = ...
    def getDefaultCellVoltage(self) -> float: ...
    def getDefaultCurrentDensity(self) -> float: ...
    def getDefaultFaradaicEfficiency(self) -> float: ...
    def getDefaultPressureBara(self) -> float: ...
    def getDefaultTemperatureC(self) -> float: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'ElectrolyzerTechnology': ...
    @staticmethod
    def values() -> typing.MutableSequence['ElectrolyzerTechnology']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.electrolyzer")``.

    CO2Electrolyzer: typing.Type[CO2Electrolyzer]
    Electrolyzer: typing.Type[Electrolyzer]
    ElectrolyzerIVCharacteristic: typing.Type[ElectrolyzerIVCharacteristic]
    ElectrolyzerTechnology: typing.Type[ElectrolyzerTechnology]
