import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import typing

class H2SScavengerPerformance(java.io.Serializable):
    def __init__(self): ...
    def evaluate(self) -> None: ...
    def getBreakthroughDays(self) -> float: ...
    def getCapacityKgH2SPerKgActive(self) -> float: ...
    def getH2SToRemoveKgPerDay(self) -> float: ...
    def getScavengerDemandKgPerDay(self) -> float: ...
    def getStandardsApplied(
        self,
    ) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getWarnings(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def isEvaluated(self) -> bool: ...
    def setActiveWtPct(self, double: float) -> None: ...
    def setChemistry(
        self, scavengerChemistry: "H2SScavengerPerformance.ScavengerChemistry"
    ) -> None: ...
    def setGasFlowMSm3PerDay(self, double: float) -> None: ...
    def setH2SInletPpm(self, double: float) -> None: ...
    def setH2STargetPpm(self, double: float) -> None: ...
    def setPressureBara(self, double: float) -> None: ...
    def setScavengerInventoryKg(self, double: float) -> None: ...
    def setTemperatureCelsius(self, double: float) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

    class ScavengerChemistry(
        java.lang.Enum["H2SScavengerPerformance.ScavengerChemistry"]
    ):
        MEA_TRIAZINE: typing.ClassVar["H2SScavengerPerformance.ScavengerChemistry"] = (
            ...
        )
        MMA_TRIAZINE: typing.ClassVar["H2SScavengerPerformance.ScavengerChemistry"] = (
            ...
        )
        IRON_CHELATE: typing.ClassVar["H2SScavengerPerformance.ScavengerChemistry"] = (
            ...
        )
        IRON_SPONGE: typing.ClassVar["H2SScavengerPerformance.ScavengerChemistry"] = ...
        ALDEHYDE: typing.ClassVar["H2SScavengerPerformance.ScavengerChemistry"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "H2SScavengerPerformance.ScavengerChemistry": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["H2SScavengerPerformance.ScavengerChemistry"]
        ): ...

class PackedBedScavengerReactor(java.io.Serializable):
    def __init__(self): ...
    def evaluate(self) -> "PackedBedScavengerReactor": ...
    def getBedUtilisationProfile(self) -> java.util.List[float]: ...
    def getBreakthroughTimeS(self) -> float: ...
    def getFinalBedUtilisation(self) -> float: ...
    def getOutletConcentrationProfile(self) -> java.util.List[float]: ...
    def getStandardsApplied(
        self,
    ) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getTimeSeriesS(self) -> java.util.List[float]: ...
    def getTotalH2sRemovedKg(self) -> float: ...
    def isEvaluated(self) -> bool: ...
    def setDiscretisation(self, int: int, int2: int) -> "PackedBedScavengerReactor": ...
    def setFeed(self, double: float, double2: float) -> "PackedBedScavengerReactor": ...
    def setGeometry(
        self, double: float, double2: float, double3: float
    ) -> "PackedBedScavengerReactor": ...
    def setMedia(
        self, double: float, double2: float, double3: float
    ) -> "PackedBedScavengerReactor": ...
    def setRateConstant(self, double: float) -> "PackedBedScavengerReactor": ...
    def setSimulationTime(
        self, double: float, double2: float
    ) -> "PackedBedScavengerReactor": ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.chemistry.scavenger")``.

    H2SScavengerPerformance: typing.Type[H2SScavengerPerformance]
    PackedBedScavengerReactor: typing.Type[PackedBedScavengerReactor]
