
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import jneqsim.process.equipment
import jneqsim.process.mechanicaldesign
import typing



class EjectorMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def getBodyVolume(self) -> float: ...
    def getConnectedPipingVolume(self) -> float: ...
    def getDiffuserOutletArea(self) -> float: ...
    def getDiffuserOutletDiameter(self) -> float: ...
    def getDiffuserOutletLength(self) -> float: ...
    def getDiffuserOutletVelocity(self) -> float: ...
    def getDischargeConnectionLength(self) -> float: ...
    def getEntrainmentRatio(self) -> float: ...
    def getMixingChamberArea(self) -> float: ...
    def getMixingChamberDiameter(self) -> float: ...
    def getMixingChamberLength(self) -> float: ...
    def getMixingChamberVelocity(self) -> float: ...
    def getMixingPressure(self) -> float: ...
    def getMotiveNozzleDiameter(self) -> float: ...
    def getMotiveNozzleEffectiveLength(self) -> float: ...
    def getMotiveNozzleExitVelocity(self) -> float: ...
    def getMotiveNozzleThroatArea(self) -> float: ...
    def getSuctionConnectionLength(self) -> float: ...
    def getSuctionInletArea(self) -> float: ...
    def getSuctionInletDiameter(self) -> float: ...
    def getSuctionInletLength(self) -> float: ...
    def getSuctionInletVelocity(self) -> float: ...
    def getTotalVolume(self) -> float: ...
    def resetDesign(self) -> None: ...
    def updateDesign(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, double9: float, double10: float, double11: float, double12: float, double13: float, double14: float, double15: float, double16: float, double17: float, double18: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.ejector")``.

    EjectorMechanicalDesign: typing.Type[EjectorMechanicalDesign]
