
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.compressor
import jneqsim.process.equipment.separator
import jneqsim.process.equipment.valve
import jneqsim.process.ml
import jneqsim.process.processmodel
import typing



class Agent(java.io.Serializable):
    def applyAction(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def computeReward(self, stateVector: jneqsim.process.ml.StateVector, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    def getActionDim(self) -> int: ...
    def getAgentId(self) -> java.lang.String: ...
    def getLocalObservation(self, stateVector: jneqsim.process.ml.StateVector) -> typing.MutableSequence[float]: ...
    def getMessage(self, stateVector: jneqsim.process.ml.StateVector) -> typing.MutableSequence[float]: ...
    def getObservationDim(self) -> int: ...
    def isTerminated(self, stateVector: jneqsim.process.ml.StateVector) -> bool: ...
    def receiveMessages(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]]]) -> None: ...

class MultiAgentEnvironment(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def addAgent(self, agent: Agent) -> 'MultiAgentEnvironment': ...
    def getAgent(self, string: typing.Union[java.lang.String, str]) -> Agent: ...
    def getAgentIds(self) -> java.util.List[java.lang.String]: ...
    def getCurrentGlobalState(self) -> jneqsim.process.ml.StateVector: ...
    def getCurrentStep(self) -> int: ...
    def getNumAgents(self) -> int: ...
    def getProcess(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def isDone(self) -> bool: ...
    def reset(self) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def setCoordinationMode(self, coordinationMode: 'MultiAgentEnvironment.CoordinationMode') -> 'MultiAgentEnvironment': ...
    def setMaxEpisodeSteps(self, int: int) -> 'MultiAgentEnvironment': ...
    def setSharedConstraints(self, constraintManager: jneqsim.process.ml.ConstraintManager) -> 'MultiAgentEnvironment': ...
    def step(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]]]) -> 'MultiAgentEnvironment.MultiAgentStepResult': ...
    class CoordinationMode(java.lang.Enum['MultiAgentEnvironment.CoordinationMode']):
        INDEPENDENT: typing.ClassVar['MultiAgentEnvironment.CoordinationMode'] = ...
        COOPERATIVE: typing.ClassVar['MultiAgentEnvironment.CoordinationMode'] = ...
        CTDE: typing.ClassVar['MultiAgentEnvironment.CoordinationMode'] = ...
        COMMUNICATING: typing.ClassVar['MultiAgentEnvironment.CoordinationMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'MultiAgentEnvironment.CoordinationMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['MultiAgentEnvironment.CoordinationMode']: ...
    class MultiAgentStepResult(java.io.Serializable):
        observations: java.util.Map = ...
        rewards: java.util.Map = ...
        terminated: bool = ...
        truncated: bool = ...
        infos: java.util.Map = ...
        globalState: jneqsim.process.ml.StateVector = ...
        def __init__(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], boolean: bool, boolean2: bool, map3: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Any], typing.Mapping[typing.Union[java.lang.String, str], typing.Any]]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Any], typing.Mapping[typing.Union[java.lang.String, str], typing.Any]]]], stateVector: jneqsim.process.ml.StateVector): ...

class ProcessAgent(Agent, java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def computeReward(self, stateVector: jneqsim.process.ml.StateVector, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    def getActionDim(self) -> int: ...
    def getActionHigh(self) -> typing.MutableSequence[float]: ...
    def getActionLow(self) -> typing.MutableSequence[float]: ...
    def getActionNames(self) -> typing.MutableSequence[java.lang.String]: ...
    def getAgentId(self) -> java.lang.String: ...
    def getEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...
    def getLocalConstraints(self) -> jneqsim.process.ml.ConstraintManager: ...
    def getObservationDim(self) -> int: ...
    def getObservationNames(self) -> typing.MutableSequence[java.lang.String]: ...
    def getSetpoint(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def isTerminated(self, stateVector: jneqsim.process.ml.StateVector) -> bool: ...
    def setSetpoint(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> 'ProcessAgent': ...

class CompressorAgent(ProcessAgent):
    def __init__(self, string: typing.Union[java.lang.String, str], compressor: jneqsim.process.equipment.compressor.Compressor): ...
    def applyAction(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def computeReward(self, stateVector: jneqsim.process.ml.StateVector, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    def getCompressor(self) -> jneqsim.process.equipment.compressor.Compressor: ...
    def getLocalObservation(self, stateVector: jneqsim.process.ml.StateVector) -> typing.MutableSequence[float]: ...
    def isTerminated(self, stateVector: jneqsim.process.ml.StateVector) -> bool: ...
    def setDischargePressureSetpoint(self, double: float) -> None: ...
    def setSpeedRange(self, double: float, double2: float) -> None: ...

class SeparatorAgent(ProcessAgent):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], separator: jneqsim.process.equipment.separator.Separator, throttlingValve: jneqsim.process.equipment.valve.ThrottlingValve): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], separator: jneqsim.process.equipment.separator.Separator, throttlingValve: jneqsim.process.equipment.valve.ThrottlingValve, throttlingValve2: jneqsim.process.equipment.valve.ThrottlingValve): ...
    def applyAction(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def computeReward(self, stateVector: jneqsim.process.ml.StateVector, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    def getLocalObservation(self, stateVector: jneqsim.process.ml.StateVector) -> typing.MutableSequence[float]: ...
    def getSeparator(self) -> jneqsim.process.equipment.separator.Separator: ...
    def setLevelSetpoint(self, double: float) -> None: ...
    def setPressureSetpoint(self, double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.ml.multiagent")``.

    Agent: typing.Type[Agent]
    CompressorAgent: typing.Type[CompressorAgent]
    MultiAgentEnvironment: typing.Type[MultiAgentEnvironment]
    ProcessAgent: typing.Type[ProcessAgent]
    SeparatorAgent: typing.Type[SeparatorAgent]
