import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.thermo.system
import typing

class DepressurizationSimulator(java.io.Serializable):
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
        double3: float,
        double4: float,
    ): ...
    def run(self) -> "DepressurizationSimulator.DepressurizationResult": ...
    def setFireHeatInput(self, double: float) -> "DepressurizationSimulator": ...
    def setMaxTime(self, double: float) -> "DepressurizationSimulator": ...
    def setStopPressure(self, double: float) -> "DepressurizationSimulator": ...
    def setTimeStep(self, double: float) -> "DepressurizationSimulator": ...
    def setWall(
        self, double: float, double2: float, double3: float, double4: float
    ) -> "DepressurizationSimulator": ...

    class DepressurizationResult(java.io.Serializable):
        initialPressureBara: float = ...
        time: java.util.List = ...
        pressureBara: java.util.List = ...
        temperatureK: java.util.List = ...
        massKg: java.util.List = ...
        wallTempK: java.util.List = ...
        massFlowKgPerS: java.util.List = ...
        timeToHalfPressure: float = ...
        timeTo7BargS: float = ...
        minFluidTemperatureK: float = ...
        minWallTemperatureK: float = ...
        halfPressureCriterionMet: bool = ...
        sevenBargCriterionMet: bool = ...
        def __init__(self): ...
        def evaluateSTS0131(
            self, sTS0131AcceptanceCriteria: "STS0131AcceptanceCriteria"
        ) -> "STS0131AcceptanceResult": ...
        def meetsMDMT(self, double: float) -> bool: ...
        def summary(self) -> java.lang.String: ...

class STS0131AcceptanceCriteria(java.io.Serializable):
    def __init__(self): ...
    def evaluate(
        self, depressurizationResult: DepressurizationSimulator.DepressurizationResult
    ) -> "STS0131AcceptanceResult": ...
    def getEstimatedTimeToRuptureS(self) -> float: ...
    def getMaximumEscalatedFireRateKgPerS(self) -> float: ...
    def getMaximumPressureAtRuptureBara(self) -> float: ...
    def getMaximumRemainingMassKg(self) -> float: ...
    def getTimeToEscapeS(self) -> float: ...
    def setEstimatedTimeToRuptureS(
        self, double: float
    ) -> "STS0131AcceptanceCriteria": ...
    def setMaximumEscalatedFireRateKgPerS(
        self, double: float
    ) -> "STS0131AcceptanceCriteria": ...
    def setMaximumPressureAtRuptureBara(
        self, double: float
    ) -> "STS0131AcceptanceCriteria": ...
    def setMaximumRemainingMassKg(
        self, double: float
    ) -> "STS0131AcceptanceCriteria": ...
    def setTimeToEscapeS(self, double: float) -> "STS0131AcceptanceCriteria": ...

class STS0131AcceptanceResult(java.io.Serializable):
    def __init__(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        boolean: bool,
        boolean2: bool,
        boolean3: bool,
        boolean4: bool,
        boolean5: bool,
        boolean6: bool,
        boolean7: bool,
    ): ...
    def getLimitingTimeS(self) -> float: ...
    def getPeakDischargeRateKgPerS(self) -> float: ...
    def getPressureAtLimitingTimeBara(self) -> float: ...
    def getRemainingMassAtLimitingTimeKg(self) -> float: ...
    def isAcceptable(self) -> bool: ...
    def isFireRateCriterionConfigured(self) -> bool: ...
    def isFireRateCriterionMet(self) -> bool: ...
    def isMassCriterionConfigured(self) -> bool: ...
    def isMassCriterionMet(self) -> bool: ...
    def isPressureCriterionConfigured(self) -> bool: ...
    def isPressureCriterionMet(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.depressurization")``.

    DepressurizationSimulator: typing.Type[DepressurizationSimulator]
    STS0131AcceptanceCriteria: typing.Type[STS0131AcceptanceCriteria]
    STS0131AcceptanceResult: typing.Type[STS0131AcceptanceResult]
