
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import java.util.function
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.mixer
import jneqsim.process.equipment.stream
import jneqsim.process.equipment.valve
import jneqsim.process.processmodel
import jneqsim.process.util.report
import jneqsim.thermo.system
import typing



class Adjuster(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def displayResult(self) -> None: ...
    def getError(self) -> float: ...
    def getMaxAdjustedValue(self) -> float: ...
    def getMinAdjustedValue(self) -> float: ...
    def getTolerance(self) -> float: ...
    def isActivateWhenLess(self) -> bool: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setActivateWhenLess(self, boolean: bool) -> None: ...
    def setAdjustedEquipment(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def setAdjustedValueGetter(self, function: typing.Union[java.util.function.Function[jneqsim.process.equipment.ProcessEquipmentInterface, float], typing.Callable[[jneqsim.process.equipment.ProcessEquipmentInterface], float]]) -> None: ...
    @typing.overload
    def setAdjustedValueGetter(self, supplier: typing.Union[java.util.function.Supplier[float], typing.Callable[[], float]]) -> None: ...
    @typing.overload
    def setAdjustedValueSetter(self, biConsumer: typing.Union[java.util.function.BiConsumer[jneqsim.process.equipment.ProcessEquipmentInterface, float], typing.Callable[[jneqsim.process.equipment.ProcessEquipmentInterface, float], None]]) -> None: ...
    @typing.overload
    def setAdjustedValueSetter(self, consumer: typing.Union[java.util.function.Consumer[float], typing.Callable[[float], None]]) -> None: ...
    @typing.overload
    def setAdjustedVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def setAdjustedVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setAdjustedVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> None: ...
    def setError(self, double: float) -> None: ...
    def setMaxAdjustedValue(self, double: float) -> None: ...
    def setMinAdjustedValue(self, double: float) -> None: ...
    def setTargetEquipment(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    def setTargetValue(self, double: float) -> None: ...
    @typing.overload
    def setTargetValueCalculator(self, function: typing.Union[java.util.function.Function[jneqsim.process.equipment.ProcessEquipmentInterface, float], typing.Callable[[jneqsim.process.equipment.ProcessEquipmentInterface], float]]) -> None: ...
    @typing.overload
    def setTargetValueCalculator(self, supplier: typing.Union[java.util.function.Supplier[float], typing.Callable[[], float]]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> None: ...
    def setTolerance(self, double: float) -> None: ...
    def solved(self) -> bool: ...

class Calculator(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def addInputVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def addInputVariable(self, *processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    def getInputVariable(self) -> java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    def getOutputVariable(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def runAntiSurgeCalc(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def setCalculationMethod(self, runnable: typing.Union[java.lang.Runnable, typing.Callable]) -> None: ...
    @typing.overload
    def setCalculationMethod(self, biConsumer: typing.Union[java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface], typing.Callable[[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface], None]]) -> None: ...
    def setOutputVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...

class CalculatorLibrary:
    @staticmethod
    def byName(string: typing.Union[java.lang.String, str]) -> java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    @typing.overload
    @staticmethod
    def dewPointTargeting() -> java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    @typing.overload
    @staticmethod
    def dewPointTargeting(double: float) -> java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    @staticmethod
    def energyBalance() -> java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    @staticmethod
    def preset(preset: 'CalculatorLibrary.Preset') -> java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    class Preset(java.lang.Enum['CalculatorLibrary.Preset']):
        ENERGY_BALANCE: typing.ClassVar['CalculatorLibrary.Preset'] = ...
        DEW_POINT_TARGETING: typing.ClassVar['CalculatorLibrary.Preset'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'CalculatorLibrary.Preset': ...
        @staticmethod
        def values() -> typing.MutableSequence['CalculatorLibrary.Preset']: ...

class FlowRateAdjuster(jneqsim.process.equipment.TwoPortEquipment):
    desiredGasFlow: float = ...
    desiredOilFlow: float = ...
    desiredWaterFlow: float = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def setAdjustedFlowRates(self, double: float, double2: float, double3: float, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setAdjustedFlowRates(self, double: float, double2: float, string: typing.Union[java.lang.String, str]) -> None: ...

class FlowSetter(jneqsim.process.equipment.TwoPortEquipment):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def createReferenceProcess(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getGasFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getOilFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getReferenceProcess(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getWaterFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setGasFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setOilFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSeparationPT(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], string: typing.Union[java.lang.String, str], doubleArray2: typing.Union[typing.List[float], jpype.JArray], string2: typing.Union[java.lang.String, str]) -> None: ...
    def setWaterFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class GORfitter(jneqsim.process.equipment.TwoPortEquipment):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getGFV(self) -> float: ...
    def getGOR(self) -> float: ...
    @typing.overload
    def getPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getPressure(self) -> float: ...
    def getReferenceConditions(self) -> java.lang.String: ...
    @typing.overload
    def getTemperature(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getTemperature(self) -> float: ...
    def isFitAsGVF(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setFitAsGVF(self, boolean: bool) -> None: ...
    def setGOR(self, double: float) -> None: ...
    def setGVF(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    @typing.overload
    def setPressure(self, double: float) -> None: ...
    @typing.overload
    def setPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReferenceConditions(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTemperature(self, double: float) -> None: ...
    @typing.overload
    def setTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class MPFMfitter(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getGFV(self) -> float: ...
    def getGOR(self) -> float: ...
    @typing.overload
    def getPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getPressure(self) -> float: ...
    def getReferenceConditions(self) -> java.lang.String: ...
    def getReferenceFluidPackage(self) -> jneqsim.thermo.system.SystemInterface: ...
    @typing.overload
    def getTemperature(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getTemperature(self) -> float: ...
    def isFitAsGVF(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setFitAsGVF(self, boolean: bool) -> None: ...
    def setGOR(self, double: float) -> None: ...
    def setGVF(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    @typing.overload
    def setPressure(self, double: float) -> None: ...
    @typing.overload
    def setPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReferenceConditions(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReferenceFluidPackage(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    @typing.overload
    def setTemperature(self, double: float) -> None: ...
    @typing.overload
    def setTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class MoleFractionControllerUtil(jneqsim.process.equipment.TwoPortEquipment):
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    def getMolesChange(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setComponentRate(self, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str]) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setMoleFraction(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setRelativeMoleFractionReduction(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...

class NeqSimUnit(jneqsim.process.equipment.TwoPortEquipment):
    numberOfNodes: int = ...
    interfacialArea: float = ...
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def getEquipment(self) -> java.lang.String: ...
    def getID(self) -> float: ...
    def getInterfacialArea(self) -> float: ...
    def getLength(self) -> float: ...
    def getNumberOfNodes(self) -> int: ...
    def getOuterTemperature(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def runAnnular(self) -> None: ...
    def runDroplet(self) -> None: ...
    def runStratified(self) -> None: ...
    def setEquipment(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setID(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setLength(self, double: float) -> None: ...
    def setNumberOfNodes(self, int: int) -> None: ...
    def setOuterTemperature(self, double: float) -> None: ...

class PressureDrop(jneqsim.process.equipment.valve.ThrottlingValve):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setPressureDrop(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class Recycle(jneqsim.process.equipment.ProcessEquipmentBaseClass, jneqsim.process.equipment.mixer.MixerInterface):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def calcMixStreamEnthalpy(self) -> float: ...
    def compositionBalanceCheck(self) -> float: ...
    def displayResult(self) -> None: ...
    def flowBalanceCheck(self) -> float: ...
    def getCompositionTolerance(self) -> float: ...
    def getDownstreamProperty(self) -> java.util.ArrayList[java.lang.String]: ...
    def getErrorComposition(self) -> float: ...
    def getErrorFlow(self) -> float: ...
    def getErrorPressure(self) -> float: ...
    def getErrorTemperature(self) -> float: ...
    def getFlowTolerance(self) -> float: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMinimumFlow(self) -> float: ...
    def getOutStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOutletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getPriority(self) -> int: ...
    def getStream(self, int: int) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getTemperatureTolerance(self) -> float: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def guessTemperature(self) -> float: ...
    def initiateDownstreamProperties(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def mixStream(self) -> None: ...
    def pressureBalanceCheck(self) -> float: ...
    def removeInputStream(self, int: int) -> None: ...
    def replaceStream(self, int: int, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def resetIterations(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setCompositionTolerance(self, double: float) -> None: ...
    def setDownstreamProperties(self) -> None: ...
    @typing.overload
    def setDownstreamProperty(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setDownstreamProperty(self, arrayList: java.util.ArrayList[typing.Union[java.lang.String, str]]) -> None: ...
    def setErrorCompositon(self, double: float) -> None: ...
    def setErrorFlow(self, double: float) -> None: ...
    def setErrorPressure(self, double: float) -> None: ...
    def setErrorTemperature(self, double: float) -> None: ...
    def setFlowTolerance(self, double: float) -> None: ...
    def setMinimumFlow(self, double: float) -> None: ...
    def setOutletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setPressure(self, double: float) -> None: ...
    def setPriority(self, int: int) -> None: ...
    def setTemperature(self, double: float) -> None: ...
    def setTemperatureTolerance(self, double: float) -> None: ...
    def setTolerance(self, double: float) -> None: ...
    def solved(self) -> bool: ...
    def temperatureBalanceCheck(self) -> float: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...

class RecycleController(java.io.Serializable):
    def __init__(self): ...
    def addRecycle(self, recycle: Recycle) -> None: ...
    def clear(self) -> None: ...
    def doSolveRecycle(self, recycle: Recycle) -> bool: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCurrentPriorityLevel(self) -> int: ...
    def hasHigherPriorityLevel(self) -> bool: ...
    def hasLoverPriorityLevel(self) -> bool: ...
    def hashCode(self) -> int: ...
    def init(self) -> None: ...
    def isHighestPriority(self, recycle: Recycle) -> bool: ...
    def nextPriorityLevel(self) -> None: ...
    def resetPriorityLevel(self) -> None: ...
    def setCurrentPriorityLevel(self, int: int) -> None: ...
    def solvedAll(self) -> bool: ...
    def solvedCurrentPriorityLevel(self) -> bool: ...

class SetPoint(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string2: typing.Union[java.lang.String, str], processEquipmentInterface2: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def displayResult(self) -> None: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setSourceValueCalculator(self, function: typing.Union[java.util.function.Function[jneqsim.process.equipment.ProcessEquipmentInterface, float], typing.Callable[[jneqsim.process.equipment.ProcessEquipmentInterface], float]]) -> None: ...
    @typing.overload
    def setSourceVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def setSourceVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> None: ...

class Setter(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addParameter(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float) -> None: ...
    @typing.overload
    def addTargetEquipment(self, list: java.util.List[jneqsim.process.equipment.ProcessEquipmentInterface]) -> None: ...
    @typing.overload
    def addTargetEquipment(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    def getParameters(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...

class StreamSaturatorUtil(jneqsim.process.equipment.TwoPortEquipment):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def isMultiPhase(self) -> bool: ...
    def needRecalculation(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setApprachToSaturation(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setMultiPhase(self, boolean: bool) -> None: ...

class StreamTransition(jneqsim.process.equipment.TwoPortEquipment):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.util")``.

    Adjuster: typing.Type[Adjuster]
    Calculator: typing.Type[Calculator]
    CalculatorLibrary: typing.Type[CalculatorLibrary]
    FlowRateAdjuster: typing.Type[FlowRateAdjuster]
    FlowSetter: typing.Type[FlowSetter]
    GORfitter: typing.Type[GORfitter]
    MPFMfitter: typing.Type[MPFMfitter]
    MoleFractionControllerUtil: typing.Type[MoleFractionControllerUtil]
    NeqSimUnit: typing.Type[NeqSimUnit]
    PressureDrop: typing.Type[PressureDrop]
    Recycle: typing.Type[Recycle]
    RecycleController: typing.Type[RecycleController]
    SetPoint: typing.Type[SetPoint]
    Setter: typing.Type[Setter]
    StreamSaturatorUtil: typing.Type[StreamSaturatorUtil]
    StreamTransition: typing.Type[StreamTransition]
