import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.costestimation
import jneqsim.process.mechanicaldesign.tank
import typing

class TankCostEstimate(jneqsim.process.costestimation.UnitCostEstimateBaseClass):
    def __init__(
        self,
        tankMechanicalDesign: jneqsim.process.mechanicaldesign.tank.TankMechanicalDesign,
    ): ...
    @typing.overload
    def calcAnnualOperatingCost(
        self, double: float, double2: float, double3: float, int: int
    ) -> float: ...
    @typing.overload
    def calcAnnualOperatingCost(self, int: int) -> float: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getTankType(self) -> java.lang.String: ...
    def getTankVolume(self) -> float: ...
    def setDesignPressure(self, double: float) -> None: ...
    def setFloatingRoof(self, boolean: bool) -> None: ...
    def setIncludeFoundation(self, boolean: bool) -> None: ...
    def setIncludeHeatingCoils(self, boolean: bool) -> None: ...
    def setIncludeInsulation(self, boolean: bool) -> None: ...
    def setInsulationThickness(self, double: float) -> None: ...
    def setTankDiameter(self, double: float) -> None: ...
    def setTankHeight(self, double: float) -> None: ...
    def setTankType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTankVolume(self, double: float) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.costestimation.tank")``.

    TankCostEstimate: typing.Type[TankCostEstimate]
