
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.costestimation
import jneqsim.process.mechanicaldesign.compressor
import typing



class CompressorCostEstimate(jneqsim.process.costestimation.UnitCostEstimateBaseClass):
    def __init__(self, compressorMechanicalDesign: jneqsim.process.mechanicaldesign.compressor.CompressorMechanicalDesign): ...
    def calcAnnualMaintenanceCost(self) -> float: ...
    @typing.overload
    def calcAnnualOperatingCost(self, double: float, double2: float, double3: float, int: int) -> float: ...
    @typing.overload
    def calcAnnualOperatingCost(self, double: float, double2: float, double3: float) -> float: ...
    def getCompressorType(self) -> java.lang.String: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDriverType(self) -> java.lang.String: ...
    def getTotalCost(self) -> float: ...
    def setCompressorType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDriverType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setIncludeDriver(self, boolean: bool) -> None: ...
    def setIncludeIntercoolers(self, boolean: bool) -> None: ...
    def setNumberOfStages(self, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.costestimation.compressor")``.

    CompressorCostEstimate: typing.Type[CompressorCostEstimate]
