import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.design
import jneqsim.process.electricaldesign.pump
import jneqsim.process.equipment
import jneqsim.process.equipment.capacity
import jneqsim.process.equipment.compressor
import jneqsim.process.equipment.stream
import jneqsim.process.mechanicaldesign.pump
import jneqsim.process.util.report
import jneqsim.thermo.system
import typing

class PumpChartInterface(java.lang.Cloneable):
    def addCurve(
        self,
        double: float,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        doubleArray2: typing.Union[typing.List[float], jpype.JArray],
        doubleArray3: typing.Union[typing.List[float], jpype.JArray],
    ) -> None: ...
    def calculateViscosityCorrection(
        self, double: float, double2: float, double3: float, double4: float
    ) -> None: ...
    def getBestEfficiencyFlowRate(self) -> float: ...
    def getCorrectedEfficiency(
        self, double: float, double2: float, double3: float
    ) -> float: ...
    def getCorrectedHead(
        self, double: float, double2: float, double3: float
    ) -> float: ...
    def getEfficiency(self, double: float, double2: float) -> float: ...
    def getEfficiencyCorrectionFactor(self) -> float: ...
    def getFlowCorrectionFactor(self) -> float: ...
    def getFullyCorrectedHead(
        self, double: float, double2: float, double3: float, double4: float
    ) -> float: ...
    def getHead(self, double: float, double2: float) -> float: ...
    def getHeadCorrectionFactor(self) -> float: ...
    def getHeadUnit(self) -> java.lang.String: ...
    def getNPSHRequired(self, double: float, double2: float) -> float: ...
    def getOperatingStatus(self, double: float, double2: float) -> java.lang.String: ...
    def getReferenceDensity(self) -> float: ...
    def getReferenceViscosity(self) -> float: ...
    def getSpecificSpeed(self) -> float: ...
    def getSpeed(self, double: float, double2: float) -> int: ...
    def hasDensityCorrection(self) -> bool: ...
    def hasNPSHCurve(self) -> bool: ...
    def isUsePumpChart(self) -> bool: ...
    def isUseViscosityCorrection(self) -> bool: ...
    def plot(self) -> None: ...
    def setCurves(
        self,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        doubleArray2: typing.Union[typing.List[float], jpype.JArray],
        doubleArray3: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
        doubleArray4: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
        doubleArray5: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
    ) -> None: ...
    def setHeadUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setNPSHCurve(
        self,
        doubleArray: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
    ) -> None: ...
    def setReferenceConditions(
        self, double: float, double2: float, double3: float, double4: float
    ) -> None: ...
    def setReferenceDensity(self, double: float) -> None: ...
    def setReferenceViscosity(self, double: float) -> None: ...
    def setUsePumpChart(self, boolean: bool) -> None: ...
    def setUseRealKappa(self, boolean: bool) -> None: ...
    def setUseViscosityCorrection(self, boolean: bool) -> None: ...
    def useRealKappa(self) -> bool: ...

class PumpCurve(java.io.Serializable):
    flow: typing.MutableSequence[float] = ...
    head: typing.MutableSequence[float] = ...
    efficiency: typing.MutableSequence[float] = ...
    speed: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        double: float,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        doubleArray2: typing.Union[typing.List[float], jpype.JArray],
        doubleArray3: typing.Union[typing.List[float], jpype.JArray],
    ): ...

class PumpInterface(
    jneqsim.process.equipment.ProcessEquipmentInterface,
    jneqsim.process.equipment.TwoPortInterface,
):
    def equals(self, object: typing.Any) -> bool: ...
    def getEnergy(self) -> float: ...
    def getMinimumFlow(self) -> float: ...
    def getNPSHAvailable(self) -> float: ...
    def getNPSHRequired(self) -> float: ...
    def getPower(self) -> float: ...
    def hashCode(self) -> int: ...
    def isCavitating(self) -> bool: ...
    def setCheckNPSH(self, boolean: bool) -> None: ...
    def setMinimumFlow(self, double: float) -> None: ...
    def setPumpChartType(self, string: typing.Union[java.lang.String, str]) -> None: ...

class Pump(
    jneqsim.process.equipment.TwoPortEquipment,
    PumpInterface,
    jneqsim.process.equipment.capacity.CapacityConstrainedEquipment,
    jneqsim.process.design.AutoSizeable,
):
    isentropicEfficiency: float = ...
    powerSet: bool = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ): ...
    def addCapacityConstraint(
        self, capacityConstraint: jneqsim.process.equipment.capacity.CapacityConstraint
    ) -> None: ...
    @typing.overload
    def autoSize(self) -> None: ...
    @typing.overload
    def autoSize(self, double: float) -> None: ...
    @typing.overload
    def autoSize(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> None: ...
    def calculateAsCompressor(self, boolean: bool) -> None: ...
    def clearCapacityConstraints(self) -> None: ...
    def displayResult(self) -> None: ...
    def getBottleneckConstraint(
        self,
    ) -> jneqsim.process.equipment.capacity.CapacityConstraint: ...
    def getCapacityConstraints(
        self,
    ) -> java.util.Map[
        java.lang.String, jneqsim.process.equipment.capacity.CapacityConstraint
    ]: ...
    def getCapacityDuty(self) -> float: ...
    def getCapacityMax(self) -> float: ...
    def getDuty(self) -> float: ...
    def getElectricalDesign(
        self,
    ) -> jneqsim.process.electricaldesign.pump.PumpElectricalDesign: ...
    def getEnergy(self) -> float: ...
    def getEntropyProduction(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getEquipmentState(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        string3: typing.Union[java.lang.String, str],
    ) -> java.util.Map[
        java.lang.String, java.util.Map[java.lang.String, typing.Any]
    ]: ...
    def getIsentropicEfficiency(self) -> float: ...
    def getMaxUtilization(self) -> float: ...
    def getMechanicalDesign(
        self,
    ) -> jneqsim.process.mechanicaldesign.pump.PumpMechanicalDesign: ...
    def getMinimumFlow(self) -> float: ...
    def getMolarFlow(self) -> float: ...
    def getNPSHAvailable(self) -> float: ...
    def getNPSHMargin(self) -> float: ...
    def getNPSHRequired(self) -> float: ...
    def getOutTemperature(self) -> float: ...
    @typing.overload
    def getPower(self) -> float: ...
    @typing.overload
    def getPower(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getPumpChart(self) -> PumpChartInterface: ...
    def getSizingReport(self) -> java.lang.String: ...
    def getSizingReportJson(self) -> java.lang.String: ...
    def getSpeed(self) -> float: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def initElectricalDesign(self) -> None: ...
    def initMechanicalDesign(self) -> None: ...
    def isAutoSized(self) -> bool: ...
    def isCapacityExceeded(self) -> bool: ...
    def isCavitating(self) -> bool: ...
    def isCheckNPSH(self) -> bool: ...
    def isHardLimitExceeded(self) -> bool: ...
    def needRecalculation(self) -> bool: ...
    def removeCapacityConstraint(
        self, string: typing.Union[java.lang.String, str]
    ) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setCheckNPSH(self, boolean: bool) -> None: ...
    def setIsentropicEfficiency(self, double: float) -> None: ...
    def setMinimumFlow(self, double: float) -> None: ...
    def setMolarFlow(self, double: float) -> None: ...
    def setNPSHMargin(self, double: float) -> None: ...
    @typing.overload
    def setOutTemperature(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    @typing.overload
    def setOutTemperature(self, double: float) -> None: ...
    @typing.overload
    def setOutletPressure(self, double: float) -> None: ...
    @typing.overload
    def setOutletPressure(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    @typing.overload
    def setOutletTemperature(self, double: float) -> None: ...
    @typing.overload
    def setOutletTemperature(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    @typing.overload
    def setPressure(self, double: float) -> None: ...
    @typing.overload
    def setPressure(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setPumpChartType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSpeed(self, double: float) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(
        self, reportConfig: jneqsim.process.util.report.ReportConfig
    ) -> java.lang.String: ...

class PumpChart(PumpChartInterface, java.io.Serializable):
    def __init__(self): ...
    def addCurve(
        self,
        double: float,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        doubleArray2: typing.Union[typing.List[float], jpype.JArray],
        doubleArray3: typing.Union[typing.List[float], jpype.JArray],
    ) -> None: ...
    def calculateViscosityCorrection(
        self, double: float, double2: float, double3: float, double4: float
    ) -> None: ...
    def checkStoneWall(self, double: float, double2: float) -> bool: ...
    def checkSurge1(self, double: float, double2: float) -> bool: ...
    def checkSurge2(self, double: float, double2: float) -> bool: ...
    def efficiency(self, double: float, double2: float) -> float: ...
    def fitReducedCurve(self) -> None: ...
    def getBestEfficiencyFlowRate(self) -> float: ...
    def getCorrectedEfficiency(
        self, double: float, double2: float, double3: float
    ) -> float: ...
    def getCorrectedHead(
        self, double: float, double2: float, double3: float
    ) -> float: ...
    def getEfficiency(self, double: float, double2: float) -> float: ...
    def getEfficiencyCorrectionFactor(self) -> float: ...
    def getFlowCorrectionFactor(self) -> float: ...
    def getFullyCorrectedHead(
        self, double: float, double2: float, double3: float, double4: float
    ) -> float: ...
    def getHead(self, double: float, double2: float) -> float: ...
    def getHeadCorrectionFactor(self) -> float: ...
    def getHeadUnit(self) -> java.lang.String: ...
    def getNPSHRequired(self, double: float, double2: float) -> float: ...
    def getOperatingStatus(self, double: float, double2: float) -> java.lang.String: ...
    def getReferenceDensity(self) -> float: ...
    def getReferenceViscosity(self) -> float: ...
    def getSpecificSpeed(self) -> float: ...
    def getSpeed(self, double: float, double2: float) -> int: ...
    def getViscosityCorrectedEfficiency(self, double: float) -> float: ...
    def getViscosityCorrectedFlow(self, double: float) -> float: ...
    def getViscosityCorrectedHead(self, double: float) -> float: ...
    def hasDensityCorrection(self) -> bool: ...
    def hasNPSHCurve(self) -> bool: ...
    def isUsePumpChart(self) -> bool: ...
    def isUseViscosityCorrection(self) -> bool: ...
    @staticmethod
    def main(
        stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray],
    ) -> None: ...
    def plot(self) -> None: ...
    def setCurves(
        self,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        doubleArray2: typing.Union[typing.List[float], jpype.JArray],
        doubleArray3: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
        doubleArray4: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
        doubleArray5: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
    ) -> None: ...
    def setHeadUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setNPSHCurve(
        self,
        doubleArray: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
    ) -> None: ...
    def setReferenceConditions(
        self, double: float, double2: float, double3: float, double4: float
    ) -> None: ...
    def setReferenceDensity(self, double: float) -> None: ...
    def setReferenceViscosity(self, double: float) -> None: ...
    def setUsePumpChart(self, boolean: bool) -> None: ...
    def setUseRealKappa(self, boolean: bool) -> None: ...
    def setUseViscosityCorrection(self, boolean: bool) -> None: ...
    def useRealKappa(self) -> bool: ...

class PumpChartAlternativeMapLookupExtrapolate(
    jneqsim.process.equipment.compressor.CompressorChartAlternativeMapLookupExtrapolate,
    PumpChartInterface,
):
    def __init__(self): ...
    def calculateViscosityCorrection(
        self, double: float, double2: float, double3: float, double4: float
    ) -> None: ...
    def getBestEfficiencyFlowRate(self) -> float: ...
    def getCorrectedEfficiency(
        self, double: float, double2: float, double3: float
    ) -> float: ...
    def getCorrectedHead(
        self, double: float, double2: float, double3: float
    ) -> float: ...
    def getEfficiency(self, double: float, double2: float) -> float: ...
    def getEfficiencyCorrectionFactor(self) -> float: ...
    def getFlowCorrectionFactor(self) -> float: ...
    def getFullyCorrectedHead(
        self, double: float, double2: float, double3: float, double4: float
    ) -> float: ...
    def getHead(self, double: float, double2: float) -> float: ...
    def getHeadCorrectionFactor(self) -> float: ...
    def getNPSHRequired(self, double: float, double2: float) -> float: ...
    def getOperatingStatus(self, double: float, double2: float) -> java.lang.String: ...
    def getReferenceDensity(self) -> float: ...
    def getReferenceViscosity(self) -> float: ...
    def getSpecificSpeed(self) -> float: ...
    def hasDensityCorrection(self) -> bool: ...
    def hasNPSHCurve(self) -> bool: ...
    def isUsePumpChart(self) -> bool: ...
    def isUseViscosityCorrection(self) -> bool: ...
    def setNPSHCurve(
        self,
        doubleArray: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
    ) -> None: ...
    def setReferenceDensity(self, double: float) -> None: ...
    def setReferenceViscosity(self, double: float) -> None: ...
    def setUsePumpChart(self, boolean: bool) -> None: ...
    def setUseViscosityCorrection(self, boolean: bool) -> None: ...

class ESPPump(Pump):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ): ...
    def getActualHead(self) -> float: ...
    def getDesignHead(self) -> float: ...
    def getGasSeparatorEfficiency(self) -> float: ...
    def getGasVoidFraction(self) -> float: ...
    def getHeadDegradationFactor(self) -> float: ...
    def getHeadPerStage(self) -> float: ...
    def getMaxGVF(self) -> float: ...
    def getNumberOfStages(self) -> int: ...
    def getSurgingGVF(self) -> float: ...
    def hasGasSeparator(self) -> bool: ...
    def isGasLocked(self) -> bool: ...
    def isSurging(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setDegradationCoefficients(self, double: float, double2: float) -> None: ...
    def setGasSeparatorEfficiency(self, double: float) -> None: ...
    def setHasGasSeparator(self, boolean: bool) -> None: ...
    def setHeadPerStage(self, double: float) -> None: ...
    def setMaxGVF(self, double: float) -> None: ...
    def setNumberOfStages(self, int: int) -> None: ...
    def setSurgingGVF(self, double: float) -> None: ...

class JetPump(Pump):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ): ...
    def getDischargePressure(self) -> float: ...
    def getEfficiency(self) -> float: ...
    def getHeadRatio(self) -> float: ...
    def getProducedRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def headRatioAt(self, double: float) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setAreaRatio(self, double: float) -> None: ...
    def setNozzleArea(self, double: float) -> None: ...
    def setOperatingFlowRatio(self, double: float) -> None: ...
    def setPowerFluidDensity(self, double: float) -> None: ...
    def setPowerFluidPressure(self, double: float) -> None: ...

class SuckerRodPump(Pump):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ): ...
    def getActualDisplacement(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getPlungerArea(self) -> float: ...
    def getPolishedRodLoad(self) -> float: ...
    def getTheoreticalDisplacement(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setDischargePressure(self, double: float) -> None: ...
    def setFluidDensity(self, double: float) -> None: ...
    def setPlungerDiameter(self, double: float) -> None: ...
    def setPumpDepth(self, double: float) -> None: ...
    def setRodWeightPerLength(self, double: float) -> None: ...
    def setStrokeLength(self, double: float) -> None: ...
    def setStrokesPerMinute(self, double: float) -> None: ...
    def setVolumetricEfficiency(self, double: float) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.pump")``.

    ESPPump: typing.Type[ESPPump]
    JetPump: typing.Type[JetPump]
    Pump: typing.Type[Pump]
    PumpChart: typing.Type[PumpChart]
    PumpChartAlternativeMapLookupExtrapolate: typing.Type[
        PumpChartAlternativeMapLookupExtrapolate
    ]
    PumpChartInterface: typing.Type[PumpChartInterface]
    PumpCurve: typing.Type[PumpCurve]
    PumpInterface: typing.Type[PumpInterface]
    SuckerRodPump: typing.Type[SuckerRodPump]
