
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.separator
import jneqsim.process.equipment.stream
import jneqsim.process.mechanicaldesign.watertreatment
import typing



class ChemicalDoseLagModel(java.io.Serializable):
    def __init__(self): ...
    def copy(self) -> 'ChemicalDoseLagModel': ...
    def getChemicalMassKg(self) -> float: ...
    def getDecayHalfLifeHours(self) -> float: ...
    def getEffectiveDosePpm(self) -> float: ...
    def getHoldUpVolumeM3(self) -> float: ...
    def getLastInputMassFlowKgH(self) -> float: ...
    def getLastOutletMassFlowKgH(self) -> float: ...
    def getResidenceTimeHours(self, double: float) -> float: ...
    def getWaterDensityKgm3(self) -> float: ...
    def resetToSteadyState(self, double: float, double2: float) -> None: ...
    def setDecayHalfLifeHours(self, double: float) -> None: ...
    def setHoldUpVolumeM3(self, double: float) -> None: ...
    def setWaterDensityKgm3(self, double: float) -> None: ...
    def step(self, double: float, double2: float, double3: float) -> float: ...
    def toJson(self) -> java.lang.String: ...

class DemulsifierDoseResponseModel(java.io.Serializable):
    def __init__(self): ...
    def calculateRemovalFraction(self, double: float) -> float: ...
    def calibrate(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], double3: float) -> float: ...
    def getHalfEffectDosePpm(self) -> float: ...
    def getHillCoefficient(self) -> float: ...
    def getLastEffectiveRemovalFraction(self) -> float: ...
    def getLastPredictedOilInWaterMgL(self) -> float: ...
    def getLastRootMeanSquareError(self) -> float: ...
    def getMaxRemovalFraction(self) -> float: ...
    def getMinimumOilInWaterMgL(self) -> float: ...
    def getModelParameters(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getOptimumDosePpm(self) -> float: ...
    def getOverdoseSensitivity(self) -> float: ...
    def predictOilInWater(self, double: float, double2: float) -> float: ...
    def setHalfEffectDosePpm(self, double: float) -> None: ...
    def setHillCoefficient(self, double: float) -> None: ...
    def setMaxRemovalFraction(self, double: float) -> None: ...
    def setMinimumOilInWaterMgL(self, double: float) -> None: ...
    def setOptimumDosePpm(self, double: float) -> None: ...
    def setOverdoseSensitivity(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...

class GasFlotationUnit(jneqsim.process.equipment.separator.Separator):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def calcMinimumGasFlowRate(self) -> float: ...
    def calcPerStageEfficiency(self) -> float: ...
    def calcRejectFlowPerStage(self) -> float: ...
    def getDesignValidationSummary(self) -> java.lang.String: ...
    def getFlotationGasFlowRate(self) -> float: ...
    def getFlotationGasType(self) -> java.lang.String: ...
    def getInletOilConcentration(self) -> float: ...
    def getNumberOfStages(self) -> int: ...
    def getOilRemovalEfficiency(self) -> float: ...
    def getOutletOilMgL(self) -> float: ...
    def getPerStageEfficiency(self) -> float: ...
    def getRejectFlowPerStage(self) -> float: ...
    def getTotalRejectFlow(self) -> float: ...
    def getWaterFlowRate(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setFlotationGasType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInletOilConcentration(self, double: float) -> None: ...
    def setNumberOfStages(self, int: int) -> None: ...
    def setOilRemovalEfficiency(self, double: float) -> None: ...
    def setWaterFlowRate(self, double: float) -> None: ...

class Hydrocyclone(jneqsim.process.equipment.separator.Separator):
    OSPAR_OIW_LIMIT_MGL: typing.ClassVar[float] = ...
    MIN_DESIGN_DP_BAR: typing.ClassVar[float] = ...
    RECOMMENDED_DP_BAR: typing.ClassVar[float] = ...
    STANDARD_LINER_SIZES_MM: typing.ClassVar[typing.MutableSequence[float]] = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def autoSize(self, double: float) -> None: ...
    @typing.overload
    def autoSize(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def autoSize(self) -> None: ...
    def calcD50FromConditions(self) -> float: ...
    def calcEfficiencyFromDSD(self) -> float: ...
    def calcNumberOfLiners(self, double: float) -> int: ...
    def calcNumberOfVessels(self) -> int: ...
    def calcRejectRatioFromPDR(self) -> float: ...
    def calcRequiredInletPressure(self, double: float, double2: float, double3: float, double4: float) -> float: ...
    def estimateEfficiencyFromConditions(self, double: float, double2: float) -> float: ...
    def getCalculatedD50(self) -> float: ...
    def getCalculatedEfficiency(self) -> float: ...
    def getD50Microns(self) -> float: ...
    def getDesignFlowPerLinerM3h(self) -> float: ...
    def getDesignValidationSummary(self) -> java.lang.String: ...
    def getDv50Microns(self) -> float: ...
    def getEfficiencyForDropletSize(self, double: float) -> float: ...
    def getFeedFlowM3h(self) -> float: ...
    def getFlowPerLinerM3h(self) -> float: ...
    def getGeometricStdDev(self) -> float: ...
    def getHydrocycloneCapacityUtilization(self) -> float: ...
    def getInletOilConcentration(self) -> float: ...
    def getLinerDiameterMm(self) -> float: ...
    def getLinersPerVessel(self) -> int: ...
    def getMaxDesignCapacityM3h(self) -> float: ...
    def getMaxFlowPerLinerM3h(self) -> float: ...
    def getMaxOperatingFlowM3h(self) -> float: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.watertreatment.HydrocycloneMechanicalDesign: ...
    def getMinFlowPerLinerM3h(self) -> float: ...
    def getMinOperatingFlowM3h(self) -> float: ...
    def getNumberOfLiners(self) -> int: ...
    def getNumberOfSpareLiners(self) -> int: ...
    def getNumberOfVessels(self) -> int: ...
    def getOilRemovalEfficiency(self) -> float: ...
    def getOutletOilMgL(self) -> float: ...
    def getOverflowFlowM3h(self) -> float: ...
    def getPDR(self) -> float: ...
    def getPDREfficiencyFactor(self) -> float: ...
    def getPressureDropBar(self) -> float: ...
    def getRejectFlowM3h(self) -> float: ...
    def getRejectRatio(self) -> float: ...
    def getRemovedOilKgPerHour(self) -> float: ...
    def getSharpnessIndex(self) -> float: ...
    def getSizingResults(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getTurndownRatio(self) -> float: ...
    def initMechanicalDesign(self) -> None: ...
    def isDifferentialPressureAdequate(self) -> bool: ...
    def isOSPARCompliant(self) -> bool: ...
    def isOverloaded(self) -> bool: ...
    def isWithinOperatingRange(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setD50Microns(self, double: float) -> None: ...
    def setDv50Microns(self, double: float) -> None: ...
    def setGeometricStdDev(self, double: float) -> None: ...
    def setInletOilConcentration(self, double: float) -> None: ...
    def setLinerDiameterMm(self, double: float) -> None: ...
    def setLinersPerVessel(self, int: int) -> None: ...
    def setNumberOfLiners(self, int: int) -> None: ...
    def setNumberOfSpareLiners(self, int: int) -> None: ...
    def setOilDensity(self, double: float) -> None: ...
    def setOilRemovalEfficiency(self, double: float) -> None: ...
    def setPDR(self, double: float) -> None: ...
    def setPressureDrop(self, double: float) -> None: ...
    def setPressureDropBar(self, double: float) -> None: ...
    def setRejectRatio(self, double: float) -> None: ...
    def setSharpnessIndex(self, double: float) -> None: ...
    def setWaterDensity(self, double: float) -> None: ...
    def setWaterViscosity(self, double: float) -> None: ...

class OilInWaterAnalyzerDriftModel(java.io.Serializable):
    def __init__(self): ...
    def calibrate(self, double: float, double2: float, double3: float) -> None: ...
    def correctMeasuredValue(self, double: float, double2: float) -> float: ...
    def getCalibrationIntervalDays(self) -> float: ...
    def getLastMeasuredOilInWaterMgL(self) -> float: ...
    def getNoiseStandardDeviationMgL(self) -> float: ...
    def getSpanDriftFractionPerDay(self) -> float: ...
    def getSpanFactor(self) -> float: ...
    def getZeroDriftMgLPerDay(self) -> float: ...
    def getZeroOffsetMgL(self) -> float: ...
    def isCalibrationDue(self, double: float) -> bool: ...
    def measure(self, double: float, double2: float) -> float: ...
    def measureConservative(self, double: float, double2: float, double3: float) -> float: ...
    def setCalibrationIntervalDays(self, double: float) -> None: ...
    def setNoiseStandardDeviationMgL(self, double: float) -> None: ...
    def setSpanDriftFractionPerDay(self, double: float) -> None: ...
    def setSpanFactor(self, double: float) -> None: ...
    def setZeroDriftMgLPerDay(self, double: float) -> None: ...
    def setZeroOffsetMgL(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...

class OilInWaterDoseOptimizer(java.io.Serializable):
    def __init__(self): ...
    def addMonthlySample(self, double: float, double2: float) -> None: ...
    def getAnalyzerDriftModel(self) -> OilInWaterAnalyzerDriftModel: ...
    def getChemicalLagModel(self) -> ChemicalDoseLagModel: ...
    def getDoseResponseModel(self) -> DemulsifierDoseResponseModel: ...
    def getLastRecommendation(self) -> 'OilInWaterDoseOptimizer.DoseRecommendation': ...
    def getMonthlyMonitor(self) -> 'OilInWaterMonthlyComplianceMonitor': ...
    def getOptimizationHorizonHours(self) -> float: ...
    def getSafetyMarginMgL(self) -> float: ...
    @typing.overload
    def recommendDose(self, double: float, double2: float, double3: float, int: int) -> 'OilInWaterDoseOptimizer.DoseRecommendation': ...
    @typing.overload
    def recommendDose(self, double: float, double2: float, int: int) -> 'OilInWaterDoseOptimizer.DoseRecommendation': ...
    def setAnalyzerConfidenceMultiplier(self, double: float) -> None: ...
    def setAnalyzerDriftModel(self, oilInWaterAnalyzerDriftModel: OilInWaterAnalyzerDriftModel) -> None: ...
    def setChemicalLagModel(self, chemicalDoseLagModel: ChemicalDoseLagModel) -> None: ...
    def setDoseRange(self, double: float, double2: float, double3: float) -> None: ...
    def setDoseResponseModel(self, demulsifierDoseResponseModel: DemulsifierDoseResponseModel) -> None: ...
    def setMonthlyMonitor(self, oilInWaterMonthlyComplianceMonitor: 'OilInWaterMonthlyComplianceMonitor') -> None: ...
    def setOptimizationHorizonHours(self, double: float) -> None: ...
    def setSafetyMarginMgL(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    class DoseRecommendation(java.io.Serializable):
        def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, boolean: bool, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
        def getEffectiveDosePpm(self) -> float: ...
        def getMessage(self) -> java.lang.String: ...
        def getPredictedMeasuredOilInWaterMgL(self) -> float: ...
        def getPredictedOilInWaterMgL(self) -> float: ...
        def getSetpointDosePpm(self) -> float: ...
        def getStatus(self) -> java.lang.String: ...
        def getTargetOilInWaterMgL(self) -> float: ...
        def isFeasible(self) -> bool: ...

class OilInWaterMonthlyComplianceMonitor(java.io.Serializable):
    def __init__(self): ...
    def addSample(self, double: float, double2: float) -> None: ...
    def calculateStatus(self, int: int) -> 'OilInWaterMonthlyComplianceMonitor.MonthlyStatus': ...
    def getCumulativeOilMassKg(self) -> float: ...
    def getCumulativeWaterVolumeM3(self) -> float: ...
    def getDaysInMonth(self) -> int: ...
    def getMonthlyLimitMgL(self) -> float: ...
    def getProjectedDailyWaterVolumeM3(self) -> float: ...
    def getSampleCount(self) -> int: ...
    def getWeightedAverageMgL(self) -> float: ...
    def reset(self) -> None: ...
    def setDaysInMonth(self, int: int) -> None: ...
    def setMonthlyLimitMgL(self, double: float) -> None: ...
    def setProjectedDailyWaterVolumeM3(self, double: float) -> None: ...
    def setWarningFraction(self, double: float) -> None: ...
    def setWatchFraction(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    class ComplianceStatus(java.lang.Enum['OilInWaterMonthlyComplianceMonitor.ComplianceStatus']):
        NORMAL: typing.ClassVar['OilInWaterMonthlyComplianceMonitor.ComplianceStatus'] = ...
        WATCH: typing.ClassVar['OilInWaterMonthlyComplianceMonitor.ComplianceStatus'] = ...
        WARNING: typing.ClassVar['OilInWaterMonthlyComplianceMonitor.ComplianceStatus'] = ...
        EXCEEDED: typing.ClassVar['OilInWaterMonthlyComplianceMonitor.ComplianceStatus'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'OilInWaterMonthlyComplianceMonitor.ComplianceStatus': ...
        @staticmethod
        def values() -> typing.MutableSequence['OilInWaterMonthlyComplianceMonitor.ComplianceStatus']: ...
    class MonthlyStatus(java.io.Serializable):
        def __init__(self, double: float, double2: float, double3: float, double4: float, complianceStatus: 'OilInWaterMonthlyComplianceMonitor.ComplianceStatus', string: typing.Union[java.lang.String, str]): ...
        def getProjectedMonthlyWaterVolumeM3(self) -> float: ...
        def getRecommendation(self) -> java.lang.String: ...
        def getRemainingAllowedAverageMgL(self) -> float: ...
        def getRemainingWaterVolumeM3(self) -> float: ...
        def getStatus(self) -> 'OilInWaterMonthlyComplianceMonitor.ComplianceStatus': ...
        def getWeightedAverageMgL(self) -> float: ...

class ProducedWaterTreatmentTrain(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    NCS_OIW_LIMIT_MGL: typing.ClassVar[float] = ...
    OSPAR_OIW_LIMIT_MGL: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def addStage(self, waterTreatmentStage: 'ProducedWaterTreatmentTrain.WaterTreatmentStage') -> None: ...
    def clearStages(self) -> None: ...
    def generateReport(self) -> java.lang.String: ...
    def getAnnualOilDischargeTonnes(self, double: float) -> float: ...
    def getInletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOilInWaterDoseOptimizer(self) -> OilInWaterDoseOptimizer: ...
    def getOilInWaterMgL(self) -> float: ...
    def getOilInWaterPpm(self) -> float: ...
    def getOverallEfficiency(self) -> float: ...
    def getRecoveredOilM3h(self) -> float: ...
    def getRecoveredOilStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getStages(self) -> java.util.List['ProducedWaterTreatmentTrain.WaterTreatmentStage']: ...
    def getTreatedWaterStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def isCompliantWith(self, double: float) -> bool: ...
    def isDischargeCompliant(self) -> bool: ...
    def recommendDemulsifierDose(self, double: float, double2: float, int: int) -> OilInWaterDoseOptimizer.DoseRecommendation: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setInletOilConcentration(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setOilInWaterDoseOptimizer(self, oilInWaterDoseOptimizer: OilInWaterDoseOptimizer) -> None: ...
    def setStageEfficiency(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setWaterFlowRate(self, double: float) -> None: ...
    class StageType(java.lang.Enum['ProducedWaterTreatmentTrain.StageType']):
        HYDROCYCLONE: typing.ClassVar['ProducedWaterTreatmentTrain.StageType'] = ...
        FLOTATION: typing.ClassVar['ProducedWaterTreatmentTrain.StageType'] = ...
        SKIM_TANK: typing.ClassVar['ProducedWaterTreatmentTrain.StageType'] = ...
        COALESCER: typing.ClassVar['ProducedWaterTreatmentTrain.StageType'] = ...
        FILTER: typing.ClassVar['ProducedWaterTreatmentTrain.StageType'] = ...
        MEMBRANE: typing.ClassVar['ProducedWaterTreatmentTrain.StageType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ProducedWaterTreatmentTrain.StageType': ...
        @staticmethod
        def values() -> typing.MutableSequence['ProducedWaterTreatmentTrain.StageType']: ...
    class WaterTreatmentStage(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], stageType: 'ProducedWaterTreatmentTrain.StageType', double: float): ...
        def getEfficiency(self) -> float: ...
        def getInletOIW(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getOutletOIW(self) -> float: ...
        def getRecoveredOilM3h(self) -> float: ...
        def getType(self) -> 'ProducedWaterTreatmentTrain.StageType': ...
        def setEfficiency(self, double: float) -> None: ...
        def setInletOIW(self, double: float) -> None: ...
        def setOutletOIW(self, double: float) -> None: ...
        def setRecoveredOilM3h(self, double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.watertreatment")``.

    ChemicalDoseLagModel: typing.Type[ChemicalDoseLagModel]
    DemulsifierDoseResponseModel: typing.Type[DemulsifierDoseResponseModel]
    GasFlotationUnit: typing.Type[GasFlotationUnit]
    Hydrocyclone: typing.Type[Hydrocyclone]
    OilInWaterAnalyzerDriftModel: typing.Type[OilInWaterAnalyzerDriftModel]
    OilInWaterDoseOptimizer: typing.Type[OilInWaterDoseOptimizer]
    OilInWaterMonthlyComplianceMonitor: typing.Type[OilInWaterMonthlyComplianceMonitor]
    ProducedWaterTreatmentTrain: typing.Type[ProducedWaterTreatmentTrain]
