
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import com.google.gson
import java.io
import java.lang
import java.util
import jneqsim.process.logic.sis
import jneqsim.process.measurementdevice
import jneqsim.process.processmodel
import jneqsim.process.safety.risk.bowtie
import jneqsim.process.safety.risk.sis
import typing



class BarrierRegister(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addBarrier(self, safetyBarrier: 'SafetyBarrier') -> 'BarrierRegister': ...
    def addEvidence(self, documentEvidence: 'DocumentEvidence') -> 'BarrierRegister': ...
    def addPerformanceStandard(self, performanceStandard: 'PerformanceStandard') -> 'BarrierRegister': ...
    def addSafetyCriticalElement(self, safetyCriticalElement: 'SafetyCriticalElement') -> 'BarrierRegister': ...
    def getBarrier(self, string: typing.Union[java.lang.String, str]) -> 'SafetyBarrier': ...
    def getBarriers(self) -> java.util.List['SafetyBarrier']: ...
    def getBarriersForEquipment(self, string: typing.Union[java.lang.String, str]) -> java.util.List['SafetyBarrier']: ...
    def getImpairedBarriers(self) -> java.util.List['SafetyBarrier']: ...
    def getName(self) -> java.lang.String: ...
    def getPerformanceStandard(self, string: typing.Union[java.lang.String, str]) -> 'PerformanceStandard': ...
    def getPerformanceStandards(self) -> java.util.List['PerformanceStandard']: ...
    def getRegisterId(self) -> java.lang.String: ...
    def getSafetyCriticalElement(self, string: typing.Union[java.lang.String, str]) -> 'SafetyCriticalElement': ...
    def getSafetyCriticalElements(self) -> java.util.List['SafetyCriticalElement']: ...
    def linkBarrierToSafetyCriticalElement(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> bool: ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> 'BarrierRegister': ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def validate(self) -> java.util.List[java.lang.String]: ...

class DocumentEvidence(java.io.Serializable):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str], int: int, string6: typing.Union[java.lang.String, str], string7: typing.Union[java.lang.String, str], double: float): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str], int: int, string6: typing.Union[java.lang.String, str], string7: typing.Union[java.lang.String, str], double: float, string8: typing.Union[java.lang.String, str]): ...
    def getConfidence(self) -> float: ...
    def getDocumentId(self) -> java.lang.String: ...
    def getDocumentTitle(self) -> java.lang.String: ...
    def getEvidenceId(self) -> java.lang.String: ...
    def getExcerpt(self) -> java.lang.String: ...
    def getInstallationCode(self) -> java.lang.String: ...
    def getPage(self) -> int: ...
    def getRevision(self) -> java.lang.String: ...
    def getSection(self) -> java.lang.String: ...
    def getSourceReference(self) -> java.lang.String: ...
    def isTraceable(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class PerformanceStandard(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addAcceptanceCriterion(self, string: typing.Union[java.lang.String, str]) -> 'PerformanceStandard': ...
    def addEvidence(self, documentEvidence: DocumentEvidence) -> 'PerformanceStandard': ...
    def getAcceptanceCriteria(self) -> java.util.List[java.lang.String]: ...
    def getDemandMode(self) -> 'PerformanceStandard.DemandMode': ...
    def getEvidence(self) -> java.util.List[DocumentEvidence]: ...
    def getId(self) -> java.lang.String: ...
    def getProofTestIntervalHours(self) -> float: ...
    def getRequiredAvailability(self) -> float: ...
    def getResponseTimeSeconds(self) -> float: ...
    def getSafetyFunction(self) -> java.lang.String: ...
    def getTargetPfd(self) -> float: ...
    def getTitle(self) -> java.lang.String: ...
    def hasTraceableEvidence(self) -> bool: ...
    def setDemandMode(self, demandMode: 'PerformanceStandard.DemandMode') -> 'PerformanceStandard': ...
    def setProofTestIntervalHours(self, double: float) -> 'PerformanceStandard': ...
    def setRequiredAvailability(self, double: float) -> 'PerformanceStandard': ...
    def setResponseTimeSeconds(self, double: float) -> 'PerformanceStandard': ...
    def setSafetyFunction(self, string: typing.Union[java.lang.String, str]) -> 'PerformanceStandard': ...
    def setTargetPfd(self, double: float) -> 'PerformanceStandard': ...
    def setTitle(self, string: typing.Union[java.lang.String, str]) -> 'PerformanceStandard': ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def validate(self) -> java.util.List[java.lang.String]: ...
    class DemandMode(java.lang.Enum['PerformanceStandard.DemandMode']):
        LOW_DEMAND: typing.ClassVar['PerformanceStandard.DemandMode'] = ...
        HIGH_DEMAND: typing.ClassVar['PerformanceStandard.DemandMode'] = ...
        CONTINUOUS: typing.ClassVar['PerformanceStandard.DemandMode'] = ...
        OTHER: typing.ClassVar['PerformanceStandard.DemandMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PerformanceStandard.DemandMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['PerformanceStandard.DemandMode']: ...

class SafetyBarrier(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addEquipmentTag(self, string: typing.Union[java.lang.String, str]) -> 'SafetyBarrier': ...
    def addEvidence(self, documentEvidence: DocumentEvidence) -> 'SafetyBarrier': ...
    def addHazardId(self, string: typing.Union[java.lang.String, str]) -> 'SafetyBarrier': ...
    @staticmethod
    def fromBowTieBarrier(barrier: jneqsim.process.safety.risk.bowtie.BowTieModel.Barrier) -> 'SafetyBarrier': ...
    def getDescription(self) -> java.lang.String: ...
    def getEffectiveness(self) -> float: ...
    def getEvidence(self) -> java.util.List[DocumentEvidence]: ...
    def getId(self) -> java.lang.String: ...
    def getLinkedEquipmentTags(self) -> java.util.List[java.lang.String]: ...
    def getLinkedHazardIds(self) -> java.util.List[java.lang.String]: ...
    def getName(self) -> java.lang.String: ...
    def getOwner(self) -> java.lang.String: ...
    def getPerformanceStandard(self) -> PerformanceStandard: ...
    def getPfd(self) -> float: ...
    def getRiskReductionFactor(self) -> float: ...
    def getSafetyFunction(self) -> java.lang.String: ...
    def getStatus(self) -> 'SafetyBarrier.BarrierStatus': ...
    def getType(self) -> 'SafetyBarrier.BarrierType': ...
    def hasTraceableEvidence(self) -> bool: ...
    def isAvailable(self) -> bool: ...
    def setDescription(self, string: typing.Union[java.lang.String, str]) -> 'SafetyBarrier': ...
    def setEffectiveness(self, double: float) -> 'SafetyBarrier': ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> 'SafetyBarrier': ...
    def setOwner(self, string: typing.Union[java.lang.String, str]) -> 'SafetyBarrier': ...
    def setPerformanceStandard(self, performanceStandard: PerformanceStandard) -> 'SafetyBarrier': ...
    def setPfd(self, double: float) -> 'SafetyBarrier': ...
    def setSafetyFunction(self, string: typing.Union[java.lang.String, str]) -> 'SafetyBarrier': ...
    def setStatus(self, barrierStatus: 'SafetyBarrier.BarrierStatus') -> 'SafetyBarrier': ...
    def setType(self, barrierType: 'SafetyBarrier.BarrierType') -> 'SafetyBarrier': ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def validate(self) -> java.util.List[java.lang.String]: ...
    class BarrierStatus(java.lang.Enum['SafetyBarrier.BarrierStatus']):
        AVAILABLE: typing.ClassVar['SafetyBarrier.BarrierStatus'] = ...
        IMPAIRED: typing.ClassVar['SafetyBarrier.BarrierStatus'] = ...
        BYPASSED: typing.ClassVar['SafetyBarrier.BarrierStatus'] = ...
        OUT_OF_SERVICE: typing.ClassVar['SafetyBarrier.BarrierStatus'] = ...
        UNKNOWN: typing.ClassVar['SafetyBarrier.BarrierStatus'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyBarrier.BarrierStatus': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyBarrier.BarrierStatus']: ...
    class BarrierType(java.lang.Enum['SafetyBarrier.BarrierType']):
        PREVENTION: typing.ClassVar['SafetyBarrier.BarrierType'] = ...
        MITIGATION: typing.ClassVar['SafetyBarrier.BarrierType'] = ...
        BOTH: typing.ClassVar['SafetyBarrier.BarrierType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyBarrier.BarrierType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyBarrier.BarrierType']: ...

class SafetyCriticalElement(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addBarrier(self, safetyBarrier: SafetyBarrier) -> 'SafetyCriticalElement': ...
    def addEquipmentTag(self, string: typing.Union[java.lang.String, str]) -> 'SafetyCriticalElement': ...
    def addEvidence(self, documentEvidence: DocumentEvidence) -> 'SafetyCriticalElement': ...
    def getAvailableBarrierCount(self) -> int: ...
    def getBarrier(self, string: typing.Union[java.lang.String, str]) -> SafetyBarrier: ...
    def getBarriers(self) -> java.util.List[SafetyBarrier]: ...
    def getEquipmentTags(self) -> java.util.List[java.lang.String]: ...
    def getEvidence(self) -> java.util.List[DocumentEvidence]: ...
    def getId(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getOwner(self) -> java.lang.String: ...
    def getTag(self) -> java.lang.String: ...
    def getType(self) -> 'SafetyCriticalElement.ElementType': ...
    def hasImpairedBarrier(self) -> bool: ...
    def hasTraceableEvidence(self) -> bool: ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> 'SafetyCriticalElement': ...
    def setOwner(self, string: typing.Union[java.lang.String, str]) -> 'SafetyCriticalElement': ...
    def setTag(self, string: typing.Union[java.lang.String, str]) -> 'SafetyCriticalElement': ...
    def setType(self, elementType: 'SafetyCriticalElement.ElementType') -> 'SafetyCriticalElement': ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def validate(self) -> java.util.List[java.lang.String]: ...
    class ElementType(java.lang.Enum['SafetyCriticalElement.ElementType']):
        PROCESS_EQUIPMENT: typing.ClassVar['SafetyCriticalElement.ElementType'] = ...
        INSTRUMENTED_FUNCTION: typing.ClassVar['SafetyCriticalElement.ElementType'] = ...
        FIRE_PROTECTION: typing.ClassVar['SafetyCriticalElement.ElementType'] = ...
        STRUCTURAL: typing.ClassVar['SafetyCriticalElement.ElementType'] = ...
        UTILITY: typing.ClassVar['SafetyCriticalElement.ElementType'] = ...
        OTHER: typing.ClassVar['SafetyCriticalElement.ElementType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyCriticalElement.ElementType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyCriticalElement.ElementType']: ...

class SafetySystemCategory(java.lang.Enum['SafetySystemCategory']):
    FIREWATER_DELUGE: typing.ClassVar['SafetySystemCategory'] = ...
    FIRE_GAS_DETECTION: typing.ClassVar['SafetySystemCategory'] = ...
    PASSIVE_FIRE_PROTECTION: typing.ClassVar['SafetySystemCategory'] = ...
    PSD: typing.ClassVar['SafetySystemCategory'] = ...
    ESD_BLOWDOWN: typing.ClassVar['SafetySystemCategory'] = ...
    RELIEF_FLARE: typing.ClassVar['SafetySystemCategory'] = ...
    STRUCTURAL_FIREWALL: typing.ClassVar['SafetySystemCategory'] = ...
    HIPPS: typing.ClassVar['SafetySystemCategory'] = ...
    UNKNOWN: typing.ClassVar['SafetySystemCategory'] = ...
    def getDescription(self) -> java.lang.String: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetySystemCategory': ...
    @staticmethod
    def values() -> typing.MutableSequence['SafetySystemCategory']: ...

class SafetySystemDemand(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addEvidence(self, documentEvidence: DocumentEvidence) -> 'SafetySystemDemand': ...
    def getActualAvailability(self) -> float: ...
    def getActualEffectiveness(self) -> float: ...
    def getActualPfd(self) -> float: ...
    def getActualResponseTimeSeconds(self) -> float: ...
    def getBarrierId(self) -> java.lang.String: ...
    def getCapacityValue(self) -> float: ...
    def getCategory(self) -> SafetySystemCategory: ...
    def getDemandId(self) -> java.lang.String: ...
    def getDemandUnit(self) -> java.lang.String: ...
    def getDemandValue(self) -> float: ...
    def getEquipmentTag(self) -> java.lang.String: ...
    def getEvidence(self) -> java.util.List[DocumentEvidence]: ...
    def getRequiredAvailability(self) -> float: ...
    def getRequiredEffectiveness(self) -> float: ...
    def getRequiredPfd(self) -> float: ...
    def getRequiredResponseTimeSeconds(self) -> float: ...
    def getScenario(self) -> java.lang.String: ...
    def matches(self, safetyBarrier: SafetyBarrier) -> bool: ...
    def setActualAvailability(self, double: float) -> 'SafetySystemDemand': ...
    def setActualEffectiveness(self, double: float) -> 'SafetySystemDemand': ...
    def setActualPfd(self, double: float) -> 'SafetySystemDemand': ...
    def setActualResponseTimeSeconds(self, double: float) -> 'SafetySystemDemand': ...
    def setBarrierId(self, string: typing.Union[java.lang.String, str]) -> 'SafetySystemDemand': ...
    def setCapacityValue(self, double: float) -> 'SafetySystemDemand': ...
    def setCategory(self, safetySystemCategory: SafetySystemCategory) -> 'SafetySystemDemand': ...
    def setDemandUnit(self, string: typing.Union[java.lang.String, str]) -> 'SafetySystemDemand': ...
    def setDemandValue(self, double: float) -> 'SafetySystemDemand': ...
    def setEquipmentTag(self, string: typing.Union[java.lang.String, str]) -> 'SafetySystemDemand': ...
    def setRequiredAvailability(self, double: float) -> 'SafetySystemDemand': ...
    def setRequiredEffectiveness(self, double: float) -> 'SafetySystemDemand': ...
    def setRequiredPfd(self, double: float) -> 'SafetySystemDemand': ...
    def setRequiredResponseTimeSeconds(self, double: float) -> 'SafetySystemDemand': ...
    def setScenario(self, string: typing.Union[java.lang.String, str]) -> 'SafetySystemDemand': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class SafetySystemPerformanceAnalyzer:
    def __init__(self, barrierRegister: BarrierRegister): ...
    def addDemandCase(self, safetySystemDemand: SafetySystemDemand) -> 'SafetySystemPerformanceAnalyzer': ...
    def addMeasurementDevice(self, measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface) -> 'SafetySystemPerformanceAnalyzer': ...
    def addMeasurementDevices(self, processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'SafetySystemPerformanceAnalyzer': ...
    def addQuantitativeSafetyInstrumentedFunction(self, safetyInstrumentedFunction: jneqsim.process.safety.risk.sis.SafetyInstrumentedFunction) -> 'SafetySystemPerformanceAnalyzer': ...
    def addSafetyInstrumentedFunction(self, safetyInstrumentedFunction: jneqsim.process.logic.sis.SafetyInstrumentedFunction) -> 'SafetySystemPerformanceAnalyzer': ...
    def analyze(self) -> 'SafetySystemPerformanceReport': ...

class SafetySystemPerformanceReport(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addAssessment(self, barrierAssessment: 'SafetySystemPerformanceReport.BarrierAssessment') -> 'SafetySystemPerformanceReport': ...
    def countAssessments(self, verdict: 'SafetySystemPerformanceReport.Verdict') -> int: ...
    def getAssessments(self) -> java.util.List['SafetySystemPerformanceReport.BarrierAssessment']: ...
    def getName(self) -> java.lang.String: ...
    def getOverallVerdict(self) -> 'SafetySystemPerformanceReport.Verdict': ...
    def getRegisterId(self) -> java.lang.String: ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> 'SafetySystemPerformanceReport': ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class BarrierAssessment(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def addFinding(self, findingSeverity: 'SafetySystemPerformanceReport.FindingSeverity', string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'SafetySystemPerformanceReport.BarrierAssessment': ...
        def addInstrumentTag(self, string: typing.Union[java.lang.String, str]) -> 'SafetySystemPerformanceReport.BarrierAssessment': ...
        def addMetric(self, string: typing.Union[java.lang.String, str], object: typing.Any) -> 'SafetySystemPerformanceReport.BarrierAssessment': ...
        def addSafetyInstrumentedFunction(self, string: typing.Union[java.lang.String, str]) -> 'SafetySystemPerformanceReport.BarrierAssessment': ...
        def getBarrierId(self) -> java.lang.String: ...
        def getBarrierName(self) -> java.lang.String: ...
        def getCategory(self) -> SafetySystemCategory: ...
        def getDemandId(self) -> java.lang.String: ...
        def getFindings(self) -> java.util.List['SafetySystemPerformanceReport.Finding']: ...
        def getVerdict(self) -> 'SafetySystemPerformanceReport.Verdict': ...
        def setBarrierName(self, string: typing.Union[java.lang.String, str]) -> 'SafetySystemPerformanceReport.BarrierAssessment': ...
        def setCategory(self, safetySystemCategory: SafetySystemCategory) -> 'SafetySystemPerformanceReport.BarrierAssessment': ...
        def setDemandId(self, string: typing.Union[java.lang.String, str]) -> 'SafetySystemPerformanceReport.BarrierAssessment': ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Finding(java.io.Serializable):
        def __init__(self, findingSeverity: 'SafetySystemPerformanceReport.FindingSeverity', string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
        def getMessage(self) -> java.lang.String: ...
        def getRemediation(self) -> java.lang.String: ...
        def getSeverity(self) -> 'SafetySystemPerformanceReport.FindingSeverity': ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class FindingSeverity(java.lang.Enum['SafetySystemPerformanceReport.FindingSeverity']):
        INFO: typing.ClassVar['SafetySystemPerformanceReport.FindingSeverity'] = ...
        WARNING: typing.ClassVar['SafetySystemPerformanceReport.FindingSeverity'] = ...
        FAIL: typing.ClassVar['SafetySystemPerformanceReport.FindingSeverity'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetySystemPerformanceReport.FindingSeverity': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetySystemPerformanceReport.FindingSeverity']: ...
    class Verdict(java.lang.Enum['SafetySystemPerformanceReport.Verdict']):
        PASS: typing.ClassVar['SafetySystemPerformanceReport.Verdict'] = ...
        PASS_WITH_WARNINGS: typing.ClassVar['SafetySystemPerformanceReport.Verdict'] = ...
        FAIL: typing.ClassVar['SafetySystemPerformanceReport.Verdict'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetySystemPerformanceReport.Verdict': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetySystemPerformanceReport.Verdict']: ...

class StidBarrierRegisterDataSource:
    SCE_ARRAY_KEYS: typing.ClassVar[typing.MutableSequence[java.lang.String]] = ...
    BARRIER_ARRAY_KEYS: typing.ClassVar[typing.MutableSequence[java.lang.String]] = ...
    EVIDENCE_ARRAY_KEYS: typing.ClassVar[typing.MutableSequence[java.lang.String]] = ...
    @typing.overload
    def __init__(self, jsonObject: com.google.gson.JsonObject): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def getInstallationCode(self) -> java.lang.String: ...
    def read(self) -> BarrierRegister: ...

class TR2237Templates:
    @staticmethod
    def createNorsokS001Mapping() -> java.util.Map[java.lang.String, java.lang.String]: ...
    @staticmethod
    def createOnshoreTemplate() -> BarrierRegister: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.barrier")``.

    BarrierRegister: typing.Type[BarrierRegister]
    DocumentEvidence: typing.Type[DocumentEvidence]
    PerformanceStandard: typing.Type[PerformanceStandard]
    SafetyBarrier: typing.Type[SafetyBarrier]
    SafetyCriticalElement: typing.Type[SafetyCriticalElement]
    SafetySystemCategory: typing.Type[SafetySystemCategory]
    SafetySystemDemand: typing.Type[SafetySystemDemand]
    SafetySystemPerformanceAnalyzer: typing.Type[SafetySystemPerformanceAnalyzer]
    SafetySystemPerformanceReport: typing.Type[SafetySystemPerformanceReport]
    StidBarrierRegisterDataSource: typing.Type[StidBarrierRegisterDataSource]
    TR2237Templates: typing.Type[TR2237Templates]
