
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import jneqsim.process.costestimation
import jneqsim.process.processmodel
import typing



class TopsidesFacilityCostEstimator(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, processCostEstimate: jneqsim.process.costestimation.ProcessCostEstimate): ...
    @typing.overload
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def estimate(self) -> jneqsim.process.costestimation.CostEstimateResult: ...
    def getEstimateBasis(self) -> jneqsim.process.costestimation.CostEstimateBasis: ...
    def getFacilityType(self) -> 'TopsidesFacilityCostEstimator.FacilityType': ...
    def getProjectContext(self) -> 'TopsidesFacilityCostEstimator.ProjectContext': ...
    def setElectricalInstrumentationFactor(self, double: float) -> 'TopsidesFacilityCostEstimator': ...
    def setEstimateBasis(self, costEstimateBasis: jneqsim.process.costestimation.CostEstimateBasis) -> 'TopsidesFacilityCostEstimator': ...
    def setEstimateClass(self, estimateClass: jneqsim.process.costestimation.EstimateClass) -> 'TopsidesFacilityCostEstimator': ...
    def setFacilityType(self, facilityType: 'TopsidesFacilityCostEstimator.FacilityType') -> 'TopsidesFacilityCostEstimator': ...
    def setIncludeUtilitiesAndOffsites(self, boolean: bool) -> 'TopsidesFacilityCostEstimator': ...
    def setLocationFactor(self, double: float) -> 'TopsidesFacilityCostEstimator': ...
    def setPipingBulkFactor(self, double: float) -> 'TopsidesFacilityCostEstimator': ...
    def setProcessCostEstimate(self, processCostEstimate: jneqsim.process.costestimation.ProcessCostEstimate) -> 'TopsidesFacilityCostEstimator': ...
    def setProcessSystem(self, processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'TopsidesFacilityCostEstimator': ...
    def setProjectContext(self, projectContext: 'TopsidesFacilityCostEstimator.ProjectContext') -> 'TopsidesFacilityCostEstimator': ...
    class FacilityType(java.lang.Enum['TopsidesFacilityCostEstimator.FacilityType']):
        FIXED_PLATFORM: typing.ClassVar['TopsidesFacilityCostEstimator.FacilityType'] = ...
        FPSO: typing.ClassVar['TopsidesFacilityCostEstimator.FacilityType'] = ...
        SEMI_SUBMERSIBLE: typing.ClassVar['TopsidesFacilityCostEstimator.FacilityType'] = ...
        ONSHORE: typing.ClassVar['TopsidesFacilityCostEstimator.FacilityType'] = ...
        BROWNFIELD_TIE_IN: typing.ClassVar['TopsidesFacilityCostEstimator.FacilityType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        def getHookUpFactor(self) -> float: ...
        def getInstallationFactor(self) -> float: ...
        def getModuleIntegrationFactor(self) -> float: ...
        def getStructuralWeightFactor(self) -> float: ...
        def getUtilityOffsiteFactor(self) -> float: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TopsidesFacilityCostEstimator.FacilityType': ...
        @staticmethod
        def values() -> typing.MutableSequence['TopsidesFacilityCostEstimator.FacilityType']: ...
    class ProjectContext(java.lang.Enum['TopsidesFacilityCostEstimator.ProjectContext']):
        GREENFIELD: typing.ClassVar['TopsidesFacilityCostEstimator.ProjectContext'] = ...
        BROWNFIELD_MODIFICATION: typing.ClassVar['TopsidesFacilityCostEstimator.ProjectContext'] = ...
        HOST_TIE_IN: typing.ClassVar['TopsidesFacilityCostEstimator.ProjectContext'] = ...
        def getCongestionFactor(self) -> float: ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TopsidesFacilityCostEstimator.ProjectContext': ...
        @staticmethod
        def values() -> typing.MutableSequence['TopsidesFacilityCostEstimator.ProjectContext']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.costestimation.topsides")``.

    TopsidesFacilityCostEstimator: typing.Type[TopsidesFacilityCostEstimator]
