
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.diagnostics.restart
import jneqsim.process.equipment
import jneqsim.process.processmodel
import jneqsim.thermo.system
import typing



class AgentRcaDynamicProcessBenchmark:
    FEED_TOTAL_FLOW: typing.ClassVar[java.lang.String] = ...
    SEPARATOR_INLET_FLOW: typing.ClassVar[java.lang.String] = ...
    SEPARATOR_PRESSURE: typing.ClassVar[java.lang.String] = ...
    SEPARATOR_LEVEL: typing.ClassVar[java.lang.String] = ...
    GAS_EXPORT_FLOW: typing.ClassVar[java.lang.String] = ...
    LIQUID_EXPORT_FLOW: typing.ClassVar[java.lang.String] = ...
    LIQUID_FEED_FLOW: typing.ClassVar[java.lang.String] = ...
    DEFAULT_WINDOW_SAMPLES: typing.ClassVar[int] = ...
    DEFAULT_TIME_STEP_SECONDS: typing.ClassVar[float] = ...
    def __init__(self): ...
    def createDefaultHypotheses(self) -> java.util.List['RcaFaultHypothesis']: ...
    def runBenchmark(self) -> 'AgentRcaDynamicProcessBenchmark.BenchmarkResult': ...
    def runScenario(self, scenario: 'AgentRcaDynamicProcessBenchmark.Scenario') -> 'AgentRcaDynamicProcessBenchmark.ScenarioRun': ...
    class BenchmarkResult(java.io.Serializable):
        def getDiagnoses(self) -> java.util.Map['AgentRcaDynamicProcessBenchmark.Scenario', 'RcaDiagnosis']: ...
        def getDiagnosis(self, scenario: 'AgentRcaDynamicProcessBenchmark.Scenario') -> 'RcaDiagnosis': ...
        def getNormalTrainingRun(self) -> 'AgentRcaDynamicProcessBenchmark.ScenarioRun': ...
        def getScenarioRuns(self) -> java.util.Map['AgentRcaDynamicProcessBenchmark.Scenario', 'AgentRcaDynamicProcessBenchmark.ScenarioRun']: ...
    class Scenario(java.lang.Enum['AgentRcaDynamicProcessBenchmark.Scenario']):
        NORMAL: typing.ClassVar['AgentRcaDynamicProcessBenchmark.Scenario'] = ...
        PRESSURE_SENSOR_BIAS: typing.ClassVar['AgentRcaDynamicProcessBenchmark.Scenario'] = ...
        EXPORT_GAS_LEAK: typing.ClassVar['AgentRcaDynamicProcessBenchmark.Scenario'] = ...
        INLET_BLOCKAGE: typing.ClassVar['AgentRcaDynamicProcessBenchmark.Scenario'] = ...
        MULTIPHASE_SLUGGING: typing.ClassVar['AgentRcaDynamicProcessBenchmark.Scenario'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'AgentRcaDynamicProcessBenchmark.Scenario': ...
        @staticmethod
        def values() -> typing.MutableSequence['AgentRcaDynamicProcessBenchmark.Scenario']: ...
    class ScenarioRun(java.io.Serializable):
        def getFinalInletValveFoulingFraction(self) -> float: ...
        def getFinalSeparatorLevel(self) -> float: ...
        def getFinalSeparatorPressureBara(self) -> float: ...
        def getLeakedMassKg(self) -> float: ...
        def getScenario(self) -> 'AgentRcaDynamicProcessBenchmark.Scenario': ...
        def getWindow(self) -> 'RcaProcessWindow': ...

class AnomalyScanner(java.io.Serializable):
    def __init__(self): ...
    def mapTagToSymptom(self, string: typing.Union[java.lang.String, str], anomalyKind: 'AnomalyScanner.AnomalyKind') -> 'Symptom': ...
    def scan(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]]]) -> java.util.List['AnomalyScanner.Anomaly']: ...
    def setDesignLimit(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def setSpikeZThreshold(self, double: float) -> None: ...
    def setTrendR2Threshold(self, double: float) -> None: ...
    def suggestSymptom(self, list: java.util.List['AnomalyScanner.Anomaly']) -> 'Symptom': ...
    class Anomaly(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], anomalyKind: 'AnomalyScanner.AnomalyKind', double: float, double2: float, string2: typing.Union[java.lang.String, str]): ...
        def getDescription(self) -> java.lang.String: ...
        def getKind(self) -> 'AnomalyScanner.AnomalyKind': ...
        def getLatestValue(self) -> float: ...
        def getSeverity(self) -> float: ...
        def getTag(self) -> java.lang.String: ...
        def toString(self) -> java.lang.String: ...
    class AnomalyKind(java.lang.Enum['AnomalyScanner.AnomalyKind']):
        THRESHOLD_HIGH: typing.ClassVar['AnomalyScanner.AnomalyKind'] = ...
        THRESHOLD_LOW: typing.ClassVar['AnomalyScanner.AnomalyKind'] = ...
        SPIKE_HIGH: typing.ClassVar['AnomalyScanner.AnomalyKind'] = ...
        SPIKE_LOW: typing.ClassVar['AnomalyScanner.AnomalyKind'] = ...
        TREND_UP: typing.ClassVar['AnomalyScanner.AnomalyKind'] = ...
        TREND_DOWN: typing.ClassVar['AnomalyScanner.AnomalyKind'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'AnomalyScanner.AnomalyKind': ...
        @staticmethod
        def values() -> typing.MutableSequence['AnomalyScanner.AnomalyKind']: ...

class CausalTopologyModel(java.io.Serializable):
    def __init__(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], java.util.Set[typing.Union[java.lang.String, str]]], typing.Mapping[typing.Union[java.lang.String, str], java.util.Set[typing.Union[java.lang.String, str]]]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]]]): ...
    @staticmethod
    def buildDownstreamAdjacency(processSystem: jneqsim.process.processmodel.ProcessSystem) -> java.util.Map[java.lang.String, java.util.Set[java.lang.String]]: ...
    def classify(self, list: java.util.List['RelationshipGraph.Relationship']) -> java.util.List['CausalTopologyModel.CausalEdge']: ...
    class CausalEdge(java.io.Serializable):
        def __init__(self, relationship: 'RelationshipGraph.Relationship', verdict: 'CausalTopologyModel.Verdict', string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
        def getFollowerEquipment(self) -> java.lang.String: ...
        def getLeaderEquipment(self) -> java.lang.String: ...
        def getRationale(self) -> java.lang.String: ...
        def getRelationship(self) -> 'RelationshipGraph.Relationship': ...
        def getVerdict(self) -> 'CausalTopologyModel.Verdict': ...
        def toString(self) -> java.lang.String: ...
    class Verdict(java.lang.Enum['CausalTopologyModel.Verdict']):
        CAUSAL_CANDIDATE: typing.ClassVar['CausalTopologyModel.Verdict'] = ...
        LOCAL: typing.ClassVar['CausalTopologyModel.Verdict'] = ...
        COUNTER_FLOW: typing.ClassVar['CausalTopologyModel.Verdict'] = ...
        COMMON_CAUSE_OR_ARTIFACT: typing.ClassVar['CausalTopologyModel.Verdict'] = ...
        UNKNOWN: typing.ClassVar['CausalTopologyModel.Verdict'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'CausalTopologyModel.Verdict': ...
        @staticmethod
        def values() -> typing.MutableSequence['CausalTopologyModel.Verdict']: ...

class DiagnosisCase(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addDataQuality(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'DiagnosisCase': ...
    def addDataSource(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'DiagnosisCase': ...
    def addOperatingContext(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'DiagnosisCase': ...
    @staticmethod
    def fromHistorian(string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray], map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]]]) -> 'DiagnosisCase': ...
    def getCaseId(self) -> java.lang.String: ...
    def getDataQuality(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def getDataSources(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def getEquipmentName(self) -> java.lang.String: ...
    def getOperatingContext(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def getProcessModelId(self) -> java.lang.String: ...
    def getProcessModelRevision(self) -> java.lang.String: ...
    def getWindowEndEpochSeconds(self) -> float: ...
    def getWindowStartEpochSeconds(self) -> float: ...
    def setCaseId(self, string: typing.Union[java.lang.String, str]) -> 'DiagnosisCase': ...
    def setProcessModel(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'DiagnosisCase': ...
    def setTimeWindow(self, double: float, double2: float) -> 'DiagnosisCase': ...

class EvidenceCollector(java.io.Serializable):
    def __init__(self): ...
    def calculateLikelihoodScore(self, list: java.util.List['Hypothesis.Evidence']) -> float: ...
    def collectAutonomousEvidence(self, hypothesis: 'Hypothesis', list: java.util.List[AnomalyScanner.Anomaly], list2: java.util.List[CausalTopologyModel.CausalEdge]) -> java.util.List['Hypothesis.Evidence']: ...
    def collectEvidence(self, hypothesis: 'Hypothesis') -> java.util.List['Hypothesis.Evidence']: ...
    def loadFromCsv(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDesignLimit(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def setHistorianData(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]]], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setStidData(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]]]) -> None: ...

class FailurePropagationTracer(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def setCustomDelay(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setMaxCascadeDepth(self, int: int) -> None: ...
    @typing.overload
    def trace(self, string: typing.Union[java.lang.String, str]) -> 'FailurePropagationTracer.PropagationResult': ...
    @typing.overload
    def trace(self, tripEvent: 'TripEvent') -> 'FailurePropagationTracer.PropagationResult': ...
    class PropagationResult(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def getAffectedCount(self) -> int: ...
        def getEquipmentToMonitor(self) -> java.util.List[java.lang.String]: ...
        def getInitiatingEquipment(self) -> java.lang.String: ...
        def getInitiatingTripEvent(self) -> 'TripEvent': ...
        def getMaxCascadeDepth(self) -> int: ...
        def getSteps(self) -> java.util.List['FailurePropagationTracer.PropagationStep']: ...
        def getTotalProductionLossPercent(self) -> float: ...
        def toJson(self) -> java.lang.String: ...
        def toTextSummary(self) -> java.lang.String: ...
    class PropagationStep(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, int: int, string2: typing.Union[java.lang.String, str], impactLevel: 'FailurePropagationTracer.PropagationStep.ImpactLevel'): ...
        def getCascadeDepth(self) -> int: ...
        def getEffect(self) -> java.lang.String: ...
        def getEquipmentName(self) -> java.lang.String: ...
        def getEstimatedDelaySeconds(self) -> float: ...
        def getImpactLevel(self) -> 'FailurePropagationTracer.PropagationStep.ImpactLevel': ...
        def toString(self) -> java.lang.String: ...
        class ImpactLevel(java.lang.Enum['FailurePropagationTracer.PropagationStep.ImpactLevel']):
            LOW: typing.ClassVar['FailurePropagationTracer.PropagationStep.ImpactLevel'] = ...
            MEDIUM: typing.ClassVar['FailurePropagationTracer.PropagationStep.ImpactLevel'] = ...
            HIGH: typing.ClassVar['FailurePropagationTracer.PropagationStep.ImpactLevel'] = ...
            CRITICAL: typing.ClassVar['FailurePropagationTracer.PropagationStep.ImpactLevel'] = ...
            _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
            @typing.overload
            @staticmethod
            def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
            @typing.overload
            @staticmethod
            def valueOf(string: typing.Union[java.lang.String, str]) -> 'FailurePropagationTracer.PropagationStep.ImpactLevel': ...
            @staticmethod
            def values() -> typing.MutableSequence['FailurePropagationTracer.PropagationStep.ImpactLevel']: ...

class Hypothesis(java.io.Serializable, java.lang.Comparable['Hypothesis']):
    def addEvidence(self, evidence: 'Hypothesis.Evidence') -> None: ...
    def addRecommendedAction(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @staticmethod
    def builder() -> 'Hypothesis.Builder': ...
    def compareTo(self, hypothesis: 'Hypothesis') -> int: ...
    def getCategory(self) -> 'Hypothesis.Category': ...
    def getConfidenceScore(self) -> float: ...
    def getDescription(self) -> java.lang.String: ...
    def getEvidenceList(self) -> java.util.List['Hypothesis.Evidence']: ...
    def getExpectedSignals(self) -> java.util.List['Hypothesis.ExpectedSignal']: ...
    def getFailureMode(self) -> java.lang.String: ...
    def getLikelihoodScore(self) -> float: ...
    def getLikelihoodStatus(self) -> 'Hypothesis.EvaluationStatus': ...
    def getName(self) -> java.lang.String: ...
    def getPriorProbability(self) -> float: ...
    def getRecommendedActions(self) -> java.util.List[java.lang.String]: ...
    def getSimulationSummary(self) -> java.lang.String: ...
    def getVerificationComparisonCount(self) -> int: ...
    def getVerificationCoverage(self) -> float: ...
    def getVerificationScore(self) -> float: ...
    def getVerificationStatus(self) -> 'Hypothesis.EvaluationStatus': ...
    def setLikelihoodEvaluation(self, double: float, evaluationStatus: 'Hypothesis.EvaluationStatus') -> None: ...
    def setLikelihoodScore(self, double: float) -> None: ...
    def setPriorProbability(self, double: float) -> None: ...
    def setSimulationSummary(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setVerificationCoverage(self, double: float, int: int) -> None: ...
    def setVerificationEvaluation(self, double: float, evaluationStatus: 'Hypothesis.EvaluationStatus') -> None: ...
    def setVerificationScore(self, double: float) -> None: ...
    def toString(self) -> java.lang.String: ...
    class Builder:
        def __init__(self): ...
        def addAction(self, string: typing.Union[java.lang.String, str]) -> 'Hypothesis.Builder': ...
        def addEvidence(self, evidence: 'Hypothesis.Evidence') -> 'Hypothesis.Builder': ...
        def addExpectedSignal(self, string: typing.Union[java.lang.String, str], expectedBehavior: 'Hypothesis.ExpectedBehavior', double: float, string2: typing.Union[java.lang.String, str]) -> 'Hypothesis.Builder': ...
        def build(self) -> 'Hypothesis': ...
        def category(self, category: 'Hypothesis.Category') -> 'Hypothesis.Builder': ...
        def copy(self) -> 'Hypothesis.Builder': ...
        def description(self, string: typing.Union[java.lang.String, str]) -> 'Hypothesis.Builder': ...
        def failureMode(self, string: typing.Union[java.lang.String, str]) -> 'Hypothesis.Builder': ...
        def name(self, string: typing.Union[java.lang.String, str]) -> 'Hypothesis.Builder': ...
        def priorProbability(self, double: float) -> 'Hypothesis.Builder': ...
    class Category(java.lang.Enum['Hypothesis.Category']):
        MECHANICAL: typing.ClassVar['Hypothesis.Category'] = ...
        PROCESS: typing.ClassVar['Hypothesis.Category'] = ...
        CONTROL: typing.ClassVar['Hypothesis.Category'] = ...
        EXTERNAL: typing.ClassVar['Hypothesis.Category'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Hypothesis.Category': ...
        @staticmethod
        def values() -> typing.MutableSequence['Hypothesis.Category']: ...
    class EvaluationStatus(java.lang.Enum['Hypothesis.EvaluationStatus']):
        UNKNOWN: typing.ClassVar['Hypothesis.EvaluationStatus'] = ...
        EVALUATED: typing.ClassVar['Hypothesis.EvaluationStatus'] = ...
        UNSUPPORTED: typing.ClassVar['Hypothesis.EvaluationStatus'] = ...
        FAILED: typing.ClassVar['Hypothesis.EvaluationStatus'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Hypothesis.EvaluationStatus': ...
        @staticmethod
        def values() -> typing.MutableSequence['Hypothesis.EvaluationStatus']: ...
    class Evidence(java.io.Serializable):
        @typing.overload
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], evidenceStrength: 'Hypothesis.EvidenceStrength', string3: typing.Union[java.lang.String, str]): ...
        @typing.overload
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], evidenceStrength: 'Hypothesis.EvidenceStrength', string3: typing.Union[java.lang.String, str], boolean: bool, double: float, string4: typing.Union[java.lang.String, str]): ...
        def getObservation(self) -> java.lang.String: ...
        def getParameter(self) -> java.lang.String: ...
        def getSource(self) -> java.lang.String: ...
        def getSourceReference(self) -> java.lang.String: ...
        def getStrength(self) -> 'Hypothesis.EvidenceStrength': ...
        def getWeight(self) -> float: ...
        def isSupporting(self) -> bool: ...
        def toString(self) -> java.lang.String: ...
    class EvidenceStrength(java.lang.Enum['Hypothesis.EvidenceStrength']):
        STRONG: typing.ClassVar['Hypothesis.EvidenceStrength'] = ...
        MODERATE: typing.ClassVar['Hypothesis.EvidenceStrength'] = ...
        WEAK: typing.ClassVar['Hypothesis.EvidenceStrength'] = ...
        CONTRADICTORY: typing.ClassVar['Hypothesis.EvidenceStrength'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Hypothesis.EvidenceStrength': ...
        @staticmethod
        def values() -> typing.MutableSequence['Hypothesis.EvidenceStrength']: ...
    class ExpectedBehavior(java.lang.Enum['Hypothesis.ExpectedBehavior']):
        INCREASE: typing.ClassVar['Hypothesis.ExpectedBehavior'] = ...
        DECREASE: typing.ClassVar['Hypothesis.ExpectedBehavior'] = ...
        HIGH_LIMIT: typing.ClassVar['Hypothesis.ExpectedBehavior'] = ...
        LOW_LIMIT: typing.ClassVar['Hypothesis.ExpectedBehavior'] = ...
        STEP_CHANGE: typing.ClassVar['Hypothesis.ExpectedBehavior'] = ...
        CORRELATION: typing.ClassVar['Hypothesis.ExpectedBehavior'] = ...
        ANY_CHANGE: typing.ClassVar['Hypothesis.ExpectedBehavior'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Hypothesis.ExpectedBehavior': ...
        @staticmethod
        def values() -> typing.MutableSequence['Hypothesis.ExpectedBehavior']: ...
    class ExpectedSignal(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], expectedBehavior: 'Hypothesis.ExpectedBehavior', double: float, string2: typing.Union[java.lang.String, str]): ...
        def getExpectedBehavior(self) -> 'Hypothesis.ExpectedBehavior': ...
        def getParameterPattern(self) -> java.lang.String: ...
        def getRationale(self) -> java.lang.String: ...
        def getWeight(self) -> float: ...

class HypothesisGenerator(java.io.Serializable):
    def __init__(self): ...
    def generate(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, symptom: 'Symptom') -> java.util.List[Hypothesis]: ...
    def register(self, string: typing.Union[java.lang.String, str], symptom: 'Symptom', hypothesis: Hypothesis) -> None: ...

class RcaDiagnosis(java.io.Serializable):
    def getEvidence(self) -> 'RcaEvidence': ...
    def getRankedHypotheses(self) -> java.util.List['RcaDiagnosis.RankedHypothesis']: ...
    def getTopHypothesis(self) -> 'RcaDiagnosis.RankedHypothesis': ...
    def isInTop(self, string: typing.Union[java.lang.String, str], int: int) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    class RankedHypothesis(java.io.Serializable):
        def getDescription(self) -> java.lang.String: ...
        def getName(self) -> java.lang.String: ...
        def getRuleTraces(self) -> java.util.List['RcaDiagnosis.RuleTrace']: ...
        def getScore(self) -> float: ...
    class RuleTrace(java.io.Serializable):
        def getExpectation(self) -> java.lang.String: ...
        def getFirstSignal(self) -> java.lang.String: ...
        def getMetric(self) -> java.lang.String: ...
        def getObservedValue(self) -> float: ...
        def getRationale(self) -> java.lang.String: ...
        def getScale(self) -> float: ...
        def getSecondSignal(self) -> java.lang.String: ...
        def getSupport(self) -> float: ...
        def getWeight(self) -> float: ...

class RcaDiagnosisEngine:
    def __init__(self): ...
    def diagnose(self, rcaNormalOperationModel: 'RcaNormalOperationModel', rcaProcessWindow: 'RcaProcessWindow', list: java.util.List['RcaFaultHypothesis']) -> RcaDiagnosis: ...

class RcaEvidence(java.io.Serializable):
    def getCorrelationDifference(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> float: ...
    def getCorrelationEvidence(self) -> java.util.List['RcaEvidence.CorrelationEvidence']: ...
    def getMatchedRegimeId(self) -> java.lang.String: ...
    def getOverallAnomalyScore(self) -> float: ...
    def getRegimeDistance(self) -> float: ...
    @typing.overload
    def getSignalEvidence(self) -> java.util.Map[java.lang.String, 'RcaEvidence.SignalEvidence']: ...
    @typing.overload
    def getSignalEvidence(self, string: typing.Union[java.lang.String, str]) -> 'RcaEvidence.SignalEvidence': ...
    def toJson(self) -> java.lang.String: ...
    class CorrelationEvidence(java.io.Serializable):
        def getDifference(self) -> float: ...
        def getFirstSignal(self) -> java.lang.String: ...
        def getNormalCorrelation(self) -> float: ...
        def getObservedCorrelation(self) -> float: ...
        def getSecondSignal(self) -> java.lang.String: ...
    class SignalEvidence(java.io.Serializable):
        def getLagOneCorrelationDifference(self) -> float: ...
        def getLogRangeRatio(self) -> float: ...
        def getLogVarianceRatio(self) -> float: ...
        def getMeanZScore(self) -> float: ...
        def getNormalMean(self) -> float: ...
        def getNormalizedSlope(self) -> float: ...
        def getObservedMean(self) -> float: ...
        def getSignalName(self) -> java.lang.String: ...

class RcaFaultHypothesis(java.io.Serializable):
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'RcaFaultHypothesis.Builder': ...
    def getDescription(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getRules(self) -> java.util.List['RcaFaultHypothesis.EvidenceRule']: ...
    class Builder:
        def build(self) -> 'RcaFaultHypothesis': ...
        def correlationRule(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], expectation: 'RcaFaultHypothesis.Expectation', double: float, double2: float, string3: typing.Union[java.lang.String, str]) -> 'RcaFaultHypothesis.Builder': ...
        def overallRule(self, expectation: 'RcaFaultHypothesis.Expectation', double: float, double2: float, string: typing.Union[java.lang.String, str]) -> 'RcaFaultHypothesis.Builder': ...
        def signalRule(self, string: typing.Union[java.lang.String, str], metric: 'RcaFaultHypothesis.Metric', expectation: 'RcaFaultHypothesis.Expectation', double: float, double2: float, string2: typing.Union[java.lang.String, str]) -> 'RcaFaultHypothesis.Builder': ...
    class EvidenceRule(java.io.Serializable):
        def getExpectation(self) -> 'RcaFaultHypothesis.Expectation': ...
        def getFirstSignal(self) -> java.lang.String: ...
        def getMetric(self) -> 'RcaFaultHypothesis.Metric': ...
        def getRationale(self) -> java.lang.String: ...
        def getScale(self) -> float: ...
        def getSecondSignal(self) -> java.lang.String: ...
        def getWeight(self) -> float: ...
    class Expectation(java.lang.Enum['RcaFaultHypothesis.Expectation']):
        POSITIVE: typing.ClassVar['RcaFaultHypothesis.Expectation'] = ...
        NEGATIVE: typing.ClassVar['RcaFaultHypothesis.Expectation'] = ...
        LARGE_ABSOLUTE: typing.ClassVar['RcaFaultHypothesis.Expectation'] = ...
        NEAR_ZERO: typing.ClassVar['RcaFaultHypothesis.Expectation'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'RcaFaultHypothesis.Expectation': ...
        @staticmethod
        def values() -> typing.MutableSequence['RcaFaultHypothesis.Expectation']: ...
    class Metric(java.lang.Enum['RcaFaultHypothesis.Metric']):
        MEAN_Z_SCORE: typing.ClassVar['RcaFaultHypothesis.Metric'] = ...
        LOG_VARIANCE_RATIO: typing.ClassVar['RcaFaultHypothesis.Metric'] = ...
        LOG_RANGE_RATIO: typing.ClassVar['RcaFaultHypothesis.Metric'] = ...
        NORMALIZED_SLOPE: typing.ClassVar['RcaFaultHypothesis.Metric'] = ...
        ABS_CORRELATION_CHANGE: typing.ClassVar['RcaFaultHypothesis.Metric'] = ...
        OVERALL_ANOMALY: typing.ClassVar['RcaFaultHypothesis.Metric'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'RcaFaultHypothesis.Metric': ...
        @staticmethod
        def values() -> typing.MutableSequence['RcaFaultHypothesis.Metric']: ...

class RcaNormalOperationModel(java.io.Serializable):
    def analyze(self, rcaProcessWindow: 'RcaProcessWindow') -> RcaEvidence: ...
    @staticmethod
    def fit(list: java.util.List['RcaProcessWindow']) -> 'RcaNormalOperationModel': ...
    def getRegimeIds(self) -> java.util.List[java.lang.String]: ...
    def getSignalNames(self) -> java.util.List[java.lang.String]: ...

class RcaProcessWindow(java.io.Serializable):
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], double: float) -> 'RcaProcessWindow.Builder': ...
    def getOperatingConditions(self) -> java.util.Map[java.lang.String, float]: ...
    def getRegimeId(self) -> java.lang.String: ...
    def getSampleCount(self) -> int: ...
    def getSampleIntervalSeconds(self) -> float: ...
    def getSignal(self, string: typing.Union[java.lang.String, str]) -> typing.MutableSequence[float]: ...
    def getSignalNames(self) -> java.util.List[java.lang.String]: ...
    class Builder:
        def build(self) -> 'RcaProcessWindow': ...
        def operatingCondition(self, string: typing.Union[java.lang.String, str], double: float) -> 'RcaProcessWindow.Builder': ...
        def signal(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> 'RcaProcessWindow.Builder': ...

class RelationshipGraph(java.io.Serializable):
    def __init__(self): ...
    def analyze(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]]]) -> java.util.List['RelationshipGraph.Relationship']: ...
    def setMaxLagSamples(self, int: int) -> None: ...
    def setMinAbsCorrelation(self, double: float) -> None: ...
    def setTimestamps(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setUseRankCorrelation(self, boolean: bool) -> None: ...
    def toTextReport(self, list: java.util.List['RelationshipGraph.Relationship']) -> java.lang.String: ...
    class Direction(java.lang.Enum['RelationshipGraph.Direction']):
        LEADS: typing.ClassVar['RelationshipGraph.Direction'] = ...
        SYNCHRONOUS: typing.ClassVar['RelationshipGraph.Direction'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'RelationshipGraph.Direction': ...
        @staticmethod
        def values() -> typing.MutableSequence['RelationshipGraph.Direction']: ...
    class Relationship(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], direction: 'RelationshipGraph.Direction', int: int, double: float, double2: float, double3: float): ...
        def getCorrelation(self) -> float: ...
        def getDirection(self) -> 'RelationshipGraph.Direction': ...
        def getLagSamples(self) -> int: ...
        def getLagSeconds(self) -> float: ...
        def getSource(self) -> java.lang.String: ...
        def getTarget(self) -> java.lang.String: ...
        def getZeroLagCorrelation(self) -> float: ...
        def toString(self) -> java.lang.String: ...

class RootCauseAnalyzer(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem, string: typing.Union[java.lang.String, str]): ...
    def analyze(self) -> 'RootCauseReport': ...
    @typing.overload
    def analyzeAutonomous(self) -> 'RootCauseReport': ...
    @typing.overload
    def analyzeAutonomous(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]]]) -> 'RootCauseReport': ...
    def getDiagnosisCase(self) -> DiagnosisCase: ...
    def getLastAnomalies(self) -> java.util.List[AnomalyScanner.Anomaly]: ...
    def getLastCausalEdges(self) -> java.util.List[CausalTopologyModel.CausalEdge]: ...
    def getLastRelationships(self) -> java.util.List[RelationshipGraph.Relationship]: ...
    def setDesignLimit(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def setDiagnosisCase(self, diagnosisCase: DiagnosisCase) -> None: ...
    def setHistorianData(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]]], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setHypothesisGenerator(self, hypothesisGenerator: HypothesisGenerator) -> None: ...
    def setSimulationEnabled(self, boolean: bool) -> None: ...
    def setStidData(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]]]) -> None: ...
    def setSymptom(self, symptom: 'Symptom') -> None: ...

class RootCauseReport(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], symptom: 'Symptom'): ...
    def getAnalysisTimestamp(self) -> int: ...
    def getDataPointsAnalyzed(self) -> int: ...
    def getDiagnosisCase(self) -> DiagnosisCase: ...
    def getEquipmentName(self) -> java.lang.String: ...
    def getEquipmentType(self) -> java.lang.String: ...
    def getHypothesesAboveThreshold(self, double: float) -> java.util.List[Hypothesis]: ...
    def getParametersAnalyzed(self) -> int: ...
    def getRankedHypotheses(self) -> java.util.List[Hypothesis]: ...
    def getSymptom(self) -> 'Symptom': ...
    def getTopHypothesis(self) -> Hypothesis: ...
    def setAnalysisSummary(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDataPointsAnalyzed(self, int: int) -> None: ...
    def setDiagnosisCase(self, diagnosisCase: DiagnosisCase) -> None: ...
    def setHypotheses(self, list: java.util.List[Hypothesis]) -> None: ...
    def setParametersAnalyzed(self, int: int) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toResultsMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def toTextReport(self) -> java.lang.String: ...

class SimulationVerifier(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem, string: typing.Union[java.lang.String, str]): ...
    def setHistorianData(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]]]) -> None: ...
    def verify(self, hypothesis: Hypothesis) -> None: ...
    def verifyWithResult(self, hypothesis: Hypothesis) -> 'SimulationVerifier.VerificationResult': ...
    class VerificationResult(java.io.Serializable):
        def getComparisonCount(self) -> int: ...
        def getCoverage(self) -> float: ...
        def getScore(self) -> float: ...
        def getStatus(self) -> Hypothesis.EvaluationStatus: ...
        def getSummary(self) -> java.lang.String: ...

class Symptom(java.lang.Enum['Symptom']):
    TRIP: typing.ClassVar['Symptom'] = ...
    HIGH_VIBRATION: typing.ClassVar['Symptom'] = ...
    SEAL_FAILURE: typing.ClassVar['Symptom'] = ...
    HIGH_TEMPERATURE: typing.ClassVar['Symptom'] = ...
    LOW_EFFICIENCY: typing.ClassVar['Symptom'] = ...
    PRESSURE_DEVIATION: typing.ClassVar['Symptom'] = ...
    FLOW_DEVIATION: typing.ClassVar['Symptom'] = ...
    HIGH_POWER: typing.ClassVar['Symptom'] = ...
    SURGE_EVENT: typing.ClassVar['Symptom'] = ...
    FOULING: typing.ClassVar['Symptom'] = ...
    ABNORMAL_NOISE: typing.ClassVar['Symptom'] = ...
    LIQUID_CARRYOVER: typing.ClassVar['Symptom'] = ...
    def getDescription(self) -> java.lang.String: ...
    def getRelatedCategories(self) -> java.util.List[java.lang.String]: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'Symptom': ...
    @staticmethod
    def values() -> typing.MutableSequence['Symptom']: ...

class TripEvent(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float, boolean: bool, double3: float, severity: 'TripEvent.Severity'): ...
    def getActualValue(self) -> float: ...
    def getDeviation(self) -> float: ...
    def getEquipmentName(self) -> java.lang.String: ...
    def getParameterName(self) -> java.lang.String: ...
    def getSeverity(self) -> 'TripEvent.Severity': ...
    def getSimulationTimeSeconds(self) -> float: ...
    def getThreshold(self) -> float: ...
    def getTimestampMillis(self) -> int: ...
    def isHighTrip(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toString(self) -> java.lang.String: ...
    class Severity(java.lang.Enum['TripEvent.Severity']):
        LOW: typing.ClassVar['TripEvent.Severity'] = ...
        MEDIUM: typing.ClassVar['TripEvent.Severity'] = ...
        HIGH: typing.ClassVar['TripEvent.Severity'] = ...
        CRITICAL: typing.ClassVar['TripEvent.Severity'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TripEvent.Severity': ...
        @staticmethod
        def values() -> typing.MutableSequence['TripEvent.Severity']: ...

class TripEventDetector(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def addTripCondition(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, boolean: bool, severity: TripEvent.Severity) -> None: ...
    def autoConfigureFromDesignLimits(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]]]) -> None: ...
    def check(self, double: float) -> java.util.List[TripEvent]: ...
    def checkCurrentState(self) -> java.util.List[TripEvent]: ...
    def getDetectedTrips(self) -> java.util.List[TripEvent]: ...
    def getFirstTrip(self) -> TripEvent: ...
    def getTripCount(self) -> int: ...
    def hasTrips(self) -> bool: ...
    def reset(self) -> None: ...
    def setDeadbandFraction(self, double: float) -> None: ...
    def setFirstTripOnly(self, boolean: bool) -> None: ...
    def toJson(self) -> java.lang.String: ...

class ValveSeatLeakageAssessment(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> 'ValveSeatLeakageAssessment.Result': ...
    def setDischargeCoefficient(self, double: float) -> 'ValveSeatLeakageAssessment': ...
    def setPressureBuildUpTest(self, double: float, double2: float, double3: float) -> 'ValveSeatLeakageAssessment': ...
    def setStandingBleedTest(self, double: float, double2: float) -> 'ValveSeatLeakageAssessment': ...
    def setTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> 'ValveSeatLeakageAssessment': ...
    def setUpstreamPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> 'ValveSeatLeakageAssessment': ...
    class Result(java.io.Serializable):
        def __init__(self): ...
        def getDischargeCoefficient(self) -> float: ...
        def getEquivalentGapAreaM2(self) -> float: ...
        def getEquivalentGapDiameterMm(self) -> float: ...
        def getLeakRateKgPerSec(self) -> float: ...
        def getLeakRateSm3PerHour(self) -> float: ...
        def getSeverity(self) -> 'ValveSeatLeakageAssessment.Severity': ...
        def getStandardDensityKgPerSm3(self) -> float: ...
        def getTagName(self) -> java.lang.String: ...
        def getTemperatureK(self) -> float: ...
        def getTestMode(self) -> 'ValveSeatLeakageAssessment.TestMode': ...
        def getUpstreamPressureBara(self) -> float: ...
        def isBleedChoked(self) -> bool: ...
        def providesPositiveIsolation(self) -> bool: ...
        def toJson(self) -> java.lang.String: ...
    class Severity(java.lang.Enum['ValveSeatLeakageAssessment.Severity']):
        NEGLIGIBLE: typing.ClassVar['ValveSeatLeakageAssessment.Severity'] = ...
        SEAT_WEEPAGE: typing.ClassVar['ValveSeatLeakageAssessment.Severity'] = ...
        SEAT_DAMAGE: typing.ClassVar['ValveSeatLeakageAssessment.Severity'] = ...
        GROSS_LEAK: typing.ClassVar['ValveSeatLeakageAssessment.Severity'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ValveSeatLeakageAssessment.Severity': ...
        @staticmethod
        def values() -> typing.MutableSequence['ValveSeatLeakageAssessment.Severity']: ...
    class TestMode(java.lang.Enum['ValveSeatLeakageAssessment.TestMode']):
        PRESSURE_BUILD_UP: typing.ClassVar['ValveSeatLeakageAssessment.TestMode'] = ...
        STANDING_BLEED: typing.ClassVar['ValveSeatLeakageAssessment.TestMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ValveSeatLeakageAssessment.TestMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['ValveSeatLeakageAssessment.TestMode']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.diagnostics")``.

    AgentRcaDynamicProcessBenchmark: typing.Type[AgentRcaDynamicProcessBenchmark]
    AnomalyScanner: typing.Type[AnomalyScanner]
    CausalTopologyModel: typing.Type[CausalTopologyModel]
    DiagnosisCase: typing.Type[DiagnosisCase]
    EvidenceCollector: typing.Type[EvidenceCollector]
    FailurePropagationTracer: typing.Type[FailurePropagationTracer]
    Hypothesis: typing.Type[Hypothesis]
    HypothesisGenerator: typing.Type[HypothesisGenerator]
    RcaDiagnosis: typing.Type[RcaDiagnosis]
    RcaDiagnosisEngine: typing.Type[RcaDiagnosisEngine]
    RcaEvidence: typing.Type[RcaEvidence]
    RcaFaultHypothesis: typing.Type[RcaFaultHypothesis]
    RcaNormalOperationModel: typing.Type[RcaNormalOperationModel]
    RcaProcessWindow: typing.Type[RcaProcessWindow]
    RelationshipGraph: typing.Type[RelationshipGraph]
    RootCauseAnalyzer: typing.Type[RootCauseAnalyzer]
    RootCauseReport: typing.Type[RootCauseReport]
    SimulationVerifier: typing.Type[SimulationVerifier]
    Symptom: typing.Type[Symptom]
    TripEvent: typing.Type[TripEvent]
    TripEventDetector: typing.Type[TripEventDetector]
    ValveSeatLeakageAssessment: typing.Type[ValveSeatLeakageAssessment]
    restart: jneqsim.process.diagnostics.restart.__module_protocol__
