changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - breaking
    - title: New Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Dependencies
      labels:
        - dependencies
    - title: Maintenance
      labels:
        - maintenance
        - chore
    - title: Other Changes
      labels:
        - "*"
