
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import typing



class ChemicalInjectionNozzlePerformance(java.io.Serializable):
    QUILL_MIN_GAS_VELOCITY: typing.ClassVar[float] = ...
    DROPLET_BAND_MIN_MICRON: typing.ClassVar[float] = ...
    DROPLET_PREFERRED_MIN_MICRON: typing.ClassVar[float] = ...
    DROPLET_PREFERRED_MAX_MICRON: typing.ClassVar[float] = ...
    DROPLET_BAND_MAX_MICRON: typing.ClassVar[float] = ...
    def __init__(self): ...
    def evaluate(self) -> None: ...
    def getCoverageFraction(self) -> float: ...
    def getDispersionIndex(self) -> float: ...
    def getDropletSettlingVelocity(self) -> float: ...
    def getGasVelocity(self) -> float: ...
    def getInterfacialArea(self) -> float: ...
    def getSauterMeanDiameter(self) -> float: ...
    def getSauterMeanDiameterMicron(self) -> float: ...
    def getSuspensionIndex(self) -> float: ...
    def getWallImpingementLength(self) -> float: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isEvaluated(self) -> bool: ...
    def setChemicalDensity(self, double: float) -> None: ...
    def setChemicalViscosity(self, double: float) -> None: ...
    def setChemicalVolumeFlow(self, double: float) -> None: ...
    def setEvaluationLength(self, double: float) -> None: ...
    def setGasDensity(self, double: float) -> None: ...
    def setGasViscosity(self, double: float) -> None: ...
    def setGasVolumeFlow(self, double: float) -> None: ...
    def setInjectionDevice(self, injectionDevice: 'ChemicalInjectionNozzlePerformance.InjectionDevice') -> None: ...
    def setInsertionDepth(self, double: float) -> None: ...
    def setNozzleDifferentialPressure(self, double: float) -> None: ...
    def setPipeInnerDiameter(self, double: float) -> None: ...
    def setSprayConeAngle(self, double: float) -> None: ...
    def setSurfaceTension(self, double: float) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class InjectionDevice(java.lang.Enum['ChemicalInjectionNozzlePerformance.InjectionDevice']):
        PLAIN_QUILL: typing.ClassVar['ChemicalInjectionNozzlePerformance.InjectionDevice'] = ...
        FULL_CONE_NOZZLE: typing.ClassVar['ChemicalInjectionNozzlePerformance.InjectionDevice'] = ...
        HOLLOW_CONE_NOZZLE: typing.ClassVar['ChemicalInjectionNozzlePerformance.InjectionDevice'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ChemicalInjectionNozzlePerformance.InjectionDevice': ...
        @staticmethod
        def values() -> typing.MutableSequence['ChemicalInjectionNozzlePerformance.InjectionDevice']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.chemistry.injection")``.

    ChemicalInjectionNozzlePerformance: typing.Type[ChemicalInjectionNozzlePerformance]
