
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import jneqsim.process.electricaldesign
import jneqsim.process.equipment
import typing



class CompressorElectricalDesign(jneqsim.process.electricaldesign.ElectricalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def getCoolingFanKW(self) -> float: ...
    def getInstrumentationKW(self) -> float: ...
    def getLubeOilHeaterKW(self) -> float: ...
    def getLubeOilPumpKW(self) -> float: ...
    def getSealGasSystemKW(self) -> float: ...
    def getTotalAuxiliaryKW(self) -> float: ...
    def getTotalConnectedLoadKW(self) -> float: ...
    def isHasAirCooling(self) -> bool: ...
    def isHasLubeOilSystem(self) -> bool: ...
    def isHasSealGasSystem(self) -> bool: ...
    def readDesignSpecifications(self) -> None: ...
    def setHasAirCooling(self, boolean: bool) -> None: ...
    def setHasLubeOilSystem(self, boolean: bool) -> None: ...
    def setHasSealGasSystem(self, boolean: bool) -> None: ...
    def setInstrumentationKW(self, double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.electricaldesign.compressor")``.

    CompressorElectricalDesign: typing.Type[CompressorElectricalDesign]
