
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import neqsim
import jneqsim.process.equipment.adsorber
import jneqsim.process.equipment.compressor
import jneqsim.process.equipment.reactor
import jneqsim.process.equipment.splitter
import jneqsim.process.equipment.stream
import jneqsim.process.processmodel
import typing



class ATRHydrogenPlantBuilder(jneqsim.process.hydrogen.HydrogenPlantBuilderBase):
    def __init__(self): ...
    def build(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def setFeedTemperature(self, double: float) -> 'ATRHydrogenPlantBuilder': ...
    def setIncludePsa(self, boolean: bool) -> 'ATRHydrogenPlantBuilder': ...
    def setMethaneFeedMolePerSec(self, double: float) -> 'ATRHydrogenPlantBuilder': ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> 'ATRHydrogenPlantBuilder': ...
    def setOxygenToCarbonRatio(self, double: float) -> 'ATRHydrogenPlantBuilder': ...
    def setPressure(self, double: float) -> 'ATRHydrogenPlantBuilder': ...
    def setSteamToCarbonRatio(self, double: float) -> 'ATRHydrogenPlantBuilder': ...

class BlueHydrogenPlantBuilder(jneqsim.process.hydrogen.SMRHydrogenPlantBuilder):
    def __init__(self): ...
    def build(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getCaptureReadinessSummary(self) -> java.lang.String: ...
    def getCapturedCo2MassFlowKgPerHour(self) -> float: ...
    def getCarbonIntensityKgCO2PerKgH2(self) -> float: ...
    def getCo2CaptureFraction(self) -> float: ...
    def getCo2CaptureUnit(self) -> jneqsim.process.equipment.splitter.ComponentCaptureUnit: ...
    def getCo2ExportCompressor(self) -> jneqsim.process.equipment.compressor.Compressor: ...
    def getCo2ExportStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getGrossCarbonIntensityKgCO2PerKgH2(self) -> float: ...
    def getGrossCo2EquivalentKgPerHour(self) -> float: ...
    def getH2Dryer(self) -> jneqsim.process.equipment.splitter.ComponentCaptureUnit: ...
    def getH2ExportCompressor(self) -> jneqsim.process.equipment.compressor.Compressor: ...
    def getH2ProductStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getHighTemperatureShiftReactor(self) -> jneqsim.process.equipment.reactor.WaterGasShiftReactor: ...
    def getHydrogenProductMassFlowKgPerHour(self) -> float: ...
    def getLowTemperatureShiftReactor(self) -> jneqsim.process.equipment.reactor.WaterGasShiftReactor: ...
    def getPsaCascade(self) -> jneqsim.process.equipment.adsorber.PSACascade: ...
    def getReformerFurnace(self) -> jneqsim.process.equipment.reactor.ReformerFurnace: ...
    def getResidualCo2EquivalentKgPerHour(self) -> float: ...
    def getResults(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def setCo2CaptureFraction(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setCo2ExportPressure(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setFeedTemperature(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setFuelToFeedMethaneRatio(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setH2DryerWaterRemovalFraction(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setH2ExportPressure(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setHighTemperatureShiftTemperature(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setIncludePsa(self, boolean: bool) -> 'BlueHydrogenPlantBuilder': ...
    def setLowTemperatureShiftTemperature(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setMethaneFeedMolePerSec(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> 'BlueHydrogenPlantBuilder': ...
    def setPressure(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setPsaConfiguration(self, cascadeConfiguration: jneqsim.process.equipment.adsorber.PSACascade.CascadeConfiguration) -> 'BlueHydrogenPlantBuilder': ...
    def setPsaPerBedRecoveryTarget(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setReformingTemperature(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setShiftedGasCoolerOutletTemperature(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def setSteamToCarbonRatio(self, double: float) -> 'BlueHydrogenPlantBuilder': ...
    def toJson(self) -> java.lang.String: ...

class POXHydrogenPlantBuilder(jneqsim.process.hydrogen.HydrogenPlantBuilderBase):
    def __init__(self): ...
    def build(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def setIncludePsa(self, boolean: bool) -> 'POXHydrogenPlantBuilder': ...
    def setMethaneFeedMolePerSec(self, double: float) -> 'POXHydrogenPlantBuilder': ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> 'POXHydrogenPlantBuilder': ...
    def setOxygenToCarbonRatio(self, double: float) -> 'POXHydrogenPlantBuilder': ...
    def setSteamToCarbonRatio(self, double: float) -> 'POXHydrogenPlantBuilder': ...

class SMRHydrogenPlantBuilder(jneqsim.process.hydrogen.HydrogenPlantBuilderBase):
    def __init__(self): ...
    def build(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def setFeedTemperature(self, double: float) -> 'SMRHydrogenPlantBuilder': ...
    def setFuelToFeedMethaneRatio(self, double: float) -> 'SMRHydrogenPlantBuilder': ...
    def setIncludePsa(self, boolean: bool) -> 'SMRHydrogenPlantBuilder': ...
    def setMethaneFeedMolePerSec(self, double: float) -> 'SMRHydrogenPlantBuilder': ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> 'SMRHydrogenPlantBuilder': ...
    def setPressure(self, double: float) -> 'SMRHydrogenPlantBuilder': ...
    def setPsaConfiguration(self, cascadeConfiguration: jneqsim.process.equipment.adsorber.PSACascade.CascadeConfiguration) -> 'SMRHydrogenPlantBuilder': ...
    def setPsaPerBedRecoveryTarget(self, double: float) -> 'SMRHydrogenPlantBuilder': ...
    def setReformingTemperature(self, double: float) -> 'SMRHydrogenPlantBuilder': ...
    def setSteamToCarbonRatio(self, double: float) -> 'SMRHydrogenPlantBuilder': ...

class HydrogenPlantBuilderBase: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.hydrogen")``.

    ATRHydrogenPlantBuilder: typing.Type[ATRHydrogenPlantBuilder]
    BlueHydrogenPlantBuilder: typing.Type[BlueHydrogenPlantBuilder]
    HydrogenPlantBuilderBase: typing.Type[HydrogenPlantBuilderBase]
    POXHydrogenPlantBuilder: typing.Type[POXHydrogenPlantBuilder]
    SMRHydrogenPlantBuilder: typing.Type[SMRHydrogenPlantBuilder]
