import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.thermo.system
import jneqsim.thermodynamicoperations
import org.jfree.chart
import typing

class HPTphaseEnvelope(jneqsim.thermodynamicoperations.BaseOperation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def displayResult(self) -> None: ...
    def getJFreeChart(
        self, string: typing.Union[java.lang.String, str]
    ) -> org.jfree.chart.JFreeChart: ...
    def getPoints(
        self, int: int
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getResultTable(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class PTphaseEnvelope(jneqsim.thermodynamicoperations.BaseOperation):
    points2: typing.MutableSequence[typing.MutableSequence[float]] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        string: typing.Union[java.lang.String, str],
        double: float,
        double2: float,
        boolean: bool,
    ): ...
    def addData(
        self,
        string: typing.Union[java.lang.String, str],
        doubleArray: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
    ) -> None: ...
    def calcHydrateLine(self) -> None: ...
    def displayResult(self) -> None: ...
    def get(
        self, string: typing.Union[java.lang.String, str]
    ) -> typing.MutableSequence[float]: ...
    def getJFreeChart(
        self, string: typing.Union[java.lang.String, str]
    ) -> org.jfree.chart.JFreeChart: ...
    def getPoints(
        self, int: int
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getResultTable(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def isBubblePointFirst(self) -> bool: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def setBubblePointFirst(self, boolean: bool) -> None: ...
    def tempKWilson(self, double: float, double2: float) -> float: ...

class PTphaseEnvelope1(jneqsim.thermodynamicoperations.BaseOperation):
    points2: typing.MutableSequence[typing.MutableSequence[float]] = ...
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        string: typing.Union[java.lang.String, str],
        double: float,
        double2: float,
        boolean: bool,
    ): ...
    def displayResult(self) -> None: ...
    def get(
        self, string: typing.Union[java.lang.String, str]
    ) -> typing.MutableSequence[float]: ...
    def getJFreeChart(
        self, string: typing.Union[java.lang.String, str]
    ) -> org.jfree.chart.JFreeChart: ...
    def getPoints(
        self, int: int
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getResultTable(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def isBubblePointFirst(self) -> bool: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def setBubblePointFirst(self, boolean: bool) -> None: ...

class PTphaseEnvelopeMay(jneqsim.thermodynamicoperations.BaseOperation):
    points2: typing.MutableSequence[typing.MutableSequence[float]] = ...
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        string: typing.Union[java.lang.String, str],
        double: float,
        double2: float,
        boolean: bool,
    ): ...
    def addData(
        self,
        string: typing.Union[java.lang.String, str],
        doubleArray: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
    ) -> None: ...
    def calcHydrateLine(self) -> None: ...
    def displayResult(self) -> None: ...
    def get(
        self, string: typing.Union[java.lang.String, str]
    ) -> typing.MutableSequence[float]: ...
    def getJFreeChart(
        self, string: typing.Union[java.lang.String, str]
    ) -> org.jfree.chart.JFreeChart: ...
    def getPoints(
        self, int: int
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getResultTable(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def isBubblePointFirst(self) -> bool: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def setBubblePointFirst(self, boolean: bool) -> None: ...
    def tempKWilson(self, double: float, double2: float) -> float: ...

class PTphaseEnvelopeNew(jneqsim.thermodynamicoperations.BaseOperation):
    points2: typing.MutableSequence[typing.MutableSequence[float]] = ...
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        string: typing.Union[java.lang.String, str],
        double: float,
        double2: float,
    ): ...
    def displayResult(self) -> None: ...
    def get(
        self, string: typing.Union[java.lang.String, str]
    ) -> typing.MutableSequence[float]: ...
    def getJFreeChart(
        self, string: typing.Union[java.lang.String, str]
    ) -> org.jfree.chart.JFreeChart: ...
    def getPoints(
        self, int: int
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getResultTable(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class PTphaseEnvelopeNew2(jneqsim.thermodynamicoperations.BaseOperation):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        string: typing.Union[java.lang.String, str],
        double: float,
        double2: float,
        boolean: bool,
    ): ...
    def calcHydrateLine(self) -> None: ...
    def displayResult(self) -> None: ...
    def get(
        self, string: typing.Union[java.lang.String, str]
    ) -> typing.MutableSequence[float]: ...
    def getJFreeChart(
        self, string: typing.Union[java.lang.String, str]
    ) -> org.jfree.chart.JFreeChart: ...
    def getResultTable(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def isBubblePointFirst(self) -> bool: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def setBubblePointFirst(self, boolean: bool) -> None: ...
    def tempKWilson(self, double: float, double2: float) -> float: ...

class PTphaseEnvelopeNew3(jneqsim.thermodynamicoperations.OperationInterface):
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
    ): ...
    def addData(
        self,
        string: typing.Union[java.lang.String, str],
        doubleArray: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
    ) -> None: ...
    def coarse(self) -> None: ...
    def displayResult(self) -> None: ...
    def findBettaTransitionsAndRefine(self) -> None: ...
    def get(
        self, string: typing.Union[java.lang.String, str]
    ) -> typing.MutableSequence[float]: ...
    def getBettaMatrix(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getBettaTransitionRegion(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[bool]]: ...
    def getCricondenbar(self) -> float: ...
    def getCricondentherm(self) -> float: ...
    def getDewPointPressures(self) -> typing.MutableSequence[float]: ...
    def getDewPointTemperatures(self) -> typing.MutableSequence[float]: ...
    def getJFreeChart(
        self, string: typing.Union[java.lang.String, str]
    ) -> org.jfree.chart.JFreeChart: ...
    def getPhaseMatrix(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getPoints(
        self, int: int
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getPressurePhaseEnvelope(self) -> java.util.List[float]: ...
    def getPressures(self) -> typing.MutableSequence[float]: ...
    def getRefinedTransitionPoints(
        self,
    ) -> java.util.List[typing.MutableSequence[float]]: ...
    def getResultTable(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def getTemperaturePhaseEnvelope(self) -> java.util.List[float]: ...
    def getTemperatures(self) -> typing.MutableSequence[float]: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class SysNewtonRhapsonPhaseEnvelope(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        int: int,
        int2: int,
    ): ...
    def calcCrit(self) -> None: ...
    def calcInc(self, int: int) -> None: ...
    def calcInc2(self, int: int) -> None: ...
    def calc_x_y(self) -> None: ...
    def findSpecEq(self) -> None: ...
    def findSpecEqInit(self) -> None: ...
    def getNpCrit(self) -> int: ...
    def init(self) -> None: ...
    def setJac(self) -> None: ...
    def setJac2(self) -> None: ...
    def setfvec(self) -> None: ...
    def setfvec22(self) -> None: ...
    def setu(self) -> None: ...
    def sign(self, double: float, double2: float) -> float: ...
    def solve(self, int: int) -> None: ...
    def useAsSpecEq(self, int: int) -> None: ...

class SysNewtonRhapsonPhaseEnvelope2(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcInc(self, int: int) -> None: ...
    def calcInc2(self, int: int) -> None: ...
    def critPassed(self) -> bool: ...
    def findSpecEq(self) -> None: ...
    def findSpecEqInit(self) -> None: ...
    def getNpCrit(self) -> int: ...
    def init(self) -> None: ...
    @staticmethod
    def main(
        stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]
    ) -> None: ...
    def setJac(self) -> None: ...
    def setfvec(self) -> None: ...
    def setu(self) -> None: ...
    def sign(self, double: float, double2: float) -> float: ...
    def solve(self, int: int) -> None: ...

class CricondenBarFlash(PTphaseEnvelope):
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        string: typing.Union[java.lang.String, str],
        double: float,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        doubleArray2: typing.Union[typing.List[float], jpype.JArray],
        doubleArray3: typing.Union[typing.List[float], jpype.JArray],
    ): ...
    def funcP(self) -> None: ...
    def funcT(self) -> None: ...
    def init(self) -> None: ...
    def run(self) -> None: ...
    def setNewK(self) -> None: ...
    def setNewX(self) -> None: ...

class CricondenThermFlash(PTphaseEnvelope):
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        string: typing.Union[java.lang.String, str],
        double: float,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        doubleArray2: typing.Union[typing.List[float], jpype.JArray],
        doubleArray3: typing.Union[typing.List[float], jpype.JArray],
    ): ...
    def funcP(self) -> None: ...
    def funcT(self) -> None: ...
    def init(self) -> None: ...
    def run(self) -> None: ...
    def setNewK(self) -> None: ...
    def setNewX(self) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.thermodynamicoperations.phaseenvelopeops.multicomponentenvelopeops")``.

    CricondenBarFlash: typing.Type[CricondenBarFlash]
    CricondenThermFlash: typing.Type[CricondenThermFlash]
    HPTphaseEnvelope: typing.Type[HPTphaseEnvelope]
    PTphaseEnvelope: typing.Type[PTphaseEnvelope]
    PTphaseEnvelope1: typing.Type[PTphaseEnvelope1]
    PTphaseEnvelopeMay: typing.Type[PTphaseEnvelopeMay]
    PTphaseEnvelopeNew: typing.Type[PTphaseEnvelopeNew]
    PTphaseEnvelopeNew2: typing.Type[PTphaseEnvelopeNew2]
    PTphaseEnvelopeNew3: typing.Type[PTphaseEnvelopeNew3]
    SysNewtonRhapsonPhaseEnvelope: typing.Type[SysNewtonRhapsonPhaseEnvelope]
    SysNewtonRhapsonPhaseEnvelope2: typing.Type[SysNewtonRhapsonPhaseEnvelope2]
