
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jpype
import jneqsim.statistics.parameterfitting.nonlinearparameterfitting
import jneqsim.thermo.system
import jneqsim.thermodynamicoperations
import typing



class SimulationInterface:
    def getBaseThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getOptimizer(self) -> jneqsim.statistics.parameterfitting.nonlinearparameterfitting.LevenbergMarquardt: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def run(self) -> None: ...
    def setTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setThermoSystem(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...

class BasePVTsimulation(SimulationInterface):
    thermoOps: jneqsim.thermodynamicoperations.ThermodynamicOperations = ...
    pressures: typing.MutableSequence[float] = ...
    temperature: float = ...
    optimizer: jneqsim.statistics.parameterfitting.nonlinearparameterfitting.LevenbergMarquardt = ...
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def getBaseThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getOptimizer(self) -> jneqsim.statistics.parameterfitting.nonlinearparameterfitting.LevenbergMarquardt: ...
    def getPressure(self) -> float: ...
    def getPressures(self) -> typing.MutableSequence[float]: ...
    def getSaturationPressure(self) -> float: ...
    def getSaturationTemperature(self) -> float: ...
    def getTemperature(self) -> float: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getZsaturation(self) -> float: ...
    def run(self) -> None: ...
    def setExperimentalData(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    def setPressure(self, double: float) -> None: ...
    def setPressures(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def setTemperature(self, double: float) -> None: ...
    @typing.overload
    def setTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setThermoSystem(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...

class ConstantMassExpansion(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcSaturationConditions(self) -> None: ...
    def calculateAAD(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    def calculateRelativeVolumeDeviation(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calculateZFactorQC(self) -> typing.MutableSequence[float]: ...
    def generateQCReport(self) -> java.lang.String: ...
    def getBg(self) -> typing.MutableSequence[float]: ...
    def getDensity(self) -> typing.MutableSequence[float]: ...
    def getIsoThermalCompressibility(self) -> typing.MutableSequence[float]: ...
    def getLiquidRelativeVolume(self) -> typing.MutableSequence[float]: ...
    def getRelativeVolume(self) -> typing.MutableSequence[float]: ...
    def getSaturationIsoThermalCompressibility(self) -> float: ...
    def getSaturationPressure(self) -> float: ...
    def getViscosity(self) -> typing.MutableSequence[float]: ...
    def getYfactor(self) -> typing.MutableSequence[float]: ...
    def getZgas(self) -> typing.MutableSequence[float]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def runCalc(self) -> None: ...
    def runTuning(self) -> None: ...
    def setTemperaturesAndPressures(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def validateMassBalance(self, double: float) -> bool: ...

class ConstantVolumeDepletion(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcSaturationConditions(self) -> None: ...
    def calculateGasDensityQC(self) -> typing.MutableSequence[float]: ...
    def calculateKValues(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def calculateOilDensityQC(self) -> typing.MutableSequence[float]: ...
    def generateQCReport(self) -> java.lang.String: ...
    def getCummulativeMolePercDepleted(self) -> typing.MutableSequence[float]: ...
    def getLiquidDropoutCurve(self) -> typing.MutableSequence[float]: ...
    def getLiquidRelativeVolume(self) -> typing.MutableSequence[float]: ...
    def getRelativeVolume(self) -> typing.MutableSequence[float]: ...
    def getSaturationPressure(self) -> float: ...
    def getZgas(self) -> typing.MutableSequence[float]: ...
    def getZmix(self) -> typing.MutableSequence[float]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def runCalc(self) -> None: ...
    def runTuning(self) -> None: ...
    def setTemperaturesAndPressures(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def validateMaterialBalance(self, double: float) -> bool: ...

class DensitySim(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def getAqueousDensity(self) -> typing.MutableSequence[float]: ...
    def getGasDensity(self) -> typing.MutableSequence[float]: ...
    def getOilDensity(self) -> typing.MutableSequence[float]: ...
    def getWaxFraction(self) -> typing.MutableSequence[float]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def runCalc(self) -> None: ...
    def runTuning(self) -> None: ...
    def setTemperaturesAndPressures(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class DifferentialLiberation(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcSaturationConditions(self) -> None: ...
    def calculateMaterialBalanceResidual(self) -> float: ...
    def generateQCReport(self) -> java.lang.String: ...
    def getBg(self) -> typing.MutableSequence[float]: ...
    def getBo(self) -> typing.MutableSequence[float]: ...
    def getGasStandardVolume(self) -> typing.MutableSequence[float]: ...
    def getOilDensity(self) -> typing.MutableSequence[float]: ...
    def getRelGasGravity(self) -> typing.MutableSequence[float]: ...
    def getRelativeVolume(self) -> typing.MutableSequence[float]: ...
    def getRs(self) -> typing.MutableSequence[float]: ...
    def getSaturationPressure(self) -> float: ...
    def getShrinkage(self) -> typing.MutableSequence[float]: ...
    def getZgas(self) -> typing.MutableSequence[float]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def runCalc(self) -> None: ...
    def validateBgMonotonicity(self) -> bool: ...
    def validateBoMonotonicity(self) -> bool: ...
    def validateOilDensityMonotonicity(self) -> bool: ...
    def validateRsMonotonicity(self) -> bool: ...

class GOR(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def getBofactor(self) -> typing.MutableSequence[float]: ...
    def getGOR(self) -> typing.MutableSequence[float]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def runCalc(self) -> None: ...
    def setTemperaturesAndPressures(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class MMPCalculator(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, systemInterface2: jneqsim.thermo.system.SystemInterface): ...
    def generateReport(self) -> java.lang.String: ...
    def getMMP(self) -> float: ...
    def getMiscibilityMechanism(self) -> 'MMPCalculator.MiscibilityMechanism': ...
    def getPressures(self) -> typing.MutableSequence[float]: ...
    def getRecoveries(self) -> typing.MutableSequence[float]: ...
    def run(self) -> None: ...
    def setMethod(self, calculationMethod: 'MMPCalculator.CalculationMethod') -> None: ...
    def setNumberOfPressurePoints(self, int: int) -> None: ...
    def setPressureRange(self, double: float, double2: float) -> None: ...
    def setRecoveryThreshold(self, double: float) -> None: ...
    def setSlimTubeParameters(self, int: int, double: float) -> None: ...
    @typing.overload
    def setTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTemperature(self, double: float) -> None: ...
    class CalculationMethod(java.lang.Enum['MMPCalculator.CalculationMethod']):
        SLIM_TUBE: typing.ClassVar['MMPCalculator.CalculationMethod'] = ...
        KEY_TIE_LINE: typing.ClassVar['MMPCalculator.CalculationMethod'] = ...
        RISING_BUBBLE: typing.ClassVar['MMPCalculator.CalculationMethod'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'MMPCalculator.CalculationMethod': ...
        @staticmethod
        def values() -> typing.MutableSequence['MMPCalculator.CalculationMethod']: ...
    class MiscibilityMechanism(java.lang.Enum['MMPCalculator.MiscibilityMechanism']):
        FIRST_CONTACT: typing.ClassVar['MMPCalculator.MiscibilityMechanism'] = ...
        VAPORIZING: typing.ClassVar['MMPCalculator.MiscibilityMechanism'] = ...
        CONDENSING: typing.ClassVar['MMPCalculator.MiscibilityMechanism'] = ...
        COMBINED: typing.ClassVar['MMPCalculator.MiscibilityMechanism'] = ...
        IMMISCIBLE: typing.ClassVar['MMPCalculator.MiscibilityMechanism'] = ...
        UNKNOWN: typing.ClassVar['MMPCalculator.MiscibilityMechanism'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'MMPCalculator.MiscibilityMechanism': ...
        @staticmethod
        def values() -> typing.MutableSequence['MMPCalculator.MiscibilityMechanism']: ...

class MultiStageSeparatorTest(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def addSeparatorStage(self, double: float, double2: float) -> None: ...
    @typing.overload
    def addSeparatorStage(self, double: float, double2: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def addStockTankStage(self) -> None: ...
    def clearStages(self) -> None: ...
    def generateReport(self) -> java.lang.String: ...
    def getBo(self) -> float: ...
    def getNumberOfStages(self) -> int: ...
    def getRs(self) -> float: ...
    def getStageResults(self) -> java.util.List['MultiStageSeparatorTest.SeparatorStageResult']: ...
    def getStockTankAPIGravity(self) -> float: ...
    def getStockTankOilDensity(self) -> float: ...
    def getTotalGOR(self) -> float: ...
    @typing.overload
    def optimizeFirstStageSeparator(self) -> 'MultiStageSeparatorTest.OptimizationResult': ...
    @typing.overload
    def optimizeFirstStageSeparator(self, double: float, double2: float, int: int, double3: float, double4: float, int2: int) -> 'MultiStageSeparatorTest.OptimizationResult': ...
    def run(self) -> None: ...
    def setReservoirConditions(self, double: float, double2: float) -> None: ...
    def setTypicalThreeStage(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    class OptimizationResult:
        def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float): ...
        def getApiAtOptimum(self) -> float: ...
        def getBoAtOptimum(self) -> float: ...
        def getGorAtOptimum(self) -> float: ...
        def getMaximumOilRecovery(self) -> float: ...
        def getOptimalPressure(self) -> float: ...
        def getOptimalTemperature(self) -> float: ...
        def toString(self) -> java.lang.String: ...
    class SeparatorStage:
        @typing.overload
        def __init__(self, double: float, double2: float): ...
        @typing.overload
        def __init__(self, double: float, double2: float, string: typing.Union[java.lang.String, str]): ...
        def getName(self) -> java.lang.String: ...
        def getPressure(self) -> float: ...
        def getTemperature(self) -> float: ...
    class SeparatorStageResult:
        def __init__(self, int: int, string: typing.Union[java.lang.String, str], double: float, double2: float): ...
        def getCumulativeGOR(self) -> float: ...
        def getGasDensity(self) -> float: ...
        def getGasMW(self) -> float: ...
        def getGasRate(self) -> float: ...
        def getGasZFactor(self) -> float: ...
        def getOilDensity(self) -> float: ...
        def getOilMW(self) -> float: ...
        def getOilRate(self) -> float: ...
        def getOilViscosity(self) -> float: ...
        def getPressure(self) -> float: ...
        def getStageGOR(self) -> float: ...
        def getStageName(self) -> java.lang.String: ...
        def getStageNumber(self) -> int: ...
        def getTemperature(self) -> float: ...
        def toString(self) -> java.lang.String: ...

class SaturationPressure(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcSaturationPressure(self) -> float: ...
    def getSaturationPressure(self) -> float: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def run(self) -> None: ...

class SaturationTemperature(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcSaturationTemperature(self) -> float: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def run(self) -> None: ...

class SeparatorTest(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def getBofactor(self) -> typing.MutableSequence[float]: ...
    def getGOR(self) -> typing.MutableSequence[float]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def runCalc(self) -> None: ...
    def setSeparatorConditions(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class SlimTubeSim(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, systemInterface2: jneqsim.thermo.system.SystemInterface): ...
    def getNumberOfSlimTubeNodes(self) -> int: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def run(self) -> None: ...
    def setNumberOfSlimTubeNodes(self, int: int) -> None: ...

class SwellingTest(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def getPressures(self) -> typing.MutableSequence[float]: ...
    def getRelativeOilVolume(self) -> typing.MutableSequence[float]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def runCalc(self) -> None: ...
    def setCummulativeMolePercentGasInjected(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setInjectionGas(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    def setPressures(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setRelativeOilVolume(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class ViscositySim(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def getAqueousViscosity(self) -> typing.MutableSequence[float]: ...
    def getGasViscosity(self) -> typing.MutableSequence[float]: ...
    def getOilViscosity(self) -> typing.MutableSequence[float]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def runCalc(self) -> None: ...
    def runTuning(self) -> None: ...
    def setTemperaturesAndPressures(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class ViscosityWaxOilSim(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def getAqueousViscosity(self) -> typing.MutableSequence[float]: ...
    def getGasViscosity(self) -> typing.MutableSequence[float]: ...
    def getOilViscosity(self) -> typing.MutableSequence[float]: ...
    def getOilwaxDispersionViscosity(self) -> typing.MutableSequence[float]: ...
    def getShareRate(self) -> typing.MutableSequence[float]: ...
    def getWaxFraction(self) -> typing.MutableSequence[float]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def runCalc(self) -> None: ...
    def runTuning(self) -> None: ...
    def setShareRate(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setTemperaturesAndPressures(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class WaxFractionSim(BasePVTsimulation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def getBofactor(self) -> typing.MutableSequence[float]: ...
    def getGOR(self) -> typing.MutableSequence[float]: ...
    def getWaxFraction(self) -> typing.MutableSequence[float]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def runCalc(self) -> None: ...
    def runTuning(self) -> None: ...
    def setTemperaturesAndPressures(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.pvtsimulation.simulation")``.

    BasePVTsimulation: typing.Type[BasePVTsimulation]
    ConstantMassExpansion: typing.Type[ConstantMassExpansion]
    ConstantVolumeDepletion: typing.Type[ConstantVolumeDepletion]
    DensitySim: typing.Type[DensitySim]
    DifferentialLiberation: typing.Type[DifferentialLiberation]
    GOR: typing.Type[GOR]
    MMPCalculator: typing.Type[MMPCalculator]
    MultiStageSeparatorTest: typing.Type[MultiStageSeparatorTest]
    SaturationPressure: typing.Type[SaturationPressure]
    SaturationTemperature: typing.Type[SaturationTemperature]
    SeparatorTest: typing.Type[SeparatorTest]
    SimulationInterface: typing.Type[SimulationInterface]
    SlimTubeSim: typing.Type[SlimTubeSim]
    SwellingTest: typing.Type[SwellingTest]
    ViscositySim: typing.Type[ViscositySim]
    ViscosityWaxOilSim: typing.Type[ViscosityWaxOilSim]
    WaxFractionSim: typing.Type[WaxFractionSim]
