import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jpype
import jneqsim.process.processmodel
import jneqsim.thermo.system
import typing

class OilGasProcessSimulationOptimization:
    def __init__(self): ...
    def configureCompressorCharts(self, double: float, double2: float) -> None: ...
    def createProcess(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getInputParameters(
        self,
    ) -> "OilGasProcessSimulationOptimization.ProcessInputParameters": ...
    def getOilProcess(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getOutput(
        self,
    ) -> "OilGasProcessSimulationOptimization.ProcessOutputResults": ...
    def getWellFluid(self) -> jneqsim.thermo.system.SystemInterface: ...
    @staticmethod
    def main(
        stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray],
    ) -> None: ...
    def optimizeMaxProduction(
        self,
        processInputParameters: "OilGasProcessSimulationOptimization.ProcessInputParameters",
    ) -> "OilGasProcessSimulationOptimization.MaxProductionResult": ...
    def optimizePowerConsumption(
        self,
        processInputParameters: "OilGasProcessSimulationOptimization.ProcessInputParameters",
    ) -> "OilGasProcessSimulationOptimization.ProcessInputParameters": ...
    @typing.overload
    def runSimulation(
        self,
    ) -> "OilGasProcessSimulationOptimization.ProcessOutputResults": ...
    @typing.overload
    def runSimulation(
        self,
        processInputParameters: "OilGasProcessSimulationOptimization.ProcessInputParameters",
    ) -> "OilGasProcessSimulationOptimization.ProcessOutputResults": ...
    def setInputParameters(
        self,
        processInputParameters: "OilGasProcessSimulationOptimization.ProcessInputParameters",
    ) -> None: ...
    def updateInput(
        self,
        processInputParameters: "OilGasProcessSimulationOptimization.ProcessInputParameters",
    ) -> None: ...

    class MaxProductionResult:
        def __init__(self): ...
        def getBottleneckSeparator(self) -> java.lang.String: ...
        def getBottleneckUtilization(self) -> float: ...
        def getCompressorSpeedUtilization(
            self,
        ) -> java.util.Map[java.lang.String, float]: ...
        def getLimitingFeedRate(self) -> float: ...
        def getLimitingSeparator(self) -> java.lang.String: ...
        def getLimitingUtilization(self) -> float: ...
        def getMaxFeedRate(self) -> float: ...
        def getMaxGasExportRate(self) -> float: ...
        def getMaxOilExportRate(self) -> float: ...
        def getOptimalParams(
            self,
        ) -> "OilGasProcessSimulationOptimization.ProcessInputParameters": ...
        def getSeparatorCapacities(self) -> java.util.Map[java.lang.String, float]: ...
        def getSuccessfulIterations(self) -> int: ...
        def getTotalFailures(self) -> int: ...
        def setBottleneckSeparator(
            self, string: typing.Union[java.lang.String, str]
        ) -> None: ...
        def setBottleneckUtilization(self, double: float) -> None: ...
        def setCompressorSpeedUtilization(
            self,
            map: typing.Union[
                java.util.Map[typing.Union[java.lang.String, str], float],
                typing.Mapping[typing.Union[java.lang.String, str], float],
            ],
        ) -> None: ...
        def setLimitingFeedRate(self, double: float) -> None: ...
        def setLimitingSeparator(
            self, string: typing.Union[java.lang.String, str]
        ) -> None: ...
        def setLimitingUtilization(self, double: float) -> None: ...
        def setMaxFeedRate(self, double: float) -> None: ...
        def setMaxGasExportRate(self, double: float) -> None: ...
        def setMaxOilExportRate(self, double: float) -> None: ...
        def setOptimalParams(
            self,
            processInputParameters: "OilGasProcessSimulationOptimization.ProcessInputParameters",
        ) -> None: ...
        def setSeparatorCapacities(
            self,
            map: typing.Union[
                java.util.Map[typing.Union[java.lang.String, str], float],
                typing.Mapping[typing.Union[java.lang.String, str], float],
            ],
        ) -> None: ...
        def setSuccessfulIterations(self, int: int) -> None: ...
        def setTotalFailures(self, int: int) -> None: ...
        def toString(self) -> java.lang.String: ...

    class ProcessInputParameters:
        def __init__(self): ...
        def copyFrom(
            self,
            processInputParameters: "OilGasProcessSimulationOptimization.ProcessInputParameters",
        ) -> None: ...
        def getFeedRate(self) -> float: ...
        def getP_gas_export(self) -> float: ...
        def getP_oil_export(self) -> float: ...
        def getPcomp1(self) -> float: ...
        def getPsep1(self) -> float: ...
        def getPsep2(self) -> float: ...
        def getPsep3(self) -> float: ...
        def getT_gas_export(self) -> float: ...
        def getT_oil_export(self) -> float: ...
        def getTrefrig(self) -> float: ...
        def getTscrub1(self) -> float: ...
        def getTscrub2(self) -> float: ...
        def getTscrub3(self) -> float: ...
        def getTscrub4(self) -> float: ...
        def getTsep1(self) -> float: ...
        def getTsep2(self) -> float: ...
        def getTsep3(self) -> float: ...
        def getdP_20_HA_01(self) -> float: ...
        def getdP_20_HA_02(self) -> float: ...
        def getdP_20_HA_03(self) -> float: ...
        def getdP_21_HA_01(self) -> float: ...
        def getdP_23_HA_01(self) -> float: ...
        def getdP_23_HA_02(self) -> float: ...
        def getdP_23_HA_03(self) -> float: ...
        def getdP_24_HA_01(self) -> float: ...
        def getdP_25_HA_01(self) -> float: ...
        def getdP_25_HA_02(self) -> float: ...
        def getdP_27_HA_01(self) -> float: ...
        def setFeedRate(self, double: float) -> None: ...
        def setP_gas_export(self, double: float) -> None: ...
        def setP_oil_export(self, double: float) -> None: ...
        def setPcomp1(self, double: float) -> None: ...
        def setPsep1(self, double: float) -> None: ...
        def setPsep2(self, double: float) -> None: ...
        def setPsep3(self, double: float) -> None: ...
        def setT_gas_export(self, double: float) -> None: ...
        def setT_oil_export(self, double: float) -> None: ...
        def setTrefrig(self, double: float) -> None: ...
        def setTscrub1(self, double: float) -> None: ...
        def setTscrub2(self, double: float) -> None: ...
        def setTscrub3(self, double: float) -> None: ...
        def setTscrub4(self, double: float) -> None: ...
        def setTsep1(self, double: float) -> None: ...
        def setTsep2(self, double: float) -> None: ...
        def setTsep3(self, double: float) -> None: ...
        def setdP_20_HA_01(self, double: float) -> None: ...
        def setdP_20_HA_02(self, double: float) -> None: ...
        def setdP_20_HA_03(self, double: float) -> None: ...
        def setdP_21_HA_01(self, double: float) -> None: ...
        def setdP_23_HA_01(self, double: float) -> None: ...
        def setdP_23_HA_02(self, double: float) -> None: ...
        def setdP_23_HA_03(self, double: float) -> None: ...
        def setdP_24_HA_01(self, double: float) -> None: ...
        def setdP_25_HA_01(self, double: float) -> None: ...
        def setdP_25_HA_02(self, double: float) -> None: ...
        def setdP_27_HA_01(self, double: float) -> None: ...

    class ProcessOutputResults:
        def __init__(self): ...
        def getCompressorMaxSpeeds(self) -> java.util.Map[java.lang.String, float]: ...
        def getCompressorPowers(self) -> java.util.Map[java.lang.String, float]: ...
        def getCompressorSpeedUtilization(
            self,
        ) -> java.util.Map[java.lang.String, float]: ...
        def getCompressorSpeeds(self) -> java.util.Map[java.lang.String, float]: ...
        def getFuelGasRate(self) -> float: ...
        def getGasExportRate(self) -> float: ...
        def getMassBalance(self) -> float: ...
        def getOilExportRate(self) -> float: ...
        def getSeparatorCapacityUtilization(
            self,
        ) -> java.util.Map[java.lang.String, float]: ...
        def getSeparatorLoadFactors(self) -> java.util.Map[java.lang.String, float]: ...
        def getStreamFlowRates(self) -> java.util.Map[java.lang.String, float]: ...
        def getTotalCompressorPower(self) -> float: ...
        def getTotalPowerConsumption(self) -> float: ...
        def getTotalPumpPower(self) -> float: ...
        def isAnyCompressorOverspeed(self) -> bool: ...
        def isAnySeparatorOverloaded(self) -> bool: ...
        def setAnyCompressorOverspeed(self, boolean: bool) -> None: ...
        def setAnySeparatorOverloaded(self, boolean: bool) -> None: ...
        def setCompressorMaxSpeeds(
            self,
            map: typing.Union[
                java.util.Map[typing.Union[java.lang.String, str], float],
                typing.Mapping[typing.Union[java.lang.String, str], float],
            ],
        ) -> None: ...
        def setCompressorPowers(
            self,
            map: typing.Union[
                java.util.Map[typing.Union[java.lang.String, str], float],
                typing.Mapping[typing.Union[java.lang.String, str], float],
            ],
        ) -> None: ...
        def setCompressorSpeedUtilization(
            self,
            map: typing.Union[
                java.util.Map[typing.Union[java.lang.String, str], float],
                typing.Mapping[typing.Union[java.lang.String, str], float],
            ],
        ) -> None: ...
        def setCompressorSpeeds(
            self,
            map: typing.Union[
                java.util.Map[typing.Union[java.lang.String, str], float],
                typing.Mapping[typing.Union[java.lang.String, str], float],
            ],
        ) -> None: ...
        def setFuelGasRate(self, double: float) -> None: ...
        def setGasExportRate(self, double: float) -> None: ...
        def setMassBalance(self, double: float) -> None: ...
        def setOilExportRate(self, double: float) -> None: ...
        def setSeparatorCapacityUtilization(
            self,
            map: typing.Union[
                java.util.Map[typing.Union[java.lang.String, str], float],
                typing.Mapping[typing.Union[java.lang.String, str], float],
            ],
        ) -> None: ...
        def setSeparatorLoadFactors(
            self,
            map: typing.Union[
                java.util.Map[typing.Union[java.lang.String, str], float],
                typing.Mapping[typing.Union[java.lang.String, str], float],
            ],
        ) -> None: ...
        def setStreamFlowRates(
            self,
            map: typing.Union[
                java.util.Map[typing.Union[java.lang.String, str], float],
                typing.Mapping[typing.Union[java.lang.String, str], float],
            ],
        ) -> None: ...
        def setTotalCompressorPower(self, double: float) -> None: ...
        def setTotalPumpPower(self, double: float) -> None: ...
        def toString(self) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.examples")``.

    OilGasProcessSimulationOptimization: typing.Type[
        OilGasProcessSimulationOptimization
    ]
