import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.time
import java.util
import jneqsim.process.processmodel
import typing

class EmissionsTracker(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def calculateEmissions(self) -> "EmissionsTracker.EmissionsReport": ...
    def getCumulativeCO2e(self) -> float: ...
    def getGridEmissionFactor(self) -> float: ...
    def getHistory(self) -> java.util.List["EmissionsTracker.EmissionsSnapshot"]: ...
    def getNaturalGasEmissionFactor(self) -> float: ...
    def isIncludeIndirectEmissions(self) -> bool: ...
    def recordSnapshot(self) -> None: ...
    def setGridEmissionFactor(self, double: float) -> None: ...
    def setIncludeIndirectEmissions(self, boolean: bool) -> None: ...
    def setNaturalGasEmissionFactor(self, double: float) -> None: ...

    class EmissionCategory(java.lang.Enum["EmissionsTracker.EmissionCategory"]):
        FLARING: typing.ClassVar["EmissionsTracker.EmissionCategory"] = ...
        COMBUSTION: typing.ClassVar["EmissionsTracker.EmissionCategory"] = ...
        COMPRESSION: typing.ClassVar["EmissionsTracker.EmissionCategory"] = ...
        EXPANSION: typing.ClassVar["EmissionsTracker.EmissionCategory"] = ...
        PUMPING: typing.ClassVar["EmissionsTracker.EmissionCategory"] = ...
        HEATING: typing.ClassVar["EmissionsTracker.EmissionCategory"] = ...
        COOLING: typing.ClassVar["EmissionsTracker.EmissionCategory"] = ...
        VENTING: typing.ClassVar["EmissionsTracker.EmissionCategory"] = ...
        OTHER: typing.ClassVar["EmissionsTracker.EmissionCategory"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "EmissionsTracker.EmissionCategory": ...
        @staticmethod
        def values() -> typing.MutableSequence["EmissionsTracker.EmissionCategory"]: ...

    class EmissionsReport(java.io.Serializable):
        timestamp: java.time.Instant = ...
        processName: java.lang.String = ...
        totalCO2eKgPerHr: float = ...
        totalPowerKW: float = ...
        totalHeatDutyKW: float = ...
        equipmentEmissions: java.util.Map = ...
        def __init__(self): ...
        def exportToCSV(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def exportToJSON(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def getEmissionsByCategory(
            self,
        ) -> java.util.Map["EmissionsTracker.EmissionCategory", float]: ...
        def getFlaringCO2e(
            self, string: typing.Union[java.lang.String, str]
        ) -> float: ...
        def getSummary(self) -> java.lang.String: ...
        def getTotalCO2e(
            self, string: typing.Union[java.lang.String, str]
        ) -> float: ...
        def getTotalPower(
            self, string: typing.Union[java.lang.String, str]
        ) -> float: ...
        def toJson(self) -> java.lang.String: ...

    class EmissionsSnapshot(java.io.Serializable):
        timestamp: java.time.Instant = ...
        totalCO2eKgPerHr: float = ...
        totalPowerKW: float = ...
        def __init__(self): ...

    class EquipmentEmissions(java.io.Serializable):
        equipmentName: java.lang.String = ...
        equipmentType: java.lang.String = ...
        category: "EmissionsTracker.EmissionCategory" = ...
        directCO2eKgPerHr: float = ...
        indirectCO2eKgPerHr: float = ...
        powerConsumptionKW: float = ...
        heatDutyKW: float = ...
        def __init__(self): ...
        def getTotalCO2e(self) -> float: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.sustainability")``.

    EmissionsTracker: typing.Type[EmissionsTracker]
