
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.processmodel
import jneqsim.process.safety
import typing



class RiskEvent:
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], initiatingEvent: jneqsim.process.safety.InitiatingEvent): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], initiatingEvent: jneqsim.process.safety.InitiatingEvent): ...
    @staticmethod
    def builder() -> 'RiskEvent.Builder': ...
    def getAbsoluteFrequency(self) -> float: ...
    def getConditionalProbability(self) -> float: ...
    def getConsequenceCategory(self) -> 'RiskEvent.ConsequenceCategory': ...
    def getDescription(self) -> java.lang.String: ...
    def getFrequency(self) -> float: ...
    def getInitiatingEvent(self) -> jneqsim.process.safety.InitiatingEvent: ...
    def getName(self) -> java.lang.String: ...
    def getParentEvent(self) -> 'RiskEvent': ...
    def getRiskIndex(self) -> float: ...
    def getScenario(self) -> jneqsim.process.safety.ProcessSafetyScenario: ...
    def isInitiatingEvent(self) -> bool: ...
    def setConditionalProbability(self, double: float) -> None: ...
    def setConsequenceCategory(self, consequenceCategory: 'RiskEvent.ConsequenceCategory') -> None: ...
    def setFrequency(self, double: float) -> None: ...
    def setParentEvent(self, riskEvent: 'RiskEvent') -> None: ...
    def setScenario(self, processSafetyScenario: jneqsim.process.safety.ProcessSafetyScenario) -> None: ...
    def toString(self) -> java.lang.String: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'RiskEvent': ...
        def conditionalProbability(self, double: float) -> 'RiskEvent.Builder': ...
        def consequenceCategory(self, consequenceCategory: 'RiskEvent.ConsequenceCategory') -> 'RiskEvent.Builder': ...
        def description(self, string: typing.Union[java.lang.String, str]) -> 'RiskEvent.Builder': ...
        def frequency(self, double: float) -> 'RiskEvent.Builder': ...
        def initiatingEvent(self, initiatingEvent: jneqsim.process.safety.InitiatingEvent) -> 'RiskEvent.Builder': ...
        def name(self, string: typing.Union[java.lang.String, str]) -> 'RiskEvent.Builder': ...
        def parentEvent(self, riskEvent: 'RiskEvent') -> 'RiskEvent.Builder': ...
        def scenario(self, processSafetyScenario: jneqsim.process.safety.ProcessSafetyScenario) -> 'RiskEvent.Builder': ...
    class ConsequenceCategory(java.lang.Enum['RiskEvent.ConsequenceCategory']):
        NEGLIGIBLE: typing.ClassVar['RiskEvent.ConsequenceCategory'] = ...
        MINOR: typing.ClassVar['RiskEvent.ConsequenceCategory'] = ...
        MODERATE: typing.ClassVar['RiskEvent.ConsequenceCategory'] = ...
        MAJOR: typing.ClassVar['RiskEvent.ConsequenceCategory'] = ...
        CATASTROPHIC: typing.ClassVar['RiskEvent.ConsequenceCategory'] = ...
        def getSeverity(self) -> int: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'RiskEvent.ConsequenceCategory': ...
        @staticmethod
        def values() -> typing.MutableSequence['RiskEvent.ConsequenceCategory']: ...

class RiskModel:
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addConditionalEvent(self, string: typing.Union[java.lang.String, str], riskEvent: RiskEvent, double: float, consequenceCategory: RiskEvent.ConsequenceCategory) -> RiskEvent: ...
    def addEvent(self, riskEvent: RiskEvent) -> None: ...
    def addInitiatingEvent(self, string: typing.Union[java.lang.String, str], double: float, consequenceCategory: RiskEvent.ConsequenceCategory) -> RiskEvent: ...
    @staticmethod
    def builder() -> 'RiskModel.Builder': ...
    def getEvents(self) -> java.util.List[RiskEvent]: ...
    def getInitiatingEvents(self) -> java.util.List[RiskEvent]: ...
    def getName(self) -> java.lang.String: ...
    def runDeterministicAnalysis(self) -> 'RiskResult': ...
    def runMonteCarloAnalysis(self, int: int) -> 'RiskResult': ...
    @typing.overload
    def runSensitivityAnalysis(self, double: float, double2: float) -> 'SensitivityResult': ...
    @typing.overload
    def runSensitivityAnalysis(self, double: float, double2: float, int: int) -> 'SensitivityResult': ...
    def runSimulationBasedAnalysis(self) -> 'RiskResult': ...
    def setFrequencyUncertaintyFactor(self, double: float) -> None: ...
    def setProbabilityUncertaintyStdDev(self, double: float) -> None: ...
    def setProcessSystem(self, processSystem: jneqsim.process.processmodel.ProcessSystem) -> None: ...
    def setRandomSeed(self, long: int) -> None: ...
    def setStoreMonteCarloSamples(self, boolean: bool) -> None: ...
    def toString(self) -> java.lang.String: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'RiskModel': ...
        def frequencyUncertaintyFactor(self, double: float) -> 'RiskModel.Builder': ...
        def name(self, string: typing.Union[java.lang.String, str]) -> 'RiskModel.Builder': ...
        def processSystem(self, processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'RiskModel.Builder': ...
        def seed(self, long: int) -> 'RiskModel.Builder': ...

class RiskResult:
    def __init__(self, string: typing.Union[java.lang.String, str], int: int, long: int): ...
    def exportToCSV(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def exportToJSON(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def getAnalysisName(self) -> java.lang.String: ...
    def getCategoryFrequency(self, consequenceCategory: RiskEvent.ConsequenceCategory) -> float: ...
    def getEventResults(self) -> java.util.List['RiskResult.EventResult']: ...
    def getFNCurveData(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getIterations(self) -> int: ...
    def getMaxConsequence(self) -> float: ...
    def getMeanConsequence(self) -> float: ...
    def getPercentile95(self) -> float: ...
    def getPercentile99(self) -> float: ...
    def getSamples(self) -> typing.MutableSequence[float]: ...
    def getSeed(self) -> int: ...
    def getSummary(self) -> java.lang.String: ...
    def getTotalFrequency(self) -> float: ...
    def getTotalRiskIndex(self) -> float: ...
    def toString(self) -> java.lang.String: ...
    class EventResult:
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, consequenceCategory: RiskEvent.ConsequenceCategory): ...
        def getCategory(self) -> RiskEvent.ConsequenceCategory: ...
        def getEventName(self) -> java.lang.String: ...
        def getFrequency(self) -> float: ...
        def getProbability(self) -> float: ...
        def getRiskContribution(self) -> float: ...

class SensitivityResult:
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def exportToCSV(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def exportToJSON(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def getAnalysisName(self) -> java.lang.String: ...
    def getBaseCase(self) -> java.lang.String: ...
    def getBaseFrequency(self) -> float: ...
    def getBaseRiskIndex(self) -> float: ...
    def getMostSensitiveParameter(self) -> java.lang.String: ...
    def getParameterNames(self) -> typing.MutableSequence[java.lang.String]: ...
    def getParameterSensitivity(self, string: typing.Union[java.lang.String, str]) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getSensitivityIndex(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTornadoData(self) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def toString(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.risk")``.

    RiskEvent: typing.Type[RiskEvent]
    RiskModel: typing.Type[RiskModel]
    RiskResult: typing.Type[RiskResult]
    SensitivityResult: typing.Type[SensitivityResult]
