import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.thermo.system
import typing

class RunawayReactionAnalyzer:
    def __init__(self): ...
    def analyze(self) -> "RunawayReactionResult": ...
    def setAcceptableMargin(self, double: float) -> "RunawayReactionAnalyzer": ...
    def setActivationEnergy(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> "RunawayReactionAnalyzer": ...
    def setFluid(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> "RunawayReactionAnalyzer": ...
    def setGassySystem(self, boolean: bool) -> "RunawayReactionAnalyzer": ...
    def setInitialHeatReleaseRate(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> "RunawayReactionAnalyzer": ...
    def setLimitingReactantMoles(self, double: float) -> "RunawayReactionAnalyzer": ...
    def setMaxAllowableTemperature(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> "RunawayReactionAnalyzer": ...
    def setProcessTemperature(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> "RunawayReactionAnalyzer": ...
    def setReactionEnthalpy(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> "RunawayReactionAnalyzer": ...
    def setSpecificHeat(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> "RunawayReactionAnalyzer": ...
    def setTotalMass(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> "RunawayReactionAnalyzer": ...

    class RunawayVerdict(java.lang.Enum["RunawayReactionAnalyzer.RunawayVerdict"]):
        NO_RATING: typing.ClassVar["RunawayReactionAnalyzer.RunawayVerdict"] = ...
        ACCEPTABLE_MARGIN: typing.ClassVar["RunawayReactionAnalyzer.RunawayVerdict"] = (
            ...
        )
        MARGINAL: typing.ClassVar["RunawayReactionAnalyzer.RunawayVerdict"] = ...
        RUNAWAY_RISK: typing.ClassVar["RunawayReactionAnalyzer.RunawayVerdict"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "RunawayReactionAnalyzer.RunawayVerdict": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["RunawayReactionAnalyzer.RunawayVerdict"]
        ): ...

class RunawayReactionResult(java.io.Serializable):
    def __init__(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        boolean: bool,
        boolean2: bool,
        double6: float,
        double7: float,
        double8: float,
        boolean3: bool,
        double9: float,
        boolean4: bool,
        runawayVerdict: RunawayReactionAnalyzer.RunawayVerdict,
        list: java.util.List[typing.Union[java.lang.String, str]],
    ): ...
    def getAdiabaticTemperatureRiseK(self) -> float: ...
    def getMaxAllowableTemperatureK(self) -> float: ...
    def getMtsrK(self) -> float: ...
    def getProcessTemperatureK(self) -> float: ...
    def getSpecificHeatJPerKgK(self) -> float: ...
    def getTemperatureMarginK(self) -> float: ...
    def getTimeToMaxRateS(self) -> float: ...
    def getTotalHeatReleaseJ(self) -> float: ...
    def getTotalMassKg(self) -> float: ...
    def getVerdict(self) -> RunawayReactionAnalyzer.RunawayVerdict: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isMarginExceeded(self) -> bool: ...
    def isMaxAllowableProvided(self) -> bool: ...
    def isTimeToMaxRateProvided(self) -> bool: ...
    def isTwoPhaseReliefScreeningRequired(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.reaction")``.

    RunawayReactionAnalyzer: typing.Type[RunawayReactionAnalyzer]
    RunawayReactionResult: typing.Type[RunawayReactionResult]
