import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.standards
import jneqsim.thermo
import jneqsim.thermo.system
import typing

class BestPracticeHydrocarbonDewPoint(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...

class CriticalFlowOrifice(java.io.Serializable):
    def __init__(self): ...
    def calcCriticalFlow(self) -> None: ...
    @staticmethod
    def criticalPressureRatio(double: float) -> float: ...
    def getCriticalExpansionFactor(self) -> float: ...
    def getCriticalMassFlow(self) -> float: ...
    def getCriticalPressureRatio(self) -> float: ...
    @staticmethod
    def isChoked(double: float, double2: float, double3: float) -> bool: ...
    def isFlowChoked(self) -> bool: ...
    def setGeometry(self, double: float, double2: float) -> None: ...
    def setUpstreamConditions(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    def toJson(self) -> java.lang.String: ...

class Draft_GERG2004(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def createTable(
        self, string: typing.Union[java.lang.String, str]
    ) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...

class Draft_ISO18453(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...

class GasChromotograpyhBase(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...

class GpsaOrificeCalculator(java.io.Serializable):
    def __init__(self): ...
    def calcFlow(self) -> None: ...
    def getBetaRatio(self) -> float: ...
    def getExpansionFactor(self) -> float: ...
    def getMassFlowRate(self) -> float: ...
    def getOrificeDiameter(self) -> float: ...
    def getVolumetricFlowRate(self) -> float: ...
    def setDischargeCoefficient(self, double: float) -> None: ...
    def setFlowConditions(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    def setFluidService(
        self, fluidService: "GpsaOrificeCalculator.FluidService", double: float
    ) -> None: ...
    def setGeometry(self, double: float, double2: float) -> None: ...
    def sizeOrificeForFlow(self, double: float) -> float: ...
    def toJson(self) -> java.lang.String: ...

    class FluidService(java.lang.Enum["GpsaOrificeCalculator.FluidService"]):
        LIQUID: typing.ClassVar["GpsaOrificeCalculator.FluidService"] = ...
        STEAM: typing.ClassVar["GpsaOrificeCalculator.FluidService"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "GpsaOrificeCalculator.FluidService": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["GpsaOrificeCalculator.FluidService"]
        ): ...

class OrificeWellTester(java.io.Serializable):
    def __init__(self): ...
    def calcRate(self) -> None: ...
    def getGasRate(self) -> float: ...
    def getGravityFactor(self) -> float: ...
    def getSupercompressibilityFactor(self) -> float: ...
    def getTemperatureFactor(self) -> float: ...
    def setFlowingConditions(self, double: float, double2: float) -> None: ...
    def setGasProperties(self, double: float, double2: float) -> None: ...
    def setOrificeCoefficient(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...

class Standard_AGA3(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...
    def setDifferentialPressure(self, double: float) -> None: ...
    def setFlowingTemperature(self, double: float) -> None: ...
    def setOrificeDimensions(self, double: float, double2: float) -> None: ...
    def setStaticPressure(self, double: float) -> None: ...
    def setTapType(self, string: typing.Union[java.lang.String, str]) -> None: ...

class Standard_AGA7(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...
    def setFlowingConditions(self, double: float, double2: float) -> None: ...
    def setMeasuredSpeedOfSound(self, double: float) -> None: ...
    def setMeasuredVelocity(self, double: float) -> None: ...
    def setPipeDiameter(self, double: float) -> None: ...
    def setSOSDeviationLimit(self, double: float) -> None: ...

class Standard_EN16723(jneqsim.standards.Standard):
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(
        self, systemInterface: jneqsim.thermo.system.SystemInterface, int: int
    ): ...
    def calculate(self) -> None: ...
    def getEN16726(self) -> "Standard_EN16726": ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...
    def setPart(self, int: int) -> None: ...

class Standard_EN16726(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getNetworkType(self) -> java.lang.String: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def getWobbeIndexMax(self) -> float: ...
    def getWobbeIndexMin(self) -> float: ...
    def isOnSpec(self) -> bool: ...
    def setH2Limit(self, double: float) -> None: ...
    def setNetworkType(self, string: typing.Union[java.lang.String, str]) -> None: ...

class Standard_GPA2145(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    @staticmethod
    def getReferenceGrossHV(string: typing.Union[java.lang.String, str]) -> float: ...
    @staticmethod
    def getReferenceMolarMass(string: typing.Union[java.lang.String, str]) -> float: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...

class Standard_GPA2172(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...

class Standard_ISO12213(jneqsim.standards.Standard):
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
    ): ...
    def calculate(self) -> None: ...
    def getCalculationMethod(self) -> java.lang.String: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...
    def setCalculationMethod(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...

class Standard_ISO13443(jneqsim.standards.Standard):
    T_METER_15C: typing.ClassVar[float] = ...
    T_NORMAL_0C: typing.ClassVar[float] = ...
    T_US_60F: typing.ClassVar[float] = ...
    T_20C: typing.ClassVar[float] = ...
    T_COMBUSTION_25C: typing.ClassVar[float] = ...
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def convertVolume(self, double: float) -> float: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...
    @typing.overload
    def setConversionConditions(
        self, double: float, double2: float, double3: float, double4: float
    ) -> None: ...
    @typing.overload
    def setConversionConditions(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> None: ...

class Standard_ISO14687(jneqsim.standards.Standard):
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        string: typing.Union[java.lang.String, str],
    ): ...
    def calculate(self) -> None: ...
    def getGrade(self) -> java.lang.String: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...
    def setGrade(self, string: typing.Union[java.lang.String, str]) -> None: ...

class Standard_ISO15112(jneqsim.standards.Standard):
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
        double3: float,
    ): ...
    def calculate(self) -> None: ...
    def getISO6976(self) -> "Standard_ISO6976": ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def getVolumeFlowRate(self) -> float: ...
    def isOnSpec(self) -> bool: ...
    def setAccumulationPeriod(self, double: float) -> None: ...
    def setMeteringConditions(self, double: float, double2: float) -> None: ...
    def setVolumeFlowRate(self, double: float) -> None: ...

class Standard_ISO15403(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...

class Standard_ISO18453(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...
    def setDewPointTemperatureSpec(self, double: float) -> None: ...
    def setPressure(self, double: float) -> None: ...

class Standard_ISO23874(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getEvaluationPressure(self) -> float: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...
    def setEvaluationPressure(self, double: float) -> None: ...
    def setMinimumCarbonNumber(self, int: int) -> None: ...

class Standard_ISO6578(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getCorrFactor1(self) -> float: ...
    def getCorrFactor2(self) -> float: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...
    def setCorrectionFactors(self) -> None: ...
    def useISO6578VolumeCorrectionFacotrs(self, boolean: bool) -> None: ...

class Standard_ISO6976(
    jneqsim.standards.Standard, jneqsim.thermo.ThermodynamicConstantsInterface
):
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        systemInterface: jneqsim.thermo.system.SystemInterface,
    ): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
        string: typing.Union[java.lang.String, str],
    ): ...
    def calculate(self) -> None: ...
    def checkReferenceCondition(self) -> None: ...
    def createTable(
        self, string: typing.Union[java.lang.String, str]
    ) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def getAverageCarbonNumber(self) -> float: ...
    def getComponentsNotDefinedByStandard(
        self,
    ) -> java.util.ArrayList[java.lang.String]: ...
    def getEnergyRefP(self) -> float: ...
    def getEnergyRefT(self) -> float: ...
    def getReferenceType(self) -> java.lang.String: ...
    def getTotalMolesOfInerts(self) -> float: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def getVolRefT(self) -> float: ...
    def isOnSpec(self) -> bool: ...
    def removeInertsButNitrogen(self) -> None: ...
    def setEnergyRefP(self, double: float) -> None: ...
    def setEnergyRefT(self, double: float) -> None: ...
    def setReferenceType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setVolRefT(self, double: float) -> None: ...

class SulfurSpecificationMethod(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...

class UKspecifications_ICF_SI(jneqsim.standards.Standard):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcPropaneNumber(self) -> float: ...
    def calcWithNitrogenAsInert(self) -> float: ...
    def calculate(self) -> None: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isOnSpec(self) -> bool: ...

class Standard_ISO6974(GasChromotograpyhBase):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> None: ...
    def getExpandedUncertainties(self) -> java.util.Map[java.lang.String, float]: ...
    def getNormalisedComposition(self) -> java.util.Map[java.lang.String, float]: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def isNormalisationApplied(self) -> bool: ...
    def isOnSpec(self) -> bool: ...
    def setComponentUncertainty(
        self, string: typing.Union[java.lang.String, str], double: float
    ) -> None: ...
    def setCoverageFactor(self, double: float) -> None: ...
    def setNormalisationTolerance(self, double: float) -> None: ...

class Standard_ISO6976_2016(Standard_ISO6976):
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
        string: typing.Union[java.lang.String, str],
    ): ...
    def calculate(self) -> None: ...
    def getUnit(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.lang.String: ...
    @typing.overload
    def getValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getValue(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.standards.gasquality")``.

    BestPracticeHydrocarbonDewPoint: typing.Type[BestPracticeHydrocarbonDewPoint]
    CriticalFlowOrifice: typing.Type[CriticalFlowOrifice]
    Draft_GERG2004: typing.Type[Draft_GERG2004]
    Draft_ISO18453: typing.Type[Draft_ISO18453]
    GasChromotograpyhBase: typing.Type[GasChromotograpyhBase]
    GpsaOrificeCalculator: typing.Type[GpsaOrificeCalculator]
    OrificeWellTester: typing.Type[OrificeWellTester]
    Standard_AGA3: typing.Type[Standard_AGA3]
    Standard_AGA7: typing.Type[Standard_AGA7]
    Standard_EN16723: typing.Type[Standard_EN16723]
    Standard_EN16726: typing.Type[Standard_EN16726]
    Standard_GPA2145: typing.Type[Standard_GPA2145]
    Standard_GPA2172: typing.Type[Standard_GPA2172]
    Standard_ISO12213: typing.Type[Standard_ISO12213]
    Standard_ISO13443: typing.Type[Standard_ISO13443]
    Standard_ISO14687: typing.Type[Standard_ISO14687]
    Standard_ISO15112: typing.Type[Standard_ISO15112]
    Standard_ISO15403: typing.Type[Standard_ISO15403]
    Standard_ISO18453: typing.Type[Standard_ISO18453]
    Standard_ISO23874: typing.Type[Standard_ISO23874]
    Standard_ISO6578: typing.Type[Standard_ISO6578]
    Standard_ISO6974: typing.Type[Standard_ISO6974]
    Standard_ISO6976: typing.Type[Standard_ISO6976]
    Standard_ISO6976_2016: typing.Type[Standard_ISO6976_2016]
    SulfurSpecificationMethod: typing.Type[SulfurSpecificationMethod]
    UKspecifications_ICF_SI: typing.Type[UKspecifications_ICF_SI]
