import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.costestimation
import jneqsim.process.mechanicaldesign.absorber
import typing

class AbsorberCostEstimate(jneqsim.process.costestimation.UnitCostEstimateBaseClass):
    def __init__(
        self,
        absorberMechanicalDesign: jneqsim.process.mechanicaldesign.absorber.AbsorberMechanicalDesign,
    ): ...
    @typing.overload
    def calcAnnualOperatingCost(
        self, double: float, double2: float, double3: float, int: int
    ) -> float: ...
    @typing.overload
    def calcAnnualOperatingCost(
        self, int: int, double: float, double2: float
    ) -> float: ...
    def getAbsorberType(self) -> java.lang.String: ...
    def getColumnDiameter(self) -> float: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def setAbsorberType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setColumnDiameter(self, double: float) -> None: ...
    def setColumnHeight(self, double: float) -> None: ...
    def setDesignPressure(self, double: float) -> None: ...
    def setIncludeLiquidDistributor(self, boolean: bool) -> None: ...
    def setIncludeMistEliminator(self, boolean: bool) -> None: ...
    def setIncludeReboiler(self, boolean: bool) -> None: ...
    def setIncludeRefluxSystem(self, boolean: bool) -> None: ...
    def setNumberOfStages(self, int: int) -> None: ...
    def setPackingHeight(self, double: float) -> None: ...
    def setPackingType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReboilerDuty(self, double: float) -> None: ...
    def setTrayType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.costestimation.absorber")``.

    AbsorberCostEstimate: typing.Type[AbsorberCostEstimate]
