
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import com.google.gson
import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.costestimation
import jneqsim.process.equipment
import jneqsim.process.equipment.subsea
import jneqsim.process.mechanicaldesign
import jneqsim.process.mechanicaldesign.designstandards
import jneqsim.thermo.system
import typing



class BarrierElement(java.io.Serializable):
    @typing.overload
    def __init__(self, elementType: 'BarrierElement.ElementType', string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, elementType: 'BarrierElement.ElementType', string: typing.Union[java.lang.String, str], double: float): ...
    def getDepthMD(self) -> float: ...
    def getDescription(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getStatus(self) -> 'BarrierElement.Status': ...
    def getType(self) -> 'BarrierElement.ElementType': ...
    def isFunctional(self) -> bool: ...
    def isVerified(self) -> bool: ...
    def setDepthMD(self, double: float) -> None: ...
    def setDescription(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setStatus(self, status: 'BarrierElement.Status') -> None: ...
    def setVerified(self, boolean: bool) -> None: ...
    def toString(self) -> java.lang.String: ...
    class ElementType(java.lang.Enum['BarrierElement.ElementType']):
        CASING: typing.ClassVar['BarrierElement.ElementType'] = ...
        TUBING: typing.ClassVar['BarrierElement.ElementType'] = ...
        PACKER: typing.ClassVar['BarrierElement.ElementType'] = ...
        DHSV: typing.ClassVar['BarrierElement.ElementType'] = ...
        ISV: typing.ClassVar['BarrierElement.ElementType'] = ...
        WELLHEAD: typing.ClassVar['BarrierElement.ElementType'] = ...
        XMAS_TREE: typing.ClassVar['BarrierElement.ElementType'] = ...
        ASV: typing.ClassVar['BarrierElement.ElementType'] = ...
        CEMENT: typing.ClassVar['BarrierElement.ElementType'] = ...
        CASING_CEMENT: typing.ClassVar['BarrierElement.ElementType'] = ...
        FORMATION: typing.ClassVar['BarrierElement.ElementType'] = ...
        PLUG: typing.ClassVar['BarrierElement.ElementType'] = ...
        WING_VALVE: typing.ClassVar['BarrierElement.ElementType'] = ...
        SWAB_VALVE: typing.ClassVar['BarrierElement.ElementType'] = ...
        CHEMICAL_INJECTION_VALVE: typing.ClassVar['BarrierElement.ElementType'] = ...
        KILL_VALVE: typing.ClassVar['BarrierElement.ElementType'] = ...
        GAUGE: typing.ClassVar['BarrierElement.ElementType'] = ...
        ANNULUS_ACCESS_VALVE: typing.ClassVar['BarrierElement.ElementType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'BarrierElement.ElementType': ...
        @staticmethod
        def values() -> typing.MutableSequence['BarrierElement.ElementType']: ...
    class Status(java.lang.Enum['BarrierElement.Status']):
        INTACT: typing.ClassVar['BarrierElement.Status'] = ...
        DEGRADED: typing.ClassVar['BarrierElement.Status'] = ...
        FAILED: typing.ClassVar['BarrierElement.Status'] = ...
        UNKNOWN: typing.ClassVar['BarrierElement.Status'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'BarrierElement.Status': ...
        @staticmethod
        def values() -> typing.MutableSequence['BarrierElement.Status']: ...

class BarrierEnvelope(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addElement(self, barrierElement: BarrierElement) -> None: ...
    def getElementCount(self) -> int: ...
    def getElements(self) -> java.util.List[BarrierElement]: ...
    def getElementsByType(self, elementType: BarrierElement.ElementType) -> java.util.List[BarrierElement]: ...
    def getFailedElements(self) -> java.util.List[BarrierElement]: ...
    def getFunctionalElementCount(self) -> int: ...
    def getName(self) -> java.lang.String: ...
    def getVerifiedElementCount(self) -> int: ...
    def hasElementType(self, elementType: BarrierElement.ElementType) -> bool: ...
    def isIntact(self) -> bool: ...
    def meetsMinimum(self, int: int) -> bool: ...
    def toString(self) -> java.lang.String: ...

class DnvRpF109OnBottomStabilityAssessment(java.io.Serializable):
    def areAllScreeningChecksPassing(self) -> bool: ...
    def getCaseResults(self) -> java.util.List['DnvRpF109OnBottomStabilityAssessment.CaseResult']: ...
    def getChecks(self) -> java.util.List['DnvRpF109StabilityCheck']: ...
    def getGoverningCheck(self) -> 'DnvRpF109StabilityCheck': ...
    def isEngineeringApprovalRequired(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class CaseResult(java.io.Serializable):
        def getCaseId(self) -> java.lang.String: ...
        def getDragLoadNPerM(self) -> float: ...
        def getFactoredHorizontalDemandNPerM(self) -> float: ...
        def getInertiaLoadNPerM(self) -> float: ...
        def getLateralResistanceNPerM(self) -> float: ...
        def getLiftLoadNPerM(self) -> float: ...
        def getNormalCurrentVelocityMPerS(self) -> float: ...
        def getNormalWaveAccelerationMPerS2(self) -> float: ...
        def getNormalWaveVelocityMPerS(self) -> float: ...
        def getRequiredSubmergedWeightNPerM(self) -> float: ...
        def getSpecificGravity(self) -> float: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class DnvRpF109OnBottomStabilityCalculator:
    @staticmethod
    def calculate(dnvRpF109OnBottomStabilityInput: 'DnvRpF109OnBottomStabilityInput') -> DnvRpF109OnBottomStabilityAssessment: ...

class DnvRpF109OnBottomStabilityInput(java.io.Serializable):
    @staticmethod
    def builder() -> 'DnvRpF109OnBottomStabilityInput.Builder': ...
    def getAssetType(self) -> 'DnvRpF109OnBottomStabilityInput.AssetType': ...
    def getEdition(self) -> jneqsim.process.mechanicaldesign.designstandards.StandardEdition: ...
    def getEngineeringBasis(self) -> java.lang.String: ...
    def getEquipmentType(self) -> java.lang.String: ...
    def getGravitationalAccelerationMPerS2(self) -> float: ...
    def getLoadCases(self) -> java.util.List['DnvRpF109OnBottomStabilityInput.LoadCase']: ...
    def getOutsideDiameterM(self) -> float: ...
    def getSeawaterDensityKgM3(self) -> float: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class AssetType(java.lang.Enum['DnvRpF109OnBottomStabilityInput.AssetType']):
        PIPELINE: typing.ClassVar['DnvRpF109OnBottomStabilityInput.AssetType'] = ...
        CABLE: typing.ClassVar['DnvRpF109OnBottomStabilityInput.AssetType'] = ...
        UMBILICAL: typing.ClassVar['DnvRpF109OnBottomStabilityInput.AssetType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'DnvRpF109OnBottomStabilityInput.AssetType': ...
        @staticmethod
        def values() -> typing.MutableSequence['DnvRpF109OnBottomStabilityInput.AssetType']: ...
    class Builder:
        def addLoadCase(self, loadCase: 'DnvRpF109OnBottomStabilityInput.LoadCase') -> 'DnvRpF109OnBottomStabilityInput.Builder': ...
        def assetType(self, assetType: 'DnvRpF109OnBottomStabilityInput.AssetType') -> 'DnvRpF109OnBottomStabilityInput.Builder': ...
        def build(self) -> 'DnvRpF109OnBottomStabilityInput': ...
        def edition(self, standardEdition: jneqsim.process.mechanicaldesign.designstandards.StandardEdition) -> 'DnvRpF109OnBottomStabilityInput.Builder': ...
        def engineeringBasis(self, string: typing.Union[java.lang.String, str]) -> 'DnvRpF109OnBottomStabilityInput.Builder': ...
        def equipmentType(self, string: typing.Union[java.lang.String, str]) -> 'DnvRpF109OnBottomStabilityInput.Builder': ...
        def gravitationalAccelerationMPerS2(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.Builder': ...
        def outsideDiameterM(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.Builder': ...
        def seawaterDensityKgM3(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.Builder': ...
    class LateralMethod(java.lang.Enum['DnvRpF109OnBottomStabilityInput.LateralMethod']):
        ABSOLUTE_STATIC: typing.ClassVar['DnvRpF109OnBottomStabilityInput.LateralMethod'] = ...
        EXTERNAL_RESPONSE_0_5D: typing.ClassVar['DnvRpF109OnBottomStabilityInput.LateralMethod'] = ...
        EXTERNAL_RESPONSE_10D: typing.ClassVar['DnvRpF109OnBottomStabilityInput.LateralMethod'] = ...
        EXTERNAL_RESPONSE_USER_DEFINED: typing.ClassVar['DnvRpF109OnBottomStabilityInput.LateralMethod'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'DnvRpF109OnBottomStabilityInput.LateralMethod': ...
        @staticmethod
        def values() -> typing.MutableSequence['DnvRpF109OnBottomStabilityInput.LateralMethod']: ...
    class LoadCase(java.io.Serializable):
        @staticmethod
        def builder() -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
        def getAllowableDisplacementDiameters(self) -> float: ...
        def getCaseId(self) -> java.lang.String: ...
        def getCurrentDirectionRelativeToPipeDeg(self) -> float: ...
        def getCurrentVelocityMPerS(self) -> float: ...
        def getDragCoefficient(self) -> float: ...
        def getHorizontalLoadReductionFactor(self) -> float: ...
        def getHorizontalSafetyFactor(self) -> float: ...
        def getInertiaCoefficient(self) -> float: ...
        def getLateralMethod(self) -> 'DnvRpF109OnBottomStabilityInput.LateralMethod': ...
        def getLiftCoefficient(self) -> float: ...
        def getOscillationCount(self) -> float: ...
        def getPassiveSoilResistanceNPerM(self) -> float: ...
        def getPredictedLateralDisplacementM(self) -> float: ...
        def getResponseModelBasis(self) -> java.lang.String: ...
        def getResponseModelWithinValidatedRange(self) -> bool: ...
        def getSoilFrictionCoefficient(self) -> float: ...
        def getStormDurationHours(self) -> float: ...
        def getSubmergedWeightNPerM(self) -> float: ...
        def getVerticalLoadReductionFactor(self) -> float: ...
        def getVerticalSafetyFactor(self) -> float: ...
        def getWaveAccelerationMPerS2(self) -> float: ...
        def getWaveDirectionRelativeToPipeDeg(self) -> float: ...
        def getWaveVelocityMPerS(self) -> float: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
        class Builder:
            def allowableDisplacementDiameters(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def build(self) -> 'DnvRpF109OnBottomStabilityInput.LoadCase': ...
            def caseId(self, string: typing.Union[java.lang.String, str]) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def currentDirectionRelativeToPipeDeg(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def currentVelocityMPerS(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def dragCoefficient(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def horizontalLoadReductionFactor(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def horizontalSafetyFactor(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def inertiaCoefficient(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def lateralMethod(self, lateralMethod: 'DnvRpF109OnBottomStabilityInput.LateralMethod') -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def liftCoefficient(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def oscillationCount(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def passiveSoilResistanceNPerM(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def predictedLateralDisplacementM(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def responseModelBasis(self, string: typing.Union[java.lang.String, str]) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def responseModelWithinValidatedRange(self, boolean: bool) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def soilFrictionCoefficient(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def stormDurationHours(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def submergedWeightNPerM(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def verticalLoadReductionFactor(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def verticalSafetyFactor(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def waveAccelerationMPerS2(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def waveDirectionRelativeToPipeDeg(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...
            def waveVelocityMPerS(self, double: float) -> 'DnvRpF109OnBottomStabilityInput.LoadCase.Builder': ...

class DnvRpF109StabilityCheck(java.io.Serializable):
    def getCaseId(self) -> java.lang.String: ...
    def getDemand(self) -> float: ...
    def getLimitState(self) -> 'DnvRpF109StabilityCheck.LimitState': ...
    def getMethod(self) -> java.lang.String: ...
    def getNote(self) -> java.lang.String: ...
    def getResistance(self) -> float: ...
    def getUnit(self) -> java.lang.String: ...
    def getUtilization(self) -> float: ...
    def getVerdict(self) -> 'DnvRpF109StabilityCheck.Verdict': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class LimitState(java.lang.Enum['DnvRpF109StabilityCheck.LimitState']):
        VERTICAL_STABILITY: typing.ClassVar['DnvRpF109StabilityCheck.LimitState'] = ...
        ABSOLUTE_LATERAL_STABILITY: typing.ClassVar['DnvRpF109StabilityCheck.LimitState'] = ...
        LATERAL_DISPLACEMENT: typing.ClassVar['DnvRpF109StabilityCheck.LimitState'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'DnvRpF109StabilityCheck.LimitState': ...
        @staticmethod
        def values() -> typing.MutableSequence['DnvRpF109StabilityCheck.LimitState']: ...
    class Verdict(java.lang.Enum['DnvRpF109StabilityCheck.Verdict']):
        PASS: typing.ClassVar['DnvRpF109StabilityCheck.Verdict'] = ...
        FAIL: typing.ClassVar['DnvRpF109StabilityCheck.Verdict'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'DnvRpF109StabilityCheck.Verdict': ...
        @staticmethod
        def values() -> typing.MutableSequence['DnvRpF109StabilityCheck.Verdict']: ...

class FlexiblePipeMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def calculateCostEstimate(self) -> None: ...
    def generateBillOfMaterials(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getCalculatedMBR(self) -> float: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDesignStandardCode(self) -> java.lang.String: ...
    def getEquipmentCostUSD(self) -> float: ...
    def getInstallationCostUSD(self) -> float: ...
    def getRequiredBurstPressure(self) -> float: ...
    def getRequiredTensileCapacity(self) -> float: ...
    def getTotalCostUSD(self) -> float: ...
    def getTotalManhours(self) -> float: ...
    def getVesselDays(self) -> float: ...
    def readDesignSpecifications(self) -> None: ...
    def setDesignStandardCode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRegion(self, region: 'SubseaCostEstimator.Region') -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class FlowlineSizeSelector(java.io.Serializable):
    C_FACTOR_CONTINUOUS: typing.ClassVar[float] = ...
    C_FACTOR_INTERMITTENT: typing.ClassVar[float] = ...
    def __init__(self): ...
    @staticmethod
    def erosionalVelocity(double: float, double2: float) -> float: ...
    def getCandidates(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getErosionalVelocity(self) -> float: ...
    def getSelected(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def select(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def setBasisFromFluid(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float) -> 'FlowlineSizeSelector': ...
    def setCFactor(self, double: float) -> 'FlowlineSizeSelector': ...
    def setCandidates(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> 'FlowlineSizeSelector': ...
    def setMassFlowRate(self, double: float) -> 'FlowlineSizeSelector': ...
    def setMixtureDensity(self, double: float) -> 'FlowlineSizeSelector': ...
    def setTargetVelocity(self, double: float) -> 'FlowlineSizeSelector': ...
    def setWallThickness(self, double: float) -> 'FlowlineSizeSelector': ...
    def toJson(self) -> java.lang.String: ...

class PLEMMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def calculateCostEstimate(self) -> None: ...
    def generateBillOfMaterials(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDesignStandardCode(self) -> java.lang.String: ...
    def getEquipmentCostUSD(self) -> float: ...
    def getHeaderWallThickness(self) -> float: ...
    def getInstallationCostUSD(self) -> float: ...
    def getTotalCostUSD(self) -> float: ...
    def getTotalManhours(self) -> float: ...
    def getVesselDays(self) -> float: ...
    def readDesignSpecifications(self) -> None: ...
    def setDesignStandardCode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRegion(self, region: 'SubseaCostEstimator.Region') -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class PLETMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def calculateCostEstimate(self) -> None: ...
    def generateBillOfMaterials(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDesignStandardCode(self) -> java.lang.String: ...
    def getEquipmentCostUSD(self) -> float: ...
    def getHubWallThickness(self) -> float: ...
    def getInstallationCostUSD(self) -> float: ...
    def getRequiredFoundationWeight(self) -> float: ...
    def getRequiredMudmatArea(self) -> float: ...
    def getStructureMaterialGrade(self) -> java.lang.String: ...
    def getTotalCostUSD(self) -> float: ...
    def getTotalManhours(self) -> float: ...
    def getVesselDays(self) -> float: ...
    def readDesignSpecifications(self) -> None: ...
    def setDesignStandardCode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setStructureMaterialGrade(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class SURFCostEstimator:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int, double: float, region: 'SubseaCostEstimator.Region'): ...
    def calculate(self) -> float: ...
    def excludeExportPipeline(self, double: float) -> None: ...
    def getCategoryLineItems(self, string: typing.Union[java.lang.String, str]) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDetailedEstimateResult(self) -> jneqsim.process.costestimation.CostEstimateResult: ...
    def getEstimateBasis(self) -> jneqsim.process.costestimation.CostEstimateBasis: ...
    def getEstimateClass(self) -> jneqsim.process.costestimation.EstimateClass: ...
    def getFlowlineCostUSD(self) -> float: ...
    def getLineItems(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getRiserCostUSD(self) -> float: ...
    def getSubseaCostUSD(self) -> float: ...
    def getTotalCostInCurrency(self, double: float) -> float: ...
    def getTotalSURFCostUSD(self) -> float: ...
    def getUmbilicalCostUSD(self) -> float: ...
    def setCoatingPricePerM2(self, double: float) -> None: ...
    def setContingencyPct(self, double: float) -> None: ...
    def setDualBoreTrees(self, boolean: bool) -> None: ...
    def setEstimateBasis(self, costEstimateBasis: jneqsim.process.costestimation.CostEstimateBasis) -> None: ...
    def setEstimateClass(self, estimateClass: jneqsim.process.costestimation.EstimateClass) -> None: ...
    def setExportPipelineDiameterInches(self, double: float) -> None: ...
    def setExportPipelineLengthKm(self, double: float) -> None: ...
    def setFlexibleRiser(self, boolean: bool) -> None: ...
    def setHorizontalTrees(self, boolean: bool) -> None: ...
    def setIncludeRisers(self, boolean: bool) -> None: ...
    def setInfieldFlowlineDiameterInches(self, double: float) -> None: ...
    def setInfieldFlowlineFlexible(self, boolean: bool) -> None: ...
    def setInfieldFlowlineLengthKm(self, double: float) -> None: ...
    def setJumperDiameterInches(self, double: float) -> None: ...
    def setJumperLengthM(self, double: float) -> None: ...
    def setManifoldHasTestHeader(self, boolean: bool) -> None: ...
    def setManifoldSlots(self, int: int) -> None: ...
    def setManifoldWeightTonnes(self, double: float) -> None: ...
    def setNumberOfJumpers(self, int: int) -> None: ...
    def setNumberOfPLEMs(self, int: int) -> None: ...
    def setNumberOfPLETs(self, int: int) -> None: ...
    def setNumberOfProductionRisers(self, int: int) -> None: ...
    def setNumberOfWells(self, int: int) -> None: ...
    def setPipelineDesignPressureBar(self, double: float) -> None: ...
    def setPipelineInstallMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPipelineMaterialGrade(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPipelineWallThicknessMm(self, double: float) -> None: ...
    def setPlemHeaderSizeInches(self, double: float) -> None: ...
    def setPlemWeightTonnes(self, double: float) -> None: ...
    def setPletHubSizeInches(self, double: float) -> None: ...
    def setPletWeightTonnes(self, double: float) -> None: ...
    def setRegion(self, region: 'SubseaCostEstimator.Region') -> None: ...
    def setRigidJumpers(self, boolean: bool) -> None: ...
    def setRiserDiameterInches(self, double: float) -> None: ...
    def setRiserHasBuoyancy(self, boolean: bool) -> None: ...
    def setRiserLengthM(self, double: float) -> None: ...
    def setSteelPricePerKg(self, double: float) -> None: ...
    def setTreeBoreSizeInches(self, double: float) -> None: ...
    def setTreePressureRatingPsi(self, double: float) -> None: ...
    def setUmbilicalChemicalLines(self, int: int) -> None: ...
    def setUmbilicalDynamic(self, boolean: bool) -> None: ...
    def setUmbilicalElectricalCables(self, int: int) -> None: ...
    def setUmbilicalHydraulicLines(self, int: int) -> None: ...
    def setUmbilicalLengthKm(self, double: float) -> None: ...
    def setWaterDepthM(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...

class StidWellBarrierDataSource:
    PRIMARY_KEYS: typing.ClassVar[typing.MutableSequence[java.lang.String]] = ...
    SECONDARY_KEYS: typing.ClassVar[typing.MutableSequence[java.lang.String]] = ...
    ELEMENT_ARRAY_KEYS: typing.ClassVar[typing.MutableSequence[java.lang.String]] = ...
    @typing.overload
    def __init__(self, jsonObject: com.google.gson.JsonObject): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def getInstallationCode(self) -> java.lang.String: ...
    def getWellId(self) -> java.lang.String: ...
    def read(self) -> 'WellBarrierSchematic': ...

class SubseaBoosterMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def calculateCostEstimate(self) -> None: ...
    def generateBillOfMaterials(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getBearingLife(self) -> float: ...
    def getCalculatedHead(self) -> float: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDesignStandardCode(self) -> java.lang.String: ...
    def getEquipmentCostUSD(self) -> float: ...
    def getHousingWallThickness(self) -> float: ...
    def getInstallationCostUSD(self) -> float: ...
    def getRequiredMotorPower(self) -> float: ...
    def getTotalCostUSD(self) -> float: ...
    def getTotalManhours(self) -> float: ...
    def getVesselDays(self) -> float: ...
    def readDesignSpecifications(self) -> None: ...
    def setDesignStandardCode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRegion(self, region: 'SubseaCostEstimator.Region') -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class SubseaCostEstimator:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, region: 'SubseaCostEstimator.Region'): ...
    def calculateBoosterCost(self, double: float, boolean: bool, double2: float, boolean2: bool) -> None: ...
    def calculateFlexiblePipeCost(self, double: float, double2: float, double3: float, boolean: bool, boolean2: bool) -> None: ...
    def calculateJumperCost(self, double: float, double2: float, boolean: bool, double3: float) -> None: ...
    def calculateManifoldCost(self, int: int, double: float, double2: float, boolean: bool) -> None: ...
    def calculatePLETCost(self, double: float, double2: float, double3: float, boolean: bool, boolean2: bool) -> None: ...
    def calculateTreeCost(self, double: float, double2: float, double3: float, boolean: bool, boolean2: bool) -> None: ...
    def calculateUmbilicalCost(self, double: float, int: int, int2: int, int3: int, double2: float, boolean: bool) -> None: ...
    def generateBOM(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def generateBillOfMaterials(self, string: typing.Union[java.lang.String, str], map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Any], typing.Mapping[typing.Union[java.lang.String, str], typing.Any]]) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getCurrency(self) -> 'SubseaCostEstimator.Currency': ...
    def getEquipmentCost(self) -> float: ...
    def getFabricationCost(self) -> float: ...
    def getInstallationCost(self) -> float: ...
    def getRegion(self) -> 'SubseaCostEstimator.Region': ...
    def getTotalCost(self) -> float: ...
    def getTotalManhours(self) -> float: ...
    def getVesselDays(self) -> float: ...
    def setContingencyPct(self, double: float) -> None: ...
    def setCurrency(self, currency: 'SubseaCostEstimator.Currency') -> None: ...
    def setRegion(self, region: 'SubseaCostEstimator.Region') -> None: ...
    def toJson(self) -> java.lang.String: ...
    class Currency(java.lang.Enum['SubseaCostEstimator.Currency']):
        USD: typing.ClassVar['SubseaCostEstimator.Currency'] = ...
        EUR: typing.ClassVar['SubseaCostEstimator.Currency'] = ...
        GBP: typing.ClassVar['SubseaCostEstimator.Currency'] = ...
        NOK: typing.ClassVar['SubseaCostEstimator.Currency'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaCostEstimator.Currency': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaCostEstimator.Currency']: ...
    class Region(java.lang.Enum['SubseaCostEstimator.Region']):
        NORWAY: typing.ClassVar['SubseaCostEstimator.Region'] = ...
        UK: typing.ClassVar['SubseaCostEstimator.Region'] = ...
        GOM: typing.ClassVar['SubseaCostEstimator.Region'] = ...
        BRAZIL: typing.ClassVar['SubseaCostEstimator.Region'] = ...
        WEST_AFRICA: typing.ClassVar['SubseaCostEstimator.Region'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaCostEstimator.Region': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaCostEstimator.Region']: ...

class SubseaJumperMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def calculateCostEstimate(self) -> None: ...
    def generateBillOfMaterials(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDesignStandardCode(self) -> java.lang.String: ...
    def getEquipmentCostUSD(self) -> float: ...
    def getHoopStress(self) -> float: ...
    def getInstallationCostUSD(self) -> float: ...
    def getRequiredWallThickness(self) -> float: ...
    def getTotalCostUSD(self) -> float: ...
    def getTotalManhours(self) -> float: ...
    def getUnityCheck(self) -> float: ...
    def getVesselDays(self) -> float: ...
    def isBendRadiusOK(self) -> bool: ...
    def readDesignSpecifications(self) -> None: ...
    def setDesignStandardCode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRegion(self, region: SubseaCostEstimator.Region) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class SubseaManifoldMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def calculateCostEstimate(self) -> None: ...
    def generateBillOfMaterials(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDesignStandardCode(self) -> java.lang.String: ...
    def getEquipmentCostUSD(self) -> float: ...
    def getInstallationCostUSD(self) -> float: ...
    def getProductionHeaderWallThickness(self) -> float: ...
    def getTestHeaderWallThickness(self) -> float: ...
    def getTotalCostUSD(self) -> float: ...
    def getTotalManhours(self) -> float: ...
    def getVesselDays(self) -> float: ...
    def readDesignSpecifications(self) -> None: ...
    def setDesignStandardCode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRegion(self, region: SubseaCostEstimator.Region) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class SubseaTreeMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def calculateCostEstimate(self) -> None: ...
    def generateBillOfMaterials(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getBoreWallThickness(self) -> float: ...
    def getConnectorCapacity(self) -> float: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDesignStandardCode(self) -> java.lang.String: ...
    def getEquipmentCostUSD(self) -> float: ...
    def getInstallationCostUSD(self) -> float: ...
    def getTestPressure(self) -> float: ...
    def getTotalCostUSD(self) -> float: ...
    def getTotalManhours(self) -> float: ...
    def getVesselDays(self) -> float: ...
    def readDesignSpecifications(self) -> None: ...
    def setDesignStandardCode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRegion(self, region: SubseaCostEstimator.Region) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class TiebackThermalDesign(java.io.Serializable):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getRequiredInsulationForWall(self, double: float) -> float: ...
    def isWaterPresent(self) -> bool: ...
    def setExternalHTC(self, double: float) -> 'TiebackThermalDesign': ...
    def setInsulationConductivity(self, double: float) -> 'TiebackThermalDesign': ...
    def setInsulationThicknesses(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> 'TiebackThermalDesign': ...
    def setInternalDiameter(self, double: float) -> 'TiebackThermalDesign': ...
    def setOperatingTemperature(self, double: float) -> 'TiebackThermalDesign': ...
    def setRequireWater(self, boolean: bool) -> 'TiebackThermalDesign': ...
    def setRequiredNoTouchTime(self, double: float) -> 'TiebackThermalDesign': ...
    def setSeabedTemperature(self, double: float) -> 'TiebackThermalDesign': ...
    def setWallThicknesses(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> 'TiebackThermalDesign': ...
    def toJson(self) -> java.lang.String: ...

class UmbilicalMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def calculateCostEstimate(self) -> None: ...
    def generateBillOfMaterials(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getChemicalTubeWallThickness(self) -> float: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDesignStandardCode(self) -> java.lang.String: ...
    def getEquipmentCostUSD(self) -> float: ...
    def getHydraulicTubeWallThickness(self) -> float: ...
    def getInstallationCostUSD(self) -> float: ...
    def getMaxAllowableTension(self) -> float: ...
    def getRequiredArmorLayers(self) -> int: ...
    def getTotalCostUSD(self) -> float: ...
    def getTotalManhours(self) -> float: ...
    def getVesselDays(self) -> float: ...
    def readDesignSpecifications(self) -> None: ...
    def setDesignStandardCode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRegion(self, region: SubseaCostEstimator.Region) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class WellBarrierSchematic(java.io.Serializable):
    def __init__(self): ...
    def getAppliedStandards(self) -> java.util.List[java.lang.String]: ...
    def getIssueCount(self) -> int: ...
    def getIssues(self) -> java.util.List[java.lang.String]: ...
    def getPrimaryEnvelope(self) -> BarrierEnvelope: ...
    def getSecondaryEnvelope(self) -> BarrierEnvelope: ...
    def getWellType(self) -> java.lang.String: ...
    def isPassed(self) -> bool: ...
    def setAnnulusMonitoringRequired(self, boolean: bool) -> None: ...
    def setDhsvRequired(self, boolean: bool) -> None: ...
    def setIsvRequired(self, boolean: bool) -> None: ...
    def setMinimumElements(self, int: int, int2: int) -> None: ...
    def setPrimaryEnvelope(self, barrierEnvelope: BarrierEnvelope) -> None: ...
    def setSecondaryEnvelope(self, barrierEnvelope: BarrierEnvelope) -> None: ...
    def setWellType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def validate(self) -> bool: ...

class WellCostEstimator:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, region: SubseaCostEstimator.Region): ...
    @typing.overload
    def calculateWellCost(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float, boolean: bool, int: int) -> None: ...
    @typing.overload
    def calculateWellCost(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float, boolean: bool, int: int, wellLocationType: 'WellCostEstimator.WellLocationType') -> None: ...
    def generateBillOfMaterials(self, subseaWell: jneqsim.process.equipment.subsea.SubseaWell) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getBitsCost(self) -> float: ...
    def getCasingMaterialCost(self) -> float: ...
    def getCementCost(self) -> float: ...
    def getCompletionCost(self) -> float: ...
    def getContingencyCost(self) -> float: ...
    def getContingencyPct(self) -> float: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDrillingCost(self) -> float: ...
    def getLoggingCost(self) -> float: ...
    def getMudCost(self) -> float: ...
    def getRegion(self) -> SubseaCostEstimator.Region: ...
    def getRegionFactor(self) -> float: ...
    def getSafetyValveCost(self) -> float: ...
    def getTotalCost(self) -> float: ...
    def getWellLocationType(self) -> 'WellCostEstimator.WellLocationType': ...
    def getWellTestCost(self) -> float: ...
    def getWellheadCost(self) -> float: ...
    def setContingencyPct(self, double: float) -> None: ...
    def setRegion(self, region: SubseaCostEstimator.Region) -> None: ...
    def setRigDayRate(self, double: float) -> None: ...
    def setWellLocationType(self, wellLocationType: 'WellCostEstimator.WellLocationType') -> None: ...
    def toJson(self) -> java.lang.String: ...
    class WellLocationType(java.lang.Enum['WellCostEstimator.WellLocationType']):
        SUBSEA_WET_TREE: typing.ClassVar['WellCostEstimator.WellLocationType'] = ...
        PLATFORM_DRY_TREE: typing.ClassVar['WellCostEstimator.WellLocationType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'WellCostEstimator.WellLocationType': ...
        @staticmethod
        def values() -> typing.MutableSequence['WellCostEstimator.WellLocationType']: ...

class WellDesignCalculator(java.io.Serializable):
    def __init__(self): ...
    def calculateCasingDesign(self) -> None: ...
    def calculateCementVolumes(self) -> None: ...
    def calculateTubingDesign(self) -> None: ...
    def calculateWeights(self) -> None: ...
    def getCasingGradeSMTS(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getCasingGradeSMYS(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getIntermediateCasingWallThickness(self) -> float: ...
    def getMinBurstDesignFactor(self) -> float: ...
    def getMinCollapseDesignFactor(self) -> float: ...
    def getMinTensionDesignFactor(self) -> float: ...
    def getMinVmeDesignFactor(self) -> float: ...
    def getProductionCasingBurstDF(self) -> float: ...
    def getProductionCasingCollapseDF(self) -> float: ...
    def getProductionCasingTensionDF(self) -> float: ...
    def getProductionCasingVME_DF(self) -> float: ...
    def getProductionCasingWallThickness(self) -> float: ...
    def getSurfaceCasingWallThickness(self) -> float: ...
    def getTemperatureDeratingFactor(self) -> float: ...
    def getTotalCasingWeight(self) -> float: ...
    def getTotalCementVolume(self) -> float: ...
    def getTotalCuttingsVolume(self) -> float: ...
    def getTotalTubingWeight(self) -> float: ...
    def getTubingBurstDF(self) -> float: ...
    def getTubingWallThickness(self) -> float: ...
    def isInjectionWell(self) -> bool: ...
    def setConductorCasing(self, double: float, double2: float) -> None: ...
    def setInjectionWell(self, boolean: bool) -> None: ...
    def setIntermediateCasing(self, double: float, double2: float) -> None: ...
    def setMaxBottomholeTemperature(self, double: float) -> None: ...
    def setMaxWellheadPressure(self, double: float) -> None: ...
    def setMeasuredDepth(self, double: float) -> None: ...
    def setMinBurstDesignFactor(self, double: float) -> None: ...
    def setMinCollapseDesignFactor(self, double: float) -> None: ...
    def setMinTensionDesignFactor(self, double: float) -> None: ...
    def setMinVmeDesignFactor(self, double: float) -> None: ...
    def setProductionCasing(self, double: float, double2: float) -> None: ...
    def setProductionLiner(self, double: float, double2: float) -> None: ...
    def setReservoirPressure(self, double: float) -> None: ...
    def setReservoirTemperature(self, double: float) -> None: ...
    def setSurfaceCasing(self, double: float, double2: float) -> None: ...
    def setTrueVerticalDepth(self, double: float) -> None: ...
    def setTubing(self, double: float, double2: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class WellIntegrityScreening(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addAnnulus(self, annulusReading: 'WellIntegrityScreening.AnnulusReading') -> None: ...
    def getAnnulusResults(self) -> java.util.Map[java.lang.String, 'WellIntegrityScreening.AnnulusClassification']: ...
    def getAppliedStandards(self) -> java.util.List[java.lang.String]: ...
    def getDisposition(self) -> 'WellIntegrityScreening.IntegrityDisposition': ...
    def getFindings(self) -> java.util.List[java.lang.String]: ...
    def getWellId(self) -> java.lang.String: ...
    def getWellType(self) -> java.lang.String: ...
    def screen(self) -> 'WellIntegrityScreening.IntegrityDisposition': ...
    def setBarrierSchematic(self, wellBarrierSchematic: WellBarrierSchematic) -> None: ...
    def setWellType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class AnnulusClassification(java.lang.Enum['WellIntegrityScreening.AnnulusClassification']):
        NORMAL: typing.ClassVar['WellIntegrityScreening.AnnulusClassification'] = ...
        ELEVATED: typing.ClassVar['WellIntegrityScreening.AnnulusClassification'] = ...
        SUSTAINED_CASING_PRESSURE: typing.ClassVar['WellIntegrityScreening.AnnulusClassification'] = ...
        EXCEEDS_MAASP: typing.ClassVar['WellIntegrityScreening.AnnulusClassification'] = ...
        UNKNOWN: typing.ClassVar['WellIntegrityScreening.AnnulusClassification'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'WellIntegrityScreening.AnnulusClassification': ...
        @staticmethod
        def values() -> typing.MutableSequence['WellIntegrityScreening.AnnulusClassification']: ...
    class AnnulusReading(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float): ...
        def getId(self) -> java.lang.String: ...
        def getMaaspBara(self) -> float: ...
        def getMeasuredPressureBara(self) -> float: ...
        def isBleedsToZero(self) -> bool: ...
        def isRebuildsAfterBleed(self) -> bool: ...
        def isThermalEffectsExcluded(self) -> bool: ...
        def setBleedsToZero(self, boolean: bool) -> 'WellIntegrityScreening.AnnulusReading': ...
        def setRebuildsAfterBleed(self, boolean: bool) -> 'WellIntegrityScreening.AnnulusReading': ...
        def setThermalEffectsExcluded(self, boolean: bool) -> 'WellIntegrityScreening.AnnulusReading': ...
    class IntegrityDisposition(java.lang.Enum['WellIntegrityScreening.IntegrityDisposition']):
        ACCEPTABLE: typing.ClassVar['WellIntegrityScreening.IntegrityDisposition'] = ...
        MONITOR: typing.ClassVar['WellIntegrityScreening.IntegrityDisposition'] = ...
        INTERVENTION_REQUIRED: typing.ClassVar['WellIntegrityScreening.IntegrityDisposition'] = ...
        INSUFFICIENT_DATA: typing.ClassVar['WellIntegrityScreening.IntegrityDisposition'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'WellIntegrityScreening.IntegrityDisposition': ...
        @staticmethod
        def values() -> typing.MutableSequence['WellIntegrityScreening.IntegrityDisposition']: ...

class WellMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def calculateCostEstimate(self) -> None: ...
    def generateBillOfMaterials(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getBarrierNotes(self) -> java.util.List[java.lang.String]: ...
    def getBarrierSchematic(self) -> WellBarrierSchematic: ...
    def getCalculator(self) -> WellDesignCalculator: ...
    def getCompletionCostUSD(self) -> float: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getCostEstimator(self) -> WellCostEstimator: ...
    def getDataSource(self) -> 'WellMechanicalDesignDataSource': ...
    def getDesignStandardCode(self) -> java.lang.String: ...
    def getDrillingCostUSD(self) -> float: ...
    def getLoggingCostUSD(self) -> float: ...
    def getMaterialCostUSD(self) -> float: ...
    def getProductionCasingBurstDF(self) -> float: ...
    def getProductionCasingCollapseDF(self) -> float: ...
    def getProductionCasingTensionDF(self) -> float: ...
    def getProductionCasingVME_DF(self) -> float: ...
    def getProductionCasingWallThickness(self) -> float: ...
    def getTemperatureDeratingFactor(self) -> float: ...
    def getTotalCasingWeight(self) -> float: ...
    def getTotalCementVolume(self) -> float: ...
    def getTotalCostUSD(self) -> float: ...
    def getTotalTubingWeight(self) -> float: ...
    def getWellheadCostUSD(self) -> float: ...
    def isBarrierVerificationPassed(self) -> bool: ...
    def readDesignSpecifications(self) -> None: ...
    def setDesignStandardCode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRegion(self, region: SubseaCostEstimator.Region) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class WellMechanicalDesignDataSource(java.io.Serializable):
    def __init__(self): ...
    def clearAppliedStandards(self) -> None: ...
    def getAppliedStandards(self) -> java.util.List[java.lang.String]: ...
    def loadApiRp90Parameters(self) -> java.util.Map[java.lang.String, float]: ...
    def loadBarrierRequirements(self) -> java.util.Map[java.lang.String, float]: ...
    def loadIso16530Requirements(self) -> java.util.Map[java.lang.String, float]: ...
    def loadNorskD010DesignFactors(self, wellDesignCalculator: WellDesignCalculator, boolean: bool) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.subsea")``.

    BarrierElement: typing.Type[BarrierElement]
    BarrierEnvelope: typing.Type[BarrierEnvelope]
    DnvRpF109OnBottomStabilityAssessment: typing.Type[DnvRpF109OnBottomStabilityAssessment]
    DnvRpF109OnBottomStabilityCalculator: typing.Type[DnvRpF109OnBottomStabilityCalculator]
    DnvRpF109OnBottomStabilityInput: typing.Type[DnvRpF109OnBottomStabilityInput]
    DnvRpF109StabilityCheck: typing.Type[DnvRpF109StabilityCheck]
    FlexiblePipeMechanicalDesign: typing.Type[FlexiblePipeMechanicalDesign]
    FlowlineSizeSelector: typing.Type[FlowlineSizeSelector]
    PLEMMechanicalDesign: typing.Type[PLEMMechanicalDesign]
    PLETMechanicalDesign: typing.Type[PLETMechanicalDesign]
    SURFCostEstimator: typing.Type[SURFCostEstimator]
    StidWellBarrierDataSource: typing.Type[StidWellBarrierDataSource]
    SubseaBoosterMechanicalDesign: typing.Type[SubseaBoosterMechanicalDesign]
    SubseaCostEstimator: typing.Type[SubseaCostEstimator]
    SubseaJumperMechanicalDesign: typing.Type[SubseaJumperMechanicalDesign]
    SubseaManifoldMechanicalDesign: typing.Type[SubseaManifoldMechanicalDesign]
    SubseaTreeMechanicalDesign: typing.Type[SubseaTreeMechanicalDesign]
    TiebackThermalDesign: typing.Type[TiebackThermalDesign]
    UmbilicalMechanicalDesign: typing.Type[UmbilicalMechanicalDesign]
    WellBarrierSchematic: typing.Type[WellBarrierSchematic]
    WellCostEstimator: typing.Type[WellCostEstimator]
    WellDesignCalculator: typing.Type[WellDesignCalculator]
    WellIntegrityScreening: typing.Type[WellIntegrityScreening]
    WellMechanicalDesign: typing.Type[WellMechanicalDesign]
    WellMechanicalDesignDataSource: typing.Type[WellMechanicalDesignDataSource]
