
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import typing



class ExergyAnalysisReport(java.io.Serializable):
    def __init__(self, double: float): ...
    def addEntry(self, entry: 'ExergyAnalysisReport.Entry') -> None: ...
    def getDestructionByArea(self, string: typing.Union[java.lang.String, str]) -> java.util.Map[java.lang.String, float]: ...
    def getDestructionByType(self, string: typing.Union[java.lang.String, str]) -> java.util.Map[java.lang.String, float]: ...
    def getEntries(self) -> java.util.List['ExergyAnalysisReport.Entry']: ...
    def getSurroundingTemperatureK(self) -> float: ...
    def getTopDestructionHotspots(self, int: int) -> java.util.List['ExergyAnalysisReport.Entry']: ...
    def getTotalExergyChange(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTotalExergyDestruction(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def size(self) -> int: ...
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toString(self) -> java.lang.String: ...
    @typing.overload
    def toString(self, string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    class Entry(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float): ...
        def getArea(self) -> java.lang.String: ...
        def getExergyChange(self, string: typing.Union[java.lang.String, str]) -> float: ...
        def getExergyChangeJ(self) -> float: ...
        def getExergyDestruction(self, string: typing.Union[java.lang.String, str]) -> float: ...
        def getExergyDestructionJ(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getType(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.util.exergy")``.

    ExergyAnalysisReport: typing.Type[ExergyAnalysisReport]
