import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.thermo.system
import typing

class MultiphaseChokeFlow(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float): ...
    def calculateCriticalPressureRatio(
        self, double: float, double2: float
    ) -> float: ...
    def calculateDownstreamPressure(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
    ) -> float: ...
    def calculateGLR(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> float: ...
    def calculateGasQuality(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> float: ...
    def calculateMassFlowRate(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
    ) -> float: ...
    def calculateSizingResults(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
    ) -> java.util.Map[java.lang.String, typing.Any]: ...
    def determineFlowRegime(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
    ) -> "MultiphaseChokeFlow.FlowRegime": ...
    def getChokeArea(self) -> float: ...
    def getChokeDiameter(self) -> float: ...
    def getDischargeCoefficient(self) -> float: ...
    def getModelName(self) -> java.lang.String: ...
    def getPolytropicExponent(self) -> float: ...
    def getUpstreamDiameter(self) -> float: ...
    @typing.overload
    def setChokeDiameter(self, double: float) -> None: ...
    @typing.overload
    def setChokeDiameter(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setDischargeCoefficient(self, double: float) -> None: ...
    def setPolytropicExponent(self, double: float) -> None: ...
    def setUpstreamDiameter(self, double: float) -> None: ...

    class FlowRegime(java.lang.Enum["MultiphaseChokeFlow.FlowRegime"]):
        CRITICAL: typing.ClassVar["MultiphaseChokeFlow.FlowRegime"] = ...
        SUBCRITICAL: typing.ClassVar["MultiphaseChokeFlow.FlowRegime"] = ...
        UNKNOWN: typing.ClassVar["MultiphaseChokeFlow.FlowRegime"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "MultiphaseChokeFlow.FlowRegime": ...
        @staticmethod
        def values() -> typing.MutableSequence["MultiphaseChokeFlow.FlowRegime"]: ...

class MultiphaseChokeFlowFactory:
    @staticmethod
    def createDefaultModel() -> MultiphaseChokeFlow: ...
    @typing.overload
    @staticmethod
    def createModel(
        string: typing.Union[java.lang.String, str],
    ) -> MultiphaseChokeFlow: ...
    @typing.overload
    @staticmethod
    def createModel(
        modelType: "MultiphaseChokeFlowFactory.ModelType",
    ) -> MultiphaseChokeFlow: ...
    @typing.overload
    @staticmethod
    def createModel(
        modelType: "MultiphaseChokeFlowFactory.ModelType", double: float
    ) -> MultiphaseChokeFlow: ...
    @staticmethod
    def recommendModel(
        double: float, boolean: bool
    ) -> "MultiphaseChokeFlowFactory.ModelType": ...

    class ModelType(java.lang.Enum["MultiphaseChokeFlowFactory.ModelType"]):
        SACHDEVA: typing.ClassVar["MultiphaseChokeFlowFactory.ModelType"] = ...
        GILBERT: typing.ClassVar["MultiphaseChokeFlowFactory.ModelType"] = ...
        BAXENDELL: typing.ClassVar["MultiphaseChokeFlowFactory.ModelType"] = ...
        ROS: typing.ClassVar["MultiphaseChokeFlowFactory.ModelType"] = ...
        ACHONG: typing.ClassVar["MultiphaseChokeFlowFactory.ModelType"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "MultiphaseChokeFlowFactory.ModelType": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["MultiphaseChokeFlowFactory.ModelType"]
        ): ...

class GilbertChokeFlow(MultiphaseChokeFlow):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float): ...
    @typing.overload
    def __init__(self, correlationType: "GilbertChokeFlow.CorrelationType"): ...
    def calculateCriticalPressureRatio(
        self, double: float, double2: float
    ) -> float: ...
    def calculateDownstreamPressure(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
    ) -> float: ...
    def calculateMassFlowRate(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
    ) -> float: ...
    def calculateRequiredChokeDiameter(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
    ) -> float: ...
    def getCorrelationConstant(self) -> float: ...
    def getCorrelationType(self) -> "GilbertChokeFlow.CorrelationType": ...
    def getDiameterExponent(self) -> float: ...
    def getGlrExponent(self) -> float: ...
    def getModelName(self) -> java.lang.String: ...
    def setCorrelationConstant(self, double: float) -> None: ...
    def setCorrelationType(
        self, correlationType: "GilbertChokeFlow.CorrelationType"
    ) -> None: ...
    def setDiameterExponent(self, double: float) -> None: ...
    def setGlrExponent(self, double: float) -> None: ...

    class CorrelationType(java.lang.Enum["GilbertChokeFlow.CorrelationType"]):
        GILBERT: typing.ClassVar["GilbertChokeFlow.CorrelationType"] = ...
        BAXENDELL: typing.ClassVar["GilbertChokeFlow.CorrelationType"] = ...
        ROS: typing.ClassVar["GilbertChokeFlow.CorrelationType"] = ...
        ACHONG: typing.ClassVar["GilbertChokeFlow.CorrelationType"] = ...
        CUSTOM: typing.ClassVar["GilbertChokeFlow.CorrelationType"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "GilbertChokeFlow.CorrelationType": ...
        @staticmethod
        def values() -> typing.MutableSequence["GilbertChokeFlow.CorrelationType"]: ...

class SachdevaChokeFlow(MultiphaseChokeFlow):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float): ...
    def calculateCriticalPressureRatio(
        self, double: float, double2: float
    ) -> float: ...
    def calculateDownstreamPressure(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
    ) -> float: ...
    def calculateMassFlowRate(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        double: float,
        double2: float,
    ) -> float: ...
    def calculateVariableDischargeCoefficient(
        self, double: float, double2: float
    ) -> float: ...
    def getModelName(self) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.valve.choke")``.

    GilbertChokeFlow: typing.Type[GilbertChokeFlow]
    MultiphaseChokeFlow: typing.Type[MultiphaseChokeFlow]
    MultiphaseChokeFlowFactory: typing.Type[MultiphaseChokeFlowFactory]
    SachdevaChokeFlow: typing.Type[SachdevaChokeFlow]
