
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jneqsim.fluidmechanics.geometrydefinitions.internalgeometry.wall
import typing



class SurroundingEnvironment:
    def getHeatTransferCoefficient(self) -> float: ...
    def getTemperature(self) -> float: ...
    def setHeatTransferCoefficient(self, double: float) -> None: ...
    def setTemperature(self, double: float) -> None: ...

class SurroundingEnvironmentBaseClass(SurroundingEnvironment):
    def __init__(self): ...
    def getHeatTransferCoefficient(self) -> float: ...
    def getTemperature(self) -> float: ...
    def setHeatTransferCoefficient(self, double: float) -> None: ...
    def setTemperature(self, double: float) -> None: ...

class PipeSurroundingEnvironment(SurroundingEnvironmentBaseClass):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @staticmethod
    def buriedPipe(double: float, double2: float, double3: float, pipeMaterial: jneqsim.fluidmechanics.geometrydefinitions.internalgeometry.wall.PipeMaterial) -> 'PipeSurroundingEnvironment': ...
    @staticmethod
    def calcBuriedPipeHeatTransferCoefficient(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def calcBuriedPipeThermalResistance(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def exposedToAir(double: float, double2: float) -> 'PipeSurroundingEnvironment': ...
    def getBurialDepth(self) -> float: ...
    def getEnvironmentType(self) -> 'PipeSurroundingEnvironment.EnvironmentType': ...
    def getSeawaterVelocity(self) -> float: ...
    def getSoilConductivity(self) -> float: ...
    def getWindVelocity(self) -> float: ...
    def isBuried(self) -> bool: ...
    def isSubsea(self) -> bool: ...
    def setForAir(self, double: float) -> None: ...
    def setForBuried(self, double: float, double2: float, pipeMaterial: jneqsim.fluidmechanics.geometrydefinitions.internalgeometry.wall.PipeMaterial) -> None: ...
    def setForSeawater(self, double: float) -> None: ...
    @staticmethod
    def subseaPipe(double: float, double2: float) -> 'PipeSurroundingEnvironment': ...
    def toString(self) -> java.lang.String: ...
    class EnvironmentType(java.lang.Enum['PipeSurroundingEnvironment.EnvironmentType']):
        AIR: typing.ClassVar['PipeSurroundingEnvironment.EnvironmentType'] = ...
        SEAWATER: typing.ClassVar['PipeSurroundingEnvironment.EnvironmentType'] = ...
        BURIED: typing.ClassVar['PipeSurroundingEnvironment.EnvironmentType'] = ...
        CUSTOM: typing.ClassVar['PipeSurroundingEnvironment.EnvironmentType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PipeSurroundingEnvironment.EnvironmentType': ...
        @staticmethod
        def values() -> typing.MutableSequence['PipeSurroundingEnvironment.EnvironmentType']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.fluidmechanics.geometrydefinitions.surrounding")``.

    PipeSurroundingEnvironment: typing.Type[PipeSurroundingEnvironment]
    SurroundingEnvironment: typing.Type[SurroundingEnvironment]
    SurroundingEnvironmentBaseClass: typing.Type[SurroundingEnvironmentBaseClass]
