
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.process.measurementdevice
import jneqsim.process.mechanicaldesign.valve
import jneqsim.process.util.report
import jneqsim.thermo.system
import typing



class ValveInterface(jneqsim.process.equipment.ProcessEquipmentInterface, jneqsim.process.equipment.TwoPortInterface):
    def equals(self, object: typing.Any) -> bool: ...
    def getCg(self) -> float: ...
    def getClosingTravelTime(self) -> float: ...
    @typing.overload
    def getCv(self) -> float: ...
    @typing.overload
    def getCv(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getKv(self) -> float: ...
    def getOpeningTravelTime(self) -> float: ...
    def getPercentValveOpening(self) -> float: ...
    def getTargetPercentValveOpening(self) -> float: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getTravelModel(self) -> 'ValveTravelModel': ...
    def getTravelTime(self) -> float: ...
    def getTravelTimeConstant(self) -> float: ...
    def hashCode(self) -> int: ...
    def isIsoThermal(self) -> bool: ...
    def setClosingTravelTime(self, double: float) -> None: ...
    @typing.overload
    def setCv(self, double: float) -> None: ...
    @typing.overload
    def setCv(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setIsoThermal(self, boolean: bool) -> None: ...
    def setKv(self, double: float) -> None: ...
    def setOpeningTravelTime(self, double: float) -> None: ...
    def setPercentValveOpening(self, double: float) -> None: ...
    def setTargetPercentValveOpening(self, double: float) -> None: ...
    def setTravelModel(self, valveTravelModel: 'ValveTravelModel') -> None: ...
    def setTravelTime(self, double: float) -> None: ...
    def setTravelTimeConstant(self, double: float) -> None: ...

class ValveTravelModel(java.lang.Enum['ValveTravelModel']):
    NONE: typing.ClassVar['ValveTravelModel'] = ...
    LINEAR_RATE_LIMIT: typing.ClassVar['ValveTravelModel'] = ...
    FIRST_ORDER_LAG: typing.ClassVar['ValveTravelModel'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'ValveTravelModel': ...
    @staticmethod
    def values() -> typing.MutableSequence['ValveTravelModel']: ...

class ThrottlingValve(jneqsim.process.equipment.TwoPortEquipment, ValveInterface):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def calcKv(self) -> None: ...
    def calculateMolarFlow(self) -> float: ...
    def calculateOutletPressure(self, double: float) -> float: ...
    def displayResult(self) -> None: ...
    def getCapacityDuty(self) -> float: ...
    def getCapacityMax(self) -> float: ...
    def getCg(self) -> float: ...
    def getClosingTravelTime(self) -> float: ...
    @typing.overload
    def getCv(self) -> float: ...
    @typing.overload
    def getCv(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getDeltaPressure(self) -> float: ...
    @typing.overload
    def getDeltaPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getEntropyProduction(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getExergyChange(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getExergyChange(self, string: typing.Union[java.lang.String, str], double: float) -> float: ...
    def getFp(self) -> float: ...
    def getInletPressure(self) -> float: ...
    def getKv(self) -> float: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.valve.ValveMechanicalDesign: ...
    def getOpeningTravelTime(self) -> float: ...
    def getOutletPressure(self) -> float: ...
    def getPercentValveOpening(self) -> float: ...
    def getResultTable(self) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def getTargetPercentValveOpening(self) -> float: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getTravelModel(self) -> ValveTravelModel: ...
    def getTravelTime(self) -> float: ...
    def getTravelTimeConstant(self) -> float: ...
    def initMechanicalDesign(self) -> None: ...
    def isAcceptNegativeDP(self) -> bool: ...
    def isAllowChoked(self) -> bool: ...
    def isAllowLaminar(self) -> bool: ...
    def isGasValve(self) -> bool: ...
    def isIsoThermal(self) -> bool: ...
    def isValveKvSet(self) -> bool: ...
    def needRecalculation(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def runController(self, double: float, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setAcceptNegativeDP(self, boolean: bool) -> None: ...
    def setAllowChoked(self, boolean: bool) -> None: ...
    def setAllowLaminar(self, boolean: bool) -> None: ...
    def setClosingTravelTime(self, double: float) -> None: ...
    @typing.overload
    def setCv(self, double: float) -> None: ...
    @typing.overload
    def setCv(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDeltaPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setFp(self, double: float) -> None: ...
    def setGasValve(self, boolean: bool) -> None: ...
    def setIsCalcOutPressure(self, boolean: bool) -> None: ...
    def setIsoThermal(self, boolean: bool) -> None: ...
    def setKv(self, double: float) -> None: ...
    def setMaximumValveOpening(self, double: float) -> None: ...
    def setMinimumValveOpening(self, double: float) -> None: ...
    def setOpeningTravelTime(self, double: float) -> None: ...
    @typing.overload
    def setOutletPressure(self, double: float) -> None: ...
    @typing.overload
    def setOutletPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPercentValveOpening(self, double: float) -> None: ...
    @typing.overload
    def setPressure(self, double: float) -> None: ...
    @typing.overload
    def setPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTargetPercentValveOpening(self, double: float) -> None: ...
    def setTravelModel(self, valveTravelModel: ValveTravelModel) -> None: ...
    def setTravelTime(self, double: float) -> None: ...
    def setTravelTimeConstant(self, double: float) -> None: ...
    def setValveKvSet(self, boolean: bool) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...

class BlowdownValve(ThrottlingValve):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def activate(self) -> None: ...
    def close(self) -> None: ...
    def getOpeningTime(self) -> float: ...
    def getTimeElapsed(self) -> float: ...
    def isActivated(self) -> bool: ...
    def isOpening(self) -> bool: ...
    def reset(self) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setOpeningTime(self, double: float) -> None: ...
    def toString(self) -> java.lang.String: ...

class CheckValve(ThrottlingValve):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getCrackingPressure(self) -> float: ...
    def isOpen(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setCrackingPressure(self, double: float) -> None: ...
    def toString(self) -> java.lang.String: ...

class ControlValve(ThrottlingValve):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def toString(self) -> java.lang.String: ...

class ESDValve(ThrottlingValve):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def completePartialStrokeTest(self) -> None: ...
    def deEnergize(self) -> None: ...
    def energize(self) -> None: ...
    def getFailSafePosition(self) -> float: ...
    def getStrokeTime(self) -> float: ...
    def getTimeElapsedSinceTrip(self) -> float: ...
    def hasTripCompleted(self) -> bool: ...
    def isClosing(self) -> bool: ...
    def isEnergized(self) -> bool: ...
    def isPartialStrokeTestActive(self) -> bool: ...
    def reset(self) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setFailSafePosition(self, double: float) -> None: ...
    def setStrokeTime(self, double: float) -> None: ...
    def startPartialStrokeTest(self, double: float) -> None: ...
    def toString(self) -> java.lang.String: ...
    def trip(self) -> None: ...

class HIPPSValve(ThrottlingValve):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def addPressureTransmitter(self, measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface) -> None: ...
    def getActiveTransmitterCount(self) -> int: ...
    def getClosureTime(self) -> float: ...
    def getDiagnostics(self) -> java.lang.String: ...
    def getLastTripTime(self) -> float: ...
    def getPressureTransmitters(self) -> java.util.List[jneqsim.process.measurementdevice.MeasurementDeviceInterface]: ...
    def getProofTestInterval(self) -> float: ...
    def getSILRating(self) -> int: ...
    def getSpuriousTripCount(self) -> int: ...
    def getTimeSinceProofTest(self) -> float: ...
    def getVotingLogic(self) -> 'HIPPSValve.VotingLogic': ...
    def hasTripped(self) -> bool: ...
    def isPartialStrokeTestActive(self) -> bool: ...
    def isProofTestDue(self) -> bool: ...
    def isTripEnabled(self) -> bool: ...
    def performPartialStrokeTest(self, double: float) -> None: ...
    def performProofTest(self) -> None: ...
    def recordSpuriousTrip(self) -> None: ...
    def removePressureTransmitter(self, measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface) -> None: ...
    def reset(self) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setClosureTime(self, double: float) -> None: ...
    def setPercentValveOpening(self, double: float) -> None: ...
    def setProofTestInterval(self, double: float) -> None: ...
    def setSILRating(self, int: int) -> None: ...
    def setTripEnabled(self, boolean: bool) -> None: ...
    def setVotingLogic(self, votingLogic: 'HIPPSValve.VotingLogic') -> None: ...
    def toString(self) -> java.lang.String: ...
    class VotingLogic(java.lang.Enum['HIPPSValve.VotingLogic']):
        ONE_OUT_OF_ONE: typing.ClassVar['HIPPSValve.VotingLogic'] = ...
        ONE_OUT_OF_TWO: typing.ClassVar['HIPPSValve.VotingLogic'] = ...
        TWO_OUT_OF_TWO: typing.ClassVar['HIPPSValve.VotingLogic'] = ...
        TWO_OUT_OF_THREE: typing.ClassVar['HIPPSValve.VotingLogic'] = ...
        TWO_OUT_OF_FOUR: typing.ClassVar['HIPPSValve.VotingLogic'] = ...
        def getNotation(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'HIPPSValve.VotingLogic': ...
        @staticmethod
        def values() -> typing.MutableSequence['HIPPSValve.VotingLogic']: ...

class PSDValve(ThrottlingValve):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getClosureTime(self) -> float: ...
    def getPressureTransmitter(self) -> jneqsim.process.measurementdevice.MeasurementDeviceInterface: ...
    def hasTripped(self) -> bool: ...
    def isTripEnabled(self) -> bool: ...
    def linkToPressureTransmitter(self, measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface) -> None: ...
    def reset(self) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setClosureTime(self, double: float) -> None: ...
    def setPercentValveOpening(self, double: float) -> None: ...
    def setTripEnabled(self, boolean: bool) -> None: ...
    def toString(self) -> java.lang.String: ...

class RuptureDisk(ThrottlingValve):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getBurstPressure(self) -> float: ...
    def getFullOpenPressure(self) -> float: ...
    def hasRuptured(self) -> bool: ...
    def reset(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setBurstPressure(self, double: float) -> None: ...
    def setFullOpenPressure(self, double: float) -> None: ...

class SafetyReliefValve(ThrottlingValve):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def configureBalancedModulating(self, double: float, double2: float, double3: float, double4: float) -> 'SafetyReliefValve': ...
    def configureConventionalSnap(self, double: float, double2: float, double3: float, double4: float) -> 'SafetyReliefValve': ...
    def getBackpressureSensitivity(self) -> float: ...
    def getBlowdownFrac(self) -> float: ...
    def getKbMax(self) -> float: ...
    def getKd(self) -> float: ...
    def getMinStableOpenFrac(self) -> float: ...
    def getOpenFraction(self) -> float: ...
    def getOpeningLaw(self) -> 'SafetyReliefValve.OpeningLaw': ...
    def getOverpressureFrac(self) -> float: ...
    def getRatedCv(self) -> float: ...
    def getRelievingPressureBar(self) -> float: ...
    def getReseatPressureBar(self) -> float: ...
    def getSetPressureBar(self) -> float: ...
    def getValveType(self) -> 'SafetyReliefValve.ValveType': ...
    def initMechanicalDesign(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setBackpressureSensitivity(self, double: float) -> None: ...
    def setBlowdownFrac(self, double: float) -> None: ...
    def setKbMax(self, double: float) -> None: ...
    def setKd(self, double: float) -> None: ...
    def setMaxLiftRatePerSec(self, double: float) -> None: ...
    def setMinCloseTimeSec(self, double: float) -> None: ...
    def setMinOpenTimeSec(self, double: float) -> None: ...
    def setMinStableOpenFrac(self, double: float) -> None: ...
    def setOpeningLaw(self, openingLaw: 'SafetyReliefValve.OpeningLaw') -> None: ...
    def setOverpressureFrac(self, double: float) -> None: ...
    def setRatedCv(self, double: float) -> None: ...
    def setSetPressureBar(self, double: float) -> None: ...
    def setTauCloseSec(self, double: float) -> None: ...
    def setTauOpenSec(self, double: float) -> None: ...
    def setValveType(self, valveType: 'SafetyReliefValve.ValveType') -> None: ...
    class OpeningLaw(java.lang.Enum['SafetyReliefValve.OpeningLaw']):
        SNAP: typing.ClassVar['SafetyReliefValve.OpeningLaw'] = ...
        MODULATING: typing.ClassVar['SafetyReliefValve.OpeningLaw'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyReliefValve.OpeningLaw': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyReliefValve.OpeningLaw']: ...
    class ValveType(java.lang.Enum['SafetyReliefValve.ValveType']):
        CONVENTIONAL: typing.ClassVar['SafetyReliefValve.ValveType'] = ...
        BALANCED_BELLOWS: typing.ClassVar['SafetyReliefValve.ValveType'] = ...
        PILOT_MODULATING: typing.ClassVar['SafetyReliefValve.ValveType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyReliefValve.ValveType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyReliefValve.ValveType']: ...

class SafetyValve(ThrottlingValve):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def addScenario(self, relievingScenario: 'SafetyValve.RelievingScenario') -> 'SafetyValve': ...
    def clearRelievingScenarios(self) -> None: ...
    def ensureDefaultScenario(self) -> None: ...
    def getActiveScenario(self) -> java.util.Optional['SafetyValve.RelievingScenario']: ...
    def getActiveScenarioName(self) -> java.util.Optional[java.lang.String]: ...
    def getBlowdownPressure(self) -> float: ...
    def getFullOpenPressure(self) -> float: ...
    def getPressureSpec(self) -> float: ...
    def getRelievingScenarios(self) -> java.util.List['SafetyValve.RelievingScenario']: ...
    def initMechanicalDesign(self) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setActiveScenario(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setBlowdown(self, double: float) -> None: ...
    def setBlowdownPressure(self, double: float) -> None: ...
    def setFullOpenPressure(self, double: float) -> None: ...
    def setPressureSpec(self, double: float) -> None: ...
    def setRelievingScenarios(self, list: java.util.List['SafetyValve.RelievingScenario']) -> None: ...
    class FluidService(java.lang.Enum['SafetyValve.FluidService']):
        GAS: typing.ClassVar['SafetyValve.FluidService'] = ...
        LIQUID: typing.ClassVar['SafetyValve.FluidService'] = ...
        MULTIPHASE: typing.ClassVar['SafetyValve.FluidService'] = ...
        FIRE: typing.ClassVar['SafetyValve.FluidService'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyValve.FluidService': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyValve.FluidService']: ...
    class RelievingScenario(java.io.Serializable):
        def getBackPressure(self) -> float: ...
        def getBackPressureCorrection(self) -> java.util.Optional[float]: ...
        def getDischargeCoefficient(self) -> java.util.Optional[float]: ...
        def getFluidService(self) -> 'SafetyValve.FluidService': ...
        def getInstallationCorrection(self) -> java.util.Optional[float]: ...
        def getName(self) -> java.lang.String: ...
        def getOverpressureFraction(self) -> float: ...
        def getRelievingStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
        def getSetPressure(self) -> java.util.Optional[float]: ...
        def getSizingStandard(self) -> 'SafetyValve.SizingStandard': ...
        class Builder:
            def __init__(self, string: typing.Union[java.lang.String, str]): ...
            def backPressure(self, double: float) -> 'SafetyValve.RelievingScenario.Builder': ...
            def backPressureCorrection(self, double: float) -> 'SafetyValve.RelievingScenario.Builder': ...
            def build(self) -> 'SafetyValve.RelievingScenario': ...
            def dischargeCoefficient(self, double: float) -> 'SafetyValve.RelievingScenario.Builder': ...
            def fluidService(self, fluidService: 'SafetyValve.FluidService') -> 'SafetyValve.RelievingScenario.Builder': ...
            def installationCorrection(self, double: float) -> 'SafetyValve.RelievingScenario.Builder': ...
            def overpressureFraction(self, double: float) -> 'SafetyValve.RelievingScenario.Builder': ...
            def relievingStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> 'SafetyValve.RelievingScenario.Builder': ...
            def setPressure(self, double: float) -> 'SafetyValve.RelievingScenario.Builder': ...
            def sizingStandard(self, sizingStandard: 'SafetyValve.SizingStandard') -> 'SafetyValve.RelievingScenario.Builder': ...
    class SizingStandard(java.lang.Enum['SafetyValve.SizingStandard']):
        API_520: typing.ClassVar['SafetyValve.SizingStandard'] = ...
        ISO_4126: typing.ClassVar['SafetyValve.SizingStandard'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyValve.SizingStandard': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyValve.SizingStandard']: ...

class LevelControlValve(ControlValve):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getControlAction(self) -> 'LevelControlValve.ControlAction': ...
    def getControlError(self) -> float: ...
    def getControllerGain(self) -> float: ...
    def getFailSafePosition(self) -> float: ...
    def getLevelSetpoint(self) -> float: ...
    def getMeasuredLevel(self) -> float: ...
    def isAutoMode(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setAutoMode(self, boolean: bool) -> None: ...
    def setControlAction(self, controlAction: 'LevelControlValve.ControlAction') -> None: ...
    def setControllerGain(self, double: float) -> None: ...
    def setFailSafePosition(self, double: float) -> None: ...
    def setLevelSetpoint(self, double: float) -> None: ...
    def setMeasuredLevel(self, double: float) -> None: ...
    def toString(self) -> java.lang.String: ...
    class ControlAction(java.lang.Enum['LevelControlValve.ControlAction']):
        DIRECT: typing.ClassVar['LevelControlValve.ControlAction'] = ...
        REVERSE: typing.ClassVar['LevelControlValve.ControlAction'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'LevelControlValve.ControlAction': ...
        @staticmethod
        def values() -> typing.MutableSequence['LevelControlValve.ControlAction']: ...

class PressureControlValve(ControlValve):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getControlError(self) -> float: ...
    def getControlMode(self) -> 'PressureControlValve.ControlMode': ...
    def getControllerGain(self) -> float: ...
    def getPressureSetpoint(self) -> float: ...
    def getProcessVariable(self) -> float: ...
    def isAutoMode(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setAutoMode(self, boolean: bool) -> None: ...
    def setControlMode(self, controlMode: 'PressureControlValve.ControlMode') -> None: ...
    def setControllerGain(self, double: float) -> None: ...
    def setPressureSetpoint(self, double: float) -> None: ...
    def toString(self) -> java.lang.String: ...
    class ControlMode(java.lang.Enum['PressureControlValve.ControlMode']):
        DOWNSTREAM: typing.ClassVar['PressureControlValve.ControlMode'] = ...
        UPSTREAM: typing.ClassVar['PressureControlValve.ControlMode'] = ...
        DIFFERENTIAL: typing.ClassVar['PressureControlValve.ControlMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PressureControlValve.ControlMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['PressureControlValve.ControlMode']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.valve")``.

    BlowdownValve: typing.Type[BlowdownValve]
    CheckValve: typing.Type[CheckValve]
    ControlValve: typing.Type[ControlValve]
    ESDValve: typing.Type[ESDValve]
    HIPPSValve: typing.Type[HIPPSValve]
    LevelControlValve: typing.Type[LevelControlValve]
    PSDValve: typing.Type[PSDValve]
    PressureControlValve: typing.Type[PressureControlValve]
    RuptureDisk: typing.Type[RuptureDisk]
    SafetyReliefValve: typing.Type[SafetyReliefValve]
    SafetyValve: typing.Type[SafetyValve]
    ThrottlingValve: typing.Type[ThrottlingValve]
    ValveInterface: typing.Type[ValveInterface]
    ValveTravelModel: typing.Type[ValveTravelModel]
