
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import com.google.gson
import java.lang
import java.util
import jneqsim.process.processmodel
import typing



class MaterialNode:
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
    def getComponentName(self) -> java.lang.String: ...
    def getDescription(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...

class OperationOption:
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def addInputMaterial(self, string: typing.Union[java.lang.String, str]) -> 'OperationOption': ...
    def addOutputMaterial(self, string: typing.Union[java.lang.String, str]) -> 'OperationOption': ...
    def getDescription(self) -> java.lang.String: ...
    def getEquipmentType(self) -> java.lang.String: ...
    def getInputMaterials(self) -> java.util.List[java.lang.String]: ...
    def getName(self) -> java.lang.String: ...
    def getOutputMaterials(self) -> java.util.List[java.lang.String]: ...
    def getProperties(self) -> java.util.Map[java.lang.String, com.google.gson.JsonElement]: ...
    def propertiesToJson(self) -> com.google.gson.JsonObject: ...
    def setDescription(self, string: typing.Union[java.lang.String, str]) -> 'OperationOption': ...
    @typing.overload
    def setProperty(self, string: typing.Union[java.lang.String, str], double: float) -> 'OperationOption': ...
    @typing.overload
    def setProperty(self, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str]) -> 'OperationOption': ...
    @typing.overload
    def setProperty(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'OperationOption': ...

class ProcessCandidate:
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
    def addAssumption(self, string: typing.Union[java.lang.String, str]) -> 'ProcessCandidate': ...
    def addError(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def addObjectiveValue(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def addProductStreamReference(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'ProcessCandidate': ...
    def addSynthesisPathStep(self, string: typing.Union[java.lang.String, str]) -> 'ProcessCandidate': ...
    def addWarning(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def getAssumptions(self) -> java.util.List[java.lang.String]: ...
    def getDescription(self) -> java.lang.String: ...
    def getDominanceReason(self) -> java.lang.String: ...
    def getErrors(self) -> java.util.List[java.lang.String]: ...
    def getGenerationMethod(self) -> java.lang.String: ...
    def getId(self) -> java.lang.String: ...
    def getJsonDefinition(self) -> java.lang.String: ...
    def getMetrics(self) -> 'ProcessResearchMetrics': ...
    def getName(self) -> java.lang.String: ...
    def getObjectiveValues(self) -> java.util.Map[java.lang.String, float]: ...
    def getProcessSystem(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getProductStreamReference(self, string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    def getProductStreamReferences(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def getScore(self) -> float: ...
    def getSynthesisPath(self) -> java.util.List[java.lang.String]: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isDominated(self) -> bool: ...
    def isFeasible(self) -> bool: ...
    def isOptimized(self) -> bool: ...
    def setDescription(self, string: typing.Union[java.lang.String, str]) -> 'ProcessCandidate': ...
    def setDominanceReason(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDominated(self, boolean: bool) -> None: ...
    def setFeasible(self, boolean: bool) -> None: ...
    def setJsonDefinition(self, string: typing.Union[java.lang.String, str]) -> 'ProcessCandidate': ...
    def setMetrics(self, processResearchMetrics: 'ProcessResearchMetrics') -> None: ...
    def setOptimized(self, boolean: bool) -> None: ...
    def setProcessSystem(self, processSystem: jneqsim.process.processmodel.ProcessSystem) -> None: ...
    def setScore(self, double: float) -> None: ...

class ProcessCandidateEvaluator:
    def __init__(self): ...
    def evaluate(self, processCandidate: ProcessCandidate, processResearchSpec: 'ProcessResearchSpec') -> None: ...

class ProcessCandidateGenerator:
    def __init__(self): ...
    def generate(self, processResearchSpec: 'ProcessResearchSpec') -> java.util.List[ProcessCandidate]: ...

class ProcessResearchMetrics:
    def __init__(self): ...
    def add(self, string: typing.Union[java.lang.String, str], double: float) -> 'ProcessResearchMetrics': ...
    def asMap(self) -> java.util.Map[java.lang.String, float]: ...
    def get(self, string: typing.Union[java.lang.String, str], double: float) -> float: ...
    def set(self, string: typing.Union[java.lang.String, str], double: float) -> 'ProcessResearchMetrics': ...

class ProcessResearchResult:
    def __init__(self): ...
    def addCandidate(self, processCandidate: ProcessCandidate) -> None: ...
    def addMessage(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def getBestCandidate(self) -> ProcessCandidate: ...
    def getCandidates(self) -> java.util.List[ProcessCandidate]: ...
    def getMessages(self) -> java.util.List[java.lang.String]: ...
    def getNonDominatedCandidates(self) -> java.util.List[ProcessCandidate]: ...
    def sortCandidates(self) -> None: ...

class ProcessResearchSpec:
    def __init__(self): ...
    def allowsUnitType(self, string: typing.Union[java.lang.String, str]) -> bool: ...
    @staticmethod
    def builder() -> 'ProcessResearchSpec.Builder': ...
    def getAllowedUnitTypes(self) -> java.util.List[java.lang.String]: ...
    def getDecisionVariables(self) -> java.util.List['ProcessResearchSpec.DecisionVariable']: ...
    def getEconomicAssumptions(self) -> 'ProcessResearchSpec.EconomicAssumptions': ...
    def getFeedComponents(self) -> java.util.Map[java.lang.String, float]: ...
    def getFeedFlowRate(self) -> float: ...
    def getFeedFlowUnit(self) -> java.lang.String: ...
    def getFeedMaterialName(self) -> java.lang.String: ...
    def getFeedPressureBara(self) -> float: ...
    def getFeedTemperatureK(self) -> float: ...
    def getFluidModel(self) -> java.lang.String: ...
    def getHeatIntegrationDeltaTMinC(self) -> float: ...
    def getMaterialNodes(self) -> java.util.List[MaterialNode]: ...
    def getMaxCandidates(self) -> int: ...
    def getMaxOptimizationCases(self) -> int: ...
    def getMaxSynthesisDepth(self) -> int: ...
    def getMixingRule(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getObjective(self) -> 'ProcessResearchSpec.Objective': ...
    def getOperationOptions(self) -> java.util.List[OperationOption]: ...
    def getProductTargets(self) -> java.util.List['ProcessResearchSpec.ProductTarget']: ...
    def getReactionOptions(self) -> java.util.List['ReactionOption']: ...
    def getRobustnessScenarios(self) -> java.util.List['ProcessResearchSpec.RobustnessScenario']: ...
    def getScoringWeights(self) -> 'ProcessResearchSpec.ScoringWeights': ...
    def getSynthesisConstraints(self) -> 'ProcessResearchSpec.SynthesisConstraints': ...
    def isEvaluateCandidates(self) -> bool: ...
    def isFeasibilityPruningEnabled(self) -> bool: ...
    def isIncludeCostEstimate(self) -> bool: ...
    def isIncludeEmissionEstimate(self) -> bool: ...
    def isIncludeHeatIntegration(self) -> bool: ...
    def isIncludeSynthesisLibrary(self) -> bool: ...
    class Builder:
        def __init__(self): ...
        def addAllowedUnitType(self, string: typing.Union[java.lang.String, str]) -> 'ProcessResearchSpec.Builder': ...
        def addDecisionVariable(self, decisionVariable: 'ProcessResearchSpec.DecisionVariable') -> 'ProcessResearchSpec.Builder': ...
        def addFeedComponent(self, string: typing.Union[java.lang.String, str], double: float) -> 'ProcessResearchSpec.Builder': ...
        def addMaterialNode(self, materialNode: MaterialNode) -> 'ProcessResearchSpec.Builder': ...
        def addOperationOption(self, operationOption: OperationOption) -> 'ProcessResearchSpec.Builder': ...
        def addProductTarget(self, productTarget: 'ProcessResearchSpec.ProductTarget') -> 'ProcessResearchSpec.Builder': ...
        def addReactionOption(self, reactionOption: 'ReactionOption') -> 'ProcessResearchSpec.Builder': ...
        def addRobustnessScenario(self, robustnessScenario: 'ProcessResearchSpec.RobustnessScenario') -> 'ProcessResearchSpec.Builder': ...
        def build(self) -> 'ProcessResearchSpec': ...
        def setEconomicAssumptions(self, economicAssumptions: 'ProcessResearchSpec.EconomicAssumptions') -> 'ProcessResearchSpec.Builder': ...
        def setEnableFeasibilityPruning(self, boolean: bool) -> 'ProcessResearchSpec.Builder': ...
        def setEvaluateCandidates(self, boolean: bool) -> 'ProcessResearchSpec.Builder': ...
        def setFeedFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> 'ProcessResearchSpec.Builder': ...
        def setFeedMaterialName(self, string: typing.Union[java.lang.String, str]) -> 'ProcessResearchSpec.Builder': ...
        def setFeedPressure(self, double: float) -> 'ProcessResearchSpec.Builder': ...
        def setFeedTemperature(self, double: float) -> 'ProcessResearchSpec.Builder': ...
        def setFluidModel(self, string: typing.Union[java.lang.String, str]) -> 'ProcessResearchSpec.Builder': ...
        def setHeatIntegrationDeltaTMinC(self, double: float) -> 'ProcessResearchSpec.Builder': ...
        def setIncludeCostEstimate(self, boolean: bool) -> 'ProcessResearchSpec.Builder': ...
        def setIncludeEmissionEstimate(self, boolean: bool) -> 'ProcessResearchSpec.Builder': ...
        def setIncludeHeatIntegration(self, boolean: bool) -> 'ProcessResearchSpec.Builder': ...
        def setIncludeSynthesisLibrary(self, boolean: bool) -> 'ProcessResearchSpec.Builder': ...
        def setMaxCandidates(self, int: int) -> 'ProcessResearchSpec.Builder': ...
        def setMaxOptimizationCases(self, int: int) -> 'ProcessResearchSpec.Builder': ...
        def setMaxSynthesisDepth(self, int: int) -> 'ProcessResearchSpec.Builder': ...
        def setMixingRule(self, string: typing.Union[java.lang.String, str]) -> 'ProcessResearchSpec.Builder': ...
        def setName(self, string: typing.Union[java.lang.String, str]) -> 'ProcessResearchSpec.Builder': ...
        def setObjective(self, objective: 'ProcessResearchSpec.Objective') -> 'ProcessResearchSpec.Builder': ...
        def setScoringWeights(self, scoringWeights: 'ProcessResearchSpec.ScoringWeights') -> 'ProcessResearchSpec.Builder': ...
        def setSynthesisConstraints(self, synthesisConstraints: 'ProcessResearchSpec.SynthesisConstraints') -> 'ProcessResearchSpec.Builder': ...
    class DecisionVariable:
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float, string3: typing.Union[java.lang.String, str]): ...
        def getEquipmentName(self) -> java.lang.String: ...
        def getGridLevels(self) -> int: ...
        def getLowerBound(self) -> float: ...
        def getPropertyName(self) -> java.lang.String: ...
        def getUnit(self) -> java.lang.String: ...
        def getUpperBound(self) -> float: ...
        def setGridLevels(self, int: int) -> 'ProcessResearchSpec.DecisionVariable': ...
    class EconomicAssumptions:
        def __init__(self): ...
        def getCarbonPriceUsdPerTonne(self) -> float: ...
        def getColdUtilityCostUsdPerKWh(self) -> float: ...
        def getElectricityCostUsdPerKWh(self) -> float: ...
        def getElectricityEmissionFactorKgCO2PerKWh(self) -> float: ...
        def getEquipmentCostProxyUsd(self, string: typing.Union[java.lang.String, str]) -> float: ...
        def getHotUtilityCostUsdPerKWh(self) -> float: ...
        def getOperatingHoursPerYear(self) -> float: ...
        def setCarbonPriceUsdPerTonne(self, double: float) -> 'ProcessResearchSpec.EconomicAssumptions': ...
        def setColdUtilityCostUsdPerKWh(self, double: float) -> 'ProcessResearchSpec.EconomicAssumptions': ...
        def setDefaultEquipmentCostUsd(self, double: float) -> 'ProcessResearchSpec.EconomicAssumptions': ...
        def setElectricityCostUsdPerKWh(self, double: float) -> 'ProcessResearchSpec.EconomicAssumptions': ...
        def setElectricityEmissionFactorKgCO2PerKWh(self, double: float) -> 'ProcessResearchSpec.EconomicAssumptions': ...
        def setEquipmentCostProxyUsd(self, string: typing.Union[java.lang.String, str], double: float) -> 'ProcessResearchSpec.EconomicAssumptions': ...
        def setHotUtilityCostUsdPerKWh(self, double: float) -> 'ProcessResearchSpec.EconomicAssumptions': ...
        def setOperatingHoursPerYear(self, double: float) -> 'ProcessResearchSpec.EconomicAssumptions': ...
    class Objective(java.lang.Enum['ProcessResearchSpec.Objective']):
        MAXIMIZE_PRODUCT: typing.ClassVar['ProcessResearchSpec.Objective'] = ...
        MINIMIZE_ENERGY: typing.ClassVar['ProcessResearchSpec.Objective'] = ...
        MAXIMIZE_SCORE: typing.ClassVar['ProcessResearchSpec.Objective'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ProcessResearchSpec.Objective': ...
        @staticmethod
        def values() -> typing.MutableSequence['ProcessResearchSpec.Objective']: ...
    class ProductTarget:
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def getComponentName(self) -> java.lang.String: ...
        def getMaterialName(self) -> java.lang.String: ...
        def getMinFlowRate(self) -> float: ...
        def getMinPurity(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getStreamReference(self) -> java.lang.String: ...
        def getStreamRole(self) -> java.lang.String: ...
        def getWeight(self) -> float: ...
        def setComponentName(self, string: typing.Union[java.lang.String, str]) -> 'ProcessResearchSpec.ProductTarget': ...
        def setMaterialName(self, string: typing.Union[java.lang.String, str]) -> 'ProcessResearchSpec.ProductTarget': ...
        def setMinFlowRate(self, double: float) -> 'ProcessResearchSpec.ProductTarget': ...
        def setMinPurity(self, double: float) -> 'ProcessResearchSpec.ProductTarget': ...
        def setStreamReference(self, string: typing.Union[java.lang.String, str]) -> 'ProcessResearchSpec.ProductTarget': ...
        def setStreamRole(self, string: typing.Union[java.lang.String, str]) -> 'ProcessResearchSpec.ProductTarget': ...
        def setWeight(self, double: float) -> 'ProcessResearchSpec.ProductTarget': ...
    class RobustnessScenario:
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def getFeedFlowMultiplier(self) -> float: ...
        def getFeedPressureMultiplier(self) -> float: ...
        def getFeedTemperatureOffsetK(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def setFeedFlowMultiplier(self, double: float) -> 'ProcessResearchSpec.RobustnessScenario': ...
        def setFeedPressureMultiplier(self, double: float) -> 'ProcessResearchSpec.RobustnessScenario': ...
        def setFeedTemperatureOffsetK(self, double: float) -> 'ProcessResearchSpec.RobustnessScenario': ...
    class ScoringWeights:
        def __init__(self): ...
        def getCapitalCostPenalty(self) -> float: ...
        def getColdUtilityPenalty(self) -> float: ...
        def getComplexityPenalty(self) -> float: ...
        def getElectricPowerPenalty(self) -> float: ...
        def getEmissionsPenalty(self) -> float: ...
        def getHotUtilityPenalty(self) -> float: ...
        def getProductFlowWeight(self) -> float: ...
        def getPurityWeight(self) -> float: ...
        def getRobustnessWeight(self) -> float: ...
        def setCapitalCostPenalty(self, double: float) -> 'ProcessResearchSpec.ScoringWeights': ...
        def setColdUtilityPenalty(self, double: float) -> 'ProcessResearchSpec.ScoringWeights': ...
        def setComplexityPenalty(self, double: float) -> 'ProcessResearchSpec.ScoringWeights': ...
        def setElectricPowerPenalty(self, double: float) -> 'ProcessResearchSpec.ScoringWeights': ...
        def setEmissionsPenalty(self, double: float) -> 'ProcessResearchSpec.ScoringWeights': ...
        def setHotUtilityPenalty(self, double: float) -> 'ProcessResearchSpec.ScoringWeights': ...
        def setProductFlowWeight(self, double: float) -> 'ProcessResearchSpec.ScoringWeights': ...
        def setPurityWeight(self, double: float) -> 'ProcessResearchSpec.ScoringWeights': ...
        def setRobustnessWeight(self, double: float) -> 'ProcessResearchSpec.ScoringWeights': ...
    class SynthesisConstraints:
        def __init__(self): ...
        def getMaxAnnualOperatingCostProxyUSDPerYr(self) -> float: ...
        def getMaxCapitalCostProxyUSD(self) -> float: ...
        def getMaxColdUtilityKW(self) -> float: ...
        def getMaxEmissionsKgCO2ePerHr(self) -> float: ...
        def getMaxEquipmentCount(self) -> float: ...
        def getMaxHotUtilityKW(self) -> float: ...
        def getMaxTotalPowerKW(self) -> float: ...
        def setMaxAnnualOperatingCostProxyUSDPerYr(self, double: float) -> 'ProcessResearchSpec.SynthesisConstraints': ...
        def setMaxCapitalCostProxyUSD(self, double: float) -> 'ProcessResearchSpec.SynthesisConstraints': ...
        def setMaxColdUtilityKW(self, double: float) -> 'ProcessResearchSpec.SynthesisConstraints': ...
        def setMaxEmissionsKgCO2ePerHr(self, double: float) -> 'ProcessResearchSpec.SynthesisConstraints': ...
        def setMaxEquipmentCount(self, double: float) -> 'ProcessResearchSpec.SynthesisConstraints': ...
        def setMaxHotUtilityKW(self, double: float) -> 'ProcessResearchSpec.SynthesisConstraints': ...
        def setMaxTotalPowerKW(self, double: float) -> 'ProcessResearchSpec.SynthesisConstraints': ...

class ProcessResearcher:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, processCandidateGenerator: ProcessCandidateGenerator, processCandidateEvaluator: ProcessCandidateEvaluator): ...
    @typing.overload
    def __init__(self, processCandidateGenerator: ProcessCandidateGenerator, processCandidateEvaluator: ProcessCandidateEvaluator, processSynthesisFeasibilityPruner: 'ProcessSynthesisFeasibilityPruner'): ...
    def research(self, processResearchSpec: ProcessResearchSpec) -> ProcessResearchResult: ...

class ProcessSuperstructureExporter:
    def __init__(self): ...
    def toJson(self, processResearchSpec: ProcessResearchSpec) -> java.lang.String: ...
    def toPyomoSkeleton(self, processResearchSpec: ProcessResearchSpec) -> java.lang.String: ...

class ProcessSynthesisFeasibilityPruner:
    def __init__(self): ...
    def checkOperationPath(self, list: java.util.List[OperationOption], processResearchSpec: ProcessResearchSpec) -> 'ProcessSynthesisFeasibilityPruner.FeasibilityResult': ...
    def checkReaction(self, reactionOption: 'ReactionOption', processResearchSpec: ProcessResearchSpec) -> 'ProcessSynthesisFeasibilityPruner.FeasibilityResult': ...
    def validateSpec(self, processResearchSpec: ProcessResearchSpec) -> java.util.List[java.lang.String]: ...
    class FeasibilityResult:
        def __init__(self): ...
        def addIssue(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def getIssues(self) -> java.util.List[java.lang.String]: ...
        def isFeasible(self) -> bool: ...

class ProcessSynthesisGraph:
    def __init__(self): ...
    def addMaterial(self, materialNode: MaterialNode) -> 'ProcessSynthesisGraph': ...
    def addOperation(self, operationOption: OperationOption) -> 'ProcessSynthesisGraph': ...
    def enumeratePaths(self, string: typing.Union[java.lang.String, str], list: java.util.List[typing.Union[java.lang.String, str]], int: int, int2: int) -> java.util.List[java.util.List[OperationOption]]: ...
    @staticmethod
    def fromSpec(processResearchSpec: ProcessResearchSpec) -> 'ProcessSynthesisGraph': ...
    def getMaterials(self) -> java.util.Map[java.lang.String, MaterialNode]: ...
    def getOperations(self) -> java.util.List[OperationOption]: ...

class ProcessSynthesisTemplateLibrary:
    def __init__(self): ...
    def createOptions(self, processResearchSpec: ProcessResearchSpec) -> java.util.List[OperationOption]: ...

class ReactionOption:
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addStoichiometricCoefficient(self, string: typing.Union[java.lang.String, str], double: float) -> 'ReactionOption': ...
    def getEnergyMode(self) -> java.lang.String: ...
    def getExpectedProductComponent(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getReactorPressureBara(self) -> float: ...
    def getReactorTemperatureK(self) -> float: ...
    def getReactorType(self) -> java.lang.String: ...
    def getStoichiometry(self) -> java.util.Map[java.lang.String, float]: ...
    def setEnergyMode(self, string: typing.Union[java.lang.String, str]) -> 'ReactionOption': ...
    def setExpectedProductComponent(self, string: typing.Union[java.lang.String, str]) -> 'ReactionOption': ...
    def setReactorPressure(self, double: float) -> 'ReactionOption': ...
    def setReactorTemperature(self, double: float) -> 'ReactionOption': ...
    def setReactorType(self, string: typing.Union[java.lang.String, str]) -> 'ReactionOption': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.research")``.

    MaterialNode: typing.Type[MaterialNode]
    OperationOption: typing.Type[OperationOption]
    ProcessCandidate: typing.Type[ProcessCandidate]
    ProcessCandidateEvaluator: typing.Type[ProcessCandidateEvaluator]
    ProcessCandidateGenerator: typing.Type[ProcessCandidateGenerator]
    ProcessResearchMetrics: typing.Type[ProcessResearchMetrics]
    ProcessResearchResult: typing.Type[ProcessResearchResult]
    ProcessResearchSpec: typing.Type[ProcessResearchSpec]
    ProcessResearcher: typing.Type[ProcessResearcher]
    ProcessSuperstructureExporter: typing.Type[ProcessSuperstructureExporter]
    ProcessSynthesisFeasibilityPruner: typing.Type[ProcessSynthesisFeasibilityPruner]
    ProcessSynthesisGraph: typing.Type[ProcessSynthesisGraph]
    ProcessSynthesisTemplateLibrary: typing.Type[ProcessSynthesisTemplateLibrary]
    ReactionOption: typing.Type[ReactionOption]
