
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.costestimation
import jneqsim.process.mechanicaldesign.ejector
import typing



class EjectorCostEstimate(jneqsim.process.costestimation.UnitCostEstimateBaseClass):
    def __init__(self, ejectorMechanicalDesign: jneqsim.process.mechanicaldesign.ejector.EjectorMechanicalDesign): ...
    @typing.overload
    def calcAnnualOperatingCost(self, double: float, double2: float, double3: float, int: int) -> float: ...
    @typing.overload
    def calcAnnualOperatingCost(self, int: int, double: float, double2: float) -> float: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getEjectorType(self) -> java.lang.String: ...
    def getNumberOfStages(self) -> int: ...
    def setDischargePressure(self, double: float) -> None: ...
    def setEjectorType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setIncludeAftercondenser(self, boolean: bool) -> None: ...
    def setIncludeIntercondensers(self, boolean: bool) -> None: ...
    def setMotivePressure(self, double: float) -> None: ...
    def setNumberOfStages(self, int: int) -> None: ...
    def setSuctionCapacity(self, double: float) -> None: ...
    def setSuctionPressure(self, double: float) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.costestimation.ejector")``.

    EjectorCostEstimate: typing.Type[EjectorCostEstimate]
