import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.process.mechanicaldesign.ejector
import jneqsim.process.util.report
import typing

class Ejector(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ): ...
    def getDesignResult(
        self,
    ) -> jneqsim.process.mechanicaldesign.ejector.EjectorMechanicalDesign: ...
    def getDiffuserEfficiency(self) -> float: ...
    def getEfficiencyIsentropic(self) -> float: ...
    def getEntrainmentRatio(self) -> float: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMechanicalDesign(
        self,
    ) -> jneqsim.process.mechanicaldesign.ejector.EjectorMechanicalDesign: ...
    def getMixedStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getMotiveStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOutStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getSuctionStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def initMechanicalDesign(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setDesignDiffuserOutletVelocity(self, double: float) -> None: ...
    def setDesignSuctionVelocity(self, double: float) -> None: ...
    def setDiffuserEfficiency(self, double: float) -> None: ...
    def setDischargeConnectionLength(self, double: float) -> None: ...
    def setDischargePressure(self, double: float) -> None: ...
    def setEfficiencyIsentropic(self, double: float) -> None: ...
    def setMixingPressure(self, double: float) -> None: ...
    def setSuctionConnectionLength(self, double: float) -> None: ...
    def setThroatArea(self, double: float) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(
        self, reportConfig: jneqsim.process.util.report.ReportConfig
    ) -> java.lang.String: ...

class EjectorDesignResult:
    def __init__(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
        double10: float,
        double11: float,
        double12: float,
        double13: float,
        double14: float,
        double15: float,
        double16: float,
        double17: float,
        double18: float,
    ): ...
    @staticmethod
    def empty() -> "EjectorDesignResult": ...
    def getBodyVolume(self) -> float: ...
    def getConnectedPipingVolume(self) -> float: ...
    def getDiffuserOutletArea(self) -> float: ...
    def getDiffuserOutletDiameter(self) -> float: ...
    def getDiffuserOutletLength(self) -> float: ...
    def getDiffuserOutletVelocity(self) -> float: ...
    def getDischargeConnectionLength(self) -> float: ...
    def getEntrainmentRatio(self) -> float: ...
    def getMixingChamberArea(self) -> float: ...
    def getMixingChamberDiameter(self) -> float: ...
    def getMixingChamberLength(self) -> float: ...
    def getMixingChamberVelocity(self) -> float: ...
    def getMixingPressure(self) -> float: ...
    def getMotiveNozzleDiameter(self) -> float: ...
    def getMotiveNozzleEffectiveLength(self) -> float: ...
    def getMotiveNozzleExitVelocity(self) -> float: ...
    def getMotiveNozzleThroatArea(self) -> float: ...
    def getSuctionConnectionLength(self) -> float: ...
    def getSuctionInletArea(self) -> float: ...
    def getSuctionInletDiameter(self) -> float: ...
    def getSuctionInletLength(self) -> float: ...
    def getSuctionInletVelocity(self) -> float: ...
    def getTotalVolume(self) -> float: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.ejector")``.

    Ejector: typing.Type[Ejector]
    EjectorDesignResult: typing.Type[EjectorDesignResult]
