
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jneqsim.process.equipment
import jneqsim.process.mechanicaldesign
import typing



class ExpanderMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def displayResults(self) -> None: ...
    def getBearingType(self) -> java.lang.String: ...
    def getCasingDesignPressure(self) -> float: ...
    def getCasingDesignTemperature(self) -> float: ...
    def getExpanderType(self) -> 'ExpanderMechanicalDesign.ExpanderType': ...
    def getFirstCriticalSpeed(self) -> float: ...
    def getIsentropicEfficiency(self) -> float: ...
    def getLoadType(self) -> 'ExpanderMechanicalDesign.LoadType': ...
    def getNumberOfStages(self) -> int: ...
    def getRatedSpeed(self) -> float: ...
    def getRecoveredPower(self) -> float: ...
    def getSealType(self) -> java.lang.String: ...
    def getShaftDiameter(self) -> float: ...
    def getTipSpeed(self) -> float: ...
    def getWheelDiameter(self) -> float: ...
    class ExpanderType(java.lang.Enum['ExpanderMechanicalDesign.ExpanderType']):
        RADIAL_INFLOW: typing.ClassVar['ExpanderMechanicalDesign.ExpanderType'] = ...
        AXIAL: typing.ClassVar['ExpanderMechanicalDesign.ExpanderType'] = ...
        MIXED_FLOW: typing.ClassVar['ExpanderMechanicalDesign.ExpanderType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ExpanderMechanicalDesign.ExpanderType': ...
        @staticmethod
        def values() -> typing.MutableSequence['ExpanderMechanicalDesign.ExpanderType']: ...
    class LoadType(java.lang.Enum['ExpanderMechanicalDesign.LoadType']):
        GENERATOR: typing.ClassVar['ExpanderMechanicalDesign.LoadType'] = ...
        COMPRESSOR: typing.ClassVar['ExpanderMechanicalDesign.LoadType'] = ...
        BRAKE: typing.ClassVar['ExpanderMechanicalDesign.LoadType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ExpanderMechanicalDesign.LoadType': ...
        @staticmethod
        def values() -> typing.MutableSequence['ExpanderMechanicalDesign.LoadType']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.expander")``.

    ExpanderMechanicalDesign: typing.Type[ExpanderMechanicalDesign]
