import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.process.equipment.valve
import jneqsim.process.mechanicaldesign
import jneqsim.process.mechanicaldesign.valve.choke
import typing

class ControlValveGasSizing_IEC_60534_2_1(java.io.Serializable):
    def __init__(self): ...
    def calcSizing(self) -> None: ...
    def fromValve(
        self, throttlingValve: jneqsim.process.equipment.valve.ThrottlingValve
    ) -> None: ...
    def getChokedPressureDropRatio(self) -> float: ...
    def getExpansionFactor(self) -> float: ...
    def getPressureDropRatio(self) -> float: ...
    def getRequiredCv(self) -> float: ...
    def getRequiredKv(self) -> float: ...
    def getSpecificHeatRatioFactor(self) -> float: ...
    def isChoked(self) -> bool: ...
    def setFlowConditions(
        self, double: float, double2: float, double3: float, double4: float
    ) -> None: ...
    def setValveCoefficients(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    def toJson(self) -> java.lang.String: ...

class ControlValveNoise_IEC_60534_8_3(java.io.Serializable):
    def __init__(self): ...
    def calcNoise(self) -> None: ...
    def getAcousticalEfficiency(self) -> float: ...
    def getFlowRegime(self) -> int: ...
    def getMechanicalStreamPower(self) -> float: ...
    def getOutletMach(self) -> float: ...
    def getSoundPowerInternal(self) -> float: ...
    def getSoundPressureLevelDbA(self) -> float: ...
    def getTransmissionLoss(self) -> float: ...
    def setAcousticProperties(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    def setFlowConditions(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
    ) -> None: ...
    def setGeometry(self, double: float, double2: float, double3: float) -> None: ...
    def setValveCoefficients(self, double: float, double2: float) -> None: ...
    def toJson(self) -> java.lang.String: ...

class ControlValveSizingInterface:
    def calcValveSize(
        self, double: float
    ) -> java.util.Map[java.lang.String, typing.Any]: ...
    def calculateFlowRateFromValveOpening(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def calculateValveOpeningFromFlowRate(
        self,
        double: float,
        double2: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def findOutletPressureForFixedKv(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def getxT(self) -> float: ...
    def isAllowChoked(self) -> bool: ...
    def setAllowChoked(self, boolean: bool) -> None: ...
    def setxT(self, double: float) -> None: ...

class ValveCharacteristic(java.io.Serializable):
    def getActualKv(self, double: float, double2: float) -> float: ...
    def getOpeningFactor(self, double: float) -> float: ...

class ValveMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(
        self,
        processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface,
    ): ...
    def calcDesign(self) -> None: ...
    def calcValveSize(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def displayResults(self) -> None: ...
    def getActuatorWeight(self) -> float: ...
    def getAnsiPressureClass(self) -> int: ...
    def getBodyWallThickness(self) -> float: ...
    def getBodyWeight(self) -> float: ...
    def getChokeDiameter(self) -> float: ...
    def getDesignPressure(self) -> float: ...
    def getDesignTemperature(self) -> float: ...
    def getDp(self) -> float: ...
    def getFL(self) -> float: ...
    def getFaceToFace(self) -> float: ...
    def getFlangeType(self) -> java.lang.String: ...
    def getInletPressure(self) -> float: ...
    def getNominalSizeInches(self) -> float: ...
    def getOutletPressure(self) -> float: ...
    def getRequiredActuatorThrust(self) -> float: ...
    def getResponse(self) -> "ValveMechanicalDesignResponse": ...
    def getStemDiameter(self) -> float: ...
    def getValveCharacterization(self) -> java.lang.String: ...
    def getValveCharacterizationMethod(self) -> ValveCharacteristic: ...
    def getValveCvMax(self) -> float: ...
    def getValveSizingMethod(self) -> ControlValveSizingInterface: ...
    def getValveSizingStandard(self) -> java.lang.String: ...
    def getValveType(self) -> java.lang.String: ...
    def getxT(self) -> float: ...
    def readDesignSpecifications(self) -> None: ...
    def setChokeDiameter(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setChokeDischargeCoefficient(self, double: float) -> None: ...
    def setValveCharacterization(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setValveCharacterizationMethod(
        self, valveCharacteristic: ValveCharacteristic
    ) -> None: ...
    def setValveSizingStandard(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def toJson(self) -> java.lang.String: ...

class ValveMechanicalDesignResponse(
    jneqsim.process.mechanicaldesign.MechanicalDesignResponse
):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, valveMechanicalDesign: ValveMechanicalDesign): ...
    def getActuatorType(self) -> java.lang.String: ...
    def getActuatorWeight(self) -> float: ...
    def getAnsiPressureClass(self) -> int: ...
    def getBodyWallThickness(self) -> float: ...
    def getBodyWeight(self) -> float: ...
    def getCavitationIndex(self) -> float: ...
    def getCvMax(self) -> float: ...
    def getCvRequired(self) -> float: ...
    def getFaceToFace(self) -> float: ...
    def getFlFactor(self) -> float: ...
    def getFlangeType(self) -> java.lang.String: ...
    def getFlowRegime(self) -> java.lang.String: ...
    def getInletPressure(self) -> float: ...
    def getKv(self) -> float: ...
    def getMassFlowRate(self) -> float: ...
    def getNoiseLevel(self) -> float: ...
    def getNominalSizeInches(self) -> float: ...
    def getOutletPressure(self) -> float: ...
    def getPressureDrop(self) -> float: ...
    def getRequiredActuatorThrust(self) -> float: ...
    def getStemDiameter(self) -> float: ...
    def getValveCharacteristic(self) -> java.lang.String: ...
    def getValveOpening(self) -> float: ...
    def getValveType(self) -> java.lang.String: ...
    def getVolumetricFlowRate(self) -> float: ...
    def getXtFactor(self) -> float: ...
    def isChoked(self) -> bool: ...
    def populateFromValveDesign(
        self, valveMechanicalDesign: ValveMechanicalDesign
    ) -> None: ...
    def setActuatorType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setActuatorWeight(self, double: float) -> None: ...
    def setAnsiPressureClass(self, int: int) -> None: ...
    def setBodyWallThickness(self, double: float) -> None: ...
    def setBodyWeight(self, double: float) -> None: ...
    def setCavitationIndex(self, double: float) -> None: ...
    def setChoked(self, boolean: bool) -> None: ...
    def setCvMax(self, double: float) -> None: ...
    def setCvRequired(self, double: float) -> None: ...
    def setFaceToFace(self, double: float) -> None: ...
    def setFlFactor(self, double: float) -> None: ...
    def setFlangeType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setFlowRegime(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInletPressure(self, double: float) -> None: ...
    def setKv(self, double: float) -> None: ...
    def setMassFlowRate(self, double: float) -> None: ...
    def setNoiseLevel(self, double: float) -> None: ...
    def setNominalSizeInches(self, double: float) -> None: ...
    def setOutletPressure(self, double: float) -> None: ...
    def setPressureDrop(self, double: float) -> None: ...
    def setRequiredActuatorThrust(self, double: float) -> None: ...
    def setStemDiameter(self, double: float) -> None: ...
    def setValveCharacteristic(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setValveOpening(self, double: float) -> None: ...
    def setValveType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setVolumetricFlowRate(self, double: float) -> None: ...
    def setXtFactor(self, double: float) -> None: ...

class ControlValveSizing(ControlValveSizingInterface, java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, valveMechanicalDesign: ValveMechanicalDesign): ...
    def calcKv(self, double: float) -> float: ...
    def calcValveSize(
        self, double: float
    ) -> java.util.Map[java.lang.String, typing.Any]: ...
    def calculateFlowRateFromValveOpening(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def calculateMolarFlow(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def calculateOutletPressure(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def calculateValveOpeningFromFlowRate(
        self,
        double: float,
        double2: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def findOutletPressureForFixedKv(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def getValveMechanicalDesign(self) -> ValveMechanicalDesign: ...
    def getxT(self) -> float: ...
    def isAllowChoked(self) -> bool: ...
    def setAllowChoked(self, boolean: bool) -> None: ...
    def setxT(self, double: float) -> None: ...

class ControlValveSizing_MultiphaseChoke(
    ControlValveSizingInterface, java.io.Serializable
):
    @typing.overload
    def __init__(self, valveMechanicalDesign: ValveMechanicalDesign): ...
    @typing.overload
    def __init__(
        self,
        valveMechanicalDesign: ValveMechanicalDesign,
        string: typing.Union[java.lang.String, str],
    ): ...
    def calcValveSize(
        self, double: float
    ) -> java.util.Map[java.lang.String, typing.Any]: ...
    def calculateFlowRateFromValveOpening(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def calculateValveOpeningFromFlowRate(
        self,
        double: float,
        double2: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def findOutletPressureForFixedKv(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def getChokeDiameter(self) -> float: ...
    def getChokeModel(
        self,
    ) -> jneqsim.process.mechanicaldesign.valve.choke.MultiphaseChokeFlow: ...
    def getChokeReport(
        self,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        double: float,
    ) -> java.lang.String: ...
    def getDischargeCoefficient(self) -> float: ...
    def getModelType(self) -> java.lang.String: ...
    def getxT(self) -> float: ...
    def isAllowChoked(self) -> bool: ...
    def isAllowLaminar(self) -> bool: ...
    def setAllowChoked(self, boolean: bool) -> None: ...
    def setAllowLaminar(self, boolean: bool) -> None: ...
    def setChokeDiameter(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setChokeModel(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDischargeCoefficient(self, double: float) -> None: ...
    def setxT(self, double: float) -> None: ...

class EqualPercentageCharacteristic(ValveCharacteristic):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float): ...
    def getActualKv(self, double: float, double2: float) -> float: ...
    def getOpeningFactor(self, double: float) -> float: ...
    def getRangeability(self) -> float: ...
    def setRangeability(self, double: float) -> None: ...

class LinearCharacteristic(ValveCharacteristic):
    def __init__(self): ...
    def getActualKv(self, double: float, double2: float) -> float: ...
    def getOpeningFactor(self, double: float) -> float: ...

class ModifiedParabolicCharacteristic(ValveCharacteristic):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float): ...
    def getActualKv(self, double: float, double2: float) -> float: ...
    def getExponent(self) -> float: ...
    def getOpeningFactor(self, double: float) -> float: ...
    def setExponent(self, double: float) -> None: ...

class QuickOpeningCharacteristic(ValveCharacteristic):
    def __init__(self): ...
    def getActualKv(self, double: float, double2: float) -> float: ...
    def getOpeningFactor(self, double: float) -> float: ...

class SafetyValveMechanicalDesign(ValveMechanicalDesign):
    def __init__(
        self,
        processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface,
    ): ...
    def calcDesign(self) -> None: ...
    def calcGasOrificeAreaAPI520(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
    ) -> float: ...
    def getControllingOrificeArea(self) -> float: ...
    def getControllingScenarioName(self) -> java.lang.String: ...
    def getOrificeArea(self) -> float: ...
    def getScenarioReports(
        self,
    ) -> java.util.Map[
        java.lang.String, "SafetyValveMechanicalDesign.SafetyValveScenarioReport"
    ]: ...
    def getScenarioResults(
        self,
    ) -> java.util.Map[
        java.lang.String, "SafetyValveMechanicalDesign.SafetyValveScenarioResult"
    ]: ...

    class SafetyValveScenarioReport:
        def getBackPressureBar(self) -> float: ...
        def getFluidService(
            self,
        ) -> jneqsim.process.equipment.valve.SafetyValve.FluidService: ...
        def getOverpressureMarginBar(self) -> float: ...
        def getRelievingPressureBar(self) -> float: ...
        def getRequiredOrificeArea(self) -> float: ...
        def getScenarioName(self) -> java.lang.String: ...
        def getSetPressureBar(self) -> float: ...
        def getSizingStandard(
            self,
        ) -> jneqsim.process.equipment.valve.SafetyValve.SizingStandard: ...
        def isActiveScenario(self) -> bool: ...
        def isControllingScenario(self) -> bool: ...

    class SafetyValveScenarioResult:
        def getBackPressureBar(self) -> float: ...
        def getBackPressurePa(self) -> float: ...
        def getFluidService(
            self,
        ) -> jneqsim.process.equipment.valve.SafetyValve.FluidService: ...
        def getOverpressureMarginBar(self) -> float: ...
        def getOverpressureMarginPa(self) -> float: ...
        def getRelievingPressureBar(self) -> float: ...
        def getRelievingPressurePa(self) -> float: ...
        def getRequiredOrificeArea(self) -> float: ...
        def getScenarioName(self) -> java.lang.String: ...
        def getSetPressureBar(self) -> float: ...
        def getSetPressurePa(self) -> float: ...
        def getSizingStandard(
            self,
        ) -> jneqsim.process.equipment.valve.SafetyValve.SizingStandard: ...
        def isActiveScenario(self) -> bool: ...
        def isControllingScenario(self) -> bool: ...

class ControlValveSizing_IEC_60534(ControlValveSizing):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, valveMechanicalDesign: ValveMechanicalDesign): ...
    def calcValveSize(
        self, double: float
    ) -> java.util.Map[java.lang.String, typing.Any]: ...
    @typing.overload
    def calculateFlowRateFromKvAndValveOpeningGas(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
        double10: float,
        boolean: bool,
    ) -> float: ...
    @typing.overload
    def calculateFlowRateFromKvAndValveOpeningGas(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def calculateFlowRateFromValveOpening(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def calculateFlowRateFromValveOpeningGas(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    @typing.overload
    def calculateFlowRateFromValveOpeningLiquid(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
    ) -> float: ...
    @typing.overload
    def calculateFlowRateFromValveOpeningLiquid(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    @typing.overload
    def calculateValveOpeningFromFlowRateGas(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
        double10: float,
        double11: float,
        boolean: bool,
    ) -> float: ...
    @typing.overload
    def calculateValveOpeningFromFlowRateGas(
        self,
        double: float,
        double2: float,
        double3: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    @typing.overload
    def calculateValveOpeningFromFlowRateLiquid(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
    ) -> float: ...
    @typing.overload
    def calculateValveOpeningFromFlowRateLiquid(
        self,
        double: float,
        double2: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def findOutletPressureForFixedKv(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    @typing.overload
    def findOutletPressureForFixedKvGas(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
    ) -> float: ...
    @typing.overload
    def findOutletPressureForFixedKvGas(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    @typing.overload
    def findOutletPressureForFixedKvLiquid(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
        boolean: bool,
        boolean2: bool,
    ) -> float: ...
    @typing.overload
    def findOutletPressureForFixedKvLiquid(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def getD(self) -> float: ...
    def getD1(self) -> float: ...
    def getD2(self) -> float: ...
    def getFL(self) -> float: ...
    def getFd(self) -> float: ...
    def getValve(self) -> jneqsim.process.equipment.valve.ValveInterface: ...
    def isAllowChoked(self) -> bool: ...
    def isAllowLaminar(self) -> bool: ...
    def isFullOutput(self) -> bool: ...
    def setAllowChoked(self, boolean: bool) -> None: ...
    def setAllowLaminar(self, boolean: bool) -> None: ...
    def setD(self, double: float) -> None: ...
    def setD1(self, double: float) -> None: ...
    def setD2(self, double: float) -> None: ...
    def setFL(self, double: float) -> None: ...
    def setFd(self, double: float) -> None: ...
    def setFullOutput(self, boolean: bool) -> None: ...
    def sizeControlValve(
        self,
        fluidType: "ControlValveSizing_IEC_60534.FluidType",
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
        double10: float,
        double11: float,
        double12: float,
        double13: float,
        double14: float,
        boolean: bool,
        boolean2: bool,
        boolean3: bool,
        double15: float,
    ) -> java.util.Map[java.lang.String, typing.Any]: ...
    def sizeControlValveGas(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
    ) -> java.util.Map[java.lang.String, typing.Any]: ...
    def sizeControlValveLiquid(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
    ) -> java.util.Map[java.lang.String, typing.Any]: ...

    class FluidType(java.lang.Enum["ControlValveSizing_IEC_60534.FluidType"]):
        LIQUID: typing.ClassVar["ControlValveSizing_IEC_60534.FluidType"] = ...
        GAS: typing.ClassVar["ControlValveSizing_IEC_60534.FluidType"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "ControlValveSizing_IEC_60534.FluidType": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["ControlValveSizing_IEC_60534.FluidType"]
        ): ...

class ControlValveSizing_simple(ControlValveSizing):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, valveMechanicalDesign: ValveMechanicalDesign): ...
    def calcKv(self, double: float) -> float: ...
    @typing.overload
    def calculateFlowRateFromValveOpening(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    @typing.overload
    def calculateFlowRateFromValveOpening(
        self,
        double: float,
        double2: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def calculateMolarFlow(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def calculateOutletPressure(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    @typing.overload
    def calculateValveOpeningFromFlowRate(
        self,
        double: float,
        double2: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    @typing.overload
    def calculateValveOpeningFromFlowRate(
        self,
        double: float,
        double2: float,
        double3: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    @typing.overload
    def findOutletPressureForFixedKv(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    @typing.overload
    def findOutletPressureForFixedKv(
        self,
        double: float,
        double2: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def getCd(self) -> float: ...
    def setCd(self, double: float) -> None: ...

class ControlValveSizing_IEC_60534_full(ControlValveSizing_IEC_60534):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, valveMechanicalDesign: ValveMechanicalDesign): ...
    def calculateFlowRateFromValveOpening(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    @typing.overload
    def calculateValveOpeningFromFlowRate(
        self,
        double: float,
        double2: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    @typing.overload
    def calculateValveOpeningFromFlowRate(
        self,
        double: float,
        double2: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        streamInterface2: jneqsim.process.equipment.stream.StreamInterface,
        double3: float,
    ) -> float: ...
    def findOutletPressureForFixedKv(
        self,
        double: float,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> float: ...
    def isFullTrim(self) -> bool: ...
    def setFullTrim(self, boolean: bool) -> None: ...
    def sizeControlValveGas(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
    ) -> java.util.Map[java.lang.String, typing.Any]: ...
    def sizeControlValveLiquid(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
    ) -> java.util.Map[java.lang.String, typing.Any]: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.valve")``.

    ControlValveGasSizing_IEC_60534_2_1: typing.Type[
        ControlValveGasSizing_IEC_60534_2_1
    ]
    ControlValveNoise_IEC_60534_8_3: typing.Type[ControlValveNoise_IEC_60534_8_3]
    ControlValveSizing: typing.Type[ControlValveSizing]
    ControlValveSizingInterface: typing.Type[ControlValveSizingInterface]
    ControlValveSizing_IEC_60534: typing.Type[ControlValveSizing_IEC_60534]
    ControlValveSizing_IEC_60534_full: typing.Type[ControlValveSizing_IEC_60534_full]
    ControlValveSizing_MultiphaseChoke: typing.Type[ControlValveSizing_MultiphaseChoke]
    ControlValveSizing_simple: typing.Type[ControlValveSizing_simple]
    EqualPercentageCharacteristic: typing.Type[EqualPercentageCharacteristic]
    LinearCharacteristic: typing.Type[LinearCharacteristic]
    ModifiedParabolicCharacteristic: typing.Type[ModifiedParabolicCharacteristic]
    QuickOpeningCharacteristic: typing.Type[QuickOpeningCharacteristic]
    SafetyValveMechanicalDesign: typing.Type[SafetyValveMechanicalDesign]
    ValveCharacteristic: typing.Type[ValveCharacteristic]
    ValveMechanicalDesign: typing.Type[ValveMechanicalDesign]
    ValveMechanicalDesignResponse: typing.Type[ValveMechanicalDesignResponse]
    choke: jneqsim.process.mechanicaldesign.valve.choke.__module_protocol__
