
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jpype
import jneqsim.statistics.parameterfitting.nonlinearparameterfitting
import jneqsim.thermo.system
import typing



class AsphalteneOnsetFitting:
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def addOnsetPoint(self, double: float, double2: float) -> None: ...
    @typing.overload
    def addOnsetPoint(self, double: float, double2: float, double3: float) -> None: ...
    def addOnsetPointCelsius(self, double: float, double2: float) -> None: ...
    def calculateOnsetPressure(self, double: float) -> float: ...
    def clearData(self) -> None: ...
    def displayCurveFit(self) -> None: ...
    def getFittedAssociationEnergy(self) -> float: ...
    def getFittedAssociationVolume(self) -> float: ...
    def getFittedParameters(self) -> typing.MutableSequence[float]: ...
    def getFunction(self) -> 'AsphalteneOnsetFunction': ...
    def getNumberOfDataPoints(self) -> int: ...
    def getOptimizer(self) -> jneqsim.statistics.parameterfitting.nonlinearparameterfitting.LevenbergMarquardt: ...
    def isSolved(self) -> bool: ...
    def printResults(self) -> None: ...
    @typing.overload
    def setInitialGuess(self, double: float) -> None: ...
    @typing.overload
    def setInitialGuess(self, double: float, double2: float) -> None: ...
    def setParameterType(self, fittingParameterType: 'AsphalteneOnsetFunction.FittingParameterType') -> None: ...
    def setPressureRange(self, double: float, double2: float, double3: float) -> None: ...
    def setPressureStdDev(self, double: float) -> None: ...
    def solve(self) -> bool: ...
    class OnsetDataPoint:
        temperatureK: float = ...
        pressureBara: float = ...
        stdDev: float = ...
        def __init__(self, double: float, double2: float, double3: float): ...

class AsphalteneOnsetFunction(jneqsim.statistics.parameterfitting.nonlinearparameterfitting.LevenbergMarquardtFunction):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    def calcValue(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    def setAsphalteneComponentName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setFittingParams(self, int: int, double: float) -> None: ...
    @typing.overload
    def setFittingParams(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setParameterType(self, fittingParameterType: 'AsphalteneOnsetFunction.FittingParameterType') -> None: ...
    def setPressureRange(self, double: float, double2: float, double3: float) -> None: ...
    def setPressureTolerance(self, double: float) -> None: ...
    class FittingParameterType(java.lang.Enum['AsphalteneOnsetFunction.FittingParameterType']):
        ASSOCIATION_PARAMETERS: typing.ClassVar['AsphalteneOnsetFunction.FittingParameterType'] = ...
        BINARY_INTERACTION: typing.ClassVar['AsphalteneOnsetFunction.FittingParameterType'] = ...
        MOLAR_MASS: typing.ClassVar['AsphalteneOnsetFunction.FittingParameterType'] = ...
        COMBINED: typing.ClassVar['AsphalteneOnsetFunction.FittingParameterType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'AsphalteneOnsetFunction.FittingParameterType': ...
        @staticmethod
        def values() -> typing.MutableSequence['AsphalteneOnsetFunction.FittingParameterType']: ...

class CMEFunction(jneqsim.statistics.parameterfitting.nonlinearparameterfitting.LevenbergMarquardtFunction):
    def __init__(self): ...
    def calcSaturationConditions(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    def calcValue(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    @typing.overload
    def setFittingParams(self, int: int, double: float) -> None: ...
    @typing.overload
    def setFittingParams(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class CVDFunction(jneqsim.statistics.parameterfitting.nonlinearparameterfitting.LevenbergMarquardtFunction):
    def __init__(self): ...
    def calcSaturationConditions(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    def calcValue(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    @typing.overload
    def setFittingParams(self, int: int, double: float) -> None: ...
    @typing.overload
    def setFittingParams(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class DensityFunction(jneqsim.statistics.parameterfitting.nonlinearparameterfitting.LevenbergMarquardtFunction):
    def __init__(self): ...
    def calcValue(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    @typing.overload
    def setFittingParams(self, int: int, double: float) -> None: ...
    @typing.overload
    def setFittingParams(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class FunctionJohanSverderup(jneqsim.statistics.parameterfitting.nonlinearparameterfitting.LevenbergMarquardtFunction):
    def __init__(self): ...
    def calcValue(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    @typing.overload
    def setFittingParams(self, int: int, double: float) -> None: ...
    @typing.overload
    def setFittingParams(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class SaturationPressureFunction(jneqsim.statistics.parameterfitting.nonlinearparameterfitting.LevenbergMarquardtFunction):
    def __init__(self): ...
    def calcValue(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    @typing.overload
    def setFittingParams(self, int: int, double: float) -> None: ...
    @typing.overload
    def setFittingParams(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class TestFitToOilFieldFluid:
    def __init__(self): ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...

class TestSaturationPresFunction:
    def __init__(self): ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...

class TestWaxTuning:
    def __init__(self): ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...

class ViscosityFunction(jneqsim.statistics.parameterfitting.nonlinearparameterfitting.LevenbergMarquardtFunction):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, boolean: bool): ...
    def calcValue(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    @typing.overload
    def setFittingParams(self, int: int, double: float) -> None: ...
    @typing.overload
    def setFittingParams(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class WaxFunction(jneqsim.statistics.parameterfitting.nonlinearparameterfitting.LevenbergMarquardtFunction):
    def __init__(self): ...
    def calcValue(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    @typing.overload
    def setFittingParams(self, int: int, double: float) -> None: ...
    @typing.overload
    def setFittingParams(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.pvtsimulation.util.parameterfitting")``.

    AsphalteneOnsetFitting: typing.Type[AsphalteneOnsetFitting]
    AsphalteneOnsetFunction: typing.Type[AsphalteneOnsetFunction]
    CMEFunction: typing.Type[CMEFunction]
    CVDFunction: typing.Type[CVDFunction]
    DensityFunction: typing.Type[DensityFunction]
    FunctionJohanSverderup: typing.Type[FunctionJohanSverderup]
    SaturationPressureFunction: typing.Type[SaturationPressureFunction]
    TestFitToOilFieldFluid: typing.Type[TestFitToOilFieldFluid]
    TestSaturationPresFunction: typing.Type[TestSaturationPresFunction]
    TestWaxTuning: typing.Type[TestWaxTuning]
    ViscosityFunction: typing.Type[ViscosityFunction]
    WaxFunction: typing.Type[WaxFunction]
