
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment.pipeline.twophasepipe
import jneqsim.process.equipment.pipeline.twophasepipe.closure
import jneqsim.thermo.system
import typing



class AUSMPlusFluxCalculator(java.io.Serializable):
    def __init__(self): ...
    def calcMachMinus(self, double: float) -> float: ...
    def calcMachPlus(self, double: float) -> float: ...
    @typing.overload
    def calcPhaseFlux(self, phaseState: 'AUSMPlusFluxCalculator.PhaseState', phaseState2: 'AUSMPlusFluxCalculator.PhaseState', double: float) -> 'AUSMPlusFluxCalculator.PhaseFlux': ...
    @typing.overload
    def calcPhaseFlux(self, phaseState: 'AUSMPlusFluxCalculator.PhaseState', phaseState2: 'AUSMPlusFluxCalculator.PhaseState', double: float, double2: float) -> 'AUSMPlusFluxCalculator.PhaseFlux': ...
    def calcPressureMinus(self, double: float) -> float: ...
    def calcPressurePlus(self, double: float) -> float: ...
    def calcRusanovFlux(self, phaseState: 'AUSMPlusFluxCalculator.PhaseState', phaseState2: 'AUSMPlusFluxCalculator.PhaseState', double: float) -> 'AUSMPlusFluxCalculator.PhaseFlux': ...
    def calcTwoFluidFlux(self, phaseState: 'AUSMPlusFluxCalculator.PhaseState', phaseState2: 'AUSMPlusFluxCalculator.PhaseState', phaseState3: 'AUSMPlusFluxCalculator.PhaseState', phaseState4: 'AUSMPlusFluxCalculator.PhaseState', double: float) -> 'AUSMPlusFluxCalculator.TwoFluidFlux': ...
    def calcUpwindFlux(self, phaseState: 'AUSMPlusFluxCalculator.PhaseState', phaseState2: 'AUSMPlusFluxCalculator.PhaseState', double: float) -> 'AUSMPlusFluxCalculator.PhaseFlux': ...
    def getAlpha(self) -> float: ...
    def getBeta(self) -> float: ...
    def getMinSoundSpeed(self) -> float: ...
    def isCenteredPressureFluxEnabled(self) -> bool: ...
    def setAlpha(self, double: float) -> None: ...
    def setBeta(self, double: float) -> None: ...
    def setCenteredPressureFluxEnabled(self, boolean: bool) -> None: ...
    def setMinSoundSpeed(self, double: float) -> None: ...
    class PhaseFlux(java.io.Serializable):
        massFlux: float = ...
        momentumFlux: float = ...
        energyFlux: float = ...
        holdupFlux: float = ...
        interfaceHoldup: float = ...
        interfacePressure: float = ...
        def __init__(self): ...
    class PhaseState(java.io.Serializable):
        density: float = ...
        velocity: float = ...
        pressure: float = ...
        soundSpeed: float = ...
        enthalpy: float = ...
        holdup: float = ...
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float): ...
    class TwoFluidFlux(java.io.Serializable):
        gasFlux: 'AUSMPlusFluxCalculator.PhaseFlux' = ...
        liquidFlux: 'AUSMPlusFluxCalculator.PhaseFlux' = ...
        interfaceMach: float = ...
        def __init__(self): ...

class ConservativeStateLimiter:
    @staticmethod
    def enforceThreePhaseMassPositivity(doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class CoupledPressureMomentumSolver(java.io.Serializable):
    def __init__(self): ...
    def correct(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], double2: float, doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray], doubleArray5: typing.Union[typing.List[float], jpype.JArray], doubleArray6: typing.Union[typing.List[float], jpype.JArray], doubleArray7: typing.Union[typing.List[float], jpype.JArray], doubleArray8: typing.Union[typing.List[float], jpype.JArray], doubleArray9: typing.Union[typing.List[float], jpype.JArray], doubleArray10: typing.Union[typing.List[float], jpype.JArray], double12: float, boolean: bool) -> 'CoupledPressureMomentumSolver.Result': ...
    def getGasDensityModel(self) -> 'CoupledPressureMomentumSolver.GasDensityModel': ...
    def getMaximumIterations(self) -> int: ...
    def getMinimumPressure(self) -> float: ...
    def getRelativeVolumeTolerance(self) -> float: ...
    def isCheckerboardCorrectionEnabled(self) -> bool: ...
    def setCheckerboardCorrectionEnabled(self, boolean: bool) -> None: ...
    def setGasDensityModel(self, gasDensityModel: 'CoupledPressureMomentumSolver.GasDensityModel') -> None: ...
    def setMaximumIterations(self, int: int) -> None: ...
    def setMinimumPressure(self, double: float) -> None: ...
    def setPressureRelaxation(self, double: float) -> None: ...
    def setRelativeVolumeTolerance(self, double: float) -> None: ...
    class GasDensityModel(java.lang.Enum['CoupledPressureMomentumSolver.GasDensityModel']):
        AFFINE: typing.ClassVar['CoupledPressureMomentumSolver.GasDensityModel'] = ...
        POLYTROPIC: typing.ClassVar['CoupledPressureMomentumSolver.GasDensityModel'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'CoupledPressureMomentumSolver.GasDensityModel': ...
        @staticmethod
        def values() -> typing.MutableSequence['CoupledPressureMomentumSolver.GasDensityModel']: ...
    class PressureLimitEvent(java.io.Serializable):
        def getAppliedCorrectionPa(self) -> float: ...
        def getCell(self) -> int: ...
        def getDamping(self) -> float: ...
        def getIteration(self) -> int: ...
        def getProposedCorrectionPa(self) -> float: ...
        def getReason(self) -> 'CoupledPressureMomentumSolver.PressureLimitReason': ...
    class PressureLimitReason(java.lang.Enum['CoupledPressureMomentumSolver.PressureLimitReason']):
        CORRECTION_SIZE: typing.ClassVar['CoupledPressureMomentumSolver.PressureLimitReason'] = ...
        MINIMUM_PRESSURE: typing.ClassVar['CoupledPressureMomentumSolver.PressureLimitReason'] = ...
        DENSITY_POSITIVITY: typing.ClassVar['CoupledPressureMomentumSolver.PressureLimitReason'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'CoupledPressureMomentumSolver.PressureLimitReason': ...
        @staticmethod
        def values() -> typing.MutableSequence['CoupledPressureMomentumSolver.PressureLimitReason']: ...
    class Result(java.io.Serializable):
        def getGasDensity(self) -> typing.MutableSequence[float]: ...
        def getGasSoundSpeed(self) -> typing.MutableSequence[float]: ...
        def getIterations(self) -> int: ...
        def getMaximumRelativeVolumeResidual(self) -> float: ...
        def getMinimumMassFluxCorrectionScale(self) -> float: ...
        def getOilDensity(self) -> typing.MutableSequence[float]: ...
        def getOutletBoundaryMassCorrectionKg(self) -> typing.MutableSequence[float]: ...
        def getPhaseMassCorrectionsKg(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
        def getPressure(self) -> typing.MutableSequence[float]: ...
        def getPressureLimitEvents(self) -> java.util.List['CoupledPressureMomentumSolver.PressureLimitEvent']: ...
        def getState(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
        def getWaterDensity(self) -> typing.MutableSequence[float]: ...
        def isConverged(self) -> bool: ...
        def isPressureCorrectionLimited(self) -> bool: ...

class DispersedBubbleDragSolver:
    @staticmethod
    def relax(flowRegime: jneqsim.process.equipment.pipeline.twophasepipe.PipeSection.FlowRegime, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, double9: float, double10: float, interfacialFriction: jneqsim.process.equipment.pipeline.twophasepipe.closure.InterfacialFriction) -> typing.MutableSequence[float]: ...

class MUSCLReconstructor(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, slopeLimiter: 'MUSCLReconstructor.SlopeLimiter'): ...
    def calcLimitedSlope(self, double: float, double2: float) -> float: ...
    def calcLimiter(self, double: float) -> float: ...
    def getLimiterType(self) -> 'MUSCLReconstructor.SlopeLimiter': ...
    def isSecondOrder(self) -> bool: ...
    def mc(self, double: float) -> float: ...
    def minmod(self, double: float) -> float: ...
    def minmod3(self, double: float, double2: float, double3: float) -> float: ...
    def reconstruct(self, double: float, double2: float, double3: float, double4: float) -> 'MUSCLReconstructor.ReconstructedPair': ...
    def reconstructArray(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence['MUSCLReconstructor.ReconstructedPair']: ...
    def setLimiterType(self, slopeLimiter: 'MUSCLReconstructor.SlopeLimiter') -> None: ...
    def superbee(self, double: float) -> float: ...
    def vanAlbada(self, double: float) -> float: ...
    def vanLeer(self, double: float) -> float: ...
    class ReconstructedPair(java.io.Serializable):
        left: float = ...
        right: float = ...
        def __init__(self): ...
    class SlopeLimiter(java.lang.Enum['MUSCLReconstructor.SlopeLimiter']):
        MINMOD: typing.ClassVar['MUSCLReconstructor.SlopeLimiter'] = ...
        VAN_LEER: typing.ClassVar['MUSCLReconstructor.SlopeLimiter'] = ...
        VAN_ALBADA: typing.ClassVar['MUSCLReconstructor.SlopeLimiter'] = ...
        SUPERBEE: typing.ClassVar['MUSCLReconstructor.SlopeLimiter'] = ...
        MC: typing.ClassVar['MUSCLReconstructor.SlopeLimiter'] = ...
        NONE: typing.ClassVar['MUSCLReconstructor.SlopeLimiter'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'MUSCLReconstructor.SlopeLimiter': ...
        @staticmethod
        def values() -> typing.MutableSequence['MUSCLReconstructor.SlopeLimiter']: ...

class StiffInterphaseMomentumSolver:
    @staticmethod
    def solve(doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], double4: float) -> typing.MutableSequence[float]: ...

class TimeIntegrator(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, method: 'TimeIntegrator.Method'): ...
    def advanceTime(self, double: float) -> None: ...
    def calcIMEXTimeStep(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], double3: float) -> float: ...
    def calcStableTimeStep(self, double: float, double2: float) -> float: ...
    def calcTwoFluidTimeStep(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray], double5: float) -> float: ...
    def getCflNumber(self) -> float: ...
    def getCoupledPressureLimitEvents(self) -> java.util.List[CoupledPressureMomentumSolver.PressureLimitEvent]: ...
    def getCoupledPressureMomentumGasDensity(self) -> typing.MutableSequence[float]: ...
    def getCoupledPressureMomentumGasDensityModel(self) -> CoupledPressureMomentumSolver.GasDensityModel: ...
    def getCoupledPressureMomentumGasSoundSpeed(self) -> typing.MutableSequence[float]: ...
    def getCoupledPressureMomentumIterations(self) -> int: ...
    def getCoupledPressureMomentumMaximumIterations(self) -> int: ...
    def getCoupledPressureMomentumMinimumMassFluxCorrectionScale(self) -> float: ...
    def getCoupledPressureMomentumMinimumPressure(self) -> float: ...
    def getCoupledPressureMomentumOilDensity(self) -> typing.MutableSequence[float]: ...
    def getCoupledPressureMomentumOutletMassCorrectionKg(self) -> typing.MutableSequence[float]: ...
    def getCoupledPressureMomentumPhaseMassCorrectionsKg(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getCoupledPressureMomentumPressure(self) -> typing.MutableSequence[float]: ...
    def getCoupledPressureMomentumRelativeVolumeTolerance(self) -> float: ...
    def getCoupledPressureMomentumVolumeResidual(self) -> float: ...
    def getCoupledPressureMomentumWaterDensity(self) -> typing.MutableSequence[float]: ...
    def getCurrentDt(self) -> float: ...
    def getCurrentTime(self) -> float: ...
    def getMaxTimeStep(self) -> float: ...
    def getMethod(self) -> 'TimeIntegrator.Method': ...
    def getMinTimeStep(self) -> float: ...
    def isCoupledPressureMomentumCheckerboardCorrectionEnabled(self) -> bool: ...
    def isCoupledPressureMomentumConverged(self) -> bool: ...
    def isCoupledPressureMomentumEnabled(self) -> bool: ...
    def isCoupledPressureMomentumPressureCorrectionLimited(self) -> bool: ...
    def reset(self) -> None: ...
    def setCflNumber(self, double: float) -> None: ...
    def setCoupledPressureMomentumCheckerboardCorrectionEnabled(self, boolean: bool) -> None: ...
    def setCoupledPressureMomentumEnabled(self, boolean: bool) -> None: ...
    def setCoupledPressureMomentumGasDensityModel(self, gasDensityModel: CoupledPressureMomentumSolver.GasDensityModel) -> None: ...
    def setCoupledPressureMomentumMaximumIterations(self, int: int) -> None: ...
    def setCoupledPressureMomentumMinimumPressure(self, double: float) -> None: ...
    def setCoupledPressureMomentumProperties(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray], doubleArray5: typing.Union[typing.List[float], jpype.JArray], doubleArray6: typing.Union[typing.List[float], jpype.JArray], doubleArray7: typing.Union[typing.List[float], jpype.JArray], doubleArray8: typing.Union[typing.List[float], jpype.JArray], doubleArray9: typing.Union[typing.List[float], jpype.JArray], double10: float, boolean: bool, boolean2: bool) -> None: ...
    def setCoupledPressureMomentumRelativeVolumeTolerance(self, double: float) -> None: ...
    def setCurrentTime(self, double: float) -> None: ...
    @typing.overload
    def setIMEXProperties(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], double3: float, double4: float, boolean: bool) -> None: ...
    @typing.overload
    def setIMEXProperties(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray], doubleArray5: typing.Union[typing.List[float], jpype.JArray], doubleArray6: typing.Union[typing.List[float], jpype.JArray], double7: float, double8: float, boolean: bool) -> None: ...
    def setImplicitVoidWaveProperties(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray], doubleArray5: typing.Union[typing.List[float], jpype.JArray], doubleArray6: typing.Union[typing.List[float], jpype.JArray], double7: float, boolean: bool) -> None: ...
    def setMaxTimeStep(self, double: float) -> None: ...
    def setMethod(self, method: 'TimeIntegrator.Method') -> None: ...
    def setMinTimeStep(self, double: float) -> None: ...
    def step(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], rHSFunction: typing.Union['TimeIntegrator.RHSFunction', typing.Callable], double2: float) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def stepEuler(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], rHSFunction: typing.Union['TimeIntegrator.RHSFunction', typing.Callable], double2: float) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def stepIMEXPressureCorrection(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], rHSFunction: typing.Union['TimeIntegrator.RHSFunction', typing.Callable], double2: float) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def stepRK2(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], rHSFunction: typing.Union['TimeIntegrator.RHSFunction', typing.Callable], double2: float) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def stepRK4(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], rHSFunction: typing.Union['TimeIntegrator.RHSFunction', typing.Callable], double2: float) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def stepSSPRK3(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], rHSFunction: typing.Union['TimeIntegrator.RHSFunction', typing.Callable], double2: float) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    class Method(java.lang.Enum['TimeIntegrator.Method']):
        EULER: typing.ClassVar['TimeIntegrator.Method'] = ...
        RK2: typing.ClassVar['TimeIntegrator.Method'] = ...
        RK4: typing.ClassVar['TimeIntegrator.Method'] = ...
        SSP_RK3: typing.ClassVar['TimeIntegrator.Method'] = ...
        IMEX_PRESSURE_CORRECTION: typing.ClassVar['TimeIntegrator.Method'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TimeIntegrator.Method': ...
        @staticmethod
        def values() -> typing.MutableSequence['TimeIntegrator.Method']: ...
    class RHSFunction:
        def evaluate(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], double2: float) -> typing.MutableSequence[typing.MutableSequence[float]]: ...

class TwoFluidUnsplitIntegrator:
    @typing.overload
    def __init__(self, twoFluidConservationEquations: jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidConservationEquations, phaseDensityModel: typing.Union['TwoFluidUnsplitModelAdapter.PhaseDensityModel', typing.Callable], unsplitTransientSolver: 'UnsplitTransientSolver'): ...
    @typing.overload
    def __init__(self, twoFluidConservationEquations: jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidConservationEquations, phaseDensityModel: typing.Union['TwoFluidUnsplitModelAdapter.PhaseDensityModel', typing.Callable], unsplitTransientSolver: 'UnsplitTransientSolver', int: int, int2: int): ...
    def isPressureInterpolationEnabled(self) -> bool: ...
    @typing.overload
    def prepareInterval(self, twoFluidSectionArray: typing.Union[typing.List[jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidSection], jpype.JArray], double: float, double2: float, double3: float, double4: float, boolean: bool, double5: float) -> 'TwoFluidUnsplitIntegrator.PreparedInterval': ...
    @typing.overload
    def prepareInterval(self, twoFluidSectionArray: typing.Union[typing.List[jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidSection], jpype.JArray], double: float, double2: float, double3: float, double4: float, boolean: bool, double5: float, double6: float) -> 'TwoFluidUnsplitIntegrator.PreparedInterval': ...
    def setPressureInterpolationEnabled(self, boolean: bool) -> None: ...
    class IntervalPreparationException(java.lang.IllegalStateException):
        def getAttemptedTimeStepSeconds(self) -> float: ...
        def getFailureTimeSeconds(self) -> float: ...
        def getPreparedSubsteps(self) -> int: ...
        def getRejectedAttempts(self) -> int: ...
        def getTerminationReason(self) -> 'UnsplitTransientSolver.TerminationReason': ...
    class PreparedInterval(java.io.Serializable):
        def getEndTimeSeconds(self) -> float: ...
        def getEndpointSections(self) -> typing.MutableSequence[jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidSection]: ...
        def getMassResidualKg(self) -> typing.MutableSequence[float]: ...
        def getMaximumScaledResidual(self) -> float: ...
        def getModelEvaluations(self) -> int: ...
        def getPhaseMassFaceTransferKg(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
        def getPhaseMassSourceTransferKg(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
        def getRejectedAttempts(self) -> int: ...
        def getStartTimeSeconds(self) -> float: ...
        def getSubsteps(self) -> java.util.List['TwoFluidUnsplitModelAdapter.PreparedStep']: ...

class TwoFluidUnsplitPublication(java.io.Serializable):
    @typing.overload
    def createOutletFluid(self, systemInterface: jneqsim.thermo.system.SystemInterface, systemInterface2: jneqsim.thermo.system.SystemInterface, double: float, double2: float) -> jneqsim.thermo.system.SystemInterface: ...
    @typing.overload
    def createOutletFluid(self, systemInterface: jneqsim.thermo.system.SystemInterface, systemInterface2: jneqsim.thermo.system.SystemInterface, twoFluidSectionArray: typing.Union[typing.List[jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidSection], jpype.JArray], double: float, double2: float) -> jneqsim.thermo.system.SystemInterface: ...
    def getAcceptedSubsteps(self) -> int: ...
    def getElapsedTimeSeconds(self) -> float: ...
    def getEndTimeSeconds(self) -> float: ...
    def getEndpointSections(self) -> typing.MutableSequence[jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidSection]: ...
    def getFinalMassKg(self) -> typing.MutableSequence[float]: ...
    def getInitialMassKg(self) -> typing.MutableSequence[float]: ...
    def getInletMassKg(self) -> typing.MutableSequence[float]: ...
    def getOutletMassFlowKgPerSecond(self) -> typing.MutableSequence[float]: ...
    def getOutletMassKg(self) -> typing.MutableSequence[float]: ...
    def getSourceMassKg(self) -> typing.MutableSequence[float]: ...
    def getStartTimeSeconds(self) -> float: ...
    @staticmethod
    def prepare(preparedInterval: TwoFluidUnsplitIntegrator.PreparedInterval, twoFluidSectionArray: typing.Union[typing.List[jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidSection], jpype.JArray], double: float, double2: float, double3: float) -> 'TwoFluidUnsplitPublication': ...

class UnsplitTransientSolver(java.io.Serializable):
    CONSERVATIVE_VARIABLE_COUNT: typing.ClassVar[int] = ...
    BLOCK_SIZE: typing.ClassVar[int] = ...
    def __init__(self): ...
    def getCellStencilHalfWidth(self) -> int: ...
    def getMaximumActiveSetUpdates(self) -> int: ...
    def getMaximumIterations(self) -> int: ...
    def getMinimumPressure(self) -> float: ...
    def getRelativeTolerance(self) -> float: ...
    def getTimeIntegrationMethod(self) -> 'UnsplitTransientSolver.TimeIntegrationMethod': ...
    def residual(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray], doubleArray5: typing.Union[typing.List[float], jpype.JArray], double6: float, double7: float, double8: float, boolean: bool, model: typing.Union['UnsplitTransientSolver.Model', typing.Callable]) -> typing.MutableSequence[float]: ...
    def scaledJacobian(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray], doubleArray5: typing.Union[typing.List[float], jpype.JArray], double6: float, double7: float, double8: float, boolean: bool, model: typing.Union['UnsplitTransientSolver.Model', typing.Callable]) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def setCellStencilHalfWidth(self, int: int) -> None: ...
    def setMaximumActiveSetUpdates(self, int: int) -> None: ...
    def setMaximumIterations(self, int: int) -> None: ...
    def setMinimumPressure(self, double: float) -> None: ...
    def setRelativeTolerance(self, double: float) -> None: ...
    def setTimeIntegrationMethod(self, timeIntegrationMethod: 'UnsplitTransientSolver.TimeIntegrationMethod') -> None: ...
    def solve(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], double4: float, double5: float, double6: float, boolean: bool, model: typing.Union['UnsplitTransientSolver.Model', typing.Callable]) -> 'UnsplitTransientSolver.Result': ...
    class Evaluation:
        def __init__(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]): ...
    class Model:
        def beginLinearization(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
        def endLinearization(self) -> None: ...
        def evaluate(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray], double5: float, double6: float, boolean: bool) -> 'UnsplitTransientSolver.Evaluation': ...
        def updateActiveSet(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> bool: ...
    class Result(java.io.Serializable):
        def getIterations(self) -> int: ...
        def getMaximumScaledResidual(self) -> float: ...
        def getMinimumAcceptedStepLength(self) -> float: ...
        def getModelEvaluations(self) -> int: ...
        def getPressure(self) -> typing.MutableSequence[float]: ...
        def getState(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
        def getTerminationReason(self) -> 'UnsplitTransientSolver.TerminationReason': ...
        def getTimeIntegrationWeight(self) -> float: ...
        def isActiveSetStable(self) -> bool: ...
        def isConverged(self) -> bool: ...
    class TerminationReason(java.lang.Enum['UnsplitTransientSolver.TerminationReason']):
        CONVERGED: typing.ClassVar['UnsplitTransientSolver.TerminationReason'] = ...
        MAXIMUM_ITERATIONS: typing.ClassVar['UnsplitTransientSolver.TerminationReason'] = ...
        ACTIVE_SET_UPDATE_LIMIT: typing.ClassVar['UnsplitTransientSolver.TerminationReason'] = ...
        SINGULAR_JACOBIAN: typing.ClassVar['UnsplitTransientSolver.TerminationReason'] = ...
        NO_ADMISSIBLE_STEP: typing.ClassVar['UnsplitTransientSolver.TerminationReason'] = ...
        LINE_SEARCH_FAILED: typing.ClassVar['UnsplitTransientSolver.TerminationReason'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'UnsplitTransientSolver.TerminationReason': ...
        @staticmethod
        def values() -> typing.MutableSequence['UnsplitTransientSolver.TerminationReason']: ...
    class TimeIntegrationMethod(java.lang.Enum['UnsplitTransientSolver.TimeIntegrationMethod']):
        IMPLICIT_MIDPOINT: typing.ClassVar['UnsplitTransientSolver.TimeIntegrationMethod'] = ...
        BACKWARD_EULER: typing.ClassVar['UnsplitTransientSolver.TimeIntegrationMethod'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'UnsplitTransientSolver.TimeIntegrationMethod': ...
        @staticmethod
        def values() -> typing.MutableSequence['UnsplitTransientSolver.TimeIntegrationMethod']: ...

class TwoFluidUnsplitModelAdapter(UnsplitTransientSolver.Model, java.io.Serializable):
    @typing.overload
    def __init__(self, twoFluidConservationEquations: jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidConservationEquations, twoFluidSectionArray: typing.Union[typing.List[jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidSection], jpype.JArray], double: float, phaseDensityModel: typing.Union['TwoFluidUnsplitModelAdapter.PhaseDensityModel', typing.Callable]): ...
    @typing.overload
    def __init__(self, twoFluidConservationEquations: jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidConservationEquations, twoFluidSectionArray: typing.Union[typing.List[jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidSection], jpype.JArray], double: float, phaseDensityModel: typing.Union['TwoFluidUnsplitModelAdapter.PhaseDensityModel', typing.Callable], double2: float): ...
    @typing.overload
    def __init__(self, twoFluidConservationEquations: jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidConservationEquations, twoFluidSectionArray: typing.Union[typing.List[jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidSection], jpype.JArray], double: float, phaseDensityModel: typing.Union['TwoFluidUnsplitModelAdapter.PhaseDensityModel', typing.Callable], activeSetController: 'TwoFluidUnsplitModelAdapter.ActiveSetController'): ...
    @typing.overload
    def __init__(self, twoFluidConservationEquations: jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidConservationEquations, twoFluidSectionArray: typing.Union[typing.List[jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidSection], jpype.JArray], double: float, phaseDensityModel: typing.Union['TwoFluidUnsplitModelAdapter.PhaseDensityModel', typing.Callable], activeSetController: 'TwoFluidUnsplitModelAdapter.ActiveSetController', double2: float): ...
    def beginLinearization(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def endLinearization(self) -> None: ...
    def evaluate(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray], double5: float, double6: float, boolean: bool) -> UnsplitTransientSolver.Evaluation: ...
    def prepareStep(self, result: UnsplitTransientSolver.Result, double: float, double2: float, double3: float, boolean: bool, double4: float) -> 'TwoFluidUnsplitModelAdapter.PreparedStep': ...
    def updateActiveSet(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> bool: ...
    class ActiveSetController(java.io.Serializable):
        def beginLinearization(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
        def endLinearization(self) -> None: ...
        def update(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> bool: ...
    class PhaseDensityModel(java.io.Serializable):
        def calculate(self, int: int, doubleArray: typing.Union[typing.List[float], jpype.JArray], double2: float, double3: float) -> typing.MutableSequence[float]: ...
    class PreparedStep(java.io.Serializable):
        def getEndpointSections(self) -> typing.MutableSequence[jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidSection]: ...
        def getEvaluation(self) -> jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidConservationEquations.TransactionalEvaluation: ...
        def getEvaluationTimeSeconds(self) -> float: ...
        def getFinalMassKg(self) -> typing.MutableSequence[float]: ...
        def getInitialMassKg(self) -> typing.MutableSequence[float]: ...
        def getMassResidualKg(self) -> typing.MutableSequence[float]: ...
        def getMaximumScaledResidual(self) -> float: ...
        def getMidpointEvaluation(self) -> jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidConservationEquations.TransactionalEvaluation: ...
        def getPressureInterpolationTimeScale(self) -> float: ...
        def getStartTimeSeconds(self) -> float: ...
        def getTimeIntegrationWeight(self) -> float: ...
        def getTimeStepSeconds(self) -> float: ...

class AnchoredIsothermalDensityModel(TwoFluidUnsplitModelAdapter.PhaseDensityModel, java.lang.Cloneable):
    def __init__(self, twoFluidSectionArray: typing.Union[typing.List[jneqsim.process.equipment.pipeline.twophasepipe.TwoFluidSection], jpype.JArray], systemInterfaceArray: typing.Union[typing.List[jneqsim.thermo.system.SystemInterface], jpype.JArray]): ...
    def calculate(self, int: int, doubleArray: typing.Union[typing.List[float], jpype.JArray], double2: float, double3: float) -> typing.MutableSequence[float]: ...
    def clone(self) -> 'AnchoredIsothermalDensityModel': ...
    def getNumberOfCells(self) -> int: ...
    def getReferenceIsothermalCompressibility(self, int: int, int2: int) -> float: ...
    def hasPhase(self, int: int, int2: int) -> bool: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.pipeline.twophasepipe.numerics")``.

    AUSMPlusFluxCalculator: typing.Type[AUSMPlusFluxCalculator]
    AnchoredIsothermalDensityModel: typing.Type[AnchoredIsothermalDensityModel]
    ConservativeStateLimiter: typing.Type[ConservativeStateLimiter]
    CoupledPressureMomentumSolver: typing.Type[CoupledPressureMomentumSolver]
    DispersedBubbleDragSolver: typing.Type[DispersedBubbleDragSolver]
    MUSCLReconstructor: typing.Type[MUSCLReconstructor]
    StiffInterphaseMomentumSolver: typing.Type[StiffInterphaseMomentumSolver]
    TimeIntegrator: typing.Type[TimeIntegrator]
    TwoFluidUnsplitIntegrator: typing.Type[TwoFluidUnsplitIntegrator]
    TwoFluidUnsplitModelAdapter: typing.Type[TwoFluidUnsplitModelAdapter]
    TwoFluidUnsplitPublication: typing.Type[TwoFluidUnsplitPublication]
    UnsplitTransientSolver: typing.Type[UnsplitTransientSolver]
