import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.thermo.system
import typing

class AmineHeatOfAbsorption(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        amineType: "AmineHeatOfAbsorption.AmineType",
        double: float,
        double2: float,
        double3: float,
    ): ...
    def calcHeatOfAbsorptionCO2(self) -> float: ...
    def calcHeatOfAbsorptionH2S(self) -> float: ...
    def calcTotalHeatReleased(self) -> float: ...
    def getAbsorptionProperties(self) -> java.util.Map[java.lang.String, float]: ...
    def getAmineConcentration(self) -> float: ...
    def getAmineType(self) -> "AmineHeatOfAbsorption.AmineType": ...
    def getCO2Loading(self) -> float: ...
    def getTemperature(self) -> float: ...
    def setAmineConcentration(self, double: float) -> None: ...
    def setAmineType(self, amineType: "AmineHeatOfAbsorption.AmineType") -> None: ...
    def setCO2Loading(self, double: float) -> None: ...
    def setTemperature(self, double: float) -> None: ...

    class AmineType(java.lang.Enum["AmineHeatOfAbsorption.AmineType"]):
        MEA: typing.ClassVar["AmineHeatOfAbsorption.AmineType"] = ...
        DEA: typing.ClassVar["AmineHeatOfAbsorption.AmineType"] = ...
        MDEA: typing.ClassVar["AmineHeatOfAbsorption.AmineType"] = ...
        AMDEA: typing.ClassVar["AmineHeatOfAbsorption.AmineType"] = ...
        def getMaxLoading(self) -> float: ...
        def getMolarMass(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "AmineHeatOfAbsorption.AmineType": ...
        @staticmethod
        def values() -> typing.MutableSequence["AmineHeatOfAbsorption.AmineType"]: ...

class AmineSystem(java.io.Serializable):
    @typing.overload
    def __init__(self, amineType: "AmineSystem.AmineType"): ...
    @typing.overload
    def __init__(
        self, amineType: "AmineSystem.AmineType", double: float, double2: float
    ): ...
    def calcBubblePointPressure(self) -> float: ...
    def createSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getAmineType(self) -> "AmineSystem.AmineType": ...
    def getCO2PartialPressure(self) -> float: ...
    def getHeatCalculator(self) -> AmineHeatOfAbsorption: ...
    def getHeatOfAbsorptionCO2(self) -> float: ...
    def getHeatOfAbsorptionH2S(self) -> float: ...
    def getSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getTotalHeatReleased(self) -> float: ...
    def getpH(self) -> float: ...
    def runTPflash(self) -> jneqsim.thermo.system.SystemInterface: ...
    def setAmineConcentration(self, double: float) -> None: ...
    def setCO2Loading(self, double: float) -> None: ...
    def setH2SLoading(self, double: float) -> None: ...
    def setPiperazineConcentration(self, double: float) -> None: ...
    def toString(self) -> java.lang.String: ...

    class AmineType(java.lang.Enum["AmineSystem.AmineType"]):
        MEA: typing.ClassVar["AmineSystem.AmineType"] = ...
        DEA: typing.ClassVar["AmineSystem.AmineType"] = ...
        MDEA: typing.ClassVar["AmineSystem.AmineType"] = ...
        AMDEA: typing.ClassVar["AmineSystem.AmineType"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "AmineSystem.AmineType": ...
        @staticmethod
        def values() -> typing.MutableSequence["AmineSystem.AmineType"]: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.thermo.util.amines")``.

    AmineHeatOfAbsorption: typing.Type[AmineHeatOfAbsorption]
    AmineSystem: typing.Type[AmineSystem]
