
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jpype
import neqsim.process.equipment.separator
import neqsim.process.equipment.splitter
import neqsim.process.equipment.valve
import neqsim.process.logic
import typing



class ActivateBlowdownAction(neqsim.process.logic.LogicAction):
    def __init__(self, blowdownValve: neqsim.process.equipment.valve.BlowdownValve): ...
    def execute(self) -> None: ...
    def getDescription(self) -> java.lang.String: ...
    def getTargetName(self) -> java.lang.String: ...
    def isComplete(self) -> bool: ...

class CloseValveAction(neqsim.process.logic.LogicAction):
    def __init__(self, throttlingValve: neqsim.process.equipment.valve.ThrottlingValve): ...
    def execute(self) -> None: ...
    def getDescription(self) -> java.lang.String: ...
    def getTargetName(self) -> java.lang.String: ...
    def isComplete(self) -> bool: ...

class ConditionalAction(neqsim.process.logic.LogicAction):
    @typing.overload
    def __init__(self, logicCondition: neqsim.process.logic.LogicCondition, logicAction: neqsim.process.logic.LogicAction, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, logicCondition: neqsim.process.logic.LogicCondition, logicAction: neqsim.process.logic.LogicAction, logicAction2: neqsim.process.logic.LogicAction, string: typing.Union[java.lang.String, str]): ...
    def execute(self) -> None: ...
    def getAlternativeAction(self) -> neqsim.process.logic.LogicAction: ...
    def getCondition(self) -> neqsim.process.logic.LogicCondition: ...
    def getDescription(self) -> java.lang.String: ...
    def getPrimaryAction(self) -> neqsim.process.logic.LogicAction: ...
    def getSelectedAction(self) -> neqsim.process.logic.LogicAction: ...
    def getTargetName(self) -> java.lang.String: ...
    def isComplete(self) -> bool: ...
    def isEvaluated(self) -> bool: ...
    def reset(self) -> None: ...

class EnergizeESDValveAction(neqsim.process.logic.LogicAction):
    @typing.overload
    def __init__(self, eSDValve: neqsim.process.equipment.valve.ESDValve): ...
    @typing.overload
    def __init__(self, eSDValve: neqsim.process.equipment.valve.ESDValve, double: float): ...
    def execute(self) -> None: ...
    def getDescription(self) -> java.lang.String: ...
    def getTargetName(self) -> java.lang.String: ...
    def isComplete(self) -> bool: ...

class OpenValveAction(neqsim.process.logic.LogicAction):
    def __init__(self, throttlingValve: neqsim.process.equipment.valve.ThrottlingValve): ...
    def execute(self) -> None: ...
    def getDescription(self) -> java.lang.String: ...
    def getTargetName(self) -> java.lang.String: ...
    def isComplete(self) -> bool: ...

class ParallelActionGroup(neqsim.process.logic.LogicAction):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addAction(self, logicAction: neqsim.process.logic.LogicAction) -> None: ...
    def execute(self) -> None: ...
    def getActions(self) -> java.util.List[neqsim.process.logic.LogicAction]: ...
    def getCompletedCount(self) -> int: ...
    def getCompletionPercentage(self) -> float: ...
    def getDescription(self) -> java.lang.String: ...
    def getTargetName(self) -> java.lang.String: ...
    def getTotalCount(self) -> int: ...
    def isComplete(self) -> bool: ...
    def toString(self) -> java.lang.String: ...

class SetSeparatorModeAction(neqsim.process.logic.LogicAction):
    def __init__(self, separator: neqsim.process.equipment.separator.Separator, boolean: bool): ...
    def execute(self) -> None: ...
    def getDescription(self) -> java.lang.String: ...
    def getTargetName(self) -> java.lang.String: ...
    def isComplete(self) -> bool: ...
    def isSteadyState(self) -> bool: ...

class SetSplitterAction(neqsim.process.logic.LogicAction):
    def __init__(self, splitter: neqsim.process.equipment.splitter.Splitter, doubleArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def execute(self) -> None: ...
    def getDescription(self) -> java.lang.String: ...
    def getTargetName(self) -> java.lang.String: ...
    def isComplete(self) -> bool: ...

class SetValveOpeningAction(neqsim.process.logic.LogicAction):
    def __init__(self, throttlingValve: neqsim.process.equipment.valve.ThrottlingValve, double: float): ...
    def execute(self) -> None: ...
    def getDescription(self) -> java.lang.String: ...
    def getTargetName(self) -> java.lang.String: ...
    def getTargetOpening(self) -> float: ...
    def isComplete(self) -> bool: ...

class TripValveAction(neqsim.process.logic.LogicAction):
    def __init__(self, eSDValve: neqsim.process.equipment.valve.ESDValve): ...
    def execute(self) -> None: ...
    def getDescription(self) -> java.lang.String: ...
    def getTargetName(self) -> java.lang.String: ...
    def isComplete(self) -> bool: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("neqsim.process.logic.action")``.

    ActivateBlowdownAction: typing.Type[ActivateBlowdownAction]
    CloseValveAction: typing.Type[CloseValveAction]
    ConditionalAction: typing.Type[ConditionalAction]
    EnergizeESDValveAction: typing.Type[EnergizeESDValveAction]
    OpenValveAction: typing.Type[OpenValveAction]
    ParallelActionGroup: typing.Type[ParallelActionGroup]
    SetSeparatorModeAction: typing.Type[SetSeparatorModeAction]
    SetSplitterAction: typing.Type[SetSplitterAction]
    SetValveOpeningAction: typing.Type[SetValveOpeningAction]
    TripValveAction: typing.Type[TripValveAction]
