
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import typing



class DemistingInternal(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def calcGasVelocity(self, double: float, double2: float, double3: float) -> float: ...
    def calcLiquidCarryOver(self, double: float, double2: float) -> float: ...
    def calcPressureDrop(self, double: float, double2: float) -> float: ...
    def getArea(self) -> float: ...
    def getEuNumber(self) -> float: ...
    def getKFactor(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getThickness(self) -> float: ...
    def getType(self) -> java.lang.String: ...
    def getVoidFraction(self) -> float: ...
    def getWireDiameter(self) -> float: ...
    def setArea(self, double: float) -> None: ...
    def setEuNumber(self, double: float) -> None: ...
    def setKFactor(self, double: float) -> None: ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setThickness(self, double: float) -> None: ...
    def setType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setVoidFraction(self, double: float) -> None: ...
    def setWireDiameter(self, double: float) -> None: ...

class DemistingInternalWithDrainage(DemistingInternal):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def calcLiquidCarryOver(self, double: float, double2: float) -> float: ...
    def getDrainageEfficiency(self) -> float: ...
    def setDrainageEfficiency(self, double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.separator.internals")``.

    DemistingInternal: typing.Type[DemistingInternal]
    DemistingInternalWithDrainage: typing.Type[DemistingInternalWithDrainage]
