import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.blackoil
import jneqsim.process.equipment
import jneqsim.process.util.report
import typing

class BlackOilSeparator(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        systemBlackOil: jneqsim.blackoil.SystemBlackOil,
        double: float,
        double2: float,
    ): ...
    def getBlackOilInlet(self) -> jneqsim.blackoil.SystemBlackOil: ...
    def getGasOut(self) -> jneqsim.blackoil.SystemBlackOil: ...
    def getLastFlashResult(self) -> jneqsim.blackoil.BlackOilFlashResult: ...
    def getOilOut(self) -> jneqsim.blackoil.SystemBlackOil: ...
    @typing.overload
    def getOutletPressure(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    @typing.overload
    def getOutletPressure(self) -> float: ...
    @typing.overload
    def getOutletTemperature(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    @typing.overload
    def getOutletTemperature(self) -> float: ...
    def getResultsMap(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def getWaterOut(self) -> jneqsim.blackoil.SystemBlackOil: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def runSeparation(self) -> None: ...
    def setInlet(self, systemBlackOil: jneqsim.blackoil.SystemBlackOil) -> None: ...
    def setOutletPressure(self, double: float) -> None: ...
    def setOutletTemperature(self, double: float) -> None: ...
    @typing.overload
    def toJson(
        self, reportConfig: jneqsim.process.util.report.ReportConfig
    ) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.blackoil")``.

    BlackOilSeparator: typing.Type[BlackOilSeparator]
