
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import com.google.gson
import java.io
import java.lang
import java.util
import jneqsim.process.automation
import typing



class BaselineComparator(java.io.Serializable):
    def __init__(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]]): ...
    def addCriterion(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'BaselineComparator': ...
    def addStepTrigger(self, string: typing.Union[java.lang.String, str], double: float) -> 'BaselineComparator': ...
    def compare(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]]) -> com.google.gson.JsonObject: ...

class ImprovementCycle(java.io.Serializable):
    def __init__(self, processAutomation: jneqsim.process.automation.ProcessAutomation): ...
    def addKpi(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'ImprovementCycle': ...
    def getComparator(self) -> BaselineComparator: ...
    def getDriftMonitor(self) -> 'ModelDriftMonitor': ...
    def runCycle(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    def setComparator(self, baselineComparator: BaselineComparator) -> 'ImprovementCycle': ...
    def setConvergence(self, int: int, double: float) -> 'ImprovementCycle': ...
    def setDriftMonitor(self, modelDriftMonitor: 'ModelDriftMonitor') -> 'ImprovementCycle': ...

class ModelDriftMonitor(java.io.Serializable):
    def __init__(self): ...
    def getState(self, string: typing.Union[java.lang.String, str]) -> 'ModelDriftMonitor.SignalState': ...
    def reset(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setCusum(self, double: float, double2: float) -> 'ModelDriftMonitor': ...
    def setLambda(self, double: float) -> 'ModelDriftMonitor': ...
    def setLimitWidth(self, double: float) -> 'ModelDriftMonitor': ...
    def setMinSigma(self, string: typing.Union[java.lang.String, str], double: float) -> 'ModelDriftMonitor': ...
    def setWarmup(self, int: int, int2: int) -> 'ModelDriftMonitor': ...
    def update(self, string: typing.Union[java.lang.String, str], double: float) -> com.google.gson.JsonObject: ...
    class SignalState(java.io.Serializable):
        def __init__(self): ...
        def getMean(self) -> float: ...
        def isAlarm(self) -> bool: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.operations.continuous")``.

    BaselineComparator: typing.Type[BaselineComparator]
    ImprovementCycle: typing.Type[ImprovementCycle]
    ModelDriftMonitor: typing.Type[ModelDriftMonitor]
