import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import Jama
import java.io
import java.lang
import jpype
import jneqsim.statistics.parameterfitting
import typing

class LevenbergMarquardt(jneqsim.statistics.parameterfitting.StatisticsBaseClass):
    def __init__(self): ...
    def clone(self) -> "LevenbergMarquardt": ...
    def getMaxNumberOfIterations(self) -> int: ...
    def getResult(self) -> "LevenbergMarquardtResult": ...
    def init(self) -> None: ...
    def isSolved(self) -> bool: ...
    @staticmethod
    def main(
        stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray],
    ) -> None: ...
    def setMaxNumberOfIterations(self, int: int) -> None: ...
    def solve(self) -> None: ...

class LevenbergMarquardtFunction(jneqsim.statistics.parameterfitting.BaseFunction):
    def __init__(self): ...
    def calcValue(
        self, doubleArray: typing.Union[typing.List[float], jpype.JArray]
    ) -> float: ...
    @typing.overload
    def getFittingParams(self, int: int) -> float: ...
    @typing.overload
    def getFittingParams(self) -> typing.MutableSequence[float]: ...
    def getNumberOfFittingParams(self) -> int: ...
    def setFittingParam(self, int: int, double: float) -> None: ...
    @typing.overload
    def setFittingParams(
        self, doubleArray: typing.Union[typing.List[float], jpype.JArray]
    ) -> None: ...
    @typing.overload
    def setFittingParams(self, int: int, double: float) -> None: ...

class LevenbergMarquardtResult(java.io.Serializable):
    def __init__(
        self,
        convergenceReason: "LevenbergMarquardtResult.ConvergenceReason",
        int: int,
        double: float,
        double2: float,
        matrix: Jama.Matrix,
        matrix2: Jama.Matrix,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
    ): ...
    def getConvergenceReason(self) -> "LevenbergMarquardtResult.ConvergenceReason": ...
    def getCorrelationMatrix(self) -> Jama.Matrix: ...
    def getCorrelationMatrixArray(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getCovarianceMatrix(self) -> Jama.Matrix: ...
    def getCovarianceMatrixArray(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getFinalChiSquare(self) -> float: ...
    def getGradientNorm(self) -> float: ...
    def getIterations(self) -> int: ...
    def getParameterStandardErrors(self) -> typing.MutableSequence[float]: ...
    def isConverged(self) -> bool: ...
    @staticmethod
    def notRun() -> "LevenbergMarquardtResult": ...

    class ConvergenceReason(
        java.lang.Enum["LevenbergMarquardtResult.ConvergenceReason"]
    ):
        NOT_RUN: typing.ClassVar["LevenbergMarquardtResult.ConvergenceReason"] = ...
        CHI_SQUARE_TOLERANCE: typing.ClassVar[
            "LevenbergMarquardtResult.ConvergenceReason"
        ] = ...
        GRADIENT_TOLERANCE: typing.ClassVar[
            "LevenbergMarquardtResult.ConvergenceReason"
        ] = ...
        MAX_ITERATIONS_REACHED: typing.ClassVar[
            "LevenbergMarquardtResult.ConvergenceReason"
        ] = ...
        SINGULAR_MATRIX: typing.ClassVar[
            "LevenbergMarquardtResult.ConvergenceReason"
        ] = ...
        def isConverged(self) -> bool: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "LevenbergMarquardtResult.ConvergenceReason": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["LevenbergMarquardtResult.ConvergenceReason"]
        ): ...

class LevenbergMarquardtAbsDev(LevenbergMarquardt):
    def __init__(self): ...
    def calcAlphaMatrix(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def calcBetaMatrix(self) -> typing.MutableSequence[float]: ...
    def calcChiSquare(self) -> float: ...
    def clone(self) -> "LevenbergMarquardtAbsDev": ...

class LevenbergMarquardtBiasDev(LevenbergMarquardt):
    def __init__(self): ...
    def calcAlphaMatrix(
        self,
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def calcBetaMatrix(self) -> typing.MutableSequence[float]: ...
    def calcChiSquare(self) -> float: ...
    def clone(self) -> "LevenbergMarquardtBiasDev": ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.statistics.parameterfitting.nonlinearparameterfitting")``.

    LevenbergMarquardt: typing.Type[LevenbergMarquardt]
    LevenbergMarquardtAbsDev: typing.Type[LevenbergMarquardtAbsDev]
    LevenbergMarquardtBiasDev: typing.Type[LevenbergMarquardtBiasDev]
    LevenbergMarquardtFunction: typing.Type[LevenbergMarquardtFunction]
    LevenbergMarquardtResult: typing.Type[LevenbergMarquardtResult]
