
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.fluidmechanics.flowsystem
import jneqsim.process.equipment
import jneqsim.process.equipment.pipeline
import jneqsim.process.equipment.pipeline.twophasepipe.closure
import jneqsim.process.equipment.pipeline.twophasepipe.numerics
import jneqsim.process.equipment.stream
import jneqsim.thermo.system
import typing



class DriftFluxModel(java.io.Serializable):
    def __init__(self): ...
    def calculateDriftFlux(self, pipeSection: 'PipeSection') -> 'DriftFluxModel.DriftFluxParameters': ...
    def calculateEnergyEquation(self, pipeSection: 'PipeSection', driftFluxParameters: 'DriftFluxModel.DriftFluxParameters', double: float, double2: float, double3: float, double4: float, double5: float) -> 'DriftFluxModel.EnergyEquationResult': ...
    def calculateMixtureHeatCapacity(self, pipeSection: 'PipeSection', driftFluxParameters: 'DriftFluxModel.DriftFluxParameters', double: float, double2: float) -> float: ...
    def calculatePressureGradient(self, pipeSection: 'PipeSection', driftFluxParameters: 'DriftFluxModel.DriftFluxParameters') -> float: ...
    def calculateSteadyStateTemperature(self, pipeSection: 'PipeSection', double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> float: ...
    def estimateJouleThomsonCoefficient(self, double: float, double2: float, double3: float) -> float: ...
    class DriftFluxParameters(java.io.Serializable):
        C0: float = ...
        driftVelocity: float = ...
        gasVelocity: float = ...
        liquidVelocity: float = ...
        slipRatio: float = ...
        voidFraction: float = ...
        liquidHoldup: float = ...
        def __init__(self): ...
    class EnergyEquationResult(java.io.Serializable):
        newTemperature: float = ...
        jouleThomsonDeltaT: float = ...
        heatTransferDeltaT: float = ...
        frictionHeatingDeltaT: float = ...
        elevationWorkDeltaT: float = ...
        heatTransferRate: float = ...
        frictionHeatingPower: float = ...
        def __init__(self): ...

class EntrainmentDeposition(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, entrainmentModel: 'EntrainmentDeposition.EntrainmentModel', depositionModel: 'EntrainmentDeposition.DepositionModel'): ...
    def calculate(self, flowRegime: 'PipeSection.FlowRegime', double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, double9: float) -> 'EntrainmentDeposition.EntrainmentResult': ...
    def getCriticalReFilm(self) -> float: ...
    def getCriticalWeber(self) -> float: ...
    def getDepositionModel(self) -> 'EntrainmentDeposition.DepositionModel': ...
    def getEntrainmentModel(self) -> 'EntrainmentDeposition.EntrainmentModel': ...
    def setCriticalReFilm(self, double: float) -> None: ...
    def setCriticalWeber(self, double: float) -> None: ...
    def setDepositionModel(self, depositionModel: 'EntrainmentDeposition.DepositionModel') -> None: ...
    def setEntrainmentModel(self, entrainmentModel: 'EntrainmentDeposition.EntrainmentModel') -> None: ...
    class DepositionModel(java.lang.Enum['EntrainmentDeposition.DepositionModel']):
        MCCOY_HANRATTY: typing.ClassVar['EntrainmentDeposition.DepositionModel'] = ...
        RELAXATION: typing.ClassVar['EntrainmentDeposition.DepositionModel'] = ...
        COUSINS: typing.ClassVar['EntrainmentDeposition.DepositionModel'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EntrainmentDeposition.DepositionModel': ...
        @staticmethod
        def values() -> typing.MutableSequence['EntrainmentDeposition.DepositionModel']: ...
    class EntrainmentModel(java.lang.Enum['EntrainmentDeposition.EntrainmentModel']):
        ISHII_MISHIMA: typing.ClassVar['EntrainmentDeposition.EntrainmentModel'] = ...
        PAN_HANRATTY: typing.ClassVar['EntrainmentDeposition.EntrainmentModel'] = ...
        OLIEMANS: typing.ClassVar['EntrainmentDeposition.EntrainmentModel'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EntrainmentDeposition.EntrainmentModel': ...
        @staticmethod
        def values() -> typing.MutableSequence['EntrainmentDeposition.EntrainmentModel']: ...
    class EntrainmentResult(java.io.Serializable):
        entrainmentRate: float = ...
        depositionRate: float = ...
        netTransferRate: float = ...
        entrainmentFraction: float = ...
        dropletDiameter: float = ...
        dropletConcentration: float = ...
        filmReynoldsNumber: float = ...
        isEntraining: bool = ...
        def __init__(self): ...

class FlashTable(java.io.Serializable):
    def __init__(self): ...
    def build(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float, int: int, double3: float, double4: float, int2: int) -> None: ...
    def clear(self) -> None: ...
    def estimateMemoryUsage(self) -> int: ...
    def getMaxPressure(self) -> float: ...
    def getMaxTemperature(self) -> float: ...
    def getMinPressure(self) -> float: ...
    def getMinTemperature(self) -> float: ...
    def getNumPressurePoints(self) -> int: ...
    def getNumTemperaturePoints(self) -> int: ...
    def getPressures(self) -> typing.MutableSequence[float]: ...
    def getProperty(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> float: ...
    def getTemperatures(self) -> typing.MutableSequence[float]: ...
    def getTotalGridPoints(self) -> int: ...
    def interpolate(self, double: float, double2: float) -> 'ThermodynamicCoupling.ThermoProperties': ...
    def isBuilt(self) -> bool: ...

class FlowRegimeDetector(java.io.Serializable):
    def __init__(self): ...
    def detectFlowRegime(self, pipeSection: 'PipeSection') -> 'PipeSection.FlowRegime': ...
    def getDetectionMethod(self) -> 'FlowRegimeDetector.DetectionMethod': ...
    def getFlowRegimeMap(self, pipeSection: 'PipeSection', double: float, double2: float, int: int) -> typing.MutableSequence[typing.MutableSequence['PipeSection.FlowRegime']]: ...
    def isUseMinimumSlipCriterion(self) -> bool: ...
    def setDetectionMethod(self, detectionMethod: 'FlowRegimeDetector.DetectionMethod') -> None: ...
    def setUseMinimumSlipCriterion(self, boolean: bool) -> None: ...
    class DetectionMethod(java.lang.Enum['FlowRegimeDetector.DetectionMethod']):
        MECHANISTIC: typing.ClassVar['FlowRegimeDetector.DetectionMethod'] = ...
        MINIMUM_SLIP: typing.ClassVar['FlowRegimeDetector.DetectionMethod'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FlowRegimeDetector.DetectionMethod': ...
        @staticmethod
        def values() -> typing.MutableSequence['FlowRegimeDetector.DetectionMethod']: ...

class LiquidAccumulationTracker(java.io.Serializable):
    def __init__(self): ...
    def calculateDrainageRate(self, accumulationZone: 'LiquidAccumulationTracker.AccumulationZone', pipeSectionArray: typing.Union[typing.List['PipeSection'], jpype.JArray], double: float) -> float: ...
    def checkForSlugRelease(self, accumulationZone: 'LiquidAccumulationTracker.AccumulationZone', pipeSectionArray: typing.Union[typing.List['PipeSection'], jpype.JArray]) -> 'LiquidAccumulationTracker.SlugCharacteristics': ...
    def getAccumulationZones(self) -> java.util.List['LiquidAccumulationTracker.AccumulationZone']: ...
    def getCriticalHoldup(self) -> float: ...
    def getOverflowingZones(self) -> java.util.List['LiquidAccumulationTracker.AccumulationZone']: ...
    def getTotalAccumulatedVolume(self) -> float: ...
    def identifyAccumulationZones(self, pipeSectionArray: typing.Union[typing.List['PipeSection'], jpype.JArray]) -> None: ...
    def setCriticalHoldup(self, double: float) -> None: ...
    def setDrainageCoefficient(self, double: float) -> None: ...
    def updateAccumulation(self, pipeSectionArray: typing.Union[typing.List['PipeSection'], jpype.JArray], double: float) -> None: ...
    class AccumulationZone(java.io.Serializable):
        startPosition: float = ...
        endPosition: float = ...
        liquidVolume: float = ...
        maxVolume: float = ...
        liquidLevel: float = ...
        isActive: bool = ...
        isOverflowing: bool = ...
        netInflowRate: float = ...
        outflowRate: float = ...
        timeSinceSlug: float = ...
        sectionIndices: java.util.List = ...
        def __init__(self): ...
    class SlugCharacteristics(java.io.Serializable):
        frontPosition: float = ...
        tailPosition: float = ...
        length: float = ...
        holdup: float = ...
        velocity: float = ...
        volume: float = ...
        isTerrainInduced: bool = ...
        def __init__(self): ...
        def toString(self) -> java.lang.String: ...

class PipeSection(java.lang.Cloneable, java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float, double2: float, double3: float, double4: float): ...
    def clone(self) -> 'PipeSection': ...
    def getAccumulatedLiquidVolume(self) -> float: ...
    def getArea(self) -> float: ...
    def getConservativeVariables(self) -> typing.MutableSequence[float]: ...
    def getDiameter(self) -> float: ...
    def getEffectiveLiquidHoldup(self) -> float: ...
    def getEffectiveMixtureDensity(self) -> float: ...
    def getElevation(self) -> float: ...
    def getFlowRegime(self) -> 'PipeSection.FlowRegime': ...
    def getFrictionPressureGradient(self) -> float: ...
    def getGasDensity(self) -> float: ...
    def getGasEnthalpy(self) -> float: ...
    def getGasHoldup(self) -> float: ...
    def getGasSoundSpeed(self) -> float: ...
    def getGasVelocity(self) -> float: ...
    def getGasViscosity(self) -> float: ...
    def getGravityPressureGradient(self) -> float: ...
    def getInclination(self) -> float: ...
    def getLength(self) -> float: ...
    def getLiquidDensity(self) -> float: ...
    def getLiquidEnthalpy(self) -> float: ...
    def getLiquidHoldup(self) -> float: ...
    def getLiquidLevel(self) -> float: ...
    def getLiquidSoundSpeed(self) -> float: ...
    def getLiquidVelocity(self) -> float: ...
    def getLiquidViscosity(self) -> float: ...
    def getMassTransferRate(self) -> float: ...
    def getMixtureDensity(self) -> float: ...
    def getMixtureHeatCapacity(self) -> float: ...
    def getMixtureVelocity(self) -> float: ...
    def getPosition(self) -> float: ...
    def getPressure(self) -> float: ...
    def getRoughness(self) -> float: ...
    def getSlugHoldup(self) -> float: ...
    def getSuperficialGasVelocity(self) -> float: ...
    def getSuperficialLiquidVelocity(self) -> float: ...
    def getSurfaceTension(self) -> float: ...
    def getTemperature(self) -> float: ...
    def getWallisSoundSpeed(self) -> float: ...
    def isHighPoint(self) -> bool: ...
    def isInSlugBody(self) -> bool: ...
    def isInSlugBubble(self) -> bool: ...
    def isLowPoint(self) -> bool: ...
    def setAccumulatedLiquidVolume(self, double: float) -> None: ...
    def setDiameter(self, double: float) -> None: ...
    def setElevation(self, double: float) -> None: ...
    def setFlowRegime(self, flowRegime: 'PipeSection.FlowRegime') -> None: ...
    def setFrictionPressureGradient(self, double: float) -> None: ...
    def setFromConservativeVariables(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setGasDensity(self, double: float) -> None: ...
    def setGasEnthalpy(self, double: float) -> None: ...
    def setGasHoldup(self, double: float) -> None: ...
    def setGasSoundSpeed(self, double: float) -> None: ...
    def setGasVelocity(self, double: float) -> None: ...
    def setGasViscosity(self, double: float) -> None: ...
    def setGravityPressureGradient(self, double: float) -> None: ...
    def setHighPoint(self, boolean: bool) -> None: ...
    def setInSlugBody(self, boolean: bool) -> None: ...
    def setInSlugBubble(self, boolean: bool) -> None: ...
    def setInclination(self, double: float) -> None: ...
    def setLength(self, double: float) -> None: ...
    def setLiquidDensity(self, double: float) -> None: ...
    def setLiquidEnthalpy(self, double: float) -> None: ...
    def setLiquidHoldup(self, double: float) -> None: ...
    def setLiquidSoundSpeed(self, double: float) -> None: ...
    def setLiquidVelocity(self, double: float) -> None: ...
    def setLiquidViscosity(self, double: float) -> None: ...
    def setLowPoint(self, boolean: bool) -> None: ...
    def setMassTransferRate(self, double: float) -> None: ...
    def setMixtureHeatCapacity(self, double: float) -> None: ...
    def setPosition(self, double: float) -> None: ...
    def setPressure(self, double: float) -> None: ...
    def setRoughness(self, double: float) -> None: ...
    def setSlugHoldup(self, double: float) -> None: ...
    def setSurfaceTension(self, double: float) -> None: ...
    def setTemperature(self, double: float) -> None: ...
    def updateDerivedQuantities(self) -> None: ...
    class FlowRegime(java.lang.Enum['PipeSection.FlowRegime']):
        STRATIFIED_SMOOTH: typing.ClassVar['PipeSection.FlowRegime'] = ...
        STRATIFIED_WAVY: typing.ClassVar['PipeSection.FlowRegime'] = ...
        SLUG: typing.ClassVar['PipeSection.FlowRegime'] = ...
        ANNULAR: typing.ClassVar['PipeSection.FlowRegime'] = ...
        DISPERSED_BUBBLE: typing.ClassVar['PipeSection.FlowRegime'] = ...
        BUBBLE: typing.ClassVar['PipeSection.FlowRegime'] = ...
        CHURN: typing.ClassVar['PipeSection.FlowRegime'] = ...
        MIST: typing.ClassVar['PipeSection.FlowRegime'] = ...
        SINGLE_PHASE_GAS: typing.ClassVar['PipeSection.FlowRegime'] = ...
        SINGLE_PHASE_LIQUID: typing.ClassVar['PipeSection.FlowRegime'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PipeSection.FlowRegime': ...
        @staticmethod
        def values() -> typing.MutableSequence['PipeSection.FlowRegime']: ...

class SlugTracker(java.io.Serializable):
    def __init__(self): ...
    def advanceSlugs(self, pipeSectionArray: typing.Union[typing.List[PipeSection], jpype.JArray], double: float) -> None: ...
    def generateInletSlug(self, pipeSection: PipeSection, double: float) -> 'SlugTracker.SlugUnit': ...
    def getAverageSlugLength(self) -> float: ...
    def getMassConservationError(self) -> float: ...
    def getMaxSlugLength(self) -> float: ...
    def getSlugBodyHoldup(self) -> float: ...
    def getSlugCount(self) -> int: ...
    def getSlugFrequency(self) -> float: ...
    def getSlugs(self) -> java.util.List['SlugTracker.SlugUnit']: ...
    def getStatisticsString(self) -> java.lang.String: ...
    def getTotalMassBorrowedFromEulerian(self) -> float: ...
    def getTotalMassReturnedToEulerian(self) -> float: ...
    def getTotalSlugsGenerated(self) -> int: ...
    def getTotalSlugsMerged(self) -> int: ...
    def initializeTerrainSlug(self, slugCharacteristics: LiquidAccumulationTracker.SlugCharacteristics, pipeSectionArray: typing.Union[typing.List[PipeSection], jpype.JArray]) -> 'SlugTracker.SlugUnit': ...
    def reset(self) -> None: ...
    def setFilmHoldup(self, double: float) -> None: ...
    def setMinimumSlugLength(self, double: float) -> None: ...
    def setReferenceVelocity(self, double: float) -> None: ...
    def setSlugBodyHoldup(self, double: float) -> None: ...
    class SlugUnit(java.io.Serializable):
        id: int = ...
        frontPosition: float = ...
        tailPosition: float = ...
        slugBodyLength: float = ...
        bubbleLength: float = ...
        frontVelocity: float = ...
        tailVelocity: float = ...
        bodyHoldup: float = ...
        filmHoldup: float = ...
        liquidVolume: float = ...
        isGrowing: bool = ...
        isDecaying: bool = ...
        isTerrainInduced: bool = ...
        age: float = ...
        localInclination: float = ...
        borrowedLiquidMass: float = ...
        borrowedFromSections: typing.MutableSequence[int] = ...
        def __init__(self): ...
        def getTotalLength(self) -> float: ...
        def toString(self) -> java.lang.String: ...

class ThermodynamicCoupling(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcMassTransferRate(self, twoFluidSection: 'TwoFluidSection', double: float) -> float: ...
    def calcMixtureSoundSpeed(self, twoFluidSection: 'TwoFluidSection') -> float: ...
    def flashPH(self, double: float, double2: float) -> 'ThermodynamicCoupling.ThermoProperties': ...
    def flashPT(self, double: float, double2: float) -> 'ThermodynamicCoupling.ThermoProperties': ...
    def getFlashTable(self) -> FlashTable: ...
    def getFlashTolerance(self) -> float: ...
    def getMaxFlashIterations(self) -> int: ...
    def getReferenceFluid(self) -> jneqsim.thermo.system.SystemInterface: ...
    def isUsingFlashTable(self) -> bool: ...
    def setFlashTable(self, flashTable: FlashTable) -> None: ...
    def setFlashTolerance(self, double: float) -> None: ...
    def setMaxFlashIterations(self, int: int) -> None: ...
    def setPressureRange(self, double: float, double2: float) -> None: ...
    def setReferenceFluid(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    def setTemperatureRange(self, double: float, double2: float) -> None: ...
    def updateAllSections(self, twoFluidSectionArray: typing.Union[typing.List['TwoFluidSection'], jpype.JArray]) -> None: ...
    def updateSectionProperties(self, twoFluidSection: 'TwoFluidSection') -> None: ...
    class ThermoProperties(java.io.Serializable):
        gasVaporFraction: float = ...
        liquidFraction: float = ...
        gasDensity: float = ...
        liquidDensity: float = ...
        gasViscosity: float = ...
        liquidViscosity: float = ...
        gasEnthalpy: float = ...
        liquidEnthalpy: float = ...
        gasSoundSpeed: float = ...
        liquidSoundSpeed: float = ...
        surfaceTension: float = ...
        gasMolarMass: float = ...
        liquidMolarMass: float = ...
        gasCompressibility: float = ...
        liquidCompressibility: float = ...
        gasCp: float = ...
        liquidCp: float = ...
        gasThermalConductivity: float = ...
        liquidThermalConductivity: float = ...
        converged: bool = ...
        errorMessage: java.lang.String = ...
        def __init__(self): ...

class ThreeFluidConservationEquations(java.io.Serializable):
    def __init__(self): ...
    def calcRHS(self, threeFluidSection: 'ThreeFluidSection', double: float, threeFluidSection2: 'ThreeFluidSection', threeFluidSection3: 'ThreeFluidSection') -> 'ThreeFluidConservationEquations.ThreeFluidRHS': ...
    def getHeatTransferCoefficient(self) -> float: ...
    def getStateVector(self, threeFluidSection: 'ThreeFluidSection') -> typing.MutableSequence[float]: ...
    def getSurfaceTemperature(self) -> float: ...
    def isEnableHeatTransfer(self) -> bool: ...
    def setEnableHeatTransfer(self, boolean: bool) -> None: ...
    def setHeatTransferCoefficient(self, double: float) -> None: ...
    def setStateVector(self, threeFluidSection: 'ThreeFluidSection', doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setSurfaceTemperature(self, double: float) -> None: ...
    class ThreeFluidRHS(java.io.Serializable):
        gasMass: float = ...
        oilMass: float = ...
        waterMass: float = ...
        gasMomentum: float = ...
        oilMomentum: float = ...
        waterMomentum: float = ...
        energy: float = ...
        gasWallShear: float = ...
        oilWallShear: float = ...
        waterWallShear: float = ...
        gasOilInterfacialShear: float = ...
        oilWaterInterfacialShear: float = ...
        def __init__(self): ...

class TransientPipe(jneqsim.process.equipment.TwoPortEquipment, jneqsim.process.equipment.pipeline.PipeLineInterface):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getAccumulationTracker(self) -> LiquidAccumulationTracker: ...
    def getAmbientTemperature(self) -> float: ...
    def getCalculationIdentifier(self) -> java.util.UUID: ...
    def getDiameter(self) -> float: ...
    def getEnergyResidual(self) -> float: ...
    def getGasVelocityProfile(self) -> typing.MutableSequence[float]: ...
    def getInletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getJouleThomsonCoeff(self) -> float: ...
    def getLength(self) -> float: ...
    def getLiquidHoldupProfile(self) -> typing.MutableSequence[float]: ...
    def getLiquidVelocityProfile(self) -> typing.MutableSequence[float]: ...
    def getMassResidual(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getOutletMassFlow(self) -> float: ...
    def getOutletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOverallHeatTransferCoeff(self) -> float: ...
    def getPipe(self) -> jneqsim.fluidmechanics.flowsystem.FlowSystemInterface: ...
    def getPipeElasticity(self) -> float: ...
    def getPressureHistory(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getPressureProfile(self) -> typing.MutableSequence[float]: ...
    def getRoughness(self) -> float: ...
    def getSections(self) -> typing.MutableSequence[PipeSection]: ...
    def getSimulationTime(self) -> float: ...
    def getSlugTracker(self) -> SlugTracker: ...
    def getTemperatureProfile(self) -> typing.MutableSequence[float]: ...
    def getTotalTimeSteps(self) -> int: ...
    def getWallThickness(self) -> float: ...
    def initializePipe(self) -> None: ...
    def isConverged(self) -> bool: ...
    def isIncludeHeatTransfer(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setAmbientTemperature(self, double: float) -> None: ...
    def setCalculationIdentifier(self, uUID: java.util.UUID) -> None: ...
    def setCflNumber(self, double: float) -> None: ...
    def setDiameter(self, double: float) -> None: ...
    def setElevationProfile(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setHeightProfile(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setInclinationProfile(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setIncludeHeatTransfer(self, boolean: bool) -> None: ...
    def setInitialFlowPattern(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInletBoundaryCondition(self, boundaryCondition: 'TransientPipe.BoundaryCondition') -> None: ...
    def setInletMassFlow(self, double: float) -> None: ...
    def setInletPressure(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setLegPositions(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setLength(self, double: float) -> None: ...
    def setMaxSimulationTime(self, double: float) -> None: ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setNumberOfLegs(self, int: int) -> None: ...
    def setNumberOfNodesInLeg(self, int: int) -> None: ...
    def setNumberOfSections(self, int: int) -> None: ...
    def setOuterTemperatures(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setOutletBoundaryCondition(self, boundaryCondition: 'TransientPipe.BoundaryCondition') -> None: ...
    def setOutletMassFlow(self, double: float) -> None: ...
    def setOutletPressure(self, double: float) -> None: ...
    def setOutletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setOutputFileName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setOverallHeatTransferCoeff(self, double: float) -> None: ...
    def setPipeDiameters(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setPipeWallRoughness(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setRoughness(self, double: float) -> None: ...
    def setThermodynamicUpdateInterval(self, int: int) -> None: ...
    def setUpdateThermodynamics(self, boolean: bool) -> None: ...
    def setinletPressureValue(self, double: float) -> None: ...
    def setoutletPressureValue(self, double: float) -> None: ...
    class BoundaryCondition(java.lang.Enum['TransientPipe.BoundaryCondition']):
        CONSTANT_PRESSURE: typing.ClassVar['TransientPipe.BoundaryCondition'] = ...
        CONSTANT_FLOW: typing.ClassVar['TransientPipe.BoundaryCondition'] = ...
        CONSTANT_VELOCITY: typing.ClassVar['TransientPipe.BoundaryCondition'] = ...
        CLOSED: typing.ClassVar['TransientPipe.BoundaryCondition'] = ...
        TRANSIENT_PRESSURE: typing.ClassVar['TransientPipe.BoundaryCondition'] = ...
        TRANSIENT_FLOW: typing.ClassVar['TransientPipe.BoundaryCondition'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TransientPipe.BoundaryCondition': ...
        @staticmethod
        def values() -> typing.MutableSequence['TransientPipe.BoundaryCondition']: ...

class TwoFluidConservationEquations(java.io.Serializable):
    NUM_EQUATIONS: typing.ClassVar[int] = ...
    IDX_GAS_MASS: typing.ClassVar[int] = ...
    IDX_OIL_MASS: typing.ClassVar[int] = ...
    IDX_WATER_MASS: typing.ClassVar[int] = ...
    IDX_GAS_MOMENTUM: typing.ClassVar[int] = ...
    IDX_OIL_MOMENTUM: typing.ClassVar[int] = ...
    IDX_WATER_MOMENTUM: typing.ClassVar[int] = ...
    IDX_ENERGY: typing.ClassVar[int] = ...
    IDX_LIQUID_MOMENTUM: typing.ClassVar[int] = ...
    def __init__(self): ...
    def applyPressureGradient(self, twoFluidSectionArray: typing.Union[typing.List['TwoFluidSection'], jpype.JArray], doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], double2: float) -> None: ...
    def applyState(self, twoFluidSectionArray: typing.Union[typing.List['TwoFluidSection'], jpype.JArray], doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    def calcRHS(self, twoFluidSectionArray: typing.Union[typing.List['TwoFluidSection'], jpype.JArray], double: float) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def extractState(self, twoFluidSectionArray: typing.Union[typing.List['TwoFluidSection'], jpype.JArray]) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getFlowRegimeDetector(self) -> FlowRegimeDetector: ...
    def getFluxCalculator(self) -> jneqsim.process.equipment.pipeline.twophasepipe.numerics.AUSMPlusFluxCalculator: ...
    def getHeatTransferCoefficient(self) -> float: ...
    def getInterfacialFriction(self) -> jneqsim.process.equipment.pipeline.twophasepipe.closure.InterfacialFriction: ...
    def getMassTransferCoefficient(self) -> float: ...
    def getReconstructor(self) -> jneqsim.process.equipment.pipeline.twophasepipe.numerics.MUSCLReconstructor: ...
    def getSurfaceTemperature(self) -> float: ...
    def getWallFriction(self) -> jneqsim.process.equipment.pipeline.twophasepipe.closure.WallFriction: ...
    def isEnableWaterOilSlip(self) -> bool: ...
    def isHeatTransferEnabled(self) -> bool: ...
    def isIncludeEnergyEquation(self) -> bool: ...
    def isIncludeMassTransfer(self) -> bool: ...
    def setEnableHeatTransfer(self, boolean: bool) -> None: ...
    def setEnableWaterOilSlip(self, boolean: bool) -> None: ...
    def setHeatTransferCoefficient(self, double: float) -> None: ...
    def setIncludeEnergyEquation(self, boolean: bool) -> None: ...
    def setIncludeMassTransfer(self, boolean: bool) -> None: ...
    def setMassTransferCoefficient(self, double: float) -> None: ...
    def setSurfaceTemperature(self, double: float) -> None: ...

class TwoFluidSection(PipeSection):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float, double2: float, double3: float, double4: float): ...
    def calcGravityForces(self) -> typing.MutableSequence[float]: ...
    def calcOilWaterInterfacialShear(self) -> float: ...
    def clone(self) -> 'TwoFluidSection': ...
    def extractPrimitiveVariables(self) -> None: ...
    @staticmethod
    def fromPipeSection(pipeSection: PipeSection) -> 'TwoFluidSection': ...
    def getEnergyPerLength(self) -> float: ...
    def getEnergySource(self) -> float: ...
    def getGasHydraulicDiameter(self) -> float: ...
    def getGasMassPerLength(self) -> float: ...
    def getGasMassSource(self) -> float: ...
    def getGasMomentumPerLength(self) -> float: ...
    def getGasMomentumSource(self) -> float: ...
    def getGasWallShear(self) -> float: ...
    def getGasWettedPerimeter(self) -> float: ...
    def getInterfacialShear(self) -> float: ...
    def getInterfacialWidth(self) -> float: ...
    def getLiquidHoldup(self) -> float: ...
    def getLiquidHydraulicDiameter(self) -> float: ...
    def getLiquidMassPerLength(self) -> float: ...
    def getLiquidMassSource(self) -> float: ...
    def getLiquidMomentumPerLength(self) -> float: ...
    def getLiquidMomentumSource(self) -> float: ...
    def getLiquidWallShear(self) -> float: ...
    def getLiquidWettedPerimeter(self) -> float: ...
    def getOilDensity(self) -> float: ...
    def getOilFractionInLiquid(self) -> float: ...
    def getOilHoldup(self) -> float: ...
    def getOilMassPerLength(self) -> float: ...
    def getOilMomentumPerLength(self) -> float: ...
    def getOilVelocity(self) -> float: ...
    def getOilViscosity(self) -> float: ...
    def getStateVector(self) -> typing.MutableSequence[float]: ...
    def getStratifiedLiquidLevel(self) -> float: ...
    def getWaterCut(self) -> float: ...
    def getWaterDensity(self) -> float: ...
    def getWaterHoldup(self) -> float: ...
    def getWaterMassPerLength(self) -> float: ...
    def getWaterMomentumPerLength(self) -> float: ...
    def getWaterVelocity(self) -> float: ...
    def getWaterViscosity(self) -> float: ...
    def setEnergyPerLength(self, double: float) -> None: ...
    def setEnergySource(self, double: float) -> None: ...
    def setGasHydraulicDiameter(self, double: float) -> None: ...
    def setGasMassPerLength(self, double: float) -> None: ...
    def setGasMassSource(self, double: float) -> None: ...
    def setGasMomentumPerLength(self, double: float) -> None: ...
    def setGasMomentumSource(self, double: float) -> None: ...
    def setGasWallShear(self, double: float) -> None: ...
    def setGasWettedPerimeter(self, double: float) -> None: ...
    def setInterfacialShear(self, double: float) -> None: ...
    def setInterfacialWidth(self, double: float) -> None: ...
    def setLiquidHoldup(self, double: float) -> None: ...
    def setLiquidHydraulicDiameter(self, double: float) -> None: ...
    def setLiquidMassPerLength(self, double: float) -> None: ...
    def setLiquidMassSource(self, double: float) -> None: ...
    def setLiquidMomentumPerLength(self, double: float) -> None: ...
    def setLiquidMomentumSource(self, double: float) -> None: ...
    def setLiquidWallShear(self, double: float) -> None: ...
    def setLiquidWettedPerimeter(self, double: float) -> None: ...
    def setOilDensity(self, double: float) -> None: ...
    def setOilFractionInLiquid(self, double: float) -> None: ...
    def setOilHoldup(self, double: float) -> None: ...
    def setOilMassPerLength(self, double: float) -> None: ...
    def setOilMomentumPerLength(self, double: float) -> None: ...
    def setOilVelocity(self, double: float) -> None: ...
    def setOilViscosity(self, double: float) -> None: ...
    def setStateVector(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setStratifiedLiquidLevel(self, double: float) -> None: ...
    def setWaterCut(self, double: float) -> None: ...
    def setWaterDensity(self, double: float) -> None: ...
    def setWaterHoldup(self, double: float) -> None: ...
    def setWaterMassPerLength(self, double: float) -> None: ...
    def setWaterMomentumPerLength(self, double: float) -> None: ...
    def setWaterVelocity(self, double: float) -> None: ...
    def setWaterViscosity(self, double: float) -> None: ...
    def updateConservativeVariables(self) -> None: ...
    def updateStratifiedGeometry(self) -> None: ...
    def updateThreePhaseProperties(self) -> None: ...
    def updateWaterOilConservativeVariables(self) -> None: ...
    def updateWaterOilHoldups(self) -> None: ...

class ThreeFluidSection(TwoFluidSection, java.lang.Cloneable, java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float, double2: float, double3: float): ...
    @typing.overload
    def __init__(self, double: float, double2: float, double3: float, double4: float): ...
    def clone(self) -> 'ThreeFluidSection': ...
    def extractPrimitiveVariables(self) -> None: ...
    def getGasOilInterfacialWidth(self) -> float: ...
    def getGasOilSurfaceTension(self) -> float: ...
    def getGasWaterSurfaceTension(self) -> float: ...
    def getMixtureLiquidDensity(self) -> float: ...
    def getMixtureLiquidVelocity(self) -> float: ...
    def getMixtureLiquidViscosity(self) -> float: ...
    def getOilArea(self) -> float: ...
    def getOilDensity(self) -> float: ...
    def getOilEnthalpy(self) -> float: ...
    def getOilEvaporationRate(self) -> float: ...
    def getOilHoldup(self) -> float: ...
    def getOilLevel(self) -> float: ...
    def getOilMassPerLength(self) -> float: ...
    def getOilMomentumPerLength(self) -> float: ...
    def getOilVelocity(self) -> float: ...
    def getOilViscosity(self) -> float: ...
    def getOilWaterInterfacialWidth(self) -> float: ...
    def getOilWaterSurfaceTension(self) -> float: ...
    def getOilWettedPerimeter(self) -> float: ...
    def getTotalLiquidHoldup(self) -> float: ...
    def getWaterArea(self) -> float: ...
    def getWaterCut(self) -> float: ...
    def getWaterDensity(self) -> float: ...
    def getWaterEnthalpy(self) -> float: ...
    def getWaterEvaporationRate(self) -> float: ...
    def getWaterHoldup(self) -> float: ...
    def getWaterLevel(self) -> float: ...
    def getWaterMassPerLength(self) -> float: ...
    def getWaterMomentumPerLength(self) -> float: ...
    def getWaterVelocity(self) -> float: ...
    def getWaterViscosity(self) -> float: ...
    def getWaterWettedPerimeter(self) -> float: ...
    def setGasOilSurfaceTension(self, double: float) -> None: ...
    def setGasWaterSurfaceTension(self, double: float) -> None: ...
    def setHoldups(self, double: float, double2: float, double3: float) -> None: ...
    def setOilDensity(self, double: float) -> None: ...
    def setOilEnthalpy(self, double: float) -> None: ...
    def setOilEvaporationRate(self, double: float) -> None: ...
    def setOilHoldup(self, double: float) -> None: ...
    def setOilMassPerLength(self, double: float) -> None: ...
    def setOilMomentumPerLength(self, double: float) -> None: ...
    def setOilVelocity(self, double: float) -> None: ...
    def setOilViscosity(self, double: float) -> None: ...
    def setOilWaterSurfaceTension(self, double: float) -> None: ...
    def setWaterCut(self, double: float) -> None: ...
    def setWaterDensity(self, double: float) -> None: ...
    def setWaterEnthalpy(self, double: float) -> None: ...
    def setWaterEvaporationRate(self, double: float) -> None: ...
    def setWaterHoldup(self, double: float) -> None: ...
    def setWaterMassPerLength(self, double: float) -> None: ...
    def setWaterMomentumPerLength(self, double: float) -> None: ...
    def setWaterVelocity(self, double: float) -> None: ...
    def setWaterViscosity(self, double: float) -> None: ...
    def updateConservativeVariables(self) -> None: ...
    def updateThreeLayerGeometry(self) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.pipeline.twophasepipe")``.

    DriftFluxModel: typing.Type[DriftFluxModel]
    EntrainmentDeposition: typing.Type[EntrainmentDeposition]
    FlashTable: typing.Type[FlashTable]
    FlowRegimeDetector: typing.Type[FlowRegimeDetector]
    LiquidAccumulationTracker: typing.Type[LiquidAccumulationTracker]
    PipeSection: typing.Type[PipeSection]
    SlugTracker: typing.Type[SlugTracker]
    ThermodynamicCoupling: typing.Type[ThermodynamicCoupling]
    ThreeFluidConservationEquations: typing.Type[ThreeFluidConservationEquations]
    ThreeFluidSection: typing.Type[ThreeFluidSection]
    TransientPipe: typing.Type[TransientPipe]
    TwoFluidConservationEquations: typing.Type[TwoFluidConservationEquations]
    TwoFluidSection: typing.Type[TwoFluidSection]
    closure: jneqsim.process.equipment.pipeline.twophasepipe.closure.__module_protocol__
    numerics: jneqsim.process.equipment.pipeline.twophasepipe.numerics.__module_protocol__
