import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.equipment.reservoir
import jneqsim.process.fielddevelopment.concept
import jneqsim.process.fielddevelopment.economics
import jneqsim.process.fielddevelopment.evaluation
import jneqsim.process.fielddevelopment.facility
import jneqsim.process.fielddevelopment.screening
import jneqsim.process.fielddevelopment.subsea
import jneqsim.process.fielddevelopment.tieback
import jneqsim.process.mechanicaldesign
import jneqsim.process.processmodel
import jneqsim.thermo.system
import typing

class FieldDevelopmentWorkflow(java.io.Serializable):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        fieldConcept: jneqsim.process.fielddevelopment.concept.FieldConcept,
    ): ...
    def addHostFacility(
        self, hostFacility: jneqsim.process.fielddevelopment.tieback.HostFacility
    ) -> "FieldDevelopmentWorkflow": ...
    def addWell(
        self, wellSystem: jneqsim.process.equipment.reservoir.WellSystem
    ) -> "FieldDevelopmentWorkflow": ...
    def configureSubseaFromConcept(self) -> "FieldDevelopmentWorkflow": ...
    @staticmethod
    def generateComparisonReport(
        list: java.util.List["FieldDevelopmentWorkflow"],
    ) -> java.lang.String: ...
    def getFidelityLevel(self) -> "FieldDevelopmentWorkflow.FidelityLevel": ...
    def getLastResult(self) -> "WorkflowResult": ...
    def getProjectName(self) -> java.lang.String: ...
    def getStudyPhase(self) -> "FieldDevelopmentWorkflow.StudyPhase": ...
    @staticmethod
    def quickGasTieback(
        string: typing.Union[java.lang.String, str],
        double: float,
        double2: float,
        int: int,
        double3: float,
        string2: typing.Union[java.lang.String, str],
    ) -> "FieldDevelopmentWorkflow": ...
    @staticmethod
    def quickOilDevelopment(
        string: typing.Union[java.lang.String, str],
        double: float,
        int: int,
        double2: float,
        string2: typing.Union[java.lang.String, str],
    ) -> "FieldDevelopmentWorkflow": ...
    def run(self) -> "WorkflowResult": ...
    def setCalculateEmissions(self, boolean: bool) -> "FieldDevelopmentWorkflow": ...
    def setConcept(
        self, fieldConcept: jneqsim.process.fielddevelopment.concept.FieldConcept
    ) -> "FieldDevelopmentWorkflow": ...
    def setCountryCode(
        self, string: typing.Union[java.lang.String, str]
    ) -> "FieldDevelopmentWorkflow": ...
    def setDesignStandard(
        self, string: typing.Union[java.lang.String, str]
    ) -> "FieldDevelopmentWorkflow": ...
    def setDiscountRate(self, double: float) -> "FieldDevelopmentWorkflow": ...
    def setFacilityConfig(
        self, facilityConfig: jneqsim.process.fielddevelopment.facility.FacilityConfig
    ) -> "FieldDevelopmentWorkflow": ...
    def setFidelityLevel(
        self, fidelityLevel: "FieldDevelopmentWorkflow.FidelityLevel"
    ) -> "FieldDevelopmentWorkflow": ...
    def setFluid(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> "FieldDevelopmentWorkflow": ...
    def setGridEmissionFactor(self, double: float) -> "FieldDevelopmentWorkflow": ...
    def setMonteCarloIterations(self, int: int) -> "FieldDevelopmentWorkflow": ...
    def setPowerSupplyType(
        self, string: typing.Union[java.lang.String, str]
    ) -> "FieldDevelopmentWorkflow": ...
    def setPrices(
        self, double: float, double2: float, double3: float
    ) -> "FieldDevelopmentWorkflow": ...
    def setProcessSystem(
        self, processSystem: jneqsim.process.processmodel.ProcessSystem
    ) -> "FieldDevelopmentWorkflow": ...
    def setProductionTiming(
        self, int: int, int2: int, double: float, double2: float
    ) -> "FieldDevelopmentWorkflow": ...
    def setReservoir(
        self, simpleReservoir: jneqsim.process.equipment.reservoir.SimpleReservoir
    ) -> "FieldDevelopmentWorkflow": ...
    def setRunMechanicalDesign(self, boolean: bool) -> "FieldDevelopmentWorkflow": ...
    def setRunSubseaAnalysis(self, boolean: bool) -> "FieldDevelopmentWorkflow": ...
    def setStudyPhase(
        self, studyPhase: "FieldDevelopmentWorkflow.StudyPhase"
    ) -> "FieldDevelopmentWorkflow": ...
    def setSubseaArchitecture(
        self,
        subseaArchitecture: jneqsim.process.fielddevelopment.subsea.SubseaProductionSystem.SubseaArchitecture,
    ) -> "FieldDevelopmentWorkflow": ...
    def setSubseaSystem(
        self,
        subseaProductionSystem: jneqsim.process.fielddevelopment.subsea.SubseaProductionSystem,
    ) -> "FieldDevelopmentWorkflow": ...
    def setTiebackAnalyzer(
        self, tiebackAnalyzer: jneqsim.process.fielddevelopment.tieback.TiebackAnalyzer
    ) -> "FieldDevelopmentWorkflow": ...
    def setTiebackDistanceKm(self, double: float) -> "FieldDevelopmentWorkflow": ...
    def setWaterDepthM(self, double: float) -> "FieldDevelopmentWorkflow": ...

    class FidelityLevel(java.lang.Enum["FieldDevelopmentWorkflow.FidelityLevel"]):
        SCREENING: typing.ClassVar["FieldDevelopmentWorkflow.FidelityLevel"] = ...
        CONCEPTUAL: typing.ClassVar["FieldDevelopmentWorkflow.FidelityLevel"] = ...
        DETAILED: typing.ClassVar["FieldDevelopmentWorkflow.FidelityLevel"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "FieldDevelopmentWorkflow.FidelityLevel": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["FieldDevelopmentWorkflow.FidelityLevel"]
        ): ...

    class StudyPhase(java.lang.Enum["FieldDevelopmentWorkflow.StudyPhase"]):
        DISCOVERY: typing.ClassVar["FieldDevelopmentWorkflow.StudyPhase"] = ...
        FEASIBILITY: typing.ClassVar["FieldDevelopmentWorkflow.StudyPhase"] = ...
        CONCEPT_SELECT: typing.ClassVar["FieldDevelopmentWorkflow.StudyPhase"] = ...
        FEED: typing.ClassVar["FieldDevelopmentWorkflow.StudyPhase"] = ...
        OPERATIONS: typing.ClassVar["FieldDevelopmentWorkflow.StudyPhase"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "FieldDevelopmentWorkflow.StudyPhase": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["FieldDevelopmentWorkflow.StudyPhase"]
        ): ...

class WorkflowResult(java.io.Serializable):
    projectName: java.lang.String = ...
    fidelityLevel: FieldDevelopmentWorkflow.FidelityLevel = ...
    flowAssuranceResult: (
        jneqsim.process.fielddevelopment.screening.FlowAssuranceReport
    ) = ...
    economicsReport: (
        jneqsim.process.fielddevelopment.screening.EconomicsEstimator.EconomicsReport
    ) = ...
    gasProfile: java.util.Map = ...
    oilProfile: java.util.Map = ...
    waterProfile: java.util.Map = ...
    cashFlowResult: (
        jneqsim.process.fielddevelopment.economics.CashFlowEngine.CashFlowResult
    ) = ...
    npv: float = ...
    npvP10: float = ...
    npvP50: float = ...
    npvP90: float = ...
    irr: float = ...
    paybackYears: float = ...
    breakevenGasPrice: float = ...
    breakevenOilPrice: float = ...
    monteCarloResult: (
        jneqsim.process.fielddevelopment.economics.SensitivityAnalyzer.MonteCarloResult
    ) = ...
    tornadoResult: (
        jneqsim.process.fielddevelopment.economics.SensitivityAnalyzer.TornadoResult
    ) = ...
    conceptKPIs: jneqsim.process.fielddevelopment.evaluation.ConceptKPIs = ...
    mechanicalDesign: jneqsim.process.mechanicaldesign.SystemMechanicalDesign = ...
    totalEquipmentWeightTonnes: float = ...
    totalFootprintM2: float = ...
    totalPowerMW: float = ...
    powerBreakdownMW: java.util.Map = ...
    annualCO2eKtonnes: float = ...
    co2IntensityKgPerBoe: float = ...
    emissionBreakdown: java.util.Map = ...
    powerSupplyType: java.lang.String = ...
    gridEmissionFactor: float = ...
    subseaSystemResult: (
        jneqsim.process.fielddevelopment.subsea.SubseaProductionSystem.SubseaSystemResult
    ) = ...
    tiebackReport: jneqsim.process.fielddevelopment.tieback.TiebackReport = ...
    selectedTiebackOption: jneqsim.process.fielddevelopment.tieback.TiebackOption = ...
    subseaCapexMusd: float = ...
    arrivalPressureBara: float = ...
    arrivalTemperatureC: float = ...
    subseaSimulationError: java.lang.String = ...
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        fidelityLevel: FieldDevelopmentWorkflow.FidelityLevel,
    ): ...
    def getCashFlowTable(self) -> java.lang.String: ...
    def getProductionTable(self) -> java.lang.String: ...
    def getSummary(self) -> java.lang.String: ...
    def isViable(self) -> bool: ...
    def isViableWithConfidence(self, double: float) -> bool: ...
    def toString(self) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.fielddevelopment.workflow")``.

    FieldDevelopmentWorkflow: typing.Type[FieldDevelopmentWorkflow]
    WorkflowResult: typing.Type[WorkflowResult]
