import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.process.processmodel
import typing

class AllocationComparison:
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    DEFAULT_TOLERANCE: typing.ClassVar[float] = ...
    def __init__(
        self,
        map: typing.Union[
            java.util.Map["AllocationMethod", "ProductionAllocationResult"],
            typing.Mapping["AllocationMethod", "ProductionAllocationResult"],
        ],
        map2: typing.Union[
            java.util.Map["AllocationMethod", int],
            typing.Mapping["AllocationMethod", int],
        ],
    ): ...
    def getMaxRelativeDifference(
        self,
        allocationMethod: "AllocationMethod",
        allocationMethod2: "AllocationMethod",
    ) -> float: ...
    def getOwnerSensitivity(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.util.List["AllocationComparison.OwnerSensitivity"]: ...
    def getRecommendationRationale(self) -> java.lang.String: ...
    def getRecommendedMethod(self) -> "AllocationMethod": ...
    def getResult(
        self, allocationMethod: "AllocationMethod"
    ) -> "ProductionAllocationResult": ...
    def getResults(
        self,
    ) -> java.util.Map["AllocationMethod", "ProductionAllocationResult"]: ...
    def getRuntimeMillis(self, allocationMethod: "AllocationMethod") -> int: ...
    def setTolerance(self, double: float) -> "AllocationComparison": ...
    def toJson(self) -> java.lang.String: ...

    class OwnerSensitivity:
        def getPerMethod(self) -> java.util.Map["AllocationMethod", float]: ...
        def getProduct(self) -> "ProductType": ...
        def getSource(self) -> java.lang.String: ...
        def getSpread(self) -> float: ...
        def getUnit(self) -> java.lang.String: ...

class AllocationMethod(java.lang.Enum["AllocationMethod"]):
    COMPONENT_RATIO: typing.ClassVar["AllocationMethod"] = ...
    ALL_IN: typing.ClassVar["AllocationMethod"] = ...
    STAND_ALONE: typing.ClassVar["AllocationMethod"] = ...
    def getDescription(self) -> java.lang.String: ...
    def getDisplayName(self) -> java.lang.String: ...
    def getRelativeCostRank(self) -> int: ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> "AllocationMethod": ...
    @staticmethod
    def values() -> typing.MutableSequence["AllocationMethod"]: ...

class AllocationNetwork(java.io.Serializable):
    def __init__(self, recoveryFactorExtractor: "RecoveryFactorExtractor"): ...
    def buildRoutingMatrix(
        self, int: int
    ) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def findCustodyStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def findEntryUnit(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> int: ...
    def findProducer(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> typing.MutableSequence[int]: ...
    def findSourceStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getComponentCount(self) -> int: ...
    def getCustodyFactor(
        self, intArray: typing.Union[typing.List[int], jpype.JArray], int2: int
    ) -> float: ...
    def getFactors(self) -> "RecoveryFactorExtractor": ...
    def getNodeCount(self) -> int: ...
    def getUnits(
        self,
    ) -> java.util.List[jneqsim.process.equipment.ProcessEquipmentInterface]: ...

class AllocationSource(java.io.Serializable):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ): ...
    def getFeedStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getName(self) -> java.lang.String: ...

class AllocationUncertaintyEstimator(java.io.Serializable):
    def __init__(self): ...
    @typing.overload
    def propagate(
        self,
        allocationNetwork: AllocationNetwork,
        intArray: typing.Union[typing.List[int], jpype.JArray],
        list: java.util.List["CustodyOutlet"],
        stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray],
        stringArray2: typing.Union[typing.List[java.lang.String], jpype.JArray],
        productTypeArray: typing.Union[typing.List["ProductType"], jpype.JArray],
        stringArray3: typing.Union[typing.List[java.lang.String], jpype.JArray],
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        doubleArray2: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
    ) -> "AllocationUncertaintyEstimator.UncertaintyResult": ...
    @typing.overload
    def propagate(
        self,
        sourceAllocator: "SourceAllocator",
        doubleArray: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
    ) -> "AllocationUncertaintyEstimator.UncertaintyResult": ...
    def setNegativeClipTolerance(self, double: float) -> None: ...

    class UncertaintyResult(java.io.Serializable):
        SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
        def __init__(
            self,
            stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray],
            stringArray2: typing.Union[typing.List[java.lang.String], jpype.JArray],
            productTypeArray: typing.Union[typing.List["ProductType"], jpype.JArray],
            stringArray3: typing.Union[typing.List[java.lang.String], jpype.JArray],
            doubleArray: typing.Union[typing.List[float], jpype.JArray],
            doubleArray2: typing.Union[
                typing.List[typing.MutableSequence[typing.MutableSequence[float]]],
                jpype.JArray,
            ],
        ): ...
        def getAllocatedComponentFlowStdDevMoles(
            self,
            string: typing.Union[java.lang.String, str],
            string2: typing.Union[java.lang.String, str],
            string3: typing.Union[java.lang.String, str],
        ) -> float: ...
        def getAllocatedFlowStdDevKgPerHr(
            self,
            string: typing.Union[java.lang.String, str],
            string2: typing.Union[java.lang.String, str],
        ) -> float: ...
        def getAllocatedFlowStdDevMoles(
            self,
            string: typing.Union[java.lang.String, str],
            string2: typing.Union[java.lang.String, str],
        ) -> float: ...
        def getAllocatedFlowVariance(
            self,
            string: typing.Union[java.lang.String, str],
            string2: typing.Union[java.lang.String, str],
        ) -> float: ...
        def getComponentNames(self) -> typing.MutableSequence[java.lang.String]: ...
        def getCustodyNames(self) -> typing.MutableSequence[java.lang.String]: ...
        def getProductAllocationStdDev(
            self,
            string: typing.Union[java.lang.String, str],
            productType: "ProductType",
            string2: typing.Union[java.lang.String, str],
        ) -> float: ...
        def getSourceNames(self) -> typing.MutableSequence[java.lang.String]: ...
        def toJson(self) -> java.lang.String: ...

class CustodyOutlet(java.io.Serializable):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        productType: "ProductType",
    ): ...
    def getName(self) -> java.lang.String: ...
    def getProductType(self) -> "ProductType": ...
    def getStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...

class LinearAllocationSolver(java.io.Serializable):
    def __init__(self): ...
    def setMaxIterations(self, int: int) -> None: ...
    def setNegativeClipTolerance(self, double: float) -> None: ...
    def setTolerance(self, double: float) -> None: ...
    def solve(
        self,
        allocationNetwork: AllocationNetwork,
        intArray: typing.Union[typing.List[int], jpype.JArray],
        doubleArray: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
    ) -> "LinearAllocationSolver.SolverResult": ...

    class ComponentDiagnostics(java.io.Serializable):
        def getComponentIndex(self) -> int: ...
        def getIterations(self) -> int: ...
        def getMethod(self) -> java.lang.String: ...
        def getResidual(self) -> float: ...

    class SolverResult(java.io.Serializable):
        def getDiagnostics(
            self,
        ) -> java.util.List["LinearAllocationSolver.ComponentDiagnostics"]: ...
        def getNodeFlow(self, int: int, int2: int, int3: int) -> float: ...

class MultiMethodAllocator:
    def __init__(self): ...
    @typing.overload
    def addCustodyOutlet(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        productType: "ProductType",
    ) -> "MultiMethodAllocator": ...
    @typing.overload
    def addCustodyOutlet(
        self, custodyOutlet: CustodyOutlet
    ) -> "MultiMethodAllocator": ...
    @typing.overload
    def addSource(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> "MultiMethodAllocator": ...
    @typing.overload
    def addSource(
        self, allocationSource: AllocationSource
    ) -> "MultiMethodAllocator": ...
    def allocate(
        self, allocationMethod: AllocationMethod
    ) -> "ProductionAllocationResult": ...
    def allocateAll(self) -> AllocationComparison: ...
    def getBaseCase(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getCustodyOutlets(self) -> java.util.List[CustodyOutlet]: ...
    def getSources(self) -> java.util.List[AllocationSource]: ...
    def setBaseCase(
        self, processSystem: jneqsim.process.processmodel.ProcessSystem
    ) -> "MultiMethodAllocator": ...
    def setEnforceMassClosure(self, boolean: bool) -> "MultiMethodAllocator": ...
    def setStandaloneZeroFactor(self, double: float) -> "MultiMethodAllocator": ...

class ProductType(java.lang.Enum["ProductType"]):
    GAS: typing.ClassVar["ProductType"] = ...
    OIL: typing.ClassVar["ProductType"] = ...
    WATER: typing.ClassVar["ProductType"] = ...
    MIXED: typing.ClassVar["ProductType"] = ...
    UNKNOWN: typing.ClassVar["ProductType"] = ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> "ProductType": ...
    @staticmethod
    def values() -> typing.MutableSequence["ProductType"]: ...

class ProductionAllocationResult(java.io.Serializable):
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    def __init__(
        self,
        stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray],
        stringArray2: typing.Union[typing.List[java.lang.String], jpype.JArray],
        productTypeArray: typing.Union[typing.List[ProductType], jpype.JArray],
        stringArray3: typing.Union[typing.List[java.lang.String], jpype.JArray],
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        doubleArray2: typing.Union[
            typing.List[typing.MutableSequence[typing.MutableSequence[float]]],
            jpype.JArray,
        ],
        list: java.util.List[LinearAllocationSolver.ComponentDiagnostics],
    ): ...
    def getAllocatedComponentFlow(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        string3: typing.Union[java.lang.String, str],
        string4: typing.Union[java.lang.String, str],
    ) -> float: ...
    def getAllocatedFlow(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        string3: typing.Union[java.lang.String, str],
    ) -> float: ...
    def getAllocationFactor(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def getComponentNames(self) -> typing.MutableSequence[java.lang.String]: ...
    def getComponentRecoveryFactor(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def getCustodyNames(self) -> typing.MutableSequence[java.lang.String]: ...
    def getCustodyTotal(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def getDiagnostics(
        self,
    ) -> java.util.List[LinearAllocationSolver.ComponentDiagnostics]: ...
    def getMaxResidual(self) -> float: ...
    def getProductAllocation(
        self,
        string: typing.Union[java.lang.String, str],
        productType: ProductType,
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def getProductTotal(
        self, productType: ProductType, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getSourceNames(self) -> typing.MutableSequence[java.lang.String]: ...
    def getSourceTotal(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> float: ...
    def renormalizeMassClosure(
        self,
        doubleArray: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
    ) -> None: ...
    def toJson(self) -> java.lang.String: ...

class RecoveryFactorExtractor(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def extract(self) -> "RecoveryFactorExtractor": ...
    def getComponentNames(self) -> java.util.List[java.lang.String]: ...
    def getMolarMass(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getNodeUnits(
        self,
    ) -> java.util.List[jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    def getProcess(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getUnitSplits(self) -> java.util.Map[java.lang.String, "UnitSplit"]: ...

class SourceAllocator(java.io.Serializable):
    def __init__(self): ...
    @typing.overload
    def addCustodyOutlet(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        productType: ProductType,
    ) -> "SourceAllocator": ...
    @typing.overload
    def addCustodyOutlet(self, custodyOutlet: CustodyOutlet) -> "SourceAllocator": ...
    @typing.overload
    def addSource(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> "SourceAllocator": ...
    @typing.overload
    def addSource(self, allocationSource: AllocationSource) -> "SourceAllocator": ...
    def allocate(self) -> ProductionAllocationResult: ...
    def getBaseCase(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getCustodyOutlets(self) -> java.util.List[CustodyOutlet]: ...
    def getExtractor(self) -> RecoveryFactorExtractor: ...
    def getNetwork(self) -> AllocationNetwork: ...
    def getSolver(self) -> LinearAllocationSolver: ...
    def getSources(self) -> java.util.List[AllocationSource]: ...
    def setBaseCase(
        self, processSystem: jneqsim.process.processmodel.ProcessSystem
    ) -> "SourceAllocator": ...
    def setEnforceMassClosure(self, boolean: bool) -> "SourceAllocator": ...

class UnitSplit(java.io.Serializable):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        list: java.util.List[jneqsim.process.equipment.stream.StreamInterface],
        list2: java.util.List[jneqsim.process.equipment.stream.StreamInterface],
        stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray],
        doubleArray: typing.Union[
            typing.List[typing.MutableSequence[float]], jpype.JArray
        ],
        doubleArray2: typing.Union[typing.List[float], jpype.JArray],
    ): ...
    def getComponentNames(self) -> typing.MutableSequence[java.lang.String]: ...
    def getEquipmentType(self) -> java.lang.String: ...
    def getFactor(self, int: int, int2: int) -> float: ...
    def getInletComponentFlow(self, int: int) -> float: ...
    def getInletStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getOutletCount(self) -> int: ...
    def getOutletStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getUnitName(self) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.allocation")``.

    AllocationComparison: typing.Type[AllocationComparison]
    AllocationMethod: typing.Type[AllocationMethod]
    AllocationNetwork: typing.Type[AllocationNetwork]
    AllocationSource: typing.Type[AllocationSource]
    AllocationUncertaintyEstimator: typing.Type[AllocationUncertaintyEstimator]
    CustodyOutlet: typing.Type[CustodyOutlet]
    LinearAllocationSolver: typing.Type[LinearAllocationSolver]
    MultiMethodAllocator: typing.Type[MultiMethodAllocator]
    ProductType: typing.Type[ProductType]
    ProductionAllocationResult: typing.Type[ProductionAllocationResult]
    RecoveryFactorExtractor: typing.Type[RecoveryFactorExtractor]
    SourceAllocator: typing.Type[SourceAllocator]
    UnitSplit: typing.Type[UnitSplit]
