
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import typing



class FlareCapacityDTO(java.io.Serializable):
    def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, double9: float, boolean: bool): ...
    def getDesignHeatDutyW(self) -> float: ...
    def getDesignMassRateKgS(self) -> float: ...
    def getDesignMolarRateMoleS(self) -> float: ...
    def getHeatDutyW(self) -> float: ...
    def getHeatUtilization(self) -> float: ...
    def getMassRateKgS(self) -> float: ...
    def getMassUtilization(self) -> float: ...
    def getMolarRateMoleS(self) -> float: ...
    def getMolarUtilization(self) -> float: ...
    def isOverloaded(self) -> bool: ...

class FlareDispersionSurrogateDTO(java.io.Serializable):
    def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float): ...
    def getExitVelocityMs(self) -> float: ...
    def getMassRateKgS(self) -> float: ...
    def getMolarRateMoleS(self) -> float: ...
    def getMomentumFlux(self) -> float: ...
    def getMomentumPerMass(self) -> float: ...
    def getStandardVolumeSm3PerSec(self) -> float: ...

class FlarePerformanceDTO(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float, double6: float, flareDispersionSurrogateDTO: FlareDispersionSurrogateDTO, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], flareCapacityDTO: FlareCapacityDTO): ...
    def getCapacity(self) -> FlareCapacityDTO: ...
    def getCo2EmissionKgS(self) -> float: ...
    def getCo2EmissionTonPerDay(self) -> float: ...
    def getDispersion(self) -> FlareDispersionSurrogateDTO: ...
    def getDistanceTo4kWm2(self) -> float: ...
    def getEmissions(self) -> java.util.Map[java.lang.String, float]: ...
    def getHeatDutyMW(self) -> float: ...
    def getHeatDutyW(self) -> float: ...
    def getHeatFluxAt30mWm2(self) -> float: ...
    def getLabel(self) -> java.lang.String: ...
    def getMassRateKgS(self) -> float: ...
    def getMolarRateMoleS(self) -> float: ...
    def isOverloaded(self) -> bool: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.flare.dto")``.

    FlareCapacityDTO: typing.Type[FlareCapacityDTO]
    FlareDispersionSurrogateDTO: typing.Type[FlareDispersionSurrogateDTO]
    FlarePerformanceDTO: typing.Type[FlarePerformanceDTO]
