
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.fielddevelopment.tieback
import typing



class CapacityAllocationPolicy(java.lang.Enum['CapacityAllocationPolicy']):
    BASE_FIRST: typing.ClassVar['CapacityAllocationPolicy'] = ...
    SATELLITE_FIRST: typing.ClassVar['CapacityAllocationPolicy'] = ...
    PRO_RATA: typing.ClassVar['CapacityAllocationPolicy'] = ...
    VALUE_WEIGHTED: typing.ClassVar['CapacityAllocationPolicy'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'CapacityAllocationPolicy': ...
    @staticmethod
    def values() -> typing.MutableSequence['CapacityAllocationPolicy']: ...

class DebottleneckDecision(java.io.Serializable, java.lang.Comparable['DebottleneckDecision']):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, boolean: bool): ...
    def compareTo(self, debottleneckDecision: 'DebottleneckDecision') -> int: ...
    def getBottleneckName(self) -> java.lang.String: ...
    def getCapexMusd(self) -> float: ...
    def getDescription(self) -> java.lang.String: ...
    def getNpvMusd(self) -> float: ...
    def getPaybackYears(self) -> float: ...
    def getRecoveredValueMusd(self) -> float: ...
    def isRecommended(self) -> bool: ...

class HoldbackPolicy(java.lang.Enum['HoldbackPolicy']):
    CURTAIL: typing.ClassVar['HoldbackPolicy'] = ...
    DEFER_TO_LATER_YEARS: typing.ClassVar['HoldbackPolicy'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'HoldbackPolicy': ...
    @staticmethod
    def values() -> typing.MutableSequence['HoldbackPolicy']: ...

class HostTieInPoint(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def getBaseProcessRate(self) -> float: ...
    def getProcessRateUnit(self) -> java.lang.String: ...
    def getProcessStreamReference(self) -> java.lang.String: ...
    def setBaseProcessRate(self, double: float) -> 'HostTieInPoint': ...
    def setGasToProcessRateFactor(self, double: float) -> 'HostTieInPoint': ...
    def setLiquidToProcessRateFactor(self, double: float) -> 'HostTieInPoint': ...
    def setOilToProcessRateFactor(self, double: float) -> 'HostTieInPoint': ...
    def setWaterToProcessRateFactor(self, double: float) -> 'HostTieInPoint': ...
    def toProcessRate(self, productionLoad: 'ProductionLoad') -> float: ...

class ProductionLoad(java.io.Serializable):
    BARREL_TO_M3: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self, int: int, double: float, double2: float, double3: float, double4: float): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], int: int, double: float, double2: float, double3: float, double4: float): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], int: int, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, double9: float): ...
    def getDailyValueUsd(self) -> float: ...
    def getGasRateMSm3d(self) -> float: ...
    def getGasValueUsdPerMSm3(self) -> float: ...
    def getGasVolumeMSm3(self) -> float: ...
    def getLiquidRateM3d(self) -> float: ...
    def getLiquidValueUsdPerM3(self) -> float: ...
    def getLiquidVolumeM3(self) -> float: ...
    def getOilRateBopd(self) -> float: ...
    def getOilValueUsdPerBbl(self) -> float: ...
    def getOilVolumeBbl(self) -> float: ...
    def getPeriodLengthDays(self) -> float: ...
    def getPeriodName(self) -> java.lang.String: ...
    def getPeriodValueUsd(self) -> float: ...
    def getTotalLiquidRateM3d(self) -> float: ...
    def getWaterRateM3d(self) -> float: ...
    def getWaterValueUsdPerM3(self) -> float: ...
    def getWaterVolumeM3(self) -> float: ...
    def getYear(self) -> int: ...
    def isZero(self) -> bool: ...
    def plus(self, productionLoad: 'ProductionLoad') -> 'ProductionLoad': ...
    def scale(self, double: float) -> 'ProductionLoad': ...
    def subtractNonNegative(self, productionLoad: 'ProductionLoad') -> 'ProductionLoad': ...
    def toString(self) -> java.lang.String: ...
    def withCommodityValues(self, double: float, double2: float, double3: float, double4: float) -> 'ProductionLoad': ...
    def withPeriod(self, string: typing.Union[java.lang.String, str], int: int) -> 'ProductionLoad': ...
    def withPeriodLengthDays(self, double: float) -> 'ProductionLoad': ...
    @staticmethod
    def zero(int: int, string: typing.Union[java.lang.String, str]) -> 'ProductionLoad': ...

class ProductionProfileSeries(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def add(self, productionLoad: ProductionLoad) -> 'ProductionProfileSeries': ...
    @typing.overload
    def addPeriod(self, int: int, double: float, double2: float, double3: float, double4: float) -> 'ProductionProfileSeries': ...
    @typing.overload
    def addPeriod(self, string: typing.Union[java.lang.String, str], int: int, double: float, double2: float, double3: float, double4: float) -> 'ProductionProfileSeries': ...
    @staticmethod
    def fromGasRates(string: typing.Union[java.lang.String, str], int: int, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> 'ProductionProfileSeries': ...
    @staticmethod
    def fromOilRates(string: typing.Union[java.lang.String, str], int: int, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> 'ProductionProfileSeries': ...
    def getLoad(self, int: int) -> ProductionLoad: ...
    def getLoadByYear(self, int: int) -> ProductionLoad: ...
    def getLoadByYearOrIndex(self, int: int, int2: int, string: typing.Union[java.lang.String, str]) -> ProductionLoad: ...
    def getLoads(self) -> java.util.List[ProductionLoad]: ...
    def getName(self) -> java.lang.String: ...
    def isEmpty(self) -> bool: ...
    def size(self) -> int: ...

class TieInCapacityPlanner(java.io.Serializable):
    def __init__(self, hostFacility: jneqsim.process.fielddevelopment.tieback.HostFacility): ...
    def run(self) -> 'TieInCapacityResult': ...
    def setAllocationPolicy(self, capacityAllocationPolicy: CapacityAllocationPolicy) -> 'TieInCapacityPlanner': ...
    def setDefaultCommodityValues(self, double: float, double2: float, double3: float, double4: float) -> 'TieInCapacityPlanner': ...
    def setDefaultDebottleneckCapexMusd(self, double: float) -> 'TieInCapacityPlanner': ...
    def setDiscountRate(self, double: float) -> 'TieInCapacityPlanner': ...
    def setHoldbackPolicy(self, holdbackPolicy: HoldbackPolicy) -> 'TieInCapacityPlanner': ...
    def setHostProductionProfile(self, productionProfileSeries: ProductionProfileSeries) -> 'TieInCapacityPlanner': ...
    def setProcessUtilizationLimit(self, double: float) -> 'TieInCapacityPlanner': ...
    def setSatelliteProductionProfile(self, productionProfileSeries: ProductionProfileSeries) -> 'TieInCapacityPlanner': ...
    def setTieInPoint(self, hostTieInPoint: HostTieInPoint) -> 'TieInCapacityPlanner': ...

class TieInCapacityResult(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], capacityAllocationPolicy: CapacityAllocationPolicy, holdbackPolicy: HoldbackPolicy, list: java.util.List['TieInPeriodResult'], list2: java.util.List[DebottleneckDecision], string2: typing.Union[java.lang.String, str]): ...
    def getAllocationPolicy(self) -> CapacityAllocationPolicy: ...
    def getDebottleneckDecisions(self) -> java.util.List[DebottleneckDecision]: ...
    def getHoldbackPolicy(self) -> HoldbackPolicy: ...
    def getHostName(self) -> java.lang.String: ...
    def getPeriodResults(self) -> java.util.List['TieInPeriodResult']: ...
    def getPrimaryBottleneck(self) -> java.lang.String: ...
    def getSummary(self) -> java.lang.String: ...
    def getTotalAcceptedGasMSm3(self) -> float: ...
    def getTotalAcceptedOilBbl(self) -> float: ...
    def getTotalDeferredValueMusd(self) -> float: ...
    def getTotalDeferredValueNpvMusd(self) -> float: ...
    def getTotalHeldBackGasMSm3(self) -> float: ...
    def getTotalHeldBackLiquidM3(self) -> float: ...
    def getTotalHeldBackOilBbl(self) -> float: ...
    def getTotalHeldBackWaterM3(self) -> float: ...
    def hasHoldback(self) -> bool: ...
    def toCsv(self) -> java.lang.String: ...
    def toMarkdownTable(self) -> java.lang.String: ...

class TieInPeriodResult(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], int: int, productionLoad: ProductionLoad, productionLoad2: ProductionLoad, productionLoad3: ProductionLoad, productionLoad4: ProductionLoad, productionLoad5: ProductionLoad, productionLoad6: ProductionLoad, productionLoad7: ProductionLoad, productionLoad8: ProductionLoad, double: float, string2: typing.Union[java.lang.String, str], boolean: bool, boolean2: bool, string3: typing.Union[java.lang.String, str], double2: float, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], double3: float, double4: float, string4: typing.Union[java.lang.String, str]): ...
    def getAcceptedBase(self) -> ProductionLoad: ...
    def getAcceptedSatellite(self) -> ProductionLoad: ...
    def getBaseRequest(self) -> ProductionLoad: ...
    def getDeferredIntoPeriod(self) -> ProductionLoad: ...
    def getDeferredToNextPeriod(self) -> ProductionLoad: ...
    def getDeferredValueMusd(self) -> float: ...
    def getDeferredValueNpvMusd(self) -> float: ...
    def getHeldBackSatellite(self) -> ProductionLoad: ...
    def getNameplateBottleneck(self) -> java.lang.String: ...
    def getPeriodName(self) -> java.lang.String: ...
    def getPrimaryBottleneck(self) -> java.lang.String: ...
    def getProcessBottleneck(self) -> java.lang.String: ...
    def getProcessBottleneckUtilization(self) -> float: ...
    def getProcessUtilizationSummary(self) -> java.util.Map[java.lang.String, float]: ...
    def getSatelliteAllocationScale(self) -> float: ...
    def getSatelliteRequest(self) -> ProductionLoad: ...
    def getScheduledSatellite(self) -> ProductionLoad: ...
    def getSummary(self) -> java.lang.String: ...
    def getYear(self) -> int: ...
    def isProcessCapacityAvailable(self) -> bool: ...
    def isProcessModelUsed(self) -> bool: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.fielddevelopment.tieback.capacity")``.

    CapacityAllocationPolicy: typing.Type[CapacityAllocationPolicy]
    DebottleneckDecision: typing.Type[DebottleneckDecision]
    HoldbackPolicy: typing.Type[HoldbackPolicy]
    HostTieInPoint: typing.Type[HostTieInPoint]
    ProductionLoad: typing.Type[ProductionLoad]
    ProductionProfileSeries: typing.Type[ProductionProfileSeries]
    TieInCapacityPlanner: typing.Type[TieInCapacityPlanner]
    TieInCapacityResult: typing.Type[TieInCapacityResult]
    TieInPeriodResult: typing.Type[TieInPeriodResult]
