import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment.capacity
import typing

class DebottleneckingAdvisor(java.io.Serializable):
    def __init__(self, economicParameters: "EconomicParameters"): ...
    def addCandidate(
        self, debottleneckCandidate: "DebottleneckingAdvisor.DebottleneckCandidate"
    ) -> "DebottleneckingAdvisor": ...
    def applyShadowPrices(self) -> int: ...
    def evaluate(self) -> java.util.List["DebottleneckingAdvisor.Recommendation"]: ...
    def getCandidates(
        self,
    ) -> java.util.List["DebottleneckingAdvisor.DebottleneckCandidate"]: ...
    def toJson(self) -> java.lang.String: ...

    class DebottleneckCandidate(java.io.Serializable):
        def __init__(
            self,
            string: typing.Union[java.lang.String, str],
            string2: typing.Union[java.lang.String, str],
            double: float,
            int: int,
            int2: int,
            double2: float,
            capacityConstraint: jneqsim.process.equipment.capacity.CapacityConstraint,
        ): ...
        def getAnnualIncrementalValueNok(self) -> float: ...
        def getCapexNok(self) -> float: ...
        def getConstraint(
            self,
        ) -> jneqsim.process.equipment.capacity.CapacityConstraint: ...
        def getFirstYear(self) -> int: ...
        def getLastYear(self) -> int: ...
        def getName(self) -> java.lang.String: ...
        def getTargetEquipment(self) -> java.lang.String: ...

    class Recommendation(java.io.Serializable):
        def __init__(
            self,
            debottleneckCandidate: "DebottleneckingAdvisor.DebottleneckCandidate",
            double: float,
            double2: float,
            double3: float,
            double4: float,
        ): ...
        def getBenefitCostRatio(self) -> float: ...
        def getCandidate(self) -> "DebottleneckingAdvisor.DebottleneckCandidate": ...
        def getNpvNok(self) -> float: ...
        def getPaybackYears(self) -> float: ...
        def getPvBenefitsNok(self) -> float: ...
        def isAttractive(self) -> bool: ...

class EconomicParameters(java.io.Serializable):
    def __init__(self): ...
    def discountFactor(self, double: float) -> float: ...
    def getCo2IntensityTonnePerMWh(self) -> float: ...
    def getCo2Tax(self) -> float: ...
    def getCurrency(self) -> java.lang.String: ...
    def getDiscountRate(self) -> float: ...
    def getGasPrice(self) -> float: ...
    def getOilPrice(self) -> float: ...
    def getPowerCost(self) -> float: ...
    def setCo2IntensityTonnePerMWh(self, double: float) -> "EconomicParameters": ...
    def setCo2Tax(self, double: float) -> "EconomicParameters": ...
    def setCurrency(
        self, string: typing.Union[java.lang.String, str]
    ) -> "EconomicParameters": ...
    def setDiscountRate(self, double: float) -> "EconomicParameters": ...
    def setGasPrice(self, double: float) -> "EconomicParameters": ...
    def setOilPrice(self, double: float) -> "EconomicParameters": ...
    def setPowerCost(self, double: float) -> "EconomicParameters": ...

class LifeOfFieldOptimizer(java.io.Serializable):
    DEFAULT_MAX_COMBINATIONS: typing.ClassVar[int] = ...
    def __init__(self, int: int, economicParameters: EconomicParameters): ...
    def addInvestment(
        self, investment: "LifeOfFieldOptimizer.Investment"
    ) -> "LifeOfFieldOptimizer": ...
    def optimize(
        self,
        lifeOfFieldEvaluator: typing.Union[
            "LifeOfFieldOptimizer.LifeOfFieldEvaluator", typing.Callable
        ],
    ) -> "LifeOfFieldOptimizer.LifeOfFieldResult": ...
    def setMaxCombinations(self, long: int) -> "LifeOfFieldOptimizer": ...

    class Investment(java.io.Serializable):
        def __init__(
            self, string: typing.Union[java.lang.String, str], double: float, int: int
        ): ...
        def getCapexNok(self) -> float: ...
        def getEarliestYear(self) -> int: ...
        def getName(self) -> java.lang.String: ...

    class LifeOfFieldEvaluator:
        def annualNetValueNok(
            self, int: int, booleanArray: typing.Union[typing.List[bool], jpype.JArray]
        ) -> float: ...

    class LifeOfFieldResult(java.io.Serializable):
        def __init__(
            self,
            intArray: typing.Union[typing.List[int], jpype.JArray],
            double: float,
            doubleArray: typing.Union[typing.List[float], jpype.JArray],
        ): ...
        def getAnnualCashFlow(self) -> typing.MutableSequence[float]: ...
        def getInstallYears(self) -> typing.MutableSequence[int]: ...
        def getNpvNok(self) -> float: ...

class NetworkAllocationOptimizer(java.io.Serializable):
    def __init__(self, double: float, int: int): ...
    def optimize(
        self,
        allocationEvaluator: typing.Union[
            "NetworkAllocationOptimizer.AllocationEvaluator", typing.Callable
        ],
    ) -> "NetworkAllocationOptimizer.AllocationResult": ...
    def setBounds(
        self, int: int, double: float, double2: float
    ) -> "NetworkAllocationOptimizer": ...
    def setInitialAllocation(
        self, doubleArray: typing.Union[typing.List[float], jpype.JArray]
    ) -> "NetworkAllocationOptimizer": ...
    def setInitialStepFraction(self, double: float) -> "NetworkAllocationOptimizer": ...
    def setMaxIterations(self, int: int) -> "NetworkAllocationOptimizer": ...
    def setTolerance(self, double: float) -> "NetworkAllocationOptimizer": ...

    class AllocationEvaluator:
        def evaluate(
            self, doubleArray: typing.Union[typing.List[float], jpype.JArray]
        ) -> "NetworkAllocationOptimizer.AllocationResult": ...

    class AllocationResult(java.io.Serializable):
        def __init__(
            self,
            doubleArray: typing.Union[typing.List[float], jpype.JArray],
            double2: float,
            boolean: bool,
        ): ...
        def getAllocation(self) -> typing.MutableSequence[float]: ...
        def getObjective(self) -> float: ...
        def isFeasible(self) -> bool: ...

_ParallelSweep__SweepEvaluator__R = typing.TypeVar(
    "_ParallelSweep__SweepEvaluator__R"
)  # <R>

class ParallelSweep(java.io.Serializable):
    def __init__(self): ...
    def getParallelism(self) -> int: ...
    _run__R = typing.TypeVar("_run__R")  # <R>
    def run(
        self,
        list: java.util.List[typing.Union[typing.List[float], jpype.JArray]],
        sweepEvaluator: typing.Union[
            "ParallelSweep.SweepEvaluator"[_run__R],
            typing.Callable[[typing.MutableSequence[float]], _run__R],
        ],
    ) -> java.util.List[_run__R]: ...
    def setParallelism(self, int: int) -> "ParallelSweep": ...

    class SweepEvaluator(typing.Generic[_ParallelSweep__SweepEvaluator__R]):
        def evaluate(
            self, doubleArray: typing.Union[typing.List[float], jpype.JArray]
        ) -> _ParallelSweep__SweepEvaluator__R: ...

class RealTimeOptimizationLoop(java.io.Serializable):
    def __init__(self): ...
    def getHistory(self) -> java.util.List["RealTimeOptimizationLoop.CycleRecord"]: ...
    def run(
        self, int: int
    ) -> java.util.List["RealTimeOptimizationLoop.CycleRecord"]: ...
    def setCalibrator(
        self,
        calibrator: typing.Union[
            "RealTimeOptimizationLoop.Calibrator", typing.Callable
        ],
    ) -> "RealTimeOptimizationLoop": ...
    def setObjectiveProbe(
        self,
        objectiveProbe: typing.Union[
            "RealTimeOptimizationLoop.ObjectiveProbe", typing.Callable
        ],
    ) -> "RealTimeOptimizationLoop": ...
    def setOptimizer(
        self,
        setpointOptimizer: typing.Union[
            "RealTimeOptimizationLoop.SetpointOptimizer", typing.Callable
        ],
    ) -> "RealTimeOptimizationLoop": ...
    def setReader(
        self,
        plantReader: typing.Union[
            "RealTimeOptimizationLoop.PlantReader", typing.Callable
        ],
    ) -> "RealTimeOptimizationLoop": ...
    def setWriter(
        self,
        setpointWriter: typing.Union[
            "RealTimeOptimizationLoop.SetpointWriter", typing.Callable
        ],
    ) -> "RealTimeOptimizationLoop": ...
    def toJson(self) -> java.lang.String: ...

    class Calibrator:
        def calibrate(
            self, doubleArray: typing.Union[typing.List[float], jpype.JArray]
        ) -> None: ...

    class CycleRecord(java.io.Serializable):
        def __init__(
            self,
            int: int,
            doubleArray: typing.Union[typing.List[float], jpype.JArray],
            doubleArray2: typing.Union[typing.List[float], jpype.JArray],
            double3: float,
        ): ...
        def getCycle(self) -> int: ...
        def getMeasurements(self) -> typing.MutableSequence[float]: ...
        def getObjective(self) -> float: ...
        def getSetpoints(self) -> typing.MutableSequence[float]: ...

    class ObjectiveProbe:
        def currentObjective(self) -> float: ...

    class PlantReader:
        def read(self) -> typing.MutableSequence[float]: ...

    class SetpointOptimizer:
        def optimize(self) -> typing.MutableSequence[float]: ...

    class SetpointWriter:
        def apply(
            self, doubleArray: typing.Union[typing.List[float], jpype.JArray]
        ) -> None: ...

class RobustOptimizationStudy(java.io.Serializable):
    def __init__(self): ...
    def addScenario(
        self, doubleArray: typing.Union[typing.List[float], jpype.JArray]
    ) -> "RobustOptimizationStudy": ...
    def evaluateDecision(
        self,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        scenarioEvaluator: typing.Union[
            "RobustOptimizationStudy.ScenarioEvaluator", typing.Callable
        ],
    ) -> "RobustOptimizationStudy.RobustResult": ...
    def selectRobust(
        self,
        list: java.util.List[typing.Union[typing.List[float], jpype.JArray]],
        scenarioEvaluator: typing.Union[
            "RobustOptimizationStudy.ScenarioEvaluator", typing.Callable
        ],
    ) -> "RobustOptimizationStudy.RobustResult": ...
    def setRequiredConfidence(self, double: float) -> "RobustOptimizationStudy": ...
    def setSampler(
        self,
        scenarioSampler: typing.Union[
            "RobustOptimizationStudy.ScenarioSampler", typing.Callable
        ],
        int: int,
    ) -> "RobustOptimizationStudy": ...
    def setSeed(self, long: int) -> "RobustOptimizationStudy": ...

    class RobustResult(java.io.Serializable):
        def __init__(
            self,
            doubleArray: typing.Union[typing.List[float], jpype.JArray],
            double2: float,
            double3: float,
            double4: float,
            double5: float,
            double6: float,
        ): ...
        def getDecision(self) -> typing.MutableSequence[float]: ...
        def getFeasibleFraction(self) -> float: ...
        def getMean(self) -> float: ...
        def getP10(self) -> float: ...
        def getP50(self) -> float: ...
        def getP90(self) -> float: ...

    class ScenarioEvaluator:
        def evaluate(
            self,
            doubleArray: typing.Union[typing.List[float], jpype.JArray],
            doubleArray2: typing.Union[typing.List[float], jpype.JArray],
        ) -> "RobustOptimizationStudy.ScenarioOutcome": ...

    class ScenarioOutcome(java.io.Serializable):
        def __init__(self, double: float, boolean: bool): ...
        def getObjective(self) -> float: ...
        def isFeasible(self) -> bool: ...

    class ScenarioSampler:
        def sample(self, random: java.util.Random) -> typing.MutableSequence[float]: ...

class ValueChainObjective(java.io.Serializable):
    PRODUCTION_DAYS_PER_YEAR: typing.ClassVar[float] = ...
    def __init__(self, economicParameters: EconomicParameters): ...
    @typing.overload
    def evaluate(
        self, double: float, double2: float, double3: float
    ) -> "ValueChainObjective.ValueResult": ...
    @typing.overload
    def evaluate(
        self, double: float, double2: float, double3: float, double4: float
    ) -> "ValueChainObjective.ValueResult": ...
    def getEconomicParameters(self) -> EconomicParameters: ...
    def presentValueOfAnnualCashFlow(self, double: float, double2: float) -> float: ...

    class ValueResult(java.io.Serializable):
        def __init__(
            self,
            double: float,
            double2: float,
            double3: float,
            double4: float,
            double5: float,
        ): ...
        def getCarbonCostNokPerDay(self) -> float: ...
        def getCo2TonnePerDay(self) -> float: ...
        def getEnergyCostNokPerDay(self) -> float: ...
        def getNetValueNokPerDay(self) -> float: ...
        def getRevenueNokPerDay(self) -> float: ...
        def toJson(self) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.optimization.valuechain")``.

    DebottleneckingAdvisor: typing.Type[DebottleneckingAdvisor]
    EconomicParameters: typing.Type[EconomicParameters]
    LifeOfFieldOptimizer: typing.Type[LifeOfFieldOptimizer]
    NetworkAllocationOptimizer: typing.Type[NetworkAllocationOptimizer]
    ParallelSweep: typing.Type[ParallelSweep]
    RealTimeOptimizationLoop: typing.Type[RealTimeOptimizationLoop]
    RobustOptimizationStudy: typing.Type[RobustOptimizationStudy]
    ValueChainObjective: typing.Type[ValueChainObjective]
