
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import typing



class ThermowellDesignCalculator(java.io.Serializable):
    def __init__(self): ...
    def calcAll(self) -> None: ...
    def getDynamicStress(self) -> float: ...
    def getFrequencyRatio(self) -> float: ...
    def getInstalledNaturalFrequency(self) -> float: ...
    def getMaxAllowablePressure(self) -> float: ...
    def getNaturalFrequency(self) -> float: ...
    def getReynoldsNumber(self) -> float: ...
    def getScrutonNumber(self) -> float: ...
    def getStaticStress(self) -> float: ...
    def getStrouhalNumber(self) -> float: ...
    def getVortexSheddingFrequency(self) -> float: ...
    def isDesignAcceptable(self) -> bool: ...
    def isDynamicStressCheckPassed(self) -> bool: ...
    def isFrequencyCheckPassed(self) -> bool: ...
    def isHydrostaticCheckPassed(self) -> bool: ...
    def isStaticStressCheckPassed(self) -> bool: ...
    def setCorrectionFactors(self, double: float, double2: float, double3: float) -> None: ...
    def setFrequencyRatioLimit(self, double: float) -> None: ...
    def setGeometry(self, double: float, double2: float, double3: float, double4: float, double5: float) -> None: ...
    def setMaterial(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    def setProcessConditions(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    def toJson(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.thermowell")``.

    ThermowellDesignCalculator: typing.Type[ThermowellDesignCalculator]
