
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.processmodel
import jneqsim.process.util.optimizer
import typing



class DependencyAnalyzer(java.io.Serializable):
    @typing.overload
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    @typing.overload
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem, processTopologyAnalyzer: 'ProcessTopologyAnalyzer'): ...
    @typing.overload
    def addCrossInstallationDependency(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def addCrossInstallationDependency(self, functionalLocation: 'FunctionalLocation', functionalLocation2: 'FunctionalLocation', string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def analyzeFailure(self, string: typing.Union[java.lang.String, str]) -> 'DependencyAnalyzer.DependencyResult': ...
    def findCriticalPaths(self) -> java.util.List[java.util.List[java.lang.String]]: ...
    def getEquipmentToMonitor(self, string: typing.Union[java.lang.String, str]) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def getImpactAnalyzer(self) -> jneqsim.process.util.optimizer.ProductionImpactAnalyzer: ...
    def getTopologyAnalyzer(self) -> 'ProcessTopologyAnalyzer': ...
    def initialize(self) -> None: ...
    class CrossInstallationDependency(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
        def getDependencyType(self) -> java.lang.String: ...
        def getImpactFactor(self) -> float: ...
        def getSourceEquipment(self) -> java.lang.String: ...
        def getSourceInstallation(self) -> java.lang.String: ...
        def getSourceLocation(self) -> 'FunctionalLocation': ...
        def getTargetEquipment(self) -> java.lang.String: ...
        def getTargetInstallation(self) -> java.lang.String: ...
        def getTargetLocation(self) -> 'FunctionalLocation': ...
        def setImpactFactor(self, double: float) -> None: ...
        def setSourceInstallation(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setSourceLocation(self, functionalLocation: 'FunctionalLocation') -> None: ...
        def setTargetInstallation(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setTargetLocation(self, functionalLocation: 'FunctionalLocation') -> None: ...
    class DependencyResult(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def getCrossInstallationEffects(self) -> java.util.List['DependencyAnalyzer.CrossInstallationDependency']: ...
        def getDirectlyAffected(self) -> java.util.List[java.lang.String]: ...
        def getEquipmentToWatch(self) -> java.util.List[java.lang.String]: ...
        def getFailedEquipment(self) -> java.lang.String: ...
        def getFailedLocation(self) -> 'FunctionalLocation': ...
        def getIncreasedCriticality(self) -> java.util.Map[java.lang.String, float]: ...
        def getIndirectlyAffected(self) -> java.util.List[java.lang.String]: ...
        def getProductionImpactByEquipment(self) -> java.util.Map[java.lang.String, float]: ...
        def getTotalProductionLoss(self) -> float: ...
        def toJson(self) -> java.lang.String: ...

class FunctionalLocation(java.io.Serializable, java.lang.Comparable['FunctionalLocation']):
    GULLFAKS_A: typing.ClassVar[java.lang.String] = ...
    GULLFAKS_B: typing.ClassVar[java.lang.String] = ...
    GULLFAKS_C: typing.ClassVar[java.lang.String] = ...
    ASGARD_A: typing.ClassVar[java.lang.String] = ...
    ASGARD_B: typing.ClassVar[java.lang.String] = ...
    ASGARD_C: typing.ClassVar[java.lang.String] = ...
    TROLL_A: typing.ClassVar[java.lang.String] = ...
    OSEBERG_A: typing.ClassVar[java.lang.String] = ...
    TYPE_COMPRESSOR: typing.ClassVar[java.lang.String] = ...
    TYPE_PUMP: typing.ClassVar[java.lang.String] = ...
    TYPE_VALVE: typing.ClassVar[java.lang.String] = ...
    TYPE_HEAT_EXCHANGER: typing.ClassVar[java.lang.String] = ...
    TYPE_SEPARATOR: typing.ClassVar[java.lang.String] = ...
    TYPE_TURBINE: typing.ClassVar[java.lang.String] = ...
    TYPE_MOTOR: typing.ClassVar[java.lang.String] = ...
    TYPE_TANK: typing.ClassVar[java.lang.String] = ...
    TYPE_PIPELINE: typing.ClassVar[java.lang.String] = ...
    TYPE_COOLER: typing.ClassVar[java.lang.String] = ...
    TYPE_HEATER: typing.ClassVar[java.lang.String] = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
    @staticmethod
    def builder() -> 'FunctionalLocation.Builder': ...
    def compareTo(self, functionalLocation: 'FunctionalLocation') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getArea(self) -> java.lang.String: ...
    def getBaseTag(self) -> java.lang.String: ...
    def getDescription(self) -> java.lang.String: ...
    def getEquipmentTypeCode(self) -> java.lang.String: ...
    def getEquipmentTypeDescription(self) -> java.lang.String: ...
    def getFullTag(self) -> java.lang.String: ...
    def getInstallationCode(self) -> java.lang.String: ...
    def getInstallationName(self) -> java.lang.String: ...
    def getSequentialNumber(self) -> java.lang.String: ...
    def getSubsystem(self) -> java.lang.String: ...
    def getSystem(self) -> java.lang.String: ...
    def getTrainSuffix(self) -> java.lang.String: ...
    def hashCode(self) -> int: ...
    def isParallelTo(self, functionalLocation: 'FunctionalLocation') -> bool: ...
    def isParallelUnit(self) -> bool: ...
    def isSameInstallation(self, functionalLocation: 'FunctionalLocation') -> bool: ...
    def isSameSystem(self, functionalLocation: 'FunctionalLocation') -> bool: ...
    def setArea(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDescription(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSubsystem(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSystem(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def toString(self) -> java.lang.String: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'FunctionalLocation': ...
        def description(self, string: typing.Union[java.lang.String, str]) -> 'FunctionalLocation.Builder': ...
        def installation(self, string: typing.Union[java.lang.String, str]) -> 'FunctionalLocation.Builder': ...
        def number(self, string: typing.Union[java.lang.String, str]) -> 'FunctionalLocation.Builder': ...
        def system(self, string: typing.Union[java.lang.String, str]) -> 'FunctionalLocation.Builder': ...
        def train(self, string: typing.Union[java.lang.String, str]) -> 'FunctionalLocation.Builder': ...
        def type(self, string: typing.Union[java.lang.String, str]) -> 'FunctionalLocation.Builder': ...

class ProcessTopologyAnalyzer(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def buildTopology(self) -> None: ...
    def getAffectedByFailure(self, string: typing.Union[java.lang.String, str]) -> java.util.List[java.lang.String]: ...
    def getDownstreamEquipment(self, string: typing.Union[java.lang.String, str]) -> java.util.List[java.lang.String]: ...
    def getEdges(self) -> java.util.List['ProcessTopologyAnalyzer.ProcessEdge']: ...
    def getIncreasedCriticalityOn(self, string: typing.Union[java.lang.String, str]) -> java.util.Map[java.lang.String, float]: ...
    def getNode(self, string: typing.Union[java.lang.String, str]) -> 'ProcessTopologyAnalyzer.EquipmentNode': ...
    def getNodes(self) -> java.util.Map[java.lang.String, 'ProcessTopologyAnalyzer.EquipmentNode']: ...
    def getParallelEquipment(self, string: typing.Union[java.lang.String, str]) -> java.util.List[java.lang.String]: ...
    def getParallelGroups(self) -> java.util.List[java.util.List[java.lang.String]]: ...
    def getTopologicalOrder(self) -> java.util.Map[java.lang.String, int]: ...
    def getUpstreamEquipment(self, string: typing.Union[java.lang.String, str]) -> java.util.List[java.lang.String]: ...
    @typing.overload
    def setFunctionalLocation(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setFunctionalLocation(self, string: typing.Union[java.lang.String, str], functionalLocation: FunctionalLocation) -> None: ...
    def toDotGraph(self) -> java.lang.String: ...
    def toJson(self) -> java.lang.String: ...
    class EquipmentNode(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
        def getCriticality(self) -> float: ...
        def getDownstreamEquipment(self) -> java.util.List[java.lang.String]: ...
        def getEquipmentType(self) -> java.lang.String: ...
        def getFunctionalLocation(self) -> FunctionalLocation: ...
        def getName(self) -> java.lang.String: ...
        def getParallelEquipment(self) -> java.util.List[java.lang.String]: ...
        def getTopologicalOrder(self) -> int: ...
        def getUpstreamEquipment(self) -> java.util.List[java.lang.String]: ...
        def isCritical(self) -> bool: ...
        def setFunctionalLocation(self, functionalLocation: FunctionalLocation) -> None: ...
    class ProcessEdge(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
        def getFromEquipment(self) -> java.lang.String: ...
        def getStreamName(self) -> java.lang.String: ...
        def getStreamType(self) -> java.lang.String: ...
        def getToEquipment(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.util.topology")``.

    DependencyAnalyzer: typing.Type[DependencyAnalyzer]
    FunctionalLocation: typing.Type[FunctionalLocation]
    ProcessTopologyAnalyzer: typing.Type[ProcessTopologyAnalyzer]
