
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jneqsim.process.equipment
import jneqsim.process.mechanicaldesign
import typing



class FlareMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def getDesignHeatReleaseMW(self) -> float: ...
    def getFlameLength(self) -> float: ...
    def getFlameTiltAngle(self) -> float: ...
    def getHeaderDiameter(self) -> float: ...
    def getPilotGasConsumption(self) -> float: ...
    def getRadiationDistanceAtGrade(self) -> float: ...
    def getSmokeSuppressingSteamRate(self) -> float: ...
    def getStackHeight(self) -> float: ...
    def getStackMaterial(self) -> java.lang.String: ...
    def getStackWallThickness(self) -> float: ...
    def getStackWeight(self) -> float: ...
    def getTipDiameter(self) -> float: ...
    def setDesignWindSpeed(self, double: float) -> None: ...
    def setMaxRadiationAtGrade(self, double: float) -> None: ...
    def setMaxTipMachNumber(self, double: float) -> None: ...
    def setRadiantFraction(self, double: float) -> None: ...
    def setStackMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.flare")``.

    FlareMechanicalDesign: typing.Type[FlareMechanicalDesign]
