
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.thermo.system
import typing



class EquipmentValidator:
    def __init__(self): ...
    @staticmethod
    def isEquipmentReady(processEquipmentBaseClass: jneqsim.process.equipment.ProcessEquipmentBaseClass) -> bool: ...
    @staticmethod
    def validateEquipment(processEquipmentBaseClass: jneqsim.process.equipment.ProcessEquipmentBaseClass) -> 'ValidationFramework.ValidationResult': ...
    @staticmethod
    def validateSequence(*processEquipmentBaseClass: jneqsim.process.equipment.ProcessEquipmentBaseClass) -> 'ValidationFramework.ValidationResult': ...

class StreamValidator:
    def __init__(self): ...
    @staticmethod
    def hasStreamBeenRun(streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> bool: ...
    @staticmethod
    def isStreamReady(streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> bool: ...
    @staticmethod
    def validateStream(streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> 'ValidationFramework.ValidationResult': ...
    @staticmethod
    def validateStreamConnection(streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface) -> 'ValidationFramework.ValidationResult': ...
    @staticmethod
    def validateStreamHasRun(streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> 'ValidationFramework.ValidationResult': ...

class ThermoValidator:
    def __init__(self): ...
    @staticmethod
    def isSystemReady(systemInterface: jneqsim.thermo.system.SystemInterface) -> bool: ...
    @staticmethod
    def validateCpAeos(systemInterface: jneqsim.thermo.system.SystemInterface) -> 'ValidationFramework.ValidationResult': ...
    @staticmethod
    def validateForEquilibrium(systemInterface: jneqsim.thermo.system.SystemInterface) -> 'ValidationFramework.ValidationResult': ...
    @staticmethod
    def validateSrkEos(systemInterface: jneqsim.thermo.system.SystemInterface) -> 'ValidationFramework.ValidationResult': ...
    @staticmethod
    def validateSystem(systemInterface: jneqsim.thermo.system.SystemInterface) -> 'ValidationFramework.ValidationResult': ...

class ValidationFramework:
    def __init__(self): ...
    @staticmethod
    def validate(string: typing.Union[java.lang.String, str]) -> 'ValidationFramework.ValidationBuilder': ...
    class CommonErrors:
        MIXING_RULE_NOT_SET: typing.ClassVar[java.lang.String] = ...
        REMEDIATION_MIXING_RULE: typing.ClassVar[java.lang.String] = ...
        NO_COMPONENTS: typing.ClassVar[java.lang.String] = ...
        REMEDIATION_NO_COMPONENTS: typing.ClassVar[java.lang.String] = ...
        DATABASE_NOT_CREATED: typing.ClassVar[java.lang.String] = ...
        REMEDIATION_DATABASE: typing.ClassVar[java.lang.String] = ...
        FEED_STREAM_NOT_SET: typing.ClassVar[java.lang.String] = ...
        REMEDIATION_FEED_STREAM: typing.ClassVar[java.lang.String] = ...
        INVALID_PRESSURE: typing.ClassVar[java.lang.String] = ...
        REMEDIATION_INVALID_PRESSURE: typing.ClassVar[java.lang.String] = ...
        INVALID_TEMPERATURE: typing.ClassVar[java.lang.String] = ...
        REMEDIATION_INVALID_TEMPERATURE: typing.ClassVar[java.lang.String] = ...
        COMPOSITION_SUM_NOT_UNITY: typing.ClassVar[java.lang.String] = ...
        REMEDIATION_COMPOSITION: typing.ClassVar[java.lang.String] = ...
        SYSTEM_NOT_INITIALIZED: typing.ClassVar[java.lang.String] = ...
        REMEDIATION_SYSTEM_INIT: typing.ClassVar[java.lang.String] = ...
        STREAM_NOT_RUN: typing.ClassVar[java.lang.String] = ...
        REMEDIATION_STREAM_RUN: typing.ClassVar[java.lang.String] = ...
        def __init__(self): ...
    class CompositeValidator:
        def __init__(self, string: typing.Union[java.lang.String, str], *validatable: 'ValidationFramework.Validatable'): ...
        def validateAll(self) -> 'ValidationFramework.ValidationResult': ...
        def validateAny(self) -> 'ValidationFramework.ValidationResult': ...
    class Validatable:
        def getValidationName(self) -> java.lang.String: ...
        def validate(self) -> 'ValidationFramework.ValidationResult': ...
    class ValidationBuilder:
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def addWarning(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'ValidationFramework.ValidationBuilder': ...
        def build(self) -> 'ValidationFramework.ValidationResult': ...
        def checkNotNull(self, object: typing.Any, string: typing.Union[java.lang.String, str]) -> 'ValidationFramework.ValidationBuilder': ...
        def checkRange(self, double: float, double2: float, double3: float, string: typing.Union[java.lang.String, str]) -> 'ValidationFramework.ValidationBuilder': ...
        def checkTrue(self, boolean: bool, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'ValidationFramework.ValidationBuilder': ...
    class ValidationContext:
        def __init__(self): ...
        def get(self, string: typing.Union[java.lang.String, str]) -> typing.Any: ...
        def getCheckedObjects(self) -> java.util.List[java.lang.String]: ...
        def hasBeenChecked(self, string: typing.Union[java.lang.String, str]) -> bool: ...
        def put(self, string: typing.Union[java.lang.String, str], object: typing.Any) -> None: ...
        def recordCheck(self, string: typing.Union[java.lang.String, str]) -> None: ...
    class ValidationError:
        def __init__(self, severity: 'ValidationFramework.ValidationError.Severity', string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
        def getCategory(self) -> java.lang.String: ...
        def getMessage(self) -> java.lang.String: ...
        def getRemediation(self) -> java.lang.String: ...
        def getSeverity(self) -> 'ValidationFramework.ValidationError.Severity': ...
        def toString(self) -> java.lang.String: ...
        class Severity(java.lang.Enum['ValidationFramework.ValidationError.Severity']):
            CRITICAL: typing.ClassVar['ValidationFramework.ValidationError.Severity'] = ...
            MAJOR: typing.ClassVar['ValidationFramework.ValidationError.Severity'] = ...
            MINOR: typing.ClassVar['ValidationFramework.ValidationError.Severity'] = ...
            _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
            @typing.overload
            @staticmethod
            def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
            @typing.overload
            @staticmethod
            def valueOf(string: typing.Union[java.lang.String, str]) -> 'ValidationFramework.ValidationError.Severity': ...
            @staticmethod
            def values() -> typing.MutableSequence['ValidationFramework.ValidationError.Severity']: ...
    class ValidationResult:
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def addError(self, validationError: 'ValidationFramework.ValidationError') -> None: ...
        def addWarning(self, validationWarning: 'ValidationFramework.ValidationWarning') -> None: ...
        def getCriticalErrors(self) -> java.util.List['ValidationFramework.ValidationError']: ...
        def getErrors(self) -> java.util.List['ValidationFramework.ValidationError']: ...
        def getErrorsSummary(self) -> java.lang.String: ...
        def getValidationTimeMs(self) -> int: ...
        def getWarnings(self) -> java.util.List['ValidationFramework.ValidationWarning']: ...
        def getWarningsSummary(self) -> java.lang.String: ...
        def isReady(self) -> bool: ...
        def toString(self) -> java.lang.String: ...
    class ValidationWarning:
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
        def getCategory(self) -> java.lang.String: ...
        def getMessage(self) -> java.lang.String: ...
        def getSuggestion(self) -> java.lang.String: ...
        def toString(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.integration")``.

    EquipmentValidator: typing.Type[EquipmentValidator]
    StreamValidator: typing.Type[StreamValidator]
    ThermoValidator: typing.Type[ThermoValidator]
    ValidationFramework: typing.Type[ValidationFramework]
