import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.process.util.report
import jneqsim.thermo.system
import typing

class Tank(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ): ...
    def addStream(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> None: ...
    def displayResult(self) -> None: ...
    def getEfficiency(self) -> float: ...
    def getGas(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getGasCarryunderFraction(self) -> float: ...
    def getGasOutStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getLiquid(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getLiquidCarryoverFraction(self) -> float: ...
    def getLiquidLevel(self) -> float: ...
    def getLiquidOutStream(
        self,
    ) -> jneqsim.process.equipment.stream.StreamInterface: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getVolume(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setEfficiency(self, double: float) -> None: ...
    def setGasCarryunderFraction(self, double: float) -> None: ...
    def setInletStream(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> None: ...
    def setLiquidCarryoverFraction(self, double: float) -> None: ...
    def setOutComposition(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> None: ...
    def setTempPres(self, double: float, double2: float) -> None: ...
    def setVolume(self, double: float) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(
        self, reportConfig: jneqsim.process.util.report.ReportConfig
    ) -> java.lang.String: ...

class VesselDepressurization(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ): ...
    def assessFlowAssuranceRisks(
        self,
    ) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def calculateRequiredOrificeDiameter(
        self, double: float, double2: float
    ) -> float: ...
    def clearHistory(self) -> None: ...
    @staticmethod
    def createTwoPhaseFluid(
        string: typing.Union[java.lang.String, str], double: float, double2: float
    ) -> jneqsim.thermo.system.SystemInterface: ...
    @staticmethod
    def createTwoPhaseFluidAtPressure(
        string: typing.Union[java.lang.String, str], double: float, double2: float
    ) -> jneqsim.thermo.system.SystemInterface: ...
    def exportToCSV(self) -> java.lang.String: ...
    def exportToJSON(self) -> java.lang.String: ...
    def getCO2FreezingSubcooling(self) -> float: ...
    @typing.overload
    def getCO2FreezingTemperature(self) -> float: ...
    @typing.overload
    def getCO2FreezingTemperature(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getDensity(self) -> float: ...
    def getDischargeRate(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getEnthalpy(self) -> float: ...
    def getEntropy(self) -> float: ...
    def getFireHeatInput(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getFlareHeaderMach(self, double: float) -> float: ...
    def getFlareHeaderVelocity(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getGasWallTemperature(self) -> float: ...
    def getGasWallTemperatureHistory(self) -> java.util.List[float]: ...
    @typing.overload
    def getHydrateFormationTemperature(self) -> float: ...
    @typing.overload
    def getHydrateFormationTemperature(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getHydrateSubcooling(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getInternalEnergy(self) -> float: ...
    def getLiquidLevel(self) -> float: ...
    def getLiquidLevelHistory(self) -> java.util.List[float]: ...
    def getLiquidWallTemperature(self) -> float: ...
    def getLiquidWallTemperatureHistory(self) -> java.util.List[float]: ...
    def getMass(self) -> float: ...
    def getMassHistory(self) -> java.util.List[float]: ...
    def getMaxHydrateSubcoolingDuringBlowdown(self) -> float: ...
    def getMinimumTemperatureReached(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getMinimumWallTemperatureReached(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getOutletLiquidFraction(self) -> float: ...
    def getOutletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getPeakDischargeRate(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getPeakOutletLiquidFraction(self) -> float: ...
    @typing.overload
    def getPressure(self) -> float: ...
    @typing.overload
    def getPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getPressureHistory(self) -> java.util.List[float]: ...
    @typing.overload
    def getTemperature(self) -> float: ...
    @typing.overload
    def getTemperature(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTemperatureHistory(self) -> java.util.List[float]: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getTimeHistory(self) -> java.util.List[float]: ...
    def getTimeToReachPressure(self, double: float) -> float: ...
    def getTotalMassDischarged(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getVaporFraction(self) -> float: ...
    def getVentTemperature(self) -> float: ...
    def getVolume(self) -> float: ...
    def getWallTemperature(self) -> float: ...
    def hasCO2FreezingRisk(self) -> bool: ...
    def hasHydrateRisk(self) -> bool: ...
    def hasLiquidRainout(self) -> bool: ...
    def isFireCase(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def runOrificeSensitivity(
        self,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        double2: float,
    ) -> typing.MutableSequence[float]: ...
    @typing.overload
    def runSimulation(
        self, double: float, double2: float
    ) -> "VesselDepressurization.SimulationResult": ...
    @typing.overload
    def runSimulation(
        self, double: float, double2: float, int: int
    ) -> "VesselDepressurization.SimulationResult": ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setAmbientTemperature(self, double: float) -> None: ...
    def setBackPressure(self, double: float) -> None: ...
    def setCalculationType(
        self, calculationType: "VesselDepressurization.CalculationType"
    ) -> None: ...
    def setDischargeCoefficient(self, double: float) -> None: ...
    def setExternalHeatTransferCoefficient(self, double: float) -> None: ...
    def setFireCase(self, boolean: bool) -> None: ...
    @typing.overload
    def setFireHeatFlux(self, double: float) -> None: ...
    @typing.overload
    def setFireHeatFlux(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setFixedQ(self, double: float) -> None: ...
    def setFixedU(self, double: float) -> None: ...
    def setFlowDirection(
        self, flowDirection: "VesselDepressurization.FlowDirection"
    ) -> None: ...
    def setHeatTransferType(
        self, heatTransferType: "VesselDepressurization.HeatTransferType"
    ) -> None: ...
    def setInitialLiquidLevel(self, double: float) -> None: ...
    def setInletStream(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> None: ...
    def setLinerMaterial(
        self, double: float, linerMaterial: "VesselDepressurization.LinerMaterial"
    ) -> None: ...
    def setLinerProperties(
        self, double: float, double2: float, double3: float, double4: float
    ) -> None: ...
    def setOrificeDiameter(self, double: float) -> None: ...
    def setTwoPhaseHeatTransfer(self, boolean: bool) -> None: ...
    def setValveOpeningTime(self, double: float) -> None: ...
    def setVesselGeometry(
        self,
        double: float,
        double2: float,
        vesselOrientation: "VesselDepressurization.VesselOrientation",
    ) -> None: ...
    def setVesselMaterial(
        self, double: float, vesselMaterial: "VesselDepressurization.VesselMaterial"
    ) -> None: ...
    def setVesselProperties(
        self, double: float, double2: float, double3: float, double4: float
    ) -> None: ...
    def setVolume(self, double: float) -> None: ...
    def setWettedSurfaceFraction(self, double: float) -> None: ...
    def validate(self) -> None: ...
    def validateWithWarnings(self) -> java.util.List[java.lang.String]: ...

    class CalculationType(java.lang.Enum["VesselDepressurization.CalculationType"]):
        ISOTHERMAL: typing.ClassVar["VesselDepressurization.CalculationType"] = ...
        ISENTHALPIC: typing.ClassVar["VesselDepressurization.CalculationType"] = ...
        ISENTROPIC: typing.ClassVar["VesselDepressurization.CalculationType"] = ...
        ISENERGETIC: typing.ClassVar["VesselDepressurization.CalculationType"] = ...
        ENERGY_BALANCE: typing.ClassVar["VesselDepressurization.CalculationType"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "VesselDepressurization.CalculationType": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["VesselDepressurization.CalculationType"]
        ): ...

    class FlowDirection(java.lang.Enum["VesselDepressurization.FlowDirection"]):
        DISCHARGE: typing.ClassVar["VesselDepressurization.FlowDirection"] = ...
        FILLING: typing.ClassVar["VesselDepressurization.FlowDirection"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "VesselDepressurization.FlowDirection": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["VesselDepressurization.FlowDirection"]
        ): ...

    class HeatTransferType(java.lang.Enum["VesselDepressurization.HeatTransferType"]):
        ADIABATIC: typing.ClassVar["VesselDepressurization.HeatTransferType"] = ...
        FIXED_U: typing.ClassVar["VesselDepressurization.HeatTransferType"] = ...
        FIXED_Q: typing.ClassVar["VesselDepressurization.HeatTransferType"] = ...
        CALCULATED: typing.ClassVar["VesselDepressurization.HeatTransferType"] = ...
        TRANSIENT_WALL: typing.ClassVar["VesselDepressurization.HeatTransferType"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "VesselDepressurization.HeatTransferType": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["VesselDepressurization.HeatTransferType"]
        ): ...

    class LinerMaterial(java.lang.Enum["VesselDepressurization.LinerMaterial"]):
        HDPE: typing.ClassVar["VesselDepressurization.LinerMaterial"] = ...
        NYLON: typing.ClassVar["VesselDepressurization.LinerMaterial"] = ...
        ALUMINUM: typing.ClassVar["VesselDepressurization.LinerMaterial"] = ...
        def getDensity(self) -> float: ...
        def getHeatCapacity(self) -> float: ...
        def getThermalConductivity(self) -> float: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "VesselDepressurization.LinerMaterial": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["VesselDepressurization.LinerMaterial"]
        ): ...

    class SimulationResult:
        def getEndTime(self) -> float: ...
        def getFinalPressure(self) -> float: ...
        def getFinalTemperature(self) -> float: ...
        def getGasWallTemperature(self) -> java.util.List[float]: ...
        def getInitialPressure(self) -> float: ...
        def getInitialTemperature(self) -> float: ...
        def getLiquidLevel(self) -> java.util.List[float]: ...
        def getLiquidWallTemperature(self) -> java.util.List[float]: ...
        def getMass(self) -> java.util.List[float]: ...
        def getMassDischarged(self) -> float: ...
        def getMassDischargedFraction(self) -> float: ...
        def getMassFlowRate(self) -> java.util.List[float]: ...
        def getMinTemperature(self) -> float: ...
        def getMinWallTemperature(self) -> float: ...
        def getPressure(self) -> java.util.List[float]: ...
        def getTemperature(self) -> java.util.List[float]: ...
        def getTime(self) -> java.util.List[float]: ...
        def getTimeStep(self) -> float: ...
        def getWallTemperature(self) -> java.util.List[float]: ...
        def size(self) -> int: ...

    class VesselMaterial(java.lang.Enum["VesselDepressurization.VesselMaterial"]):
        CARBON_STEEL: typing.ClassVar["VesselDepressurization.VesselMaterial"] = ...
        STAINLESS_304: typing.ClassVar["VesselDepressurization.VesselMaterial"] = ...
        STAINLESS_316: typing.ClassVar["VesselDepressurization.VesselMaterial"] = ...
        DUPLEX_22CR: typing.ClassVar["VesselDepressurization.VesselMaterial"] = ...
        ALUMINUM_6061: typing.ClassVar["VesselDepressurization.VesselMaterial"] = ...
        TITANIUM_GR2: typing.ClassVar["VesselDepressurization.VesselMaterial"] = ...
        CFRP: typing.ClassVar["VesselDepressurization.VesselMaterial"] = ...
        FIBERGLASS: typing.ClassVar["VesselDepressurization.VesselMaterial"] = ...
        def getDensity(self) -> float: ...
        def getHeatCapacity(self) -> float: ...
        def getThermalConductivity(self) -> float: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "VesselDepressurization.VesselMaterial": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["VesselDepressurization.VesselMaterial"]
        ): ...

    class VesselOrientation(java.lang.Enum["VesselDepressurization.VesselOrientation"]):
        VERTICAL: typing.ClassVar["VesselDepressurization.VesselOrientation"] = ...
        HORIZONTAL: typing.ClassVar["VesselDepressurization.VesselOrientation"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "VesselDepressurization.VesselOrientation": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["VesselDepressurization.VesselOrientation"]
        ): ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.tank")``.

    Tank: typing.Type[Tank]
    VesselDepressurization: typing.Type[VesselDepressurization]
