
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.process.util.report
import jneqsim.thermo.system
import typing



class Tank(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def addStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def displayResult(self) -> None: ...
    def getEfficiency(self) -> float: ...
    def getGas(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getGasCarryunderFraction(self) -> float: ...
    def getGasOutStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getLiquid(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getLiquidCarryoverFraction(self) -> float: ...
    def getLiquidLevel(self) -> float: ...
    def getLiquidOutStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getVolume(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setEfficiency(self, double: float) -> None: ...
    def setGasCarryunderFraction(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setLiquidCarryoverFraction(self, double: float) -> None: ...
    def setOutComposition(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    def setTempPres(self, double: float, double2: float) -> None: ...
    def setVolume(self, double: float) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.tank")``.

    Tank: typing.Type[Tank]
