
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process
import jneqsim.process.processmodel
import typing



class DynamicActivationResolver:
    @staticmethod
    def diagnostic(processElementInterface: jneqsim.process.ProcessElementInterface) -> java.lang.String: ...
    @staticmethod
    def resolve(processElementInterface: jneqsim.process.ProcessElementInterface) -> 'DynamicActivationStatus': ...

class DynamicActivationStatus(java.lang.Enum['DynamicActivationStatus']):
    NOT_APPLICABLE: typing.ClassVar['DynamicActivationStatus'] = ...
    ACTIVE: typing.ClassVar['DynamicActivationStatus'] = ...
    INACTIVE: typing.ClassVar['DynamicActivationStatus'] = ...
    INCOMPLETE_CONFIGURATION: typing.ClassVar['DynamicActivationStatus'] = ...
    UNVERIFIED: typing.ClassVar['DynamicActivationStatus'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'DynamicActivationStatus': ...
    @staticmethod
    def values() -> typing.MutableSequence['DynamicActivationStatus']: ...

class DynamicCapability(java.lang.Enum['DynamicCapability']):
    ALGEBRAIC: typing.ClassVar['DynamicCapability'] = ...
    DYNAMIC_LUMPED: typing.ClassVar['DynamicCapability'] = ...
    DYNAMIC_DISTRIBUTED: typing.ClassVar['DynamicCapability'] = ...
    BOUNDARY_DYNAMIC: typing.ClassVar['DynamicCapability'] = ...
    CONTROL_DYNAMIC: typing.ClassVar['DynamicCapability'] = ...
    UNCLASSIFIED_DYNAMIC: typing.ClassVar['DynamicCapability'] = ...
    UNSUPPORTED_DYNAMIC: typing.ClassVar['DynamicCapability'] = ...
    def canParticipateInTransientStudy(self) -> bool: ...
    def hasExplicitDynamicState(self) -> bool: ...
    def isAudited(self) -> bool: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'DynamicCapability': ...
    @staticmethod
    def values() -> typing.MutableSequence['DynamicCapability']: ...

class DynamicCapabilityReport(java.io.Serializable):
    def assertStrictTransientReady(self) -> None: ...
    @typing.overload
    @staticmethod
    def from_(processModel: jneqsim.process.processmodel.ProcessModel) -> 'DynamicCapabilityReport': ...
    @typing.overload
    @staticmethod
    def from_(processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'DynamicCapabilityReport': ...
    def getActivationCounts(self) -> java.util.Map[DynamicActivationStatus, int]: ...
    def getBlockingIssues(self) -> java.util.List[java.lang.String]: ...
    def getCapabilityCounts(self) -> java.util.Map[DynamicCapability, int]: ...
    def getEntries(self) -> java.util.List['DynamicCapabilityReport.Entry']: ...
    def getExecutionIssues(self) -> java.util.List[java.lang.String]: ...
    def getInactiveAuditedDynamicElements(self) -> java.util.List[java.lang.String]: ...
    def getReviewItems(self) -> java.util.List[java.lang.String]: ...
    def getSchemaVersion(self) -> java.lang.String: ...
    def getStrictPreflightIssues(self) -> java.util.List[java.lang.String]: ...
    def getUnverifiedActivationElements(self) -> java.util.List[java.lang.String]: ...
    def hasBlockingIssues(self) -> bool: ...
    def isFullyAudited(self) -> bool: ...
    def isStrictPreflightReady(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    class Entry(java.io.Serializable):
        def getActivationDiagnostic(self) -> java.lang.String: ...
        def getActivationStatus(self) -> DynamicActivationStatus: ...
        def getAreaName(self) -> java.lang.String: ...
        def getCalculateSteadyState(self) -> bool: ...
        def getCapability(self) -> DynamicCapability: ...
        def getCategory(self) -> java.lang.String: ...
        def getClassName(self) -> java.lang.String: ...
        def getContainerPath(self) -> java.lang.String: ...
        def getName(self) -> java.lang.String: ...
        def getQualifiedName(self) -> java.lang.String: ...
        def hasInactiveAuditedDynamicState(self) -> bool: ...
        def hasIncompleteDynamicActivation(self) -> bool: ...
        def hasUnsupportedDynamicConfiguration(self) -> bool: ...
        def isDynamicModeRequested(self) -> bool: ...
        def requiresCapabilityReview(self) -> bool: ...

class DynamicCapabilityResolver:
    @staticmethod
    def resolve(processElementInterface: jneqsim.process.ProcessElementInterface) -> DynamicCapability: ...

class EventScheduler(java.io.Serializable):
    def __init__(self): ...
    def clear(self) -> None: ...
    def fireDueEvents(self, double: float) -> int: ...
    def getDueEvents(self, double: float) -> java.util.List['EventScheduler.ScheduledEvent']: ...
    def getFiredEvents(self) -> java.util.List['EventScheduler.ScheduledEvent']: ...
    def getNextEventTime(self) -> float: ...
    def getPendingEvents(self) -> java.util.List['EventScheduler.ScheduledEvent']: ...
    def restore(self, snapshot: 'EventScheduler.Snapshot') -> None: ...
    def scheduleEvent(self, double: float, string: typing.Union[java.lang.String, str], runnable: typing.Union[java.lang.Runnable, typing.Callable]) -> 'EventScheduler.ScheduledEvent': ...
    def scheduleTransactionalEvent(self, double: float, string: typing.Union[java.lang.String, str], runnable: typing.Union[java.lang.Runnable, typing.Callable], *string2: typing.Union[java.lang.String, str]) -> 'EventScheduler.ScheduledEvent': ...
    def snapshot(self) -> 'EventScheduler.Snapshot': ...
    class ScheduledEvent(java.io.Serializable, java.lang.Comparable['EventScheduler.ScheduledEvent']):
        def __init__(self, double: float, string: typing.Union[java.lang.String, str], runnable: typing.Union[java.lang.Runnable, typing.Callable]): ...
        def compareTo(self, scheduledEvent: 'EventScheduler.ScheduledEvent') -> int: ...
        def getAction(self) -> java.lang.Runnable: ...
        def getLabel(self) -> java.lang.String: ...
        def getTime(self) -> float: ...
        def getTransientStateIdentities(self) -> java.util.List[java.lang.String]: ...
        def hasDeclaredTransientStateScope(self) -> bool: ...
    class Snapshot(java.io.Serializable):
        def getFiredEventCount(self) -> int: ...
        def getPendingEventCount(self) -> int: ...

class IntegratorStrategy(java.io.Serializable):
    def getName(self) -> java.lang.String: ...
    def step(self, double: float, double2: float, slope: typing.Union['IntegratorStrategy.Slope', typing.Callable], double3: float) -> float: ...
    class Slope(java.io.Serializable):
        def dxdt(self, double: float, double2: float) -> float: ...

_TransientStateParticipant__S = typing.TypeVar('_TransientStateParticipant__S', bound=java.io.Serializable)  # <S>
class TransientStateParticipant(jneqsim.process.ProcessElementInterface, typing.Generic[_TransientStateParticipant__S]):
    def captureTransientState(self) -> _TransientStateParticipant__S: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, s2: _TransientStateParticipant__S) -> None: ...

class TransientStepIdentifier:
    @staticmethod
    def deterministicEvaluation(uUID: java.util.UUID, long: int) -> java.util.UUID: ...
    @staticmethod
    def deterministicPhysicalStep(string: typing.Union[java.lang.String, str], long: int) -> java.util.UUID: ...
    @staticmethod
    def randomPhysicalStep() -> java.util.UUID: ...

class TransientStepTransaction(java.lang.AutoCloseable):
    def close(self) -> None: ...
    def commit(self) -> None: ...
    def getStatus(self) -> 'TransientStepTransaction.Status': ...
    def isOpen(self) -> bool: ...
    def prepareCommit(self) -> None: ...
    def rollback(self) -> None: ...
    class Status(java.lang.Enum['TransientStepTransaction.Status']):
        OPEN: typing.ClassVar['TransientStepTransaction.Status'] = ...
        COMMITTED: typing.ClassVar['TransientStepTransaction.Status'] = ...
        ROLLED_BACK: typing.ClassVar['TransientStepTransaction.Status'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TransientStepTransaction.Status': ...
        @staticmethod
        def values() -> typing.MutableSequence['TransientStepTransaction.Status']: ...

class TransientTransactionCoverage(java.io.Serializable):
    def __init__(self, int: int, int2: int, list: java.util.List[typing.Union[java.lang.String, str]]): ...
    def assertComplete(self) -> None: ...
    def getBlockingIssues(self) -> java.util.List[java.lang.String]: ...
    def getParticipantCount(self) -> int: ...
    def getProcessElementCount(self) -> int: ...
    def isComplete(self) -> bool: ...

class AdaptiveRK45Integrator(IntegratorStrategy):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float, double2: float, int: int): ...
    def getAbsTol(self) -> float: ...
    def getAbsoluteTolerance(self) -> float: ...
    def getLastSubSteps(self) -> int: ...
    def getName(self) -> java.lang.String: ...
    def getRelTol(self) -> float: ...
    def getRelativeTolerance(self) -> float: ...
    def setAbsoluteTolerance(self, double: float) -> 'AdaptiveRK45Integrator': ...
    def setMaxSubSteps(self, int: int) -> 'AdaptiveRK45Integrator': ...
    def setRelativeTolerance(self, double: float) -> 'AdaptiveRK45Integrator': ...
    def step(self, double: float, double2: float, slope: typing.Union[IntegratorStrategy.Slope, typing.Callable], double3: float) -> float: ...

class BDFIntegrator(IntegratorStrategy):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float, int: int, double2: float): ...
    def getLastNewtonIterations(self) -> int: ...
    def getLastResidual(self) -> float: ...
    def getMaxIterations(self) -> int: ...
    def getName(self) -> java.lang.String: ...
    def getTolerance(self) -> float: ...
    def isExplicitEulerFallbackEnabled(self) -> bool: ...
    def lastStepConverged(self) -> bool: ...
    def lastStepFellBack(self) -> bool: ...
    def setExplicitEulerFallbackEnabled(self, boolean: bool) -> None: ...
    def step(self, double: float, double2: float, slope: typing.Union[IntegratorStrategy.Slope, typing.Callable], double3: float) -> float: ...

class ExplicitEulerIntegrator(IntegratorStrategy):
    def __init__(self): ...
    def getName(self) -> java.lang.String: ...
    def step(self, double: float, double2: float, slope: typing.Union[IntegratorStrategy.Slope, typing.Callable], double3: float) -> float: ...

class RK4Integrator(IntegratorStrategy):
    def __init__(self): ...
    def getName(self) -> java.lang.String: ...
    def step(self, double: float, double2: float, slope: typing.Union[IntegratorStrategy.Slope, typing.Callable], double3: float) -> float: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.dynamics")``.

    AdaptiveRK45Integrator: typing.Type[AdaptiveRK45Integrator]
    BDFIntegrator: typing.Type[BDFIntegrator]
    DynamicActivationResolver: typing.Type[DynamicActivationResolver]
    DynamicActivationStatus: typing.Type[DynamicActivationStatus]
    DynamicCapability: typing.Type[DynamicCapability]
    DynamicCapabilityReport: typing.Type[DynamicCapabilityReport]
    DynamicCapabilityResolver: typing.Type[DynamicCapabilityResolver]
    EventScheduler: typing.Type[EventScheduler]
    ExplicitEulerIntegrator: typing.Type[ExplicitEulerIntegrator]
    IntegratorStrategy: typing.Type[IntegratorStrategy]
    RK4Integrator: typing.Type[RK4Integrator]
    TransientStateParticipant: typing.Type[TransientStateParticipant]
    TransientStepIdentifier: typing.Type[TransientStepIdentifier]
    TransientStepTransaction: typing.Type[TransientStepTransaction]
    TransientTransactionCoverage: typing.Type[TransientTransactionCoverage]
