
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.thermo.system
import typing



class SettleOutPressureAnalyzer(java.io.Serializable):
    def __init__(self): ...
    def addVolume(self, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], double2: float, string3: typing.Union[java.lang.String, str], double3: float, string4: typing.Union[java.lang.String, str]) -> 'SettleOutPressureAnalyzer': ...
    def analyze(self) -> 'SettleOutPressureResult': ...
    def setGas(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> 'SettleOutPressureAnalyzer': ...
    def setProtectedPressureRating(self, double: float, string: typing.Union[java.lang.String, str]) -> 'SettleOutPressureAnalyzer': ...
    def setSettleOutTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> 'SettleOutPressureAnalyzer': ...
    class SettleOutVerdict(java.lang.Enum['SettleOutPressureAnalyzer.SettleOutVerdict']):
        NO_RATING: typing.ClassVar['SettleOutPressureAnalyzer.SettleOutVerdict'] = ...
        WITHIN_RATING: typing.ClassVar['SettleOutPressureAnalyzer.SettleOutVerdict'] = ...
        EXCEEDS_RATING: typing.ClassVar['SettleOutPressureAnalyzer.SettleOutVerdict'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SettleOutPressureAnalyzer.SettleOutVerdict': ...
        @staticmethod
        def values() -> typing.MutableSequence['SettleOutPressureAnalyzer.SettleOutVerdict']: ...

class SettleOutPressureResult(java.io.Serializable):
    def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, boolean: bool, double9: float, boolean2: bool, settleOutVerdict: SettleOutPressureAnalyzer.SettleOutVerdict, list: java.util.List['SettleOutPressureResult.CompartmentResult'], list2: java.util.List[typing.Union[java.lang.String, str]]): ...
    def getCompartments(self) -> java.util.List['SettleOutPressureResult.CompartmentResult']: ...
    def getMarginToRatingBar(self) -> float: ...
    def getMaxCompartmentPressureBara(self) -> float: ...
    def getMinCompartmentPressureBara(self) -> float: ...
    def getProtectedRatingBara(self) -> float: ...
    def getSettleOutPressureBara(self) -> float: ...
    def getSettleOutTemperatureK(self) -> float: ...
    def getSettleOutZFactor(self) -> float: ...
    def getTotalMoles(self) -> float: ...
    def getTotalVolumeM3(self) -> float: ...
    def getVerdict(self) -> SettleOutPressureAnalyzer.SettleOutVerdict: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isExceedsRating(self) -> bool: ...
    def isRatingProvided(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    class CompartmentResult(java.io.Serializable):
        name: java.lang.String = ...
        volumeM3: float = ...
        pressureBara: float = ...
        temperatureK: float = ...
        zFactor: float = ...
        moles: float = ...
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float): ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.settleout")``.

    SettleOutPressureAnalyzer: typing.Type[SettleOutPressureAnalyzer]
    SettleOutPressureResult: typing.Type[SettleOutPressureResult]
