
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.process.equipment.compressor
import jneqsim.process.equipment.distillation
import jneqsim.process.equipment.ejector
import jneqsim.process.equipment.expander
import jneqsim.process.equipment.filter
import jneqsim.process.equipment.flare
import jneqsim.process.equipment.heatexchanger
import jneqsim.process.equipment.manifold
import jneqsim.process.equipment.mixer
import jneqsim.process.equipment.pipeline
import jneqsim.process.equipment.pump
import jneqsim.process.equipment.reactor
import jneqsim.process.equipment.separator
import jneqsim.process.equipment.splitter
import jneqsim.process.equipment.stream
import jneqsim.process.equipment.tank
import jneqsim.process.equipment.util
import jneqsim.process.equipment.valve
import jneqsim.process.measurementdevice
import jneqsim.process.util.report
import jneqsim.thermo.system
import typing



class BaseResponse:
    tagName: java.lang.String = ...
    name: java.lang.String = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    @typing.overload
    def __init__(self, measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface): ...
    def applyConfig(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> None: ...

class FluidComponentResponse:
    name: java.lang.String = ...
    properties: java.util.HashMap = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def print_(self) -> None: ...

class FluidResponse:
    name: java.lang.String = ...
    properties: java.util.HashMap = ...
    composition: java.util.HashMap = ...
    conditions: java.util.HashMap = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def print_(self) -> None: ...

class KPIDashboard:
    def __init__(self): ...
    def addScenario(self, string: typing.Union[java.lang.String, str], scenarioKPI: 'ScenarioKPI') -> None: ...
    def clear(self) -> None: ...
    def getScenarioCount(self) -> int: ...
    def printDashboard(self) -> None: ...

class ScenarioKPI:
    def __init__(self): ...
    @staticmethod
    def builder() -> 'ScenarioKPI.Builder': ...
    def calculateEnvironmentalScore(self) -> float: ...
    def calculateOverallScore(self) -> float: ...
    def calculateProcessScore(self) -> float: ...
    def calculateSafetyScore(self) -> float: ...
    def getAverageFlowRate(self) -> float: ...
    def getCo2Emissions(self) -> float: ...
    def getEnergyConsumption(self) -> float: ...
    def getErrorCount(self) -> int: ...
    def getFinalStatus(self) -> java.lang.String: ...
    def getFlareGasVolume(self) -> float: ...
    def getFlaringDuration(self) -> float: ...
    def getLostProductionValue(self) -> float: ...
    def getOperatingCost(self) -> float: ...
    def getPeakPressure(self) -> float: ...
    def getPeakTemperature(self) -> float: ...
    def getProductionLoss(self) -> float: ...
    def getRecoveryTime(self) -> float: ...
    def getSafetyMarginToMAWP(self) -> float: ...
    def getSafetySystemActuations(self) -> int: ...
    def getSimulationDuration(self) -> float: ...
    def getSteadyStateDeviation(self) -> float: ...
    def getTimeToESDActivation(self) -> float: ...
    def getVentedMass(self) -> float: ...
    def getWarningCount(self) -> int: ...
    def isHippsTripped(self) -> bool: ...
    def isPsvActivated(self) -> bool: ...
    class Builder:
        def __init__(self): ...
        def averageFlowRate(self, double: float) -> 'ScenarioKPI.Builder': ...
        def build(self) -> 'ScenarioKPI': ...
        def co2Emissions(self, double: float) -> 'ScenarioKPI.Builder': ...
        def energyConsumption(self, double: float) -> 'ScenarioKPI.Builder': ...
        def errorCount(self, int: int) -> 'ScenarioKPI.Builder': ...
        def finalStatus(self, string: typing.Union[java.lang.String, str]) -> 'ScenarioKPI.Builder': ...
        def flareGasVolume(self, double: float) -> 'ScenarioKPI.Builder': ...
        def flaringDuration(self, double: float) -> 'ScenarioKPI.Builder': ...
        def hippsTripped(self, boolean: bool) -> 'ScenarioKPI.Builder': ...
        def lostProductionValue(self, double: float) -> 'ScenarioKPI.Builder': ...
        def operatingCost(self, double: float) -> 'ScenarioKPI.Builder': ...
        def peakPressure(self, double: float) -> 'ScenarioKPI.Builder': ...
        def peakTemperature(self, double: float) -> 'ScenarioKPI.Builder': ...
        def productionLoss(self, double: float) -> 'ScenarioKPI.Builder': ...
        def psvActivated(self, boolean: bool) -> 'ScenarioKPI.Builder': ...
        def recoveryTime(self, double: float) -> 'ScenarioKPI.Builder': ...
        def safetyMarginToMAWP(self, double: float) -> 'ScenarioKPI.Builder': ...
        def safetySystemActuations(self, int: int) -> 'ScenarioKPI.Builder': ...
        def simulationDuration(self, double: float) -> 'ScenarioKPI.Builder': ...
        def steadyStateDeviation(self, double: float) -> 'ScenarioKPI.Builder': ...
        def timeToESDActivation(self, double: float) -> 'ScenarioKPI.Builder': ...
        def ventedMass(self, double: float) -> 'ScenarioKPI.Builder': ...
        def warningCount(self, int: int) -> 'ScenarioKPI.Builder': ...

class Value:
    value: java.lang.String = ...
    unit: java.lang.String = ...
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...

class WellAllocatorResponse:
    name: java.lang.String = ...
    data: java.util.HashMap = ...
    def __init__(self, wellAllocator: jneqsim.process.measurementdevice.WellAllocator): ...

class ComponentSplitterResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, componentSplitter: jneqsim.process.equipment.splitter.ComponentSplitter): ...

class CompressorResponse(BaseResponse):
    suctionTemperature: float = ...
    dischargeTemperature: float = ...
    suctionPressure: float = ...
    dischargePressure: float = ...
    polytropicHead: float = ...
    polytropicEfficiency: float = ...
    power: float = ...
    suctionVolumeFlow: float = ...
    internalVolumeFlow: float = ...
    dischargeVolumeFlow: float = ...
    molarMass: float = ...
    suctionMassDensity: float = ...
    dischargeMassDensity: float = ...
    massflow: float = ...
    stdFlow: float = ...
    speed: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, compressor: jneqsim.process.equipment.compressor.Compressor): ...
    def applyConfig(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> None: ...

class DistillationColumnResponse(BaseResponse):
    massBalanceError: float = ...
    trayTemperature: typing.MutableSequence[float] = ...
    trayPressure: typing.MutableSequence[float] = ...
    numberOfTrays: int = ...
    trayVaporFlowRate: typing.MutableSequence[float] = ...
    trayLiquidFlowRate: typing.MutableSequence[float] = ...
    trayFeedFlow: typing.MutableSequence[float] = ...
    trayMassBalance: typing.MutableSequence[float] = ...
    def __init__(self, distillationColumn: jneqsim.process.equipment.distillation.DistillationColumn): ...

class EjectorResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, ejector: jneqsim.process.equipment.ejector.Ejector): ...

class FilterResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, filter: jneqsim.process.equipment.filter.Filter): ...

class FlareResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, flare: jneqsim.process.equipment.flare.Flare): ...

class FurnaceBurnerResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, furnaceBurner: jneqsim.process.equipment.reactor.FurnaceBurner): ...

class HXResponse(BaseResponse):
    feedTemperature1: float = ...
    dischargeTemperature1: float = ...
    HXthermalEfectiveness: float = ...
    feedTemperature2: float = ...
    dischargeTemperature2: float = ...
    dutyBalance: float = ...
    duty: float = ...
    UAvalue: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, heatExchanger: jneqsim.process.equipment.heatexchanger.HeatExchanger): ...

class HeaterResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, heater: jneqsim.process.equipment.heatexchanger.Heater): ...

class MPMResponse(BaseResponse):
    massFLow: float = ...
    GOR: float = ...
    GOR_std: float = ...
    gasDensity: float = ...
    oilDensity: float = ...
    waterDensity: float = ...
    def __init__(self, multiPhaseMeter: jneqsim.process.measurementdevice.MultiPhaseMeter): ...

class ManifoldResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, manifold: jneqsim.process.equipment.manifold.Manifold): ...

class MixerResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, mixer: jneqsim.process.equipment.mixer.Mixer): ...

class MultiStreamHeatExchanger2Response(BaseResponse):
    data: java.util.HashMap = ...
    temperatureApproach: float = ...
    compositeCurveResults: java.util.Map = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, multiStreamHeatExchanger2: jneqsim.process.equipment.heatexchanger.MultiStreamHeatExchanger2): ...

class MultiStreamHeatExchangerResponse(BaseResponse):
    data: java.util.HashMap = ...
    feedTemperature: typing.MutableSequence[float] = ...
    dischargeTemperature: typing.MutableSequence[float] = ...
    duty: typing.MutableSequence[float] = ...
    flowRate: typing.MutableSequence[float] = ...
    def __init__(self, multiStreamHeatExchanger: jneqsim.process.equipment.heatexchanger.MultiStreamHeatExchanger): ...

class PipeBeggsBrillsResponse(BaseResponse):
    inletPressure: float = ...
    outletPressure: float = ...
    inletTemperature: float = ...
    outletTemperature: float = ...
    inletDensity: float = ...
    outletDensity: float = ...
    inletVolumeFlow: float = ...
    outletVolumeFlow: float = ...
    inletMassFlow: float = ...
    outletMassFlow: float = ...
    def __init__(self, pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills): ...

class PipelineResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, pipeline: jneqsim.process.equipment.pipeline.Pipeline): ...

class PumpResponse(BaseResponse):
    data: java.util.HashMap = ...
    suctionTemperature: float = ...
    dischargeTemperature: float = ...
    suctionPressure: float = ...
    dischargePressure: float = ...
    power: float = ...
    duty: float = ...
    suctionVolumeFlow: float = ...
    internalVolumeFlow: float = ...
    dischargeVolumeFlow: float = ...
    molarMass: float = ...
    suctionMassDensity: float = ...
    dischargeMassDensity: float = ...
    massflow: float = ...
    speed: int = ...
    def __init__(self, pump: jneqsim.process.equipment.pump.Pump): ...

class RecycleResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, recycle: jneqsim.process.equipment.util.Recycle): ...

class SeparatorResponse(BaseResponse):
    gasLoadFactor: float = ...
    feed: 'StreamResponse' = ...
    gas: 'StreamResponse' = ...
    liquid: 'StreamResponse' = ...
    oil: 'StreamResponse' = ...
    water: 'StreamResponse' = ...
    @typing.overload
    def __init__(self, separator: jneqsim.process.equipment.separator.Separator): ...
    @typing.overload
    def __init__(self, threePhaseSeparator: jneqsim.process.equipment.separator.ThreePhaseSeparator): ...

class SplitterResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, splitter: jneqsim.process.equipment.splitter.Splitter): ...

class StreamResponse(BaseResponse):
    properties: java.util.HashMap = ...
    conditions: java.util.HashMap = ...
    composition: java.util.HashMap = ...
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def applyConfig(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> None: ...
    def print_(self) -> None: ...

class TankResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, tank: jneqsim.process.equipment.tank.Tank): ...

class ThreePhaseSeparatorResponse(BaseResponse):
    gasLoadFactor: float = ...
    massflow: float = ...
    gasFluid: FluidResponse = ...
    oilFluid: FluidResponse = ...
    @typing.overload
    def __init__(self, separator: jneqsim.process.equipment.separator.Separator): ...
    @typing.overload
    def __init__(self, threePhaseSeparator: jneqsim.process.equipment.separator.ThreePhaseSeparator): ...

class TurboExpanderCompressorResponse(BaseResponse):
    def __init__(self, turboExpanderCompressor: jneqsim.process.equipment.expander.TurboExpanderCompressor): ...

class ValveResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, valveInterface: jneqsim.process.equipment.valve.ValveInterface): ...
    def print_(self) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.util.monitor")``.

    BaseResponse: typing.Type[BaseResponse]
    ComponentSplitterResponse: typing.Type[ComponentSplitterResponse]
    CompressorResponse: typing.Type[CompressorResponse]
    DistillationColumnResponse: typing.Type[DistillationColumnResponse]
    EjectorResponse: typing.Type[EjectorResponse]
    FilterResponse: typing.Type[FilterResponse]
    FlareResponse: typing.Type[FlareResponse]
    FluidComponentResponse: typing.Type[FluidComponentResponse]
    FluidResponse: typing.Type[FluidResponse]
    FurnaceBurnerResponse: typing.Type[FurnaceBurnerResponse]
    HXResponse: typing.Type[HXResponse]
    HeaterResponse: typing.Type[HeaterResponse]
    KPIDashboard: typing.Type[KPIDashboard]
    MPMResponse: typing.Type[MPMResponse]
    ManifoldResponse: typing.Type[ManifoldResponse]
    MixerResponse: typing.Type[MixerResponse]
    MultiStreamHeatExchanger2Response: typing.Type[MultiStreamHeatExchanger2Response]
    MultiStreamHeatExchangerResponse: typing.Type[MultiStreamHeatExchangerResponse]
    PipeBeggsBrillsResponse: typing.Type[PipeBeggsBrillsResponse]
    PipelineResponse: typing.Type[PipelineResponse]
    PumpResponse: typing.Type[PumpResponse]
    RecycleResponse: typing.Type[RecycleResponse]
    ScenarioKPI: typing.Type[ScenarioKPI]
    SeparatorResponse: typing.Type[SeparatorResponse]
    SplitterResponse: typing.Type[SplitterResponse]
    StreamResponse: typing.Type[StreamResponse]
    TankResponse: typing.Type[TankResponse]
    ThreePhaseSeparatorResponse: typing.Type[ThreePhaseSeparatorResponse]
    TurboExpanderCompressorResponse: typing.Type[TurboExpanderCompressorResponse]
    Value: typing.Type[Value]
    ValveResponse: typing.Type[ValveResponse]
    WellAllocatorResponse: typing.Type[WellAllocatorResponse]
