
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.process.mechanicaldesign.compressor
import jneqsim.process.ml
import jneqsim.process.util.report
import jneqsim.thermo.system
import typing



class AntiSurge(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, controlStrategy: 'AntiSurge.ControlStrategy'): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getControlStrategy(self) -> 'AntiSurge.ControlStrategy': ...
    def getCurrentSurgeFraction(self) -> float: ...
    def getHotGasBypassFlow(self) -> float: ...
    def getMaximumRecycleFlow(self) -> float: ...
    def getMinimumRecycleFlow(self) -> float: ...
    def getPredictiveHorizon(self) -> float: ...
    def getRecycleFlow(self, double: float) -> float: ...
    def getSummary(self) -> java.lang.String: ...
    def getSurgeApproachRate(self) -> float: ...
    def getSurgeControlFactor(self) -> float: ...
    def getSurgeControlLineOffset(self) -> float: ...
    def getSurgeCycleCount(self) -> int: ...
    def getSurgeWarningMargin(self) -> float: ...
    def getTargetValvePosition(self) -> float: ...
    def getValvePosition(self) -> float: ...
    def getValveRateLimit(self) -> float: ...
    def getValveResponseTime(self) -> float: ...
    def hashCode(self) -> int: ...
    def isActive(self) -> bool: ...
    def isSurge(self) -> bool: ...
    def isUseHotGasBypass(self) -> bool: ...
    def resetPID(self) -> None: ...
    def resetSurgeCycleCount(self) -> None: ...
    def setActive(self, boolean: bool) -> None: ...
    def setControlStrategy(self, controlStrategy: 'AntiSurge.ControlStrategy') -> None: ...
    def setCurrentSurgeFraction(self, double: float) -> None: ...
    def setHotGasBypassFlow(self, double: float) -> None: ...
    def setMaxSurgeCyclesBeforeTrip(self, int: int) -> None: ...
    def setMaximumRecycleFlow(self, double: float) -> None: ...
    def setMinimumRecycleFlow(self, double: float) -> None: ...
    def setPIDParameters(self, double: float, double2: float, double3: float) -> None: ...
    def setPIDSetpoint(self, double: float) -> None: ...
    def setPredictiveHorizon(self, double: float) -> None: ...
    def setSurge(self, boolean: bool) -> None: ...
    def setSurgeControlFactor(self, double: float) -> None: ...
    def setSurgeControlLineOffset(self, double: float) -> None: ...
    def setSurgeWarningMargin(self, double: float) -> None: ...
    def setTargetValvePosition(self, double: float) -> None: ...
    def setUseHotGasBypass(self, boolean: bool) -> None: ...
    def setValvePosition(self, double: float) -> None: ...
    def setValveRateLimit(self, double: float) -> None: ...
    def setValveResponseTime(self, double: float) -> None: ...
    def shouldTrip(self) -> bool: ...
    def updateController(self, double: float, double2: float) -> float: ...
    class ControlStrategy(java.lang.Enum['AntiSurge.ControlStrategy']):
        ON_OFF: typing.ClassVar['AntiSurge.ControlStrategy'] = ...
        PROPORTIONAL: typing.ClassVar['AntiSurge.ControlStrategy'] = ...
        PID: typing.ClassVar['AntiSurge.ControlStrategy'] = ...
        PREDICTIVE: typing.ClassVar['AntiSurge.ControlStrategy'] = ...
        DUAL_LOOP: typing.ClassVar['AntiSurge.ControlStrategy'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'AntiSurge.ControlStrategy': ...
        @staticmethod
        def values() -> typing.MutableSequence['AntiSurge.ControlStrategy']: ...

class BoundaryCurveInterface(java.io.Serializable):
    def getFlow(self, double: float) -> float: ...
    def isActive(self) -> bool: ...
    def isLimit(self, double: float, double2: float) -> bool: ...
    def setActive(self, boolean: bool) -> None: ...
    def setCurve(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class CompressorChartGenerator:
    def __init__(self, compressor: 'Compressor'): ...
    def enableAdvancedCorrections(self, int: int) -> 'CompressorChartGenerator': ...
    @typing.overload
    def generateCompressorChart(self, string: typing.Union[java.lang.String, str]) -> 'CompressorChartInterface': ...
    @typing.overload
    def generateCompressorChart(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> 'CompressorChartInterface': ...
    @typing.overload
    def generateCompressorChart(self, string: typing.Union[java.lang.String, str], int: int) -> 'CompressorChartInterface': ...
    @typing.overload
    def generateFromTemplate(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> 'CompressorChartInterface': ...
    @typing.overload
    def generateFromTemplate(self, string: typing.Union[java.lang.String, str], int: int) -> 'CompressorChartInterface': ...
    @typing.overload
    def generateFromTemplate(self, compressorCurveTemplate: 'CompressorCurveTemplate', int: int) -> 'CompressorChartInterface': ...
    @staticmethod
    def getAvailableTemplates() -> typing.MutableSequence[java.lang.String]: ...
    def getChartType(self) -> java.lang.String: ...
    def getImpellerDiameter(self) -> float: ...
    def getNumberOfStages(self) -> int: ...
    @staticmethod
    def getOriginalTemplateChart(string: typing.Union[java.lang.String, str]) -> 'CompressorChartInterface': ...
    def isUseMachCorrection(self) -> bool: ...
    def isUseMultistageSurgeCorrection(self) -> bool: ...
    def isUseReynoldsCorrection(self) -> bool: ...
    def setChartType(self, string: typing.Union[java.lang.String, str]) -> 'CompressorChartGenerator': ...
    def setImpellerDiameter(self, double: float) -> 'CompressorChartGenerator': ...
    def setNumberOfStages(self, int: int) -> 'CompressorChartGenerator': ...
    def setUseMachCorrection(self, boolean: bool) -> 'CompressorChartGenerator': ...
    def setUseMultistageSurgeCorrection(self, boolean: bool) -> 'CompressorChartGenerator': ...
    def setUseReynoldsCorrection(self, boolean: bool) -> 'CompressorChartGenerator': ...

class CompressorChartInterface(java.lang.Cloneable):
    @typing.overload
    def addCurve(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def addCurve(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def generateStoneWallCurve(self) -> None: ...
    def generateSurgeCurve(self) -> None: ...
    def getChartConditions(self) -> typing.MutableSequence[float]: ...
    def getDischargeTemperatures(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getFlow(self, double: float, double2: float, double3: float) -> float: ...
    def getFlows(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getGamma(self) -> float: ...
    def getHeadUnit(self) -> java.lang.String: ...
    def getHeads(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getInletPressure(self) -> float: ...
    def getInletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getInletTemperature(self) -> float: ...
    def getMaxSpeedCurve(self) -> float: ...
    def getMinSpeedCurve(self) -> float: ...
    def getOperatingMW(self) -> float: ...
    def getPolytropicEfficiencies(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getPolytropicEfficiency(self, double: float, double2: float) -> float: ...
    def getPolytropicExponent(self) -> float: ...
    def getPolytropicHead(self, double: float, double2: float) -> float: ...
    def getPowers(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getPressureRatios(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getRatioToMaxSpeed(self, double: float) -> float: ...
    def getRatioToMinSpeed(self, double: float) -> float: ...
    def getReferenceDensity(self) -> float: ...
    def getSpeed(self, double: float, double2: float) -> int: ...
    def getSpeedValue(self, double: float, double2: float) -> float: ...
    def getSpeeds(self) -> typing.MutableSequence[float]: ...
    def getStoneWallCurve(self) -> 'StoneWallCurve': ...
    def getStoneWallFlowAtSpeed(self, double: float) -> float: ...
    def getStoneWallHeadAtSpeed(self, double: float) -> float: ...
    def getSurgeCurve(self) -> 'SafeSplineSurgeCurve': ...
    def getSurgeFlowAtSpeed(self, double: float) -> float: ...
    def getSurgeHeadAtSpeed(self, double: float) -> float: ...
    def hashCode(self) -> int: ...
    def isHigherThanMaxSpeed(self, double: float) -> bool: ...
    def isLowerThanMinSpeed(self, double: float) -> bool: ...
    def isSpeedWithinRange(self, double: float) -> bool: ...
    def isUseCompressorChart(self) -> bool: ...
    def plot(self) -> None: ...
    @typing.overload
    def setCurves(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray5: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    @typing.overload
    def setCurves(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray5: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray6: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    def setGamma(self, double: float) -> None: ...
    def setHeadUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInletPressure(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setInletTemperature(self, double: float) -> None: ...
    def setOperatingMW(self, double: float) -> None: ...
    def setPolytropicExponent(self, double: float) -> None: ...
    def setReferenceConditions(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    def setReferenceDensity(self, double: float) -> None: ...
    def setStoneWallCurve(self, stoneWallCurve: 'StoneWallCurve') -> None: ...
    def setSurgeCurve(self, safeSplineSurgeCurve: 'SafeSplineSurgeCurve') -> None: ...
    def setUseCompressorChart(self, boolean: bool) -> None: ...
    def setUseRealKappa(self, boolean: bool) -> None: ...
    def useRealKappa(self) -> bool: ...

class CompressorChartReader:
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def getChokeFlow(self) -> typing.MutableSequence[float]: ...
    def getChokeHead(self) -> typing.MutableSequence[float]: ...
    def getFlowLines(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getHeadLines(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getPolyEffLines(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getSpeeds(self) -> typing.MutableSequence[float]: ...
    def getStonewallCurve(self) -> typing.MutableSequence[float]: ...
    def getSurgeCurve(self) -> typing.MutableSequence[float]: ...
    def getSurgeFlow(self) -> typing.MutableSequence[float]: ...
    def getSurgeHead(self) -> typing.MutableSequence[float]: ...
    def setCurvesToCompressor(self, compressor: 'Compressor') -> None: ...
    def setHeadUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...

class CompressorCurve(java.io.Serializable):
    flow: typing.MutableSequence[float] = ...
    flowPolytropicEfficiency: typing.MutableSequence[float] = ...
    head: typing.MutableSequence[float] = ...
    polytropicEfficiency: typing.MutableSequence[float] = ...
    speed: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]): ...
    @typing.overload
    def __init__(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray]): ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...

class CompressorCurveCorrections(java.io.Serializable):
    @staticmethod
    def calculateCorrectedEfficiency(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def calculateEfficiencyAtFlow(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def calculateMachNumber(double: float, double2: float) -> float: ...
    @staticmethod
    def calculateMultistageSurgeCorrection(double: float, double2: float, int: int) -> float: ...
    @staticmethod
    def calculateMultistageSurgeHeadCorrection(double: float, double2: float, int: int) -> float: ...
    @typing.overload
    @staticmethod
    def calculateReynoldsEfficiencyCorrection(double: float) -> float: ...
    @typing.overload
    @staticmethod
    def calculateReynoldsEfficiencyCorrection(double: float, double2: float) -> float: ...
    @staticmethod
    def calculateReynoldsNumber(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def calculateSonicVelocity(double: float, double2: float, double3: float, double4: float) -> float: ...
    @staticmethod
    def calculateStonewallFlow(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def calculateTipSpeed(double: float, double2: float) -> float: ...
    @staticmethod
    def correctStonewallFlowForGas(double: float, double2: float, double3: float, double4: float, double5: float) -> float: ...
    @staticmethod
    def getCriticalMach() -> float: ...
    @staticmethod
    def getReferenceReynolds() -> float: ...

class CompressorCurveTemplate(java.io.Serializable):
    CENTRIFUGAL_STANDARD: typing.ClassVar['CompressorCurveTemplate'] = ...
    CENTRIFUGAL_HIGH_FLOW: typing.ClassVar['CompressorCurveTemplate'] = ...
    CENTRIFUGAL_HIGH_HEAD: typing.ClassVar['CompressorCurveTemplate'] = ...
    PIPELINE: typing.ClassVar['CompressorCurveTemplate'] = ...
    EXPORT: typing.ClassVar['CompressorCurveTemplate'] = ...
    INJECTION: typing.ClassVar['CompressorCurveTemplate'] = ...
    GAS_LIFT: typing.ClassVar['CompressorCurveTemplate'] = ...
    REFRIGERATION: typing.ClassVar['CompressorCurveTemplate'] = ...
    BOOSTER: typing.ClassVar['CompressorCurveTemplate'] = ...
    SINGLE_STAGE: typing.ClassVar['CompressorCurveTemplate'] = ...
    MULTISTAGE_INLINE: typing.ClassVar['CompressorCurveTemplate'] = ...
    INTEGRALLY_GEARED: typing.ClassVar['CompressorCurveTemplate'] = ...
    OVERHUNG: typing.ClassVar['CompressorCurveTemplate'] = ...
    def __init__(self, string: typing.Union[java.lang.String, str], double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]): ...
    @staticmethod
    def getAvailableTemplates() -> typing.MutableSequence[java.lang.String]: ...
    def getName(self) -> java.lang.String: ...
    def getNumberOfSpeedCurves(self) -> int: ...
    @typing.overload
    def getOriginalChart(self) -> CompressorChartInterface: ...
    @typing.overload
    def getOriginalChart(self, string: typing.Union[java.lang.String, str]) -> CompressorChartInterface: ...
    def getReferenceSpeed(self) -> float: ...
    def getSpeedRatios(self) -> typing.MutableSequence[float]: ...
    def getSpeeds(self) -> typing.MutableSequence[float]: ...
    @staticmethod
    def getTemplate(string: typing.Union[java.lang.String, str]) -> 'CompressorCurveTemplate': ...
    @staticmethod
    def getTemplatesByCategory(string: typing.Union[java.lang.String, str]) -> typing.MutableSequence[java.lang.String]: ...
    @typing.overload
    def scaleToDesignPoint(self, double: float, double2: float, double3: float, int: int) -> CompressorChartInterface: ...
    @typing.overload
    def scaleToDesignPoint(self, double: float, double2: float, double3: float, int: int, string: typing.Union[java.lang.String, str]) -> CompressorChartInterface: ...
    @typing.overload
    def scaleToSpeed(self, double: float) -> CompressorChartInterface: ...
    @typing.overload
    def scaleToSpeed(self, double: float, string: typing.Union[java.lang.String, str]) -> CompressorChartInterface: ...

class CompressorDriver(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, driverType: 'DriverType'): ...
    @typing.overload
    def __init__(self, driverType: 'DriverType', double: float): ...
    def calculateSpeedChange(self, double: float, double2: float, double3: float, double4: float) -> float: ...
    def canDeliverPower(self, double: float) -> bool: ...
    def checkOverloadTrip(self, double: float, double2: float) -> bool: ...
    def getAmbientPressure(self) -> float: ...
    def getAmbientTemperature(self) -> float: ...
    def getAvailablePower(self) -> float: ...
    def getDriverEfficiency(self) -> float: ...
    def getDriverType(self) -> 'DriverType': ...
    def getEfficiencyAtSpeed(self, double: float) -> float: ...
    def getInertia(self) -> float: ...
    def getMaxAcceleration(self) -> float: ...
    def getMaxAccelerationAtConditions(self, double: float, double2: float) -> float: ...
    def getMaxAvailablePower(self) -> float: ...
    def getMaxDeceleration(self) -> float: ...
    def getMaxPower(self) -> float: ...
    def getMaxSpeed(self) -> float: ...
    def getMinPower(self) -> float: ...
    def getMinSpeed(self) -> float: ...
    def getOverloadTripDelay(self) -> float: ...
    def getPowerMargin(self, double: float) -> float: ...
    def getPowerMarginRatio(self, double: float) -> float: ...
    def getRatedPower(self) -> float: ...
    def getRatedSpeed(self) -> float: ...
    def getRequiredDriverPower(self, double: float, double2: float) -> float: ...
    def getResponseTime(self) -> float: ...
    def isOverloadProtectionEnabled(self) -> bool: ...
    def resetOverloadTimer(self) -> None: ...
    def setAmbientPressure(self, double: float) -> None: ...
    def setAmbientTemperature(self, double: float) -> None: ...
    def setDriverEfficiency(self, double: float) -> None: ...
    def setDriverType(self, driverType: 'DriverType') -> None: ...
    def setInertia(self, double: float) -> None: ...
    def setMaxAcceleration(self, double: float) -> None: ...
    def setMaxDeceleration(self, double: float) -> None: ...
    def setMaxPower(self, double: float) -> None: ...
    def setMaxSpeed(self, double: float) -> None: ...
    def setMinPower(self, double: float) -> None: ...
    def setMinSpeed(self, double: float) -> None: ...
    def setOverloadProtectionEnabled(self, boolean: bool) -> None: ...
    def setOverloadTripDelay(self, double: float) -> None: ...
    def setRatedPower(self, double: float) -> None: ...
    def setRatedSpeed(self, double: float) -> None: ...
    def setResponseTime(self, double: float) -> None: ...
    def setTemperatureDerateFactor(self, double: float) -> None: ...
    def setVfdEfficiencyCoefficients(self, double: float, double2: float, double3: float) -> None: ...
    def toString(self) -> java.lang.String: ...

class CompressorEventListener:
    def onPowerLimitExceeded(self, compressor: 'Compressor', double: float, double2: float) -> None: ...
    def onShutdownComplete(self, compressor: 'Compressor') -> None: ...
    def onSpeedBelowMinimum(self, compressor: 'Compressor', double: float, double2: float) -> None: ...
    def onSpeedLimitExceeded(self, compressor: 'Compressor', double: float, double2: float) -> None: ...
    def onStartupComplete(self, compressor: 'Compressor') -> None: ...
    def onStateChange(self, compressor: 'Compressor', compressorState: 'CompressorState', compressorState2: 'CompressorState') -> None: ...
    def onStoneWallApproach(self, compressor: 'Compressor', double: float) -> None: ...
    def onSurgeApproach(self, compressor: 'Compressor', double: float, boolean: bool) -> None: ...
    def onSurgeOccurred(self, compressor: 'Compressor', double: float) -> None: ...

class CompressorInterface(jneqsim.process.equipment.ProcessEquipmentInterface, jneqsim.process.equipment.TwoPortInterface):
    def equals(self, object: typing.Any) -> bool: ...
    def getAntiSurge(self) -> AntiSurge: ...
    def getDistanceToSurge(self) -> float: ...
    def getEnergy(self) -> float: ...
    def getIsentropicEfficiency(self) -> float: ...
    def getMaximumSpeed(self) -> float: ...
    def getMinimumSpeed(self) -> float: ...
    def getPolytropicEfficiency(self) -> float: ...
    def getSurgeFlowRate(self) -> float: ...
    def getSurgeFlowRateMargin(self) -> float: ...
    def getSurgeFlowRateStd(self) -> float: ...
    def hashCode(self) -> int: ...
    def isStoneWall(self) -> bool: ...
    def isSurge(self) -> bool: ...
    def setCompressorChartType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setIsentropicEfficiency(self, double: float) -> None: ...
    def setMaximumSpeed(self, double: float) -> None: ...
    def setMinimumSpeed(self, double: float) -> None: ...
    def setPolytropicEfficiency(self, double: float) -> None: ...

class CompressorMechanicalLosses(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float): ...
    def calculateBufferGasFlow(self) -> float: ...
    def calculateLubeOilCoolerDuty(self) -> float: ...
    def calculateLubeOilFlowRate(self) -> float: ...
    def calculatePrimarySealLeakage(self) -> float: ...
    def calculateRadialBearingLoss(self) -> float: ...
    def calculateSecondarySealLeakage(self) -> float: ...
    def calculateSeparationGasFlow(self) -> float: ...
    def calculateThrustBearingLoss(self) -> float: ...
    def getBearingType(self) -> 'CompressorMechanicalLosses.BearingType': ...
    def getLubeOilInletTemp(self) -> float: ...
    def getLubeOilOutletTemp(self) -> float: ...
    def getMechanicalEfficiency(self, double: float) -> float: ...
    def getNumberOfRadialBearings(self) -> int: ...
    def getNumberOfSeals(self) -> int: ...
    def getRequiredSealGasSupplyPressure(self) -> float: ...
    def getSealDifferentialPressure(self) -> float: ...
    def getSealGasSupplyPressure(self) -> float: ...
    def getSealGasSupplyTemperature(self) -> float: ...
    def getSealType(self) -> 'CompressorMechanicalLosses.SealType': ...
    def getShaftDiameter(self) -> float: ...
    def getTotalBearingLoss(self) -> float: ...
    def getTotalMechanicalLoss(self) -> float: ...
    def getTotalSealGasConsumption(self) -> float: ...
    def printSummary(self) -> None: ...
    def setBearingType(self, bearingType: 'CompressorMechanicalLosses.BearingType') -> None: ...
    def setLubeOilInletTemp(self, double: float) -> None: ...
    def setLubeOilOutletTemp(self, double: float) -> None: ...
    def setNumberOfRadialBearings(self, int: int) -> None: ...
    def setNumberOfSeals(self, int: int) -> None: ...
    def setOperatingConditions(self, double: float, double2: float, double3: float, double4: float, double5: float) -> None: ...
    def setSealGasSupplyPressure(self, double: float) -> None: ...
    def setSealGasSupplyTemperature(self, double: float) -> None: ...
    def setSealType(self, sealType: 'CompressorMechanicalLosses.SealType') -> None: ...
    def setShaftDiameter(self, double: float) -> None: ...
    class BearingType(java.lang.Enum['CompressorMechanicalLosses.BearingType']):
        TILTING_PAD: typing.ClassVar['CompressorMechanicalLosses.BearingType'] = ...
        PLAIN_SLEEVE: typing.ClassVar['CompressorMechanicalLosses.BearingType'] = ...
        MAGNETIC_ACTIVE: typing.ClassVar['CompressorMechanicalLosses.BearingType'] = ...
        GAS_FOIL: typing.ClassVar['CompressorMechanicalLosses.BearingType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'CompressorMechanicalLosses.BearingType': ...
        @staticmethod
        def values() -> typing.MutableSequence['CompressorMechanicalLosses.BearingType']: ...
    class SealType(java.lang.Enum['CompressorMechanicalLosses.SealType']):
        DRY_GAS_TANDEM: typing.ClassVar['CompressorMechanicalLosses.SealType'] = ...
        DRY_GAS_DOUBLE: typing.ClassVar['CompressorMechanicalLosses.SealType'] = ...
        DRY_GAS_SINGLE: typing.ClassVar['CompressorMechanicalLosses.SealType'] = ...
        OIL_FILM: typing.ClassVar['CompressorMechanicalLosses.SealType'] = ...
        LABYRINTH: typing.ClassVar['CompressorMechanicalLosses.SealType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'CompressorMechanicalLosses.SealType': ...
        @staticmethod
        def values() -> typing.MutableSequence['CompressorMechanicalLosses.SealType']: ...

class CompressorOperatingHistory(java.io.Serializable):
    def __init__(self): ...
    def clear(self) -> None: ...
    def exportToCSV(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def generateSummary(self) -> java.lang.String: ...
    def getAverageEfficiency(self) -> float: ...
    def getHistory(self) -> java.util.List['CompressorOperatingHistory.OperatingPoint']: ...
    def getMinimumSurgeMargin(self) -> float: ...
    def getPeakFlow(self) -> 'CompressorOperatingHistory.OperatingPoint': ...
    def getPeakHead(self) -> 'CompressorOperatingHistory.OperatingPoint': ...
    def getPeakPower(self) -> 'CompressorOperatingHistory.OperatingPoint': ...
    def getPointCount(self) -> int: ...
    def getSurgeEventCount(self) -> int: ...
    def getTimeInSurge(self) -> float: ...
    @typing.overload
    def recordOperatingPoint(self, double: float, compressor: 'Compressor') -> None: ...
    @typing.overload
    def recordOperatingPoint(self, operatingPoint: 'CompressorOperatingHistory.OperatingPoint') -> None: ...
    class OperatingPoint(java.io.Serializable):
        def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, compressorState: 'CompressorState', double9: float, double10: float, double11: float, double12: float): ...
        def getEfficiency(self) -> float: ...
        def getFlow(self) -> float: ...
        def getHead(self) -> float: ...
        def getInletPressure(self) -> float: ...
        def getInletTemperature(self) -> float: ...
        def getOutletPressure(self) -> float: ...
        def getOutletTemperature(self) -> float: ...
        def getPower(self) -> float: ...
        def getSpeed(self) -> float: ...
        def getState(self) -> 'CompressorState': ...
        def getStoneWallMargin(self) -> float: ...
        def getSurgeMargin(self) -> float: ...
        def getTime(self) -> float: ...
        def isInSurge(self) -> bool: ...
        def toString(self) -> java.lang.String: ...

class CompressorPropertyProfile(java.io.Serializable):
    def __init__(self): ...
    def addFluid(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    def getFluid(self) -> java.util.ArrayList[jneqsim.thermo.system.SystemInterface]: ...
    def isActive(self) -> bool: ...
    def setActive(self, boolean: bool) -> None: ...
    def setFluid(self, arrayList: java.util.ArrayList[jneqsim.thermo.system.SystemInterface]) -> None: ...

class CompressorState(java.lang.Enum['CompressorState']):
    STOPPED: typing.ClassVar['CompressorState'] = ...
    STARTING: typing.ClassVar['CompressorState'] = ...
    RUNNING: typing.ClassVar['CompressorState'] = ...
    SURGE_PROTECTION: typing.ClassVar['CompressorState'] = ...
    SPEED_LIMITED: typing.ClassVar['CompressorState'] = ...
    SHUTDOWN: typing.ClassVar['CompressorState'] = ...
    DEPRESSURIZING: typing.ClassVar['CompressorState'] = ...
    TRIPPED: typing.ClassVar['CompressorState'] = ...
    STANDBY: typing.ClassVar['CompressorState'] = ...
    def canStart(self) -> bool: ...
    def getDescription(self) -> java.lang.String: ...
    def getDisplayName(self) -> java.lang.String: ...
    def isOperational(self) -> bool: ...
    def isStopped(self) -> bool: ...
    def isTransitional(self) -> bool: ...
    def requiresAcknowledgment(self) -> bool: ...
    def toString(self) -> java.lang.String: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'CompressorState': ...
    @staticmethod
    def values() -> typing.MutableSequence['CompressorState']: ...

class DriverType(java.lang.Enum['DriverType'], java.io.Serializable):
    ELECTRIC_MOTOR: typing.ClassVar['DriverType'] = ...
    VFD_MOTOR: typing.ClassVar['DriverType'] = ...
    GAS_TURBINE: typing.ClassVar['DriverType'] = ...
    STEAM_TURBINE: typing.ClassVar['DriverType'] = ...
    RECIPROCATING_ENGINE: typing.ClassVar['DriverType'] = ...
    EXPANDER_DRIVE: typing.ClassVar['DriverType'] = ...
    @staticmethod
    def fromName(string: typing.Union[java.lang.String, str]) -> 'DriverType': ...
    def getDisplayName(self) -> java.lang.String: ...
    def getTypicalEfficiency(self) -> float: ...
    def getTypicalResponseTime(self) -> float: ...
    def isElectric(self) -> bool: ...
    def supportsVariableSpeed(self) -> bool: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'DriverType': ...
    @staticmethod
    def values() -> typing.MutableSequence['DriverType']: ...

class ShutdownProfile(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, shutdownType: 'ShutdownProfile.ShutdownType', double: float): ...
    def getAntisurgeOpenDelay(self) -> float: ...
    def getCoastdownTime(self) -> float: ...
    def getCurrentPhase(self, double: float) -> java.lang.String: ...
    def getDepressurizationTime(self) -> float: ...
    def getEmergencyRampRate(self) -> float: ...
    def getIdleRundownTime(self) -> float: ...
    def getMaximumDepressurizationRate(self) -> float: ...
    def getMinimumIdleSpeed(self) -> float: ...
    def getNormalRampRate(self) -> float: ...
    def getProfilePoints(self) -> java.util.List['ShutdownProfile.ProfilePoint']: ...
    def getRapidRampRate(self) -> float: ...
    def getShutdownType(self) -> 'ShutdownProfile.ShutdownType': ...
    def getTargetSpeedAtTime(self, double: float, double2: float) -> float: ...
    def getTotalDuration(self) -> float: ...
    def isOpenAntisurgeOnShutdown(self) -> bool: ...
    def isShutdownComplete(self, double: float, double2: float) -> bool: ...
    def setAntisurgeOpenDelay(self, double: float) -> None: ...
    def setCoastdownTime(self, double: float) -> None: ...
    def setDepressurizationTime(self, double: float) -> None: ...
    def setEmergencyRampRate(self, double: float) -> None: ...
    def setIdleRundownTime(self, double: float) -> None: ...
    def setMaximumDepressurizationRate(self, double: float) -> None: ...
    def setMinimumIdleSpeed(self, double: float) -> None: ...
    def setNormalRampRate(self, double: float) -> None: ...
    def setOpenAntisurgeOnShutdown(self, boolean: bool) -> None: ...
    def setRapidRampRate(self, double: float) -> None: ...
    def setShutdownType(self, shutdownType: 'ShutdownProfile.ShutdownType', double: float) -> None: ...
    def shouldOpenAntisurge(self, double: float) -> bool: ...
    class ProfilePoint(java.io.Serializable):
        def __init__(self, double: float, double2: float, string: typing.Union[java.lang.String, str]): ...
        def getAction(self) -> java.lang.String: ...
        def getTargetSpeed(self) -> float: ...
        def getTime(self) -> float: ...
    class ShutdownType(java.lang.Enum['ShutdownProfile.ShutdownType']):
        NORMAL: typing.ClassVar['ShutdownProfile.ShutdownType'] = ...
        RAPID: typing.ClassVar['ShutdownProfile.ShutdownType'] = ...
        EMERGENCY: typing.ClassVar['ShutdownProfile.ShutdownType'] = ...
        COASTDOWN: typing.ClassVar['ShutdownProfile.ShutdownType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ShutdownProfile.ShutdownType': ...
        @staticmethod
        def values() -> typing.MutableSequence['ShutdownProfile.ShutdownType']: ...

class StartupProfile(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float): ...
    def addProfilePoint(self, double: float, double2: float, double3: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def clearProfile(self) -> None: ...
    @staticmethod
    def createFastProfile(double: float) -> 'StartupProfile': ...
    @staticmethod
    def createSlowProfile(double: float, double2: float) -> 'StartupProfile': ...
    def getAntisurgeOpeningDuration(self) -> float: ...
    def getCurrentPhase(self, double: float) -> java.lang.String: ...
    def getIdleHoldTime(self) -> float: ...
    def getMaximumVibration(self) -> float: ...
    def getMinimumIdleSpeed(self) -> float: ...
    def getMinimumLubeOilTemperature(self) -> float: ...
    def getMinimumOilPressure(self) -> float: ...
    def getNormalRampRate(self) -> float: ...
    def getProfilePoints(self) -> java.util.List['StartupProfile.ProfilePoint']: ...
    def getTargetSpeedAtTime(self, double: float, double2: float) -> float: ...
    def getTotalDuration(self, double: float) -> float: ...
    def getWarmupRampRate(self) -> float: ...
    def isRequireAntisurgeOpen(self) -> bool: ...
    def isStartupComplete(self, double: float, double2: float, double3: float, double4: float) -> bool: ...
    def setAntisurgeOpeningDuration(self, double: float) -> None: ...
    def setIdleHoldTime(self, double: float) -> None: ...
    def setMaximumVibration(self, double: float) -> None: ...
    def setMinimumIdleSpeed(self, double: float) -> None: ...
    def setMinimumLubeOilTemperature(self, double: float) -> None: ...
    def setMinimumOilPressure(self, double: float) -> None: ...
    def setNormalRampRate(self, double: float) -> None: ...
    def setRequireAntisurgeOpen(self, boolean: bool) -> None: ...
    def setWarmupRampRate(self, double: float) -> None: ...
    class ProfilePoint(java.io.Serializable):
        def __init__(self, double: float, double2: float, double3: float, string: typing.Union[java.lang.String, str]): ...
        def getCheckDescription(self) -> java.lang.String: ...
        def getHoldDuration(self) -> float: ...
        def getTargetSpeed(self) -> float: ...
        def getTime(self) -> float: ...

class BoundaryCurve(BoundaryCurveInterface):
    def equals(self, object: typing.Any) -> bool: ...
    @typing.overload
    def getFlow(self, double: float) -> float: ...
    @typing.overload
    def getFlow(self) -> typing.MutableSequence[float]: ...
    def getHead(self) -> typing.MutableSequence[float]: ...
    def hashCode(self) -> int: ...
    def isActive(self) -> bool: ...
    def setActive(self, boolean: bool) -> None: ...
    def setCurve(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class Compressor(jneqsim.process.equipment.TwoPortEquipment, CompressorInterface, jneqsim.process.ml.StateVectorProvider):
    thermoSystem: jneqsim.thermo.system.SystemInterface = ...
    dH: float = ...
    inletEnthalpy: float = ...
    pressure: float = ...
    isentropicEfficiency: float = ...
    polytropicEfficiency: float = ...
    usePolytropicCalc: bool = ...
    powerSet: bool = ...
    calcPressureOut: bool = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], boolean: bool): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def acknowledgeTrip(self) -> None: ...
    def addEventListener(self, compressorEventListener: CompressorEventListener) -> None: ...
    def addOperatingHours(self, double: float) -> None: ...
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str]) -> 'Compressor.Builder': ...
    def checkPowerLimits(self) -> None: ...
    def checkSpeedLimits(self) -> None: ...
    def checkStoneWallMargin(self) -> None: ...
    def checkSurgeMargin(self) -> None: ...
    def copy(self) -> 'Compressor': ...
    def disableOperatingHistory(self) -> None: ...
    def displayResult(self) -> None: ...
    def emergencyShutdown(self) -> None: ...
    def enableOperatingHistory(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def findOutPressure(self, double: float, double2: float, double3: float) -> float: ...
    @typing.overload
    def generateCompressorChart(self) -> None: ...
    @typing.overload
    def generateCompressorChart(self, int: int) -> None: ...
    @typing.overload
    def generateCompressorChart(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def generateCompressorChart(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def generateCompressorChart(self, string: typing.Union[java.lang.String, str], int: int) -> None: ...
    def generateCompressorChartFromTemplate(self, string: typing.Union[java.lang.String, str], int: int) -> None: ...
    def generateCompressorCurves(self) -> None: ...
    def getActualCompressionRatio(self) -> float: ...
    def getAntiSurge(self) -> AntiSurge: ...
    def getBearingLoss(self) -> float: ...
    def getCapacityDuty(self) -> float: ...
    def getCapacityMax(self) -> float: ...
    def getCompressionRatio(self) -> float: ...
    def getCompressorChart(self) -> CompressorChartInterface: ...
    def getCompressorChartType(self) -> java.lang.String: ...
    def getDegradationFactor(self) -> float: ...
    def getDistanceToStoneWall(self) -> float: ...
    def getDistanceToSurge(self) -> float: ...
    def getDriver(self) -> CompressorDriver: ...
    def getEffectivePolytropicEfficiency(self) -> float: ...
    def getEffectivePolytropicHead(self) -> float: ...
    def getEnergy(self) -> float: ...
    def getEntropyProduction(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getExergyChange(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getExergyChange(self, string: typing.Union[java.lang.String, str], double: float) -> float: ...
    def getFoulingFactor(self) -> float: ...
    def getIsentropicEfficiency(self) -> float: ...
    def getMaxAccelerationRate(self) -> float: ...
    def getMaxDecelerationRate(self) -> float: ...
    def getMaxOutletPressure(self) -> float: ...
    def getMaximumSpeed(self) -> float: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.compressor.CompressorMechanicalDesign: ...
    def getMechanicalEfficiency(self) -> float: ...
    def getMechanicalLosses(self) -> CompressorMechanicalLosses: ...
    def getMinimumSpeed(self) -> float: ...
    def getNumberOfCompressorCalcSteps(self) -> int: ...
    def getOperatingHistory(self) -> CompressorOperatingHistory: ...
    def getOperatingHours(self) -> float: ...
    def getOperatingState(self) -> CompressorState: ...
    def getOutTemperature(self) -> float: ...
    def getOutletPressure(self) -> float: ...
    def getPolytropicEfficiency(self) -> float: ...
    def getPolytropicExponent(self) -> float: ...
    def getPolytropicFluidHead(self) -> float: ...
    @typing.overload
    def getPolytropicHead(self) -> float: ...
    @typing.overload
    def getPolytropicHead(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getPolytropicHeadMeter(self) -> float: ...
    def getPolytropicMethod(self) -> java.lang.String: ...
    @typing.overload
    def getPower(self) -> float: ...
    @typing.overload
    def getPower(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getPropertyProfile(self) -> CompressorPropertyProfile: ...
    @typing.overload
    def getRatioToMaxSpeed(self) -> float: ...
    @typing.overload
    def getRatioToMaxSpeed(self, double: float) -> float: ...
    @typing.overload
    def getRatioToMinSpeed(self) -> float: ...
    @typing.overload
    def getRatioToMinSpeed(self, double: float) -> float: ...
    def getResultTable(self) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def getRotationalInertia(self) -> float: ...
    def getSafetyFactorCorrectedFlowHeadAtCurrentSpeed(self) -> typing.MutableSequence[float]: ...
    def getSealGasConsumption(self) -> float: ...
    def getShutdownProfile(self) -> ShutdownProfile: ...
    def getSpeed(self) -> float: ...
    def getStartupProfile(self) -> StartupProfile: ...
    def getStateVector(self) -> jneqsim.process.ml.StateVector: ...
    def getStoneWallWarningThreshold(self) -> float: ...
    def getSurgeCriticalThreshold(self) -> float: ...
    def getSurgeFlowRate(self) -> float: ...
    def getSurgeFlowRateMargin(self) -> float: ...
    def getSurgeFlowRateStd(self) -> float: ...
    def getSurgeWarningThreshold(self) -> float: ...
    def getTargetSpeed(self) -> float: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getTotalWork(self) -> float: ...
    def hashCode(self) -> int: ...
    def initMechanicalDesign(self) -> None: ...
    @typing.overload
    def initMechanicalLosses(self) -> CompressorMechanicalLosses: ...
    @typing.overload
    def initMechanicalLosses(self, double: float) -> CompressorMechanicalLosses: ...
    def isAutoSpeedMode(self) -> bool: ...
    def isCalcPressureOut(self) -> bool: ...
    @typing.overload
    def isHigherThanMaxSpeed(self) -> bool: ...
    @typing.overload
    def isHigherThanMaxSpeed(self, double: float) -> bool: ...
    def isLimitSpeed(self) -> bool: ...
    @typing.overload
    def isLowerThanMinSpeed(self) -> bool: ...
    @typing.overload
    def isLowerThanMinSpeed(self, double: float) -> bool: ...
    def isSetMaxOutletPressure(self) -> bool: ...
    def isSolveSpeed(self) -> bool: ...
    @typing.overload
    def isSpeedWithinRange(self) -> bool: ...
    @typing.overload
    def isSpeedWithinRange(self, double: float) -> bool: ...
    @typing.overload
    def isStoneWall(self) -> bool: ...
    @typing.overload
    def isStoneWall(self, double: float, double2: float) -> bool: ...
    @typing.overload
    def isSurge(self, double: float, double2: float) -> bool: ...
    @typing.overload
    def isSurge(self) -> bool: ...
    def isUseGERG2008(self) -> bool: ...
    def isUseLeachman(self) -> bool: ...
    def isUseRigorousPolytropicMethod(self) -> bool: ...
    def isUseVega(self) -> bool: ...
    def recordOperatingPoint(self, double: float) -> None: ...
    def removeEventListener(self, compressorEventListener: CompressorEventListener) -> None: ...
    def resetDynamicState(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def runController(self, double: float, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setAntiSurge(self, antiSurge: AntiSurge) -> None: ...
    def setAutoSpeedMode(self, boolean: bool) -> None: ...
    def setCalcPressureOut(self, boolean: bool) -> None: ...
    def setCompressionRatio(self, double: float) -> None: ...
    def setCompressorChart(self, compressorChartInterface: CompressorChartInterface) -> None: ...
    def setCompressorChartType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDegradationFactor(self, double: float) -> None: ...
    @typing.overload
    def setDriver(self, compressorDriver: CompressorDriver) -> None: ...
    @typing.overload
    def setDriver(self, driverType: DriverType, double: float) -> None: ...
    def setFoulingFactor(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setIsSetMaxOutletPressure(self, boolean: bool) -> None: ...
    def setIsentropicEfficiency(self, double: float) -> None: ...
    def setLimitSpeed(self, boolean: bool) -> None: ...
    def setMaxAccelerationRate(self, double: float) -> None: ...
    def setMaxDecelerationRate(self, double: float) -> None: ...
    def setMaxOutletPressure(self, double: float) -> None: ...
    def setMaximumSpeed(self, double: float) -> None: ...
    def setMechanicalLosses(self, compressorMechanicalLosses: CompressorMechanicalLosses) -> None: ...
    def setMinimumSpeed(self, double: float) -> None: ...
    def setNumberOfCompressorCalcSteps(self, int: int) -> None: ...
    def setOperatingHours(self, double: float) -> None: ...
    def setOperatingState(self, compressorState: CompressorState) -> None: ...
    def setOutTemperature(self, double: float) -> None: ...
    @typing.overload
    def setOutletPressure(self, double: float) -> None: ...
    @typing.overload
    def setOutletPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPolytropicEfficiency(self, double: float) -> None: ...
    def setPolytropicHeadMeter(self, double: float) -> None: ...
    def setPolytropicMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPower(self, double: float) -> None: ...
    @typing.overload
    def setPressure(self, double: float) -> None: ...
    @typing.overload
    def setPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPropertyProfile(self, compressorPropertyProfile: CompressorPropertyProfile) -> None: ...
    def setRotationalInertia(self, double: float) -> None: ...
    def setShutdownProfile(self, shutdownProfile: ShutdownProfile) -> None: ...
    def setSolveSpeed(self, boolean: bool) -> None: ...
    def setSpeed(self, double: float) -> None: ...
    def setStartupProfile(self, startupProfile: StartupProfile) -> None: ...
    def setStoneWallWarningThreshold(self, double: float) -> None: ...
    def setSurgeCriticalThreshold(self, double: float) -> None: ...
    def setSurgeWarningThreshold(self, double: float) -> None: ...
    def setTargetSpeed(self, double: float) -> None: ...
    def setUseEnergyEfficiencyChart(self, boolean: bool) -> None: ...
    def setUseGERG2008(self, boolean: bool) -> None: ...
    def setUseLeachman(self, boolean: bool) -> None: ...
    def setUsePolytropicCalc(self, boolean: bool) -> None: ...
    def setUseRigorousPolytropicMethod(self, boolean: bool) -> None: ...
    def setUseVega(self, boolean: bool) -> None: ...
    def solveAntiSurge(self) -> None: ...
    def solveEfficiency(self, double: float) -> float: ...
    def startCompressor(self, double: float) -> None: ...
    @typing.overload
    def stopCompressor(self) -> None: ...
    @typing.overload
    def stopCompressor(self, shutdownType: ShutdownProfile.ShutdownType) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    def updateDynamicState(self, double: float) -> None: ...
    def updateMechanicalLosses(self) -> None: ...
    def useOutTemperature(self, boolean: bool) -> None: ...
    def usePolytropicCalc(self) -> bool: ...
    class Builder:
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def build(self) -> 'Compressor': ...
        def compressionRatio(self, double: float) -> 'Compressor.Builder': ...
        def inletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> 'Compressor.Builder': ...
        def interpolateMapLookup(self) -> 'Compressor.Builder': ...
        def isentropicEfficiency(self, double: float) -> 'Compressor.Builder': ...
        def maxOutletPressure(self, double: float) -> 'Compressor.Builder': ...
        def maxSpeed(self, double: float) -> 'Compressor.Builder': ...
        def minSpeed(self, double: float) -> 'Compressor.Builder': ...
        def numberOfCompressorCalcSteps(self, int: int) -> 'Compressor.Builder': ...
        @typing.overload
        def outletPressure(self, double: float) -> 'Compressor.Builder': ...
        @typing.overload
        def outletPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> 'Compressor.Builder': ...
        @typing.overload
        def outletTemperature(self, double: float) -> 'Compressor.Builder': ...
        @typing.overload
        def outletTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> 'Compressor.Builder': ...
        def polytropicEfficiency(self, double: float) -> 'Compressor.Builder': ...
        def polytropicMethod(self, string: typing.Union[java.lang.String, str]) -> 'Compressor.Builder': ...
        def speed(self, double: float) -> 'Compressor.Builder': ...
        def useCompressorChart(self) -> 'Compressor.Builder': ...
        def useGERG2008(self) -> 'Compressor.Builder': ...
        def useLeachman(self) -> 'Compressor.Builder': ...
        def useRigorousPolytropicMethod(self) -> 'Compressor.Builder': ...
        def useVega(self) -> 'Compressor.Builder': ...

class CompressorChart(CompressorChartInterface, java.io.Serializable):
    def __init__(self): ...
    @typing.overload
    def addCurve(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def addCurve(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def addSurgeCurve(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def checkStoneWall(self, double: float, double2: float) -> bool: ...
    def checkSurge1(self, double: float, double2: float) -> bool: ...
    def checkSurge2(self, double: float, double2: float) -> bool: ...
    def equals(self, object: typing.Any) -> bool: ...
    def fitReducedCurve(self) -> None: ...
    def generateStoneWallCurve(self) -> None: ...
    def generateSurgeCurve(self) -> None: ...
    def getChartConditions(self) -> typing.MutableSequence[float]: ...
    def getDischargeTemperatures(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getFlow(self, double: float, double2: float, double3: float) -> float: ...
    def getFlows(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getGamma(self) -> float: ...
    def getHeadUnit(self) -> java.lang.String: ...
    def getHeads(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getInletPressure(self) -> float: ...
    def getInletTemperature(self) -> float: ...
    def getMaxSpeedCurve(self) -> float: ...
    def getMinSpeedCurve(self) -> float: ...
    def getPolytropicEfficiencies(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getPolytropicEfficiency(self, double: float, double2: float) -> float: ...
    def getPolytropicExponent(self) -> float: ...
    def getPolytropicHead(self, double: float, double2: float) -> float: ...
    def getPowers(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getPressureRatios(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getReferenceDensity(self) -> float: ...
    def getSpeed(self, double: float, double2: float) -> int: ...
    def getSpeedValue(self, double: float, double2: float) -> float: ...
    def getSpeeds(self) -> typing.MutableSequence[float]: ...
    def getStoneWallCurve(self) -> 'StoneWallCurve': ...
    def getStoneWallFlowAtSpeed(self, double: float) -> float: ...
    def getStoneWallHeadAtSpeed(self, double: float) -> float: ...
    def getSurgeCurve(self) -> 'SafeSplineSurgeCurve': ...
    def getSurgeFlowAtSpeed(self, double: float) -> float: ...
    def getSurgeHeadAtSpeed(self, double: float) -> float: ...
    def hashCode(self) -> int: ...
    def isUseCompressorChart(self) -> bool: ...
    def plot(self) -> None: ...
    def polytropicEfficiency(self, double: float, double2: float) -> float: ...
    @typing.overload
    def setCurves(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray5: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    @typing.overload
    def setCurves(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray5: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray6: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    def setGamma(self, double: float) -> None: ...
    def setHeadUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInletPressure(self, double: float) -> None: ...
    def setInletTemperature(self, double: float) -> None: ...
    def setMaxSpeedCurve(self, double: float) -> None: ...
    def setMinSpeedCurve(self, double: float) -> None: ...
    def setPolytropicExponent(self, double: float) -> None: ...
    def setReferenceConditions(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    def setReferenceDensity(self, double: float) -> None: ...
    def setStoneWallCurve(self, stoneWallCurve: 'StoneWallCurve') -> None: ...
    def setSurgeCurve(self, safeSplineSurgeCurve: 'SafeSplineSurgeCurve') -> None: ...
    def setUseCompressorChart(self, boolean: bool) -> None: ...
    def setUseRealKappa(self, boolean: bool) -> None: ...
    def useRealKappa(self) -> bool: ...

class CompressorChartAlternativeMapLookup(CompressorChart, CompressorChartInterface, java.io.Serializable):
    def __init__(self): ...
    @typing.overload
    def addCurve(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def addCurve(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def addSurgeCurve(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    @staticmethod
    def bisect_left(doubleArray: typing.Union[typing.List[float], jpype.JArray], double2: float) -> int: ...
    @typing.overload
    @staticmethod
    def bisect_left(doubleArray: typing.Union[typing.List[float], jpype.JArray], double2: float, int: int, int2: int) -> int: ...
    def checkStoneWall(self, double: float, double2: float) -> bool: ...
    def checkSurge1(self, double: float, double2: float) -> bool: ...
    def checkSurge2(self, double: float, double2: float) -> bool: ...
    def getChartConditions(self) -> typing.MutableSequence[float]: ...
    def getChartValues(self) -> java.util.ArrayList[CompressorCurve]: ...
    def getClosestRefSpeeds(self, double: float) -> java.util.ArrayList[float]: ...
    def getCurveAtRefSpeed(self, double: float) -> CompressorCurve: ...
    def getFlow(self, double: float, double2: float, double3: float) -> float: ...
    def getFlows(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getGearRatio(self) -> float: ...
    def getHeadUnit(self) -> java.lang.String: ...
    def getHeads(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getMaxSpeedCurve(self) -> float: ...
    def getMinSpeedCurve(self) -> float: ...
    def getPolytropicEfficiencies(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getPolytropicEfficiency(self, double: float, double2: float) -> float: ...
    def getPolytropicHead(self, double: float, double2: float) -> float: ...
    def getSpeed(self, double: float, double2: float) -> int: ...
    def getSpeedValue(self, double: float, double2: float) -> float: ...
    def getSpeeds(self) -> typing.MutableSequence[float]: ...
    def getStoneWallCurve(self) -> 'StoneWallCurve': ...
    def getSurgeCurve(self) -> 'SafeSplineSurgeCurve': ...
    def isUseCompressorChart(self) -> bool: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def plot(self) -> None: ...
    def polytropicEfficiency(self, double: float, double2: float) -> float: ...
    def prettyPrintChartValues(self) -> None: ...
    @typing.overload
    def setCurves(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray5: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    @typing.overload
    def setCurves(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray5: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray6: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    def setGearRatio(self, double: float) -> None: ...
    def setHeadUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReferenceConditions(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    def setStoneWallCurve(self, stoneWallCurve: 'StoneWallCurve') -> None: ...
    def setSurgeCurve(self, safeSplineSurgeCurve: 'SafeSplineSurgeCurve') -> None: ...
    def setUseCompressorChart(self, boolean: bool) -> None: ...
    def setUseRealKappa(self, boolean: bool) -> None: ...
    def useRealKappa(self) -> bool: ...

class CompressorChartMWInterpolation(CompressorChart):
    def __init__(self): ...
    @typing.overload
    def addMapAtMW(self, double: float, double2: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def addMapAtMW(self, double: float, double2: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def addMapAtMW(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray5: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    @typing.overload
    def addMapAtMW(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray5: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray6: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    @typing.overload
    def addMapAtMW(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    @typing.overload
    def addMapAtMW(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray5: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    def generateAllStoneWallCurves(self) -> None: ...
    def generateAllSurgeCurves(self) -> None: ...
    def getChartAtMW(self, double: float) -> CompressorChart: ...
    def getDistanceToStoneWall(self, double: float, double2: float) -> float: ...
    def getDistanceToSurge(self, double: float, double2: float) -> float: ...
    def getInletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getMapMolecularWeights(self) -> java.util.List[float]: ...
    def getNumberOfMaps(self) -> int: ...
    def getOperatingMW(self) -> float: ...
    def getPolytropicEfficiency(self, double: float, double2: float) -> float: ...
    def getPolytropicHead(self, double: float, double2: float) -> float: ...
    def getStoneWallFlow(self, double: float) -> float: ...
    def getStoneWallFlowAtSpeed(self, double: float) -> float: ...
    def getStoneWallHeadAtSpeed(self, double: float) -> float: ...
    def getSurgeFlow(self, double: float) -> float: ...
    def getSurgeFlowAtSpeed(self, double: float) -> float: ...
    def getSurgeHeadAtSpeed(self, double: float) -> float: ...
    def isAllowExtrapolation(self) -> bool: ...
    def isAutoGenerateStoneWallCurves(self) -> bool: ...
    def isAutoGenerateSurgeCurves(self) -> bool: ...
    def isInterpolationEnabled(self) -> bool: ...
    def isStoneWall(self, double: float, double2: float) -> bool: ...
    def isSurge(self, double: float, double2: float) -> bool: ...
    def isUseActualMW(self) -> bool: ...
    def setAllowExtrapolation(self, boolean: bool) -> None: ...
    def setAutoGenerateStoneWallCurves(self, boolean: bool) -> None: ...
    def setAutoGenerateSurgeCurves(self, boolean: bool) -> None: ...
    def setHeadUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setInterpolationEnabled(self, boolean: bool) -> None: ...
    def setOperatingMW(self, double: float) -> None: ...
    def setStoneWallCurveAtMW(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setSurgeCurveAtMW(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setUseActualMW(self, boolean: bool) -> None: ...

class StoneWallCurve(BoundaryCurve):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]): ...
    def getStoneWallFlow(self, double: float) -> float: ...
    def isLimit(self, double: float, double2: float) -> bool: ...
    def isStoneWall(self, double: float, double2: float) -> bool: ...

class SurgeCurve(BoundaryCurve):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]): ...
    def getSurgeFlow(self, double: float) -> float: ...
    def isLimit(self, double: float, double2: float) -> bool: ...
    def isSurge(self, double: float, double2: float) -> bool: ...

class CompressorChartAlternativeMapLookupExtrapolate(CompressorChartAlternativeMapLookup):
    def __init__(self): ...
    def getClosestRefSpeeds(self, double: float) -> java.util.ArrayList[float]: ...
    def getPolytropicEfficiency(self, double: float, double2: float) -> float: ...
    def getPolytropicHead(self, double: float, double2: float) -> float: ...

class SafeSplineStoneWallCurve(StoneWallCurve):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]): ...
    @typing.overload
    def getFlow(self, double: float) -> float: ...
    @typing.overload
    def getFlow(self) -> typing.MutableSequence[float]: ...
    def getSingleStoneWallFlow(self) -> float: ...
    def getSingleStoneWallHead(self) -> float: ...
    def getSortedFlow(self) -> typing.MutableSequence[float]: ...
    def getSortedHead(self) -> typing.MutableSequence[float]: ...
    def getStoneWallFlow(self, double: float) -> float: ...
    def getStoneWallHead(self, double: float) -> float: ...
    def isSinglePointStoneWall(self) -> bool: ...
    def isStoneWall(self, double: float, double2: float) -> bool: ...
    def setCurve(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class SafeSplineSurgeCurve(SurgeCurve):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]): ...
    @typing.overload
    def getFlow(self, double: float) -> float: ...
    @typing.overload
    def getFlow(self) -> typing.MutableSequence[float]: ...
    def getSingleSurgeFlow(self) -> float: ...
    def getSingleSurgeHead(self) -> float: ...
    def getSortedFlow(self) -> typing.MutableSequence[float]: ...
    def getSortedHead(self) -> typing.MutableSequence[float]: ...
    def getSurgeFlow(self, double: float) -> float: ...
    def getSurgeHead(self, double: float) -> float: ...
    def isSinglePointSurge(self) -> bool: ...
    def isSurge(self, double: float, double2: float) -> bool: ...
    def setCurve(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class CompressorChartKhader2015(CompressorChartAlternativeMapLookupExtrapolate):
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface, double: float): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, systemInterface2: jneqsim.thermo.system.SystemInterface, double: float): ...
    def generateRealCurvesForFluid(self) -> None: ...
    def generateStoneWallCurve(self) -> None: ...
    def generateSurgeCurve(self) -> None: ...
    def getCorrectedCurves(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray5: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray6: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> java.util.List['CompressorChartKhader2015.CorrectedCurve']: ...
    def getImpellerOuterDiameter(self) -> float: ...
    def getPolytropicEfficiency(self, double: float, double2: float) -> float: ...
    def getPolytropicHead(self, double: float, double2: float) -> float: ...
    def getRealCurves(self) -> java.util.List['CompressorChartKhader2015.RealCurve']: ...
    def getReferenceFluid(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getStoneWallFlowAtSpeed(self, double: float) -> float: ...
    def getStoneWallHeadAtSpeed(self, double: float) -> float: ...
    def getSurgeFlowAtSpeed(self, double: float) -> float: ...
    def getSurgeHeadAtSpeed(self, double: float) -> float: ...
    def prettyPrintRealCurvesForFluid(self) -> None: ...
    @typing.overload
    def setCurves(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray5: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    @typing.overload
    def setCurves(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray4: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray5: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray6: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    def setImpellerOuterDiameter(self, double: float) -> None: ...
    def setReferenceFluid(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    class CorrectedCurve:
        machineMachNumber: float = ...
        correctedFlowFactor: typing.MutableSequence[float] = ...
        correctedHeadFactor: typing.MutableSequence[float] = ...
        correctedFlowFactorEfficiency: typing.MutableSequence[float] = ...
        polytropicEfficiency: typing.MutableSequence[float] = ...
        def __init__(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray]): ...
    class RealCurve:
        speed: float = ...
        flow: typing.MutableSequence[float] = ...
        head: typing.MutableSequence[float] = ...
        flowPolyEff: typing.MutableSequence[float] = ...
        polytropicEfficiency: typing.MutableSequence[float] = ...
        def __init__(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray]): ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.compressor")``.

    AntiSurge: typing.Type[AntiSurge]
    BoundaryCurve: typing.Type[BoundaryCurve]
    BoundaryCurveInterface: typing.Type[BoundaryCurveInterface]
    Compressor: typing.Type[Compressor]
    CompressorChart: typing.Type[CompressorChart]
    CompressorChartAlternativeMapLookup: typing.Type[CompressorChartAlternativeMapLookup]
    CompressorChartAlternativeMapLookupExtrapolate: typing.Type[CompressorChartAlternativeMapLookupExtrapolate]
    CompressorChartGenerator: typing.Type[CompressorChartGenerator]
    CompressorChartInterface: typing.Type[CompressorChartInterface]
    CompressorChartKhader2015: typing.Type[CompressorChartKhader2015]
    CompressorChartMWInterpolation: typing.Type[CompressorChartMWInterpolation]
    CompressorChartReader: typing.Type[CompressorChartReader]
    CompressorCurve: typing.Type[CompressorCurve]
    CompressorCurveCorrections: typing.Type[CompressorCurveCorrections]
    CompressorCurveTemplate: typing.Type[CompressorCurveTemplate]
    CompressorDriver: typing.Type[CompressorDriver]
    CompressorEventListener: typing.Type[CompressorEventListener]
    CompressorInterface: typing.Type[CompressorInterface]
    CompressorMechanicalLosses: typing.Type[CompressorMechanicalLosses]
    CompressorOperatingHistory: typing.Type[CompressorOperatingHistory]
    CompressorPropertyProfile: typing.Type[CompressorPropertyProfile]
    CompressorState: typing.Type[CompressorState]
    DriverType: typing.Type[DriverType]
    SafeSplineStoneWallCurve: typing.Type[SafeSplineStoneWallCurve]
    SafeSplineSurgeCurve: typing.Type[SafeSplineSurgeCurve]
    ShutdownProfile: typing.Type[ShutdownProfile]
    StartupProfile: typing.Type[StartupProfile]
    StoneWallCurve: typing.Type[StoneWallCurve]
    SurgeCurve: typing.Type[SurgeCurve]
