
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import java.util.function
import jpype
import jneqsim.process.dynamics
import jneqsim.process.equipment
import jneqsim.process.equipment.capacity
import jneqsim.process.equipment.compressor
import jneqsim.process.equipment.mixer
import jneqsim.process.equipment.powergeneration
import jneqsim.process.equipment.separator
import jneqsim.process.equipment.splitter
import jneqsim.process.equipment.stream
import jneqsim.process.equipment.valve
import jneqsim.process.processmodel
import jneqsim.process.util.report
import jneqsim.process.util.uncertainty
import jneqsim.thermo.system
import jneqsim.util.validation
import typing



class AccelerationMethod(java.lang.Enum['AccelerationMethod']):
    DIRECT_SUBSTITUTION: typing.ClassVar['AccelerationMethod'] = ...
    WEGSTEIN: typing.ClassVar['AccelerationMethod'] = ...
    BROYDEN: typing.ClassVar['AccelerationMethod'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'AccelerationMethod': ...
    @staticmethod
    def values() -> typing.MutableSequence['AccelerationMethod']: ...

class Adjuster(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def displayResult(self) -> None: ...
    def getAdjustedEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...
    def getAdjustedVariable(self) -> java.lang.String: ...
    def getAdjustedVariableUnit(self) -> java.lang.String: ...
    def getError(self) -> float: ...
    def getMaxAdjustedValue(self) -> float: ...
    def getMinAdjustedValue(self) -> float: ...
    def getTargetEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...
    def getTargetVariable(self) -> java.lang.String: ...
    def getTolerance(self) -> float: ...
    def isActivateWhenLess(self) -> bool: ...
    @typing.overload
    def isActive(self) -> bool: ...
    @typing.overload
    def isActive(self, boolean: bool) -> None: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setActivateWhenLess(self, boolean: bool) -> None: ...
    def setActive(self, boolean: bool) -> None: ...
    def setAdjustedEquipment(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def setAdjustedValueGetter(self, function: typing.Union[java.util.function.Function[jneqsim.process.equipment.ProcessEquipmentInterface, float], typing.Callable[[jneqsim.process.equipment.ProcessEquipmentInterface], float]]) -> None: ...
    @typing.overload
    def setAdjustedValueGetter(self, supplier: typing.Union[java.util.function.Supplier[float], typing.Callable[[], float]]) -> None: ...
    @typing.overload
    def setAdjustedValueSetter(self, biConsumer: typing.Union[java.util.function.BiConsumer[jneqsim.process.equipment.ProcessEquipmentInterface, float], typing.Callable[[jneqsim.process.equipment.ProcessEquipmentInterface, float], None]]) -> None: ...
    @typing.overload
    def setAdjustedValueSetter(self, consumer: typing.Union[java.util.function.Consumer[float], typing.Callable[[float], None]]) -> None: ...
    @typing.overload
    def setAdjustedVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def setAdjustedVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setAdjustedVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> None: ...
    def setError(self, double: float) -> None: ...
    def setMaxAdjustedValue(self, double: float) -> None: ...
    def setMinAdjustedValue(self, double: float) -> None: ...
    def setTargetEquipment(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    def setTargetValue(self, double: float) -> None: ...
    @typing.overload
    def setTargetValueCalculator(self, function: typing.Union[java.util.function.Function[jneqsim.process.equipment.ProcessEquipmentInterface, float], typing.Callable[[jneqsim.process.equipment.ProcessEquipmentInterface], float]]) -> None: ...
    @typing.overload
    def setTargetValueCalculator(self, supplier: typing.Union[java.util.function.Supplier[float], typing.Callable[[], float]]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> None: ...
    def setTolerance(self, double: float) -> None: ...
    def solved(self) -> bool: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...

class BroydenAccelerator(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    def accelerate(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def captureState(self) -> 'BroydenAccelerator.Snapshot': ...
    def getDelayIterations(self) -> int: ...
    def getDimension(self) -> int: ...
    def getInverseJacobian(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getIterationCount(self) -> int: ...
    def getMaxStepSize(self) -> float: ...
    def getRelaxationFactor(self) -> float: ...
    def getResidualNorm(self) -> float: ...
    def initialize(self, int: int) -> None: ...
    def reset(self) -> None: ...
    def restoreState(self, snapshot: 'BroydenAccelerator.Snapshot') -> None: ...
    def setDelayIterations(self, int: int) -> None: ...
    def setMaxStepSize(self, double: float) -> None: ...
    def setRelaxationFactor(self, double: float) -> None: ...
    class Snapshot(java.io.Serializable): ...

class Calculator(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def addInputVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def addInputVariable(self, *processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    def getAntiSurgeProportionalGain(self) -> float: ...
    def getInputVariable(self) -> java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    def getOutputVariable(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def runAntiSurgeCalc(self, uUID: java.util.UUID) -> None: ...
    def setAntiSurgeProportionalGain(self, double: float) -> None: ...
    @typing.overload
    def setCalculationMethod(self, runnable: typing.Union[java.lang.Runnable, typing.Callable]) -> None: ...
    @typing.overload
    def setCalculationMethod(self, biConsumer: typing.Union[java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface], typing.Callable[[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface], None]]) -> None: ...
    def setOutputVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...

class CalculatorLibrary:
    @typing.overload
    @staticmethod
    def antiSurge() -> java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    @typing.overload
    @staticmethod
    def antiSurge(double: float) -> java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    @staticmethod
    def byName(string: typing.Union[java.lang.String, str]) -> java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    @typing.overload
    @staticmethod
    def dewPointTargeting() -> java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    @typing.overload
    @staticmethod
    def dewPointTargeting(double: float) -> java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    @staticmethod
    def energyBalance() -> java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    @staticmethod
    def preset(preset: 'CalculatorLibrary.Preset') -> java.util.function.BiConsumer[java.util.ArrayList[jneqsim.process.equipment.ProcessEquipmentInterface], jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    class Preset(java.lang.Enum['CalculatorLibrary.Preset']):
        ENERGY_BALANCE: typing.ClassVar['CalculatorLibrary.Preset'] = ...
        DEW_POINT_TARGETING: typing.ClassVar['CalculatorLibrary.Preset'] = ...
        ANTI_SURGE: typing.ClassVar['CalculatorLibrary.Preset'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'CalculatorLibrary.Preset': ...
        @staticmethod
        def values() -> typing.MutableSequence['CalculatorLibrary.Preset']: ...

class ConvergenceDiagnostics(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def analyze(self) -> 'ConvergenceDiagnostics.DiagnosticReport': ...
    class AdjusterStatus(java.io.Serializable):
        name: java.lang.String = ...
        converged: bool = ...
        error: float = ...
        tolerance: float = ...
        iterations: int = ...
    class DiagnosticReport(java.io.Serializable):
        def getAdjusterStatuses(self) -> java.util.List['ConvergenceDiagnostics.AdjusterStatus']: ...
        def getRecycleStatuses(self) -> java.util.List['ConvergenceDiagnostics.RecycleStatus']: ...
        def getSuggestions(self) -> java.util.List[java.lang.String]: ...
        def isConverged(self) -> bool: ...
        def toJson(self) -> java.lang.String: ...
    class RecycleStatus(java.io.Serializable):
        name: java.lang.String = ...
        converged: bool = ...
        flowError: float = ...
        tempError: float = ...
        pressError: float = ...
        compError: float = ...
        iterations: int = ...
        dominantError: java.lang.String = ...
        flowTolerance: float = ...
        tempTolerance: float = ...

class EmissionsCalculator(java.io.Serializable):
    GWP_METHANE: typing.ClassVar[float] = ...
    GWP_NMVOC: typing.ClassVar[float] = ...
    GWP_CO2: typing.ClassVar[float] = ...
    HANDBOOK_F_CH4: typing.ClassVar[float] = ...
    HANDBOOK_F_NMVOC: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self, separator: jneqsim.process.equipment.separator.Separator): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def calculate(self) -> None: ...
    @staticmethod
    def calculateConventionalCH4(double: float, double2: float) -> float: ...
    @staticmethod
    def calculateConventionalEmissions(double: float, double2: float) -> java.util.Map[java.lang.String, float]: ...
    @staticmethod
    def calculateConventionalNMVOC(double: float, double2: float) -> float: ...
    def calculateGWMF(self, double: float, double2: float) -> float: ...
    @typing.overload
    def calculateGWR(self, double: float) -> float: ...
    @typing.overload
    @staticmethod
    def calculateGWR(double: float, double2: float) -> float: ...
    def calculateMethaneFactor(self, double: float, double2: float) -> float: ...
    def calculateNMVOCFactor(self, double: float, double2: float) -> float: ...
    def compareWithConventionalMethod(self, double: float, double2: float) -> java.util.Map[java.lang.String, typing.Any]: ...
    def generateReport(self) -> java.lang.String: ...
    def getCO2EmissionRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getCO2Equivalents(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getCumulativeCO2(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getCumulativeCO2Equivalents(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getCumulativeMethane(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getCumulativeNMVOC(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getGasCompositionMass(self) -> java.util.Map[java.lang.String, float]: ...
    def getGasCompositionMole(self) -> java.util.Map[java.lang.String, float]: ...
    def getMethaneEmissionRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getNMVOCEmissionRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getNitrogenEmissionRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTotalGasRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTotalRunTime(self) -> float: ...
    def resetCumulative(self) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def updateCumulative(self, double: float) -> None: ...

class FlowRateAdjuster(jneqsim.process.equipment.TwoPortEquipment):
    desiredGasFlow: float = ...
    desiredOilFlow: float = ...
    desiredWaterFlow: float = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def setAdjustedFlowRates(self, double: float, double2: float, double3: float, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setAdjustedFlowRates(self, double: float, double2: float, string: typing.Union[java.lang.String, str]) -> None: ...

class FlowSetter(jneqsim.process.equipment.TwoPortEquipment):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def createReferenceProcess(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getGasFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getOilFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getReferenceProcess(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getWaterFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setGasFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setOilFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSeparationPT(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], string: typing.Union[java.lang.String, str], doubleArray2: typing.Union[typing.List[float], jpype.JArray], string2: typing.Union[java.lang.String, str]) -> None: ...
    def setWaterFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class FuelGasSystem(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def addConsumer(self, string: typing.Union[java.lang.String, str], consumerType: 'FuelGasSystem.ConsumerType', double: float) -> None: ...
    @typing.overload
    def addConsumer(self, fuelGasConsumer: 'FuelGasSystem.FuelGasConsumer') -> None: ...
    def getAnnualConsumptionTonnes(self, double: float) -> float: ...
    def getConsumers(self) -> java.util.List['FuelGasSystem.FuelGasConsumer']: ...
    def getDewPoint(self) -> float: ...
    def getHeaterDutyKW(self) -> float: ...
    def getInletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getJTCooling(self) -> float: ...
    def getLowerHeatingValue(self) -> float: ...
    @typing.overload
    def getOutletPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getOutletPressure(self) -> float: ...
    def getOutletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    @typing.overload
    def getOutletTemperature(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getOutletTemperature(self) -> float: ...
    def getSuperheat(self) -> float: ...
    def getThermalPowerMW(self) -> float: ...
    def getTotalDemand(self) -> float: ...
    def getWobbeIndex(self) -> float: ...
    def isSuperheatAdequate(self, double: float) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setOutletPressure(self, double: float) -> None: ...
    def setOutletTemperature(self, double: float) -> None: ...
    def setTotalDemand(self, double: float) -> None: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    class ConsumerType(java.lang.Enum['FuelGasSystem.ConsumerType']):
        GAS_TURBINE: typing.ClassVar['FuelGasSystem.ConsumerType'] = ...
        FIRED_HEATER: typing.ClassVar['FuelGasSystem.ConsumerType'] = ...
        FLARE_PILOT: typing.ClassVar['FuelGasSystem.ConsumerType'] = ...
        HOT_OIL_HEATER: typing.ClassVar['FuelGasSystem.ConsumerType'] = ...
        REGEN_HEATER: typing.ClassVar['FuelGasSystem.ConsumerType'] = ...
        INCINERATOR: typing.ClassVar['FuelGasSystem.ConsumerType'] = ...
        def getDescription(self) -> java.lang.String: ...
        def getMaxH2Sppmv(self) -> float: ...
        def getMinSuperheatC(self) -> float: ...
        def getTypicalPressureBarg(self) -> float: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FuelGasSystem.ConsumerType': ...
        @staticmethod
        def values() -> typing.MutableSequence['FuelGasSystem.ConsumerType']: ...
    class FuelGasConsumer(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], consumerType: 'FuelGasSystem.ConsumerType', double: float): ...
        def getDemandKgh(self) -> float: ...
        def getEfficiencyPercent(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getType(self) -> 'FuelGasSystem.ConsumerType': ...
        def getUsefulThermalPowerKW(self, double: float) -> float: ...
        def isRunning(self) -> bool: ...
        def setDemandKgh(self, double: float) -> None: ...
        def setEfficiencyPercent(self, double: float) -> None: ...
        def setRunning(self, boolean: bool) -> None: ...

class GORfitter(jneqsim.process.equipment.TwoPortEquipment):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getGFV(self) -> float: ...
    def getGOR(self) -> float: ...
    @typing.overload
    def getPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getPressure(self) -> float: ...
    def getReferenceConditions(self) -> java.lang.String: ...
    @typing.overload
    def getTemperature(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getTemperature(self) -> float: ...
    def isFitAsGVF(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setFitAsGVF(self, boolean: bool) -> None: ...
    def setGOR(self, double: float) -> None: ...
    def setGVF(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    @typing.overload
    def setPressure(self, double: float) -> None: ...
    @typing.overload
    def setPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReferenceConditions(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTemperature(self, double: float) -> None: ...
    @typing.overload
    def setTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class LubeOilSystem(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    MAX_BEARING_SUPPLY_TEMPERATURE: typing.ClassVar[float] = ...
    MAX_RESERVOIR_TURNOVERS_PER_HOUR: typing.ClassVar[float] = ...
    MAX_FILTER_RATING_MICRON: typing.ClassVar[float] = ...
    MAX_CLEAN_FILTER_PRESSURE_DROP: typing.ClassVar[float] = ...
    MIN_PUMP_RATED_MARGIN: typing.ClassVar[float] = ...
    MIN_RUNDOWN_TIME: typing.ClassVar[float] = ...
    MAX_HEATER_WATT_DENSITY: typing.ClassVar[float] = ...
    MIN_DRAIN_SLOPE: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], serviceCategory: 'LubeOilSystem.ServiceCategory'): ...
    @typing.overload
    def addConsumer(self, string: typing.Union[java.lang.String, str], consumerType: 'LubeOilSystem.ConsumerType', double: float) -> 'LubeOilSystem.OilConsumer': ...
    @typing.overload
    def addConsumer(self, oilConsumer: 'LubeOilSystem.OilConsumer') -> None: ...
    def addConsumerFromShaftPower(self, string: typing.Union[java.lang.String, str], consumerType: 'LubeOilSystem.ConsumerType', double: float) -> 'LubeOilSystem.OilConsumer': ...
    def addControlOilConsumer(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> 'LubeOilSystem.OilConsumer': ...
    def getAccumulatorAllowablePressureDrop(self) -> float: ...
    def getAccumulatorPrechargePressure(self) -> float: ...
    def getAccumulatorTransferTime(self) -> float: ...
    def getAccumulatorVolume(self) -> float: ...
    def getBearingElevation(self) -> float: ...
    def getComplianceChecks(self) -> java.util.List['LubeOilSystem.ComplianceCheck']: ...
    def getConsumers(self) -> java.util.List['LubeOilSystem.OilConsumer']: ...
    def getControlOilFlow(self) -> float: ...
    def getControlOilHeaderPressure(self) -> float: ...
    def getControlValvePressureDrop(self) -> float: ...
    def getCoolerDuty(self) -> float: ...
    def getCoolerDutyPerUnit(self) -> float: ...
    def getCoolerPressureDrop(self) -> float: ...
    def getCoolingWaterFlow(self) -> float: ...
    def getCoolingWaterInletTemperature(self) -> float: ...
    def getCoolingWaterOutletTemperature(self) -> float: ...
    def getDeviations(self) -> java.util.List['LubeOilSystem.ComplianceCheck']: ...
    def getDrainPipeDiameter(self) -> float: ...
    def getDrainSlope(self) -> float: ...
    def getFilterPressureDropClean(self) -> float: ...
    def getFilterPressureDropFouled(self) -> float: ...
    def getFilterRatingMicron(self) -> float: ...
    def getHeaterMinimumArea(self) -> float: ...
    def getHeaterPower(self) -> float: ...
    def getHeaterSoakTime(self) -> float: ...
    def getLubeHeaderPressure(self) -> float: ...
    def getLubeOilFlow(self) -> float: ...
    def getMaxSupplyVelocity(self) -> float: ...
    def getMinimumStartTemperature(self) -> float: ...
    def getNormalOilFlow(self) -> float: ...
    def getNumberOfCoolers(self) -> int: ...
    def getNumberOfFilters(self) -> int: ...
    def getNumberOfPumps(self) -> int: ...
    def getOilDensity(self, double: float) -> float: ...
    def getOilDensityAtSupply(self) -> float: ...
    def getOilDynamicViscosity(self, double: float) -> float: ...
    def getOilGrade(self) -> 'LubeOilSystem.OilGrade': ...
    def getOilHeatCapacity(self, double: float) -> float: ...
    def getOilHeatCapacityAtSupply(self) -> float: ...
    def getOilKinematicViscosity(self, double: float) -> float: ...
    def getOilViscosityAtSupply(self) -> float: ...
    def getPipingPressureDrop(self) -> float: ...
    def getPumpDesignMargin(self) -> float: ...
    def getPumpDifferentialPressure(self) -> float: ...
    def getPumpDischargePressure(self) -> float: ...
    def getPumpEfficiency(self) -> float: ...
    def getPumpHydraulicPower(self) -> float: ...
    def getPumpMotorRating(self) -> float: ...
    def getPumpShaftPower(self) -> float: ...
    def getRatedPumpFlow(self) -> float: ...
    def getRequiredStartTemperature(self) -> float: ...
    def getReservoirFreeboardFraction(self) -> float: ...
    def getReservoirRetentionTime(self) -> float: ...
    def getReservoirTemperature(self) -> float: ...
    def getReservoirTotalVolume(self) -> float: ...
    def getReservoirTurnoverRate(self) -> float: ...
    def getReservoirWorkingVolume(self) -> float: ...
    def getRundownTankVolume(self) -> float: ...
    def getRundownTime(self) -> float: ...
    def getServiceCategory(self) -> 'LubeOilSystem.ServiceCategory': ...
    def getSupplyPipeDiameter(self) -> float: ...
    def getSupplyTemperature(self) -> float: ...
    def getTotalHeatLoad(self) -> float: ...
    def isAccumulatorFitted(self) -> bool: ...
    def isApiCompliant(self) -> bool: ...
    def isSystemRunning(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setAccumulatorAllowablePressureDrop(self, double: float) -> None: ...
    def setAccumulatorFitted(self, boolean: bool) -> None: ...
    def setAccumulatorTransferTime(self, double: float) -> None: ...
    def setBearingElevation(self, double: float) -> None: ...
    def setControlOilHeaderPressure(self, double: float) -> None: ...
    def setControlValvePressureDrop(self, double: float) -> None: ...
    def setCoolerPressureDrop(self, double: float) -> None: ...
    def setCoolingWaterInletTemperature(self, double: float) -> None: ...
    def setCoolingWaterOutletTemperature(self, double: float) -> None: ...
    def setDrainSlope(self, double: float) -> None: ...
    def setFilterPressureDropClean(self, double: float) -> None: ...
    def setFilterPressureDropFouled(self, double: float) -> None: ...
    def setFilterRatingMicron(self, double: float) -> None: ...
    def setHeaterSoakTime(self, double: float) -> None: ...
    def setLubeHeaderPressure(self, double: float) -> None: ...
    def setMaxSupplyVelocity(self, double: float) -> None: ...
    def setMinimumStartTemperature(self, double: float) -> None: ...
    def setNumberOfCoolers(self, int: int) -> None: ...
    def setNumberOfFilters(self, int: int) -> None: ...
    def setNumberOfPumps(self, int: int) -> None: ...
    def setOilGrade(self, oilGrade: 'LubeOilSystem.OilGrade') -> None: ...
    def setPipingPressureDrop(self, double: float) -> None: ...
    def setPumpDesignMargin(self, double: float) -> None: ...
    def setPumpEfficiency(self, double: float) -> None: ...
    def setRequiredStartTemperature(self, double: float) -> None: ...
    def setReservoirFreeboardFraction(self, double: float) -> None: ...
    def setReservoirTemperature(self, double: float) -> None: ...
    def setRundownTime(self, double: float) -> None: ...
    def setServiceCategory(self, serviceCategory: 'LubeOilSystem.ServiceCategory') -> None: ...
    def setSupplyTemperature(self, double: float) -> None: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...
    class ComplianceCheck(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], boolean: bool): ...
        def getActual(self) -> java.lang.String: ...
        def getItem(self) -> java.lang.String: ...
        def getReference(self) -> java.lang.String: ...
        def getRequirement(self) -> java.lang.String: ...
        def isCompliant(self) -> bool: ...
    class ConsumerType(java.lang.Enum['LubeOilSystem.ConsumerType']):
        JOURNAL_BEARING: typing.ClassVar['LubeOilSystem.ConsumerType'] = ...
        THRUST_BEARING: typing.ClassVar['LubeOilSystem.ConsumerType'] = ...
        GEARBOX: typing.ClassVar['LubeOilSystem.ConsumerType'] = ...
        MECHANICAL_SEAL: typing.ClassVar['LubeOilSystem.ConsumerType'] = ...
        CONTROL_OIL: typing.ClassVar['LubeOilSystem.ConsumerType'] = ...
        OTHER: typing.ClassVar['LubeOilSystem.ConsumerType'] = ...
        def getLossFraction(self) -> float: ...
        def getTemperatureRise(self) -> float: ...
        def isControlOil(self) -> bool: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'LubeOilSystem.ConsumerType': ...
        @staticmethod
        def values() -> typing.MutableSequence['LubeOilSystem.ConsumerType']: ...
    class OilConsumer(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], consumerType: 'LubeOilSystem.ConsumerType'): ...
        def getCalculatedFlow(self) -> float: ...
        def getHeatLoad(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getRequiredSupplyPressure(self) -> float: ...
        def getShaftPower(self) -> float: ...
        def getSpecifiedFlow(self) -> float: ...
        def getTemperatureRise(self) -> float: ...
        def getType(self) -> 'LubeOilSystem.ConsumerType': ...
        def setCalculatedFlow(self, double: float) -> None: ...
        def setHeatLoad(self, double: float) -> None: ...
        def setRequiredSupplyPressure(self, double: float) -> None: ...
        def setShaftPower(self, double: float) -> None: ...
        def setSpecifiedFlow(self, double: float) -> None: ...
        def setTemperatureRise(self, double: float) -> None: ...
    class OilGrade(java.lang.Enum['LubeOilSystem.OilGrade']):
        ISO_VG_32: typing.ClassVar['LubeOilSystem.OilGrade'] = ...
        ISO_VG_46: typing.ClassVar['LubeOilSystem.OilGrade'] = ...
        ISO_VG_68: typing.ClassVar['LubeOilSystem.OilGrade'] = ...
        ISO_VG_100: typing.ClassVar['LubeOilSystem.OilGrade'] = ...
        def getDensity15(self) -> float: ...
        def getViscosity100(self) -> float: ...
        def getViscosity40(self) -> float: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'LubeOilSystem.OilGrade': ...
        @staticmethod
        def values() -> typing.MutableSequence['LubeOilSystem.OilGrade']: ...
    class ServiceCategory(java.lang.Enum['LubeOilSystem.ServiceCategory']):
        GENERAL_PURPOSE: typing.ClassVar['LubeOilSystem.ServiceCategory'] = ...
        SPECIAL_PURPOSE: typing.ClassVar['LubeOilSystem.ServiceCategory'] = ...
        def getMinRetentionMinutes(self) -> float: ...
        def getReference(self) -> java.lang.String: ...
        def isRundownTankRequired(self) -> bool: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'LubeOilSystem.ServiceCategory': ...
        @staticmethod
        def values() -> typing.MutableSequence['LubeOilSystem.ServiceCategory']: ...

class MPFMfitter(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getGFV(self) -> float: ...
    def getGOR(self) -> float: ...
    @typing.overload
    def getPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getPressure(self) -> float: ...
    def getReferenceConditions(self) -> java.lang.String: ...
    def getReferenceFluidPackage(self) -> jneqsim.thermo.system.SystemInterface: ...
    @typing.overload
    def getTemperature(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getTemperature(self) -> float: ...
    def isFitAsGVF(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setFitAsGVF(self, boolean: bool) -> None: ...
    def setGOR(self, double: float) -> None: ...
    def setGVF(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    @typing.overload
    def setPressure(self, double: float) -> None: ...
    @typing.overload
    def setPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReferenceConditions(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReferenceFluidPackage(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    @typing.overload
    def setTemperature(self, double: float) -> None: ...
    @typing.overload
    def setTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class MoleFractionControllerUtil(jneqsim.process.equipment.TwoPortEquipment):
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    def getMolesChange(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setComponentRate(self, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str]) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setMoleFraction(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setRelativeMoleFractionReduction(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...

class MultiVariableAdjuster(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addAdjustedVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def addTargetSpecification(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def addTargetSpecification(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> None: ...
    def getIterations(self) -> int: ...
    def getMaxResidual(self) -> float: ...
    def getNumberOfVariables(self) -> int: ...
    def isConverged(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setMaxIterations(self, int: int) -> None: ...
    def setTolerance(self, double: float) -> None: ...
    def setVariableBounds(self, int: int, double: float, double2: float) -> None: ...
    def solved(self) -> bool: ...

class NeqSimUnit(jneqsim.process.equipment.TwoPortEquipment):
    numberOfNodes: int = ...
    interfacialArea: float = ...
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def getEquipment(self) -> java.lang.String: ...
    def getID(self) -> float: ...
    def getInterfacialArea(self) -> float: ...
    def getLength(self) -> float: ...
    def getNumberOfNodes(self) -> int: ...
    def getOuterTemperature(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def runAnnular(self) -> None: ...
    def runDroplet(self) -> None: ...
    def runStratified(self) -> None: ...
    def setEquipment(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setID(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setLength(self, double: float) -> None: ...
    def setNumberOfNodes(self, int: int) -> None: ...
    def setOuterTemperature(self, double: float) -> None: ...

class PressureDrop(jneqsim.process.equipment.valve.ThrottlingValve):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setPressureDrop(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class ProducedWaterDegassingSystem(java.io.Serializable):
    KIJ_WATER_CO2_BASE: typing.ClassVar[float] = ...
    KIJ_WATER_CO2_TEMP: typing.ClassVar[float] = ...
    KIJ_WATER_CH4_BASE: typing.ClassVar[float] = ...
    KIJ_WATER_CH4_TEMP: typing.ClassVar[float] = ...
    KIJ_WATER_C2H6: typing.ClassVar[float] = ...
    KIJ_WATER_C3H8: typing.ClassVar[float] = ...
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def build(self) -> None: ...
    def getCFUEmissions(self) -> EmissionsCalculator: ...
    def getCaissonEmissions(self) -> EmissionsCalculator: ...
    def getDegasserEmissions(self) -> EmissionsCalculator: ...
    def getEmissionsReport(self) -> java.lang.String: ...
    def getMethodComparisonReport(self) -> java.lang.String: ...
    def getProcessSystem(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getTotalCO2EmissionRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTotalCO2Equivalents(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTotalMethaneEmissionRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTotalNMVOCEmissionRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getValidationResults(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setCFUPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setCaissonPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDegasserPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setDissolvedGasComposition(self, stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def setDissolvedGasComposition(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]]) -> None: ...
    def setInletPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLabGWR(self, double: float) -> None: ...
    def setLabGasComposition(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]]) -> None: ...
    def setSalinity(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTunedInteractionParameters(self, boolean: bool) -> None: ...
    def setWaterFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setWaterTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class ProductionRateFitter(jneqsim.process.equipment.TwoPortEquipment):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getGOR(self) -> float: ...
    def getReferenceConditions(self) -> java.lang.String: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setGOR(self, double: float) -> None: ...
    def setGasRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setReferenceConditions(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setWaterDensity(self, double: float) -> None: ...
    def setWaterRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class Recycle(jneqsim.process.equipment.ProcessEquipmentBaseClass, jneqsim.process.equipment.mixer.MixerInterface, jneqsim.process.dynamics.TransientStateParticipant['Recycle.TransientState']):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def applyAutoAbsoluteFlowTolerance(self, double: float) -> bool: ...
    def applyAutoAdaptiveAcceleration(self) -> bool: ...
    def calcMixStreamEnthalpy(self) -> float: ...
    def captureTransientState(self) -> 'Recycle.TransientState': ...
    def compositionBalanceCheck(self) -> float: ...
    def displayResult(self) -> None: ...
    def flowBalanceCheck(self) -> float: ...
    def getAbsoluteFlowChange(self) -> float: ...
    def getAbsoluteFlowTolerance(self) -> float: ...
    def getAccelerationMethod(self) -> AccelerationMethod: ...
    def getBroydenAccelerator(self) -> BroydenAccelerator: ...
    def getCompositionTolerance(self) -> float: ...
    def getDownstreamProperty(self) -> java.util.ArrayList[java.lang.String]: ...
    def getErrorComposition(self) -> float: ...
    def getErrorFlow(self) -> float: ...
    def getErrorPressure(self) -> float: ...
    def getErrorTemperature(self) -> float: ...
    def getFlowTolerance(self) -> float: ...
    def getInletStreams(self) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getIterations(self) -> int: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMaxIterations(self) -> int: ...
    @typing.overload
    def getMinimumFlow(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getMinimumFlow(self) -> float: ...
    def getOutStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOutletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOutletStreams(self) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getPressureTolerance(self) -> float: ...
    def getPriority(self) -> int: ...
    def getStream(self, int: int) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getTemperatureTolerance(self) -> float: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def getWegsteinDelayIterations(self) -> int: ...
    def getWegsteinQFactors(self) -> typing.MutableSequence[float]: ...
    def getWegsteinQMax(self) -> float: ...
    def getWegsteinQMin(self) -> float: ...
    def guessTemperature(self) -> float: ...
    def initiateDownstreamProperties(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def isAccelerationAutoUpgraded(self) -> bool: ...
    def isAdaptiveAcceleration(self) -> bool: ...
    def isAdaptiveAccelerationAutoManaged(self) -> bool: ...
    def mixStream(self) -> None: ...
    def pressureBalanceCheck(self) -> float: ...
    def removeInputStream(self, int: int) -> None: ...
    def replaceStream(self, int: int, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def resetAccelerationState(self) -> None: ...
    def resetAdaptiveAcceleration(self) -> None: ...
    def resetAutoAbsoluteFlowTolerance(self) -> bool: ...
    def resetAutoAdaptiveAcceleration(self) -> bool: ...
    def resetIterations(self) -> None: ...
    def restoreTransientState(self, transientState: 'Recycle.TransientState') -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setAbsoluteFlowTolerance(self, double: float) -> None: ...
    def setAccelerationMethod(self, accelerationMethod: AccelerationMethod) -> None: ...
    def setAdaptiveAcceleration(self, boolean: bool) -> None: ...
    def setCompositionTolerance(self, double: float) -> None: ...
    def setDownstreamProperties(self) -> None: ...
    @typing.overload
    def setDownstreamProperty(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setDownstreamProperty(self, arrayList: java.util.ArrayList[typing.Union[java.lang.String, str]]) -> None: ...
    def setErrorCompositon(self, double: float) -> None: ...
    def setErrorFlow(self, double: float) -> None: ...
    def setErrorPressure(self, double: float) -> None: ...
    def setErrorTemperature(self, double: float) -> None: ...
    def setFlowTolerance(self, double: float) -> None: ...
    def setMaxIterations(self, int: int) -> None: ...
    @typing.overload
    def setMinimumFlow(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setMinimumFlow(self, double: float) -> None: ...
    def setOutletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setPressure(self, double: float) -> None: ...
    def setPressureTolerance(self, double: float) -> None: ...
    def setPriority(self, int: int) -> None: ...
    def setTemperature(self, double: float) -> None: ...
    def setTemperatureTolerance(self, double: float) -> None: ...
    def setTolerance(self, double: float) -> None: ...
    def setWegsteinDelayIterations(self, int: int) -> None: ...
    def setWegsteinQMax(self, double: float) -> None: ...
    def setWegsteinQMin(self, double: float) -> None: ...
    def solved(self) -> bool: ...
    def temperatureBalanceCheck(self) -> float: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...
    class TransientState(java.io.Serializable): ...

class RecycleController(java.io.Serializable):
    def __init__(self): ...
    def addRecycle(self, recycle: Recycle) -> None: ...
    def captureTransientState(self) -> 'RecycleController.Snapshot': ...
    def clear(self) -> None: ...
    def doSolveRecycle(self, recycle: Recycle) -> bool: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getConvergenceDiagnostics(self) -> java.lang.String: ...
    def getConvergenceJacobian(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getCoordinatedAccelerator(self) -> BroydenAccelerator: ...
    def getCurrentPriorityLevel(self) -> int: ...
    def getMaxNormalizedError(self) -> float: ...
    def getMaxResidualError(self) -> float: ...
    def getRecycleCount(self) -> int: ...
    def getRecycles(self) -> java.util.List[Recycle]: ...
    def getRecyclesAtCurrentPriority(self) -> java.util.List[Recycle]: ...
    def getTearStreamSensitivityMatrix(self) -> jneqsim.process.util.uncertainty.SensitivityMatrix: ...
    def getTearStreamVariableNames(self) -> java.util.List[java.lang.String]: ...
    def getTotalIterations(self) -> int: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def hasHigherPriorityLevel(self) -> bool: ...
    def hasLoverPriorityLevel(self) -> bool: ...
    def hasSensitivityData(self) -> bool: ...
    def hashCode(self) -> int: ...
    def init(self) -> None: ...
    def isHighestPriority(self, recycle: Recycle) -> bool: ...
    def isUseCoordinatedAcceleration(self) -> bool: ...
    def nextPriorityLevel(self) -> None: ...
    def resetAll(self) -> None: ...
    def resetPriorityLevel(self) -> None: ...
    def restoreTransientState(self, snapshot: 'RecycleController.Snapshot') -> None: ...
    def runSimultaneousAcceleration(self) -> bool: ...
    @typing.overload
    def setAccelerationMethod(self, accelerationMethod: AccelerationMethod) -> None: ...
    @typing.overload
    def setAccelerationMethod(self, accelerationMethod: AccelerationMethod, int: int) -> None: ...
    def setCurrentPriorityLevel(self, int: int) -> None: ...
    def setUseCoordinatedAcceleration(self, boolean: bool) -> None: ...
    def solvedAll(self) -> bool: ...
    def solvedCurrentPriorityLevel(self) -> bool: ...
    class Snapshot(java.io.Serializable): ...

class SetPoint(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string2: typing.Union[java.lang.String, str], processEquipmentInterface2: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def displayResult(self) -> None: ...
    def getMultiplier(self) -> float: ...
    def getOffset(self) -> float: ...
    def getSourceEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...
    def getTargetEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setMultiplier(self, double: float) -> None: ...
    def setOffset(self, double: float) -> None: ...
    def setSourceValueCalculator(self, function: typing.Union[java.util.function.Function[jneqsim.process.equipment.ProcessEquipmentInterface, float], typing.Callable[[jneqsim.process.equipment.ProcessEquipmentInterface], float]]) -> None: ...
    @typing.overload
    def setSourceVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def setSourceVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTargetVariable(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> None: ...

class Setter(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addParameter(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float) -> None: ...
    @typing.overload
    def addTargetEquipment(self, list: java.util.List[jneqsim.process.equipment.ProcessEquipmentInterface]) -> None: ...
    @typing.overload
    def addTargetEquipment(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    def getParameters(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...

class SpreadsheetBlock(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addConstantCell(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def addExportCell(self, string: typing.Union[java.lang.String, str], processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, exportWriter: typing.Union['SpreadsheetBlock.ExportWriter', typing.Callable]) -> None: ...
    def addFormulaCell(self, string: typing.Union[java.lang.String, str], function: typing.Union[java.util.function.Function[typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], float], typing.Callable[[typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]]], float]]) -> None: ...
    def addImportCell(self, string: typing.Union[java.lang.String, str], processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, function: typing.Union[java.util.function.Function[jneqsim.process.equipment.ProcessEquipmentInterface, float], typing.Callable[[jneqsim.process.equipment.ProcessEquipmentInterface], float]]) -> None: ...
    def addStreamImportCell(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, function: typing.Union[java.util.function.Function[jneqsim.process.equipment.stream.StreamInterface, float], typing.Callable[[jneqsim.process.equipment.stream.StreamInterface], float]]) -> None: ...
    def getAllCellValues(self) -> java.util.Map[java.lang.String, float]: ...
    def getCellNames(self) -> java.util.List[java.lang.String]: ...
    def getCellValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    class ExportWriter(java.io.Serializable):
        def apply(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, double: float) -> None: ...

class StreamSaturatorUtil(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def isMultiPhase(self) -> bool: ...
    def needRecalculation(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setApprachToSaturation(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setMultiPhase(self, boolean: bool) -> None: ...

class StreamTransition(jneqsim.process.equipment.TwoPortEquipment):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...

class UnisimCalculator(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def addStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def getCalculationMode(self) -> java.lang.String: ...
    def getInletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getInletStreams(self) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    def getOutStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOutletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOutletStreams(self) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    @typing.overload
    def getPressure(self) -> float: ...
    @typing.overload
    def getPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getSourceOperationType(self) -> java.lang.String: ...
    @typing.overload
    def getTemperature(self) -> float: ...
    @typing.overload
    def getTemperature(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setCalculationMode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setMolarComposition(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setOutletFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setOutletPressure(self, double: float) -> None: ...
    @typing.overload
    def setOutletPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setOutletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    @typing.overload
    def setOutletTemperature(self, double: float) -> None: ...
    @typing.overload
    def setOutletTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setPressure(self, double: float) -> None: ...
    @typing.overload
    def setPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSourceOperationType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setTemperature(self, double: float) -> None: ...
    @typing.overload
    def setTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class UtilityAirSystem(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], double: float): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], double: float, airQualityClass: 'UtilityAirSystem.AirQualityClass'): ...
    @typing.overload
    def addConsumer(self, string: typing.Union[java.lang.String, str], double: float, airQualityClass: 'UtilityAirSystem.AirQualityClass') -> None: ...
    @typing.overload
    def addConsumer(self, airConsumer: 'UtilityAirSystem.AirConsumer') -> None: ...
    def autoSize(self) -> None: ...
    def calculateAnnualOperatingCost(self, double: float, double2: float) -> float: ...
    def getActualDewPoint(self) -> float: ...
    def getCompressorPowerKW(self) -> float: ...
    def getCompressorType(self) -> 'UtilityAirSystem.CompressorType': ...
    def getCondensateVolume(self) -> float: ...
    def getDischargePressure(self) -> float: ...
    def getDryerPurgeLoss(self) -> float: ...
    def getDryerType(self) -> 'UtilityAirSystem.DryerType': ...
    def getInletRelativeHumidity(self) -> float: ...
    def getInletTemperature(self) -> float: ...
    def getNumberOfCompressors(self) -> int: ...
    def getReceiverHoldupMinutes(self) -> float: ...
    def getReceiverVolume(self) -> float: ...
    def getSpecificEnergy(self) -> float: ...
    def getTargetQuality(self) -> 'UtilityAirSystem.AirQualityClass': ...
    def getTotalAirDemand(self) -> float: ...
    def isQualityTargetMet(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setCompressorType(self, compressorType: 'UtilityAirSystem.CompressorType') -> None: ...
    def setDischargePressure(self, double: float) -> None: ...
    def setDryerType(self, dryerType: 'UtilityAirSystem.DryerType') -> None: ...
    def setInletRelativeHumidity(self, double: float) -> None: ...
    def setInletTemperature(self, double: float) -> None: ...
    def setNumberOfCompressors(self, int: int) -> None: ...
    def setReceiverVolume(self, double: float) -> None: ...
    def setTargetQuality(self, airQualityClass: 'UtilityAirSystem.AirQualityClass') -> None: ...
    def setTotalAirDemand(self, double: float) -> None: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    class AirConsumer(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, airQualityClass: 'UtilityAirSystem.AirQualityClass'): ...
        def getDemandNm3h(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getRequiredQuality(self) -> 'UtilityAirSystem.AirQualityClass': ...
        def isCritical(self) -> bool: ...
        def setCritical(self, boolean: bool) -> None: ...
        def setDemandNm3h(self, double: float) -> None: ...
        def setRequiredQuality(self, airQualityClass: 'UtilityAirSystem.AirQualityClass') -> None: ...
    class AirQualityClass(java.lang.Enum['UtilityAirSystem.AirQualityClass']):
        CLASS_1: typing.ClassVar['UtilityAirSystem.AirQualityClass'] = ...
        CLASS_2: typing.ClassVar['UtilityAirSystem.AirQualityClass'] = ...
        CLASS_3: typing.ClassVar['UtilityAirSystem.AirQualityClass'] = ...
        CLASS_4: typing.ClassVar['UtilityAirSystem.AirQualityClass'] = ...
        CLASS_5: typing.ClassVar['UtilityAirSystem.AirQualityClass'] = ...
        def getMaxDewPointC(self) -> float: ...
        def getMaxOilMgM3(self) -> float: ...
        def getMaxParticleSizeMicron(self) -> float: ...
        def getTypicalUse(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'UtilityAirSystem.AirQualityClass': ...
        @staticmethod
        def values() -> typing.MutableSequence['UtilityAirSystem.AirQualityClass']: ...
    class CompressorType(java.lang.Enum['UtilityAirSystem.CompressorType']):
        ROTARY_SCREW: typing.ClassVar['UtilityAirSystem.CompressorType'] = ...
        RECIPROCATING: typing.ClassVar['UtilityAirSystem.CompressorType'] = ...
        CENTRIFUGAL: typing.ClassVar['UtilityAirSystem.CompressorType'] = ...
        SCROLL: typing.ClassVar['UtilityAirSystem.CompressorType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'UtilityAirSystem.CompressorType': ...
        @staticmethod
        def values() -> typing.MutableSequence['UtilityAirSystem.CompressorType']: ...
    class DryerType(java.lang.Enum['UtilityAirSystem.DryerType']):
        REFRIGERATED: typing.ClassVar['UtilityAirSystem.DryerType'] = ...
        DESICCANT_HEATLESS: typing.ClassVar['UtilityAirSystem.DryerType'] = ...
        DESICCANT_HEATED: typing.ClassVar['UtilityAirSystem.DryerType'] = ...
        MEMBRANE: typing.ClassVar['UtilityAirSystem.DryerType'] = ...
        HYBRID: typing.ClassVar['UtilityAirSystem.DryerType'] = ...
        def getAchievableDewPointC(self) -> float: ...
        def getAirYieldFraction(self) -> float: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'UtilityAirSystem.DryerType': ...
        @staticmethod
        def values() -> typing.MutableSequence['UtilityAirSystem.DryerType']: ...

class AntiSurgeCalculator(Calculator):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], compressor: jneqsim.process.equipment.compressor.Compressor, splitter: jneqsim.process.equipment.splitter.Splitter): ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...

class CompressorShaftCalculator(Calculator, jneqsim.process.equipment.capacity.CapacityConstrainedEquipment):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], compressorShaft: jneqsim.process.equipment.compressor.CompressorShaft, compressor2: jneqsim.process.equipment.compressor.Compressor, double: float, string2: typing.Union[java.lang.String, str]): ...
    def getLastSolveResult(self) -> jneqsim.process.equipment.compressor.CompressorShaft.SolveResult: ...
    def getPressureControl(self) -> jneqsim.process.equipment.compressor.CompressorShaft.PressureControl: ...
    def getShaft(self) -> jneqsim.process.equipment.compressor.CompressorShaft: ...
    def getShaftPowerUtilization(self) -> float: ...
    def getSpeed(self) -> float: ...
    def getTotalPower(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def isFeasible(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setMaxShaftPower(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setMaxStepFraction(self, double: float) -> None: ...
    def setMechanicalEfficiency(self, double: float) -> None: ...
    def setPressureControl(self, pressureControl: jneqsim.process.equipment.compressor.CompressorShaft.PressureControl) -> None: ...
    def setPressureTolerance(self, double: float) -> None: ...
    def setSpeedBounds(self, double: float, double2: float) -> None: ...
    def setTurbineDriver(self, gasTurbine: jneqsim.process.equipment.powergeneration.GasTurbine) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.util")``.

    AccelerationMethod: typing.Type[AccelerationMethod]
    Adjuster: typing.Type[Adjuster]
    AntiSurgeCalculator: typing.Type[AntiSurgeCalculator]
    BroydenAccelerator: typing.Type[BroydenAccelerator]
    Calculator: typing.Type[Calculator]
    CalculatorLibrary: typing.Type[CalculatorLibrary]
    CompressorShaftCalculator: typing.Type[CompressorShaftCalculator]
    ConvergenceDiagnostics: typing.Type[ConvergenceDiagnostics]
    EmissionsCalculator: typing.Type[EmissionsCalculator]
    FlowRateAdjuster: typing.Type[FlowRateAdjuster]
    FlowSetter: typing.Type[FlowSetter]
    FuelGasSystem: typing.Type[FuelGasSystem]
    GORfitter: typing.Type[GORfitter]
    LubeOilSystem: typing.Type[LubeOilSystem]
    MPFMfitter: typing.Type[MPFMfitter]
    MoleFractionControllerUtil: typing.Type[MoleFractionControllerUtil]
    MultiVariableAdjuster: typing.Type[MultiVariableAdjuster]
    NeqSimUnit: typing.Type[NeqSimUnit]
    PressureDrop: typing.Type[PressureDrop]
    ProducedWaterDegassingSystem: typing.Type[ProducedWaterDegassingSystem]
    ProductionRateFitter: typing.Type[ProductionRateFitter]
    Recycle: typing.Type[Recycle]
    RecycleController: typing.Type[RecycleController]
    SetPoint: typing.Type[SetPoint]
    Setter: typing.Type[Setter]
    SpreadsheetBlock: typing.Type[SpreadsheetBlock]
    StreamSaturatorUtil: typing.Type[StreamSaturatorUtil]
    StreamTransition: typing.Type[StreamTransition]
    UnisimCalculator: typing.Type[UnisimCalculator]
    UtilityAirSystem: typing.Type[UtilityAirSystem]
