
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.electricaldesign
import typing



class MotorMechanicalDesign(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float): ...
    @typing.overload
    def __init__(self, electricalDesign: jneqsim.process.electricaldesign.ElectricalDesign): ...
    def calcDesign(self) -> None: ...
    def getAltitudeM(self) -> float: ...
    def getAmbientTemperatureC(self) -> float: ...
    def getAppliedStandards(self) -> java.util.List[java.lang.String]: ...
    def getBearingL10LifeHours(self) -> float: ...
    def getBearingType(self) -> java.lang.String: ...
    def getCombinedDeratingFactor(self) -> float: ...
    def getCoolingCode(self) -> java.lang.String: ...
    def getCoolingDescription(self) -> java.lang.String: ...
    def getDeratedPowerKW(self) -> float: ...
    def getDesignNotes(self) -> java.util.List[java.lang.String]: ...
    def getEnclosureType(self) -> java.lang.String: ...
    def getExMarking(self) -> java.lang.String: ...
    def getFoundationType(self) -> java.lang.String: ...
    def getHeatDissipationKW(self) -> float: ...
    def getIpRating(self) -> java.lang.String: ...
    def getMaxVibrationMmS(self) -> float: ...
    def getMotorStandard(self) -> java.lang.String: ...
    def getMotorWeightKg(self) -> float: ...
    def getPoles(self) -> int: ...
    def getRatedSpeedRPM(self) -> float: ...
    def getRequiredFoundationMassKg(self) -> float: ...
    def getShaftPowerKW(self) -> float: ...
    def getSoundPowerLevelDbA(self) -> float: ...
    def getSoundPressureLevelAt1mDbA(self) -> float: ...
    def getTotalFoundationLoadKN(self) -> float: ...
    def getVibrationZone(self) -> java.lang.String: ...
    def isHasVFD(self) -> bool: ...
    def isNoiseWithinNorsokLimit(self) -> bool: ...
    def setAltitudeM(self, double: float) -> None: ...
    def setAmbientTemperatureC(self, double: float) -> None: ...
    def setFoundationWeightRatio(self, double: float) -> None: ...
    def setFrequencyHz(self, double: float) -> None: ...
    def setGasGroup(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setHasVFD(self, boolean: bool) -> None: ...
    def setHazardousZone(self, int: int) -> None: ...
    def setMotorStandard(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPoles(self, int: int) -> None: ...
    def setRatedSpeedRPM(self, double: float) -> None: ...
    def setShaftPowerKW(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.motor")``.

    MotorMechanicalDesign: typing.Type[MotorMechanicalDesign]
