import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.capacity
import jneqsim.process.equipment.stream
import jneqsim.process.mechanicaldesign
import jneqsim.process.util.report
import jneqsim.util.validation
import typing

class BiogasUpgrader(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ): ...
    def getBiomethaneCO2Percent(self) -> float: ...
    def getBiomethaneFlowNm3PerHr(self) -> float: ...
    def getBiomethaneMethanePercent(self) -> float: ...
    def getBiomethaneOutStream(
        self,
    ) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getEnergyConsumptionKW(self) -> float: ...
    def getInletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getInletStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getMethaneSlipPercent(self) -> float: ...
    def getOffgasOutStream(
        self,
    ) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOutletStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getRawBiogasFlowNm3PerHr(self) -> float: ...
    def getResults(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getTechnology(self) -> "BiogasUpgrader.UpgradingTechnology": ...
    def getWobbeIndex(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setCO2RemovalEfficiency(self, double: float) -> None: ...
    def setH2SRemovalEfficiency(self, double: float) -> None: ...
    def setInletStream(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> None: ...
    def setMethaneRecovery(self, double: float) -> None: ...
    def setOutletPressure(self, double: float) -> None: ...
    def setSpecificEnergy(self, double: float) -> None: ...
    def setTechnology(
        self, upgradingTechnology: "BiogasUpgrader.UpgradingTechnology"
    ) -> None: ...
    @typing.overload
    def toJson(
        self, reportConfig: jneqsim.process.util.report.ReportConfig
    ) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    def toString(self) -> java.lang.String: ...

    class UpgradingTechnology(java.lang.Enum["BiogasUpgrader.UpgradingTechnology"]):
        WATER_SCRUBBING: typing.ClassVar["BiogasUpgrader.UpgradingTechnology"] = ...
        AMINE_SCRUBBING: typing.ClassVar["BiogasUpgrader.UpgradingTechnology"] = ...
        MEMBRANE: typing.ClassVar["BiogasUpgrader.UpgradingTechnology"] = ...
        PSA: typing.ClassVar["BiogasUpgrader.UpgradingTechnology"] = ...
        def getCo2RemovalEfficiency(self) -> float: ...
        def getH2sRemovalEfficiency(self) -> float: ...
        def getMethaneRecovery(self) -> float: ...
        def getSpecificEnergyKWhPerNm3(self) -> float: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "BiogasUpgrader.UpgradingTechnology": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["BiogasUpgrader.UpgradingTechnology"]
        ): ...

class ComponentCaptureUnit(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ): ...
    def getActualCaptureFraction(self) -> float: ...
    def getCaptureFraction(self) -> float: ...
    def getCapturedComponentMoleFlow(self) -> float: ...
    def getCapturedStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getComponentName(self) -> java.lang.String: ...
    def getInletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getInletStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getOutletStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getResults(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getTreatedComponentMoleFlow(self) -> float: ...
    def getTreatedStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setCaptureFraction(self, double: float) -> None: ...
    def setComponentName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInletStream(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> None: ...
    @typing.overload
    def toJson(
        self, reportConfig: jneqsim.process.util.report.ReportConfig
    ) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...

class ComponentSplitter(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ): ...
    def displayResult(self) -> None: ...
    def getInletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getInletStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getOutletStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getSplitFactors(self) -> typing.MutableSequence[float]: ...
    def getSplitNumber(self) -> int: ...
    def getSplitStream(
        self, int: int
    ) -> jneqsim.process.equipment.stream.StreamInterface: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setInletStream(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> None: ...
    def setSplitFactors(
        self, doubleArray: typing.Union[typing.List[float], jpype.JArray]
    ) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(
        self, reportConfig: jneqsim.process.util.report.ReportConfig
    ) -> java.lang.String: ...

class SplitterInterface(jneqsim.process.equipment.ProcessEquipmentInterface):
    def equals(self, object: typing.Any) -> bool: ...
    def getSplitStream(
        self, int: int
    ) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def hashCode(self) -> int: ...
    def setInletStream(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> None: ...
    def setSplitNumber(self, int: int) -> None: ...

class Splitter(
    jneqsim.process.equipment.ProcessEquipmentBaseClass,
    SplitterInterface,
    jneqsim.process.equipment.capacity.CapacityConstrainedEquipment,
):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        int: int,
    ): ...
    def addCapacityConstraint(
        self, capacityConstraint: jneqsim.process.equipment.capacity.CapacityConstraint
    ) -> None: ...
    def calcSplitFactors(self) -> None: ...
    def clearCapacityConstraints(self) -> None: ...
    def displayResult(self) -> None: ...
    def getBottleneckConstraint(
        self,
    ) -> jneqsim.process.equipment.capacity.CapacityConstraint: ...
    def getCapacityConstraints(
        self,
    ) -> java.util.Map[
        java.lang.String, jneqsim.process.equipment.capacity.CapacityConstraint
    ]: ...
    def getDesignPressureDrop(self) -> float: ...
    def getFlowRates(self) -> typing.MutableSequence[float]: ...
    def getFlowUnit(self) -> java.lang.String: ...
    def getInletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getInletStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMaxDesignVelocity(self) -> float: ...
    def getMaxUtilization(self) -> float: ...
    def getMechanicalDesign(
        self,
    ) -> jneqsim.process.mechanicaldesign.MechanicalDesign: ...
    def getOutletStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getSplitFactor(self, int: int) -> float: ...
    def getSplitFactors(self) -> typing.MutableSequence[float]: ...
    def getSplitNumber(self) -> int: ...
    def getSplitStream(
        self, int: int
    ) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def initMechanicalDesign(self) -> None: ...
    def isCapacityAnalysisEnabled(self) -> bool: ...
    def isCapacityExceeded(self) -> bool: ...
    def isHardLimitExceeded(self) -> bool: ...
    def needRecalculation(self) -> bool: ...
    def removeCapacityConstraint(
        self, string: typing.Union[java.lang.String, str]
    ) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setCapacityAnalysisEnabled(self, boolean: bool) -> None: ...
    def setDesignPressureDrop(self, double: float) -> None: ...
    def setFlowRates(
        self,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        string: typing.Union[java.lang.String, str],
    ) -> None: ...
    def setInletStream(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> None: ...
    def setMaxDesignVelocity(self, double: float) -> None: ...
    def setSplitFactors(
        self, doubleArray: typing.Union[typing.List[float], jpype.JArray]
    ) -> None: ...
    def setSplitNumber(self, int: int) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(
        self, reportConfig: jneqsim.process.util.report.ReportConfig
    ) -> java.lang.String: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.splitter")``.

    BiogasUpgrader: typing.Type[BiogasUpgrader]
    ComponentCaptureUnit: typing.Type[ComponentCaptureUnit]
    ComponentSplitter: typing.Type[ComponentSplitter]
    Splitter: typing.Type[Splitter]
    SplitterInterface: typing.Type[SplitterInterface]
