
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import jpype
import typing



class Controller(java.io.Serializable):
    def computeAction(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def getName(self) -> java.lang.String: ...
    def reset(self) -> None: ...

class BangBangController(Controller):
    def __init__(self, string: typing.Union[java.lang.String, str], int: int, double: float, double2: float, double3: float, double4: float): ...
    def computeAction(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def getName(self) -> java.lang.String: ...
    def reset(self) -> None: ...

class PIDController(Controller):
    def __init__(self, string: typing.Union[java.lang.String, str], int: int, double: float, double2: float, double3: float, double4: float, double5: float, double6: float): ...
    def computeAction(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def getIntegral(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def reset(self) -> None: ...

class ProportionalController(Controller):
    def __init__(self, string: typing.Union[java.lang.String, str], int: int, double: float, double2: float, double3: float): ...
    def computeAction(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def getName(self) -> java.lang.String: ...

class RandomController(Controller):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], long: int): ...
    def computeAction(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def getName(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.ml.controllers")``.

    BangBangController: typing.Type[BangBangController]
    Controller: typing.Type[Controller]
    PIDController: typing.Type[PIDController]
    ProportionalController: typing.Type[ProportionalController]
    RandomController: typing.Type[RandomController]
