import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.heatexchanger
import jneqsim.process.mechanicaldesign
import typing

class BellDelawareMethod:
    @staticmethod
    def calcBypassArea(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def calcCorrectedHTC(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
    ) -> float: ...
    @staticmethod
    def calcCrossflowArea(
        double: float, double2: float, double3: float, double4: float
    ) -> float: ...
    @staticmethod
    def calcIdealCrossflowDP(
        int: int, double: float, double2: float, double3: float, boolean: bool
    ) -> float: ...
    @staticmethod
    def calcIdealCrossflowHTC(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
    ) -> float: ...
    @staticmethod
    def calcJb(
        double: float, double2: float, boolean: bool, int: int, int2: int
    ) -> float: ...
    @staticmethod
    def calcJc(double: float) -> float: ...
    @staticmethod
    def calcJl(
        double: float,
        double2: float,
        double3: float,
        int: int,
        double4: float,
        double5: float,
    ) -> float: ...
    @staticmethod
    def calcJr(double: float, int: int) -> float: ...
    @staticmethod
    def calcJs(double: float, double2: float, double3: float, int: int) -> float: ...
    @staticmethod
    def calcKernShellSideHTC(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
    ) -> float: ...
    @staticmethod
    def calcKernShellSidePressureDrop(
        double: float,
        double2: float,
        double3: float,
        int: int,
        double4: float,
        double5: float,
        double6: float,
    ) -> float: ...
    @staticmethod
    def calcRb(
        double: float, double2: float, boolean: bool, int: int, int2: int
    ) -> float: ...
    @staticmethod
    def calcRl(
        double: float,
        double2: float,
        double3: float,
        int: int,
        double4: float,
        double5: float,
    ) -> float: ...
    @staticmethod
    def calcShellEquivDiameter(
        double: float, double2: float, boolean: bool
    ) -> float: ...
    @staticmethod
    def calcWindowDP(
        double: float, double2: float, double3: float, int: int
    ) -> float: ...
    @staticmethod
    def estimateCrossflowFraction(double: float) -> float: ...
    @staticmethod
    def estimateTubeRowsCrossflow(
        double: float, double2: float, double3: float, boolean: bool
    ) -> int: ...

class BoilingHeatTransfer:
    @staticmethod
    def calcAverageHTC(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
        double10: float,
        double11: float,
        int: int,
    ) -> float: ...
    @staticmethod
    def calcChenEnhancementFactor(double: float) -> float: ...
    @staticmethod
    def calcChenHTC(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
        double10: float,
        double11: float,
        double12: float,
        double13: float,
    ) -> float: ...
    @staticmethod
    def calcChenSuppressionFactor(double: float) -> float: ...
    @staticmethod
    def calcGungorWintertonCorrectedHTC(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
        double10: float,
        boolean: bool,
    ) -> float: ...
    @staticmethod
    def calcGungorWintertonHTC(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
        double10: float,
    ) -> float: ...
    @staticmethod
    def calcMartinelliParameter(
        double: float, double2: float, double3: float, double4: float, double5: float
    ) -> float: ...

class FoulingModel(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, foulingModelType: "FoulingModel.FoulingModelType"): ...
    def advanceTime(self, double: float) -> None: ...
    def calcEbertPanchalFoulingRate(self, double: float) -> float: ...
    def calcEbertPanchalResistance(self, double: float) -> float: ...
    def calcKernSeatonResistance(self, double: float) -> float: ...
    def calcThresholdTemperature(self, double: float) -> float: ...
    def calcThresholdVelocity(self) -> float: ...
    @staticmethod
    def createCoolingWaterModel(double: float, double2: float) -> "FoulingModel": ...
    @staticmethod
    def createCrudeOilModel() -> "FoulingModel": ...
    @staticmethod
    def createHeavyCrudeModel() -> "FoulingModel": ...
    def getAsymptoticFoulingResistance(self) -> float: ...
    def getFixedFoulingResistance(self) -> float: ...
    def getFoulingRate(self) -> float: ...
    @typing.overload
    def getFoulingResistance(self) -> float: ...
    @typing.overload
    def getFoulingResistance(self, double: float) -> float: ...
    def getModelType(self) -> "FoulingModel.FoulingModelType": ...
    def getOperatingTimeHours(self) -> float: ...
    def predictTimeToFouling(self, double: float) -> float: ...
    def reset(self) -> None: ...
    def setActivationEnergy(self, double: float) -> None: ...
    def setAlpha(self, double: float) -> None: ...
    def setBeta(self, double: float) -> None: ...
    def setFixedFoulingResistance(self, double: float) -> None: ...
    def setGamma(self, double: float) -> None: ...
    def setModelType(
        self, foulingModelType: "FoulingModel.FoulingModelType"
    ) -> None: ...
    def setRfMax(self, double: float) -> None: ...
    def setTimeConstant(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def updateConditions(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
    ) -> None: ...

    class FoulingModelType(java.lang.Enum["FoulingModel.FoulingModelType"]):
        FIXED: typing.ClassVar["FoulingModel.FoulingModelType"] = ...
        EBERT_PANCHAL: typing.ClassVar["FoulingModel.FoulingModelType"] = ...
        KERN_SEATON: typing.ClassVar["FoulingModel.FoulingModelType"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "FoulingModel.FoulingModelType": ...
        @staticmethod
        def values() -> typing.MutableSequence["FoulingModel.FoulingModelType"]: ...

class HeatExchangerDesignFeasibilityReport:
    @typing.overload
    def __init__(
        self, heatExchanger: jneqsim.process.equipment.heatexchanger.HeatExchanger
    ): ...
    @typing.overload
    def __init__(
        self, lNGHeatExchanger: jneqsim.process.equipment.heatexchanger.LNGHeatExchanger
    ): ...
    def generateReport(self) -> None: ...
    def getInstalledCostUSD(self) -> float: ...
    def getIssues(
        self,
    ) -> java.util.List["HeatExchangerDesignFeasibilityReport.FeasibilityIssue"]: ...
    def getMatchingSuppliers(
        self,
    ) -> java.util.List["HeatExchangerDesignFeasibilityReport.SupplierMatch"]: ...
    def getMechanicalDesign(
        self,
    ) -> jneqsim.process.mechanicaldesign.MechanicalDesign: ...
    def getNumberOfMatchingSuppliers(self) -> int: ...
    def getPurchasedEquipmentCostUSD(self) -> float: ...
    def getVerdict(self) -> java.lang.String: ...
    def isFeasible(self) -> bool: ...
    def setAnnualOperatingHours(
        self, int: int
    ) -> "HeatExchangerDesignFeasibilityReport": ...
    def setDesignStandard(
        self, string: typing.Union[java.lang.String, str]
    ) -> "HeatExchangerDesignFeasibilityReport": ...
    def setExchangerType(
        self, string: typing.Union[java.lang.String, str]
    ) -> "HeatExchangerDesignFeasibilityReport": ...
    def toJson(self) -> java.lang.String: ...

    class FeasibilityIssue:
        def __init__(
            self,
            issueSeverity: "HeatExchangerDesignFeasibilityReport.IssueSeverity",
            string: typing.Union[java.lang.String, str],
            string2: typing.Union[java.lang.String, str],
        ): ...
        def getCategory(self) -> java.lang.String: ...
        def getMessage(self) -> java.lang.String: ...
        def getSeverity(
            self,
        ) -> "HeatExchangerDesignFeasibilityReport.IssueSeverity": ...
        def toString(self) -> java.lang.String: ...

    class IssueSeverity(
        java.lang.Enum["HeatExchangerDesignFeasibilityReport.IssueSeverity"]
    ):
        INFO: typing.ClassVar["HeatExchangerDesignFeasibilityReport.IssueSeverity"] = (
            ...
        )
        WARNING: typing.ClassVar[
            "HeatExchangerDesignFeasibilityReport.IssueSeverity"
        ] = ...
        BLOCKER: typing.ClassVar[
            "HeatExchangerDesignFeasibilityReport.IssueSeverity"
        ] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "HeatExchangerDesignFeasibilityReport.IssueSeverity": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["HeatExchangerDesignFeasibilityReport.IssueSeverity"]
        ): ...

    class SupplierMatch:
        def __init__(self): ...
        def getApplications(self) -> java.lang.String: ...
        def getExchangerType(self) -> java.lang.String: ...
        def getManufacturer(self) -> java.lang.String: ...
        def getMaterials(self) -> java.lang.String: ...
        def getMaxAreaM2(self) -> float: ...
        def getMaxDutyKW(self) -> float: ...
        def getMaxPressureBara(self) -> float: ...
        def getMaxTemperatureC(self) -> float: ...
        def getMinAreaM2(self) -> float: ...
        def getMinDutyKW(self) -> float: ...
        def getMinPressureBara(self) -> float: ...
        def getMinTemperatureC(self) -> float: ...
        def getNotes(self) -> java.lang.String: ...
        def getTemaTypes(self) -> java.lang.String: ...
        def getWebsite(self) -> java.lang.String: ...
        def setApplications(
            self, string: typing.Union[java.lang.String, str]
        ) -> None: ...
        def setExchangerType(
            self, string: typing.Union[java.lang.String, str]
        ) -> None: ...
        def setManufacturer(
            self, string: typing.Union[java.lang.String, str]
        ) -> None: ...
        def setMaterials(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setMaxAreaM2(self, double: float) -> None: ...
        def setMaxDutyKW(self, double: float) -> None: ...
        def setMaxPressureBara(self, double: float) -> None: ...
        def setMaxTemperatureC(self, double: float) -> None: ...
        def setMinAreaM2(self, double: float) -> None: ...
        def setMinDutyKW(self, double: float) -> None: ...
        def setMinPressureBara(self, double: float) -> None: ...
        def setMinTemperatureC(self, double: float) -> None: ...
        def setNotes(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setTemaTypes(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setWebsite(self, string: typing.Union[java.lang.String, str]) -> None: ...

class HeatExchangerMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(
        self,
        processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface,
    ): ...
    def calcDesign(self) -> None: ...
    def calculateCleanU(
        self, double: float, double2: float, double3: float, double4: float
    ) -> float: ...
    def calculateFouledU(
        self, double: float, boolean: bool, boolean2: bool
    ) -> float: ...
    def calculateTotalFoulingResistance(
        self, boolean: bool, boolean2: bool
    ) -> float: ...
    def getApproachTemperature(self) -> float: ...
    def getAreaMarginFactor(self) -> float: ...
    def getBaffleCutPercent(self) -> float: ...
    def getBaffleSpacingRatio(self) -> float: ...
    def getCalculatedUA(self) -> float: ...
    def getCandidateTypes(self) -> java.util.List["HeatExchangerType"]: ...
    def getDesignPressureMargin(self) -> float: ...
    def getDesignTemperatureMarginC(self) -> float: ...
    def getDutyMargin(self) -> float: ...
    def getFoulingResistanceShellHC(self) -> float: ...
    def getFoulingResistanceShellWater(self) -> float: ...
    def getFoulingResistanceTubeHC(self) -> float: ...
    def getFoulingResistanceTubeWater(self) -> float: ...
    def getH2sPartialPressure(self) -> float: ...
    def getLogMeanTemperatureDifference(self) -> float: ...
    def getManualSelection(self) -> "HeatExchangerType": ...
    def getMaxShellVelocity(self) -> float: ...
    def getMaxTubeLengthM(self) -> float: ...
    def getMaxTubeVelocity(self) -> float: ...
    def getMinApproachTemperatureC(self) -> float: ...
    def getMinTubeVelocity(self) -> float: ...
    def getSelectedSizingResult(self) -> "HeatExchangerSizingResult": ...
    def getSelectedType(self) -> "HeatExchangerType": ...
    def getSelectionCriterion(
        self,
    ) -> "HeatExchangerMechanicalDesign.SelectionCriterion": ...
    def getShellAndTubeCalculator(self) -> "ShellAndTubeDesignCalculator": ...
    def getShellJointEfficiency(self) -> float: ...
    def getShellMaterialGrade(self) -> java.lang.String: ...
    def getShellPasses(self) -> int: ...
    def getSizingResults(self) -> java.util.List["HeatExchangerSizingResult"]: ...
    def getSizingSummary(self) -> java.lang.String: ...
    def getTemaClass(self) -> java.lang.String: ...
    def getTemaDesignation(self) -> java.lang.String: ...
    def getTemaFrontHeadType(self) -> java.lang.String: ...
    def getTemaRearHeadType(self) -> java.lang.String: ...
    def getTemaShellType(self) -> java.lang.String: ...
    def getTubeLayoutPattern(self) -> java.lang.String: ...
    def getTubeMaterialGrade(self) -> java.lang.String: ...
    def getTubeOuterDiameterMm(self) -> float: ...
    def getTubePasses(self) -> int: ...
    def getTubePitchRatio(self) -> float: ...
    def getTubeWallThicknessMm(self) -> float: ...
    def getUsedOverallHeatTransferCoefficient(self) -> float: ...
    def isSourServiceAssessment(self) -> bool: ...
    def loadProcessDesignParameters(self) -> None: ...
    def setAreaMarginFactor(self, double: float) -> None: ...
    def setBaffleCutPercent(self, double: float) -> None: ...
    def setBaffleSpacingRatio(self, double: float) -> None: ...
    @typing.overload
    def setCandidateTypes(self, list: java.util.List["HeatExchangerType"]) -> None: ...
    @typing.overload
    def setCandidateTypes(self, *heatExchangerType: "HeatExchangerType") -> None: ...
    def setDesignPressureMargin(self, double: float) -> None: ...
    def setDesignTemperatureMarginC(self, double: float) -> None: ...
    def setDutyMargin(self, double: float) -> None: ...
    def setFoulingResistanceShellHC(self, double: float) -> None: ...
    def setFoulingResistanceShellWater(self, double: float) -> None: ...
    def setFoulingResistanceTubeHC(self, double: float) -> None: ...
    def setFoulingResistanceTubeWater(self, double: float) -> None: ...
    def setH2sPartialPressure(self, double: float) -> None: ...
    def setManualSelection(self, heatExchangerType: "HeatExchangerType") -> None: ...
    def setMaxShellVelocity(self, double: float) -> None: ...
    def setMaxTubeLengthM(self, double: float) -> None: ...
    def setMaxTubeVelocity(self, double: float) -> None: ...
    def setMinApproachTemperatureC(self, double: float) -> None: ...
    def setMinTubeVelocity(self, double: float) -> None: ...
    def setSelectionCriterion(
        self, selectionCriterion: "HeatExchangerMechanicalDesign.SelectionCriterion"
    ) -> None: ...
    def setShellJointEfficiency(self, double: float) -> None: ...
    def setShellMaterialGrade(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setShellPasses(self, int: int) -> None: ...
    def setSourServiceAssessment(self, boolean: bool) -> None: ...
    def setTemaClass(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTemaFrontHeadType(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setTemaRearHeadType(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setTemaShellType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTubeLayoutPattern(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setTubeMaterialGrade(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setTubeOuterDiameterMm(self, double: float) -> None: ...
    def setTubePasses(self, int: int) -> None: ...
    def setTubePitchRatio(self, double: float) -> None: ...
    def setTubeWallThicknessMm(self, double: float) -> None: ...
    def validateApproachTemperature(self, double: float) -> bool: ...
    def validateDesign(
        self,
    ) -> "HeatExchangerMechanicalDesign.HeatExchangerValidationResult": ...
    def validateShellVelocity(self, double: float) -> bool: ...
    def validateTubeLength(self, double: float) -> bool: ...
    def validateTubeVelocity(self, double: float) -> bool: ...

    class HeatExchangerValidationResult:
        def __init__(self): ...
        def addIssue(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def getIssues(self) -> java.util.List[java.lang.String]: ...
        def isValid(self) -> bool: ...
        def setValid(self, boolean: bool) -> None: ...

    class SelectionCriterion(
        java.lang.Enum["HeatExchangerMechanicalDesign.SelectionCriterion"]
    ):
        MIN_AREA: typing.ClassVar[
            "HeatExchangerMechanicalDesign.SelectionCriterion"
        ] = ...
        MIN_WEIGHT: typing.ClassVar[
            "HeatExchangerMechanicalDesign.SelectionCriterion"
        ] = ...
        MIN_PRESSURE_DROP: typing.ClassVar[
            "HeatExchangerMechanicalDesign.SelectionCriterion"
        ] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "HeatExchangerMechanicalDesign.SelectionCriterion": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["HeatExchangerMechanicalDesign.SelectionCriterion"]
        ): ...

class HeatExchangerMechanicalDesignResponse(
    jneqsim.process.mechanicaldesign.MechanicalDesignResponse
):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self, heatExchangerMechanicalDesign: HeatExchangerMechanicalDesign
    ): ...
    def getAreaMargin(self) -> float: ...
    def getBaffleCut(self) -> float: ...
    def getBaffleSpacing(self) -> float: ...
    def getBaffleThickness(self) -> float: ...
    def getBaffleType(self) -> java.lang.String: ...
    def getBundleWeight(self) -> float: ...
    def getChannelWeight(self) -> float: ...
    def getCleanOverallHeatTransferCoeff(self) -> float: ...
    def getDesignShellFoulingResistance(self) -> float: ...
    def getDesignTubeFoulingResistance(self) -> float: ...
    def getFouledOverallHeatTransferCoeff(self) -> float: ...
    def getHeatDuty(self) -> float: ...
    def getHeatExchangerType(self) -> java.lang.String: ...
    def getHeatTransferArea(self) -> float: ...
    def getHydroTestPressureShell(self) -> float: ...
    def getHydroTestPressureTube(self) -> float: ...
    def getLmtd(self) -> float: ...
    def getLmtdCorrectionFactor(self) -> float: ...
    def getMawpShellSide(self) -> float: ...
    def getMawpTubeSide(self) -> float: ...
    def getMaxShellVelocity(self) -> float: ...
    def getMaxTubeLength(self) -> float: ...
    def getMaxTubeVelocity(self) -> float: ...
    def getMinApproachTemperature(self) -> float: ...
    def getNumberOfBaffles(self) -> int: ...
    def getNumberOfShellPasses(self) -> int: ...
    def getNumberOfShells(self) -> int: ...
    def getNumberOfTubePasses(self) -> int: ...
    def getNumberOfTubes(self) -> int: ...
    def getOverallHeatTransferCoeff(self) -> float: ...
    def getRequiredArea(self) -> float: ...
    def getShellDesignPressure(self) -> float: ...
    def getShellDesignTemperature(self) -> float: ...
    def getShellFoulingResistance(self) -> float: ...
    def getShellInnerDiameter(self) -> float: ...
    def getShellMaterial(self) -> java.lang.String: ...
    def getShellMaterialGrade(self) -> java.lang.String: ...
    def getShellPressureDrop(self) -> float: ...
    def getShellWallThickness(self) -> float: ...
    def getTemaClass(self) -> java.lang.String: ...
    def getTemaType(self) -> java.lang.String: ...
    def getTubeDesignPressure(self) -> float: ...
    def getTubeDesignTemperature(self) -> float: ...
    def getTubeFoulingResistance(self) -> float: ...
    def getTubeLayoutAngle(self) -> int: ...
    def getTubeLength(self) -> float: ...
    def getTubeMaterial(self) -> java.lang.String: ...
    def getTubeMaterialGrade(self) -> java.lang.String: ...
    def getTubeOuterDiameter(self) -> float: ...
    def getTubePitch(self) -> float: ...
    def getTubePressureDrop(self) -> float: ...
    def getTubeWallThickness(self) -> float: ...
    def isShellNACECompliant(self) -> bool: ...
    def isSourServiceRequired(self) -> bool: ...
    def isTubeNACECompliant(self) -> bool: ...
    def isVibrationAnalysisRequired(self) -> bool: ...
    def populateFromHeatExchangerDesign(
        self, heatExchangerMechanicalDesign: HeatExchangerMechanicalDesign
    ) -> None: ...
    def setAreaMargin(self, double: float) -> None: ...
    def setBaffleCut(self, double: float) -> None: ...
    def setBaffleSpacing(self, double: float) -> None: ...
    def setBaffleThickness(self, double: float) -> None: ...
    def setBaffleType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setBundleWeight(self, double: float) -> None: ...
    def setChannelWeight(self, double: float) -> None: ...
    def setCleanOverallHeatTransferCoeff(self, double: float) -> None: ...
    def setDesignShellFoulingResistance(self, double: float) -> None: ...
    def setDesignTubeFoulingResistance(self, double: float) -> None: ...
    def setFouledOverallHeatTransferCoeff(self, double: float) -> None: ...
    def setHeatDuty(self, double: float) -> None: ...
    def setHeatExchangerType(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setHeatTransferArea(self, double: float) -> None: ...
    def setHydroTestPressureShell(self, double: float) -> None: ...
    def setHydroTestPressureTube(self, double: float) -> None: ...
    def setLmtd(self, double: float) -> None: ...
    def setLmtdCorrectionFactor(self, double: float) -> None: ...
    def setMawpShellSide(self, double: float) -> None: ...
    def setMawpTubeSide(self, double: float) -> None: ...
    def setMaxShellVelocity(self, double: float) -> None: ...
    def setMaxTubeLength(self, double: float) -> None: ...
    def setMaxTubeVelocity(self, double: float) -> None: ...
    def setMinApproachTemperature(self, double: float) -> None: ...
    def setNumberOfBaffles(self, int: int) -> None: ...
    def setNumberOfShellPasses(self, int: int) -> None: ...
    def setNumberOfShells(self, int: int) -> None: ...
    def setNumberOfTubePasses(self, int: int) -> None: ...
    def setNumberOfTubes(self, int: int) -> None: ...
    def setOverallHeatTransferCoeff(self, double: float) -> None: ...
    def setRequiredArea(self, double: float) -> None: ...
    def setShellDesignPressure(self, double: float) -> None: ...
    def setShellDesignTemperature(self, double: float) -> None: ...
    def setShellFoulingResistance(self, double: float) -> None: ...
    def setShellInnerDiameter(self, double: float) -> None: ...
    def setShellMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setShellMaterialGrade(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setShellNACECompliant(self, boolean: bool) -> None: ...
    def setShellPressureDrop(self, double: float) -> None: ...
    def setShellWallThickness(self, double: float) -> None: ...
    def setSourServiceRequired(self, boolean: bool) -> None: ...
    def setTemaClass(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTemaType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTubeDesignPressure(self, double: float) -> None: ...
    def setTubeDesignTemperature(self, double: float) -> None: ...
    def setTubeFoulingResistance(self, double: float) -> None: ...
    def setTubeLayoutAngle(self, int: int) -> None: ...
    def setTubeLength(self, double: float) -> None: ...
    def setTubeMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTubeMaterialGrade(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setTubeNACECompliant(self, boolean: bool) -> None: ...
    def setTubeOuterDiameter(self, double: float) -> None: ...
    def setTubePitch(self, double: float) -> None: ...
    def setTubePressureDrop(self, double: float) -> None: ...
    def setTubeWallThickness(self, double: float) -> None: ...
    def setVibrationAnalysisRequired(self, boolean: bool) -> None: ...

class HeatExchangerSizingResult:
    @staticmethod
    def builder() -> "HeatExchangerSizingResult.Builder": ...
    def getApproachTemperature(self) -> float: ...
    def getEstimatedLength(self) -> float: ...
    def getEstimatedPressureDrop(self) -> float: ...
    def getEstimatedWeight(self) -> float: ...
    def getFinSurfaceArea(self) -> float: ...
    def getInnerDiameter(self) -> float: ...
    def getMetric(
        self, selectionCriterion: HeatExchangerMechanicalDesign.SelectionCriterion
    ) -> float: ...
    def getModuleHeight(self) -> float: ...
    def getModuleLength(self) -> float: ...
    def getModuleWidth(self) -> float: ...
    def getOuterDiameter(self) -> float: ...
    def getOverallHeatTransferCoefficient(self) -> float: ...
    def getRequiredArea(self) -> float: ...
    def getRequiredUA(self) -> float: ...
    def getTubeCount(self) -> int: ...
    def getTubePasses(self) -> int: ...
    def getType(self) -> "HeatExchangerType": ...
    def getWallThickness(self) -> float: ...
    def toString(self) -> java.lang.String: ...

    class Builder:
        def approachTemperature(
            self, double: float
        ) -> "HeatExchangerSizingResult.Builder": ...
        def build(self) -> "HeatExchangerSizingResult": ...
        def estimatedLength(
            self, double: float
        ) -> "HeatExchangerSizingResult.Builder": ...
        def estimatedPressureDrop(
            self, double: float
        ) -> "HeatExchangerSizingResult.Builder": ...
        def estimatedWeight(
            self, double: float
        ) -> "HeatExchangerSizingResult.Builder": ...
        def finSurfaceArea(
            self, double: float
        ) -> "HeatExchangerSizingResult.Builder": ...
        def innerDiameter(
            self, double: float
        ) -> "HeatExchangerSizingResult.Builder": ...
        def moduleHeight(
            self, double: float
        ) -> "HeatExchangerSizingResult.Builder": ...
        def moduleLength(
            self, double: float
        ) -> "HeatExchangerSizingResult.Builder": ...
        def moduleWidth(self, double: float) -> "HeatExchangerSizingResult.Builder": ...
        def outerDiameter(
            self, double: float
        ) -> "HeatExchangerSizingResult.Builder": ...
        def overallHeatTransferCoefficient(
            self, double: float
        ) -> "HeatExchangerSizingResult.Builder": ...
        def requiredArea(
            self, double: float
        ) -> "HeatExchangerSizingResult.Builder": ...
        def requiredUA(self, double: float) -> "HeatExchangerSizingResult.Builder": ...
        def tubeCount(self, int: int) -> "HeatExchangerSizingResult.Builder": ...
        def tubePasses(self, int: int) -> "HeatExchangerSizingResult.Builder": ...
        def type(
            self, heatExchangerType: "HeatExchangerType"
        ) -> "HeatExchangerSizingResult.Builder": ...
        def wallThickness(
            self, double: float
        ) -> "HeatExchangerSizingResult.Builder": ...

class HeatExchangerType(java.lang.Enum["HeatExchangerType"]):
    SHELL_AND_TUBE: typing.ClassVar["HeatExchangerType"] = ...
    PLATE_AND_FRAME: typing.ClassVar["HeatExchangerType"] = ...
    AIR_COOLER: typing.ClassVar["HeatExchangerType"] = ...
    DOUBLE_PIPE: typing.ClassVar["HeatExchangerType"] = ...
    PLATE_FIN: typing.ClassVar["HeatExchangerType"] = ...
    def createSizingResult(
        self,
        heatExchanger: jneqsim.process.equipment.heatexchanger.HeatExchanger,
        double: float,
        double2: float,
        double3: float,
    ) -> HeatExchangerSizingResult: ...
    def getAllowableApproachTemperature(self) -> float: ...
    def getDisplayName(self) -> java.lang.String: ...
    def getTypicalOverallHeatTransferCoefficient(self) -> float: ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> "HeatExchangerType": ...
    @staticmethod
    def values() -> typing.MutableSequence["HeatExchangerType"]: ...

class IncrementalZoneAnalysis(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    def addZone(
        self, incrementalZone: "IncrementalZoneAnalysis.IncrementalZone"
    ) -> None: ...
    def calculate(self) -> None: ...
    def clearZones(self) -> None: ...
    def getMinimumApproachTemperature(self) -> float: ...
    def getTargetZoneCount(self) -> int: ...
    def getTotalDuty(self) -> float: ...
    def getTotalRequiredArea(self) -> float: ...
    def getTotalShellSidePressureDrop(self) -> float: ...
    def getTotalTubeSidePressureDrop(self) -> float: ...
    def getWeightedAverageU(self) -> float: ...
    def getZoneResults(
        self,
    ) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getZones(self) -> java.util.List["IncrementalZoneAnalysis.IncrementalZone"]: ...
    def setFouling(self, double: float, double2: float) -> None: ...
    def setGeometry(
        self, double: float, double2: float, double3: float, int: int, int2: int
    ) -> None: ...
    def setShellGeometry(
        self, double: float, double2: float, double3: float, boolean: bool
    ) -> None: ...
    def setTubeWallConductivity(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

    class IncrementalZone(java.io.Serializable):
        zoneName: java.lang.String = ...
        duty: float = ...
        hotInletTemp: float = ...
        hotOutletTemp: float = ...
        coldInletTemp: float = ...
        coldOutletTemp: float = ...
        tubePhaseRegime: "IncrementalZoneAnalysis.PhaseRegime" = ...
        tubeDensity: float = ...
        tubeViscosity: float = ...
        tubeCp: float = ...
        tubeConductivity: float = ...
        tubeMassFlowRate: float = ...
        tubeLiquidDensity: float = ...
        tubeVaporDensity: float = ...
        tubeLiquidViscosity: float = ...
        tubeVaporViscosity: float = ...
        tubeLiquidCp: float = ...
        tubeLiquidConductivity: float = ...
        tubeQualityIn: float = ...
        tubeQualityOut: float = ...
        tubeReducedPressure: float = ...
        tubeSurfaceTension: float = ...
        tubeHeatOfVaporization: float = ...
        shellPhaseRegime: "IncrementalZoneAnalysis.PhaseRegime" = ...
        shellDensity: float = ...
        shellViscosity: float = ...
        shellCp: float = ...
        shellConductivity: float = ...
        shellMassFlowRate: float = ...
        tubeSideHTC: float = ...
        shellSideHTC: float = ...
        overallU: float = ...
        lmtd: float = ...
        requiredArea: float = ...
        tubeSidePressureDrop: float = ...
        shellSidePressureDrop: float = ...
        def __init__(self): ...
        def setShellSideProperties(
            self,
            double: float,
            double2: float,
            double3: float,
            double4: float,
            double5: float,
            phaseRegime: "IncrementalZoneAnalysis.PhaseRegime",
        ) -> None: ...
        def setTemperatures(
            self, double: float, double2: float, double3: float, double4: float
        ) -> None: ...
        def setTubeSideProperties(
            self,
            double: float,
            double2: float,
            double3: float,
            double4: float,
            double5: float,
            phaseRegime: "IncrementalZoneAnalysis.PhaseRegime",
        ) -> None: ...

    class PhaseRegime(java.lang.Enum["IncrementalZoneAnalysis.PhaseRegime"]):
        VAPOR: typing.ClassVar["IncrementalZoneAnalysis.PhaseRegime"] = ...
        LIQUID: typing.ClassVar["IncrementalZoneAnalysis.PhaseRegime"] = ...
        CONDENSING: typing.ClassVar["IncrementalZoneAnalysis.PhaseRegime"] = ...
        EVAPORATING: typing.ClassVar["IncrementalZoneAnalysis.PhaseRegime"] = ...
        TWO_PHASE: typing.ClassVar["IncrementalZoneAnalysis.PhaseRegime"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "IncrementalZoneAnalysis.PhaseRegime": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["IncrementalZoneAnalysis.PhaseRegime"]
        ): ...

class LMTDcorrectionFactor:
    MIN_ACCEPTABLE_FT: typing.ClassVar[float] = ...
    @staticmethod
    def calcFt(
        double: float, double2: float, double3: float, double4: float, int: int
    ) -> float: ...
    @staticmethod
    def calcFt1ShellPass(
        double: float, double2: float, double3: float, double4: float
    ) -> float: ...
    @staticmethod
    def calcFt2ShellPass(
        double: float, double2: float, double3: float, double4: float
    ) -> float: ...
    @staticmethod
    def calcFtFromRP(double: float, double2: float, int: int) -> float: ...
    @staticmethod
    def calcP(
        double: float, double2: float, double3: float, double4: float
    ) -> float: ...
    @staticmethod
    def calcR(
        double: float, double2: float, double3: float, double4: float
    ) -> float: ...
    @staticmethod
    def requiredShellPasses(
        double: float, double2: float, double3: float, double4: float
    ) -> int: ...

class ShahCondensation:
    @staticmethod
    def calcAverageHTC(
        double: float, double2: float, double3: float, double4: float, int: int
    ) -> float: ...
    @staticmethod
    def calcLiquidOnlyHTC(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
    ) -> float: ...
    @staticmethod
    def calcLocalHTC(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def calcVerticalTubeHTC(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
    ) -> float: ...
    @staticmethod
    def isInValidRange(double: float, double2: float, double3: float) -> bool: ...

class ShellAndTubeDesignCalculator:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface,
    ): ...
    def calculate(self) -> None: ...
    def getActualArea(self) -> float: ...
    def getAppliedStandards(self) -> java.util.List[java.lang.String]: ...
    def getBaffleCount(self) -> int: ...
    def getBaffleSpacing(self) -> float: ...
    def getH2sPartialPressure(self) -> float: ...
    def getHydroTestPressureShell(self) -> float: ...
    def getHydroTestPressureTube(self) -> float: ...
    def getMawpShellSide(self) -> float: ...
    def getMawpTubeSide(self) -> float: ...
    def getNaceIssues(self) -> java.util.List[java.lang.String]: ...
    def getNozzleReinforcementArea(self) -> float: ...
    def getOperatingWeight(self) -> float: ...
    def getRequiredArea(self) -> float: ...
    def getShellInsideDiameter(self) -> float: ...
    def getShellJointEfficiency(self) -> float: ...
    def getShellMaterialGrade(self) -> java.lang.String: ...
    def getShellOutsideDiameter(self) -> float: ...
    def getShellWallThickness(self) -> float: ...
    def getTemaClass(self) -> "TEMAStandard.TEMAClass": ...
    def getTemaDesignation(self) -> java.lang.String: ...
    def getThermalCalculator(self) -> "ThermalDesignCalculator": ...
    def getTotalCost(self) -> float: ...
    def getTotalDryWeight(self) -> float: ...
    def getTubeCount(self) -> int: ...
    def getTubeMaterialGrade(self) -> java.lang.String: ...
    def getTubeThermalConductivity(self) -> float: ...
    def getTubesheetThicknessUHX(self) -> float: ...
    def getVibrationResult(self) -> "VibrationAnalysis.VibrationResult": ...
    def hasThermalData(self) -> bool: ...
    def isNozzleReinforcementAdequate(self) -> bool: ...
    def isShellNACECompliant(self) -> bool: ...
    def isSourServiceAssessment(self) -> bool: ...
    def isSourServiceRequired(self) -> bool: ...
    def isTubeNACECompliant(self) -> bool: ...
    def setDesignTemperature(self, double: float) -> None: ...
    def setFoulingShell(self, double: float) -> None: ...
    def setFoulingTube(self, double: float) -> None: ...
    def setH2sPartialPressure(self, double: float) -> None: ...
    def setNozzleDiameter(self, double: float) -> None: ...
    def setNozzleWallThickness(self, double: float) -> None: ...
    def setRequiredArea(self, double: float) -> None: ...
    def setShellJointEfficiency(self, double: float) -> None: ...
    def setShellMaterialGrade(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setShellSideFluidProperties(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
    ) -> None: ...
    def setShellSideMethod(
        self, shellSideMethod: "ThermalDesignCalculator.ShellSideMethod"
    ) -> None: ...
    def setShellSidePressure(self, double: float) -> None: ...
    def setSourServiceAssessment(self, boolean: bool) -> None: ...
    def setTemaClass(self, tEMAClass: "TEMAStandard.TEMAClass") -> None: ...
    def setTemaDesignation(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setTubeLength(self, double: float) -> None: ...
    def setTubeMaterialGrade(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setTubePasses(self, int: int) -> None: ...
    def setTubeSideFluidProperties(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        boolean: bool,
    ) -> None: ...
    def setTubeSidePressure(self, double: float) -> None: ...
    def setTubeSize(
        self, standardTubeSize: "TEMAStandard.StandardTubeSize"
    ) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class TEMAStandard:
    @staticmethod
    def calculateMinTubePitch(
        double: float, tubePitchPattern: "TEMAStandard.TubePitchPattern"
    ) -> float: ...
    @staticmethod
    def createConfiguration(
        char: str, char2: str, char3: str
    ) -> "TEMAStandard.TEMAConfiguration": ...
    @staticmethod
    def estimateTubeCount(
        double: float,
        double2: float,
        double3: float,
        tubePitchPattern: "TEMAStandard.TubePitchPattern",
        int: int,
    ) -> int: ...
    @staticmethod
    def getCommonConfigurations() -> (
        java.util.Map[java.lang.String, "TEMAStandard.TEMAConfiguration"]
    ): ...
    @staticmethod
    def getConfiguration(
        string: typing.Union[java.lang.String, str],
    ) -> "TEMAStandard.TEMAConfiguration": ...
    @staticmethod
    def getMaxBaffleSpacing(double: float) -> float: ...
    @staticmethod
    def getMaxUnsupportedSpan(
        double: float, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    @staticmethod
    def getMinBaffleSpacing(
        double: float, tEMAClass: "TEMAStandard.TEMAClass"
    ) -> float: ...
    @staticmethod
    def recommendConfiguration(
        boolean: bool, boolean2: bool, boolean3: bool, boolean4: bool
    ) -> java.lang.String: ...

    class BaffleType(java.lang.Enum["TEMAStandard.BaffleType"]):
        SINGLE_SEGMENTAL: typing.ClassVar["TEMAStandard.BaffleType"] = ...
        DOUBLE_SEGMENTAL: typing.ClassVar["TEMAStandard.BaffleType"] = ...
        TRIPLE_SEGMENTAL: typing.ClassVar["TEMAStandard.BaffleType"] = ...
        NO_TUBES_IN_WINDOW: typing.ClassVar["TEMAStandard.BaffleType"] = ...
        DISC_AND_DOUGHNUT: typing.ClassVar["TEMAStandard.BaffleType"] = ...
        ROD_BAFFLES: typing.ClassVar["TEMAStandard.BaffleType"] = ...
        def getDescription(self) -> java.lang.String: ...
        def getHeatTransferFactor(self) -> float: ...
        def getPressureDropFactor(self) -> float: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "TEMAStandard.BaffleType": ...
        @staticmethod
        def values() -> typing.MutableSequence["TEMAStandard.BaffleType"]: ...

    class FrontHeadType(java.lang.Enum["TEMAStandard.FrontHeadType"]):
        A: typing.ClassVar["TEMAStandard.FrontHeadType"] = ...
        B: typing.ClassVar["TEMAStandard.FrontHeadType"] = ...
        C: typing.ClassVar["TEMAStandard.FrontHeadType"] = ...
        N: typing.ClassVar["TEMAStandard.FrontHeadType"] = ...
        D: typing.ClassVar["TEMAStandard.FrontHeadType"] = ...
        def getDescription(self) -> java.lang.String: ...
        def getNotes(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "TEMAStandard.FrontHeadType": ...
        @staticmethod
        def values() -> typing.MutableSequence["TEMAStandard.FrontHeadType"]: ...

    class RearHeadType(java.lang.Enum["TEMAStandard.RearHeadType"]):
        L: typing.ClassVar["TEMAStandard.RearHeadType"] = ...
        M: typing.ClassVar["TEMAStandard.RearHeadType"] = ...
        N: typing.ClassVar["TEMAStandard.RearHeadType"] = ...
        P: typing.ClassVar["TEMAStandard.RearHeadType"] = ...
        S: typing.ClassVar["TEMAStandard.RearHeadType"] = ...
        T: typing.ClassVar["TEMAStandard.RearHeadType"] = ...
        U: typing.ClassVar["TEMAStandard.RearHeadType"] = ...
        W: typing.ClassVar["TEMAStandard.RearHeadType"] = ...
        def getDescription(self) -> java.lang.String: ...
        def getNotes(self) -> java.lang.String: ...
        def isFloating(self) -> bool: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "TEMAStandard.RearHeadType": ...
        @staticmethod
        def values() -> typing.MutableSequence["TEMAStandard.RearHeadType"]: ...

    class ShellType(java.lang.Enum["TEMAStandard.ShellType"]):
        E: typing.ClassVar["TEMAStandard.ShellType"] = ...
        F: typing.ClassVar["TEMAStandard.ShellType"] = ...
        G: typing.ClassVar["TEMAStandard.ShellType"] = ...
        H: typing.ClassVar["TEMAStandard.ShellType"] = ...
        J: typing.ClassVar["TEMAStandard.ShellType"] = ...
        K: typing.ClassVar["TEMAStandard.ShellType"] = ...
        X: typing.ClassVar["TEMAStandard.ShellType"] = ...
        def getDescription(self) -> java.lang.String: ...
        def getNotes(self) -> java.lang.String: ...
        def getPressureDropFactor(self) -> float: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "TEMAStandard.ShellType": ...
        @staticmethod
        def values() -> typing.MutableSequence["TEMAStandard.ShellType"]: ...

    class StandardTubeSize(java.lang.Enum["TEMAStandard.StandardTubeSize"]):
        TUBE_3_8_INCH: typing.ClassVar["TEMAStandard.StandardTubeSize"] = ...
        TUBE_1_2_INCH: typing.ClassVar["TEMAStandard.StandardTubeSize"] = ...
        TUBE_5_8_INCH: typing.ClassVar["TEMAStandard.StandardTubeSize"] = ...
        TUBE_3_4_INCH: typing.ClassVar["TEMAStandard.StandardTubeSize"] = ...
        TUBE_1_INCH: typing.ClassVar["TEMAStandard.StandardTubeSize"] = ...
        def getAvailableWallThicknessesMm(self) -> typing.MutableSequence[float]: ...
        def getOuterDiameterInch(self) -> float: ...
        def getOuterDiameterMm(self) -> float: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "TEMAStandard.StandardTubeSize": ...
        @staticmethod
        def values() -> typing.MutableSequence["TEMAStandard.StandardTubeSize"]: ...

    class TEMAClass(java.lang.Enum["TEMAStandard.TEMAClass"]):
        R: typing.ClassVar["TEMAStandard.TEMAClass"] = ...
        C: typing.ClassVar["TEMAStandard.TEMAClass"] = ...
        B: typing.ClassVar["TEMAStandard.TEMAClass"] = ...
        def getCostFactor(self) -> float: ...
        def getDescription(self) -> java.lang.String: ...
        def getMinCorrosionAllowanceMm(self) -> float: ...
        def getMinTubeWallMm(self) -> float: ...
        def getNotes(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "TEMAStandard.TEMAClass": ...
        @staticmethod
        def values() -> typing.MutableSequence["TEMAStandard.TEMAClass"]: ...

    class TEMAConfiguration:
        def __init__(
            self,
            frontHeadType: "TEMAStandard.FrontHeadType",
            shellType: "TEMAStandard.ShellType",
            rearHeadType: "TEMAStandard.RearHeadType",
            string: typing.Union[java.lang.String, str],
            set: java.util.Set["TEMAStandard.TEMAClass"],
        ): ...
        def getApplicableClasses(self) -> java.util.Set["TEMAStandard.TEMAClass"]: ...
        def getCostFactor(self) -> float: ...
        def getDescription(self) -> java.lang.String: ...
        def getDesignation(self) -> java.lang.String: ...
        def getFrontHead(self) -> "TEMAStandard.FrontHeadType": ...
        def getRearHead(self) -> "TEMAStandard.RearHeadType": ...
        def getShell(self) -> "TEMAStandard.ShellType": ...
        def hasGoodThermalExpansion(self) -> bool: ...
        def isBundleRemovable(self) -> bool: ...

    class TubePitchPattern(java.lang.Enum["TEMAStandard.TubePitchPattern"]):
        TRIANGULAR_30: typing.ClassVar["TEMAStandard.TubePitchPattern"] = ...
        TRIANGULAR_60: typing.ClassVar["TEMAStandard.TubePitchPattern"] = ...
        SQUARE_90: typing.ClassVar["TEMAStandard.TubePitchPattern"] = ...
        SQUARE_45: typing.ClassVar["TEMAStandard.TubePitchPattern"] = ...
        def getDescription(self) -> java.lang.String: ...
        def getHeatTransferFactor(self) -> float: ...
        def getLayoutAngle(self) -> int: ...
        def getMinPitchRatio(self) -> float: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "TEMAStandard.TubePitchPattern": ...
        @staticmethod
        def values() -> typing.MutableSequence["TEMAStandard.TubePitchPattern"]: ...

class ThermalDesignCalculator:
    def __init__(self): ...
    def calculate(self) -> None: ...
    def calculateZones(
        self,
        zoneDefinitionArray: typing.Union[
            typing.List["ThermalDesignCalculator.ZoneDefinition"], jpype.JArray
        ],
    ) -> typing.MutableSequence["ThermalDesignCalculator.ZoneResult"]: ...
    def getOverallU(self) -> float: ...
    def getShellSideHTC(self) -> float: ...
    def getShellSideMethod(self) -> "ThermalDesignCalculator.ShellSideMethod": ...
    def getShellSidePressureDrop(self) -> float: ...
    def getShellSidePressureDropBar(self) -> float: ...
    def getShellSideRe(self) -> float: ...
    def getShellSideVelocity(self) -> float: ...
    def getTubeSideHTC(self) -> float: ...
    def getTubeSidePressureDrop(self) -> float: ...
    def getTubeSidePressureDropBar(self) -> float: ...
    def getTubeSideRe(self) -> float: ...
    def getTubeSideVelocity(self) -> float: ...
    def setBaffleCount(self, int: int) -> None: ...
    def setBaffleCut(self, double: float) -> None: ...
    def setBaffleSpacingm(self, double: float) -> None: ...
    def setBypassArea(self, double: float) -> None: ...
    def setFoulingShell(self, double: float) -> None: ...
    def setFoulingTube(self, double: float) -> None: ...
    def setHasSealing(self, boolean: bool) -> None: ...
    def setSealingPairs(self, int: int) -> None: ...
    def setShellIDm(self, double: float) -> None: ...
    def setShellSideFluid(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
    ) -> None: ...
    def setShellSideMethod(
        self, shellSideMethod: "ThermalDesignCalculator.ShellSideMethod"
    ) -> None: ...
    def setShellToBaffleClearance(self, double: float) -> None: ...
    def setShellViscosityWall(self, double: float) -> None: ...
    def setTriangularPitch(self, boolean: bool) -> None: ...
    def setTubeCount(self, int: int) -> None: ...
    def setTubeIDm(self, double: float) -> None: ...
    def setTubeLengthm(self, double: float) -> None: ...
    def setTubeODm(self, double: float) -> None: ...
    def setTubePasses(self, int: int) -> None: ...
    def setTubePitchm(self, double: float) -> None: ...
    def setTubeSideFluid(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        boolean: bool,
    ) -> None: ...
    def setTubeToBaffleClearance(self, double: float) -> None: ...
    def setTubeWallConductivity(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

    class ShellSideMethod(java.lang.Enum["ThermalDesignCalculator.ShellSideMethod"]):
        KERN: typing.ClassVar["ThermalDesignCalculator.ShellSideMethod"] = ...
        BELL_DELAWARE: typing.ClassVar["ThermalDesignCalculator.ShellSideMethod"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "ThermalDesignCalculator.ShellSideMethod": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["ThermalDesignCalculator.ShellSideMethod"]
        ): ...

    class ZoneDefinition:
        zoneName: java.lang.String = ...
        dutyFraction: float = ...
        totalDuty: float = ...
        lmtd: float = ...
        tubeDensity: float = ...
        tubeViscosity: float = ...
        tubeCp: float = ...
        tubeConductivity: float = ...
        shellDensity: float = ...
        shellViscosity: float = ...
        shellCp: float = ...
        shellConductivity: float = ...
        def __init__(self): ...

    class ZoneResult:
        zoneName: java.lang.String = ...
        dutyFraction: float = ...
        tubeSideHTC: float = ...
        shellSideHTC: float = ...
        overallU: float = ...
        lmtd: float = ...
        requiredArea: float = ...
        def __init__(self): ...

class TubeInsertModel(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, insertType: "TubeInsertModel.InsertType"): ...
    def applyEnhancement(
        self, double: float, double2: float, double3: float, double4: float
    ) -> typing.MutableSequence[float]: ...
    @staticmethod
    def createCoiledWire(double: float, double2: float) -> "TubeInsertModel": ...
    @staticmethod
    def createTwistedTape(double: float) -> "TubeInsertModel": ...
    @staticmethod
    def createWireMatrix(double: float) -> "TubeInsertModel": ...
    def getHeatTransferEnhancementRatio(
        self, double: float, double2: float
    ) -> float: ...
    def getInsertType(self) -> "TubeInsertModel.InsertType": ...
    def getMatrixDensity(self) -> float: ...
    def getPerformanceEvaluationCriteria(
        self, double: float, double2: float
    ) -> float: ...
    def getPressureDropPenaltyRatio(self, double: float) -> float: ...
    def getTwistRatio(self) -> float: ...
    def setHelixAngle(self, double: float) -> None: ...
    def setInsertType(self, insertType: "TubeInsertModel.InsertType") -> None: ...
    def setMatrixDensity(self, double: float) -> None: ...
    def setRoughnessRatio(self, double: float) -> None: ...
    def setTapeThickness(self, double: float) -> None: ...
    def setTwistRatio(self, double: float) -> None: ...
    def setWireDiameter(self, double: float) -> None: ...
    def toJson(self, double: float, double2: float) -> java.lang.String: ...
    def toMap(
        self, double: float, double2: float
    ) -> java.util.Map[java.lang.String, typing.Any]: ...

    class InsertType(java.lang.Enum["TubeInsertModel.InsertType"]):
        NONE: typing.ClassVar["TubeInsertModel.InsertType"] = ...
        TWISTED_TAPE: typing.ClassVar["TubeInsertModel.InsertType"] = ...
        WIRE_MATRIX: typing.ClassVar["TubeInsertModel.InsertType"] = ...
        COILED_WIRE: typing.ClassVar["TubeInsertModel.InsertType"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "TubeInsertModel.InsertType": ...
        @staticmethod
        def values() -> typing.MutableSequence["TubeInsertModel.InsertType"]: ...

class TwoPhasePressureDrop:
    @staticmethod
    def calcAccelerationPressureDrop(
        double: float, double2: float, double3: float, double4: float, double5: float
    ) -> float: ...
    @staticmethod
    def calcFriedelAveragePressureDrop(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
        double10: float,
        int: int,
    ) -> float: ...
    @staticmethod
    def calcFriedelGradient(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
    ) -> float: ...
    @staticmethod
    def calcFriedelPressureDrop(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
    ) -> float: ...
    @staticmethod
    def calcGravitationalGradient(
        double: float, double2: float, double3: float
    ) -> float: ...
    @staticmethod
    def calcMullerSteinhagenHeckGradient(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
    ) -> float: ...

class VibrationAnalysis:
    @staticmethod
    def calcAcousticFrequency(double: float, double2: float, int: int) -> float: ...
    @staticmethod
    def calcCriticalVelocityConnors(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        boolean: bool,
    ) -> float: ...
    @staticmethod
    def calcEffectiveAcousticVelocity(double: float, double2: float) -> float: ...
    @staticmethod
    def calcNaturalFrequency(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        string: typing.Union[java.lang.String, str],
    ) -> float: ...
    @staticmethod
    def calcVortexSheddingFrequency(
        double: float, double2: float, double3: float
    ) -> float: ...
    @staticmethod
    def performScreening(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
        double10: float,
        double11: float,
        double12: float,
        boolean: bool,
    ) -> "VibrationAnalysis.VibrationResult": ...

    class VibrationResult:
        naturalFrequencyHz: float = ...
        vortexSheddingFrequencyHz: float = ...
        vortexSheddingRatio: float = ...
        vortexSheddingCritical: bool = ...
        criticalVelocityMs: float = ...
        velocityRatio: float = ...
        fluidElasticCritical: bool = ...
        acousticFrequencyHz: float = ...
        acousticRatio: float = ...
        acousticCritical: bool = ...
        passed: bool = ...
        def __init__(self): ...
        def getSummary(self) -> java.lang.String: ...

class BAHXMechanicalDesign(HeatExchangerMechanicalDesign):
    def __init__(
        self,
        processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface,
    ): ...
    def calcDesign(self) -> None: ...
    def getCoreHeightM(self) -> float: ...
    def getCoreLengthM(self) -> float: ...
    def getCoreMaterialGrade(self) -> java.lang.String: ...
    def getCoreWeightKg(self) -> float: ...
    def getCoreWidthM(self) -> float: ...
    def getDesignCycles(self) -> int: ...
    def getDesignLifeYears(self) -> int: ...
    def getFatigueUtilisation(self) -> float: ...
    def getHeaderMaterialGrade(self) -> java.lang.String: ...
    def getHeatTransferAreaM2(self) -> float: ...
    def getMaxThermalGradient(self) -> float: ...
    def getModuleHeight(self) -> float: ...
    def getModuleLength(self) -> float: ...
    def getModuleWidth(self) -> float: ...
    def getNozzleODMm(self) -> float: ...
    def getRequiredHeaderThicknessMm(self) -> float: ...
    def getRequiredNozzleThicknessMm(self) -> float: ...
    def getRequiredPartingSheetThicknessMm(self) -> float: ...
    def isFatiguePassed(self) -> bool: ...
    def setCoreMaterialGrade(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setDesignCycles(self, int: int) -> None: ...
    def setDesignLifeYears(self, int: int) -> None: ...
    def setHeaderMaterialGrade(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setNozzleODMm(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.heatexchanger")``.

    BAHXMechanicalDesign: typing.Type[BAHXMechanicalDesign]
    BellDelawareMethod: typing.Type[BellDelawareMethod]
    BoilingHeatTransfer: typing.Type[BoilingHeatTransfer]
    FoulingModel: typing.Type[FoulingModel]
    HeatExchangerDesignFeasibilityReport: typing.Type[
        HeatExchangerDesignFeasibilityReport
    ]
    HeatExchangerMechanicalDesign: typing.Type[HeatExchangerMechanicalDesign]
    HeatExchangerMechanicalDesignResponse: typing.Type[
        HeatExchangerMechanicalDesignResponse
    ]
    HeatExchangerSizingResult: typing.Type[HeatExchangerSizingResult]
    HeatExchangerType: typing.Type[HeatExchangerType]
    IncrementalZoneAnalysis: typing.Type[IncrementalZoneAnalysis]
    LMTDcorrectionFactor: typing.Type[LMTDcorrectionFactor]
    ShahCondensation: typing.Type[ShahCondensation]
    ShellAndTubeDesignCalculator: typing.Type[ShellAndTubeDesignCalculator]
    TEMAStandard: typing.Type[TEMAStandard]
    ThermalDesignCalculator: typing.Type[ThermalDesignCalculator]
    TubeInsertModel: typing.Type[TubeInsertModel]
    TwoPhasePressureDrop: typing.Type[TwoPhasePressureDrop]
    VibrationAnalysis: typing.Type[VibrationAnalysis]
