
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype.protocol
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.process.processmodel
import jneqsim.thermo.system
import typing



class DexpiMetadata:
    TAG_NAME: typing.ClassVar[java.lang.String] = ...
    LINE_NUMBER: typing.ClassVar[java.lang.String] = ...
    FLUID_CODE: typing.ClassVar[java.lang.String] = ...
    SEGMENT_NUMBER: typing.ClassVar[java.lang.String] = ...
    OPERATING_PRESSURE_VALUE: typing.ClassVar[java.lang.String] = ...
    OPERATING_PRESSURE_UNIT: typing.ClassVar[java.lang.String] = ...
    OPERATING_TEMPERATURE_VALUE: typing.ClassVar[java.lang.String] = ...
    OPERATING_TEMPERATURE_UNIT: typing.ClassVar[java.lang.String] = ...
    OPERATING_FLOW_VALUE: typing.ClassVar[java.lang.String] = ...
    OPERATING_FLOW_UNIT: typing.ClassVar[java.lang.String] = ...
    DEFAULT_PRESSURE_UNIT: typing.ClassVar[java.lang.String] = ...
    DEFAULT_TEMPERATURE_UNIT: typing.ClassVar[java.lang.String] = ...
    DEFAULT_FLOW_UNIT: typing.ClassVar[java.lang.String] = ...
    @staticmethod
    def recommendedEquipmentAttributes() -> java.util.Set[java.lang.String]: ...
    @staticmethod
    def recommendedStreamAttributes() -> java.util.Set[java.lang.String]: ...

class DexpiProcessUnit(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], equipmentEnum: jneqsim.process.equipment.EquipmentEnum, string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
    def getDexpiClass(self) -> java.lang.String: ...
    def getFluidCode(self) -> java.lang.String: ...
    def getLineNumber(self) -> java.lang.String: ...
    def getMappedEquipment(self) -> jneqsim.process.equipment.EquipmentEnum: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...

class DexpiRoundTripProfile:
    @staticmethod
    def minimalRunnableProfile() -> 'DexpiRoundTripProfile': ...
    def validate(self, processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'DexpiRoundTripProfile.ValidationResult': ...
    class ValidationResult:
        def getViolations(self) -> java.util.List[java.lang.String]: ...
        def isSuccessful(self) -> bool: ...

class DexpiStream(jneqsim.process.equipment.stream.Stream):
    def __init__(self, string: typing.Union[java.lang.String, str], systemInterface: jneqsim.thermo.system.SystemInterface, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
    def getDexpiClass(self) -> java.lang.String: ...
    def getFluidCode(self) -> java.lang.String: ...
    def getLineNumber(self) -> java.lang.String: ...

class DexpiXmlReader:
    @typing.overload
    @staticmethod
    def load(file: typing.Union[java.io.File, jpype.protocol.SupportsPath], processSystem: jneqsim.process.processmodel.ProcessSystem) -> None: ...
    @typing.overload
    @staticmethod
    def load(file: typing.Union[java.io.File, jpype.protocol.SupportsPath], processSystem: jneqsim.process.processmodel.ProcessSystem, stream: jneqsim.process.equipment.stream.Stream) -> None: ...
    @typing.overload
    @staticmethod
    def load(inputStream: java.io.InputStream, processSystem: jneqsim.process.processmodel.ProcessSystem) -> None: ...
    @typing.overload
    @staticmethod
    def load(inputStream: java.io.InputStream, processSystem: jneqsim.process.processmodel.ProcessSystem, stream: jneqsim.process.equipment.stream.Stream) -> None: ...
    @typing.overload
    @staticmethod
    def read(file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> jneqsim.process.processmodel.ProcessSystem: ...
    @typing.overload
    @staticmethod
    def read(file: typing.Union[java.io.File, jpype.protocol.SupportsPath], stream: jneqsim.process.equipment.stream.Stream) -> jneqsim.process.processmodel.ProcessSystem: ...
    @typing.overload
    @staticmethod
    def read(inputStream: java.io.InputStream) -> jneqsim.process.processmodel.ProcessSystem: ...
    @typing.overload
    @staticmethod
    def read(inputStream: java.io.InputStream, stream: jneqsim.process.equipment.stream.Stream) -> jneqsim.process.processmodel.ProcessSystem: ...

class DexpiXmlReaderException(java.lang.Exception):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], throwable: java.lang.Throwable): ...

class DexpiXmlWriter:
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> None: ...
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, outputStream: java.io.OutputStream) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.processmodel.dexpi")``.

    DexpiMetadata: typing.Type[DexpiMetadata]
    DexpiProcessUnit: typing.Type[DexpiProcessUnit]
    DexpiRoundTripProfile: typing.Type[DexpiRoundTripProfile]
    DexpiStream: typing.Type[DexpiStream]
    DexpiXmlReader: typing.Type[DexpiXmlReader]
    DexpiXmlReaderException: typing.Type[DexpiXmlReaderException]
    DexpiXmlWriter: typing.Type[DexpiXmlWriter]
