import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.process.equipment.capacity
import jneqsim.process.equipment.stream
import jneqsim.process.mechanicaldesign
import jneqsim.process.util.report
import jneqsim.thermo.system
import jneqsim.util.validation
import typing

class MixerInterface(jneqsim.process.equipment.ProcessEquipmentInterface):
    def addStream(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getOutStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOutletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def hashCode(self) -> int: ...
    def removeInputStream(self, int: int) -> None: ...
    def replaceStream(
        self,
        int: int,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> None: ...

class Mixer(
    jneqsim.process.equipment.ProcessEquipmentBaseClass,
    MixerInterface,
    jneqsim.process.equipment.capacity.CapacityConstrainedEquipment,
):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addCapacityConstraint(
        self, capacityConstraint: jneqsim.process.equipment.capacity.CapacityConstraint
    ) -> None: ...
    def addStream(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> None: ...
    def calcMixStreamEnthalpy(self) -> float: ...
    def clearCapacityConstraints(self) -> None: ...
    def displayResult(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBottleneckConstraint(
        self,
    ) -> jneqsim.process.equipment.capacity.CapacityConstraint: ...
    def getCapacityConstraints(
        self,
    ) -> java.util.Map[
        java.lang.String, jneqsim.process.equipment.capacity.CapacityConstraint
    ]: ...
    def getDesignPressureDrop(self) -> float: ...
    def getEntropyProduction(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getInletStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMaxDesignVelocity(self) -> float: ...
    def getMaxUtilization(self) -> float: ...
    def getMechanicalDesign(
        self,
    ) -> jneqsim.process.mechanicaldesign.MechanicalDesign: ...
    def getMixedSalinity(self) -> float: ...
    def getNumberOfInputStreams(self) -> int: ...
    def getOutTemperature(self) -> float: ...
    def getOutletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOutletStreams(
        self,
    ) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    @typing.overload
    def getOutletTemperature(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    @typing.overload
    def getOutletTemperature(self) -> float: ...
    def getStream(
        self, int: int
    ) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def guessTemperature(self) -> float: ...
    def hashCode(self) -> int: ...
    def initMechanicalDesign(self) -> None: ...
    def isCapacityAnalysisEnabled(self) -> bool: ...
    def isCapacityExceeded(self) -> bool: ...
    def isDoMultiPhaseCheck(self) -> bool: ...
    def isHardLimitExceeded(self) -> bool: ...
    @typing.overload
    def isSetOutTemperature(self) -> bool: ...
    @typing.overload
    def isSetOutTemperature(self, boolean: bool) -> None: ...
    def mixStream(self) -> None: ...
    def needRecalculation(self) -> bool: ...
    def removeCapacityConstraint(
        self, string: typing.Union[java.lang.String, str]
    ) -> bool: ...
    def removeInputStream(self, int: int) -> None: ...
    def replaceStream(
        self,
        int: int,
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setCapacityAnalysisEnabled(self, boolean: bool) -> None: ...
    def setDesignPressureDrop(self, double: float) -> None: ...
    def setMaxDesignVelocity(self, double: float) -> None: ...
    def setMultiPhaseCheck(self, boolean: bool) -> None: ...
    def setOutTemperature(self, double: float) -> None: ...
    def setOutletTemperature(self, double: float) -> None: ...
    def setPressure(self, double: float) -> None: ...
    def setTemperature(self, double: float) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(
        self, reportConfig: jneqsim.process.util.report.ReportConfig
    ) -> java.lang.String: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...

class StaticMixer(Mixer):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def calcMixStreamEnthalpy(self) -> float: ...
    def guessTemperature(self) -> float: ...
    def mixStream(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(
        self, reportConfig: jneqsim.process.util.report.ReportConfig
    ) -> java.lang.String: ...

class StaticNeqMixer(StaticMixer):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def mixStream(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...

class StaticPhaseMixer(StaticMixer):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def mixStream(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.mixer")``.

    Mixer: typing.Type[Mixer]
    MixerInterface: typing.Type[MixerInterface]
    StaticMixer: typing.Type[StaticMixer]
    StaticNeqMixer: typing.Type[StaticNeqMixer]
    StaticPhaseMixer: typing.Type[StaticPhaseMixer]
