
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import neqsim
import jneqsim.thermo.system
import typing



class AlDiwiniyaAtmosphericReference:
    DOI: typing.ClassVar[java.lang.String] = ...
    ARTICLE_URL: typing.ClassVar[java.lang.String] = ...
    LICENSE: typing.ClassVar[java.lang.String] = ...
    PUBLICATION_DATE: typing.ClassVar[java.lang.String] = ...
    @staticmethod
    def areHysysProductRatesImposedSpecifications() -> bool: ...
    @staticmethod
    def calculateSignedRelativeErrorPercent(double: float, double2: float) -> float: ...
    @staticmethod
    def getBottomSteamPressureBarGauge() -> float: ...
    @staticmethod
    def getBottomSteamRateKgPerHour() -> float: ...
    @staticmethod
    def getBottomSteamTemperatureCelsius() -> float: ...
    @staticmethod
    def getColumnBottomPressureBarGauge() -> float: ...
    @staticmethod
    def getColumnFeedPressureBarGauge() -> float: ...
    @staticmethod
    def getColumnFeedTemperatureCelsius() -> float: ...
    @staticmethod
    def getColumnStageCount() -> int: ...
    @staticmethod
    def getColumnTopPressureBarGauge() -> float: ...
    @staticmethod
    def getCrudeApiGravityAt15C() -> float: ...
    @staticmethod
    def getCrudeCapacityBarrelsPerDay() -> float: ...
    @staticmethod
    def getCrudeDensityKgPerCubicMetre() -> float: ...
    @staticmethod
    def getCrudeFeedRateM3PerHour() -> float: ...
    @staticmethod
    def getCrudeSaltPpm() -> float: ...
    @staticmethod
    def getCrudeSulfurMassPercent() -> float: ...
    @staticmethod
    def getFeedFlashZoneLowerTray() -> int: ...
    @staticmethod
    def getFeedFlashZoneUpperTray() -> int: ...
    @staticmethod
    def getGasoilDrawTray() -> int: ...
    @staticmethod
    def getGasoilPumpAroundRateM3PerHour() -> float: ...
    @staticmethod
    def getGasoilPumpAroundReturnTemperatureCelsius() -> float: ...
    @staticmethod
    def getGasoilStripperSteamRateKgPerHour() -> float: ...
    @staticmethod
    def getHeavyNaphthaDrawTrays() -> typing.MutableSequence[int]: ...
    @staticmethod
    def getKeroseneDrawTray() -> int: ...
    @staticmethod
    def getKeroseneStripperSteamRateKgPerHour() -> float: ...
    @staticmethod
    def getKinematicViscosityAt20CCst() -> float: ...
    @staticmethod
    def getMeasuredHydrocarbonLiquidClosurePercent() -> float: ...
    @staticmethod
    def getMeasuredHydrocarbonLiquidProductRateM3PerHour() -> float: ...
    @staticmethod
    def getOverheadWaterRateM3PerHour() -> float: ...
    @staticmethod
    def getPreheatOutletTemperatureCelsius() -> float: ...
    @staticmethod
    def getProduct(string: typing.Union[java.lang.String, str]) -> 'AlDiwiniyaAtmosphericReference.ProductReference': ...
    @staticmethod
    def getProducts() -> typing.MutableSequence['AlDiwiniyaAtmosphericReference.ProductReference']: ...
    @staticmethod
    def getSideStripperStageCount() -> int: ...
    @staticmethod
    def getTbpCumulativeVolumePercent() -> typing.MutableSequence[float]: ...
    @staticmethod
    def getTbpTemperatureCelsius() -> typing.MutableSequence[float]: ...
    @staticmethod
    def getTbpTemperatureKelvin() -> typing.MutableSequence[float]: ...
    @staticmethod
    def getWaterAndBottomSedimentVolumePercent() -> float: ...
    @staticmethod
    def hasCompleteTbpCurve() -> bool: ...
    @staticmethod
    def isIndependentYieldValidationCase() -> bool: ...
    class ProductReference(java.io.Serializable):
        def getDrawTemperatureRelativeErrorPercent(self) -> float: ...
        def getHysysDrawTemperatureCelsius(self) -> float: ...
        def getHysysRateM3PerHour(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getPlantDrawTemperatureCelsius(self) -> float: ...
        def getPlantRateM3PerHour(self) -> float: ...
        def getRateRelativeErrorPercent(self) -> float: ...
        def isHydrocarbonLiquid(self) -> bool: ...
        def toString(self) -> java.lang.String: ...

class AsphalteneCharacterization:
    CII_STABLE_LIMIT: typing.ClassVar[float] = ...
    CII_UNSTABLE_LIMIT: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float, double2: float, double3: float, double4: float): ...
    def addAsphalteneComponents(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float) -> None: ...
    def estimateAsphalteneMolecularWeight(self) -> float: ...
    def estimateResinMolecularWeight(self) -> float: ...
    def evaluateStability(self) -> java.lang.String: ...
    def getAromatics(self) -> float: ...
    def getAsphalteneAssociationEnergy(self) -> float: ...
    def getAsphalteneAssociationVolume(self) -> float: ...
    def getAsphaltenes(self) -> float: ...
    def getColloidalInstabilityIndex(self) -> float: ...
    def getMwAsphaltene(self) -> float: ...
    def getMwResin(self) -> float: ...
    def getResinToAsphalteneRatio(self) -> float: ...
    def getResins(self) -> float: ...
    def getSaturates(self) -> float: ...
    def setAromatics(self, double: float) -> None: ...
    def setAsphalteneAssociationEnergy(self, double: float) -> None: ...
    def setAsphalteneAssociationVolume(self, double: float) -> None: ...
    def setAsphaltenes(self, double: float) -> None: ...
    def setC7plusProperties(self, double: float, double2: float) -> None: ...
    def setMwAsphaltene(self, double: float) -> None: ...
    def setMwResin(self, double: float) -> None: ...
    def setResins(self, double: float) -> None: ...
    def setSARAFractions(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    def setSaturates(self, double: float) -> None: ...

class BioFeedstock(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def copy(self) -> 'BioFeedstock': ...
    def getAshFraction(self) -> float: ...
    def getBulkDensityKgPerM3(self) -> float: ...
    def getCarbonFraction(self) -> float: ...
    def getCelluloseFraction(self) -> float: ...
    def getEvidenceReference(self) -> java.lang.String: ...
    def getHemicelluloseFraction(self) -> float: ...
    def getHydrogenFraction(self) -> float: ...
    def getHydrolysisRatePerDay(self) -> float: ...
    def getLigninFraction(self) -> float: ...
    def getMaximumVsDestruction(self) -> float: ...
    def getMethaneFraction(self) -> float: ...
    def getMethaneYieldNm3PerKgDestroyedVs(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getNitrogenFraction(self) -> float: ...
    def getOxygenFraction(self) -> float: ...
    def getPhosphorusFraction(self) -> float: ...
    def getPreparedDensityKgPerM3(self) -> float: ...
    def getSulfurFraction(self) -> float: ...
    def getTotalSolidsFraction(self) -> float: ...
    def getVolatileSolidsFraction(self) -> float: ...
    @staticmethod
    def library(string: typing.Union[java.lang.String, str]) -> 'BioFeedstock': ...
    def setDigestionProperties(self, double: float, double2: float, double3: float) -> None: ...
    def setElementalAnalysis(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> None: ...
    def setEvidenceReference(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setHandlingProperties(self, double: float, double2: float) -> None: ...
    def setLignocellulosicAnalysis(self, double: float, double2: float, double3: float) -> None: ...
    def setSolidsAnalysis(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def validate(self) -> java.util.List[java.lang.String]: ...

class BiomassCharacterization(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def calculate(self) -> None: ...
    def getAsh(self) -> float: ...
    def getCarbonWt(self) -> float: ...
    def getChemicalFormula(self) -> java.lang.String: ...
    def getChlorineWt(self) -> float: ...
    def getFixedCarbon(self) -> float: ...
    def getHCRatio(self) -> float: ...
    def getHHV(self) -> float: ...
    def getHydrogenWt(self) -> float: ...
    def getLHV(self) -> float: ...
    @staticmethod
    def getLibraryFeedstocks() -> java.util.List[java.lang.String]: ...
    def getMoisture(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getNitrogenWt(self) -> float: ...
    def getOCRatio(self) -> float: ...
    def getOxygenWt(self) -> float: ...
    def getStoichiometricAir(self) -> float: ...
    def getSulfurWt(self) -> float: ...
    def getVolatileMatter(self) -> float: ...
    def isCalculated(self) -> bool: ...
    @staticmethod
    def library(string: typing.Union[java.lang.String, str]) -> 'BiomassCharacterization': ...
    def setHHV(self, double: float) -> None: ...
    def setLHV(self, double: float) -> None: ...
    def setProximateAnalysis(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    def setUltimateAnalysis(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, float]: ...
    def toString(self) -> java.lang.String: ...

class Characterise(java.io.Serializable, java.lang.Cloneable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def characterisePlusFraction(self) -> None: ...
    @typing.overload
    def characterizeToReference(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> jneqsim.thermo.system.SystemInterface: ...
    @typing.overload
    def characterizeToReference(self, systemInterface: jneqsim.thermo.system.SystemInterface, characterizationOptions: 'CharacterizationOptions') -> jneqsim.thermo.system.SystemInterface: ...
    def clone(self) -> 'Characterise': ...
    def configureLumping(self) -> 'LumpingConfigBuilder': ...
    def getLumpingModel(self) -> 'LumpingModelInterface': ...
    def getPlusFractionModel(self) -> 'PlusFractionModelInterface': ...
    def getTBPModel(self) -> 'TBPModelInterface': ...
    def setAutoEstimateGammaAlpha(self, boolean: bool) -> 'Characterise': ...
    def setGammaDensityModel(self, string: typing.Union[java.lang.String, str]) -> 'Characterise': ...
    def setGammaMinMW(self, double: float) -> 'Characterise': ...
    def setGammaShapeParameter(self, double: float) -> 'Characterise': ...
    def setLumpingModel(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPlusFractionModel(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTBPModel(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setThermoSystem(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    def transferBipsFrom(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> 'Characterise': ...

class CharacteriseInterface:
    PVTsimMolarMass: typing.ClassVar[typing.MutableSequence[float]] = ...
    def addCharacterizedPlusFraction(self) -> None: ...
    def addHeavyEnd(self) -> None: ...
    def addTBPFractions(self) -> None: ...
    def generatePlusFractions(self, int: int, int2: int, double: float, double2: float) -> None: ...
    def generateTBPFractions(self) -> None: ...
    def getCoef(self, int: int) -> float: ...
    def getCoefs(self) -> typing.MutableSequence[float]: ...
    def getDensLastTBP(self) -> float: ...
    def getDensPlus(self) -> float: ...
    def getFirstPlusFractionNumber(self) -> int: ...
    def getLastPlusFractionNumber(self) -> int: ...
    def getMPlus(self) -> float: ...
    @typing.overload
    def getPlusCoefs(self, int: int) -> float: ...
    @typing.overload
    def getPlusCoefs(self) -> typing.MutableSequence[float]: ...
    def getZPlus(self) -> float: ...
    def groupTBPfractions(self) -> bool: ...
    def hasPlusFraction(self) -> bool: ...
    def isPseudocomponents(self) -> bool: ...
    def removeTBPfraction(self) -> None: ...
    @typing.overload
    def setCoefs(self, double: float, int: int) -> None: ...
    @typing.overload
    def setCoefs(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setDensLastTBP(self, double: float) -> None: ...
    def setMPlus(self, double: float) -> None: ...
    def setNumberOfPseudocomponents(self, int: int) -> None: ...
    def setPlusCoefs(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setPseudocomponents(self, boolean: bool) -> None: ...
    def setZPlus(self, double: float) -> None: ...
    def solve(self) -> None: ...

class CharacterizationOptions:
    @staticmethod
    def builder() -> 'CharacterizationOptions.Builder': ...
    @staticmethod
    def defaults() -> 'CharacterizationOptions': ...
    def getCompositionTolerance(self) -> float: ...
    def getDelumpResolution(self) -> int: ...
    def getNamingScheme(self) -> 'CharacterizationOptions.NamingScheme': ...
    def isDelumpBeforeRecharacterization(self) -> bool: ...
    def isGenerateValidationReport(self) -> bool: ...
    def isInheritReferenceProperties(self) -> bool: ...
    def isNormalizeComposition(self) -> bool: ...
    def isSharedImaginaryBoundaries(self) -> bool: ...
    def isTransferBinaryInteractionParameters(self) -> bool: ...
    @staticmethod
    def withBipTransfer() -> 'CharacterizationOptions': ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'CharacterizationOptions': ...
        def compositionTolerance(self, double: float) -> 'CharacterizationOptions.Builder': ...
        def delumpBeforeRecharacterization(self, boolean: bool) -> 'CharacterizationOptions.Builder': ...
        def delumpResolution(self, int: int) -> 'CharacterizationOptions.Builder': ...
        def generateValidationReport(self, boolean: bool) -> 'CharacterizationOptions.Builder': ...
        def inheritReferenceProperties(self, boolean: bool) -> 'CharacterizationOptions.Builder': ...
        def namingScheme(self, namingScheme: 'CharacterizationOptions.NamingScheme') -> 'CharacterizationOptions.Builder': ...
        def normalizeComposition(self, boolean: bool) -> 'CharacterizationOptions.Builder': ...
        def sharedImaginaryBoundaries(self, boolean: bool) -> 'CharacterizationOptions.Builder': ...
        def transferBinaryInteractionParameters(self, boolean: bool) -> 'CharacterizationOptions.Builder': ...
    class NamingScheme(java.lang.Enum['CharacterizationOptions.NamingScheme']):
        REFERENCE: typing.ClassVar['CharacterizationOptions.NamingScheme'] = ...
        SEQUENTIAL: typing.ClassVar['CharacterizationOptions.NamingScheme'] = ...
        CARBON_NUMBER: typing.ClassVar['CharacterizationOptions.NamingScheme'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'CharacterizationOptions.NamingScheme': ...
        @staticmethod
        def values() -> typing.MutableSequence['CharacterizationOptions.NamingScheme']: ...

class CharacterizationValidationReport:
    @staticmethod
    def generate(systemInterface: jneqsim.thermo.system.SystemInterface, systemInterface2: jneqsim.thermo.system.SystemInterface, systemInterface3: jneqsim.thermo.system.SystemInterface) -> 'CharacterizationValidationReport': ...
    def getMassDifferencePercent(self) -> float: ...
    def getMolesDifferencePercent(self) -> float: ...
    def getResultPseudoComponentCount(self) -> int: ...
    def getSourcePseudoComponentCount(self) -> int: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isValid(self) -> bool: ...
    def toReportString(self) -> java.lang.String: ...
    def toString(self) -> java.lang.String: ...

class DoeBigHillSweetAssay:
    COMPREHENSIVE_ASSAY_URL: typing.ClassVar[java.lang.String] = ...
    PIANO_ASSAY_URL: typing.ClassVar[java.lang.String] = ...
    @typing.overload
    @staticmethod
    def create(systemInterface: jneqsim.thermo.system.SystemInterface) -> 'OilAssayCharacterisation': ...
    @typing.overload
    @staticmethod
    def create(systemInterface: jneqsim.thermo.system.SystemInterface, double: float) -> 'OilAssayCharacterisation': ...

class LumpingConfigBuilder:
    def __init__(self, characterise: Characterise): ...
    def build(self) -> Characterise: ...
    def customBoundaries(self, *int: int) -> 'LumpingConfigBuilder': ...
    def model(self, string: typing.Union[java.lang.String, str]) -> 'LumpingConfigBuilder': ...
    def noLumping(self) -> 'LumpingConfigBuilder': ...
    def plusFractionGroups(self, int: int) -> 'LumpingConfigBuilder': ...
    def totalPseudoComponents(self, int: int) -> 'LumpingConfigBuilder': ...

class LumpingModelInterface:
    def generateLumpedComposition(self, characterise: Characterise) -> None: ...
    def getCustomBoundaries(self) -> typing.MutableSequence[int]: ...
    def getFractionOfHeavyEnd(self, int: int) -> float: ...
    def getLumpedComponentName(self, int: int) -> java.lang.String: ...
    def getLumpedComponentNames(self) -> typing.MutableSequence[java.lang.String]: ...
    def getName(self) -> java.lang.String: ...
    def getNumberOfLumpedComponents(self) -> int: ...
    def getNumberOfPseudoComponents(self) -> int: ...
    def hasCustomBoundaries(self) -> bool: ...
    def setCustomBoundaries(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    def setNumberOfLumpedComponents(self, int: int) -> None: ...
    def setNumberOfPseudoComponents(self, int: int) -> None: ...

class LumpingResult(java.io.Serializable):
    def getCarbonNumberBoundaries(self) -> typing.MutableSequence[int]: ...
    def getDensityError(self) -> float: ...
    def getLumpedAverageDensity(self) -> float: ...
    def getLumpedAverageMW(self) -> float: ...
    def getLumpedComponentCount(self) -> int: ...
    def getLumpedComponentNames(self) -> java.util.List[java.lang.String]: ...
    def getMWError(self) -> float: ...
    def getModelName(self) -> java.lang.String: ...
    def getOriginalAverageDensity(self) -> float: ...
    def getOriginalAverageMW(self) -> float: ...
    def getOriginalComponentCount(self) -> int: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def hasWarnings(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def toString(self) -> java.lang.String: ...
    class Builder:
        def __init__(self): ...
        def addWarning(self, string: typing.Union[java.lang.String, str]) -> 'LumpingResult.Builder': ...
        def build(self) -> 'LumpingResult': ...
        def carbonNumberBoundaries(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'LumpingResult.Builder': ...
        def lumpedAverageDensity(self, double: float) -> 'LumpingResult.Builder': ...
        def lumpedAverageMW(self, double: float) -> 'LumpingResult.Builder': ...
        def lumpedComponentCount(self, int: int) -> 'LumpingResult.Builder': ...
        def lumpedComponentNames(self, list: java.util.List[typing.Union[java.lang.String, str]]) -> 'LumpingResult.Builder': ...
        def modelName(self, string: typing.Union[java.lang.String, str]) -> 'LumpingResult.Builder': ...
        def originalAverageDensity(self, double: float) -> 'LumpingResult.Builder': ...
        def originalAverageMW(self, double: float) -> 'LumpingResult.Builder': ...
        def originalComponentCount(self, int: int) -> 'LumpingResult.Builder': ...

class NewtonSolveAB(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, tBPCharacterize: 'TBPCharacterize'): ...
    def setJac(self) -> None: ...
    def setfvec(self) -> None: ...
    def solve(self) -> None: ...

class NewtonSolveABCD(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, tBPCharacterize: 'TBPCharacterize'): ...
    def setJac(self) -> None: ...
    def setfvec(self) -> None: ...
    def solve(self) -> None: ...

class NewtonSolveCDplus(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, plusCharacterize: 'PlusCharacterize'): ...
    def setJac(self) -> None: ...
    def setfvec(self) -> None: ...
    def solve(self) -> None: ...

class OilAssayCharacterisation(java.lang.Cloneable, java.io.Serializable):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def addCut(self, assayCut: 'OilAssayCharacterisation.AssayCut') -> None: ...
    def addCuts(self, collection: typing.Union[java.util.Collection['OilAssayCharacterisation.AssayCut'], typing.Sequence['OilAssayCharacterisation.AssayCut'], typing.Set['OilAssayCharacterisation.AssayCut']]) -> None: ...
    def addTBPCutBoundariesCelsius(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def addTBPCutBoundariesKelvin(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def apply(self) -> None: ...
    @staticmethod
    def calculatePianoMolarMassKgPerMol(pianoHydrocarbonFamilyArray: typing.Union[typing.List['OilAssayCharacterisation.PianoHydrocarbonFamily'], jpype.JArray], intArray: typing.Union[typing.List[int], jpype.JArray], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    def clearCuts(self) -> None: ...
    def clone(self) -> 'OilAssayCharacterisation': ...
    def getBulkApiGravity(self) -> float: ...
    def getBulkDensityKgPerCubicMetreAt60F(self) -> float: ...
    def getBulkNitrogenMassFraction(self) -> float: ...
    def getBulkNitrogenMassPercent(self) -> float: ...
    def getBulkSpecificGravity(self) -> float: ...
    def getBulkSulfurMassFraction(self) -> float: ...
    def getBulkSulfurMassPercent(self) -> float: ...
    def getCuts(self) -> java.util.List['OilAssayCharacterisation.AssayCut']: ...
    def getResolvedMassFractions(self) -> typing.MutableSequence[float]: ...
    def getTotalAssayMass(self) -> float: ...
    def setThermoSystem(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    def setTotalAssayMass(self, double: float) -> None: ...
    class AssayCut(java.lang.Cloneable, java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def clone(self) -> 'OilAssayCharacterisation.AssayCut': ...
        def getLowerBoilingPointKelvin(self) -> float: ...
        def getMassFraction(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getNitrogenMassFraction(self) -> float: ...
        def getStandardComponentName(self) -> java.lang.String: ...
        def getSulfurMassFraction(self) -> float: ...
        def getUpperBoilingPointKelvin(self) -> float: ...
        def getVolumeFraction(self) -> float: ...
        def getWatsonCharacterizationFactor(self) -> float: ...
        def hasBoilingRange(self) -> bool: ...
        def hasLowerBoilingPoint(self) -> bool: ...
        def hasMassFraction(self) -> bool: ...
        def hasMolarMass(self) -> bool: ...
        def hasNitrogenMassFraction(self) -> bool: ...
        def hasSulfurMassFraction(self) -> bool: ...
        def hasUpperBoilingPoint(self) -> bool: ...
        def hasVolumeFraction(self) -> bool: ...
        def hasWatsonCharacterizationFactor(self) -> bool: ...
        def isStandardComponent(self) -> bool: ...
        def resolveAverageBoilingPoint(self) -> float: ...
        def resolveDensity(self) -> float: ...
        def resolveMolarMass(self, double: float, double2: float) -> float: ...
        def withApiGravity(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withAverageBoilingPointCelsius(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withAverageBoilingPointFahrenheit(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withAverageBoilingPointKelvin(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withBoilingRangeCelsius(self, double: float, double2: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withBoilingRangeKelvin(self, double: float, double2: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withDensity(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withDensityKgPerCubicMetre(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withLowerBoilingPointCelsius(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withLowerBoilingPointFahrenheit(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withLowerBoilingPointKelvin(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withMassFraction(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withMolarMass(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withMolarMassGramPerMol(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withMolarMassKgPerMol(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withNitrogenMassFraction(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withNitrogenMassPercent(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withSpecificGravity(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withStandardComponent(self, string: typing.Union[java.lang.String, str]) -> 'OilAssayCharacterisation.AssayCut': ...
        def withSulfurMassFraction(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withSulfurMassPercent(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withUpperBoilingPointCelsius(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withUpperBoilingPointFahrenheit(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withUpperBoilingPointKelvin(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withVolumeFraction(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withVolumePercent(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withWatsonCharacterizationFactor(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
        def withWeightPercent(self, double: float) -> 'OilAssayCharacterisation.AssayCut': ...
    class PianoHydrocarbonFamily(java.lang.Enum['OilAssayCharacterisation.PianoHydrocarbonFamily']):
        PARAFFIN: typing.ClassVar['OilAssayCharacterisation.PianoHydrocarbonFamily'] = ...
        ISO_PARAFFIN: typing.ClassVar['OilAssayCharacterisation.PianoHydrocarbonFamily'] = ...
        AROMATIC: typing.ClassVar['OilAssayCharacterisation.PianoHydrocarbonFamily'] = ...
        NAPHTHENE: typing.ClassVar['OilAssayCharacterisation.PianoHydrocarbonFamily'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'OilAssayCharacterisation.PianoHydrocarbonFamily': ...
        @staticmethod
        def values() -> typing.MutableSequence['OilAssayCharacterisation.PianoHydrocarbonFamily']: ...

class PedersenAsphalteneCharacterization:
    DEFAULT_ASPHALTENE_MW: typing.ClassVar[float] = ...
    DEFAULT_ASPHALTENE_DENSITY: typing.ClassVar[float] = ...
    HEAVY_ASPHALTENE_MW: typing.ClassVar[float] = ...
    MIN_ASPHALTENE_MW: typing.ClassVar[float] = ...
    MAX_ASPHALTENE_MW: typing.ClassVar[float] = ...
    DEFAULT_ASPHALTENE_WEIGHT_FRACTION: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float, double2: float, double3: float): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    @staticmethod
    def TPflash(systemInterface: jneqsim.thermo.system.SystemInterface) -> bool: ...
    @typing.overload
    @staticmethod
    def TPflash(systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float) -> bool: ...
    def addAsphalteneToSystem(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float) -> java.lang.String: ...
    def addDistributedAsphaltene(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, int: int) -> None: ...
    def applyAsphalteneKij(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float) -> None: ...
    def assessStability(self, double: float) -> java.lang.String: ...
    def calculateOnsetPressure(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float) -> float: ...
    def calculateSolubilityParameter(self, double: float) -> float: ...
    def characterize(self) -> None: ...
    def getAcentricFactor(self) -> float: ...
    def getAsphalteneDensity(self) -> float: ...
    def getAsphalteneMW(self) -> float: ...
    def getAsphalteneWeightFraction(self) -> float: ...
    def getBoilingPoint(self) -> float: ...
    def getCriticalPressure(self) -> float: ...
    def getCriticalTemperature(self) -> float: ...
    def getKijAdjustment(self) -> float: ...
    def getNumberOfAsphaltenePseudoComponents(self) -> int: ...
    def getOmegaMultiplier(self) -> float: ...
    def getPcMultiplier(self) -> float: ...
    def getTbMultiplier(self) -> float: ...
    def getTcMultiplier(self) -> float: ...
    def isCharacterized(self) -> bool: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @staticmethod
    def markAsphalteneRichLiquidPhases(systemInterface: jneqsim.thermo.system.SystemInterface) -> bool: ...
    def resetTuningParameters(self) -> None: ...
    def setAsphalteneDensity(self, double: float) -> None: ...
    def setAsphalteneMW(self, double: float) -> None: ...
    def setAsphalteneWeightFraction(self, double: float) -> None: ...
    def setKijAdjustment(self, double: float) -> None: ...
    def setNumberOfAsphaltenePseudoComponents(self, int: int) -> None: ...
    def setOmegaMultiplier(self, double: float) -> None: ...
    def setPcMultiplier(self, double: float) -> None: ...
    def setTbMultiplier(self, double: float) -> None: ...
    def setTcMultiplier(self, double: float) -> None: ...
    def setTuningParameters(self, double: float, double2: float, double3: float) -> None: ...
    def toString(self) -> java.lang.String: ...

class PedersenPlusModelSolver(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, pedersenPlusModel: 'PlusFractionModel.PedersenPlusModel'): ...
    def setJacAB(self) -> None: ...
    def setJacCD(self) -> None: ...
    def setfvecAB(self) -> None: ...
    def setfvecCD(self) -> None: ...
    def solve(self) -> None: ...

class PlusFractionModel(java.io.Serializable):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def getModel(self, string: typing.Union[java.lang.String, str]) -> 'PlusFractionModelInterface': ...
    class PedersenPlusModel: ...

class PlusFractionModelInterface(java.io.Serializable):
    def characterizePlusFraction(self, tBPModelInterface: 'TBPModelInterface') -> bool: ...
    def getCoef(self, int: int) -> float: ...
    def getCoefs(self) -> typing.MutableSequence[float]: ...
    def getDens(self) -> typing.MutableSequence[float]: ...
    def getDensPlus(self) -> float: ...
    def getFirstPlusFractionNumber(self) -> int: ...
    def getFirstTBPFractionNumber(self) -> int: ...
    def getLastPlusFractionNumber(self) -> int: ...
    def getM(self) -> typing.MutableSequence[float]: ...
    def getMPlus(self) -> float: ...
    def getMaxPlusMolarMass(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getNumberOfPlusPseudocomponents(self) -> float: ...
    def getPlusComponentNumber(self) -> int: ...
    def getZ(self) -> typing.MutableSequence[float]: ...
    def getZPlus(self) -> float: ...
    def hasPlusFraction(self) -> bool: ...
    def setLastPlusFractionNumber(self, int: int) -> None: ...

class PseudoComponentCombiner:
    @typing.overload
    @staticmethod
    def characterizeToCommonSlate(list: java.util.List[jneqsim.thermo.system.SystemInterface], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> java.util.List[jneqsim.thermo.system.SystemInterface]: ...
    @typing.overload
    @staticmethod
    def characterizeToCommonSlate(list: java.util.List[jneqsim.thermo.system.SystemInterface], doubleArray: typing.Union[typing.List[float], jpype.JArray], int: int) -> java.util.List[jneqsim.thermo.system.SystemInterface]: ...
    @typing.overload
    @staticmethod
    def characterizeToReference(systemInterface: jneqsim.thermo.system.SystemInterface, systemInterface2: jneqsim.thermo.system.SystemInterface) -> jneqsim.thermo.system.SystemInterface: ...
    @typing.overload
    @staticmethod
    def characterizeToReference(systemInterface: jneqsim.thermo.system.SystemInterface, systemInterface2: jneqsim.thermo.system.SystemInterface, characterizationOptions: CharacterizationOptions) -> jneqsim.thermo.system.SystemInterface: ...
    @typing.overload
    @staticmethod
    def combineReservoirFluids(int: int, collection: typing.Union[java.util.Collection[jneqsim.thermo.system.SystemInterface], typing.Sequence[jneqsim.thermo.system.SystemInterface], typing.Set[jneqsim.thermo.system.SystemInterface]]) -> jneqsim.thermo.system.SystemInterface: ...
    @typing.overload
    @staticmethod
    def combineReservoirFluids(int: int, *systemInterface: jneqsim.thermo.system.SystemInterface) -> jneqsim.thermo.system.SystemInterface: ...
    @staticmethod
    def generateValidationReport(systemInterface: jneqsim.thermo.system.SystemInterface, systemInterface2: jneqsim.thermo.system.SystemInterface, systemInterface3: jneqsim.thermo.system.SystemInterface) -> CharacterizationValidationReport: ...
    @staticmethod
    def normalizeComposition(systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    @staticmethod
    def transferBinaryInteractionParameters(systemInterface: jneqsim.thermo.system.SystemInterface, systemInterface2: jneqsim.thermo.system.SystemInterface) -> None: ...

class Recombine:
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, systemInterface2: jneqsim.thermo.system.SystemInterface): ...
    def getGOR(self) -> float: ...
    def getOilDesnity(self) -> float: ...
    def getRecombinedSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def runRecombination(self) -> jneqsim.thermo.system.SystemInterface: ...
    def setGOR(self, double: float) -> None: ...
    def setOilDesnity(self, double: float) -> None: ...

class SarirAtmosphericAssay:
    CUT_COUNT: typing.ClassVar[int] = ...
    BULK_DENSITY_TOLERANCE_KG_PER_CUBIC_METRE: typing.ClassVar[float] = ...
    BULK_MOLAR_MASS_TOLERANCE_KG_PER_MOL: typing.ClassVar[float] = ...
    @staticmethod
    def calculateBulkMolarMassKgPerMol(doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    @staticmethod
    def calculateBulkSpecificGravity(doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    @typing.overload
    @staticmethod
    def create(systemInterface: jneqsim.thermo.system.SystemInterface, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> OilAssayCharacterisation: ...
    @typing.overload
    @staticmethod
    def create(systemInterface: jneqsim.thermo.system.SystemInterface, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> OilAssayCharacterisation: ...
    @staticmethod
    def getCutVolumePercent() -> typing.MutableSequence[float]: ...

class SarirAtmosphericReference:
    DOI: typing.ClassVar[java.lang.String] = ...
    ARTICLE_URL: typing.ClassVar[java.lang.String] = ...
    LICENSE: typing.ClassVar[java.lang.String] = ...
    PUBLICATION_DATE: typing.ClassVar[java.lang.String] = ...
    @staticmethod
    def areSimulationProductRatesImposedSpecifications() -> bool: ...
    @staticmethod
    def calculateAbsoluteRelativeErrorPercent(double: float, double2: float) -> float: ...
    @staticmethod
    def getBottomPumpAroundRateKgPerHour() -> float: ...
    @staticmethod
    def getColumnCrudeFeedRateKgPerHour() -> float: ...
    @staticmethod
    def getColumnFeedPressureKPa() -> float: ...
    @staticmethod
    def getColumnFeedTemperatureCelsius() -> float: ...
    @staticmethod
    def getColumnTrayCount() -> int: ...
    @staticmethod
    def getCrudeApiGravityAt60F() -> float: ...
    @staticmethod
    def getCrudeAverageMolarMassKgPerMol() -> float: ...
    @staticmethod
    def getCrudeDensityAt15CKgPerCubicMetre() -> float: ...
    @staticmethod
    def getCrudeSulfurMassPercent() -> float: ...
    @staticmethod
    def getDieselStripperSteamRateKgPerHour() -> float: ...
    @staticmethod
    def getFeedTrayFromTop() -> int: ...
    @staticmethod
    def getKeroseneStripperSteamRateKgPerHour() -> float: ...
    @staticmethod
    def getMainColumnSteamRateKgPerHour() -> float: ...
    @staticmethod
    def getProductQualities() -> typing.MutableSequence['SarirAtmosphericReference.ProductQualityReference']: ...
    @staticmethod
    def getProductYield(string: typing.Union[java.lang.String, str]) -> 'SarirAtmosphericReference.ProductYieldReference': ...
    @staticmethod
    def getProductYields() -> typing.MutableSequence['SarirAtmosphericReference.ProductYieldReference']: ...
    @staticmethod
    def getTbpCumulativeVolumePercent() -> typing.MutableSequence[float]: ...
    @staticmethod
    def getTbpTemperatureCelsius() -> typing.MutableSequence[float]: ...
    @staticmethod
    def getTbpTemperatureKelvin() -> typing.MutableSequence[float]: ...
    @staticmethod
    def getTerminalResidueLowerBoundaryCelsius() -> float: ...
    @staticmethod
    def getTerminalResidueVolumePercent() -> float: ...
    @staticmethod
    def getTopPumpAroundRateKgPerHour() -> float: ...
    @staticmethod
    def hasCompleteNumericTbpCurve() -> bool: ...
    @staticmethod
    def hasResolvedLightEndComposition() -> bool: ...
    @staticmethod
    def isIndependentYieldValidationCase() -> bool: ...
    class ProductQualityReference(java.io.Serializable):
        def getLaboratoryFivePercentCelsius(self) -> float: ...
        def getLaboratoryNinetyFivePercentCelsius(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getSimulationFivePercentCelsius(self) -> float: ...
        def getSimulationNinetyFivePercentCelsius(self) -> float: ...
    class ProductYieldReference(java.io.Serializable):
        def getAbsoluteRelativeErrorPercent(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getPlantMetricTonPerDay(self) -> float: ...
        def getSimulationMetricTonPerDay(self) -> float: ...

class TBPModelInterface:
    def calcAcentricFactor(self, double: float, double2: float) -> float: ...
    def calcAcentricFactorKeslerLee(self, double: float, double2: float) -> float: ...
    def calcCriticalViscosity(self, double: float, double2: float) -> float: ...
    def calcCriticalVolume(self, double: float, double2: float) -> float: ...
    def calcPC(self, double: float, double2: float) -> float: ...
    def calcParachorParameter(self, double: float, double2: float) -> float: ...
    def calcRacketZ(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float) -> float: ...
    def calcTB(self, double: float, double2: float) -> float: ...
    def calcTC(self, double: float, double2: float) -> float: ...
    def calcWatsonCharacterizationFactor(self, double: float, double2: float) -> float: ...
    def calcm(self, double: float, double2: float) -> float: ...
    def getBoilingPoint(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def isCalcm(self) -> bool: ...
    def setBoilingPoint(self, double: float) -> None: ...

class WaxModelInterface(java.io.Serializable, java.lang.Cloneable):
    def addTBPWax(self) -> None: ...
    def clone(self) -> 'WaxModelInterface': ...
    def getParameterWaxHeatOfFusion(self) -> typing.MutableSequence[float]: ...
    def getParameterWaxTriplePointTemperature(self) -> typing.MutableSequence[float]: ...
    def getWaxParameters(self) -> typing.MutableSequence[float]: ...
    def removeWax(self) -> None: ...
    @typing.overload
    def setParameterWaxHeatOfFusion(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def setParameterWaxHeatOfFusion(self, int: int, double: float) -> None: ...
    @typing.overload
    def setParameterWaxTriplePointTemperature(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def setParameterWaxTriplePointTemperature(self, int: int, double: float) -> None: ...
    def setWaxParameter(self, int: int, double: float) -> None: ...
    def setWaxParameters(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...

class PlusCharacterize(java.io.Serializable, CharacteriseInterface):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def addCharacterizedPlusFraction(self) -> None: ...
    def addHeavyEnd(self) -> None: ...
    def addPseudoTBPfraction(self, int: int, int2: int) -> None: ...
    def addTBPFractions(self) -> None: ...
    def characterizePlusFraction(self) -> None: ...
    def generatePlusFractions(self, int: int, int2: int, double: float, double2: float) -> None: ...
    def generateTBPFractions(self) -> None: ...
    def getCarbonNumberVector(self) -> typing.MutableSequence[int]: ...
    def getCoef(self, int: int) -> float: ...
    def getCoefs(self) -> typing.MutableSequence[float]: ...
    def getDensLastTBP(self) -> float: ...
    def getDensPlus(self) -> float: ...
    def getFirstPlusFractionNumber(self) -> int: ...
    def getLastPlusFractionNumber(self) -> int: ...
    def getLength(self) -> int: ...
    def getMPlus(self) -> float: ...
    def getNumberOfPseudocomponents(self) -> int: ...
    @typing.overload
    def getPlusCoefs(self, int: int) -> float: ...
    @typing.overload
    def getPlusCoefs(self) -> typing.MutableSequence[float]: ...
    def getStartPlus(self) -> int: ...
    def getZPlus(self) -> float: ...
    def groupTBPfractions(self) -> bool: ...
    def hasPlusFraction(self) -> bool: ...
    def isPseudocomponents(self) -> bool: ...
    def removeTBPfraction(self) -> None: ...
    def setCarbonNumberVector(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def setCoefs(self, double: float, int: int) -> None: ...
    @typing.overload
    def setCoefs(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setDensLastTBP(self, double: float) -> None: ...
    def setDensPlus(self, double: float) -> None: ...
    def setFirstPlusFractionNumber(self, int: int) -> None: ...
    def setHeavyTBPtoPlus(self) -> None: ...
    def setMPlus(self, double: float) -> None: ...
    def setNumberOfPseudocomponents(self, int: int) -> None: ...
    def setPlusCoefs(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setPseudocomponents(self, boolean: bool) -> None: ...
    def setZPlus(self, double: float) -> None: ...
    def solve(self) -> None: ...

class TBPCharacterize(PlusCharacterize):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def addHeavyEnd(self) -> None: ...
    def addPlusFraction(self) -> None: ...
    def addTBPFractions(self) -> None: ...
    def getCalcTBPfractions(self) -> typing.MutableSequence[float]: ...
    def getCarbonNumberVector(self) -> typing.MutableSequence[int]: ...
    def getDensPlus(self) -> float: ...
    def getLength(self) -> int: ...
    @typing.overload
    def getPlusCoefs(self, int: int) -> float: ...
    @typing.overload
    def getPlusCoefs(self) -> typing.MutableSequence[float]: ...
    def getTBP_M(self) -> typing.MutableSequence[float]: ...
    @typing.overload
    def getTBPdens(self, int: int) -> float: ...
    @typing.overload
    def getTBPdens(self) -> typing.MutableSequence[float]: ...
    @typing.overload
    def getTBPfractions(self, int: int) -> float: ...
    @typing.overload
    def getTBPfractions(self) -> typing.MutableSequence[float]: ...
    def groupTBPfractions(self) -> bool: ...
    def isPseudocomponents(self) -> bool: ...
    def saveCharacterizedFluid(self) -> bool: ...
    def setCalcTBPfractions(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setCarbonNumberVector(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def setCoefs(self, double: float, int: int) -> None: ...
    @typing.overload
    def setCoefs(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setDensPlus(self, double: float) -> None: ...
    def setPlusCoefs(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setTBP_M(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setTBPdens(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setTBPfractions(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def solve(self) -> None: ...
    def solveAB(self) -> None: ...

class LumpingModel(java.io.Serializable):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def getModel(self, string: typing.Union[java.lang.String, str]) -> LumpingModelInterface: ...
    class NoLumpingModel(jneqsim.thermo.characterization.LumpingModel.StandardLumpingModel):
        def __init__(self, lumpingModel: 'LumpingModel'): ...
        def generateLumpedComposition(self, characterise: Characterise) -> None: ...
        def getFractionOfHeavyEnd(self, int: int) -> float: ...
    class PVTLumpingModel(jneqsim.thermo.characterization.LumpingModel.StandardLumpingModel):
        def __init__(self, lumpingModel: 'LumpingModel'): ...
        def generateLumpedComposition(self, characterise: Characterise) -> None: ...
        def getFractionOfHeavyEnd(self, int: int) -> float: ...
        def setNumberOfPseudoComponents(self, int: int) -> None: ...
    class StandardLumpingModel(LumpingModelInterface, java.lang.Cloneable, java.io.Serializable):
        def __init__(self, lumpingModel: 'LumpingModel'): ...
        def generateLumpedComposition(self, characterise: Characterise) -> None: ...
        def getCustomBoundaries(self) -> typing.MutableSequence[int]: ...
        def getFractionOfHeavyEnd(self, int: int) -> float: ...
        def getLumpedComponentName(self, int: int) -> java.lang.String: ...
        def getLumpedComponentNames(self) -> typing.MutableSequence[java.lang.String]: ...
        def getName(self) -> java.lang.String: ...
        def getNumberOfLumpedComponents(self) -> int: ...
        def getNumberOfPseudoComponents(self) -> int: ...
        def hasCustomBoundaries(self) -> bool: ...
        def setCustomBoundaries(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
        def setNumberOfLumpedComponents(self, int: int) -> None: ...
        def setNumberOfPseudoComponents(self, int: int) -> None: ...

class TBPfractionModel(java.io.Serializable):
    def __init__(self): ...
    @staticmethod
    def calcAPIGravity(double: float) -> float: ...
    @staticmethod
    def calcSpecificGravity(double: float) -> float: ...
    def calcWatsonKFactor(self, double: float, double2: float) -> float: ...
    @staticmethod
    def getAvailableModels() -> typing.MutableSequence[java.lang.String]: ...
    def getModel(self, string: typing.Union[java.lang.String, str]) -> TBPModelInterface: ...
    def recommendTBPModel(self, double: float, double2: float, string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    class CavettModel(jneqsim.thermo.characterization.TBPfractionModel.TBPBaseModel):
        def __init__(self, tBPfractionModel: 'TBPfractionModel'): ...
        def calcAcentricFactor(self, double: float, double2: float) -> float: ...
        def calcPC(self, double: float, double2: float) -> float: ...
        def calcRacketZ(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float) -> float: ...
        def calcTB(self, double: float, double2: float) -> float: ...
        def calcTC(self, double: float, double2: float) -> float: ...
    class LeeKesler(jneqsim.thermo.characterization.TBPfractionModel.TBPBaseModel):
        def __init__(self, tBPfractionModel: 'TBPfractionModel'): ...
        def calcAcentricFactor(self, double: float, double2: float) -> float: ...
        def calcPC(self, double: float, double2: float) -> float: ...
        def calcRacketZ(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float) -> float: ...
        def calcTC(self, double: float, double2: float) -> float: ...
    class PedersenTBPModelPR(jneqsim.thermo.characterization.TBPfractionModel.PedersenTBPModelSRK):
        def __init__(self, tBPfractionModel: 'TBPfractionModel'): ...
    class PedersenTBPModelPR2(jneqsim.thermo.characterization.TBPfractionModel.PedersenTBPModelSRK):
        def __init__(self, tBPfractionModel: 'TBPfractionModel'): ...
        def calcTB(self, double: float, double2: float) -> float: ...
    class PedersenTBPModelPRHeavyOil(jneqsim.thermo.characterization.TBPfractionModel.PedersenTBPModelPR):
        def __init__(self, tBPfractionModel: 'TBPfractionModel'): ...
    class PedersenTBPModelSRK(jneqsim.thermo.characterization.TBPfractionModel.TBPBaseModel):
        def __init__(self, tBPfractionModel: 'TBPfractionModel'): ...
        def calcPC(self, double: float, double2: float) -> float: ...
        def calcRacketZ(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float) -> float: ...
        def calcTB(self, double: float, double2: float) -> float: ...
        def calcTC(self, double: float, double2: float) -> float: ...
        def calcm(self, double: float, double2: float) -> float: ...
    class PedersenTBPModelSRKHeavyOil(jneqsim.thermo.characterization.TBPfractionModel.PedersenTBPModelSRK):
        def __init__(self, tBPfractionModel: 'TBPfractionModel'): ...
    class RiaziDaubert(jneqsim.thermo.characterization.TBPfractionModel.PedersenTBPModelSRK):
        def __init__(self, tBPfractionModel: 'TBPfractionModel'): ...
        def calcAcentricFactor(self, double: float, double2: float) -> float: ...
        def calcAcentricFactor2(self, double: float, double2: float) -> float: ...
        def calcPC(self, double: float, double2: float) -> float: ...
        def calcTB(self, double: float, double2: float) -> float: ...
        def calcTC(self, double: float, double2: float) -> float: ...
    class StandingModel(jneqsim.thermo.characterization.TBPfractionModel.TBPBaseModel):
        def __init__(self, tBPfractionModel: 'TBPfractionModel'): ...
        def calcAcentricFactor(self, double: float, double2: float) -> float: ...
        def calcPC(self, double: float, double2: float) -> float: ...
        def calcRacketZ(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float) -> float: ...
        def calcTC(self, double: float, double2: float) -> float: ...
    class TBPBaseModel(TBPModelInterface, java.lang.Cloneable, java.io.Serializable):
        def __init__(self, tBPfractionModel: 'TBPfractionModel'): ...
        def calcAcentricFactor(self, double: float, double2: float) -> float: ...
        def calcAcentricFactorKeslerLee(self, double: float, double2: float) -> float: ...
        def calcCriticalViscosity(self, double: float, double2: float) -> float: ...
        def calcCriticalVolume(self, double: float, double2: float) -> float: ...
        def calcParachorParameter(self, double: float, double2: float) -> float: ...
        def calcRacketZ(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float) -> float: ...
        def calcTB(self, double: float, double2: float) -> float: ...
        def calcWatsonCharacterizationFactor(self, double: float, double2: float) -> float: ...
        def calcm(self, double: float, double2: float) -> float: ...
        def getBoilingPoint(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def isCalcm(self) -> bool: ...
        def setBoilingPoint(self, double: float) -> None: ...
    class TwuModel(jneqsim.thermo.characterization.TBPfractionModel.TBPBaseModel):
        def __init__(self, tBPfractionModel: 'TBPfractionModel'): ...
        def calcCriticalVolume(self, double: float, double2: float) -> float: ...
        def calcPC(self, double: float, double2: float) -> float: ...
        def calcRacketZ(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float) -> float: ...
        def calcTC(self, double: float, double2: float) -> float: ...
        def calculateTfunc(self, double: float, double2: float) -> float: ...
        def computeGradient(self, double: float, double2: float) -> float: ...
        def solveMW(self, double: float) -> float: ...

class WaxCharacterise(java.io.Serializable, java.lang.Cloneable):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def clone(self) -> 'WaxCharacterise': ...
    @typing.overload
    def getModel(self) -> WaxModelInterface: ...
    @typing.overload
    def getModel(self, string: typing.Union[java.lang.String, str]) -> WaxModelInterface: ...
    def setModel(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setModelName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    class PedersenWaxModel(jneqsim.thermo.characterization.WaxCharacterise.WaxBaseModel):
        def __init__(self, waxCharacterise: 'WaxCharacterise'): ...
        def addTBPWax(self) -> None: ...
        def calcHeatOfFusion(self, int: int) -> float: ...
        def calcPCwax(self, int: int, string: typing.Union[java.lang.String, str]) -> float: ...
        def calcParaffinDensity(self, int: int) -> float: ...
        def calcTriplePointTemperature(self, int: int) -> float: ...
        def removeWax(self) -> None: ...
    class WaxBaseModel(WaxModelInterface):
        def __init__(self, waxCharacterise: 'WaxCharacterise'): ...
        def addTBPWax(self) -> None: ...
        def clone(self) -> 'WaxCharacterise.WaxBaseModel': ...
        def getParameterWaxHeatOfFusion(self) -> typing.MutableSequence[float]: ...
        def getParameterWaxTriplePointTemperature(self) -> typing.MutableSequence[float]: ...
        def getWaxParameters(self) -> typing.MutableSequence[float]: ...
        @typing.overload
        def setParameterWaxHeatOfFusion(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
        @typing.overload
        def setParameterWaxHeatOfFusion(self, int: int, double: float) -> None: ...
        @typing.overload
        def setParameterWaxTriplePointTemperature(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
        @typing.overload
        def setParameterWaxTriplePointTemperature(self, int: int, double: float) -> None: ...
        def setWaxParameter(self, int: int, double: float) -> None: ...
        def setWaxParameters(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.thermo.characterization")``.

    AlDiwiniyaAtmosphericReference: typing.Type[AlDiwiniyaAtmosphericReference]
    AsphalteneCharacterization: typing.Type[AsphalteneCharacterization]
    BioFeedstock: typing.Type[BioFeedstock]
    BiomassCharacterization: typing.Type[BiomassCharacterization]
    Characterise: typing.Type[Characterise]
    CharacteriseInterface: typing.Type[CharacteriseInterface]
    CharacterizationOptions: typing.Type[CharacterizationOptions]
    CharacterizationValidationReport: typing.Type[CharacterizationValidationReport]
    DoeBigHillSweetAssay: typing.Type[DoeBigHillSweetAssay]
    LumpingConfigBuilder: typing.Type[LumpingConfigBuilder]
    LumpingModel: typing.Type[LumpingModel]
    LumpingModelInterface: typing.Type[LumpingModelInterface]
    LumpingResult: typing.Type[LumpingResult]
    NewtonSolveAB: typing.Type[NewtonSolveAB]
    NewtonSolveABCD: typing.Type[NewtonSolveABCD]
    NewtonSolveCDplus: typing.Type[NewtonSolveCDplus]
    OilAssayCharacterisation: typing.Type[OilAssayCharacterisation]
    PedersenAsphalteneCharacterization: typing.Type[PedersenAsphalteneCharacterization]
    PedersenPlusModelSolver: typing.Type[PedersenPlusModelSolver]
    PlusCharacterize: typing.Type[PlusCharacterize]
    PlusFractionModel: typing.Type[PlusFractionModel]
    PlusFractionModelInterface: typing.Type[PlusFractionModelInterface]
    PseudoComponentCombiner: typing.Type[PseudoComponentCombiner]
    Recombine: typing.Type[Recombine]
    SarirAtmosphericAssay: typing.Type[SarirAtmosphericAssay]
    SarirAtmosphericReference: typing.Type[SarirAtmosphericReference]
    TBPCharacterize: typing.Type[TBPCharacterize]
    TBPModelInterface: typing.Type[TBPModelInterface]
    TBPfractionModel: typing.Type[TBPfractionModel]
    WaxCharacterise: typing.Type[WaxCharacterise]
    WaxModelInterface: typing.Type[WaxModelInterface]
