
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment.failure
import jneqsim.process.processmodel
import jneqsim.process.safety.risk
import typing



class DynamicRiskResult(jneqsim.process.safety.risk.OperationalRiskResult, java.io.Serializable):
    def __init__(self): ...
    @typing.overload
    def calculateStatistics(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], intArray: typing.Union[typing.List[int], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def calculateStatistics(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray], intArray: typing.Union[typing.List[int], jpype.JArray], intArray2: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    def compareWithStatic(self, operationalRiskResult: jneqsim.process.safety.risk.OperationalRiskResult) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getMeanSteadyStateLoss(self) -> float: ...
    def getMeanTransientCount(self) -> float: ...
    def getMeanTransientLoss(self) -> float: ...
    def getP10TransientLoss(self) -> float: ...
    def getP50TransientLoss(self) -> float: ...
    def getP90TransientLoss(self) -> float: ...
    def getRampUpTimeHours(self) -> float: ...
    def getTimestepHours(self) -> float: ...
    def getTotalMeanLoss(self) -> float: ...
    def getTotalTransientEvents(self) -> int: ...
    def getTransientLossFraction(self) -> float: ...
    def getTransientLossPercent(self) -> float: ...
    def isSimulateTransients(self) -> bool: ...
    def setRampUpTimeHours(self, double: float) -> None: ...
    def setSimulateTransients(self, boolean: bool) -> None: ...
    def setTimestepHours(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def toString(self) -> java.lang.String: ...

class DynamicRiskSimulator(jneqsim.process.safety.risk.OperationalRiskSimulator, java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def getProductionProfiles(self) -> java.util.List['ProductionProfile']: ...
    def getRampUpTimeHours(self) -> float: ...
    def getTimestepHours(self) -> float: ...
    def getTransientStats(self) -> 'TransientLossStatistics': ...
    def runDynamicSimulation(self, int: int, double: float) -> DynamicRiskResult: ...
    def setRampUpProfile(self, rampProfile: 'DynamicRiskSimulator.RampProfile') -> 'DynamicRiskSimulator': ...
    def setRampUpTimeHours(self, double: float) -> 'DynamicRiskSimulator': ...
    def setShutdownProfile(self, rampProfile: 'DynamicRiskSimulator.RampProfile') -> 'DynamicRiskSimulator': ...
    def setShutdownTimeHours(self, double: float) -> 'DynamicRiskSimulator': ...
    def setSimulateTransients(self, boolean: bool) -> 'DynamicRiskSimulator': ...
    def setTimestepHours(self, double: float) -> 'DynamicRiskSimulator': ...
    def simulateFailureEvent(self, equipmentFailureMode: jneqsim.process.equipment.failure.EquipmentFailureMode, double: float) -> 'ProductionProfile': ...
    class RampProfile(java.lang.Enum['DynamicRiskSimulator.RampProfile']):
        LINEAR: typing.ClassVar['DynamicRiskSimulator.RampProfile'] = ...
        EXPONENTIAL: typing.ClassVar['DynamicRiskSimulator.RampProfile'] = ...
        S_CURVE: typing.ClassVar['DynamicRiskSimulator.RampProfile'] = ...
        STEP: typing.ClassVar['DynamicRiskSimulator.RampProfile'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'DynamicRiskSimulator.RampProfile': ...
        @staticmethod
        def values() -> typing.MutableSequence['DynamicRiskSimulator.RampProfile']: ...

class ProductionProfile(java.io.Serializable):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def calculateTotals(self) -> None: ...
    def getBaselineProduction(self) -> float: ...
    def getDegradedProduction(self) -> float: ...
    def getEquipmentName(self) -> java.lang.String: ...
    def getFailureMode(self) -> java.lang.String: ...
    def getProductionLossPercent(self) -> float: ...
    def getRampUpDuration(self) -> float: ...
    def getRampUpTransientLoss(self) -> float: ...
    def getRepairDuration(self) -> float: ...
    def getShutdownDuration(self) -> float: ...
    def getShutdownTransientLoss(self) -> float: ...
    def getSteadyStateDuration(self) -> float: ...
    def getSteadyStateLoss(self) -> float: ...
    def getTimeSeries(self) -> java.util.List['ProductionProfile.TimePoint']: ...
    def getTotalLoss(self) -> float: ...
    def getTotalProduction(self) -> float: ...
    def getTotalTransientLoss(self) -> float: ...
    def getTransientLossFraction(self) -> float: ...
    def setBaselineProduction(self, double: float) -> None: ...
    def setDegradedProduction(self, double: float) -> None: ...
    def setFailureMode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRampUpDuration(self, double: float) -> None: ...
    def setRampUpTransientLoss(self, double: float) -> None: ...
    def setRepairDuration(self, double: float) -> None: ...
    def setShutdownDuration(self, double: float) -> None: ...
    def setShutdownTransientLoss(self, double: float) -> None: ...
    def setSteadyStateDuration(self, double: float) -> None: ...
    def setSteadyStateLoss(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def toString(self) -> java.lang.String: ...
    class TimePoint(java.io.Serializable):
        def __init__(self, double: float, double2: float, string: typing.Union[java.lang.String, str]): ...
        def getPhase(self) -> java.lang.String: ...
        def getProductionRate(self) -> float: ...
        def getTime(self) -> float: ...

class TransientLossStatistics(java.io.Serializable):
    def __init__(self): ...
    def addProfile(self, productionProfile: ProductionProfile) -> None: ...
    def getMeanTransientLoss(self) -> float: ...
    def getRampUpFraction(self) -> float: ...
    def getShutdownFraction(self) -> float: ...
    def getSteadyStateFraction(self) -> float: ...
    def getTotalEventCount(self) -> int: ...
    def getTotalLoss(self) -> float: ...
    def getTotalRampUpLoss(self) -> float: ...
    def getTotalShutdownLoss(self) -> float: ...
    def getTotalSteadyStateLoss(self) -> float: ...
    def getTotalTransientLoss(self) -> float: ...
    def getTransientFraction(self) -> float: ...
    def getTransientPercent(self) -> float: ...
    def reset(self) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def toString(self) -> java.lang.String: ...
    def update(self, dynamicRiskResult: DynamicRiskResult) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.risk.dynamic")``.

    DynamicRiskResult: typing.Type[DynamicRiskResult]
    DynamicRiskSimulator: typing.Type[DynamicRiskSimulator]
    ProductionProfile: typing.Type[ProductionProfile]
    TransientLossStatistics: typing.Type[TransientLossStatistics]
