
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.processmodel
import typing



class PinchAnalyzer(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def addColdStream(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float) -> None: ...
    def addHotStream(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float) -> None: ...
    def analyze(self) -> None: ...
    def extractStreams(self) -> None: ...
    def getColdCompositeCurve(self) -> java.util.List[typing.MutableSequence[float]]: ...
    def getColdStreams(self) -> java.util.List['PinchAnalyzer.HeatStream']: ...
    def getEnergyRecoveryFraction(self) -> float: ...
    def getGrandCompositeCurve(self) -> java.util.List[typing.MutableSequence[float]]: ...
    def getHotCompositeCurve(self) -> java.util.List[typing.MutableSequence[float]]: ...
    def getHotStreams(self) -> java.util.List['PinchAnalyzer.HeatStream']: ...
    def getMatches(self) -> java.util.List['PinchAnalyzer.HeatExchangerMatch']: ...
    def getMinApproachTemperature(self) -> float: ...
    def getMinColdUtilityDuty(self) -> float: ...
    def getMinHotUtilityDuty(self) -> float: ...
    def getPinchTemperature(self) -> float: ...
    def getTotalRecoverableEnergy(self) -> float: ...
    def setMinApproachTemperature(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    class HeatExchangerMatch(java.io.Serializable):
        hotStreamName: java.lang.String = ...
        coldStreamName: java.lang.String = ...
        recoverableDuty: float = ...
        lmtd: float = ...
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float): ...
    class HeatStream(java.io.Serializable):
        name: java.lang.String = ...
        supplyTemperature: float = ...
        targetTemperature: float = ...
        duty: float = ...
        heatCapacityFlowRate: float = ...
        isHot: bool = ...
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, boolean: bool): ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.util.heatintegration")``.

    PinchAnalyzer: typing.Type[PinchAnalyzer]
