
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jneqsim.process.equipment.separator.sectiontype
import typing



class SepDesignSection:
    totalWeight: float = ...
    totalHeight: float = ...
    ANSIclass: int = ...
    nominalSize: java.lang.String = ...
    def __init__(self, separatorSection: jneqsim.process.equipment.separator.sectiontype.SeparatorSection): ...
    def calcDesign(self) -> None: ...
    def getANSIclass(self) -> int: ...
    def getNominalSize(self) -> java.lang.String: ...
    def getTotalHeight(self) -> float: ...
    def getTotalWeight(self) -> float: ...
    def setANSIclass(self, int: int) -> None: ...
    def setNominalSize(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTotalHeight(self, double: float) -> None: ...
    def setTotalWeight(self, double: float) -> None: ...

class DistillationTraySection(SepDesignSection):
    def __init__(self, separatorSection: jneqsim.process.equipment.separator.sectiontype.SeparatorSection): ...
    def calcDesign(self) -> None: ...

class MecMeshSection(SepDesignSection):
    def __init__(self, separatorSection: jneqsim.process.equipment.separator.sectiontype.SeparatorSection): ...
    def calcDesign(self) -> None: ...

class MechManwaySection(SepDesignSection):
    def __init__(self, separatorSection: jneqsim.process.equipment.separator.sectiontype.SeparatorSection): ...
    def calcDesign(self) -> None: ...

class MechNozzleSection(SepDesignSection):
    def __init__(self, separatorSection: jneqsim.process.equipment.separator.sectiontype.SeparatorSection): ...
    def calcDesign(self) -> None: ...

class MechVaneSection(SepDesignSection):
    def __init__(self, separatorSection: jneqsim.process.equipment.separator.sectiontype.SeparatorSection): ...
    def calcDesign(self) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.separator.sectiontype")``.

    DistillationTraySection: typing.Type[DistillationTraySection]
    MecMeshSection: typing.Type[MecMeshSection]
    MechManwaySection: typing.Type[MechManwaySection]
    MechNozzleSection: typing.Type[MechNozzleSection]
    MechVaneSection: typing.Type[MechVaneSection]
    SepDesignSection: typing.Type[SepDesignSection]
