import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import typing

class AsphalteneInhibitorPerformance(java.io.Serializable):
    def __init__(self): ...
    def evaluate(self) -> None: ...
    def getAopShiftBar(self) -> float: ...
    def getCiiReduction(self) -> float: ...
    def getEfficacyFraction(self) -> float: ...
    def getInhibitedAopBara(self) -> float: ...
    def getInhibitedCii(self) -> float: ...
    def getStandardsApplied(
        self,
    ) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isEvaluated(self) -> bool: ...
    def isStableAfterTreatment(self) -> bool: ...
    def setBaseAsphalteneOnsetPressureBara(self, double: float) -> None: ...
    def setBaseColloidalInstabilityIndex(self, double: float) -> None: ...
    def setDoseAt50PctEfficacyMgL(self, double: float) -> None: ...
    def setDoseMgL(self, double: float) -> None: ...
    def setInhibitorChemistry(
        self, inhibitorChemistry: "AsphalteneInhibitorPerformance.InhibitorChemistry"
    ) -> None: ...
    def setMaxAopShiftBar(self, double: float) -> None: ...
    def setMaxCiiReduction(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

    class InhibitorChemistry(
        java.lang.Enum["AsphalteneInhibitorPerformance.InhibitorChemistry"]
    ):
        ALKYLPHENOL_RESIN: typing.ClassVar[
            "AsphalteneInhibitorPerformance.InhibitorChemistry"
        ] = ...
        POAA: typing.ClassVar["AsphalteneInhibitorPerformance.InhibitorChemistry"] = ...
        SURFACTANT: typing.ClassVar[
            "AsphalteneInhibitorPerformance.InhibitorChemistry"
        ] = ...
        POLYMERIC_ESTER: typing.ClassVar[
            "AsphalteneInhibitorPerformance.InhibitorChemistry"
        ] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "AsphalteneInhibitorPerformance.InhibitorChemistry": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["AsphalteneInhibitorPerformance.InhibitorChemistry"]
        ): ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.chemistry.asphaltene")``.

    AsphalteneInhibitorPerformance: typing.Type[AsphalteneInhibitorPerformance]
