import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.safety.risk
import typing

class LOPAResult(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addLayer(
        self,
        string: typing.Union[java.lang.String, str],
        double: float,
        double2: float,
        double3: float,
    ) -> None: ...
    def getGapToTarget(self) -> float: ...
    def getInitiatingEventFrequency(self) -> float: ...
    def getLayers(self) -> java.util.List["LOPAResult.ProtectionLayer"]: ...
    def getMitigatedFrequency(self) -> float: ...
    def getRequiredAdditionalRRF(self) -> float: ...
    def getRequiredAdditionalSIL(self) -> int: ...
    @staticmethod
    def getSTS0131OverpressureTargetFrequency(
        double: float, double2: float, double3: float
    ) -> float: ...
    @staticmethod
    def getSTS0131PressureCategory(
        double: float, double2: float, double3: float
    ) -> "LOPAResult.STS0131PressureCategory": ...
    def getScenarioName(self) -> java.lang.String: ...
    def getTargetFrequency(self) -> float: ...
    def getTotalRRF(self) -> float: ...
    def isTargetMet(self) -> bool: ...
    def setInitiatingEventFrequency(self, double: float) -> None: ...
    def setMitigatedFrequency(self, double: float) -> None: ...
    def setTargetFrequency(self, double: float) -> None: ...
    def setTargetFrequencyFromSTS0131Overpressure(
        self, double: float, double2: float, double3: float
    ) -> "LOPAResult": ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def toString(self) -> java.lang.String: ...
    def toVisualization(self) -> java.lang.String: ...

    class ProtectionLayer(java.io.Serializable):
        def __init__(
            self,
            string: typing.Union[java.lang.String, str],
            double: float,
            double2: float,
            double3: float,
        ): ...
        def getContribution(self) -> float: ...
        def getFrequencyAfter(self) -> float: ...
        def getFrequencyBefore(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getPfd(self) -> float: ...
        def getRRF(self) -> float: ...

    class STS0131PressureCategory(java.lang.Enum["LOPAResult.STS0131PressureCategory"]):
        BELOW_OR_AT_DESIGN_PRESSURE: typing.ClassVar[
            "LOPAResult.STS0131PressureCategory"
        ] = ...
        ABOVE_DESIGN_TO_TEST_PRESSURE: typing.ClassVar[
            "LOPAResult.STS0131PressureCategory"
        ] = ...
        ABOVE_TEST_TO_TWO_TIMES_DESIGN_PRESSURE: typing.ClassVar[
            "LOPAResult.STS0131PressureCategory"
        ] = ...
        ABOVE_TWO_TIMES_DESIGN_PRESSURE: typing.ClassVar[
            "LOPAResult.STS0131PressureCategory"
        ] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "LOPAResult.STS0131PressureCategory": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["LOPAResult.STS0131PressureCategory"]
        ): ...

class SILVerificationResult(java.io.Serializable):
    def __init__(self, safetyInstrumentedFunction: "SafetyInstrumentedFunction"): ...
    def addComponentContribution(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        double: float,
        double2: float,
        double3: float,
    ) -> None: ...
    def getAchievedSIL(self) -> int: ...
    def getClaimedSIL(self) -> int: ...
    def getComponentContributions(
        self,
    ) -> java.util.List["SILVerificationResult.ComponentContribution"]: ...
    def getDiagnosticCoverage(self) -> float: ...
    def getErrors(
        self,
    ) -> java.util.List["SILVerificationResult.VerificationIssue"]: ...
    def getHardwareFaultTolerance(self) -> int: ...
    def getIssues(
        self,
    ) -> java.util.List["SILVerificationResult.VerificationIssue"]: ...
    def getPfdAverage(self) -> float: ...
    def getPfdUpper(self) -> float: ...
    def getSif(self) -> "SafetyInstrumentedFunction": ...
    def getSystematicCapability(self) -> int: ...
    def getWarnings(
        self,
    ) -> java.util.List["SILVerificationResult.VerificationIssue"]: ...
    def hasErrors(self) -> bool: ...
    def isSilAchieved(self) -> bool: ...
    def setDiagnosticCoverage(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def toReport(self) -> java.lang.String: ...
    def toString(self) -> java.lang.String: ...

    class ComponentContribution(java.io.Serializable):
        def __init__(
            self,
            string: typing.Union[java.lang.String, str],
            string2: typing.Union[java.lang.String, str],
            double: float,
            double2: float,
            double3: float,
        ): ...
        def getComponentName(self) -> java.lang.String: ...
        def getComponentType(self) -> java.lang.String: ...
        def getFailureRate(self) -> float: ...
        def getPercentOfTotal(self) -> float: ...
        def getPfdContribution(self) -> float: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

    class VerificationIssue(java.io.Serializable):
        def __init__(
            self,
            issueSeverity: "SILVerificationResult.VerificationIssue.IssueSeverity",
            issueCategory: "SILVerificationResult.VerificationIssue.IssueCategory",
            string: typing.Union[java.lang.String, str],
            string2: typing.Union[java.lang.String, str],
        ): ...
        def getCategory(
            self,
        ) -> "SILVerificationResult.VerificationIssue.IssueCategory": ...
        def getDescription(self) -> java.lang.String: ...
        def getRecommendation(self) -> java.lang.String: ...
        def getSeverity(
            self,
        ) -> "SILVerificationResult.VerificationIssue.IssueSeverity": ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

        class IssueCategory(
            java.lang.Enum["SILVerificationResult.VerificationIssue.IssueCategory"]
        ):
            PFD_EXCEEDED: typing.ClassVar[
                "SILVerificationResult.VerificationIssue.IssueCategory"
            ] = ...
            ARCHITECTURE: typing.ClassVar[
                "SILVerificationResult.VerificationIssue.IssueCategory"
            ] = ...
            DIAGNOSTIC_COVERAGE: typing.ClassVar[
                "SILVerificationResult.VerificationIssue.IssueCategory"
            ] = ...
            PROOF_TEST_INTERVAL: typing.ClassVar[
                "SILVerificationResult.VerificationIssue.IssueCategory"
            ] = ...
            COMMON_CAUSE: typing.ClassVar[
                "SILVerificationResult.VerificationIssue.IssueCategory"
            ] = ...
            SYSTEMATIC: typing.ClassVar[
                "SILVerificationResult.VerificationIssue.IssueCategory"
            ] = ...
            _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
            @typing.overload
            @staticmethod
            def valueOf(
                class_: typing.Type[_valueOf_0__T],
                string: typing.Union[java.lang.String, str],
            ) -> _valueOf_0__T: ...
            @typing.overload
            @staticmethod
            def valueOf(
                string: typing.Union[java.lang.String, str],
            ) -> "SILVerificationResult.VerificationIssue.IssueCategory": ...
            @staticmethod
            def values() -> (
                typing.MutableSequence[
                    "SILVerificationResult.VerificationIssue.IssueCategory"
                ]
            ): ...

        class IssueSeverity(
            java.lang.Enum["SILVerificationResult.VerificationIssue.IssueSeverity"]
        ):
            WARNING: typing.ClassVar[
                "SILVerificationResult.VerificationIssue.IssueSeverity"
            ] = ...
            ERROR: typing.ClassVar[
                "SILVerificationResult.VerificationIssue.IssueSeverity"
            ] = ...
            INFO: typing.ClassVar[
                "SILVerificationResult.VerificationIssue.IssueSeverity"
            ] = ...
            _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
            @typing.overload
            @staticmethod
            def valueOf(
                class_: typing.Type[_valueOf_0__T],
                string: typing.Union[java.lang.String, str],
            ) -> _valueOf_0__T: ...
            @typing.overload
            @staticmethod
            def valueOf(
                string: typing.Union[java.lang.String, str],
            ) -> "SILVerificationResult.VerificationIssue.IssueSeverity": ...
            @staticmethod
            def values() -> (
                typing.MutableSequence[
                    "SILVerificationResult.VerificationIssue.IssueSeverity"
                ]
            ): ...

class SISIntegratedRiskModel(
    jneqsim.process.safety.risk.RiskModel, java.io.Serializable
):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addIPL(
        self,
        independentProtectionLayer: "SISIntegratedRiskModel.IndependentProtectionLayer",
    ) -> None: ...
    def addSIF(
        self, safetyInstrumentedFunction: "SafetyInstrumentedFunction"
    ) -> None: ...
    def calculateResidualRisk(self) -> "SISRiskResult": ...
    def determineRequiredSIL(
        self,
        string: typing.Union[java.lang.String, str],
        consequenceType: "SISIntegratedRiskModel.ConsequenceType",
    ) -> int: ...
    def getIPLs(
        self,
    ) -> java.util.List["SISIntegratedRiskModel.IndependentProtectionLayer"]: ...
    def getSIFs(self) -> java.util.List["SafetyInstrumentedFunction"]: ...
    def getSIFsForEquipment(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.util.List["SafetyInstrumentedFunction"]: ...
    def getSIFsForEvent(
        self, string: typing.Union[java.lang.String, str]
    ) -> java.util.List["SafetyInstrumentedFunction"]: ...
    def getToleranceCriteria(
        self,
    ) -> "SISIntegratedRiskModel.RiskToleranceCriteria": ...
    def performLOPA(
        self, string: typing.Union[java.lang.String, str]
    ) -> LOPAResult: ...
    def setToleranceCriteria(
        self, riskToleranceCriteria: "SISIntegratedRiskModel.RiskToleranceCriteria"
    ) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def verifySILRequirements(
        self,
    ) -> java.util.Map[java.lang.String, SILVerificationResult]: ...

    class ConsequenceType(java.lang.Enum["SISIntegratedRiskModel.ConsequenceType"]):
        FATALITY: typing.ClassVar["SISIntegratedRiskModel.ConsequenceType"] = ...
        INJURY: typing.ClassVar["SISIntegratedRiskModel.ConsequenceType"] = ...
        ENVIRONMENT: typing.ClassVar["SISIntegratedRiskModel.ConsequenceType"] = ...
        ASSET: typing.ClassVar["SISIntegratedRiskModel.ConsequenceType"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "SISIntegratedRiskModel.ConsequenceType": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["SISIntegratedRiskModel.ConsequenceType"]
        ): ...

    class IndependentProtectionLayer(java.io.Serializable):
        def __init__(
            self,
            string: typing.Union[java.lang.String, str],
            double: float,
            iPLType: "SISIntegratedRiskModel.IndependentProtectionLayer.IPLType",
        ): ...
        def addApplicableEvent(
            self, string: typing.Union[java.lang.String, str]
        ) -> None: ...
        def getApplicableEvents(self) -> java.util.List[java.lang.String]: ...
        def getName(self) -> java.lang.String: ...
        def getPfd(self) -> float: ...
        def getRiskReductionFactor(self) -> float: ...
        def getType(
            self,
        ) -> "SISIntegratedRiskModel.IndependentProtectionLayer.IPLType": ...

        class IPLType(
            java.lang.Enum["SISIntegratedRiskModel.IndependentProtectionLayer.IPLType"]
        ):
            BPCS: typing.ClassVar[
                "SISIntegratedRiskModel.IndependentProtectionLayer.IPLType"
            ] = ...
            ALARM: typing.ClassVar[
                "SISIntegratedRiskModel.IndependentProtectionLayer.IPLType"
            ] = ...
            MECHANICAL: typing.ClassVar[
                "SISIntegratedRiskModel.IndependentProtectionLayer.IPLType"
            ] = ...
            PHYSICAL: typing.ClassVar[
                "SISIntegratedRiskModel.IndependentProtectionLayer.IPLType"
            ] = ...
            EMERGENCY_RESPONSE: typing.ClassVar[
                "SISIntegratedRiskModel.IndependentProtectionLayer.IPLType"
            ] = ...
            OTHER: typing.ClassVar[
                "SISIntegratedRiskModel.IndependentProtectionLayer.IPLType"
            ] = ...
            _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
            @typing.overload
            @staticmethod
            def valueOf(
                class_: typing.Type[_valueOf_0__T],
                string: typing.Union[java.lang.String, str],
            ) -> _valueOf_0__T: ...
            @typing.overload
            @staticmethod
            def valueOf(
                string: typing.Union[java.lang.String, str],
            ) -> "SISIntegratedRiskModel.IndependentProtectionLayer.IPLType": ...
            @staticmethod
            def values() -> (
                typing.MutableSequence[
                    "SISIntegratedRiskModel.IndependentProtectionLayer.IPLType"
                ]
            ): ...

    class RiskToleranceCriteria(java.io.Serializable):
        def __init__(self): ...
        def getALARP(self) -> float: ...
        def getTolerableFrequency(
            self, consequenceType: "SISIntegratedRiskModel.ConsequenceType"
        ) -> float: ...
        def setTolerableFrequencyAsset(self, double: float) -> None: ...
        def setTolerableFrequencyFatality(self, double: float) -> None: ...

class SISRiskResult(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addEventResult(
        self,
        string: typing.Union[java.lang.String, str],
        double: float,
        double2: float,
        list: java.util.List["SafetyInstrumentedFunction"],
    ) -> None: ...
    def calculateTotals(self) -> None: ...
    def getEventResults(
        self,
    ) -> java.util.List["SISRiskResult.EventMitigationResult"]: ...
    def getOverallRRF(self) -> float: ...
    def getResidualFrequency(self) -> float: ...
    def getRiskReductionPercent(self) -> float: ...
    def getStudyName(self) -> java.lang.String: ...
    def getTotalMitigatedFrequency(self) -> float: ...
    def getTotalRiskReduction(self) -> float: ...
    def getTotalUnmitigatedFrequency(self) -> float: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def toString(self) -> java.lang.String: ...

    class EventMitigationResult(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def getAppliedSIFs(self) -> java.util.List[java.lang.String]: ...
        def getEventName(self) -> java.lang.String: ...
        def getMitigatedFrequency(self) -> float: ...
        def getRiskReduction(self) -> float: ...
        def getSifContributions(self) -> java.util.Map[java.lang.String, float]: ...
        def getUnmitigatedFrequency(self) -> float: ...

class SafetyInstrumentedFunction(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self, string: typing.Union[java.lang.String, str], int: int, double: float
    ): ...
    def addProtectedEquipment(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    @staticmethod
    def builder() -> "SafetyInstrumentedFunction.Builder": ...
    @staticmethod
    def calculatePfd1oo1(double: float, double2: float) -> float: ...
    @staticmethod
    def calculatePfd1oo2(double: float, double2: float) -> float: ...
    @staticmethod
    def calculatePfd2oo3(double: float, double2: float) -> float: ...
    @staticmethod
    def calculateRequiredPfd(double: float, double2: float) -> float: ...
    def getArchitecture(self) -> java.lang.String: ...
    def getAvailabilityWithSpuriousTrips(
        self, double: float, double2: float
    ) -> float: ...
    def getCategory(self) -> "SafetyInstrumentedFunction.SIFCategory": ...
    def getDescription(self) -> java.lang.String: ...
    def getId(self) -> java.lang.String: ...
    def getInitiatingEvent(self) -> java.lang.String: ...
    @staticmethod
    def getMaxPfdForSil(int: int) -> float: ...
    def getMitigatedFrequency(self, double: float) -> float: ...
    def getMttr(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getNotes(self) -> java.lang.String: ...
    def getPfdAvg(self) -> float: ...
    def getProofTestIntervalYears(self) -> float: ...
    def getProtectedEquipment(self) -> java.util.List[java.lang.String]: ...
    @staticmethod
    def getRequiredSil(double: float) -> int: ...
    def getRiskReductionFactor(self) -> float: ...
    def getSafeState(self) -> java.lang.String: ...
    def getSil(self) -> int: ...
    def getSpuriousTripRate(self) -> float: ...
    def getTestIntervalHours(self) -> float: ...
    def setArchitecture(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setCategory(
        self, sIFCategory: "SafetyInstrumentedFunction.SIFCategory"
    ) -> None: ...
    def setDescription(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setId(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInitiatingEvent(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setMttr(self, double: float) -> None: ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setNotes(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPfdAvg(self, double: float) -> None: ...
    def setProtectedEquipment(
        self, list: java.util.List[typing.Union[java.lang.String, str]]
    ) -> None: ...
    def setSafeState(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSil(self, int: int) -> None: ...
    def setSpuriousTripRate(self, double: float) -> None: ...
    def setTestIntervalHours(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def toString(self) -> java.lang.String: ...

    class Builder:
        def __init__(self): ...
        def addProtectedEquipment(
            self, string: typing.Union[java.lang.String, str]
        ) -> "SafetyInstrumentedFunction.Builder": ...
        def architecture(
            self, string: typing.Union[java.lang.String, str]
        ) -> "SafetyInstrumentedFunction.Builder": ...
        def build(self) -> "SafetyInstrumentedFunction": ...
        def category(
            self, sIFCategory: "SafetyInstrumentedFunction.SIFCategory"
        ) -> "SafetyInstrumentedFunction.Builder": ...
        def description(
            self, string: typing.Union[java.lang.String, str]
        ) -> "SafetyInstrumentedFunction.Builder": ...
        def id(
            self, string: typing.Union[java.lang.String, str]
        ) -> "SafetyInstrumentedFunction.Builder": ...
        def initiatingEvent(
            self, string: typing.Union[java.lang.String, str]
        ) -> "SafetyInstrumentedFunction.Builder": ...
        def mttr(self, double: float) -> "SafetyInstrumentedFunction.Builder": ...
        def name(
            self, string: typing.Union[java.lang.String, str]
        ) -> "SafetyInstrumentedFunction.Builder": ...
        def notes(
            self, string: typing.Union[java.lang.String, str]
        ) -> "SafetyInstrumentedFunction.Builder": ...
        def pfd(self, double: float) -> "SafetyInstrumentedFunction.Builder": ...
        def protectedEquipment(
            self, list: java.util.List[typing.Union[java.lang.String, str]]
        ) -> "SafetyInstrumentedFunction.Builder": ...
        def safeState(
            self, string: typing.Union[java.lang.String, str]
        ) -> "SafetyInstrumentedFunction.Builder": ...
        def sil(self, int: int) -> "SafetyInstrumentedFunction.Builder": ...
        def spuriousTripRate(
            self, double: float
        ) -> "SafetyInstrumentedFunction.Builder": ...
        def testIntervalHours(
            self, double: float
        ) -> "SafetyInstrumentedFunction.Builder": ...

    class SIFCategory(java.lang.Enum["SafetyInstrumentedFunction.SIFCategory"]):
        ESD: typing.ClassVar["SafetyInstrumentedFunction.SIFCategory"] = ...
        HIPPS: typing.ClassVar["SafetyInstrumentedFunction.SIFCategory"] = ...
        FIRE_GAS: typing.ClassVar["SafetyInstrumentedFunction.SIFCategory"] = ...
        BLOWDOWN: typing.ClassVar["SafetyInstrumentedFunction.SIFCategory"] = ...
        PSD: typing.ClassVar["SafetyInstrumentedFunction.SIFCategory"] = ...
        OTHER: typing.ClassVar["SafetyInstrumentedFunction.SIFCategory"] = ...
        def getDescription(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "SafetyInstrumentedFunction.SIFCategory": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["SafetyInstrumentedFunction.SIFCategory"]
        ): ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.risk.sis")``.

    LOPAResult: typing.Type[LOPAResult]
    SILVerificationResult: typing.Type[SILVerificationResult]
    SISIntegratedRiskModel: typing.Type[SISIntegratedRiskModel]
    SISRiskResult: typing.Type[SISRiskResult]
    SafetyInstrumentedFunction: typing.Type[SafetyInstrumentedFunction]
