import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.equipment.subsea
import jneqsim.process.fielddevelopment.tieback
import jneqsim.process.processmodel
import jneqsim.thermo.system
import typing

class SubseaProductionSystem(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def build(self) -> "SubseaProductionSystem": ...
    def getArchitecture(self) -> "SubseaProductionSystem.SubseaArchitecture": ...
    def getArrivalPressureBara(self) -> float: ...
    def getArrivalTemperatureC(self) -> float: ...
    def getFlowlineDiameterInches(self) -> float: ...
    def getFlowlines(
        self,
    ) -> java.util.List[jneqsim.process.equipment.subsea.SimpleFlowLine]: ...
    def getName(self) -> java.lang.String: ...
    def getProcessSystem(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getResult(self) -> "SubseaProductionSystem.SubseaSystemResult": ...
    def getTiebackDistanceKm(self) -> float: ...
    def getTiebackOption(
        self,
    ) -> jneqsim.process.fielddevelopment.tieback.TiebackOption: ...
    def getWaterDepthM(self) -> float: ...
    def getWellCount(self) -> int: ...
    def getWells(
        self,
    ) -> java.util.List[jneqsim.process.equipment.subsea.SubseaWell]: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setArchitecture(
        self, subseaArchitecture: "SubseaProductionSystem.SubseaArchitecture"
    ) -> "SubseaProductionSystem": ...
    def setDiscoveryLocation(
        self, double: float, double2: float
    ) -> "SubseaProductionSystem": ...
    def setFlowlineDiameterInches(self, double: float) -> "SubseaProductionSystem": ...
    def setFlowlineMaterial(
        self, string: typing.Union[java.lang.String, str]
    ) -> "SubseaProductionSystem": ...
    def setFlowlineWallThicknessMm(self, double: float) -> "SubseaProductionSystem": ...
    def setHostFacility(
        self, hostFacility: jneqsim.process.fielddevelopment.tieback.HostFacility
    ) -> "SubseaProductionSystem": ...
    def setManifoldCount(self, int: int) -> "SubseaProductionSystem": ...
    def setRatePerWell(self, double: float) -> "SubseaProductionSystem": ...
    def setReservoirConditions(
        self, double: float, double2: float
    ) -> "SubseaProductionSystem": ...
    def setReservoirFluid(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> "SubseaProductionSystem": ...
    def setSeabedTemperatureC(self, double: float) -> "SubseaProductionSystem": ...
    def setTiebackDistanceKm(self, double: float) -> "SubseaProductionSystem": ...
    def setTubingDiameterInches(self, double: float) -> "SubseaProductionSystem": ...
    def setWaterDepthM(self, double: float) -> "SubseaProductionSystem": ...
    def setWellCount(self, int: int) -> "SubseaProductionSystem": ...
    def setWellDepthM(self, double: float) -> "SubseaProductionSystem": ...
    def setWellheadConditions(
        self, double: float, double2: float
    ) -> "SubseaProductionSystem": ...

    class SubseaArchitecture(
        java.lang.Enum["SubseaProductionSystem.SubseaArchitecture"]
    ):
        DIRECT_TIEBACK: typing.ClassVar["SubseaProductionSystem.SubseaArchitecture"] = (
            ...
        )
        MANIFOLD_CLUSTER: typing.ClassVar[
            "SubseaProductionSystem.SubseaArchitecture"
        ] = ...
        DAISY_CHAIN: typing.ClassVar["SubseaProductionSystem.SubseaArchitecture"] = ...
        TEMPLATE: typing.ClassVar["SubseaProductionSystem.SubseaArchitecture"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "SubseaProductionSystem.SubseaArchitecture": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["SubseaProductionSystem.SubseaArchitecture"]
        ): ...

    class SubseaSystemResult(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def getArrivalPressureBara(self) -> float: ...
        def getArrivalTemperatureC(self) -> float: ...
        def getManifoldCostMusd(self) -> float: ...
        def getPipelineCostMusd(self) -> float: ...
        def getSubseaTreeCostMusd(self) -> float: ...
        def getSummary(self) -> java.lang.String: ...
        def getTotalPressureDropBara(self) -> float: ...
        def getTotalProductionSm3d(self) -> float: ...
        def getTotalSubseaCapexMusd(self) -> float: ...
        def getUmbilicalCostMusd(self) -> float: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.fielddevelopment.subsea")``.

    SubseaProductionSystem: typing.Type[SubseaProductionSystem]
