
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import com.google.gson
import java.io
import java.lang
import java.util
import jneqsim.process.equipment.stream
import jneqsim.process.processmodel
import typing



class CompressionDuty(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, double: float): ...
    def getDischargePressureBara(self) -> float: ...
    def getFeed(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getFinalCoolerTemperatureC(self) -> float: ...
    def getInterstageCoolerTemperatureC(self) -> float: ...
    def getMaxStageRatio(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getPolytropicEfficiency(self) -> float: ...
    def hasAfterCooler(self) -> bool: ...
    def setAfterCooler(self, boolean: bool, double: float) -> 'CompressionDuty': ...
    def setInterstageCoolerTemperatureC(self, double: float) -> 'CompressionDuty': ...
    def setMaxStageRatio(self, double: float) -> 'CompressionDuty': ...
    def setPolytropicEfficiency(self, double: float) -> 'CompressionDuty': ...

class CompressionProposal(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem, int: int, double: float, string: typing.Union[java.lang.String, str], list: java.util.List[typing.Union[java.lang.String, str]]): ...
    def getPerStagePressureRatio(self) -> float: ...
    def getProcessSystem(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getRationale(self) -> java.lang.String: ...
    def getStageNames(self) -> java.util.List[java.lang.String]: ...
    def getStages(self) -> int: ...
    def toJson(self) -> java.lang.String: ...

class FlowsheetProposal(java.io.Serializable):
    def __init__(self, strategy: 'FlowsheetProposal.Strategy', string: typing.Union[java.lang.String, str], processSystem: jneqsim.process.processmodel.ProcessSystem, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], list: java.util.List[typing.Union[java.lang.String, str]], boolean: bool): ...
    def getAlternatives(self) -> java.util.List[java.lang.String]: ...
    def getBottomProductPredicted(self) -> java.util.Map[java.lang.String, float]: ...
    def getProcessSystem(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getRationale(self) -> java.lang.String: ...
    def getStrategy(self) -> 'FlowsheetProposal.Strategy': ...
    def getTopProductPredicted(self) -> java.util.Map[java.lang.String, float]: ...
    def isSpecsMet(self) -> bool: ...
    def toJson(self) -> com.google.gson.JsonObject: ...
    class Strategy(java.lang.Enum['FlowsheetProposal.Strategy']):
        SINGLE_FLASH: typing.ClassVar['FlowsheetProposal.Strategy'] = ...
        TWO_STAGE_FLASH: typing.ClassVar['FlowsheetProposal.Strategy'] = ...
        DISTILLATION: typing.ClassVar['FlowsheetProposal.Strategy'] = ...
        STRIPPER: typing.ClassVar['FlowsheetProposal.Strategy'] = ...
        INFEASIBLE: typing.ClassVar['FlowsheetProposal.Strategy'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FlowsheetProposal.Strategy': ...
        @staticmethod
        def values() -> typing.MutableSequence['FlowsheetProposal.Strategy']: ...

class FlowsheetSynthesisEngine:
    ALPHA_DISTILLATION_THRESHOLD: typing.ClassVar[float] = ...
    MIN_TRAYS: typing.ClassVar[int] = ...
    MAX_TRAYS: typing.ClassVar[int] = ...
    def __init__(self): ...
    @staticmethod
    def ensureRun(streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def proposeAndBuild(self, separationDuty: 'SeparationDuty') -> FlowsheetProposal: ...
    def proposeAndBuildCompression(self, compressionDuty: CompressionDuty) -> CompressionProposal: ...

class SeparationDuty(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], double: float): ...
    def getBottomProductSpecs(self) -> java.util.Map[java.lang.String, float]: ...
    def getFeed(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getName(self) -> java.lang.String: ...
    def getOperatingPressureBara(self) -> float: ...
    def getTopProductSpecs(self) -> java.util.Map[java.lang.String, float]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.synthesis")``.

    CompressionDuty: typing.Type[CompressionDuty]
    CompressionProposal: typing.Type[CompressionProposal]
    FlowsheetProposal: typing.Type[FlowsheetProposal]
    FlowsheetSynthesisEngine: typing.Type[FlowsheetSynthesisEngine]
    SeparationDuty: typing.Type[SeparationDuty]
