
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import neqsim.process
import neqsim.process.controllerdevice
import neqsim.process.equipment.absorber
import neqsim.process.equipment.adsorber
import neqsim.process.equipment.battery
import neqsim.process.equipment.blackoil
import neqsim.process.equipment.compressor
import neqsim.process.equipment.diffpressure
import neqsim.process.equipment.distillation
import neqsim.process.equipment.ejector
import neqsim.process.equipment.electrolyzer
import neqsim.process.equipment.expander
import neqsim.process.equipment.filter
import neqsim.process.equipment.flare
import neqsim.process.equipment.heatexchanger
import neqsim.process.equipment.manifold
import neqsim.process.equipment.membrane
import neqsim.process.equipment.mixer
import neqsim.process.equipment.network
import neqsim.process.equipment.pipeline
import neqsim.process.equipment.powergeneration
import neqsim.process.equipment.pump
import neqsim.process.equipment.reactor
import neqsim.process.equipment.reservoir
import neqsim.process.equipment.separator
import neqsim.process.equipment.splitter
import neqsim.process.equipment.stream
import neqsim.process.equipment.subsea
import neqsim.process.equipment.tank
import neqsim.process.equipment.util
import neqsim.process.equipment.valve
import neqsim.process.mechanicaldesign
import neqsim.process.util.report
import neqsim.thermo.system
import typing



class EquipmentEnum(java.lang.Enum['EquipmentEnum']):
    Stream: typing.ClassVar['EquipmentEnum'] = ...
    ThrottlingValve: typing.ClassVar['EquipmentEnum'] = ...
    Compressor: typing.ClassVar['EquipmentEnum'] = ...
    Pump: typing.ClassVar['EquipmentEnum'] = ...
    Separator: typing.ClassVar['EquipmentEnum'] = ...
    HeatExchanger: typing.ClassVar['EquipmentEnum'] = ...
    Cooler: typing.ClassVar['EquipmentEnum'] = ...
    Heater: typing.ClassVar['EquipmentEnum'] = ...
    Mixer: typing.ClassVar['EquipmentEnum'] = ...
    Splitter: typing.ClassVar['EquipmentEnum'] = ...
    Reactor: typing.ClassVar['EquipmentEnum'] = ...
    Column: typing.ClassVar['EquipmentEnum'] = ...
    ThreePhaseSeparator: typing.ClassVar['EquipmentEnum'] = ...
    Recycle: typing.ClassVar['EquipmentEnum'] = ...
    Ejector: typing.ClassVar['EquipmentEnum'] = ...
    GORfitter: typing.ClassVar['EquipmentEnum'] = ...
    Adjuster: typing.ClassVar['EquipmentEnum'] = ...
    SetPoint: typing.ClassVar['EquipmentEnum'] = ...
    FlowRateAdjuster: typing.ClassVar['EquipmentEnum'] = ...
    Calculator: typing.ClassVar['EquipmentEnum'] = ...
    Expander: typing.ClassVar['EquipmentEnum'] = ...
    SimpleTEGAbsorber: typing.ClassVar['EquipmentEnum'] = ...
    Tank: typing.ClassVar['EquipmentEnum'] = ...
    ComponentSplitter: typing.ClassVar['EquipmentEnum'] = ...
    ReservoirCVDsim: typing.ClassVar['EquipmentEnum'] = ...
    ReservoirDiffLibsim: typing.ClassVar['EquipmentEnum'] = ...
    VirtualStream: typing.ClassVar['EquipmentEnum'] = ...
    ReservoirTPsim: typing.ClassVar['EquipmentEnum'] = ...
    SimpleReservoir: typing.ClassVar['EquipmentEnum'] = ...
    Manifold: typing.ClassVar['EquipmentEnum'] = ...
    Flare: typing.ClassVar['EquipmentEnum'] = ...
    FlareStack: typing.ClassVar['EquipmentEnum'] = ...
    FuelCell: typing.ClassVar['EquipmentEnum'] = ...
    CO2Electrolyzer: typing.ClassVar['EquipmentEnum'] = ...
    Electrolyzer: typing.ClassVar['EquipmentEnum'] = ...
    WindTurbine: typing.ClassVar['EquipmentEnum'] = ...
    BatteryStorage: typing.ClassVar['EquipmentEnum'] = ...
    SolarPanel: typing.ClassVar['EquipmentEnum'] = ...
    def toString(self) -> java.lang.String: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'EquipmentEnum': ...
    @staticmethod
    def values() -> typing.MutableSequence['EquipmentEnum']: ...

class EquipmentFactory:
    @staticmethod
    def createEjector(string: typing.Union[java.lang.String, str], streamInterface: neqsim.process.equipment.stream.StreamInterface, streamInterface2: neqsim.process.equipment.stream.StreamInterface) -> neqsim.process.equipment.ejector.Ejector: ...
    @typing.overload
    @staticmethod
    def createEquipment(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'ProcessEquipmentInterface': ...
    @typing.overload
    @staticmethod
    def createEquipment(string: typing.Union[java.lang.String, str], equipmentEnum: EquipmentEnum) -> 'ProcessEquipmentInterface': ...
    @staticmethod
    def createGORfitter(string: typing.Union[java.lang.String, str], streamInterface: neqsim.process.equipment.stream.StreamInterface) -> neqsim.process.equipment.util.GORfitter: ...
    @staticmethod
    def createReservoirCVDsim(string: typing.Union[java.lang.String, str], systemInterface: neqsim.thermo.system.SystemInterface) -> neqsim.process.equipment.reservoir.ReservoirCVDsim: ...
    @staticmethod
    def createReservoirDiffLibsim(string: typing.Union[java.lang.String, str], systemInterface: neqsim.thermo.system.SystemInterface) -> neqsim.process.equipment.reservoir.ReservoirDiffLibsim: ...
    @staticmethod
    def createReservoirTPsim(string: typing.Union[java.lang.String, str], systemInterface: neqsim.thermo.system.SystemInterface) -> neqsim.process.equipment.reservoir.ReservoirTPsim: ...

class ProcessEquipmentInterface(neqsim.process.SimulationInterface):
    def displayResult(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCapacityDuty(self) -> float: ...
    def getCapacityMax(self) -> float: ...
    def getConditionAnalysisMessage(self) -> java.lang.String: ...
    def getController(self) -> neqsim.process.controllerdevice.ControllerDeviceInterface: ...
    def getEntropyProduction(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getExergyChange(self, string: typing.Union[java.lang.String, str], double: float) -> float: ...
    @typing.overload
    def getExergyChange(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getFluid(self) -> neqsim.thermo.system.SystemInterface: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMechanicalDesign(self) -> neqsim.process.mechanicaldesign.MechanicalDesign: ...
    @typing.overload
    def getPressure(self) -> float: ...
    @typing.overload
    def getPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getReport_json(self) -> java.lang.String: ...
    def getRestCapacity(self) -> float: ...
    def getResultTable(self) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def getSpecification(self) -> java.lang.String: ...
    @typing.overload
    def getTemperature(self) -> float: ...
    @typing.overload
    def getTemperature(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getThermoSystem(self) -> neqsim.thermo.system.SystemInterface: ...
    def hashCode(self) -> int: ...
    def initMechanicalDesign(self) -> None: ...
    def needRecalculation(self) -> bool: ...
    def reportResults(self) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def runConditionAnalysis(self, processEquipmentInterface: 'ProcessEquipmentInterface') -> None: ...
    def setController(self, controllerDeviceInterface: neqsim.process.controllerdevice.ControllerDeviceInterface) -> None: ...
    def setPressure(self, double: float) -> None: ...
    def setRegulatorOutSignal(self, double: float) -> None: ...
    def setSpecification(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTemperature(self, double: float) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(self, reportConfig: neqsim.process.util.report.ReportConfig) -> java.lang.String: ...

class TwoPortInterface:
    def getInStream(self) -> neqsim.process.equipment.stream.StreamInterface: ...
    def getInletPressure(self) -> float: ...
    def getInletStream(self) -> neqsim.process.equipment.stream.StreamInterface: ...
    def getInletTemperature(self) -> float: ...
    def getOutStream(self) -> neqsim.process.equipment.stream.StreamInterface: ...
    def getOutletPressure(self) -> float: ...
    def getOutletStream(self) -> neqsim.process.equipment.stream.StreamInterface: ...
    def getOutletTemperature(self) -> float: ...
    def setInletPressure(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: neqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setInletTemperature(self, double: float) -> None: ...
    def setOutletPressure(self, double: float) -> None: ...
    def setOutletStream(self, streamInterface: neqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setOutletTemperature(self, double: float) -> None: ...

class ProcessEquipmentBaseClass(neqsim.process.SimulationBaseClass, ProcessEquipmentInterface):
    hasController: bool = ...
    report: typing.MutableSequence[typing.MutableSequence[java.lang.String]] = ...
    properties: java.util.HashMap = ...
    energyStream: neqsim.process.equipment.stream.EnergyStream = ...
    conditionAnalysisMessage: java.lang.String = ...
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def copy(self) -> ProcessEquipmentInterface: ...
    def displayResult(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getConditionAnalysisMessage(self) -> java.lang.String: ...
    def getController(self) -> neqsim.process.controllerdevice.ControllerDeviceInterface: ...
    def getEnergyStream(self) -> neqsim.process.equipment.stream.EnergyStream: ...
    def getEntropyProduction(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getExergyChange(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getExergyChange(self, string: typing.Union[java.lang.String, str], double: float) -> float: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMechanicalDesign(self) -> neqsim.process.mechanicaldesign.MechanicalDesign: ...
    def getMinimumFlow(self) -> float: ...
    @typing.overload
    def getPressure(self) -> float: ...
    @typing.overload
    def getPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getProperty(self, string: typing.Union[java.lang.String, str]) -> typing.Any: ...
    def getReport_json(self) -> java.lang.String: ...
    def getResultTable(self) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def getSpecification(self) -> java.lang.String: ...
    @typing.overload
    def getTemperature(self) -> float: ...
    @typing.overload
    def getTemperature(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getThermoSystem(self) -> neqsim.thermo.system.SystemInterface: ...
    def hashCode(self) -> int: ...
    def initMechanicalDesign(self) -> None: ...
    @typing.overload
    def isActive(self) -> bool: ...
    @typing.overload
    def isActive(self, boolean: bool) -> None: ...
    def isSetEnergyStream(self) -> bool: ...
    def reportResults(self) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def runConditionAnalysis(self, processEquipmentInterface: ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def run_step(self) -> None: ...
    @typing.overload
    def run_step(self, uUID: java.util.UUID) -> None: ...
    def setController(self, controllerDeviceInterface: neqsim.process.controllerdevice.ControllerDeviceInterface) -> None: ...
    @typing.overload
    def setEnergyStream(self, boolean: bool) -> None: ...
    @typing.overload
    def setEnergyStream(self, energyStream: neqsim.process.equipment.stream.EnergyStream) -> None: ...
    def setFlowValveController(self, controllerDeviceInterface: neqsim.process.controllerdevice.ControllerDeviceInterface) -> None: ...
    def setMinimumFlow(self, double: float) -> None: ...
    def setPressure(self, double: float) -> None: ...
    def setRegulatorOutSignal(self, double: float) -> None: ...
    def setSpecification(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTemperature(self, double: float) -> None: ...
    def solved(self) -> bool: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(self, reportConfig: neqsim.process.util.report.ReportConfig) -> java.lang.String: ...

class TwoPortEquipment(ProcessEquipmentBaseClass, TwoPortInterface):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: neqsim.process.equipment.stream.StreamInterface): ...
    def getInletPressure(self) -> float: ...
    def getInletStream(self) -> neqsim.process.equipment.stream.StreamInterface: ...
    def getInletTemperature(self) -> float: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getOutletPressure(self) -> float: ...
    def getOutletStream(self) -> neqsim.process.equipment.stream.StreamInterface: ...
    def getOutletTemperature(self) -> float: ...
    def setInletPressure(self, double: float) -> None: ...
    def setInletStream(self, streamInterface: neqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setInletTemperature(self, double: float) -> None: ...
    def setOutletPressure(self, double: float) -> None: ...
    def setOutletStream(self, streamInterface: neqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setOutletTemperature(self, double: float) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(self, reportConfig: neqsim.process.util.report.ReportConfig) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("neqsim.process.equipment")``.

    EquipmentEnum: typing.Type[EquipmentEnum]
    EquipmentFactory: typing.Type[EquipmentFactory]
    ProcessEquipmentBaseClass: typing.Type[ProcessEquipmentBaseClass]
    ProcessEquipmentInterface: typing.Type[ProcessEquipmentInterface]
    TwoPortEquipment: typing.Type[TwoPortEquipment]
    TwoPortInterface: typing.Type[TwoPortInterface]
    absorber: neqsim.process.equipment.absorber.__module_protocol__
    adsorber: neqsim.process.equipment.adsorber.__module_protocol__
    battery: neqsim.process.equipment.battery.__module_protocol__
    blackoil: neqsim.process.equipment.blackoil.__module_protocol__
    compressor: neqsim.process.equipment.compressor.__module_protocol__
    diffpressure: neqsim.process.equipment.diffpressure.__module_protocol__
    distillation: neqsim.process.equipment.distillation.__module_protocol__
    ejector: neqsim.process.equipment.ejector.__module_protocol__
    electrolyzer: neqsim.process.equipment.electrolyzer.__module_protocol__
    expander: neqsim.process.equipment.expander.__module_protocol__
    filter: neqsim.process.equipment.filter.__module_protocol__
    flare: neqsim.process.equipment.flare.__module_protocol__
    heatexchanger: neqsim.process.equipment.heatexchanger.__module_protocol__
    manifold: neqsim.process.equipment.manifold.__module_protocol__
    membrane: neqsim.process.equipment.membrane.__module_protocol__
    mixer: neqsim.process.equipment.mixer.__module_protocol__
    network: neqsim.process.equipment.network.__module_protocol__
    pipeline: neqsim.process.equipment.pipeline.__module_protocol__
    powergeneration: neqsim.process.equipment.powergeneration.__module_protocol__
    pump: neqsim.process.equipment.pump.__module_protocol__
    reactor: neqsim.process.equipment.reactor.__module_protocol__
    reservoir: neqsim.process.equipment.reservoir.__module_protocol__
    separator: neqsim.process.equipment.separator.__module_protocol__
    splitter: neqsim.process.equipment.splitter.__module_protocol__
    stream: neqsim.process.equipment.stream.__module_protocol__
    subsea: neqsim.process.equipment.subsea.__module_protocol__
    tank: neqsim.process.equipment.tank.__module_protocol__
    util: neqsim.process.equipment.util.__module_protocol__
    valve: neqsim.process.equipment.valve.__module_protocol__
