import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jneqsim.process.equipment.separator
import jneqsim.process.equipment.stream
import jneqsim.process.processmodel
import jneqsim.thermo.system
import jneqsim.util.validation
import typing

_ModuleContract__T = typing.TypeVar("_ModuleContract__T")  # <T>

class ModuleContract(typing.Generic[_ModuleContract__T]):
    def checkPostconditions(
        self, t: _ModuleContract__T
    ) -> jneqsim.util.validation.ValidationResult: ...
    def checkPreconditions(
        self, t: _ModuleContract__T
    ) -> jneqsim.util.validation.ValidationResult: ...
    def getContractName(self) -> java.lang.String: ...
    def getProvidesDescription(self) -> java.lang.String: ...
    def getRequirementsDescription(self) -> java.lang.String: ...

class ProcessSystemContract(ModuleContract[jneqsim.process.processmodel.ProcessSystem]):
    def checkPostconditions(
        self, processSystem: jneqsim.process.processmodel.ProcessSystem
    ) -> jneqsim.util.validation.ValidationResult: ...
    def checkPreconditions(
        self, processSystem: jneqsim.process.processmodel.ProcessSystem
    ) -> jneqsim.util.validation.ValidationResult: ...
    def getContractName(self) -> java.lang.String: ...
    @staticmethod
    def getInstance() -> "ProcessSystemContract": ...
    def getProvidesDescription(self) -> java.lang.String: ...
    def getRequirementsDescription(self) -> java.lang.String: ...
    def validateConnectivity(
        self, processSystem: jneqsim.process.processmodel.ProcessSystem
    ) -> jneqsim.util.validation.ValidationResult: ...

class SeparatorContract(ModuleContract[jneqsim.process.equipment.separator.Separator]):
    def checkPostconditions(
        self, separator: jneqsim.process.equipment.separator.Separator
    ) -> jneqsim.util.validation.ValidationResult: ...
    def checkPreconditions(
        self, separator: jneqsim.process.equipment.separator.Separator
    ) -> jneqsim.util.validation.ValidationResult: ...
    def getContractName(self) -> java.lang.String: ...
    @staticmethod
    def getInstance() -> "SeparatorContract": ...
    def getProvidesDescription(self) -> java.lang.String: ...
    def getRequirementsDescription(self) -> java.lang.String: ...

class StreamContract(ModuleContract[jneqsim.process.equipment.stream.StreamInterface]):
    def checkPostconditions(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> jneqsim.util.validation.ValidationResult: ...
    def checkPreconditions(
        self, streamInterface: jneqsim.process.equipment.stream.StreamInterface
    ) -> jneqsim.util.validation.ValidationResult: ...
    def getContractName(self) -> java.lang.String: ...
    @staticmethod
    def getInstance() -> "StreamContract": ...
    def getProvidesDescription(self) -> java.lang.String: ...
    def getRequirementsDescription(self) -> java.lang.String: ...

class ThermodynamicSystemContract(
    ModuleContract[jneqsim.thermo.system.SystemInterface]
):
    def checkPostconditions(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> jneqsim.util.validation.ValidationResult: ...
    def checkPreconditions(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> jneqsim.util.validation.ValidationResult: ...
    def getContractName(self) -> java.lang.String: ...
    @staticmethod
    def getInstance() -> "ThermodynamicSystemContract": ...
    def getProvidesDescription(self) -> java.lang.String: ...
    def getRequirementsDescription(self) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.util.validation.contracts")``.

    ModuleContract: typing.Type[ModuleContract]
    ProcessSystemContract: typing.Type[ProcessSystemContract]
    SeparatorContract: typing.Type[SeparatorContract]
    StreamContract: typing.Type[StreamContract]
    ThermodynamicSystemContract: typing.Type[ThermodynamicSystemContract]
