
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import neqsim.process.equipment.flare.dto
import typing



class CapacityAlertDTO(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
    def getDisposalUnitName(self) -> java.lang.String: ...
    def getLoadCaseName(self) -> java.lang.String: ...
    def getMessage(self) -> java.lang.String: ...

class DisposalLoadCaseResultDTO(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], neqsim.process.equipment.flare.dto.FlarePerformanceDTO], typing.Mapping[typing.Union[java.lang.String, str], neqsim.process.equipment.flare.dto.FlarePerformanceDTO]], double: float, double2: float, list: java.util.List[CapacityAlertDTO]): ...
    def getAlerts(self) -> java.util.List[CapacityAlertDTO]: ...
    def getLoadCaseName(self) -> java.lang.String: ...
    def getMaxRadiationDistanceM(self) -> float: ...
    def getPerformanceByUnit(self) -> java.util.Map[java.lang.String, neqsim.process.equipment.flare.dto.FlarePerformanceDTO]: ...
    def getTotalHeatDutyMW(self) -> float: ...

class DisposalNetworkSummaryDTO(java.io.Serializable):
    def __init__(self, list: java.util.List[DisposalLoadCaseResultDTO], double: float, double2: float, list2: java.util.List[CapacityAlertDTO]): ...
    def getAlerts(self) -> java.util.List[CapacityAlertDTO]: ...
    def getLoadCaseResults(self) -> java.util.List[DisposalLoadCaseResultDTO]: ...
    def getMaxHeatDutyMW(self) -> float: ...
    def getMaxRadiationDistanceM(self) -> float: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("neqsim.process.safety.dto")``.

    CapacityAlertDTO: typing.Type[CapacityAlertDTO]
    DisposalLoadCaseResultDTO: typing.Type[DisposalLoadCaseResultDTO]
    DisposalNetworkSummaryDTO: typing.Type[DisposalNetworkSummaryDTO]
