
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.fluidmechanics.flowsolver
import jneqsim.process.equipment
import jneqsim.process.equipment.compressor
import jneqsim.process.equipment.mixer
import jneqsim.process.equipment.pipeline
import jneqsim.process.equipment.reservoir
import jneqsim.process.equipment.stream
import jneqsim.process.equipment.valve
import jneqsim.process.processmodel
import jneqsim.process.util.report
import jneqsim.thermo.system
import typing



class LoopDetector(java.io.Serializable):
    def __init__(self): ...
    def addEdge(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> None: ...
    def clear(self) -> None: ...
    def findLoops(self) -> java.util.List['NetworkLoop']: ...
    def getEdgeCount(self) -> int: ...
    def getLoopCount(self) -> int: ...
    def getLoops(self) -> java.util.List['NetworkLoop']: ...
    def getNodeCount(self) -> int: ...
    def hasLoops(self) -> bool: ...

class NetworkLinearSolver:
    def __init__(self): ...
    @staticmethod
    def estimateSparsity(int: int, int2: int) -> typing.MutableSequence[float]: ...
    @staticmethod
    def solve(doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], int: int) -> typing.MutableSequence[float]: ...
    @staticmethod
    def solveDense(doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], int: int) -> typing.MutableSequence[float]: ...
    @staticmethod
    def solveGaussian(doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], int: int) -> typing.MutableSequence[float]: ...
    @staticmethod
    def solveSparse(doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], int: int) -> typing.MutableSequence[float]: ...

class NetworkLoop(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addMember(self, string: typing.Union[java.lang.String, str], int: int) -> None: ...
    def getLastFlowCorrection(self) -> float: ...
    def getLastHeadLossImbalance(self) -> float: ...
    def getLoopId(self) -> java.lang.String: ...
    def getMembers(self) -> java.util.List['NetworkLoop.LoopMember']: ...
    def getTolerance(self) -> float: ...
    def isBalanced(self, double: float) -> bool: ...
    def setLastFlowCorrection(self, double: float) -> None: ...
    def setLastHeadLossImbalance(self, double: float) -> None: ...
    def setTolerance(self, double: float) -> None: ...
    def size(self) -> int: ...
    def toString(self) -> java.lang.String: ...
    class LoopMember(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], int: int): ...
        def getDirection(self) -> int: ...
        def getPipeName(self) -> java.lang.String: ...

class NetworkOptimizer:
    def __init__(self, loopedPipeNetwork: 'LoopedPipeNetwork'): ...
    def getAlgorithm(self) -> 'NetworkOptimizer.Algorithm': ...
    def getConstraintPenalty(self) -> float: ...
    def getLastResult(self) -> 'NetworkOptimizer.OptimizationResult': ...
    def getMaxEvaluations(self) -> int: ...
    def getObjectiveType(self) -> 'NetworkOptimizer.ObjectiveType': ...
    def getParetoPoints(self) -> int: ...
    def optimize(self) -> 'NetworkOptimizer.OptimizationResult': ...
    def optimizeMultiObjective(self) -> java.util.List['NetworkOptimizer.OptimizationResult']: ...
    def setAlgorithm(self, algorithm: 'NetworkOptimizer.Algorithm') -> None: ...
    def setChokeBounds(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def setConstraintPenalty(self, double: float) -> None: ...
    def setMaxEvaluations(self, int: int) -> None: ...
    def setObjectiveType(self, objectiveType: 'NetworkOptimizer.ObjectiveType') -> None: ...
    def setParetoPoints(self, int: int) -> None: ...
    class Algorithm(java.lang.Enum['NetworkOptimizer.Algorithm']):
        BOBYQA: typing.ClassVar['NetworkOptimizer.Algorithm'] = ...
        CMAES: typing.ClassVar['NetworkOptimizer.Algorithm'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'NetworkOptimizer.Algorithm': ...
        @staticmethod
        def values() -> typing.MutableSequence['NetworkOptimizer.Algorithm']: ...
    class ObjectiveType(java.lang.Enum['NetworkOptimizer.ObjectiveType']):
        MAX_PRODUCTION: typing.ClassVar['NetworkOptimizer.ObjectiveType'] = ...
        MAX_REVENUE: typing.ClassVar['NetworkOptimizer.ObjectiveType'] = ...
        MIN_COMPRESSOR_POWER: typing.ClassVar['NetworkOptimizer.ObjectiveType'] = ...
        MAX_SPECIFIC_PRODUCTION: typing.ClassVar['NetworkOptimizer.ObjectiveType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'NetworkOptimizer.ObjectiveType': ...
        @staticmethod
        def values() -> typing.MutableSequence['NetworkOptimizer.ObjectiveType']: ...
    class OptimizationResult:
        converged: bool = ...
        objectiveValue: float = ...
        totalProductionKgHr: float = ...
        totalCompressorPowerKW: float = ...
        chokeNames: java.util.List = ...
        chokeOpenings: typing.MutableSequence[float] = ...
        algorithm: java.lang.String = ...
        objectiveTypeName: java.lang.String = ...
        elapsedMs: int = ...
        functionEvaluations: int = ...
        paretoWeight: float = ...
        message: java.lang.String = ...
        wellResults: java.util.Map = ...
        def __init__(self): ...
        def getSummary(self) -> java.lang.String: ...

class NetworkValidationBenchmarks:
    def __init__(self): ...
    @staticmethod
    def runAllBenchmarks() -> java.util.List['NetworkValidationBenchmarks.BenchmarkResult']: ...
    @staticmethod
    def runParallelPipeBenchmark() -> 'NetworkValidationBenchmarks.BenchmarkResult': ...
    @staticmethod
    def runPressureMonotonicity() -> 'NetworkValidationBenchmarks.BenchmarkResult': ...
    @staticmethod
    def runSinglePipeBenchmark() -> 'NetworkValidationBenchmarks.BenchmarkResult': ...
    @staticmethod
    def runSolverCrossVerification() -> 'NetworkValidationBenchmarks.BenchmarkResult': ...
    @staticmethod
    def runSparseVsDenseBenchmark() -> 'NetworkValidationBenchmarks.BenchmarkResult': ...
    @staticmethod
    def runTriangleMassBalance() -> 'NetworkValidationBenchmarks.BenchmarkResult': ...
    class BenchmarkResult:
        name: java.lang.String = ...
        metrics: java.util.List = ...
        converged: bool = ...
        solverIterations: int = ...
        allPassed: bool = ...
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def addMetric(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float) -> None: ...
        def evaluate(self) -> None: ...
        def getSummary(self) -> java.lang.String: ...
    class MetricResult:
        name: java.lang.String = ...
        computed: float = ...
        expected: float = ...
        tolerance: float = ...
        passed: bool = ...
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float): ...

class PipeFlowNetwork(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addInletPipeline(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, string2: typing.Union[java.lang.String, str], double: float, double2: float, int: int) -> 'PipeFlowNetwork.PipelineSegment': ...
    def connectManifolds(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, int: int) -> 'PipeFlowNetwork.PipelineSegment': ...
    def createManifold(self, string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    def getCompositionProfile(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> typing.MutableSequence[float]: ...
    def getManifolds(self) -> java.util.Map[java.lang.String, 'PipeFlowNetwork.ManifoldNode']: ...
    def getOutletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getPipelines(self) -> java.util.List['PipeFlowNetwork.PipelineSegment']: ...
    def getPressureProfile(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> typing.MutableSequence[float]: ...
    def getSimulationTime(self) -> float: ...
    def getTemperatureProfile(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> typing.MutableSequence[float]: ...
    def getTerminalManifold(self) -> 'PipeFlowNetwork.ManifoldNode': ...
    def getTotalPressureDrop(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getVelocityProfile(self, string: typing.Union[java.lang.String, str]) -> typing.MutableSequence[float]: ...
    def resetSimulationTime(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setAdvectionScheme(self, advectionScheme: jneqsim.fluidmechanics.flowsolver.AdvectionScheme) -> None: ...
    def setCompositionalTracking(self, boolean: bool) -> None: ...
    def setDefaultHeatTransferCoefficients(self, double: float, double2: float) -> None: ...
    def setDefaultOuterTemperature(self, double: float) -> None: ...
    def setDefaultWallRoughness(self, double: float) -> None: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    class ManifoldNode:
        def getInboundPipelines(self) -> java.util.List['PipeFlowNetwork.PipelineSegment']: ...
        def getMixer(self) -> jneqsim.process.equipment.mixer.Mixer: ...
        def getName(self) -> java.lang.String: ...
        def getOutboundPipeline(self) -> 'PipeFlowNetwork.PipelineSegment': ...
    class PipelineSegment:
        def getFromManifold(self) -> java.lang.String: ...
        def getName(self) -> java.lang.String: ...
        def getPipeline(self) -> jneqsim.process.equipment.pipeline.OnePhasePipeLine: ...
        def getToManifold(self) -> java.lang.String: ...
        def isInletPipeline(self) -> bool: ...

class WellFlowlineNetwork(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def addBranch(self, string: typing.Union[java.lang.String, str], wellFlow: jneqsim.process.equipment.reservoir.WellFlow, pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills) -> 'WellFlowlineNetwork.Branch': ...
    @typing.overload
    def addBranch(self, string: typing.Union[java.lang.String, str], wellFlow: jneqsim.process.equipment.reservoir.WellFlow, pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills, manifoldNode: 'WellFlowlineNetwork.ManifoldNode') -> 'WellFlowlineNetwork.Branch': ...
    @typing.overload
    def addBranch(self, string: typing.Union[java.lang.String, str], wellFlow: jneqsim.process.equipment.reservoir.WellFlow, pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills, throttlingValve: jneqsim.process.equipment.valve.ThrottlingValve, manifoldNode: 'WellFlowlineNetwork.ManifoldNode') -> 'WellFlowlineNetwork.Branch': ...
    @typing.overload
    def addBranch(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> 'WellFlowlineNetwork.Branch': ...
    @typing.overload
    def addBranch(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, manifoldNode: 'WellFlowlineNetwork.ManifoldNode') -> 'WellFlowlineNetwork.Branch': ...
    def addManifold(self, string: typing.Union[java.lang.String, str], pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills) -> 'WellFlowlineNetwork.ManifoldNode': ...
    def connectManifolds(self, manifoldNode: 'WellFlowlineNetwork.ManifoldNode', manifoldNode2: 'WellFlowlineNetwork.ManifoldNode', pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills) -> None: ...
    def createManifold(self, string: typing.Union[java.lang.String, str]) -> 'WellFlowlineNetwork.ManifoldNode': ...
    def getArrivalMixer(self) -> jneqsim.process.equipment.mixer.Mixer: ...
    def getArrivalStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getBranches(self) -> java.util.List['WellFlowlineNetwork.Branch']: ...
    def getManifolds(self) -> java.util.List['WellFlowlineNetwork.ManifoldNode']: ...
    def getTerminalManifoldPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setFacilityPipeline(self, pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills) -> None: ...
    def setForceFlowFromPressureSolve(self, boolean: bool) -> None: ...
    def setIterationTolerance(self, double: float) -> None: ...
    def setMaxIterations(self, int: int) -> None: ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPropagateArrivalPressureToWells(self, boolean: bool) -> None: ...
    def setTargetEndpointPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    class Branch:
        def getChoke(self) -> jneqsim.process.equipment.valve.ThrottlingValve: ...
        def getName(self) -> java.lang.String: ...
        def getPipeline(self) -> jneqsim.process.equipment.pipeline.PipeBeggsAndBrills: ...
        def getWell(self) -> jneqsim.process.equipment.reservoir.WellFlow: ...
        def setChoke(self, throttlingValve: jneqsim.process.equipment.valve.ThrottlingValve) -> None: ...
    class ManifoldNode:
        def getBranches(self) -> java.util.List['WellFlowlineNetwork.Branch']: ...
        def getMixer(self) -> jneqsim.process.equipment.mixer.Mixer: ...
        def getName(self) -> java.lang.String: ...

class LoopedPipeNetwork(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def addChoke(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float) -> 'LoopedPipeNetwork.NetworkPipe': ...
    def addCompressor(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float) -> 'LoopedPipeNetwork.NetworkPipe': ...
    def addCompressorWithChart(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], compressor: jneqsim.process.equipment.compressor.Compressor) -> 'LoopedPipeNetwork.NetworkPipe': ...
    @typing.overload
    def addFixedPressureSinkNode(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    @typing.overload
    def addFixedPressureSinkNode(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    @typing.overload
    def addJunctionNode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def addJunctionNode(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def addMultiphasePipe(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float) -> 'LoopedPipeNetwork.NetworkPipe': ...
    @typing.overload
    def addPipe(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float) -> 'LoopedPipeNetwork.NetworkPipe': ...
    @typing.overload
    def addPipe(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, double3: float) -> 'LoopedPipeNetwork.NetworkPipe': ...
    def addRegulator(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float) -> 'LoopedPipeNetwork.NetworkPipe': ...
    @typing.overload
    def addSinkNode(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    @typing.overload
    def addSinkNode(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    @typing.overload
    def addSourceNode(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    @typing.overload
    def addSourceNode(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float) -> None: ...
    def addTubing(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, double3: float) -> 'LoopedPipeNetwork.NetworkPipe': ...
    def addWaterInjection(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float) -> 'LoopedPipeNetwork.NetworkPipe': ...
    def addWellIPR(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, boolean: bool) -> 'LoopedPipeNetwork.NetworkPipe': ...
    def addWellIPRFetkovich(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float) -> 'LoopedPipeNetwork.NetworkPipe': ...
    def addWellIPRVogel(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float) -> 'LoopedPipeNetwork.NetworkPipe': ...
    @typing.overload
    def attachReservoir(self, string: typing.Union[java.lang.String, str], simpleReservoir: jneqsim.process.equipment.reservoir.SimpleReservoir, string2: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def attachReservoir(self, string: typing.Union[java.lang.String, str], simpleReservoir: jneqsim.process.equipment.reservoir.SimpleReservoir, string2: typing.Union[java.lang.String, str], int: int) -> None: ...
    def calculateCorrosion(self) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def calculateEmissions(self) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def calculateFuelGasConsumption(self) -> java.util.Map[java.lang.String, float]: ...
    def calculateGasQuality(self) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def calculateOilQuality(self) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def calculateSandTransport(self) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def calculateWaterBalance(self) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def checkConstraints(self) -> java.util.List[java.lang.String]: ...
    def checkErosionalVelocity(self) -> java.util.List[java.lang.String]: ...
    def checkGasQualityLimits(self, double: float, double2: float) -> java.util.List[java.lang.String]: ...
    def checkOilQualityLimits(self, double: float, double2: float) -> java.util.List[java.lang.String]: ...
    def createOptimizer(self) -> NetworkOptimizer: ...
    def exportCoupledVFPTables(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def exportVFPTables(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def fullFieldForecast(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]]], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def generateCoupledVFPTables(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> java.util.Map[java.lang.String, typing.MutableSequence[typing.MutableSequence[float]]]: ...
    def generateNetworkBackpressureCurve(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def getAnnualCO2EmissionsTonnes(self) -> float: ...
    def getAttachedReservoir(self, string: typing.Union[java.lang.String, str]) -> jneqsim.process.equipment.reservoir.SimpleReservoir: ...
    def getCO2EmissionFactor(self) -> float: ...
    def getConstraintViolations(self) -> java.util.List[java.lang.String]: ...
    def getCorrosionViolations(self) -> java.util.List[java.lang.String]: ...
    def getEmissionsIntensity(self) -> float: ...
    def getErosionalVelocityViolations(self) -> java.util.List[java.lang.String]: ...
    def getFluidTemplate(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getFuelGasHeatRate(self) -> float: ...
    def getFuelGasPercentage(self) -> float: ...
    def getInletStreams(self) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getIterationCount(self) -> int: ...
    def getLoops(self) -> java.util.List[NetworkLoop]: ...
    def getMassBalanceError(self) -> float: ...
    def getMaxCompressorPowerMW(self) -> float: ...
    def getMaxIterations(self) -> int: ...
    def getMaxResidual(self) -> float: ...
    def getMaxSeparatorUtilization(self) -> float: ...
    def getNetworkReport(self) -> java.lang.String: ...
    def getNode(self, string: typing.Union[java.lang.String, str]) -> 'LoopedPipeNetwork.NetworkNode': ...
    def getNodeFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getNodeFluid(self, string: typing.Union[java.lang.String, str]) -> jneqsim.thermo.system.SystemInterface: ...
    def getNodeGasQuality(self, string: typing.Union[java.lang.String, str]) -> typing.MutableSequence[float]: ...
    def getNodeOilQuality(self, string: typing.Union[java.lang.String, str]) -> typing.MutableSequence[float]: ...
    def getNodePressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getNumberOfLoops(self) -> int: ...
    @typing.overload
    def getOutletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    @typing.overload
    def getOutletStream(self, string: typing.Union[java.lang.String, str]) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOutletStreams(self) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getPipe(self, string: typing.Union[java.lang.String, str]) -> 'LoopedPipeNetwork.NetworkPipe': ...
    def getPipeFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getPipeFlowRegime(self, string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    def getPipeFrictionFactor(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getPipeHeadLoss(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getPipeModelType(self) -> 'LoopedPipeNetwork.PipeModelType': ...
    def getPipeNames(self) -> java.util.List[java.lang.String]: ...
    def getPipeReynoldsNumber(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getPipeVelocity(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getRelaxationFactor(self) -> float: ...
    def getSandViolations(self) -> java.util.List[java.lang.String]: ...
    def getSolutionSummary(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getSolverType(self) -> 'LoopedPipeNetwork.SolverType': ...
    def getSourceNodeStream(self, string: typing.Union[java.lang.String, str]) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getTolerance(self) -> float: ...
    def getTopsideModel(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getTotalCO2Emissions(self) -> float: ...
    def getTotalESPPower(self) -> float: ...
    def getTotalFuelGasRate(self) -> float: ...
    def getTotalGasLiftRate(self) -> float: ...
    def getTotalSinkFlow(self) -> float: ...
    def getTotalWaterInjection(self) -> float: ...
    def getTotalWaterProduction(self) -> float: ...
    def getWellAllocationResults(self) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def hasAttachedReservoirs(self) -> bool: ...
    def isConverged(self) -> bool: ...
    def isTopsideFeasible(self) -> bool: ...
    def loadFluidFromE300(self, string: typing.Union[java.lang.String, str]) -> jneqsim.thermo.system.SystemInterface: ...
    def nodalAnalysis(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], int: int) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def optimizeChokeOpenings(self, int: int, double: float) -> float: ...
    def optimizeFullField(self, int: int, double: float) -> java.util.Map[java.lang.String, typing.Any]: ...
    def optimizeMultiObjective(self, int: int) -> java.util.List[NetworkOptimizer.OptimizationResult]: ...
    def optimizeProduction(self, int: int, double: float) -> float: ...
    def optimizeProductionNLP(self) -> NetworkOptimizer.OptimizationResult: ...
    def productionForecast(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    @typing.overload
    def productionForecastCoupled(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    @typing.overload
    def productionForecastCoupled(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], int: int, double2: float) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    @typing.overload
    def productionForecastWithOptimization(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], int: int, double3: float) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    @typing.overload
    def productionForecastWithOptimization(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[typing.List[float], jpype.JArray]]], doubleArray: typing.Union[typing.List[float], jpype.JArray], int: int, double2: float) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def runCoupled(self) -> java.util.Map[java.lang.String, float]: ...
    def runTransientCoupled(self, double: float, int: int, double2: float) -> java.util.Map[java.lang.String, typing.Any]: ...
    @staticmethod
    def runValidationBenchmarks() -> java.util.List[NetworkValidationBenchmarks.BenchmarkResult]: ...
    def sensitivityAnalysis(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> java.util.Map[java.lang.String, typing.MutableSequence[float]]: ...
    def setCO2EmissionFactor(self, double: float) -> None: ...
    def setCorrosionModel(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> None: ...
    def setCorrosiveGas(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def setCouplingToleranceBar(self, double: float) -> None: ...
    def setESP(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def setElementFlowLimits(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def setFeedStream(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setFluidTemplate(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    def setFuelGasHeatRate(self, double: float) -> None: ...
    def setGasLift(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setGasPrice(self, double: float) -> None: ...
    def setJetPump(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def setMaxAllowableErosionRate(self, double: float) -> None: ...
    def setMaxAllowableSandRate(self, double: float) -> None: ...
    def setMaxCompressorPowerMW(self, double: float) -> None: ...
    def setMaxCouplingIterations(self, int: int) -> None: ...
    def setMaxIterations(self, int: int) -> None: ...
    def setMaxSeparatorUtilization(self, double: float) -> None: ...
    def setMethaneSlipFactor(self, double: float) -> None: ...
    def setMinAllowableWallLife(self, double: float) -> None: ...
    def setNodeFluid(self, string: typing.Union[java.lang.String, str], systemInterface: jneqsim.thermo.system.SystemInterface) -> None: ...
    def setNodePressure(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setNodePressureLimits(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def setOilPrice(self, double: float) -> None: ...
    def setPipeEfficiency(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setPipeModelType(self, pipeModelType: 'LoopedPipeNetwork.PipeModelType') -> None: ...
    def setRelaxationFactor(self, double: float) -> None: ...
    def setReservoirComposition(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setReservoirCompositionFromE300(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> None: ...
    def setReservoirPressure(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setRodPump(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def setSandRate(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setSolverType(self, solverType: 'LoopedPipeNetwork.SolverType') -> None: ...
    def setTolerance(self, double: float) -> None: ...
    def setTopsideModel(self, processSystem: jneqsim.process.processmodel.ProcessSystem, string: typing.Union[java.lang.String, str]) -> None: ...
    def setWaterBreakthrough(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float) -> None: ...
    def setWaterCut(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setWellPrice(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    def updateCompositionalMixing(self) -> None: ...
    def validate(self) -> java.util.List[java.lang.String]: ...
    def validateVFPPoint(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], double4: float, double5: float, double6: float) -> java.util.Map[java.lang.String, float]: ...
    class ArtificialLiftType(java.lang.Enum['LoopedPipeNetwork.ArtificialLiftType']):
        NONE: typing.ClassVar['LoopedPipeNetwork.ArtificialLiftType'] = ...
        GAS_LIFT: typing.ClassVar['LoopedPipeNetwork.ArtificialLiftType'] = ...
        ESP: typing.ClassVar['LoopedPipeNetwork.ArtificialLiftType'] = ...
        JET_PUMP: typing.ClassVar['LoopedPipeNetwork.ArtificialLiftType'] = ...
        ROD_PUMP: typing.ClassVar['LoopedPipeNetwork.ArtificialLiftType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'LoopedPipeNetwork.ArtificialLiftType': ...
        @staticmethod
        def values() -> typing.MutableSequence['LoopedPipeNetwork.ArtificialLiftType']: ...
    class IPRType(java.lang.Enum['LoopedPipeNetwork.IPRType']):
        PRODUCTIVITY_INDEX: typing.ClassVar['LoopedPipeNetwork.IPRType'] = ...
        VOGEL: typing.ClassVar['LoopedPipeNetwork.IPRType'] = ...
        FETKOVICH: typing.ClassVar['LoopedPipeNetwork.IPRType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'LoopedPipeNetwork.IPRType': ...
        @staticmethod
        def values() -> typing.MutableSequence['LoopedPipeNetwork.IPRType']: ...
    class NetworkElementType(java.lang.Enum['LoopedPipeNetwork.NetworkElementType']):
        PIPE: typing.ClassVar['LoopedPipeNetwork.NetworkElementType'] = ...
        WELL_IPR: typing.ClassVar['LoopedPipeNetwork.NetworkElementType'] = ...
        CHOKE: typing.ClassVar['LoopedPipeNetwork.NetworkElementType'] = ...
        TUBING: typing.ClassVar['LoopedPipeNetwork.NetworkElementType'] = ...
        MULTIPHASE_PIPE: typing.ClassVar['LoopedPipeNetwork.NetworkElementType'] = ...
        COMPRESSOR: typing.ClassVar['LoopedPipeNetwork.NetworkElementType'] = ...
        REGULATOR: typing.ClassVar['LoopedPipeNetwork.NetworkElementType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'LoopedPipeNetwork.NetworkElementType': ...
        @staticmethod
        def values() -> typing.MutableSequence['LoopedPipeNetwork.NetworkElementType']: ...
    class NetworkNode:
        def __init__(self, string: typing.Union[java.lang.String, str], nodeType: 'LoopedPipeNetwork.NodeType'): ...
        def getDemand(self) -> float: ...
        def getElevation(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getPressure(self) -> float: ...
        def getStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
        def getTemperature(self) -> float: ...
        def getType(self) -> 'LoopedPipeNetwork.NodeType': ...
        def isPressureFixed(self) -> bool: ...
        def setDemand(self, double: float) -> None: ...
        def setElevation(self, double: float) -> None: ...
        def setPressure(self, double: float) -> None: ...
        def setPressureFixed(self, boolean: bool) -> None: ...
        def setStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
        def setTemperature(self, double: float) -> None: ...
    class NetworkPipe:
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
        def getAmbientTemperature(self) -> float: ...
        def getArtificialLiftType(self) -> 'LoopedPipeNetwork.ArtificialLiftType': ...
        def getBBModel(self) -> jneqsim.process.equipment.pipeline.PipeBeggsAndBrills: ...
        def getChokeCriticalPressureRatio(self) -> float: ...
        def getChokeKv(self) -> float: ...
        def getChokeOpening(self) -> float: ...
        def getCo2MoleFraction(self) -> float: ...
        def getCompressorEfficiency(self) -> float: ...
        def getCompressorModel(self) -> jneqsim.process.equipment.compressor.Compressor: ...
        def getCompressorPower(self) -> float: ...
        def getCompressorSpeed(self) -> float: ...
        def getCorrosionModel(self) -> java.lang.String: ...
        def getCorrosionRate(self) -> float: ...
        def getDepositionRate(self) -> float: ...
        def getDiameter(self) -> float: ...
        def getElementType(self) -> 'LoopedPipeNetwork.NetworkElementType': ...
        def getErosionRate(self) -> float: ...
        def getErosionalC(self) -> float: ...
        def getErosionalVelocity(self) -> float: ...
        def getErosionalVelocityRatio(self) -> float: ...
        def getEspEfficiency(self) -> float: ...
        def getEspFrequency(self) -> float: ...
        def getEspHeadRise(self) -> float: ...
        def getEspPower(self) -> float: ...
        def getFetkovichC(self) -> float: ...
        def getFetkovichN(self) -> float: ...
        def getFlowRate(self) -> float: ...
        def getFlowRegime(self) -> java.lang.String: ...
        def getFrictionFactor(self) -> float: ...
        def getFromNode(self) -> java.lang.String: ...
        def getGasLiftGLR(self) -> float: ...
        def getGasLiftRate(self) -> float: ...
        def getH2sMoleFraction(self) -> float: ...
        def getHeadLoss(self) -> float: ...
        def getIprType(self) -> 'LoopedPipeNetwork.IPRType': ...
        def getLength(self) -> float: ...
        def getLiquidHoldup(self) -> float: ...
        def getMultiphaseSegments(self) -> int: ...
        def getName(self) -> java.lang.String: ...
        def getOutletTemperature(self) -> float: ...
        def getOverallHeatTransferCoeff(self) -> float: ...
        def getPipeEfficiency(self) -> float: ...
        def getPipeModel(self) -> jneqsim.process.equipment.pipeline.AdiabaticPipe: ...
        def getProductivityIndex(self) -> float: ...
        def getRegulatorSetPoint(self) -> float: ...
        def getRemainingWallLife(self) -> float: ...
        def getReservoirPressure(self) -> float: ...
        def getReynoldsNumber(self) -> float: ...
        def getRoughness(self) -> float: ...
        def getSandConcentration(self) -> float: ...
        def getSandRate(self) -> float: ...
        def getToNode(self) -> java.lang.String: ...
        def getTubingInclination(self) -> float: ...
        def getTubingSegments(self) -> int: ...
        def getVelocity(self) -> float: ...
        def getVogelQmax(self) -> float: ...
        def getWallThickness(self) -> float: ...
        def getWaterCut(self) -> float: ...
        def getWaterFlowRate(self) -> float: ...
        def getWaterInjectionRate(self) -> float: ...
        def isChokeUseValveModel(self) -> bool: ...
        def isCompressorHasChart(self) -> bool: ...
        def isGasIPR(self) -> bool: ...
        def setAmbientTemperature(self, double: float) -> None: ...
        def setArtificialLiftType(self, artificialLiftType: 'LoopedPipeNetwork.ArtificialLiftType') -> None: ...
        def setBBModel(self, pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills) -> None: ...
        def setChokeCriticalPressureRatio(self, double: float) -> None: ...
        def setChokeKv(self, double: float) -> None: ...
        def setChokeOpening(self, double: float) -> None: ...
        def setChokeUseValveModel(self, boolean: bool) -> None: ...
        def setCo2MoleFraction(self, double: float) -> None: ...
        def setCompressorEfficiency(self, double: float) -> None: ...
        def setCompressorHasChart(self, boolean: bool) -> None: ...
        def setCompressorModel(self, compressor: jneqsim.process.equipment.compressor.Compressor) -> None: ...
        def setCompressorPower(self, double: float) -> None: ...
        def setCompressorSpeed(self, double: float) -> None: ...
        def setCorrosionModel(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setCorrosionRate(self, double: float) -> None: ...
        def setDepositionRate(self, double: float) -> None: ...
        def setDiameter(self, double: float) -> None: ...
        def setElementType(self, networkElementType: 'LoopedPipeNetwork.NetworkElementType') -> None: ...
        def setErosionRate(self, double: float) -> None: ...
        def setErosionalC(self, double: float) -> None: ...
        def setErosionalVelocity(self, double: float) -> None: ...
        def setErosionalVelocityRatio(self, double: float) -> None: ...
        def setEspEfficiency(self, double: float) -> None: ...
        def setEspFrequency(self, double: float) -> None: ...
        def setEspHeadRise(self, double: float) -> None: ...
        def setEspPower(self, double: float) -> None: ...
        def setFetkovichC(self, double: float) -> None: ...
        def setFetkovichN(self, double: float) -> None: ...
        def setFlowRate(self, double: float) -> None: ...
        def setFlowRegime(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setFrictionFactor(self, double: float) -> None: ...
        def setGasIPR(self, boolean: bool) -> None: ...
        def setGasLiftGLR(self, double: float) -> None: ...
        def setGasLiftRate(self, double: float) -> None: ...
        def setH2sMoleFraction(self, double: float) -> None: ...
        def setHeadLoss(self, double: float) -> None: ...
        def setIprType(self, iPRType: 'LoopedPipeNetwork.IPRType') -> None: ...
        def setLength(self, double: float) -> None: ...
        def setLiquidHoldup(self, double: float) -> None: ...
        def setMultiphaseSegments(self, int: int) -> None: ...
        def setOutletTemperature(self, double: float) -> None: ...
        def setOverallHeatTransferCoeff(self, double: float) -> None: ...
        def setPipeEfficiency(self, double: float) -> None: ...
        def setPipeModel(self, adiabaticPipe: jneqsim.process.equipment.pipeline.AdiabaticPipe) -> None: ...
        def setProductivityIndex(self, double: float) -> None: ...
        def setRegulatorSetPoint(self, double: float) -> None: ...
        def setRemainingWallLife(self, double: float) -> None: ...
        def setReservoirPressure(self, double: float) -> None: ...
        def setReynoldsNumber(self, double: float) -> None: ...
        def setRoughness(self, double: float) -> None: ...
        def setSandConcentration(self, double: float) -> None: ...
        def setSandRate(self, double: float) -> None: ...
        def setTubingInclination(self, double: float) -> None: ...
        def setTubingSegments(self, int: int) -> None: ...
        def setVelocity(self, double: float) -> None: ...
        def setVogelQmax(self, double: float) -> None: ...
        def setWallThickness(self, double: float) -> None: ...
        def setWaterCut(self, double: float) -> None: ...
        def setWaterFlowRate(self, double: float) -> None: ...
        def setWaterInjectionRate(self, double: float) -> None: ...
    class NodeType(java.lang.Enum['LoopedPipeNetwork.NodeType']):
        SOURCE: typing.ClassVar['LoopedPipeNetwork.NodeType'] = ...
        SINK: typing.ClassVar['LoopedPipeNetwork.NodeType'] = ...
        JUNCTION: typing.ClassVar['LoopedPipeNetwork.NodeType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'LoopedPipeNetwork.NodeType': ...
        @staticmethod
        def values() -> typing.MutableSequence['LoopedPipeNetwork.NodeType']: ...
    class PipeModelType(java.lang.Enum['LoopedPipeNetwork.PipeModelType']):
        DARCY_WEISBACH: typing.ClassVar['LoopedPipeNetwork.PipeModelType'] = ...
        BEGGS_BRILL: typing.ClassVar['LoopedPipeNetwork.PipeModelType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'LoopedPipeNetwork.PipeModelType': ...
        @staticmethod
        def values() -> typing.MutableSequence['LoopedPipeNetwork.PipeModelType']: ...
    class SolverType(java.lang.Enum['LoopedPipeNetwork.SolverType']):
        HARDY_CROSS: typing.ClassVar['LoopedPipeNetwork.SolverType'] = ...
        SEQUENTIAL: typing.ClassVar['LoopedPipeNetwork.SolverType'] = ...
        NEWTON_RAPHSON: typing.ClassVar['LoopedPipeNetwork.SolverType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'LoopedPipeNetwork.SolverType': ...
        @staticmethod
        def values() -> typing.MutableSequence['LoopedPipeNetwork.SolverType']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.network")``.

    LoopDetector: typing.Type[LoopDetector]
    LoopedPipeNetwork: typing.Type[LoopedPipeNetwork]
    NetworkLinearSolver: typing.Type[NetworkLinearSolver]
    NetworkLoop: typing.Type[NetworkLoop]
    NetworkOptimizer: typing.Type[NetworkOptimizer]
    NetworkValidationBenchmarks: typing.Type[NetworkValidationBenchmarks]
    PipeFlowNetwork: typing.Type[PipeFlowNetwork]
    WellFlowlineNetwork: typing.Type[WellFlowlineNetwork]
