import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import jneqsim.process.equipment.pipeline.twophasepipe
import typing

class GeometryCalculator(java.io.Serializable):
    def __init__(self): ...
    def approximateLiquidLevel(self, double: float, double2: float) -> float: ...
    def calcAnnularFilmThickness(self, double: float, double2: float) -> float: ...
    def calcAnnularGasPerimeter(self, double: float, double2: float) -> float: ...
    def calcAreaDerivative(self, double: float, double2: float) -> float: ...
    def calculateFromHoldup(
        self, double: float, double2: float
    ) -> "GeometryCalculator.StratifiedGeometry": ...
    def calculateFromLiquidLevel(
        self, double: float, double2: float
    ) -> "GeometryCalculator.StratifiedGeometry": ...
    def isStratifiedStable(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
    ) -> bool: ...

    class StratifiedGeometry(java.io.Serializable):
        liquidArea: float = ...
        gasArea: float = ...
        liquidWettedPerimeter: float = ...
        gasWettedPerimeter: float = ...
        interfacialWidth: float = ...
        liquidHydraulicDiameter: float = ...
        gasHydraulicDiameter: float = ...
        liquidAngle: float = ...
        liquidLevel: float = ...
        liquidHoldup: float = ...
        def __init__(self): ...

class InterfacialFriction(java.io.Serializable):
    def __init__(self): ...
    def calcInterfacialForce(
        self,
        flowRegime: jneqsim.process.equipment.pipeline.twophasepipe.PipeSection.FlowRegime,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
    ) -> float: ...
    def calculate(
        self,
        flowRegime: jneqsim.process.equipment.pipeline.twophasepipe.PipeSection.FlowRegime,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
    ) -> "InterfacialFriction.InterfacialFrictionResult": ...

    class InterfacialFrictionResult(java.io.Serializable):
        interfacialShear: float = ...
        frictionFactor: float = ...
        slipVelocity: float = ...
        interfacialAreaPerLength: float = ...
        def __init__(self): ...

class WallFriction(java.io.Serializable):
    def __init__(self): ...
    def calcColebrookFanning(
        self, double: float, double2: float, double3: float
    ) -> float: ...
    def calcFanningFrictionFactor(
        self, double: float, double2: float, double3: float
    ) -> float: ...
    def calculate(
        self,
        flowRegime: jneqsim.process.equipment.pipeline.twophasepipe.PipeSection.FlowRegime,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
        double8: float,
        double9: float,
    ) -> "WallFriction.WallFrictionResult": ...
    def getDefaultRoughness(self) -> float: ...
    def setDefaultRoughness(self, double: float) -> None: ...

    class WallFrictionResult(java.io.Serializable):
        gasWallShear: float = ...
        liquidWallShear: float = ...
        gasFrictionFactor: float = ...
        liquidFrictionFactor: float = ...
        gasReynolds: float = ...
        liquidReynolds: float = ...
        def __init__(self): ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.pipeline.twophasepipe.closure")``.

    GeometryCalculator: typing.Type[GeometryCalculator]
    InterfacialFriction: typing.Type[InterfacialFriction]
    WallFriction: typing.Type[WallFriction]
