
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import neqsim.process.equipment
import neqsim.process.equipment.compressor
import neqsim.process.equipment.distillation
import neqsim.process.equipment.expander
import neqsim.process.equipment.heatexchanger
import neqsim.process.equipment.manifold
import neqsim.process.equipment.mixer
import neqsim.process.equipment.pipeline
import neqsim.process.equipment.pump
import neqsim.process.equipment.reactor
import neqsim.process.equipment.separator
import neqsim.process.equipment.splitter
import neqsim.process.equipment.stream
import neqsim.process.equipment.tank
import neqsim.process.equipment.util
import neqsim.process.equipment.valve
import neqsim.process.measurementdevice
import neqsim.process.util.report
import neqsim.thermo.system
import typing



class BaseResponse:
    tagName: java.lang.String = ...
    name: java.lang.String = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, processEquipmentInterface: neqsim.process.equipment.ProcessEquipmentInterface): ...
    @typing.overload
    def __init__(self, measurementDeviceInterface: neqsim.process.measurementdevice.MeasurementDeviceInterface): ...
    def applyConfig(self, reportConfig: neqsim.process.util.report.ReportConfig) -> None: ...

class FluidComponentResponse:
    name: java.lang.String = ...
    properties: java.util.HashMap = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], systemInterface: neqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(self, systemInterface: neqsim.thermo.system.SystemInterface): ...
    def print_(self) -> None: ...

class FluidResponse:
    name: java.lang.String = ...
    properties: java.util.HashMap = ...
    composition: java.util.HashMap = ...
    conditions: java.util.HashMap = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], systemInterface: neqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(self, systemInterface: neqsim.thermo.system.SystemInterface): ...
    def print_(self) -> None: ...

class KPIDashboard:
    def __init__(self): ...
    def addScenario(self, string: typing.Union[java.lang.String, str], scenarioKPI: 'ScenarioKPI') -> None: ...
    def clear(self) -> None: ...
    def getScenarioCount(self) -> int: ...
    def printDashboard(self) -> None: ...

class ScenarioKPI:
    def __init__(self): ...
    @staticmethod
    def builder() -> 'ScenarioKPI.Builder': ...
    def calculateEnvironmentalScore(self) -> float: ...
    def calculateOverallScore(self) -> float: ...
    def calculateProcessScore(self) -> float: ...
    def calculateSafetyScore(self) -> float: ...
    def getAverageFlowRate(self) -> float: ...
    def getCo2Emissions(self) -> float: ...
    def getEnergyConsumption(self) -> float: ...
    def getErrorCount(self) -> int: ...
    def getFinalStatus(self) -> java.lang.String: ...
    def getFlareGasVolume(self) -> float: ...
    def getFlaringDuration(self) -> float: ...
    def getLostProductionValue(self) -> float: ...
    def getOperatingCost(self) -> float: ...
    def getPeakPressure(self) -> float: ...
    def getPeakTemperature(self) -> float: ...
    def getProductionLoss(self) -> float: ...
    def getRecoveryTime(self) -> float: ...
    def getSafetyMarginToMAWP(self) -> float: ...
    def getSafetySystemActuations(self) -> int: ...
    def getSimulationDuration(self) -> float: ...
    def getSteadyStateDeviation(self) -> float: ...
    def getTimeToESDActivation(self) -> float: ...
    def getVentedMass(self) -> float: ...
    def getWarningCount(self) -> int: ...
    def isHippsTripped(self) -> bool: ...
    def isPsvActivated(self) -> bool: ...
    class Builder:
        def __init__(self): ...
        def averageFlowRate(self, double: float) -> 'ScenarioKPI.Builder': ...
        def build(self) -> 'ScenarioKPI': ...
        def co2Emissions(self, double: float) -> 'ScenarioKPI.Builder': ...
        def energyConsumption(self, double: float) -> 'ScenarioKPI.Builder': ...
        def errorCount(self, int: int) -> 'ScenarioKPI.Builder': ...
        def finalStatus(self, string: typing.Union[java.lang.String, str]) -> 'ScenarioKPI.Builder': ...
        def flareGasVolume(self, double: float) -> 'ScenarioKPI.Builder': ...
        def flaringDuration(self, double: float) -> 'ScenarioKPI.Builder': ...
        def hippsTripped(self, boolean: bool) -> 'ScenarioKPI.Builder': ...
        def lostProductionValue(self, double: float) -> 'ScenarioKPI.Builder': ...
        def operatingCost(self, double: float) -> 'ScenarioKPI.Builder': ...
        def peakPressure(self, double: float) -> 'ScenarioKPI.Builder': ...
        def peakTemperature(self, double: float) -> 'ScenarioKPI.Builder': ...
        def productionLoss(self, double: float) -> 'ScenarioKPI.Builder': ...
        def psvActivated(self, boolean: bool) -> 'ScenarioKPI.Builder': ...
        def recoveryTime(self, double: float) -> 'ScenarioKPI.Builder': ...
        def safetyMarginToMAWP(self, double: float) -> 'ScenarioKPI.Builder': ...
        def safetySystemActuations(self, int: int) -> 'ScenarioKPI.Builder': ...
        def simulationDuration(self, double: float) -> 'ScenarioKPI.Builder': ...
        def steadyStateDeviation(self, double: float) -> 'ScenarioKPI.Builder': ...
        def timeToESDActivation(self, double: float) -> 'ScenarioKPI.Builder': ...
        def ventedMass(self, double: float) -> 'ScenarioKPI.Builder': ...
        def warningCount(self, int: int) -> 'ScenarioKPI.Builder': ...

class Value:
    value: java.lang.String = ...
    unit: java.lang.String = ...
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...

class WellAllocatorResponse:
    name: java.lang.String = ...
    data: java.util.HashMap = ...
    def __init__(self, wellAllocator: neqsim.process.measurementdevice.WellAllocator): ...

class ComponentSplitterResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, componentSplitter: neqsim.process.equipment.splitter.ComponentSplitter): ...

class CompressorResponse(BaseResponse):
    suctionTemperature: float = ...
    dischargeTemperature: float = ...
    suctionPressure: float = ...
    dischargePressure: float = ...
    polytropicHead: float = ...
    polytropicEfficiency: float = ...
    power: float = ...
    suctionVolumeFlow: float = ...
    internalVolumeFlow: float = ...
    dischargeVolumeFlow: float = ...
    molarMass: float = ...
    suctionMassDensity: float = ...
    dischargeMassDensity: float = ...
    massflow: float = ...
    stdFlow: float = ...
    speed: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, compressor: neqsim.process.equipment.compressor.Compressor): ...
    def applyConfig(self, reportConfig: neqsim.process.util.report.ReportConfig) -> None: ...

class DistillationColumnResponse(BaseResponse):
    massBalanceError: float = ...
    trayTemperature: typing.MutableSequence[float] = ...
    trayPressure: typing.MutableSequence[float] = ...
    numberOfTrays: int = ...
    trayVaporFlowRate: typing.MutableSequence[float] = ...
    trayLiquidFlowRate: typing.MutableSequence[float] = ...
    trayFeedFlow: typing.MutableSequence[float] = ...
    trayMassBalance: typing.MutableSequence[float] = ...
    def __init__(self, distillationColumn: neqsim.process.equipment.distillation.DistillationColumn): ...

class FurnaceBurnerResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, furnaceBurner: neqsim.process.equipment.reactor.FurnaceBurner): ...

class HXResponse(BaseResponse):
    feedTemperature1: float = ...
    dischargeTemperature1: float = ...
    HXthermalEfectiveness: float = ...
    feedTemperature2: float = ...
    dischargeTemperature2: float = ...
    dutyBalance: float = ...
    duty: float = ...
    UAvalue: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, heatExchanger: neqsim.process.equipment.heatexchanger.HeatExchanger): ...

class HeaterResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, heater: neqsim.process.equipment.heatexchanger.Heater): ...

class MPMResponse(BaseResponse):
    massFLow: float = ...
    GOR: float = ...
    GOR_std: float = ...
    gasDensity: float = ...
    oilDensity: float = ...
    waterDensity: float = ...
    def __init__(self, multiPhaseMeter: neqsim.process.measurementdevice.MultiPhaseMeter): ...

class ManifoldResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, manifold: neqsim.process.equipment.manifold.Manifold): ...

class MixerResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, mixer: neqsim.process.equipment.mixer.Mixer): ...

class MultiStreamHeatExchanger2Response(BaseResponse):
    data: java.util.HashMap = ...
    temperatureApproach: float = ...
    compositeCurveResults: java.util.Map = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, multiStreamHeatExchanger2: neqsim.process.equipment.heatexchanger.MultiStreamHeatExchanger2): ...

class MultiStreamHeatExchangerResponse(BaseResponse):
    data: java.util.HashMap = ...
    feedTemperature: typing.MutableSequence[float] = ...
    dischargeTemperature: typing.MutableSequence[float] = ...
    duty: typing.MutableSequence[float] = ...
    flowRate: typing.MutableSequence[float] = ...
    def __init__(self, multiStreamHeatExchanger: neqsim.process.equipment.heatexchanger.MultiStreamHeatExchanger): ...

class PipeBeggsBrillsResponse(BaseResponse):
    inletPressure: float = ...
    outletPressure: float = ...
    inletTemperature: float = ...
    outletTemperature: float = ...
    inletDensity: float = ...
    outletDensity: float = ...
    inletVolumeFlow: float = ...
    outletVolumeFlow: float = ...
    inletMassFlow: float = ...
    outletMassFlow: float = ...
    def __init__(self, pipeBeggsAndBrills: neqsim.process.equipment.pipeline.PipeBeggsAndBrills): ...

class PumpResponse(BaseResponse):
    data: java.util.HashMap = ...
    suctionTemperature: float = ...
    dischargeTemperature: float = ...
    suctionPressure: float = ...
    dischargePressure: float = ...
    power: float = ...
    duty: float = ...
    suctionVolumeFlow: float = ...
    internalVolumeFlow: float = ...
    dischargeVolumeFlow: float = ...
    molarMass: float = ...
    suctionMassDensity: float = ...
    dischargeMassDensity: float = ...
    massflow: float = ...
    speed: int = ...
    def __init__(self, pump: neqsim.process.equipment.pump.Pump): ...

class RecycleResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, recycle: neqsim.process.equipment.util.Recycle): ...

class SeparatorResponse(BaseResponse):
    gasLoadFactor: float = ...
    feed: 'StreamResponse' = ...
    gas: 'StreamResponse' = ...
    liquid: 'StreamResponse' = ...
    oil: 'StreamResponse' = ...
    water: 'StreamResponse' = ...
    @typing.overload
    def __init__(self, separator: neqsim.process.equipment.separator.Separator): ...
    @typing.overload
    def __init__(self, threePhaseSeparator: neqsim.process.equipment.separator.ThreePhaseSeparator): ...

class SplitterResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, splitter: neqsim.process.equipment.splitter.Splitter): ...

class StreamResponse(BaseResponse):
    properties: java.util.HashMap = ...
    conditions: java.util.HashMap = ...
    composition: java.util.HashMap = ...
    def __init__(self, streamInterface: neqsim.process.equipment.stream.StreamInterface): ...
    def applyConfig(self, reportConfig: neqsim.process.util.report.ReportConfig) -> None: ...
    def print_(self) -> None: ...

class TankResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, tank: neqsim.process.equipment.tank.Tank): ...

class ThreePhaseSeparatorResponse(BaseResponse):
    gasLoadFactor: float = ...
    massflow: float = ...
    gasFluid: FluidResponse = ...
    oilFluid: FluidResponse = ...
    @typing.overload
    def __init__(self, separator: neqsim.process.equipment.separator.Separator): ...
    @typing.overload
    def __init__(self, threePhaseSeparator: neqsim.process.equipment.separator.ThreePhaseSeparator): ...

class TurboExpanderCompressorResponse(BaseResponse):
    def __init__(self, turboExpanderCompressor: neqsim.process.equipment.expander.TurboExpanderCompressor): ...

class ValveResponse(BaseResponse):
    data: java.util.HashMap = ...
    def __init__(self, valveInterface: neqsim.process.equipment.valve.ValveInterface): ...
    def print_(self) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("neqsim.process.util.monitor")``.

    BaseResponse: typing.Type[BaseResponse]
    ComponentSplitterResponse: typing.Type[ComponentSplitterResponse]
    CompressorResponse: typing.Type[CompressorResponse]
    DistillationColumnResponse: typing.Type[DistillationColumnResponse]
    FluidComponentResponse: typing.Type[FluidComponentResponse]
    FluidResponse: typing.Type[FluidResponse]
    FurnaceBurnerResponse: typing.Type[FurnaceBurnerResponse]
    HXResponse: typing.Type[HXResponse]
    HeaterResponse: typing.Type[HeaterResponse]
    KPIDashboard: typing.Type[KPIDashboard]
    MPMResponse: typing.Type[MPMResponse]
    ManifoldResponse: typing.Type[ManifoldResponse]
    MixerResponse: typing.Type[MixerResponse]
    MultiStreamHeatExchanger2Response: typing.Type[MultiStreamHeatExchanger2Response]
    MultiStreamHeatExchangerResponse: typing.Type[MultiStreamHeatExchangerResponse]
    PipeBeggsBrillsResponse: typing.Type[PipeBeggsBrillsResponse]
    PumpResponse: typing.Type[PumpResponse]
    RecycleResponse: typing.Type[RecycleResponse]
    ScenarioKPI: typing.Type[ScenarioKPI]
    SeparatorResponse: typing.Type[SeparatorResponse]
    SplitterResponse: typing.Type[SplitterResponse]
    StreamResponse: typing.Type[StreamResponse]
    TankResponse: typing.Type[TankResponse]
    ThreePhaseSeparatorResponse: typing.Type[ThreePhaseSeparatorResponse]
    TurboExpanderCompressorResponse: typing.Type[TurboExpanderCompressorResponse]
    Value: typing.Type[Value]
    ValveResponse: typing.Type[ValveResponse]
    WellAllocatorResponse: typing.Type[WellAllocatorResponse]
