import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.util.fire
import jneqsim.thermo.system
import typing

class AcceptanceResult(java.io.Serializable):
    def __init__(
        self,
        double: float,
        double2: float,
        double3: float,
        boolean: bool,
        double4: float,
        string: typing.Union[java.lang.String, str],
    ): ...
    def getAccumulationFraction(self) -> float: ...
    def getAllowableAccumulatedPressureBara(self) -> float: ...
    def getBasis(self) -> java.lang.String: ...
    def getMarginBara(self) -> float: ...
    def getPeakPressureBara(self) -> float: ...
    def isAccepted(self) -> bool: ...

class BlockedOutletRelief:
    def __init__(self): ...
    def calculate(self) -> "ReliefScenario": ...
    def setFluid(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> "BlockedOutletRelief": ...
    def setInflowRateKgPerHr(self, double: float) -> "BlockedOutletRelief": ...
    def setInflowRateKgPerS(self, double: float) -> "BlockedOutletRelief": ...
    def setName(
        self, string: typing.Union[java.lang.String, str]
    ) -> "BlockedOutletRelief": ...
    def setReliefPressureBara(self, double: float) -> "BlockedOutletRelief": ...
    def setReliefTemperatureC(self, double: float) -> "BlockedOutletRelief": ...

class CheckValveLeakRelief:
    def __init__(self): ...
    def calculate(self) -> "ReliefScenario": ...
    def setDischargeCoefficient(self, double: float) -> "CheckValveLeakRelief": ...
    def setDownstreamPressureBara(self, double: float) -> "CheckValveLeakRelief": ...
    def setFluid(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> "CheckValveLeakRelief": ...
    def setLeakAreaFraction(self, double: float) -> "CheckValveLeakRelief": ...
    def setMolarMassKgPerMol(self, double: float) -> "CheckValveLeakRelief": ...
    def setName(
        self, string: typing.Union[java.lang.String, str]
    ) -> "CheckValveLeakRelief": ...
    def setNominalDiameterInch(self, double: float) -> "CheckValveLeakRelief": ...
    def setNominalDiameterM(self, double: float) -> "CheckValveLeakRelief": ...
    def setSpecificHeatRatio(self, double: float) -> "CheckValveLeakRelief": ...
    def setUpstreamPressureBara(self, double: float) -> "CheckValveLeakRelief": ...
    def setUpstreamTemperatureC(self, double: float) -> "CheckValveLeakRelief": ...

class ComplianceFinding(java.io.Serializable):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        complianceStatus: "ComplianceStatus",
        string3: typing.Union[java.lang.String, str],
    ): ...
    def getDetail(self) -> java.lang.String: ...
    def getRequirementId(self) -> java.lang.String: ...
    def getStatus(self) -> "ComplianceStatus": ...
    def getTitle(self) -> java.lang.String: ...
    def toString(self) -> java.lang.String: ...

class ComplianceStatus(java.lang.Enum["ComplianceStatus"]):
    PASS: typing.ClassVar["ComplianceStatus"] = ...
    FAIL: typing.ClassVar["ComplianceStatus"] = ...
    INFO: typing.ClassVar["ComplianceStatus"] = ...
    NEEDS_REVIEW: typing.ClassVar["ComplianceStatus"] = ...
    def getLabel(self) -> java.lang.String: ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> "ComplianceStatus": ...
    @staticmethod
    def values() -> typing.MutableSequence["ComplianceStatus"]: ...

class ControlValveFailureRelief:
    def __init__(self): ...
    def calculate(self) -> "ReliefScenario": ...
    def setCv(self, double: float) -> "ControlValveFailureRelief": ...
    def setCvErosionMargin(self, double: float) -> "ControlValveFailureRelief": ...
    def setDischargeCoefficient(self, double: float) -> "ControlValveFailureRelief": ...
    def setDownstreamPressureBara(
        self, double: float
    ) -> "ControlValveFailureRelief": ...
    def setEffectiveAreaM2(self, double: float) -> "ControlValveFailureRelief": ...
    def setFluid(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> "ControlValveFailureRelief": ...
    def setMolarMassKgPerMol(self, double: float) -> "ControlValveFailureRelief": ...
    def setName(
        self, string: typing.Union[java.lang.String, str]
    ) -> "ControlValveFailureRelief": ...
    def setSpecificHeatRatio(self, double: float) -> "ControlValveFailureRelief": ...
    def setUpstreamPressureBara(self, double: float) -> "ControlValveFailureRelief": ...
    def setUpstreamTemperatureC(self, double: float) -> "ControlValveFailureRelief": ...

class FireCaseRelief:
    def __init__(self): ...
    def calculate(self) -> "ReliefScenario": ...
    def setFluid(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> "FireCaseRelief": ...
    def setHasDrainage(self, boolean: bool) -> "FireCaseRelief": ...
    def setHasFireFighting(self, boolean: bool) -> "FireCaseRelief": ...
    def setLatentHeatJPerKg(self, double: float) -> "FireCaseRelief": ...
    def setName(
        self, string: typing.Union[java.lang.String, str]
    ) -> "FireCaseRelief": ...
    def setReliefPressureBara(self, double: float) -> "FireCaseRelief": ...
    def setReliefTemperatureC(self, double: float) -> "FireCaseRelief": ...
    def setVesselDiameterM(self, double: float) -> "FireCaseRelief": ...
    def setWettedAreaM2(self, double: float) -> "FireCaseRelief": ...
    def setWettedHeightM(self, double: float) -> "FireCaseRelief": ...

class OverpressureAcceptanceChecker(java.io.Serializable):
    SINGLE_NON_FIRE_FACTOR: typing.ClassVar[float] = ...
    MULTIPLE_NON_FIRE_FACTOR: typing.ClassVar[float] = ...
    FIRE_FACTOR: typing.ClassVar[float] = ...
    def __init__(self): ...
    def accumulationFactor(
        self, reliefCause: "ReliefCause", boolean: bool
    ) -> float: ...
    def check(
        self,
        double: float,
        protectedItem: "ProtectedItem",
        reliefCause: "ReliefCause",
        boolean: bool,
    ) -> AcceptanceResult: ...

class OverpressureProtectionStudy(java.io.Serializable):
    def __init__(self, protectedItem: "ProtectedItem"): ...
    def addScenario(
        self, reliefScenario: "ReliefScenario"
    ) -> "OverpressureProtectionStudy": ...
    def evaluate(self) -> "OverpressureStudyResult": ...
    def getItem(self) -> "ProtectedItem": ...
    def getScenarios(self) -> java.util.List["ReliefScenario"]: ...
    def governingScenario(self) -> "ReliefScenario": ...
    def setMultipleDevices(self, boolean: bool) -> "OverpressureProtectionStudy": ...

class OverpressureStudyResult(java.io.Serializable):
    def __init__(
        self,
        protectedItem: "ProtectedItem",
        reliefScenario: "ReliefScenario",
        list: java.util.List["ReliefScenario"],
        double: float,
        double2: float,
        string: typing.Union[java.lang.String, str],
        double3: float,
        double4: float,
        boolean: bool,
        acceptanceResult: AcceptanceResult,
        list2: java.util.List[typing.Union[java.lang.String, str]],
        pSVSizingResult: jneqsim.process.util.fire.ReliefValveSizing.PSVSizingResult,
    ): ...
    def getAcceptance(self) -> AcceptanceResult: ...
    def getGoverningScenario(self) -> "ReliefScenario": ...
    def getItem(self) -> "ProtectedItem": ...
    def getRecommendedOrifice(self) -> java.lang.String: ...
    def getRequiredAreaIn2(self) -> float: ...
    def getRequiredAreaM2(self) -> float: ...
    def getScenarios(self) -> java.util.List["ReliefScenario"]: ...
    def getSelectedAreaIn2(self) -> float: ...
    def getSelectedOrificeCapacityKgPerS(self) -> float: ...
    def getSizingResult(
        self,
    ) -> jneqsim.process.util.fire.ReliefValveSizing.PSVSizingResult: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isCapacityAdequate(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...

class PipelinePressureProtectionCalculator(java.io.Serializable):
    def __init__(self): ...
    def calcProtection(self) -> None: ...
    def getDesignMargin(self) -> float: ...
    def getMaxIncidentalPressure(self) -> float: ...
    def getVerdict(self) -> java.lang.String: ...
    def isBarrier1Adequate(self) -> bool: ...
    def isBarrier2Adequate(self) -> bool: ...
    def isFullyRated(self) -> bool: ...
    def isProtectionAdequate(self) -> bool: ...
    def setBarriers(self, double: float, double2: float) -> None: ...
    def setPressureBasis(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    def toJson(self) -> java.lang.String: ...

class ProtectedItem(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], double: float): ...
    def getBackPressureBara(self) -> float: ...
    def getDesignTemperatureC(self) -> float: ...
    def getMaximumAllowableWorkingPressureBara(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getReliefSetPressureBara(self) -> float: ...
    def setBackPressureBara(self, double: float) -> "ProtectedItem": ...
    def setDesignTemperatureC(self, double: float) -> "ProtectedItem": ...
    def setMaximumAllowableWorkingPressureBara(
        self, double: float
    ) -> "ProtectedItem": ...
    def setReliefSetPressureBara(self, double: float) -> "ProtectedItem": ...

class ReliefCause(java.lang.Enum["ReliefCause"]):
    BLOCKED_OUTLET: typing.ClassVar["ReliefCause"] = ...
    CHECK_VALVE_LEAKAGE: typing.ClassVar["ReliefCause"] = ...
    GAS_BLOW_BY: typing.ClassVar["ReliefCause"] = ...
    LIQUID_BLOW_BY: typing.ClassVar["ReliefCause"] = ...
    VOLATILE_LIQUID_INGRESS: typing.ClassVar["ReliefCause"] = ...
    INADVERTENT_VALVE_OPENING: typing.ClassVar["ReliefCause"] = ...
    CONTROL_VALVE_FAILURE: typing.ClassVar["ReliefCause"] = ...
    FIRE: typing.ClassVar["ReliefCause"] = ...
    THERMAL_EXPANSION: typing.ClassVar["ReliefCause"] = ...
    CHOKE_COLLAPSE: typing.ClassVar["ReliefCause"] = ...
    TUBE_RUPTURE: typing.ClassVar["ReliefCause"] = ...
    VACUUM: typing.ClassVar["ReliefCause"] = ...
    OTHER: typing.ClassVar["ReliefCause"] = ...
    def getLabel(self) -> java.lang.String: ...
    def getStandardReference(self) -> java.lang.String: ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> "ReliefCause": ...
    @staticmethod
    def values() -> typing.MutableSequence["ReliefCause"]: ...

class ReliefDisposalNetwork:
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addContribution(
        self, reliefLoadContribution: "ReliefLoadContribution"
    ) -> "ReliefDisposalNetwork": ...
    @typing.overload
    def addRelief(
        self, overpressureStudyResult: OverpressureStudyResult
    ) -> "ReliefDisposalNetwork": ...
    @typing.overload
    def addRelief(
        self, overpressureStudyResult: OverpressureStudyResult, boolean: bool
    ) -> "ReliefDisposalNetwork": ...
    def calculate(self) -> "ReliefDisposalResult": ...
    def getName(self) -> java.lang.String: ...

class ReliefDisposalResult(java.io.Serializable):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        double: float,
        double2: float,
        string2: typing.Union[java.lang.String, str],
        list: java.util.List["ReliefLoadContribution"],
        list2: java.util.List[typing.Union[java.lang.String, str]],
    ): ...
    def getContributions(self) -> java.util.List["ReliefLoadContribution"]: ...
    def getGoverningContributor(self) -> java.lang.String: ...
    def getNetworkName(self) -> java.lang.String: ...
    def getPeakSingleKgPerS(self) -> float: ...
    def getTotalSimultaneousKgPerHr(self) -> float: ...
    def getTotalSimultaneousKgPerS(self) -> float: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def toJson(self) -> java.lang.String: ...

class ReliefLoadContribution(java.io.Serializable):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        reliefCause: ReliefCause,
        reliefPhase: "ReliefPhase",
        double: float,
        boolean: bool,
    ): ...
    def getCause(self) -> ReliefCause: ...
    def getItemName(self) -> java.lang.String: ...
    def getMassFlowKgPerHr(self) -> float: ...
    def getMassFlowKgPerS(self) -> float: ...
    def getPhase(self) -> "ReliefPhase": ...
    def isSimultaneous(self) -> bool: ...

class ReliefPhase(java.lang.Enum["ReliefPhase"]):
    VAPOUR: typing.ClassVar["ReliefPhase"] = ...
    LIQUID: typing.ClassVar["ReliefPhase"] = ...
    TWO_PHASE: typing.ClassVar["ReliefPhase"] = ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> "ReliefPhase": ...
    @staticmethod
    def values() -> typing.MutableSequence["ReliefPhase"]: ...

class ReliefScenario(java.io.Serializable):
    def getAssumptions(self) -> java.util.List[java.lang.String]: ...
    def getCause(self) -> ReliefCause: ...
    def getCompressibility(self) -> float: ...
    def getDensityKgPerM3(self) -> float: ...
    def getGasDensityKgPerM3(self) -> float: ...
    def getGasMassFraction(self) -> float: ...
    def getLatentHeatJPerKg(self) -> float: ...
    def getLiquidDensityKgPerM3(self) -> float: ...
    def getLiquidHeatCapacityJPerKgK(self) -> float: ...
    def getMolarMassKgPerMol(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getPhase(self) -> ReliefPhase: ...
    def getReliefRateKgPerHr(self) -> float: ...
    def getReliefRateKgPerS(self) -> float: ...
    def getReliefTemperatureK(self) -> float: ...
    def getSpecificHeatRatio(self) -> float: ...
    def getStandardReference(self) -> java.lang.String: ...
    def getViscosityPaS(self) -> float: ...
    def isCredible(self) -> bool: ...
    def isDynamicallyDetermined(self) -> bool: ...
    def withCredible(self, boolean: bool) -> "ReliefScenario": ...

    class Builder:
        def __init__(
            self, string: typing.Union[java.lang.String, str], reliefCause: ReliefCause
        ): ...
        def addAssumption(
            self, string: typing.Union[java.lang.String, str]
        ) -> "ReliefScenario.Builder": ...
        def assumptions(
            self, list: java.util.List[typing.Union[java.lang.String, str]]
        ) -> "ReliefScenario.Builder": ...
        def build(self) -> "ReliefScenario": ...
        def compressibility(self, double: float) -> "ReliefScenario.Builder": ...
        def credible(self, boolean: bool) -> "ReliefScenario.Builder": ...
        def densityKgPerM3(self, double: float) -> "ReliefScenario.Builder": ...
        def dynamicallyDetermined(self, boolean: bool) -> "ReliefScenario.Builder": ...
        def gasDensityKgPerM3(self, double: float) -> "ReliefScenario.Builder": ...
        def gasMassFraction(self, double: float) -> "ReliefScenario.Builder": ...
        def latentHeatJPerKg(self, double: float) -> "ReliefScenario.Builder": ...
        def liquidDensityKgPerM3(self, double: float) -> "ReliefScenario.Builder": ...
        def liquidHeatCapacityJPerKgK(
            self, double: float
        ) -> "ReliefScenario.Builder": ...
        def molarMassKgPerMol(self, double: float) -> "ReliefScenario.Builder": ...
        def phase(self, reliefPhase: ReliefPhase) -> "ReliefScenario.Builder": ...
        def reliefRateKgPerS(self, double: float) -> "ReliefScenario.Builder": ...
        def reliefTemperatureK(self, double: float) -> "ReliefScenario.Builder": ...
        def specificHeatRatio(self, double: float) -> "ReliefScenario.Builder": ...
        def standardReference(
            self, string: typing.Union[java.lang.String, str]
        ) -> "ReliefScenario.Builder": ...
        def viscosityPaS(self, double: float) -> "ReliefScenario.Builder": ...

class TR3001ComplianceChecker:
    def __init__(self): ...
    def check(
        self, overpressureStudyResult: OverpressureStudyResult
    ) -> java.util.List[ComplianceFinding]: ...
    @staticmethod
    def findingsToJson(list: java.util.List[ComplianceFinding]) -> java.lang.String: ...
    def isCompliant(self, list: java.util.List[ComplianceFinding]) -> bool: ...

class TubeRuptureRelief:
    def __init__(self): ...
    def calculate(self) -> ReliefScenario: ...
    def setDischargeCoefficient(self, double: float) -> "TubeRuptureRelief": ...
    def setHighPressureBara(self, double: float) -> "TubeRuptureRelief": ...
    def setHighPressureFluid(
        self, systemInterface: jneqsim.thermo.system.SystemInterface
    ) -> "TubeRuptureRelief": ...
    def setHighTemperatureC(self, double: float) -> "TubeRuptureRelief": ...
    def setLowPressureBara(self, double: float) -> "TubeRuptureRelief": ...
    def setMolarMassKgPerMol(self, double: float) -> "TubeRuptureRelief": ...
    def setName(
        self, string: typing.Union[java.lang.String, str]
    ) -> "TubeRuptureRelief": ...
    def setNumberOfOpenEnds(self, int: int) -> "TubeRuptureRelief": ...
    def setSpecificHeatRatio(self, double: float) -> "TubeRuptureRelief": ...
    def setTubeInnerDiameterM(self, double: float) -> "TubeRuptureRelief": ...
    def setTubeInnerDiameterMm(self, double: float) -> "TubeRuptureRelief": ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.overpressure")``.

    AcceptanceResult: typing.Type[AcceptanceResult]
    BlockedOutletRelief: typing.Type[BlockedOutletRelief]
    CheckValveLeakRelief: typing.Type[CheckValveLeakRelief]
    ComplianceFinding: typing.Type[ComplianceFinding]
    ComplianceStatus: typing.Type[ComplianceStatus]
    ControlValveFailureRelief: typing.Type[ControlValveFailureRelief]
    FireCaseRelief: typing.Type[FireCaseRelief]
    OverpressureAcceptanceChecker: typing.Type[OverpressureAcceptanceChecker]
    OverpressureProtectionStudy: typing.Type[OverpressureProtectionStudy]
    OverpressureStudyResult: typing.Type[OverpressureStudyResult]
    PipelinePressureProtectionCalculator: typing.Type[
        PipelinePressureProtectionCalculator
    ]
    ProtectedItem: typing.Type[ProtectedItem]
    ReliefCause: typing.Type[ReliefCause]
    ReliefDisposalNetwork: typing.Type[ReliefDisposalNetwork]
    ReliefDisposalResult: typing.Type[ReliefDisposalResult]
    ReliefLoadContribution: typing.Type[ReliefLoadContribution]
    ReliefPhase: typing.Type[ReliefPhase]
    ReliefScenario: typing.Type[ReliefScenario]
    TR3001ComplianceChecker: typing.Type[TR3001ComplianceChecker]
    TubeRuptureRelief: typing.Type[TubeRuptureRelief]
