
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.nio.file
import java.util
import jpype.protocol
import jneqsim.process.equipment
import jneqsim.process.mechanicaldesign.designstandards
import jneqsim.process.processmodel
import typing



class TechnicalRequirementsDocument(java.io.Serializable):
    @staticmethod
    def builder() -> 'TechnicalRequirementsDocument.Builder': ...
    def getAllApplicableStandards(self, string: typing.Union[java.lang.String, str]) -> java.util.List[jneqsim.process.mechanicaldesign.designstandards.StandardType]: ...
    def getCompanyIdentifier(self) -> java.lang.String: ...
    _getCustomParameter_1__T = typing.TypeVar('_getCustomParameter_1__T')  # <T>
    @typing.overload
    def getCustomParameter(self, string: typing.Union[java.lang.String, str]) -> typing.Any: ...
    @typing.overload
    def getCustomParameter(self, string: typing.Union[java.lang.String, str], class_: typing.Type[_getCustomParameter_1__T]) -> _getCustomParameter_1__T: ...
    def getDefinedCategories(self) -> java.util.Set[java.lang.String]: ...
    def getEnvironmentalConditions(self) -> 'TechnicalRequirementsDocument.EnvironmentalConditions': ...
    def getIssueDate(self) -> java.lang.String: ...
    def getMaterialSpecifications(self) -> 'TechnicalRequirementsDocument.MaterialSpecifications': ...
    def getProjectId(self) -> java.lang.String: ...
    def getProjectName(self) -> java.lang.String: ...
    def getRevision(self) -> java.lang.String: ...
    def getSafetyFactors(self) -> 'TechnicalRequirementsDocument.SafetyFactors': ...
    def getStandardsForCategory(self, string: typing.Union[java.lang.String, str]) -> java.util.List[jneqsim.process.mechanicaldesign.designstandards.StandardType]: ...
    def getStandardsForEquipment(self, string: typing.Union[java.lang.String, str]) -> java.util.List[jneqsim.process.mechanicaldesign.designstandards.StandardType]: ...
    def hasStandardsForCategory(self, string: typing.Union[java.lang.String, str]) -> bool: ...
    def toString(self) -> java.lang.String: ...
    class Builder:
        def __init__(self): ...
        def addEquipmentStandard(self, string: typing.Union[java.lang.String, str], standardType: jneqsim.process.mechanicaldesign.designstandards.StandardType) -> 'TechnicalRequirementsDocument.Builder': ...
        def addStandard(self, string: typing.Union[java.lang.String, str], standardType: jneqsim.process.mechanicaldesign.designstandards.StandardType) -> 'TechnicalRequirementsDocument.Builder': ...
        def build(self) -> 'TechnicalRequirementsDocument': ...
        def companyIdentifier(self, string: typing.Union[java.lang.String, str]) -> 'TechnicalRequirementsDocument.Builder': ...
        def customParameter(self, string: typing.Union[java.lang.String, str], object: typing.Any) -> 'TechnicalRequirementsDocument.Builder': ...
        @typing.overload
        def environmentalConditions(self, double: float, double2: float) -> 'TechnicalRequirementsDocument.Builder': ...
        @typing.overload
        def environmentalConditions(self, environmentalConditions: 'TechnicalRequirementsDocument.EnvironmentalConditions') -> 'TechnicalRequirementsDocument.Builder': ...
        def issueDate(self, string: typing.Union[java.lang.String, str]) -> 'TechnicalRequirementsDocument.Builder': ...
        def materialSpecifications(self, materialSpecifications: 'TechnicalRequirementsDocument.MaterialSpecifications') -> 'TechnicalRequirementsDocument.Builder': ...
        def projectId(self, string: typing.Union[java.lang.String, str]) -> 'TechnicalRequirementsDocument.Builder': ...
        def projectName(self, string: typing.Union[java.lang.String, str]) -> 'TechnicalRequirementsDocument.Builder': ...
        def revision(self, string: typing.Union[java.lang.String, str]) -> 'TechnicalRequirementsDocument.Builder': ...
        def safetyFactors(self, safetyFactors: 'TechnicalRequirementsDocument.SafetyFactors') -> 'TechnicalRequirementsDocument.Builder': ...
        def setStandards(self, string: typing.Union[java.lang.String, str], list: java.util.List[jneqsim.process.mechanicaldesign.designstandards.StandardType]) -> 'TechnicalRequirementsDocument.Builder': ...
    class EnvironmentalConditions(java.io.Serializable):
        def __init__(self, double: float, double2: float, double3: float, string: typing.Union[java.lang.String, str], double4: float, double5: float, string2: typing.Union[java.lang.String, str]): ...
        def getDesignSeawaterTemperature(self) -> float: ...
        def getLocation(self) -> java.lang.String: ...
        def getMaxAmbientTemperature(self) -> float: ...
        def getMinAmbientTemperature(self) -> float: ...
        def getSeismicZone(self) -> java.lang.String: ...
        def getWaveHeight(self) -> float: ...
        def getWindSpeed(self) -> float: ...
    class MaterialSpecifications(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float, boolean: bool, string3: typing.Union[java.lang.String, str]): ...
        def getDefaultPipeMaterial(self) -> java.lang.String: ...
        def getDefaultPlateMaterial(self) -> java.lang.String: ...
        def getMaterialStandard(self) -> java.lang.String: ...
        def getMaxDesignTemperature(self) -> float: ...
        def getMinDesignTemperature(self) -> float: ...
        def isImpactTestingRequired(self) -> bool: ...
    class SafetyFactors(java.io.Serializable):
        def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float): ...
        def getCorrosionAllowance(self) -> float: ...
        def getLoadFactor(self) -> float: ...
        def getPressureSafetyFactor(self) -> float: ...
        def getTemperatureSafetyMargin(self) -> float: ...
        def getWallThicknessTolerance(self) -> float: ...

class TorgDataSource:
    def getAvailableCompanies(self) -> java.util.List[java.lang.String]: ...
    def getAvailableProjectIds(self) -> java.util.List[java.lang.String]: ...
    def hasProject(self, string: typing.Union[java.lang.String, str]) -> bool: ...
    def isWritable(self) -> bool: ...
    def loadByCompanyAndProject(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> java.util.Optional[TechnicalRequirementsDocument]: ...
    def loadByProjectId(self, string: typing.Union[java.lang.String, str]) -> java.util.Optional[TechnicalRequirementsDocument]: ...
    def store(self, technicalRequirementsDocument: TechnicalRequirementsDocument) -> bool: ...
    def update(self, technicalRequirementsDocument: TechnicalRequirementsDocument) -> bool: ...

class TorgManager:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, torgDataSource: TorgDataSource): ...
    def addDataSource(self, torgDataSource: TorgDataSource) -> 'TorgManager': ...
    def apply(self, technicalRequirementsDocument: TechnicalRequirementsDocument, processSystem: jneqsim.process.processmodel.ProcessSystem) -> None: ...
    def applyToEquipment(self, technicalRequirementsDocument: TechnicalRequirementsDocument, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    def generateSummary(self) -> java.lang.String: ...
    def getActiveTorg(self) -> TechnicalRequirementsDocument: ...
    def getAllAppliedStandards(self) -> java.util.Map[java.lang.String, java.util.List[jneqsim.process.mechanicaldesign.designstandards.StandardType]]: ...
    def getAppliedStandards(self, string: typing.Union[java.lang.String, str]) -> java.util.List[jneqsim.process.mechanicaldesign.designstandards.StandardType]: ...
    def getAvailableProjects(self) -> java.util.List[java.lang.String]: ...
    @typing.overload
    def load(self, string: typing.Union[java.lang.String, str]) -> java.util.Optional[TechnicalRequirementsDocument]: ...
    @typing.overload
    def load(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> java.util.Optional[TechnicalRequirementsDocument]: ...
    def loadAndApply(self, string: typing.Union[java.lang.String, str], processSystem: jneqsim.process.processmodel.ProcessSystem) -> bool: ...
    def reset(self) -> None: ...
    def setActiveTorg(self, technicalRequirementsDocument: TechnicalRequirementsDocument) -> None: ...

class CsvTorgDataSource(TorgDataSource):
    def __init__(self, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]): ...
    @staticmethod
    def fromResource(string: typing.Union[java.lang.String, str]) -> 'CsvTorgDataSource': ...
    def getAvailableCompanies(self) -> java.util.List[java.lang.String]: ...
    def getAvailableProjectIds(self) -> java.util.List[java.lang.String]: ...
    def loadByCompanyAndProject(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> java.util.Optional[TechnicalRequirementsDocument]: ...
    def loadByProjectId(self, string: typing.Union[java.lang.String, str]) -> java.util.Optional[TechnicalRequirementsDocument]: ...

class DatabaseTorgDataSource(TorgDataSource):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, boolean: bool): ...
    def getAvailableCompanies(self) -> java.util.List[java.lang.String]: ...
    def getAvailableProjectIds(self) -> java.util.List[java.lang.String]: ...
    def loadByCompanyAndProject(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> java.util.Optional[TechnicalRequirementsDocument]: ...
    def loadByProjectId(self, string: typing.Union[java.lang.String, str]) -> java.util.Optional[TechnicalRequirementsDocument]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.torg")``.

    CsvTorgDataSource: typing.Type[CsvTorgDataSource]
    DatabaseTorgDataSource: typing.Type[DatabaseTorgDataSource]
    TechnicalRequirementsDocument: typing.Type[TechnicalRequirementsDocument]
    TorgDataSource: typing.Type[TorgDataSource]
    TorgManager: typing.Type[TorgManager]
