
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import typing



class ElectricalCable(java.io.Serializable):
    def __init__(self): ...
    def calculateVoltageDrop(self, double: float, double2: float) -> float: ...
    def getAmpacityA(self) -> float: ...
    def getConductorMaterial(self) -> java.lang.String: ...
    def getCrossSectionMM2(self) -> float: ...
    def getEstimatedCostPerMeterUSD(self) -> float: ...
    def getInstallationMethod(self) -> java.lang.String: ...
    def getInsulationType(self) -> java.lang.String: ...
    def getLengthM(self) -> float: ...
    def getMaxVoltageDropPercent(self) -> float: ...
    def getNumberOfCores(self) -> int: ...
    def getRouteReference(self) -> java.lang.String: ...
    def getShortCircuitWithstandKA(self) -> float: ...
    def getTotalCostUSD(self) -> float: ...
    def getVoltageDropPercent(self) -> float: ...
    def setBurialDepthDeratingFactor(self, double: float) -> None: ...
    def setConductorMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setCrossSectionMM2(self, double: float) -> None: ...
    def setInstallationMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInsulationType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLengthM(self, double: float) -> None: ...
    def setMaxVoltageDropPercent(self, double: float) -> None: ...
    def setNumberOfCores(self, int: int) -> None: ...
    def setRouteReference(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def sizeCable(self, double: float, double2: float, double3: float, string: typing.Union[java.lang.String, str], double4: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class ElectricalMotor(java.io.Serializable):
    def __init__(self): ...
    def getDutyType(self) -> java.lang.String: ...
    def getEfficiencyAtLoad(self, double: float) -> float: ...
    def getEfficiencyClass(self) -> java.lang.String: ...
    def getEfficiencyPercent(self) -> float: ...
    def getEnclosureType(self) -> java.lang.String: ...
    def getEstimatedCostUSD(self) -> float: ...
    def getExProtection(self) -> java.lang.String: ...
    def getFrameSize(self) -> java.lang.String: ...
    def getFrequencyHz(self) -> float: ...
    def getGasGroup(self) -> java.lang.String: ...
    def getInsulationClass(self) -> java.lang.String: ...
    def getLockedRotorCurrentMultiplier(self) -> float: ...
    def getPoles(self) -> int: ...
    def getPowerFactorAtLoad(self, double: float) -> float: ...
    def getPowerFactorFL(self) -> float: ...
    def getRatedCurrentA(self) -> float: ...
    def getRatedPowerKW(self) -> float: ...
    def getRatedSpeedRPM(self) -> float: ...
    def getRatedVoltageV(self) -> float: ...
    def getServiceFactor(self) -> float: ...
    def getStartingMethod(self) -> java.lang.String: ...
    def getStartingTorquePercent(self) -> float: ...
    def getTemperatureClass(self) -> java.lang.String: ...
    def getWeightKg(self) -> float: ...
    def setDutyType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setEfficiencyClass(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setEfficiencyPercent(self, double: float) -> None: ...
    def setEnclosureType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setEstimatedCostUSD(self, double: float) -> None: ...
    def setExProtection(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setFrameSize(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setFrequencyHz(self, double: float) -> None: ...
    def setGasGroup(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInsulationClass(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLockedRotorCurrentMultiplier(self, double: float) -> None: ...
    def setPoles(self, int: int) -> None: ...
    def setPowerFactorFL(self, double: float) -> None: ...
    def setRatedCurrentA(self, double: float) -> None: ...
    def setRatedPowerKW(self, double: float) -> None: ...
    def setRatedSpeedRPM(self, double: float) -> None: ...
    def setRatedVoltageV(self, double: float) -> None: ...
    def setServiceFactor(self, double: float) -> None: ...
    def setStartingMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setStartingTorquePercent(self, double: float) -> None: ...
    def setTemperatureClass(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setWeightKg(self, double: float) -> None: ...
    def sizeMotor(self, double: float, double2: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class HazardousAreaClassification(java.io.Serializable):
    def __init__(self): ...
    def classify(self, string: typing.Union[java.lang.String, str], boolean: bool, double: float) -> None: ...
    def getClassificationStandard(self) -> java.lang.String: ...
    def getEquipmentProtectionLevel(self) -> java.lang.String: ...
    def getExMarking(self) -> java.lang.String: ...
    def getGasGroup(self) -> java.lang.String: ...
    def getRequiredExProtection(self) -> java.lang.String: ...
    def getTemperatureClass(self) -> java.lang.String: ...
    def getZone(self) -> java.lang.String: ...
    def setClassificationStandard(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setEquipmentProtectionLevel(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setGasGroup(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRequiredExProtection(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTemperatureClass(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setZone(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class Switchgear(java.io.Serializable):
    def __init__(self): ...
    def getCircuitBreakerRatingA(self) -> float: ...
    def getEstimatedCostUSD(self) -> float: ...
    def getFuseRatingA(self) -> float: ...
    def getRatedCurrentA(self) -> float: ...
    def getRatedVoltageV(self) -> float: ...
    def getShortCircuitCurrentKA(self) -> float: ...
    def getStarterType(self) -> java.lang.String: ...
    def getSwitchgearType(self) -> java.lang.String: ...
    def getWeightKg(self) -> float: ...
    def setShortCircuitCurrentKA(self, double: float) -> None: ...
    def setStarterType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def sizeSwitchgear(self, double: float, double2: float, double3: float, boolean: bool) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class Transformer(java.io.Serializable):
    def __init__(self): ...
    def getCoolingType(self) -> java.lang.String: ...
    def getEfficiencyPercent(self) -> float: ...
    def getEstimatedCostUSD(self) -> float: ...
    def getFrequencyHz(self) -> float: ...
    def getImpedancePercent(self) -> float: ...
    def getPrimaryVoltageV(self) -> float: ...
    def getRatedPowerKVA(self) -> float: ...
    def getSecondaryVoltageV(self) -> float: ...
    def getTotalLossKW(self) -> float: ...
    def getVectorGroup(self) -> java.lang.String: ...
    def getWeightKg(self) -> float: ...
    def setFrequencyHz(self, double: float) -> None: ...
    def setPrimaryVoltageV(self, double: float) -> None: ...
    def setRatedPowerKVA(self, double: float) -> None: ...
    def setSecondaryVoltageV(self, double: float) -> None: ...
    def setVectorGroup(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def sizeTransformer(self, double: float, double2: float, double3: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class VariableFrequencyDrive(java.io.Serializable):
    def __init__(self): ...
    def getCoolingMethod(self) -> java.lang.String: ...
    def getEfficiency(self, double: float, double2: float) -> float: ...
    def getEfficiencyPercent(self) -> float: ...
    def getElectricalInputKW(self, double: float) -> float: ...
    def getEnclosureRating(self) -> java.lang.String: ...
    def getEstimatedCostUSD(self) -> float: ...
    def getHeatDissipationKW(self) -> float: ...
    def getInputPowerFactor(self) -> float: ...
    def getInputVoltageV(self) -> float: ...
    def getMaxOutputFrequencyHz(self) -> float: ...
    def getMaxSpeedPercent(self) -> float: ...
    def getMinOutputFrequencyHz(self) -> float: ...
    def getMinSpeedPercent(self) -> float: ...
    def getOutputVoltageV(self) -> float: ...
    def getPulseConfiguration(self) -> java.lang.String: ...
    def getRatedCurrentA(self) -> float: ...
    def getRatedPowerKW(self) -> float: ...
    def getThdCurrentPercent(self) -> float: ...
    def getTopologyType(self) -> java.lang.String: ...
    def getWeightKg(self) -> float: ...
    def isHasActiveRectifier(self) -> bool: ...
    def isRequiresInputFilter(self) -> bool: ...
    def setCoolingMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setEfficiencyPercent(self, double: float) -> None: ...
    def setEnclosureRating(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setHasActiveRectifier(self, boolean: bool) -> None: ...
    def setInputPowerFactor(self, double: float) -> None: ...
    def setInputVoltageV(self, double: float) -> None: ...
    def setMaxOutputFrequencyHz(self, double: float) -> None: ...
    def setMaxSpeedPercent(self, double: float) -> None: ...
    def setMinOutputFrequencyHz(self, double: float) -> None: ...
    def setMinSpeedPercent(self, double: float) -> None: ...
    def setOutputVoltageV(self, double: float) -> None: ...
    def setPulseConfiguration(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRatedCurrentA(self, double: float) -> None: ...
    def setRatedPowerKW(self, double: float) -> None: ...
    def setRequiresInputFilter(self, boolean: bool) -> None: ...
    def setThdCurrentPercent(self, double: float) -> None: ...
    def setTopologyType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def sizeVFD(self, electricalMotor: ElectricalMotor) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.electricaldesign.components")``.

    ElectricalCable: typing.Type[ElectricalCable]
    ElectricalMotor: typing.Type[ElectricalMotor]
    HazardousAreaClassification: typing.Type[HazardousAreaClassification]
    Switchgear: typing.Type[Switchgear]
    Transformer: typing.Type[Transformer]
    VariableFrequencyDrive: typing.Type[VariableFrequencyDrive]
