import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.processmodel
import typing

class PortfolioRiskAnalyzer(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def addAsset(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        double: float,
    ) -> "PortfolioRiskAnalyzer.Asset": ...
    @typing.overload
    def addAsset(self, asset: "PortfolioRiskAnalyzer.Asset") -> None: ...
    def addCommonCauseScenario(
        self, commonCauseScenario: "PortfolioRiskAnalyzer.CommonCauseScenario"
    ) -> None: ...
    def createRegionalWeatherScenario(
        self, string: typing.Union[java.lang.String, str], double: float, double2: float
    ) -> "PortfolioRiskAnalyzer.CommonCauseScenario": ...
    def getAssets(self) -> java.util.List["PortfolioRiskAnalyzer.Asset"]: ...
    def getCommonCauseScenarios(
        self,
    ) -> java.util.List["PortfolioRiskAnalyzer.CommonCauseScenario"]: ...
    def getLastResult(self) -> "PortfolioRiskResult": ...
    def getName(self) -> java.lang.String: ...
    def run(self) -> "PortfolioRiskResult": ...
    def setNumberOfSimulations(self, int: int) -> None: ...
    def setSimulationPeriodYears(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toString(self) -> java.lang.String: ...

    class Asset(java.io.Serializable):
        def __init__(
            self,
            string: typing.Union[java.lang.String, str],
            string2: typing.Union[java.lang.String, str],
            double: float,
        ): ...
        def getAssetId(self) -> java.lang.String: ...
        def getAssetName(self) -> java.lang.String: ...
        def getAssetType(self) -> java.lang.String: ...
        def getExpectedProduction(self) -> float: ...
        def getExpectedProductionLoss(self) -> float: ...
        def getInsuranceValue(self) -> float: ...
        def getMaxProduction(self) -> float: ...
        def getRegion(self) -> java.lang.String: ...
        def getSystemAvailability(self) -> float: ...
        def runRiskSimulation(self, int: int) -> None: ...
        def setAssetType(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setExpectedProductionLoss(self, double: float) -> None: ...
        def setInsuranceValue(self, double: float) -> None: ...
        def setProcessSystem(
            self, processSystem: jneqsim.process.processmodel.ProcessSystem
        ) -> None: ...
        def setRegion(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setSystemAvailability(self, double: float) -> None: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

    class CommonCauseScenario(java.io.Serializable):
        def __init__(
            self,
            string: typing.Union[java.lang.String, str],
            string2: typing.Union[java.lang.String, str],
            commonCauseType: "PortfolioRiskAnalyzer.CommonCauseScenario.CommonCauseType",
            double: float,
        ): ...
        def addAffectedAsset(
            self, string: typing.Union[java.lang.String, str], double: float
        ) -> None: ...
        def getAffectedAssetIds(self) -> java.util.List[java.lang.String]: ...
        def getAssetImpact(
            self, string: typing.Union[java.lang.String, str]
        ) -> float: ...
        def getDescription(self) -> java.lang.String: ...
        def getDuration(self) -> float: ...
        def getFrequency(self) -> float: ...
        def getScenarioId(self) -> java.lang.String: ...
        def getType(
            self,
        ) -> "PortfolioRiskAnalyzer.CommonCauseScenario.CommonCauseType": ...
        def setDuration(self, double: float) -> None: ...
        def setFrequency(self, double: float) -> None: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

        class CommonCauseType(
            java.lang.Enum["PortfolioRiskAnalyzer.CommonCauseScenario.CommonCauseType"]
        ):
            WEATHER: typing.ClassVar[
                "PortfolioRiskAnalyzer.CommonCauseScenario.CommonCauseType"
            ] = ...
            REGIONAL_INFRASTRUCTURE: typing.ClassVar[
                "PortfolioRiskAnalyzer.CommonCauseScenario.CommonCauseType"
            ] = ...
            SUPPLY_CHAIN: typing.ClassVar[
                "PortfolioRiskAnalyzer.CommonCauseScenario.CommonCauseType"
            ] = ...
            MARKET: typing.ClassVar[
                "PortfolioRiskAnalyzer.CommonCauseScenario.CommonCauseType"
            ] = ...
            CYBER: typing.ClassVar[
                "PortfolioRiskAnalyzer.CommonCauseScenario.CommonCauseType"
            ] = ...
            PANDEMIC: typing.ClassVar[
                "PortfolioRiskAnalyzer.CommonCauseScenario.CommonCauseType"
            ] = ...
            GEOPOLITICAL: typing.ClassVar[
                "PortfolioRiskAnalyzer.CommonCauseScenario.CommonCauseType"
            ] = ...
            _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
            @typing.overload
            @staticmethod
            def valueOf(
                class_: typing.Type[_valueOf_0__T],
                string: typing.Union[java.lang.String, str],
            ) -> _valueOf_0__T: ...
            @typing.overload
            @staticmethod
            def valueOf(
                string: typing.Union[java.lang.String, str],
            ) -> "PortfolioRiskAnalyzer.CommonCauseScenario.CommonCauseType": ...
            @staticmethod
            def values() -> (
                typing.MutableSequence[
                    "PortfolioRiskAnalyzer.CommonCauseScenario.CommonCauseType"
                ]
            ): ...

class PortfolioRiskResult(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addAssetResult(
        self, assetResult: "PortfolioRiskResult.AssetResult"
    ) -> None: ...
    def getAnalysisName(self) -> java.lang.String: ...
    def getAssetResults(self) -> java.util.List["PortfolioRiskResult.AssetResult"]: ...
    def getCommonCauseFraction(self) -> float: ...
    def getDiversificationBenefit(self) -> float: ...
    def getExpectedCommonCauseLoss(self) -> float: ...
    def getExpectedPortfolioLoss(self) -> float: ...
    def getMaxPortfolioLoss(self) -> float: ...
    def getNumberOfSimulations(self) -> int: ...
    def getP10PortfolioLoss(self) -> float: ...
    def getP50PortfolioLoss(self) -> float: ...
    def getP90PortfolioLoss(self) -> float: ...
    def getP99PortfolioLoss(self) -> float: ...
    def getPortfolioAvailability(self) -> float: ...
    def getPortfolioLossStdDev(self) -> float: ...
    def getSimulationPeriodYears(self) -> float: ...
    def getTotalExpectedProduction(self) -> float: ...
    def getTotalMaxProduction(self) -> float: ...
    def getValueAtRisk(self, int: int) -> float: ...
    def setCommonCauseFraction(self, double: float) -> None: ...
    def setDiversificationBenefit(self, double: float) -> None: ...
    def setExpectedCommonCauseLoss(self, double: float) -> None: ...
    def setExpectedPortfolioLoss(self, double: float) -> None: ...
    def setMaxPortfolioLoss(self, double: float) -> None: ...
    def setNumberOfSimulations(self, int: int) -> None: ...
    def setP10PortfolioLoss(self, double: float) -> None: ...
    def setP50PortfolioLoss(self, double: float) -> None: ...
    def setP90PortfolioLoss(self, double: float) -> None: ...
    def setP99PortfolioLoss(self, double: float) -> None: ...
    def setPortfolioAvailability(self, double: float) -> None: ...
    def setPortfolioLossStdDev(self, double: float) -> None: ...
    def setSimulationPeriodYears(self, double: float) -> None: ...
    def setTotalExpectedProduction(self, double: float) -> None: ...
    def setTotalMaxProduction(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def toReport(self) -> java.lang.String: ...
    def toString(self) -> java.lang.String: ...

    class AssetResult(java.io.Serializable):
        def __init__(self): ...
        def getAssetId(self) -> java.lang.String: ...
        def getAssetName(self) -> java.lang.String: ...
        def getAvailability(self) -> float: ...
        def getContributionToPortfolioRisk(self) -> float: ...
        def getExpectedLoss(self) -> float: ...
        def getExpectedProduction(self) -> float: ...
        def getMaxProduction(self) -> float: ...
        def getP90Loss(self) -> float: ...
        def setAssetId(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setAssetName(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setAvailability(self, double: float) -> None: ...
        def setContributionToPortfolioRisk(self, double: float) -> None: ...
        def setExpectedLoss(self, double: float) -> None: ...
        def setExpectedProduction(self, double: float) -> None: ...
        def setMaxProduction(self, double: float) -> None: ...
        def setP90Loss(self, double: float) -> None: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.risk.portfolio")``.

    PortfolioRiskAnalyzer: typing.Type[PortfolioRiskAnalyzer]
    PortfolioRiskResult: typing.Type[PortfolioRiskResult]
