import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import jpype
import jneqsim.process.controllerdevice
import jneqsim.process.measurementdevice
import typing

class ControlStructureInterface(java.io.Serializable):
    def getOutput(self) -> float: ...
    def isActive(self) -> bool: ...
    def runTransient(self, double: float) -> None: ...
    def setActive(self, boolean: bool) -> None: ...

class CascadeControllerStructure(ControlStructureInterface):
    def __init__(
        self,
        controllerDeviceInterface: jneqsim.process.controllerdevice.ControllerDeviceInterface,
        controllerDeviceInterface2: jneqsim.process.controllerdevice.ControllerDeviceInterface,
    ): ...
    def getOutput(self) -> float: ...
    def isActive(self) -> bool: ...
    def runTransient(self, double: float) -> None: ...
    def setActive(self, boolean: bool) -> None: ...

class FeedForwardControllerStructure(ControlStructureInterface):
    def __init__(
        self,
        controllerDeviceInterface: jneqsim.process.controllerdevice.ControllerDeviceInterface,
        measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface,
    ): ...
    def getOutput(self) -> float: ...
    def isActive(self) -> bool: ...
    def runTransient(self, double: float) -> None: ...
    def setActive(self, boolean: bool) -> None: ...
    def setFeedForwardGain(self, double: float) -> None: ...

class OverrideControllerStructure(ControlStructureInterface):
    def __init__(
        self,
        controllerDeviceInterface: jneqsim.process.controllerdevice.ControllerDeviceInterface,
        controllerDeviceInterface2: jneqsim.process.controllerdevice.ControllerDeviceInterface,
        selectionType: "OverrideControllerStructure.SelectionType",
    ): ...
    def getOutput(self) -> float: ...
    def getSelectionType(self) -> "OverrideControllerStructure.SelectionType": ...
    def isActive(self) -> bool: ...
    def isOverrideActive(self) -> bool: ...
    def runTransient(self, double: float) -> None: ...
    def setActive(self, boolean: bool) -> None: ...

    class SelectionType(java.lang.Enum["OverrideControllerStructure.SelectionType"]):
        HIGH_SELECT: typing.ClassVar["OverrideControllerStructure.SelectionType"] = ...
        LOW_SELECT: typing.ClassVar["OverrideControllerStructure.SelectionType"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "OverrideControllerStructure.SelectionType": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["OverrideControllerStructure.SelectionType"]
        ): ...

class RatioControllerStructure(ControlStructureInterface):
    def __init__(
        self,
        controllerDeviceInterface: jneqsim.process.controllerdevice.ControllerDeviceInterface,
        measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface,
    ): ...
    def getOutput(self) -> float: ...
    def isActive(self) -> bool: ...
    def runTransient(self, double: float) -> None: ...
    def setActive(self, boolean: bool) -> None: ...
    def setRatio(self, double: float) -> None: ...

class SplitRangeControllerStructure(ControlStructureInterface):
    @typing.overload
    def __init__(
        self,
        controllerDeviceInterface: jneqsim.process.controllerdevice.ControllerDeviceInterface,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        doubleArray2: typing.Union[typing.List[float], jpype.JArray],
    ): ...
    @typing.overload
    def __init__(
        self,
        controllerDeviceInterface: jneqsim.process.controllerdevice.ControllerDeviceInterface,
        int: int,
    ): ...
    def getNumberOfElements(self) -> int: ...
    @typing.overload
    def getOutput(self) -> float: ...
    @typing.overload
    def getOutput(self, int: int) -> float: ...
    def isActive(self) -> bool: ...
    def runTransient(self, double: float) -> None: ...
    def setActive(self, boolean: bool) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.controllerdevice.structure")``.

    CascadeControllerStructure: typing.Type[CascadeControllerStructure]
    ControlStructureInterface: typing.Type[ControlStructureInterface]
    FeedForwardControllerStructure: typing.Type[FeedForwardControllerStructure]
    OverrideControllerStructure: typing.Type[OverrideControllerStructure]
    RatioControllerStructure: typing.Type[RatioControllerStructure]
    SplitRangeControllerStructure: typing.Type[SplitRangeControllerStructure]
