
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import typing



class WaxInhibitorPerformance(java.io.Serializable):
    def __init__(self): ...
    def evaluate(self) -> None: ...
    def getEfficacyFraction(self) -> float: ...
    def getInhibitedPourPointC(self) -> float: ...
    def getInhibitedWaxAppearanceTemperatureC(self) -> float: ...
    def getPourPointDepressionC(self) -> float: ...
    def getStandardsApplied(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def getYieldStressReductionFraction(self) -> float: ...
    def isEvaluated(self) -> bool: ...
    def setBasePourPointC(self, double: float) -> None: ...
    def setBaseWaxAppearanceTemperatureC(self, double: float) -> None: ...
    def setDoseAt50PctEfficacyMgL(self, double: float) -> None: ...
    def setDoseMgL(self, double: float) -> None: ...
    def setInhibitorChemistry(self, inhibitorChemistry: 'WaxInhibitorPerformance.InhibitorChemistry') -> None: ...
    def setMaxPourPointDepressionC(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class InhibitorChemistry(java.lang.Enum['WaxInhibitorPerformance.InhibitorChemistry']):
        EVA: typing.ClassVar['WaxInhibitorPerformance.InhibitorChemistry'] = ...
        POLY_ACRYLATE: typing.ClassVar['WaxInhibitorPerformance.InhibitorChemistry'] = ...
        OLEFIN_ESTER: typing.ClassVar['WaxInhibitorPerformance.InhibitorChemistry'] = ...
        MALEIC_VINYL_ESTER: typing.ClassVar['WaxInhibitorPerformance.InhibitorChemistry'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'WaxInhibitorPerformance.InhibitorChemistry': ...
        @staticmethod
        def values() -> typing.MutableSequence['WaxInhibitorPerformance.InhibitorChemistry']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.chemistry.wax")``.

    WaxInhibitorPerformance: typing.Type[WaxInhibitorPerformance]
