
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.safety.barrier
import jneqsim.process.safety.inventory
import jneqsim.process.safety.release
import jneqsim.thermo.system
import typing



class FireExposureScenario(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], fireType: 'FireExposureScenario.FireType', double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float): ...
    @staticmethod
    def api521PoolFire(double: float, double2: float) -> 'FireExposureScenario': ...
    @staticmethod
    def fixedHeatFlux(double: float, double2: float) -> 'FireExposureScenario': ...
    def getAmbientTemperatureK(self) -> float: ...
    def getExposedAreaM2(self) -> float: ...
    def getFireType(self) -> 'FireExposureScenario.FireType': ...
    def getName(self) -> java.lang.String: ...
    def getPassiveProtectionHeatFluxFactor(self) -> float: ...
    def heatInputW(self, double: float) -> float: ...
    def incidentHeatFlux(self, double: float) -> float: ...
    @staticmethod
    def radiativeFire(double: float, double2: float, double3: float, double4: float, double5: float) -> 'FireExposureScenario': ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def withPassiveProtectionFactor(self, double: float) -> 'FireExposureScenario': ...
    class FireType(java.lang.Enum['FireExposureScenario.FireType']):
        API_521_POOL_FIRE: typing.ClassVar['FireExposureScenario.FireType'] = ...
        FIXED_HEAT_FLUX: typing.ClassVar['FireExposureScenario.FireType'] = ...
        RADIATIVE_FIRE: typing.ClassVar['FireExposureScenario.FireType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FireExposureScenario.FireType': ...
        @staticmethod
        def values() -> typing.MutableSequence['FireExposureScenario.FireType']: ...

class MaterialStrengthCurve(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], string2: typing.Union[java.lang.String, str]): ...
    def allowableRuptureStressAt(self, double: float, double2: float) -> float: ...
    @staticmethod
    def carbonSteel(string: typing.Union[java.lang.String, str], double: float, double2: float) -> 'MaterialStrengthCurve': ...
    @staticmethod
    def forApi5LPipeGrade(string: typing.Union[java.lang.String, str]) -> 'MaterialStrengthCurve': ...
    def getAmbientTensileStrengthPa(self) -> float: ...
    def getAmbientYieldStrengthPa(self) -> float: ...
    def getDataSource(self) -> java.lang.String: ...
    def getMaterialName(self) -> java.lang.String: ...
    def retainedStrengthFactor(self, double: float) -> float: ...
    def tensileStrengthAt(self, double: float) -> float: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def yieldStrengthAt(self, double: float) -> float: ...

class TrappedLiquidFireRuptureResult(java.io.Serializable):
    def createRuptureSourceTerm(self, systemInterface: jneqsim.thermo.system.SystemInterface, releaseOrientation: jneqsim.process.safety.release.ReleaseOrientation, double: float, double2: float) -> jneqsim.process.safety.release.SourceTermResult: ...
    def getFinalLiquidTemperatureK(self) -> float: ...
    def getFinalOuterWallTemperatureK(self) -> float: ...
    def getFinalPressureBara(self) -> float: ...
    def getLimitingFailureMode(self) -> 'TrappedLiquidFireRuptureResult.FailureMode': ...
    def getMinimumFailureTimeSeconds(self) -> float: ...
    def getPressureBara(self) -> java.util.List[float]: ...
    def getRecommendations(self) -> java.util.List[java.lang.String]: ...
    def getSegmentId(self) -> java.lang.String: ...
    def getTimeSeconds(self) -> java.util.List[float]: ...
    def getTimeToFlangeFailureSeconds(self) -> float: ...
    def getTimeToPipeRuptureSeconds(self) -> float: ...
    def getTimeToReliefSetSeconds(self) -> float: ...
    def getTimeToVaporPocketSeconds(self) -> float: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isRupturePredicted(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def toPassiveFireProtectionDemand(self, string: typing.Union[java.lang.String, str], double: float) -> jneqsim.process.safety.barrier.SafetySystemDemand: ...
    class FailureMode(java.lang.Enum['TrappedLiquidFireRuptureResult.FailureMode']):
        NONE: typing.ClassVar['TrappedLiquidFireRuptureResult.FailureMode'] = ...
        RELIEF_SET_PRESSURE: typing.ClassVar['TrappedLiquidFireRuptureResult.FailureMode'] = ...
        VAPOR_POCKET: typing.ClassVar['TrappedLiquidFireRuptureResult.FailureMode'] = ...
        PIPE_RUPTURE: typing.ClassVar['TrappedLiquidFireRuptureResult.FailureMode'] = ...
        FLANGE_FAILURE: typing.ClassVar['TrappedLiquidFireRuptureResult.FailureMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TrappedLiquidFireRuptureResult.FailureMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['TrappedLiquidFireRuptureResult.FailureMode']: ...

class TrappedLiquidFireRuptureStudy(java.io.Serializable):
    @staticmethod
    def builder() -> 'TrappedLiquidFireRuptureStudy.Builder': ...
    def run(self) -> TrappedLiquidFireRuptureResult: ...
    class Builder:
        def __init__(self): ...
        def api5lMaterial(self, string: typing.Union[java.lang.String, str]) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def build(self) -> 'TrappedLiquidFireRuptureStudy': ...
        def fireScenario(self, fireExposureScenario: FireExposureScenario) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def flangeClass(self, int: int) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def fluid(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def heatTransferCoefficients(self, double: float, double2: float) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def inventory(self, inventoryResult: jneqsim.process.safety.inventory.TrappedInventoryCalculator.InventoryResult) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def liquidThermalProperties(self, double: float, double2: float, double3: float) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def material(self, materialStrengthCurve: MaterialStrengthCurve) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        @typing.overload
        def pipeGeometry(self, double: float, double2: float, double3: float) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        @typing.overload
        def pipeGeometry(self, double: float, string: typing.Union[java.lang.String, str], double2: float, string2: typing.Union[java.lang.String, str], double3: float, string3: typing.Union[java.lang.String, str]) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def reliefSetPressure(self, double: float, string: typing.Union[java.lang.String, str], boolean: bool) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def segmentId(self, string: typing.Union[java.lang.String, str]) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def tensileStrengthFactor(self, double: float) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def timeControls(self, double: float, double2: float) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def vaporPocketDetectionEnabled(self, boolean: bool) -> 'TrappedLiquidFireRuptureStudy.Builder': ...
        def wallThermalProperties(self, double: float, double2: float, double3: float) -> 'TrappedLiquidFireRuptureStudy.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.rupture")``.

    FireExposureScenario: typing.Type[FireExposureScenario]
    MaterialStrengthCurve: typing.Type[MaterialStrengthCurve]
    TrappedLiquidFireRuptureResult: typing.Type[TrappedLiquidFireRuptureResult]
    TrappedLiquidFireRuptureStudy: typing.Type[TrappedLiquidFireRuptureStudy]
