import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.equipment.stream
import jneqsim.pvtsimulation.flowassurance
import typing

class CorrosionInhibitorPerformance(java.io.Serializable):
    def __init__(self): ...
    def evaluate(self) -> None: ...
    @staticmethod
    def fromStream(
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
        double: float,
        double2: float,
    ) -> "CorrosionInhibitorPerformance": ...
    def getEfficiency(self) -> float: ...
    def getInhibitedCorrosionRateMmYr(self) -> float: ...
    def getMinimumEffectiveDoseMgL(self) -> float: ...
    def getStandardsApplied(
        self,
    ) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getWarnings(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def isEvaluated(self) -> bool: ...
    def setAcidicService(self, boolean: bool) -> None: ...
    def setBaseCorrosionRateMmYr(self, double: float) -> None: ...
    def setChemistry(
        self, inhibitorChemistry: "CorrosionInhibitorPerformance.InhibitorChemistry"
    ) -> None: ...
    def setDoseMgL(self, double: float) -> None: ...
    def setFromDeWaardMilliams(
        self,
        deWaardMilliamsCorrosion: jneqsim.pvtsimulation.flowassurance.DeWaardMilliamsCorrosion,
    ) -> None: ...
    def setH2SPartialPressureBar(self, double: float) -> None: ...
    def setOrganicAcidPpm(self, double: float) -> None: ...
    def setOxygenPpb(self, double: float) -> None: ...
    def setTemperatureCelsius(self, double: float) -> None: ...
    def setWallShearStressPa(self, double: float) -> None: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

    class InhibitorChemistry(
        java.lang.Enum["CorrosionInhibitorPerformance.InhibitorChemistry"]
    ):
        IMIDAZOLINE: typing.ClassVar[
            "CorrosionInhibitorPerformance.InhibitorChemistry"
        ] = ...
        QUATERNARY_AMMONIUM: typing.ClassVar[
            "CorrosionInhibitorPerformance.InhibitorChemistry"
        ] = ...
        AMIDO_AMINE: typing.ClassVar[
            "CorrosionInhibitorPerformance.InhibitorChemistry"
        ] = ...
        PHOSPHATE_ESTER: typing.ClassVar[
            "CorrosionInhibitorPerformance.InhibitorChemistry"
        ] = ...
        PYRIDINE: typing.ClassVar[
            "CorrosionInhibitorPerformance.InhibitorChemistry"
        ] = ...
        MERCAPTAN: typing.ClassVar[
            "CorrosionInhibitorPerformance.InhibitorChemistry"
        ] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "CorrosionInhibitorPerformance.InhibitorChemistry": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["CorrosionInhibitorPerformance.InhibitorChemistry"]
        ): ...

class LangmuirInhibitorIsotherm(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self, double: float, double2: float, double3: float, double4: float
    ): ...
    def getCoverage(self, double: float, double2: float) -> float: ...
    def getDoseForEfficiency(self, double: float, double2: float) -> float: ...
    def getEfficiency(self, double: float, double2: float) -> float: ...
    def getKAds(self, double: float) -> float: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class MechanisticCorrosionModel(java.io.Serializable):
    def __init__(self): ...
    def evaluate(self) -> "MechanisticCorrosionModel": ...
    def getInhibitedRateMmYr(self) -> float: ...
    def getInhibitorCoverage(self) -> float: ...
    def getInhibitorEfficiency(self) -> float: ...
    def getKineticRateMmYr(self) -> float: ...
    def getMassTransferLimitedRateMmYr(self) -> float: ...
    def getMixedControlRateMmYr(self) -> float: ...
    def getReynoldsNumber(self) -> float: ...
    def getSchmidtNumber(self) -> float: ...
    def getSherwoodNumber(self) -> float: ...
    def getStandardsApplied(
        self,
    ) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def isEvaluated(self) -> bool: ...
    def setFlow(
        self, double: float, double2: float, double3: float, double4: float
    ) -> "MechanisticCorrosionModel": ...
    def setGasComposition(
        self, double: float, double2: float
    ) -> "MechanisticCorrosionModel": ...
    def setInhibitor(
        self, langmuirInhibitorIsotherm: LangmuirInhibitorIsotherm, double: float
    ) -> "MechanisticCorrosionModel": ...
    def setTemperatureCelsius(self, double: float) -> "MechanisticCorrosionModel": ...
    def setTotalPressureBara(self, double: float) -> "MechanisticCorrosionModel": ...
    def setWaterChemistry(
        self, double: float, double2: float, double3: float
    ) -> "MechanisticCorrosionModel": ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.chemistry.corrosion")``.

    CorrosionInhibitorPerformance: typing.Type[CorrosionInhibitorPerformance]
    LangmuirInhibitorIsotherm: typing.Type[LangmuirInhibitorIsotherm]
    MechanisticCorrosionModel: typing.Type[MechanisticCorrosionModel]
