
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jpype
import jneqsim.thermo.phase
import org.netlib.util
import typing



class Leachman:
    def __init__(self): ...
    def DensityLeachman(self, int: int, double: float, double2: float, doubleW: org.netlib.util.doubleW, intW: org.netlib.util.intW, stringW: org.netlib.util.StringW) -> None: ...
    def PressureLeachman(self, double: float, double2: float, doubleW: org.netlib.util.doubleW, doubleW2: org.netlib.util.doubleW) -> None: ...
    @typing.overload
    def SetupLeachman(self) -> None: ...
    @typing.overload
    def SetupLeachman(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def propertiesLeachman(self, double: float, double2: float, doubleW: org.netlib.util.doubleW, doubleW2: org.netlib.util.doubleW, doubleW3: org.netlib.util.doubleW, doubleW4: org.netlib.util.doubleW, doubleW5: org.netlib.util.doubleW, doubleW6: org.netlib.util.doubleW, doubleW7: org.netlib.util.doubleW, doubleW8: org.netlib.util.doubleW, doubleW9: org.netlib.util.doubleW, doubleW10: org.netlib.util.doubleW, doubleW11: org.netlib.util.doubleW, doubleW12: org.netlib.util.doubleW, doubleW13: org.netlib.util.doubleW, doubleW14: org.netlib.util.doubleW, doubleW15: org.netlib.util.doubleW, doubleW16: org.netlib.util.doubleW) -> None: ...

class NeqSimLeachman:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, phaseInterface: jneqsim.thermo.phase.PhaseInterface, string: typing.Union[java.lang.String, str]): ...
    def getAlpha0_Leachman(self) -> typing.MutableSequence[org.netlib.util.doubleW]: ...
    def getAlphares_Leachman(self) -> typing.MutableSequence[typing.MutableSequence[org.netlib.util.doubleW]]: ...
    @typing.overload
    def getDensity(self) -> float: ...
    @typing.overload
    def getDensity(self, phaseInterface: jneqsim.thermo.phase.PhaseInterface) -> float: ...
    @typing.overload
    def getMolarDensity(self) -> float: ...
    @typing.overload
    def getMolarDensity(self, phaseInterface: jneqsim.thermo.phase.PhaseInterface) -> float: ...
    def getPressure(self) -> float: ...
    def getProperties(self, phaseInterface: jneqsim.thermo.phase.PhaseInterface, stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> typing.MutableSequence[float]: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @typing.overload
    def propertiesLeachman(self) -> typing.MutableSequence[float]: ...
    @typing.overload
    def propertiesLeachman(self, phaseInterface: jneqsim.thermo.phase.PhaseInterface) -> typing.MutableSequence[float]: ...
    def setPhase(self, phaseInterface: jneqsim.thermo.phase.PhaseInterface) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.thermo.util.leachman")``.

    Leachman: typing.Type[Leachman]
    NeqSimLeachman: typing.Type[NeqSimLeachman]
