
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.lang.annotation
import java.util
import jpype
import typing



class AIExposable(java.lang.annotation.Annotation):
    def category(self) -> java.lang.String: ...
    def description(self) -> java.lang.String: ...
    def equals(self, object: typing.Any) -> bool: ...
    def example(self) -> java.lang.String: ...
    def hashCode(self) -> int: ...
    def priority(self) -> int: ...
    def safe(self) -> bool: ...
    def tags(self) -> typing.MutableSequence[java.lang.String]: ...
    def toString(self) -> java.lang.String: ...

class AIParameter(java.lang.annotation.Annotation):
    def defaultValue(self) -> java.lang.String: ...
    def description(self) -> java.lang.String: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def maxValue(self) -> float: ...
    def minValue(self) -> float: ...
    def name(self) -> java.lang.String: ...
    def options(self) -> typing.MutableSequence[java.lang.String]: ...
    def required(self) -> bool: ...
    def toString(self) -> java.lang.String: ...
    def unit(self) -> java.lang.String: ...

class AISchemaDiscovery(java.io.Serializable):
    def __init__(self): ...
    def discoverCommonMethods(self, class_: typing.Type[typing.Any]) -> java.util.List['AISchemaDiscovery.MethodSchema']: ...
    def discoverCoreAPIs(self) -> java.util.Map[java.lang.String, java.util.List['AISchemaDiscovery.MethodSchema']]: ...
    def discoverMethods(self, class_: typing.Type[typing.Any]) -> java.util.List['AISchemaDiscovery.MethodSchema']: ...
    def generateMethodPrompt(self, list: java.util.List['AISchemaDiscovery.MethodSchema']) -> java.lang.String: ...
    def getQuickStartPrompt(self) -> java.lang.String: ...
    class MethodSchema(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str], int: int, boolean: bool, stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray], list: java.util.List['AISchemaDiscovery.ParameterSchema'], string7: typing.Union[java.lang.String, str]): ...
        def getCategory(self) -> java.lang.String: ...
        def getClassName(self) -> java.lang.String: ...
        def getDescription(self) -> java.lang.String: ...
        def getExample(self) -> java.lang.String: ...
        def getMethodName(self) -> java.lang.String: ...
        def getParameters(self) -> java.util.List['AISchemaDiscovery.ParameterSchema']: ...
        def getPriority(self) -> int: ...
        def getReturnType(self) -> java.lang.String: ...
        def getTags(self) -> typing.MutableSequence[java.lang.String]: ...
        def isSafe(self) -> bool: ...
        def toPromptText(self) -> java.lang.String: ...
    class ParameterSchema(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], double: float, double2: float, string5: typing.Union[java.lang.String, str], boolean: bool, stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]): ...
        def getName(self) -> java.lang.String: ...
        def getType(self) -> java.lang.String: ...
        def toPromptText(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.util.annotation")``.

    AIExposable: typing.Type[AIExposable]
    AIParameter: typing.Type[AIParameter]
    AISchemaDiscovery: typing.Type[AISchemaDiscovery]
