import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import jpype
import jneqsim.fluidmechanics.flownode
import jneqsim.fluidmechanics.flownode.multiphasenode.waxnode
import jneqsim.fluidmechanics.flownode.twophasenode
import jneqsim.fluidmechanics.geometrydefinitions
import jneqsim.thermo.system
import typing

class MultiPhaseFlowNode(jneqsim.fluidmechanics.flownode.FlowNode):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        geometryDefinitionInterface: jneqsim.fluidmechanics.geometrydefinitions.GeometryDefinitionInterface,
    ): ...
    def calcContactLength(self) -> float: ...
    def calcFluxes(self) -> None: ...
    def calcGasLiquidContactArea(self) -> float: ...
    def calcHydraulicDiameter(self) -> float: ...
    def calcReynoldNumber(self) -> float: ...
    def calcWallFrictionFactor(self) -> float: ...
    def clone(
        self,
    ) -> jneqsim.fluidmechanics.flownode.twophasenode.TwoPhaseFlowNode: ...
    def init(self) -> None: ...
    def initFlowCalc(self) -> None: ...
    def initVelocity(self) -> float: ...
    def setFluxes(
        self, doubleArray: typing.Union[typing.List[float], jpype.JArray]
    ) -> None: ...
    def update(self) -> None: ...
    def updateMolarFlow(self) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.fluidmechanics.flownode.multiphasenode")``.

    MultiPhaseFlowNode: typing.Type[MultiPhaseFlowNode]
    waxnode: jneqsim.fluidmechanics.flownode.multiphasenode.waxnode.__module_protocol__
