
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jneqsim.process.equipment
import jneqsim.process.equipment.valve
import jneqsim.process.logic
import typing



class PressureCondition(jneqsim.process.logic.LogicCondition):
    @typing.overload
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, double: float, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, double: float, string: typing.Union[java.lang.String, str], double2: float): ...
    def evaluate(self) -> bool: ...
    def getCurrentValue(self) -> java.lang.String: ...
    def getDescription(self) -> java.lang.String: ...
    def getExpectedValue(self) -> java.lang.String: ...
    def getTargetEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...

class TemperatureCondition(jneqsim.process.logic.LogicCondition):
    @typing.overload
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, double: float, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, double: float, string: typing.Union[java.lang.String, str], double2: float): ...
    def evaluate(self) -> bool: ...
    def getCurrentValue(self) -> java.lang.String: ...
    def getDescription(self) -> java.lang.String: ...
    def getExpectedValue(self) -> java.lang.String: ...
    def getTargetEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...

class TimerCondition(jneqsim.process.logic.LogicCondition):
    def __init__(self, double: float): ...
    def evaluate(self) -> bool: ...
    def getCurrentValue(self) -> java.lang.String: ...
    def getDescription(self) -> java.lang.String: ...
    def getElapsed(self) -> float: ...
    def getExpectedValue(self) -> java.lang.String: ...
    def getRemaining(self) -> float: ...
    def getTargetEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...
    def reset(self) -> None: ...
    def start(self) -> None: ...
    def update(self, double: float) -> None: ...

class ValvePositionCondition(jneqsim.process.logic.LogicCondition):
    @typing.overload
    def __init__(self, valveInterface: jneqsim.process.equipment.valve.ValveInterface, string: typing.Union[java.lang.String, str], double: float): ...
    @typing.overload
    def __init__(self, valveInterface: jneqsim.process.equipment.valve.ValveInterface, string: typing.Union[java.lang.String, str], double: float, double2: float): ...
    def evaluate(self) -> bool: ...
    def getCurrentValue(self) -> java.lang.String: ...
    def getDescription(self) -> java.lang.String: ...
    def getExpectedValue(self) -> java.lang.String: ...
    def getTargetEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.logic.condition")``.

    PressureCondition: typing.Type[PressureCondition]
    TemperatureCondition: typing.Type[TemperatureCondition]
    TimerCondition: typing.Type[TimerCondition]
    ValvePositionCondition: typing.Type[ValvePositionCondition]
