
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import neqsim.process.equipment
import neqsim.process.equipment.stream
import neqsim.process.util.report
import neqsim.thermo.system
import typing



class MixerInterface(neqsim.process.equipment.ProcessEquipmentInterface):
    def addStream(self, streamInterface: neqsim.process.equipment.stream.StreamInterface) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getOutStream(self) -> neqsim.process.equipment.stream.StreamInterface: ...
    def getOutletStream(self) -> neqsim.process.equipment.stream.StreamInterface: ...
    def getThermoSystem(self) -> neqsim.thermo.system.SystemInterface: ...
    def hashCode(self) -> int: ...
    def removeInputStream(self, int: int) -> None: ...
    def replaceStream(self, int: int, streamInterface: neqsim.process.equipment.stream.StreamInterface) -> None: ...

class Mixer(neqsim.process.equipment.ProcessEquipmentBaseClass, MixerInterface):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addStream(self, streamInterface: neqsim.process.equipment.stream.StreamInterface) -> None: ...
    def calcMixStreamEnthalpy(self) -> float: ...
    def displayResult(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getEntropyProduction(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getMassBalance(self) -> float: ...
    @typing.overload
    def getMassBalance(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMixedSalinity(self) -> float: ...
    def getMixedStream(self) -> neqsim.process.equipment.stream.StreamInterface: ...
    def getNumberOfInputStreams(self) -> int: ...
    def getOutTemperature(self) -> float: ...
    def getOutletStream(self) -> neqsim.process.equipment.stream.StreamInterface: ...
    def getStream(self, int: int) -> neqsim.process.equipment.stream.StreamInterface: ...
    def getThermoSystem(self) -> neqsim.thermo.system.SystemInterface: ...
    def guessTemperature(self) -> float: ...
    def hashCode(self) -> int: ...
    def isDoMultiPhaseCheck(self) -> bool: ...
    @typing.overload
    def isSetOutTemperature(self) -> bool: ...
    @typing.overload
    def isSetOutTemperature(self, boolean: bool) -> None: ...
    def mixStream(self) -> None: ...
    def removeInputStream(self, int: int) -> None: ...
    def replaceStream(self, int: int, streamInterface: neqsim.process.equipment.stream.StreamInterface) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setMultiPhaseCheck(self, boolean: bool) -> None: ...
    def setOutTemperature(self, double: float) -> None: ...
    def setPressure(self, double: float) -> None: ...
    def setTemperature(self, double: float) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(self, reportConfig: neqsim.process.util.report.ReportConfig) -> java.lang.String: ...

class StaticMixer(Mixer):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def calcMixStreamEnthalpy(self) -> float: ...
    def guessTemperature(self) -> float: ...
    def mixStream(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(self, reportConfig: neqsim.process.util.report.ReportConfig) -> java.lang.String: ...

class StaticNeqMixer(StaticMixer):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def mixStream(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...

class StaticPhaseMixer(StaticMixer):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def mixStream(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("neqsim.process.equipment.mixer")``.

    Mixer: typing.Type[Mixer]
    MixerInterface: typing.Type[MixerInterface]
    StaticMixer: typing.Type[StaticMixer]
    StaticNeqMixer: typing.Type[StaticNeqMixer]
    StaticPhaseMixer: typing.Type[StaticPhaseMixer]
