import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.chemistry.acid
import jneqsim.process.chemistry.asphaltene
import jneqsim.process.chemistry.corrosion
import jneqsim.process.chemistry.equipment
import jneqsim.process.chemistry.hydrate
import jneqsim.process.chemistry.rca
import jneqsim.process.chemistry.scale
import jneqsim.process.chemistry.scavenger
import jneqsim.process.chemistry.util
import jneqsim.process.chemistry.wax
import jneqsim.process.equipment.stream
import typing

class ChemicalCompatibilityAssessor(java.io.Serializable):
    def __init__(self): ...
    def addChemical(self, productionChemical: "ProductionChemical") -> None: ...
    def clearChemicals(self) -> None: ...
    def evaluate(self) -> None: ...
    @staticmethod
    def fromStream(
        streamInterface: jneqsim.process.equipment.stream.StreamInterface,
    ) -> "ChemicalCompatibilityAssessor": ...
    def getHighestSeverity(self) -> "ChemicalInteractionRule.Severity": ...
    def getInteractionMatrix(
        self,
    ) -> java.util.Map[
        java.lang.String, java.util.Map[java.lang.String, java.lang.String]
    ]: ...
    def getIssues(
        self,
    ) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getStandardsApplied(
        self,
    ) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def getThermalStability(self) -> java.util.Map[java.lang.String, bool]: ...
    def getVerdict(self) -> "ChemicalCompatibilityAssessor.Verdict": ...
    def isEvaluated(self) -> bool: ...
    def setBicarbonateMgL(self, double: float) -> None: ...
    def setCalciumMgL(self, double: float) -> None: ...
    def setIronMgL(self, double: float) -> None: ...
    def setMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPressureBara(self, double: float) -> None: ...
    def setRules(self, list: java.util.List["ChemicalInteractionRule"]) -> None: ...
    def setTemperatureCelsius(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

    class Verdict(java.lang.Enum["ChemicalCompatibilityAssessor.Verdict"]):
        COMPATIBLE: typing.ClassVar["ChemicalCompatibilityAssessor.Verdict"] = ...
        CAUTION: typing.ClassVar["ChemicalCompatibilityAssessor.Verdict"] = ...
        INCOMPATIBLE: typing.ClassVar["ChemicalCompatibilityAssessor.Verdict"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "ChemicalCompatibilityAssessor.Verdict": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["ChemicalCompatibilityAssessor.Verdict"]
        ): ...

class ChemicalInteractionRule(java.io.Serializable):
    DEFAULT_RESOURCE: typing.ClassVar[java.lang.String] = ...
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        string3: typing.Union[java.lang.String, str],
        string4: typing.Union[java.lang.String, str],
        string5: typing.Union[java.lang.String, str],
        severity: "ChemicalInteractionRule.Severity",
        string6: typing.Union[java.lang.String, str],
        string7: typing.Union[java.lang.String, str],
    ): ...
    def environmentMatches(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        string: typing.Union[java.lang.String, str],
    ) -> bool: ...
    def getChemical1Ingredient(self) -> java.lang.String: ...
    def getChemical1Type(self) -> java.lang.String: ...
    def getChemical2Ingredient(self) -> java.lang.String: ...
    def getChemical2Type(self) -> java.lang.String: ...
    def getCondition(self) -> java.lang.String: ...
    def getMechanism(self) -> java.lang.String: ...
    def getMitigation(self) -> java.lang.String: ...
    def getSeverity(self) -> "ChemicalInteractionRule.Severity": ...
    def isEnvironmentRule(self) -> bool: ...
    @staticmethod
    def loadDefaultRules() -> java.util.List["ChemicalInteractionRule"]: ...
    @staticmethod
    def loadFromResource(
        string: typing.Union[java.lang.String, str],
    ) -> java.util.List["ChemicalInteractionRule"]: ...
    def matches(
        self,
        productionChemical: "ProductionChemical",
        productionChemical2: "ProductionChemical",
    ) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

    class Severity(java.lang.Enum["ChemicalInteractionRule.Severity"]):
        HIGH: typing.ClassVar["ChemicalInteractionRule.Severity"] = ...
        MEDIUM: typing.ClassVar["ChemicalInteractionRule.Severity"] = ...
        LOW: typing.ClassVar["ChemicalInteractionRule.Severity"] = ...
        INFO: typing.ClassVar["ChemicalInteractionRule.Severity"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "ChemicalInteractionRule.Severity": ...
        @staticmethod
        def values() -> typing.MutableSequence["ChemicalInteractionRule.Severity"]: ...

class ProductionChemical(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        chemicalType: "ProductionChemical.ChemicalType",
    ): ...
    @staticmethod
    def acid(
        string: typing.Union[java.lang.String, str], double: float
    ) -> "ProductionChemical": ...
    @staticmethod
    def corrosionInhibitor(
        string: typing.Union[java.lang.String, str], double: float
    ) -> "ProductionChemical": ...
    def getActiveIngredient(self) -> java.lang.String: ...
    def getActiveWtPct(self) -> float: ...
    def getDensityKgM3(self) -> float: ...
    def getDosagePpm(self) -> float: ...
    def getIonicNature(self) -> "ProductionChemical.IonicNature": ...
    def getMaxTemperatureC(self) -> float: ...
    def getMinTemperatureC(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getNotes(self) -> java.lang.String: ...
    def getPH(self) -> float: ...
    def getSolvent(self) -> java.lang.String: ...
    def getType(self) -> "ProductionChemical.ChemicalType": ...
    @staticmethod
    def h2sScavenger(
        string: typing.Union[java.lang.String, str], double: float
    ) -> "ProductionChemical": ...
    def isStableAt(self, double: float) -> bool: ...
    @staticmethod
    def scaleInhibitor(
        string: typing.Union[java.lang.String, str], double: float
    ) -> "ProductionChemical": ...
    def setActiveIngredient(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setActiveWtPct(self, double: float) -> None: ...
    def setDensityKgM3(self, double: float) -> None: ...
    def setDosagePpm(self, double: float) -> None: ...
    def setIonicNature(self, ionicNature: "ProductionChemical.IonicNature") -> None: ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setNotes(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPH(self, double: float) -> None: ...
    def setSolvent(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTemperatureRangeC(self, double: float, double2: float) -> None: ...
    def setType(self, chemicalType: "ProductionChemical.ChemicalType") -> None: ...
    @staticmethod
    def thermodynamicHydrateInhibitor(
        string: typing.Union[java.lang.String, str], double: float
    ) -> "ProductionChemical": ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def toString(self) -> java.lang.String: ...

    class ChemicalType(java.lang.Enum["ProductionChemical.ChemicalType"]):
        SCALE_INHIBITOR: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        CORROSION_INHIBITOR: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        HYDRATE_INHIBITOR_THERMODYNAMIC: typing.ClassVar[
            "ProductionChemical.ChemicalType"
        ] = ...
        HYDRATE_INHIBITOR_LDHI: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        DEMULSIFIER: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        WAX_INHIBITOR: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        ASPHALTENE_INHIBITOR: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        BIOCIDE: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        OXYGEN_SCAVENGER: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        H2S_SCAVENGER: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        ANTIFOAM: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        DRAG_REDUCER: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        PH_ADJUSTER: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        ACID: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        CHELANT: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        OTHER: typing.ClassVar["ProductionChemical.ChemicalType"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "ProductionChemical.ChemicalType": ...
        @staticmethod
        def values() -> typing.MutableSequence["ProductionChemical.ChemicalType"]: ...

    class IonicNature(java.lang.Enum["ProductionChemical.IonicNature"]):
        CATIONIC: typing.ClassVar["ProductionChemical.IonicNature"] = ...
        ANIONIC: typing.ClassVar["ProductionChemical.IonicNature"] = ...
        NON_IONIC: typing.ClassVar["ProductionChemical.IonicNature"] = ...
        AMPHOTERIC: typing.ClassVar["ProductionChemical.IonicNature"] = ...
        UNKNOWN: typing.ClassVar["ProductionChemical.IonicNature"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "ProductionChemical.IonicNature": ...
        @staticmethod
        def values() -> typing.MutableSequence["ProductionChemical.IonicNature"]: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.chemistry")``.

    ChemicalCompatibilityAssessor: typing.Type[ChemicalCompatibilityAssessor]
    ChemicalInteractionRule: typing.Type[ChemicalInteractionRule]
    ProductionChemical: typing.Type[ProductionChemical]
    acid: jneqsim.process.chemistry.acid.__module_protocol__
    asphaltene: jneqsim.process.chemistry.asphaltene.__module_protocol__
    corrosion: jneqsim.process.chemistry.corrosion.__module_protocol__
    equipment: jneqsim.process.chemistry.equipment.__module_protocol__
    hydrate: jneqsim.process.chemistry.hydrate.__module_protocol__
    rca: jneqsim.process.chemistry.rca.__module_protocol__
    scale: jneqsim.process.chemistry.scale.__module_protocol__
    scavenger: jneqsim.process.chemistry.scavenger.__module_protocol__
    util: jneqsim.process.chemistry.util.__module_protocol__
    wax: jneqsim.process.chemistry.wax.__module_protocol__
