
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.capacity
import jneqsim.process.equipment.compressor
import jneqsim.process.equipment.expander
import jneqsim.process.equipment.heatexchanger
import jneqsim.process.equipment.stream
import jneqsim.process.processmodel
import jneqsim.thermo.system
import typing



class LNGProcessBenchmark:
    @staticmethod
    def assess(lNGProcessCycle: 'LNGProcessCycle', result: 'LNGProcessModel.Result') -> 'LNGProcessBenchmark.Assessment': ...
    @staticmethod
    def get(lNGProcessCycle: 'LNGProcessCycle') -> 'LNGProcessBenchmark.Benchmark': ...
    @staticmethod
    def getAll() -> java.util.Map['LNGProcessCycle', 'LNGProcessBenchmark.Benchmark']: ...
    class Assessment(java.io.Serializable):
        def getMessages(self) -> java.util.List[java.lang.String]: ...
        def getSpecificEnergyDeviation(self) -> float: ...
        def isEnergyWithinRange(self) -> bool: ...
        def isProductTemperatureWithinRange(self) -> bool: ...
        def isTemperatureApproachValid(self) -> bool: ...
        def isWithinRange(self) -> bool: ...
        def isYieldWithinRange(self) -> bool: ...
    class Benchmark(java.io.Serializable):
        def getMaximumProductTemperatureC(self) -> float: ...
        def getMaximumSpecificEnergy(self) -> float: ...
        def getMinimumLNGYield(self) -> float: ...
        def getMinimumProductTemperatureC(self) -> float: ...
        def getMinimumSpecificEnergy(self) -> float: ...
        def getReferenceSpecificEnergy(self) -> float: ...
        def getSource(self) -> java.lang.String: ...

class LNGProcessBuilder:
    def __init__(self): ...
    def build(self) -> 'LNGProcessModel': ...
    def setAdaptiveRefinement(self, boolean: bool) -> 'LNGProcessBuilder': ...
    def setCompressorEfficiency(self, double: float) -> 'LNGProcessBuilder': ...
    def setCycle(self, lNGProcessCycle: 'LNGProcessCycle') -> 'LNGProcessBuilder': ...
    def setExpanderEfficiency(self, double: float) -> 'LNGProcessBuilder': ...
    def setFeedFlowRate(self, double: float) -> 'LNGProcessBuilder': ...
    def setFeedFluid(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> 'LNGProcessBuilder': ...
    def setFeedPressure(self, double: float) -> 'LNGProcessBuilder': ...
    def setFeedStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> 'LNGProcessBuilder': ...
    def setFeedTemperature(self, double: float) -> 'LNGProcessBuilder': ...
    def setMinimumApproach(self, double: float) -> 'LNGProcessBuilder': ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> 'LNGProcessBuilder': ...
    def setNumberOfZones(self, int: int) -> 'LNGProcessBuilder': ...
    def setProductPressure(self, double: float) -> 'LNGProcessBuilder': ...
    def setRefrigerantCirculationRatio(self, double: float) -> 'LNGProcessBuilder': ...
    def setRefrigerantComposition(self, stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> 'LNGProcessBuilder': ...
    def setRefrigerantCoolingTemperature(self, double: float) -> 'LNGProcessBuilder': ...
    def setRefrigerantDischargePressure(self, double: float) -> 'LNGProcessBuilder': ...
    def setRefrigerantSuctionPressure(self, double: float) -> 'LNGProcessBuilder': ...
    def setTargetLiquefactionTemperature(self, double: float) -> 'LNGProcessBuilder': ...
    def setUpstreamProcess(self, processSystem: jneqsim.process.processmodel.ProcessSystem, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> 'LNGProcessBuilder': ...
    def setUseFlashWarmStart(self, boolean: bool) -> 'LNGProcessBuilder': ...

class LNGProcessCycle(java.lang.Enum['LNGProcessCycle']):
    SMR: typing.ClassVar['LNGProcessCycle'] = ...
    C3MR: typing.ClassVar['LNGProcessCycle'] = ...
    DMR: typing.ClassVar['LNGProcessCycle'] = ...
    NITROGEN_EXPANDER: typing.ClassVar['LNGProcessCycle'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'LNGProcessCycle': ...
    @staticmethod
    def values() -> typing.MutableSequence['LNGProcessCycle']: ...

class LNGProcessModel(java.io.Serializable):
    LNG_OUTPUT: typing.ClassVar[java.lang.String] = ...
    FLASH_GAS_OUTPUT: typing.ClassVar[java.lang.String] = ...
    def addEquipment(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> 'LNGProcessModel': ...
    def autoSizeAndEvaluateCapacity(self, double: float) -> 'LNGProcessModel.CapacityResult': ...
    def evaluate(self) -> 'LNGProcessModel.Result': ...
    def evaluateCapacity(self) -> 'LNGProcessModel.CapacityResult': ...
    def getCompressors(self) -> java.util.List[jneqsim.process.equipment.compressor.Compressor]: ...
    def getCryogenicHeatExchangers(self) -> java.util.List[jneqsim.process.equipment.heatexchanger.LNGHeatExchanger]: ...
    def getCycle(self) -> LNGProcessCycle: ...
    _getEquipment_1__T = typing.TypeVar('_getEquipment_1__T', bound=jneqsim.process.equipment.ProcessEquipmentInterface)  # <T>
    @typing.overload
    def getEquipment(self) -> java.util.List[jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    @typing.overload
    def getEquipment(self, class_: typing.Type[_getEquipment_1__T]) -> java.util.List[_getEquipment_1__T]: ...
    def getExpanders(self) -> java.util.List[jneqsim.process.equipment.expander.Expander]: ...
    def getFeedStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getFlashGasStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getLastResult(self) -> 'LNGProcessModel.Result': ...
    def getName(self) -> java.lang.String: ...
    def getOutputStream(self, string: typing.Union[java.lang.String, str]) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOutputStreams(self) -> java.util.Map[java.lang.String, jneqsim.process.equipment.stream.StreamInterface]: ...
    def getProcessSystem(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getProductStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def registerOutputStream(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> 'LNGProcessModel': ...
    def run(self) -> 'LNGProcessModel.Result': ...
    def toJson(self) -> java.lang.String: ...
    class CapacityResult(java.io.Serializable):
        def getAutoSizedEquipmentCount(self) -> int: ...
        def getBottleneck(self) -> jneqsim.process.equipment.capacity.BottleneckResult: ...
        def getDerivedConstraintCount(self) -> int: ...
        def getDesignReportJson(self) -> java.lang.String: ...
        def getEquipmentNearCapacityLimit(self) -> java.util.List[java.lang.String]: ...
        def getRankedUtilizationPercent(self) -> java.util.Map[java.lang.String, float]: ...
        def getUtilizationSnapshotJson(self) -> java.lang.String: ...
        def isAnyEquipmentOverloaded(self) -> bool: ...
        def isAnyHardLimitExceeded(self) -> bool: ...
    class Result(java.io.Serializable):
        def assessBenchmark(self) -> LNGProcessBenchmark.Assessment: ...
        def getCapacityMTPA(self) -> float: ...
        def getCompressorPowerKW(self) -> float: ...
        def getCycle(self) -> LNGProcessCycle: ...
        def getExchangerExergyDestructionKW(self) -> float: ...
        def getExpanderRecoveredPowerKW(self) -> float: ...
        def getFeedMassFlowKgPerHour(self) -> float: ...
        def getLNGMassFlowKgPerHour(self) -> float: ...
        def getLNGYield(self) -> float: ...
        def getMinimumInternalTemperatureApproachC(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getNetPowerKW(self) -> float: ...
        def getProductDensityKgPerM3(self) -> float: ...
        def getProductPressureBara(self) -> float: ...
        def getProductTemperatureC(self) -> float: ...
        def getRunTimeMilliseconds(self) -> float: ...
        def getSpecificEnergyKWhPerKgLNG(self) -> float: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.lng")``.

    LNGProcessBenchmark: typing.Type[LNGProcessBenchmark]
    LNGProcessBuilder: typing.Type[LNGProcessBuilder]
    LNGProcessCycle: typing.Type[LNGProcessCycle]
    LNGProcessModel: typing.Type[LNGProcessModel]
