
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jpype
import jneqsim.thermo.system
import jneqsim.thermodynamicoperations
import typing



class OLGApropertyTableGenerator(jneqsim.thermodynamicoperations.BaseOperation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcPhaseEnvelope(self) -> None: ...
    def displayResult(self) -> None: ...
    def run(self) -> None: ...
    def setPressureRange(self, double: float, double2: float, int: int) -> None: ...
    def setTemperatureRange(self, double: float, double2: float, int: int) -> None: ...
    def writeOLGAinpFile(self, string: typing.Union[java.lang.String, str]) -> None: ...

class OLGApropertyTableGeneratorKeywordFormat(jneqsim.thermodynamicoperations.BaseOperation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcBubP(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcBubT(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcDewP(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcPhaseEnvelope(self) -> None: ...
    def displayResult(self) -> None: ...
    def initCalc(self) -> None: ...
    def run(self) -> None: ...
    def setPressureRange(self, double: float, double2: float, int: int) -> None: ...
    def setTemperatureRange(self, double: float, double2: float, int: int) -> None: ...
    def writeOLGAinpFile(self, string: typing.Union[java.lang.String, str]) -> None: ...

class OLGApropertyTableGeneratorWater(jneqsim.thermodynamicoperations.BaseOperation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcBubP(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcBubT(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcDewP(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcPhaseEnvelope(self) -> None: ...
    def calcRSWTOB(self) -> None: ...
    def displayResult(self) -> None: ...
    def extrapolateTable(self) -> None: ...
    def initCalc(self) -> None: ...
    def run(self) -> None: ...
    def setFileName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPressureRange(self, double: float, double2: float, int: int) -> None: ...
    def setTemperatureRange(self, double: float, double2: float, int: int) -> None: ...
    def writeOLGAinpFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def writeOLGAinpFile2(self, string: typing.Union[java.lang.String, str]) -> None: ...

class OLGApropertyTableGeneratorWaterEven(jneqsim.thermodynamicoperations.BaseOperation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcBubP(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcBubT(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcDewP(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcPhaseEnvelope(self) -> None: ...
    def calcRSWTOB(self) -> None: ...
    def displayResult(self) -> None: ...
    def extrapolateTable(self) -> None: ...
    def initCalc(self) -> None: ...
    def run(self) -> None: ...
    def setFileName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPressureRange(self, double: float, double2: float, int: int) -> None: ...
    def setTemperatureRange(self, double: float, double2: float, int: int) -> None: ...
    def writeOLGAinpFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def writeOLGAinpFile2(self, string: typing.Union[java.lang.String, str]) -> None: ...

class OLGApropertyTableGeneratorWaterKeywordFormat(jneqsim.thermodynamicoperations.BaseOperation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcBubP(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcBubT(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcDewP(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcPhaseEnvelope(self) -> None: ...
    def calcRSWTOB(self) -> None: ...
    def displayResult(self) -> None: ...
    def initCalc(self) -> None: ...
    def run(self) -> None: ...
    def setPressureRange(self, double: float, double2: float, int: int) -> None: ...
    def setTemperatureRange(self, double: float, double2: float, int: int) -> None: ...
    def writeOLGAinpFile(self, string: typing.Union[java.lang.String, str]) -> None: ...

class OLGApropertyTableGeneratorWaterStudents(jneqsim.thermodynamicoperations.BaseOperation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcBubP(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcBubT(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcDewP(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcPhaseEnvelope(self) -> None: ...
    def calcRSWTOB(self) -> None: ...
    def displayResult(self) -> None: ...
    def extrapolateTable(self) -> None: ...
    def initCalc(self) -> None: ...
    def run(self) -> None: ...
    def setFileName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPressureRange(self, double: float, double2: float, int: int) -> None: ...
    def setTemperatureRange(self, double: float, double2: float, int: int) -> None: ...
    def writeOLGAinpFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def writeOLGAinpFile2(self, string: typing.Union[java.lang.String, str]) -> None: ...

class OLGApropertyTableGeneratorWaterStudentsPH(jneqsim.thermodynamicoperations.BaseOperation):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcBubP(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcBubT(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcDewP(self, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    def calcPhaseEnvelope(self) -> None: ...
    def calcRSWTOB(self) -> None: ...
    def displayResult(self) -> None: ...
    def extrapolateTable(self) -> None: ...
    def initCalc(self) -> None: ...
    def run(self) -> None: ...
    def setEnthalpyRange(self, double: float, double2: float, int: int) -> None: ...
    def setFileName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPressureRange(self, double: float, double2: float, int: int) -> None: ...
    def writeOLGAinpFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def writeOLGAinpFile2(self, string: typing.Union[java.lang.String, str]) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.thermodynamicoperations.propertygenerator")``.

    OLGApropertyTableGenerator: typing.Type[OLGApropertyTableGenerator]
    OLGApropertyTableGeneratorKeywordFormat: typing.Type[OLGApropertyTableGeneratorKeywordFormat]
    OLGApropertyTableGeneratorWater: typing.Type[OLGApropertyTableGeneratorWater]
    OLGApropertyTableGeneratorWaterEven: typing.Type[OLGApropertyTableGeneratorWaterEven]
    OLGApropertyTableGeneratorWaterKeywordFormat: typing.Type[OLGApropertyTableGeneratorWaterKeywordFormat]
    OLGApropertyTableGeneratorWaterStudents: typing.Type[OLGApropertyTableGeneratorWaterStudents]
    OLGApropertyTableGeneratorWaterStudentsPH: typing.Type[OLGApropertyTableGeneratorWaterStudentsPH]
