
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.thermo
import jneqsim.thermo.phase
import jneqsim.thermo.system
import jneqsim.thermodynamicoperations
import org.jfree.chart
import typing



class CalciumSulfatePhaseBoundaryQualification(java.io.Serializable):
    REFERENCE_PRESSURE_BARA: typing.ClassVar[float] = ...
    EVIDENCE_DOI: typing.ClassVar[java.lang.String] = ...
    PRIMARY_LINEAGE_DOI: typing.ClassVar[java.lang.String] = ...
    HIGH_PRESSURE_LINEAGE_DOI: typing.ClassVar[java.lang.String] = ...
    EVIDENCE_LICENSE: typing.ClassVar[java.lang.String] = ...
    COMPSALT_PRESSURE_CORRECTION_REFERENCE_BARA: typing.ClassVar[float] = ...
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def formatDiagnostic(self) -> java.lang.String: ...
    def getAnhydriteLogKspPressureCorrection(self) -> float: ...
    def getAnhydriteLumpedReactionVolumeCm3PerMol(self) -> float: ...
    def getDecision(self) -> java.lang.String: ...
    def getEvaluatedPressureBara(self) -> float: ...
    def getEvaluatedTemperatureKelvin(self) -> float: ...
    def getEvidenceDoi(self) -> java.lang.String: ...
    def getEvidenceLicense(self) -> java.lang.String: ...
    def getGypsumLogKspPressureCorrection(self) -> float: ...
    def getGypsumLumpedReactionVolumeCm3PerMol(self) -> float: ...
    def getHighPressureLineageDoi(self) -> java.lang.String: ...
    def getLimitations(self) -> java.util.List[java.lang.String]: ...
    def getPredictedPureWaterTransitionAtEvaluatedPressureCelsius(self) -> float: ...
    def getPredictedPureWaterTransitionCelsius(self) -> float: ...
    def getPrimaryLineageDoi(self) -> java.lang.String: ...
    def getPureWaterEvidenceMaximumCelsius(self) -> float: ...
    def getPureWaterEvidenceMinimumCelsius(self) -> float: ...
    def getRequiredWaterActivityAt25Celsius(self) -> float: ...
    def getRequiredWaterActivityAt40Celsius(self) -> float: ...
    def getSodiumChloride25CWaterActivityMaximum(self) -> float: ...
    def getSodiumChloride25CWaterActivityMinimum(self) -> float: ...
    def getSodiumChloride40CWaterActivityMaximum(self) -> float: ...
    def getSodiumChloride40CWaterActivityMinimum(self) -> float: ...
    def isAqueousSpeciesVolumeResolved(self) -> bool: ...
    def isHighPressureQualified(self) -> bool: ...
    def isPublicationReady(self) -> bool: ...
    def isPureWaterEnvelopePass(self) -> bool: ...
    def isReferencePressureEnvelopePass(self) -> bool: ...
    def isSodiumChloride25CEnvelopePass(self) -> bool: ...
    def isSodiumChloride40CEnvelopePass(self) -> bool: ...

class ConstantDutyFlashInterface(jneqsim.thermodynamicoperations.OperationInterface):
    def isSuperCritical(self) -> bool: ...

class CricondenBarTemp(java.io.Serializable):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, int: int, int2: int): ...
    def init(self) -> None: ...
    def setJac(self) -> None: ...
    def setfvec(self) -> None: ...
    def setu(self) -> None: ...
    def solve(self) -> float: ...

class CricondenBarTemp1(java.io.Serializable):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def displayResult(self) -> None: ...
    def get(self, string: typing.Union[java.lang.String, str]) -> typing.MutableSequence[float]: ...
    def getJFreeChart(self, string: typing.Union[java.lang.String, str]) -> org.jfree.chart.JFreeChart: ...
    def getPoints(self, int: int) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getResultTable(self) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def init(self) -> None: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def setJac(self) -> None: ...
    def setfvec(self) -> None: ...
    def setu(self) -> None: ...
    def solve(self) -> float: ...

class ElectrolytePhaseBoundaryFlash:
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, specification: 'ElectrolytePhaseBoundaryResult.Specification', phaseType: jneqsim.thermo.phase.PhaseType, double: float, double2: float, double3: float, int: int): ...
    def solve(self) -> 'ElectrolytePhaseBoundaryResult': ...

class ElectrolytePhaseBoundaryResult(java.io.Serializable):
    @typing.overload
    def __init__(self, specification: 'ElectrolytePhaseBoundaryResult.Specification', phaseType: jneqsim.thermo.phase.PhaseType, double: float, double2: float, boolean: bool, double3: float, double4: float, int: int, int2: int, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double5: float, double6: float, double7: float, double8: float, double9: float): ...
    @typing.overload
    def __init__(self, specification: 'ElectrolytePhaseBoundaryResult.Specification', phaseType: jneqsim.thermo.phase.PhaseType, double: float, double2: float, boolean: bool, double3: float, double4: float, int: int, int2: int, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double5: float, double6: float, double7: float, double8: float, double9: float, double10: float, double11: float): ...
    def getAqueousChargeMolality(self) -> float: ...
    def getBoundaryValue(self) -> float: ...
    def getBracketWidth(self) -> float: ...
    def getFlashEvaluations(self) -> int: ...
    def getIterations(self) -> int: ...
    def getLowerBound(self) -> float: ...
    def getLowerTopology(self) -> java.lang.String: ...
    def getMaximumAbsoluteElementBalanceResidual(self) -> float: ...
    def getMaximumAbsoluteReactionLogResidual(self) -> float: ...
    def getMaximumIonMoleFractionOutsideAqueous(self) -> float: ...
    def getMaximumLogFugacityResidual(self) -> float: ...
    def getMaximumMaterialBalanceResidual(self) -> float: ...
    def getMaximumPhaseNormalizationResidual(self) -> float: ...
    def getSpecification(self) -> 'ElectrolytePhaseBoundaryResult.Specification': ...
    def getTargetPhase(self) -> jneqsim.thermo.phase.PhaseType: ...
    def getTargetPhaseFraction(self) -> float: ...
    def getTargetPresentValue(self) -> float: ...
    def getUpperBound(self) -> float: ...
    def getUpperTopology(self) -> java.lang.String: ...
    def isTargetPresentAtLowerBound(self) -> bool: ...
    class Specification(java.lang.Enum['ElectrolytePhaseBoundaryResult.Specification']):
        PRESSURE: typing.ClassVar['ElectrolytePhaseBoundaryResult.Specification'] = ...
        TEMPERATURE: typing.ClassVar['ElectrolytePhaseBoundaryResult.Specification'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ElectrolytePhaseBoundaryResult.Specification': ...
        @staticmethod
        def values() -> typing.MutableSequence['ElectrolytePhaseBoundaryResult.Specification']: ...

class FreezingPointResult(java.io.Serializable):
    @staticmethod
    def converged(double: float, int: int, double2: float, string: typing.Union[java.lang.String, str]) -> 'FreezingPointResult': ...
    @staticmethod
    def failed(int: int, double: float, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'FreezingPointResult': ...
    def getComponentName(self) -> java.lang.String: ...
    def getFailureReason(self) -> java.lang.String: ...
    def getIterations(self) -> int: ...
    def getResidual(self) -> float: ...
    def getTemperature(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def isConverged(self) -> bool: ...

class MultiSaltPrecipitation:
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, *string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, multiSaltPrecipitationResult: 'MultiSaltPrecipitationResult'): ...
    def solve(self) -> 'MultiSaltPrecipitationResult': ...

class MultiSaltPrecipitationResult(java.io.Serializable):
    def getEquilibriumUpdates(self) -> int: ...
    def getMaximumComplementarityViolation(self) -> float: ...
    def getMaximumComponentBalanceResidualMoles(self) -> float: ...
    def getMaximumNormalizedBalanceResidual(self) -> float: ...
    def getMineralResult(self, string: typing.Union[java.lang.String, str]) -> 'SaltPrecipitationResult': ...
    def getMineralResults(self) -> java.util.Map[java.lang.String, 'SaltPrecipitationResult']: ...
    def getTotalPrecipitatedMassGrams(self) -> float: ...

class SaltPrecipitationResult(java.io.Serializable):
    def getComplementarityViolation(self) -> float: ...
    def getFinalSaturationRatio(self) -> float: ...
    def getInitialSaturationRatio(self) -> float: ...
    def getMaximumIonBalanceResidualMoles(self) -> float: ...
    def getPrecipitatedMassGrams(self) -> float: ...
    def getPrecipitatedMoles(self) -> float: ...
    def getSaltName(self) -> java.lang.String: ...
    def hasPrecipitatedSolid(self) -> bool: ...

class SaltSaturationResult(java.io.Serializable):
    def getAbsoluteSaturationRatioResidual(self) -> float: ...
    def getAddedSaltMoles(self) -> float: ...
    def getBracketIterations(self) -> int: ...
    def getFinalSaturationRatio(self) -> float: ...
    def getInitialSaturationRatio(self) -> float: ...
    def getSaltName(self) -> java.lang.String: ...
    def getSolveIterations(self) -> int: ...
    def getThermodynamicInitializationCount(self) -> int: ...
    def isAlreadySaturated(self) -> bool: ...
    def isConverged(self) -> bool: ...
    def isIterationLimitReached(self) -> bool: ...

class ConstantDutyFlash(ConstantDutyFlashInterface):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def addData(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> None: ...
    def displayResult(self) -> None: ...
    @typing.overload
    def get(self, string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...
    @typing.overload
    def get(self, string: typing.Union[java.lang.String, str]) -> typing.MutableSequence[float]: ...
    def getPoints(self, int: int) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getResultTable(self) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def isSuperCritical(self) -> bool: ...
    def run(self) -> None: ...
    def setSuperCritical(self, boolean: bool) -> None: ...

class AsphalteneOnsetPressureFlash(ConstantDutyFlash):
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float): ...
    def getJFreeChart(self, string: typing.Union[java.lang.String, str]) -> org.jfree.chart.JFreeChart: ...
    @typing.overload
    def getOnsetPressure(self) -> float: ...
    @typing.overload
    def getOnsetPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getPrecipitatedFraction(self) -> float: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def isOnsetFound(self) -> bool: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def setMinPressure(self, double: float) -> None: ...
    def setPressureStep(self, double: float) -> None: ...

class AsphalteneOnsetTemperatureFlash(ConstantDutyFlash):
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float, double3: float): ...
    def getJFreeChart(self, string: typing.Union[java.lang.String, str]) -> org.jfree.chart.JFreeChart: ...
    @typing.overload
    def getOnsetTemperature(self) -> float: ...
    @typing.overload
    def getOnsetTemperature(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def isOnsetFound(self) -> bool: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def setSearchDecreasing(self, boolean: bool) -> None: ...
    def setTemperatureStep(self, double: float) -> None: ...

class ConstantDutyPressureFlash(ConstantDutyFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def getJFreeChart(self, string: typing.Union[java.lang.String, str]) -> org.jfree.chart.JFreeChart: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class ConstantDutyTemperatureFlash(ConstantDutyFlash):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def getJFreeChart(self, string: typing.Union[java.lang.String, str]) -> org.jfree.chart.JFreeChart: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class AddIonToScaleSaturation(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, int: int, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def getResultTable(self) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class BubblePointPressureFlash(ConstantDutyPressureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class BubblePointPressureFlashDer(ConstantDutyPressureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class BubblePointTemperatureFlash(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class BubblePointTemperatureNoDer(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class CalcSaltSatauration(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, string: typing.Union[java.lang.String, str]): ...
    def getResult(self) -> SaltSaturationResult: ...
    def precipitate(self) -> SaltPrecipitationResult: ...
    def run(self) -> None: ...

class CapillaryDewPointFlash(ConstantDutyTemperatureFlash):
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float): ...
    def getBulkDewPointTemperature(self) -> float: ...
    def getCapillaryPressure(self) -> float: ...
    def getContactAngle(self) -> float: ...
    def getPoreRadius(self) -> float: ...
    def getSurfaceTension(self) -> float: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def setContactAngle(self, double: float) -> None: ...
    def setPoreRadius(self, double: float) -> None: ...

class CheckScalePotential(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, int: int): ...
    def getResultTable(self) -> typing.MutableSequence[typing.MutableSequence[java.lang.String]]: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class CricondenbarFlash(ConstantDutyPressureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calcx(self) -> float: ...
    def initMoleFraction(self) -> float: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def run2(self) -> None: ...
    def setJac(self) -> None: ...
    def setfvec(self) -> None: ...

class DewPointPressureFlash(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class DewPointTemperatureFlash(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class DewPointTemperatureFlashDer(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class FreezeOut(ConstantDutyTemperatureFlash, jneqsim.thermo.ThermodynamicConstantsInterface):
    FCompTemp: typing.MutableSequence[float] = ...
    FCompNames: typing.MutableSequence[java.lang.String] = ...
    noFreezeFlash: bool = ...
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class FreezingPointTemperatureFlash(ConstantDutyTemperatureFlash, jneqsim.thermo.ThermodynamicConstantsInterface):
    noFreezeFlash: bool = ...
    Niterations: int = ...
    name: java.lang.String = ...
    phaseName: java.lang.String = ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, boolean: bool): ...
    def calcFunc(self) -> float: ...
    def getResult(self) -> FreezingPointResult: ...
    @typing.overload
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def printToFile(self, string: typing.Union[java.lang.String, str], stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray], doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def run(self) -> None: ...

class FreezingPointTemperatureFlashOld(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class FreezingPointTemperatureFlashTR(ConstantDutyTemperatureFlash, jneqsim.thermo.ThermodynamicConstantsInterface):
    noFreezeFlash: bool = ...
    Niterations: int = ...
    FCompNames: typing.MutableSequence[java.lang.String] = ...
    FCompTemp: typing.MutableSequence[float] = ...
    compnr: int = ...
    name: java.lang.String = ...
    CCequation: bool = ...
    @typing.overload
    def __init__(self, boolean: bool): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, boolean: bool): ...
    def getNiterations(self) -> int: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class FugTestConstP(ConstantDutyTemperatureFlash, jneqsim.thermo.ThermodynamicConstantsInterface):
    temp: float = ...
    pres: float = ...
    testSystem: jneqsim.thermo.system.SystemInterface = ...
    testSystem2: jneqsim.thermo.system.SystemInterface = ...
    testOps: jneqsim.thermodynamicoperations.ThermodynamicOperations = ...
    testOps2: jneqsim.thermodynamicoperations.ThermodynamicOperations = ...
    compNumber: int = ...
    compName: java.lang.String = ...
    compNameGiven: bool = ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float): ...
    def initTestSystem2(self, int: int) -> None: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class HCdewPointPressureFlash(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class HydrateEquilibriumLine(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float): ...
    def getPoints(self, int: int) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def run(self) -> None: ...

class HydrateFormationPressureFlash(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def setFug(self) -> None: ...

class HydrateFormationTemperatureFlash(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def run2(self) -> None: ...
    def setFug(self) -> None: ...
    def stop(self) -> None: ...

class HydrateInhibitorConcentrationFlash(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, string: typing.Union[java.lang.String, str], double: float): ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...

class HydrateInhibitorwtFlash(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, string: typing.Union[java.lang.String, str], double: float): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...

class SolidComplexTemperatureCalc(ConstantDutyTemperatureFlash):
    Kcomplex: float = ...
    HrefComplex: float = ...
    TrefComplex: float = ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    @typing.overload
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def getHrefComplex(self) -> float: ...
    def getKcomplex(self) -> float: ...
    def getTrefComplex(self) -> float: ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...
    def runOld(self) -> None: ...
    def setHrefComplex(self, double: float) -> None: ...
    def setKcomplex(self, double: float) -> None: ...
    def setTrefComplex(self, double: float) -> None: ...

class WATcalc(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class WaterDewPointEquilibriumLine(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float, double2: float): ...
    def getPoints(self, int: int) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def run(self) -> None: ...

class WaterDewPointTemperatureFlash(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...

class WaterDewPointTemperatureMultiphaseFlash(ConstantDutyTemperatureFlash):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def printToFile(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def run(self) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.thermodynamicoperations.flashops.saturationops")``.

    AddIonToScaleSaturation: typing.Type[AddIonToScaleSaturation]
    AsphalteneOnsetPressureFlash: typing.Type[AsphalteneOnsetPressureFlash]
    AsphalteneOnsetTemperatureFlash: typing.Type[AsphalteneOnsetTemperatureFlash]
    BubblePointPressureFlash: typing.Type[BubblePointPressureFlash]
    BubblePointPressureFlashDer: typing.Type[BubblePointPressureFlashDer]
    BubblePointTemperatureFlash: typing.Type[BubblePointTemperatureFlash]
    BubblePointTemperatureNoDer: typing.Type[BubblePointTemperatureNoDer]
    CalcSaltSatauration: typing.Type[CalcSaltSatauration]
    CalciumSulfatePhaseBoundaryQualification: typing.Type[CalciumSulfatePhaseBoundaryQualification]
    CapillaryDewPointFlash: typing.Type[CapillaryDewPointFlash]
    CheckScalePotential: typing.Type[CheckScalePotential]
    ConstantDutyFlash: typing.Type[ConstantDutyFlash]
    ConstantDutyFlashInterface: typing.Type[ConstantDutyFlashInterface]
    ConstantDutyPressureFlash: typing.Type[ConstantDutyPressureFlash]
    ConstantDutyTemperatureFlash: typing.Type[ConstantDutyTemperatureFlash]
    CricondenBarTemp: typing.Type[CricondenBarTemp]
    CricondenBarTemp1: typing.Type[CricondenBarTemp1]
    CricondenbarFlash: typing.Type[CricondenbarFlash]
    DewPointPressureFlash: typing.Type[DewPointPressureFlash]
    DewPointTemperatureFlash: typing.Type[DewPointTemperatureFlash]
    DewPointTemperatureFlashDer: typing.Type[DewPointTemperatureFlashDer]
    ElectrolytePhaseBoundaryFlash: typing.Type[ElectrolytePhaseBoundaryFlash]
    ElectrolytePhaseBoundaryResult: typing.Type[ElectrolytePhaseBoundaryResult]
    FreezeOut: typing.Type[FreezeOut]
    FreezingPointResult: typing.Type[FreezingPointResult]
    FreezingPointTemperatureFlash: typing.Type[FreezingPointTemperatureFlash]
    FreezingPointTemperatureFlashOld: typing.Type[FreezingPointTemperatureFlashOld]
    FreezingPointTemperatureFlashTR: typing.Type[FreezingPointTemperatureFlashTR]
    FugTestConstP: typing.Type[FugTestConstP]
    HCdewPointPressureFlash: typing.Type[HCdewPointPressureFlash]
    HydrateEquilibriumLine: typing.Type[HydrateEquilibriumLine]
    HydrateFormationPressureFlash: typing.Type[HydrateFormationPressureFlash]
    HydrateFormationTemperatureFlash: typing.Type[HydrateFormationTemperatureFlash]
    HydrateInhibitorConcentrationFlash: typing.Type[HydrateInhibitorConcentrationFlash]
    HydrateInhibitorwtFlash: typing.Type[HydrateInhibitorwtFlash]
    MultiSaltPrecipitation: typing.Type[MultiSaltPrecipitation]
    MultiSaltPrecipitationResult: typing.Type[MultiSaltPrecipitationResult]
    SaltPrecipitationResult: typing.Type[SaltPrecipitationResult]
    SaltSaturationResult: typing.Type[SaltSaturationResult]
    SolidComplexTemperatureCalc: typing.Type[SolidComplexTemperatureCalc]
    WATcalc: typing.Type[WATcalc]
    WaterDewPointEquilibriumLine: typing.Type[WaterDewPointEquilibriumLine]
    WaterDewPointTemperatureFlash: typing.Type[WaterDewPointTemperatureFlash]
    WaterDewPointTemperatureMultiphaseFlash: typing.Type[WaterDewPointTemperatureMultiphaseFlash]
