import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import com.google.gson
import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.measurementdevice
import jneqsim.process.operations.envelope
import jneqsim.process.processmodel
import jneqsim.util.validation
import typing

class ControllerTuningResult(java.io.Serializable):
    def getControllerName(self) -> java.lang.String: ...
    def getIntegralAbsoluteError(self) -> float: ...
    def getIntegralSquaredError(self) -> float: ...
    def getMaxAbsoluteError(self) -> float: ...
    def getMeanAbsoluteError(self) -> float: ...
    def getOutputSaturationFraction(self) -> float: ...
    def getOvershootPercent(self) -> float: ...
    def getRecommendation(self) -> java.lang.String: ...
    def getSetPoint(self) -> float: ...
    def getSettlingTimeSeconds(self) -> float: ...
    def isStableAtEnd(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...

class ControllerTuningStudy:
    @staticmethod
    def evaluateStepResponse(
        string: typing.Union[java.lang.String, str],
        double: float,
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
        doubleArray2: typing.Union[typing.List[float], jpype.JArray],
        doubleArray3: typing.Union[typing.List[float], jpype.JArray],
        double5: float,
        double6: float,
        double7: float,
    ) -> ControllerTuningResult: ...

class OperationalAction(java.io.Serializable):
    @staticmethod
    def applyFieldInputs() -> "OperationalAction": ...
    def getDescription(self) -> java.lang.String: ...
    def getDurationSeconds(self) -> float: ...
    def getTarget(self) -> java.lang.String: ...
    def getTimeStepSeconds(self) -> float: ...
    def getType(self) -> "OperationalAction.ActionType": ...
    def getUnit(self) -> java.lang.String: ...
    def getValue(self) -> float: ...
    @staticmethod
    def runSteadyState() -> "OperationalAction": ...
    @staticmethod
    def runTransient(double: float, double2: float) -> "OperationalAction": ...
    @staticmethod
    def setValveOpening(
        string: typing.Union[java.lang.String, str], double: float
    ) -> "OperationalAction": ...
    @staticmethod
    def setVariable(
        string: typing.Union[java.lang.String, str],
        double: float,
        string2: typing.Union[java.lang.String, str],
    ) -> "OperationalAction": ...

    class ActionType(java.lang.Enum["OperationalAction.ActionType"]):
        SET_VARIABLE: typing.ClassVar["OperationalAction.ActionType"] = ...
        SET_VALVE_OPENING: typing.ClassVar["OperationalAction.ActionType"] = ...
        APPLY_FIELD_INPUTS: typing.ClassVar["OperationalAction.ActionType"] = ...
        RUN_STEADY_STATE: typing.ClassVar["OperationalAction.ActionType"] = ...
        RUN_TRANSIENT: typing.ClassVar["OperationalAction.ActionType"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "OperationalAction.ActionType": ...
        @staticmethod
        def values() -> typing.MutableSequence["OperationalAction.ActionType"]: ...

class OperationalEvidencePackage:
    DEFAULT_BENCHMARK_TOLERANCE_FRACTION: typing.ClassVar[float] = ...
    @staticmethod
    def buildCapacityReport(
        processSystem: jneqsim.process.processmodel.ProcessSystem,
    ) -> com.google.gson.JsonObject: ...
    @staticmethod
    def buildReport(
        string: typing.Union[java.lang.String, str],
        processSystem: jneqsim.process.processmodel.ProcessSystem,
        operationalTagMap: "OperationalTagMap",
        map: typing.Union[
            java.util.Map[typing.Union[java.lang.String, str], float],
            typing.Mapping[typing.Union[java.lang.String, str], float],
        ],
        list: java.util.List["OperationalScenario"],
        double: float,
    ) -> com.google.gson.JsonObject: ...

class OperationalScenario(java.io.Serializable):
    @staticmethod
    def builder(
        string: typing.Union[java.lang.String, str]
    ) -> "OperationalScenario.Builder": ...
    def getActions(self) -> java.util.List[OperationalAction]: ...
    def getName(self) -> java.lang.String: ...

    class Builder:
        def addAction(
            self, operationalAction: OperationalAction
        ) -> "OperationalScenario.Builder": ...
        def build(self) -> "OperationalScenario": ...

class OperationalScenarioResult(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addActionLog(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def addError(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def addWarning(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def getActionLog(self) -> java.util.List[java.lang.String]: ...
    def getAfterValues(self) -> java.util.Map[java.lang.String, float]: ...
    def getBeforeValues(self) -> java.util.Map[java.lang.String, float]: ...
    def getErrors(self) -> java.util.List[java.lang.String]: ...
    def getScenarioName(self) -> java.lang.String: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isSuccessful(self) -> bool: ...
    def putAfterValue(
        self, string: typing.Union[java.lang.String, str], double: float
    ) -> None: ...
    def putBeforeValue(
        self, string: typing.Union[java.lang.String, str], double: float
    ) -> None: ...
    def toJson(self) -> java.lang.String: ...

class OperationalScenarioRunner:
    @staticmethod
    def run(
        processSystem: jneqsim.process.processmodel.ProcessSystem,
        operationalScenario: OperationalScenario,
    ) -> OperationalScenarioResult: ...

class OperationalTagBinding(java.io.Serializable):
    @staticmethod
    def builder(
        string: typing.Union[java.lang.String, str]
    ) -> "OperationalTagBinding.Builder": ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAutomationAddress(self) -> java.lang.String: ...
    def getDescription(self) -> java.lang.String: ...
    def getHistorianTag(self) -> java.lang.String: ...
    def getLogicalTag(self) -> java.lang.String: ...
    def getPidReference(self) -> java.lang.String: ...
    def getRole(self) -> jneqsim.process.measurementdevice.InstrumentTagRole: ...
    def getUnit(self) -> java.lang.String: ...
    def hasAutomationAddress(self) -> bool: ...
    def hasHistorianTag(self) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def automationAddress(
            self, string: typing.Union[java.lang.String, str]
        ) -> "OperationalTagBinding.Builder": ...
        def build(self) -> "OperationalTagBinding": ...
        def description(
            self, string: typing.Union[java.lang.String, str]
        ) -> "OperationalTagBinding.Builder": ...
        def historianTag(
            self, string: typing.Union[java.lang.String, str]
        ) -> "OperationalTagBinding.Builder": ...
        def pidReference(
            self, string: typing.Union[java.lang.String, str]
        ) -> "OperationalTagBinding.Builder": ...
        def role(
            self, instrumentTagRole: jneqsim.process.measurementdevice.InstrumentTagRole
        ) -> "OperationalTagBinding.Builder": ...
        def unit(
            self, string: typing.Union[java.lang.String, str]
        ) -> "OperationalTagBinding.Builder": ...

class OperationalTagMap(java.io.Serializable):
    def __init__(self): ...
    def addBinding(
        self, operationalTagBinding: OperationalTagBinding
    ) -> "OperationalTagMap": ...
    def applyFieldData(
        self,
        processSystem: jneqsim.process.processmodel.ProcessSystem,
        map: typing.Union[
            java.util.Map[typing.Union[java.lang.String, str], float],
            typing.Mapping[typing.Union[java.lang.String, str], float],
        ],
    ) -> java.util.Map[java.lang.String, float]: ...
    def containsLogicalTag(
        self, string: typing.Union[java.lang.String, str]
    ) -> bool: ...
    def getBinding(
        self, string: typing.Union[java.lang.String, str]
    ) -> OperationalTagBinding: ...
    def getBindings(self) -> java.util.List[OperationalTagBinding]: ...
    def readValues(
        self, processSystem: jneqsim.process.processmodel.ProcessSystem
    ) -> java.util.Map[java.lang.String, float]: ...
    def validate(
        self, processSystem: jneqsim.process.processmodel.ProcessSystem
    ) -> jneqsim.util.validation.ValidationResult: ...

class PipeSectionAnalyzer:
    @staticmethod
    def run(string: typing.Union[java.lang.String, str]) -> java.lang.String: ...

class WaterHammerStudy:
    @staticmethod
    def run(string: typing.Union[java.lang.String, str]) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.operations")``.

    ControllerTuningResult: typing.Type[ControllerTuningResult]
    ControllerTuningStudy: typing.Type[ControllerTuningStudy]
    OperationalAction: typing.Type[OperationalAction]
    OperationalEvidencePackage: typing.Type[OperationalEvidencePackage]
    OperationalScenario: typing.Type[OperationalScenario]
    OperationalScenarioResult: typing.Type[OperationalScenarioResult]
    OperationalScenarioRunner: typing.Type[OperationalScenarioRunner]
    OperationalTagBinding: typing.Type[OperationalTagBinding]
    OperationalTagMap: typing.Type[OperationalTagMap]
    PipeSectionAnalyzer: typing.Type[PipeSectionAnalyzer]
    WaterHammerStudy: typing.Type[WaterHammerStudy]
    envelope: jneqsim.process.operations.envelope.__module_protocol__
