
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.nio.file
import jpype.protocol
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.process.processmodel
import jneqsim.process.processmodel.graph
import typing



class DexpiDiagramBridge(java.io.Serializable):
    @staticmethod
    def createDetailedExporter(processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'ProcessDiagramExporter': ...
    @staticmethod
    def createExporter(processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'ProcessDiagramExporter': ...
    @staticmethod
    def exportToDexpi(processSystem: jneqsim.process.processmodel.ProcessSystem, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> None: ...
    @typing.overload
    @staticmethod
    def importAndCreateExporter(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'ProcessDiagramExporter': ...
    @typing.overload
    @staticmethod
    def importAndCreateExporter(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], stream: jneqsim.process.equipment.stream.Stream) -> 'ProcessDiagramExporter': ...
    @typing.overload
    @staticmethod
    def importDexpi(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> jneqsim.process.processmodel.ProcessSystem: ...
    @typing.overload
    @staticmethod
    def importDexpi(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], stream: jneqsim.process.equipment.stream.Stream) -> jneqsim.process.processmodel.ProcessSystem: ...
    @staticmethod
    def roundTrip(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], path2: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], path3: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> jneqsim.process.processmodel.ProcessSystem: ...

class DiagramDetailLevel(java.lang.Enum['DiagramDetailLevel']):
    CONCEPTUAL: typing.ClassVar['DiagramDetailLevel'] = ...
    ENGINEERING: typing.ClassVar['DiagramDetailLevel'] = ...
    DEBUG: typing.ClassVar['DiagramDetailLevel'] = ...
    def showCompositions(self) -> bool: ...
    def showConditions(self) -> bool: ...
    def showFlowRates(self) -> bool: ...
    def showSpecifications(self) -> bool: ...
    def useCompactLabels(self) -> bool: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'DiagramDetailLevel': ...
    @staticmethod
    def values() -> typing.MutableSequence['DiagramDetailLevel']: ...

class DiagramStyle(java.lang.Enum['DiagramStyle']):
    NEQSIM: typing.ClassVar['DiagramStyle'] = ...
    HYSYS: typing.ClassVar['DiagramStyle'] = ...
    PROII: typing.ClassVar['DiagramStyle'] = ...
    ASPEN_PLUS: typing.ClassVar['DiagramStyle'] = ...
    def getArrowStyle(self) -> java.lang.String: ...
    def getBackgroundColor(self) -> java.lang.String: ...
    def getDisplayName(self) -> java.lang.String: ...
    def getEdgeStyle(self) -> java.lang.String: ...
    def getEnergyStreamColor(self) -> java.lang.String: ...
    def getEquipmentFillColor(self, string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    def getEquipmentOutlineColor(self) -> java.lang.String: ...
    def getFontColor(self) -> java.lang.String: ...
    def getFontName(self) -> java.lang.String: ...
    def getFontSize(self) -> int: ...
    def getPenWidth(self) -> float: ...
    def getRecycleColor(self) -> java.lang.String: ...
    def getSplineType(self) -> java.lang.String: ...
    def getStreamColor(self) -> java.lang.String: ...
    def getStreamWidth(self) -> float: ...
    def showClusters(self) -> bool: ...
    def useHtmlLabels(self) -> bool: ...
    def useStreamNumbers(self) -> bool: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'DiagramStyle': ...
    @staticmethod
    def values() -> typing.MutableSequence['DiagramStyle']: ...

class EquipmentRole(java.lang.Enum['EquipmentRole']):
    GAS: typing.ClassVar['EquipmentRole'] = ...
    LIQUID: typing.ClassVar['EquipmentRole'] = ...
    SEPARATOR: typing.ClassVar['EquipmentRole'] = ...
    MIXED: typing.ClassVar['EquipmentRole'] = ...
    FEED: typing.ClassVar['EquipmentRole'] = ...
    PRODUCT: typing.ClassVar['EquipmentRole'] = ...
    UTILITY: typing.ClassVar['EquipmentRole'] = ...
    CONTROL: typing.ClassVar['EquipmentRole'] = ...
    UNKNOWN: typing.ClassVar['EquipmentRole'] = ...
    def getDefaultColor(self) -> java.lang.String: ...
    def getDisplayName(self) -> java.lang.String: ...
    def getPreferredZone(self) -> java.lang.String: ...
    def getRankPriority(self) -> int: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'EquipmentRole': ...
    @staticmethod
    def values() -> typing.MutableSequence['EquipmentRole']: ...

class EquipmentVisualStyle(java.io.Serializable):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str], string6: typing.Union[java.lang.String, str], string7: typing.Union[java.lang.String, str]): ...
    def getBorderColor(self) -> java.lang.String: ...
    def getFillColor(self) -> java.lang.String: ...
    def getFontColor(self) -> java.lang.String: ...
    def getHeight(self) -> java.lang.String: ...
    def getShape(self) -> java.lang.String: ...
    @typing.overload
    def getStyle(self) -> java.lang.String: ...
    @typing.overload
    @staticmethod
    def getStyle(string: typing.Union[java.lang.String, str]) -> 'EquipmentVisualStyle': ...
    @typing.overload
    @staticmethod
    def getStyle(equipmentEnum: jneqsim.process.equipment.EquipmentEnum) -> 'EquipmentVisualStyle': ...
    @staticmethod
    def getStyleForEquipment(processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> 'EquipmentVisualStyle': ...
    def getWidth(self) -> java.lang.String: ...
    def toGraphvizAttributes(self, string: typing.Union[java.lang.String, str]) -> java.lang.String: ...

class PFDLayoutPolicy(java.io.Serializable):
    def __init__(self): ...
    def classifyEdgePhase(self, processEdge: jneqsim.process.processmodel.graph.ProcessEdge) -> 'PFDLayoutPolicy.StreamPhase': ...
    def classifyEquipment(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> EquipmentRole: ...
    def classifyHorizontalPosition(self, processNode: jneqsim.process.processmodel.graph.ProcessNode, processGraph: jneqsim.process.processmodel.graph.ProcessGraph) -> 'PFDLayoutPolicy.ProcessPosition': ...
    def classifyPhaseZone(self, processNode: jneqsim.process.processmodel.graph.ProcessNode) -> 'PFDLayoutPolicy.PhaseZone': ...
    def classifySeparatorOutlet(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> 'PFDLayoutPolicy.SeparatorOutlet': ...
    def classifyStreamPhase(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> 'PFDLayoutPolicy.StreamPhase': ...
    def clearCache(self) -> None: ...
    def getLayoutCoordinates(self, processNode: jneqsim.process.processmodel.graph.ProcessNode, processGraph: jneqsim.process.processmodel.graph.ProcessGraph) -> typing.MutableSequence[int]: ...
    def getRankConstraint(self, processNode: jneqsim.process.processmodel.graph.ProcessNode) -> java.lang.String: ...
    def getRankLevel(self, processNode: jneqsim.process.processmodel.graph.ProcessNode) -> int: ...
    class PhaseZone(java.lang.Enum['PFDLayoutPolicy.PhaseZone']):
        GAS_TOP: typing.ClassVar['PFDLayoutPolicy.PhaseZone'] = ...
        OIL_MIDDLE: typing.ClassVar['PFDLayoutPolicy.PhaseZone'] = ...
        WATER_BOTTOM: typing.ClassVar['PFDLayoutPolicy.PhaseZone'] = ...
        SEPARATION_CENTER: typing.ClassVar['PFDLayoutPolicy.PhaseZone'] = ...
        UNKNOWN: typing.ClassVar['PFDLayoutPolicy.PhaseZone'] = ...
        def getColor(self) -> java.lang.String: ...
        def getLabel(self) -> java.lang.String: ...
        def getVerticalRank(self) -> int: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PFDLayoutPolicy.PhaseZone': ...
        @staticmethod
        def values() -> typing.MutableSequence['PFDLayoutPolicy.PhaseZone']: ...
    class ProcessPosition(java.lang.Enum['PFDLayoutPolicy.ProcessPosition']):
        INLET: typing.ClassVar['PFDLayoutPolicy.ProcessPosition'] = ...
        CENTER: typing.ClassVar['PFDLayoutPolicy.ProcessPosition'] = ...
        OUTLET: typing.ClassVar['PFDLayoutPolicy.ProcessPosition'] = ...
        def getDescription(self) -> java.lang.String: ...
        def getHorizontalRank(self) -> int: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PFDLayoutPolicy.ProcessPosition': ...
        @staticmethod
        def values() -> typing.MutableSequence['PFDLayoutPolicy.ProcessPosition']: ...
    class SeparatorOutlet(java.lang.Enum['PFDLayoutPolicy.SeparatorOutlet']):
        GAS_TOP: typing.ClassVar['PFDLayoutPolicy.SeparatorOutlet'] = ...
        OIL_MIDDLE: typing.ClassVar['PFDLayoutPolicy.SeparatorOutlet'] = ...
        WATER_BOTTOM: typing.ClassVar['PFDLayoutPolicy.SeparatorOutlet'] = ...
        LIQUID_BOTTOM: typing.ClassVar['PFDLayoutPolicy.SeparatorOutlet'] = ...
        FEED_SIDE: typing.ClassVar['PFDLayoutPolicy.SeparatorOutlet'] = ...
        def getPort(self) -> java.lang.String: ...
        def getRankOffset(self) -> int: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PFDLayoutPolicy.SeparatorOutlet': ...
        @staticmethod
        def values() -> typing.MutableSequence['PFDLayoutPolicy.SeparatorOutlet']: ...
    class StreamPhase(java.lang.Enum['PFDLayoutPolicy.StreamPhase']):
        GAS: typing.ClassVar['PFDLayoutPolicy.StreamPhase'] = ...
        LIQUID: typing.ClassVar['PFDLayoutPolicy.StreamPhase'] = ...
        OIL: typing.ClassVar['PFDLayoutPolicy.StreamPhase'] = ...
        AQUEOUS: typing.ClassVar['PFDLayoutPolicy.StreamPhase'] = ...
        MIXED: typing.ClassVar['PFDLayoutPolicy.StreamPhase'] = ...
        UNKNOWN: typing.ClassVar['PFDLayoutPolicy.StreamPhase'] = ...
        def getColor(self) -> java.lang.String: ...
        def getLabel(self) -> java.lang.String: ...
        def getLineStyle(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PFDLayoutPolicy.StreamPhase': ...
        @staticmethod
        def values() -> typing.MutableSequence['PFDLayoutPolicy.StreamPhase']: ...

class ProcessDiagramExporter(java.io.Serializable):
    @typing.overload
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    @typing.overload
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem, pFDLayoutPolicy: PFDLayoutPolicy): ...
    def exportDOT(self, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> None: ...
    def exportPDF(self, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> None: ...
    def exportPNG(self, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> None: ...
    def exportSVG(self, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> None: ...
    def getDiagramStyle(self) -> DiagramStyle: ...
    @staticmethod
    def isGraphvizAvailable() -> bool: ...
    def setDetailLevel(self, diagramDetailLevel: DiagramDetailLevel) -> 'ProcessDiagramExporter': ...
    def setDiagramStyle(self, diagramStyle: DiagramStyle) -> 'ProcessDiagramExporter': ...
    def setHighlightRecycles(self, boolean: bool) -> 'ProcessDiagramExporter': ...
    def setShowControlEquipment(self, boolean: bool) -> 'ProcessDiagramExporter': ...
    def setShowDexpiMetadata(self, boolean: bool) -> 'ProcessDiagramExporter': ...
    def setShowLegend(self, boolean: bool) -> 'ProcessDiagramExporter': ...
    def setShowStreamValues(self, boolean: bool) -> 'ProcessDiagramExporter': ...
    def setTitle(self, string: typing.Union[java.lang.String, str]) -> 'ProcessDiagramExporter': ...
    def setUseClusters(self, boolean: bool) -> 'ProcessDiagramExporter': ...
    def setUseStreamTables(self, boolean: bool) -> 'ProcessDiagramExporter': ...
    def setVerticalLayout(self, boolean: bool) -> 'ProcessDiagramExporter': ...
    def toDOT(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.processmodel.diagram")``.

    DexpiDiagramBridge: typing.Type[DexpiDiagramBridge]
    DiagramDetailLevel: typing.Type[DiagramDetailLevel]
    DiagramStyle: typing.Type[DiagramStyle]
    EquipmentRole: typing.Type[EquipmentRole]
    EquipmentVisualStyle: typing.Type[EquipmentVisualStyle]
    PFDLayoutPolicy: typing.Type[PFDLayoutPolicy]
    ProcessDiagramExporter: typing.Type[ProcessDiagramExporter]
