
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process
import jneqsim.process.alarm
import jneqsim.process.dynamics
import jneqsim.process.equipment
import jneqsim.process.equipment.compressor
import jneqsim.process.equipment.pipeline
import jneqsim.process.equipment.separator
import jneqsim.process.equipment.stream
import jneqsim.process.equipment.tank
import jneqsim.process.equipment.valve
import jneqsim.process.logic
import jneqsim.process.measurementdevice.online
import jneqsim.process.measurementdevice.simpleflowregime
import jneqsim.process.measurementdevice.vfm
import jneqsim.util
import typing



class ExpansibilityModel(java.lang.Enum['ExpansibilityModel']):
    ORIFICE: typing.ClassVar['ExpansibilityModel'] = ...
    ISENTROPIC: typing.ClassVar['ExpansibilityModel'] = ...
    CONE: typing.ClassVar['ExpansibilityModel'] = ...
    def calculate(self, double: float, double2: float, double3: float, double4: float) -> float: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'ExpansibilityModel': ...
    @staticmethod
    def values() -> typing.MutableSequence['ExpansibilityModel']: ...

class InstrumentTagRole(java.lang.Enum['InstrumentTagRole']):
    INPUT: typing.ClassVar['InstrumentTagRole'] = ...
    BENCHMARK: typing.ClassVar['InstrumentTagRole'] = ...
    VIRTUAL: typing.ClassVar['InstrumentTagRole'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'InstrumentTagRole': ...
    @staticmethod
    def values() -> typing.MutableSequence['InstrumentTagRole']: ...

class MeasurementDeviceInterface(jneqsim.process.ProcessElementInterface):
    def acknowledgeAlarm(self, double: float) -> jneqsim.process.alarm.AlarmEvent: ...
    def applyFieldValue(self) -> None: ...
    def displayResult(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def evaluateAlarm(self, double: float, double2: float, double3: float) -> java.util.List[jneqsim.process.alarm.AlarmEvent]: ...
    def getAlarmConfig(self) -> jneqsim.process.alarm.AlarmConfig: ...
    def getAlarmState(self) -> jneqsim.process.alarm.AlarmState: ...
    def getDeviation(self) -> float: ...
    def getFieldValue(self) -> float: ...
    def getMaximumValue(self) -> float: ...
    def getMeasuredPercentValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    def getMinimumValue(self) -> float: ...
    def getOnlineSignal(self) -> jneqsim.process.measurementdevice.online.OnlineSignal: ...
    def getOnlineValue(self) -> float: ...
    def getRelativeDeviation(self) -> float: ...
    def getTag(self) -> java.lang.String: ...
    def getTagRole(self) -> InstrumentTagRole: ...
    def getUnit(self) -> java.lang.String: ...
    def hasFieldValue(self) -> bool: ...
    def hashCode(self) -> int: ...
    def isLogging(self) -> bool: ...
    def isOnlineSignal(self) -> bool: ...
    def setAlarmConfig(self, alarmConfig: jneqsim.process.alarm.AlarmConfig) -> None: ...
    def setFieldValue(self, double: float) -> None: ...
    def setLogging(self, boolean: bool) -> None: ...
    def setMaximumValue(self, double: float) -> None: ...
    def setMinimumValue(self, double: float) -> None: ...
    def setTag(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTagRole(self, instrumentTagRole: InstrumentTagRole) -> None: ...
    def setUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...

class SensorFaultType(java.lang.Enum['SensorFaultType']):
    NONE: typing.ClassVar['SensorFaultType'] = ...
    STUCK_AT_VALUE: typing.ClassVar['SensorFaultType'] = ...
    LINEAR_DRIFT: typing.ClassVar['SensorFaultType'] = ...
    BIAS: typing.ClassVar['SensorFaultType'] = ...
    NOISE_BURST: typing.ClassVar['SensorFaultType'] = ...
    SATURATION: typing.ClassVar['SensorFaultType'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'SensorFaultType': ...
    @staticmethod
    def values() -> typing.MutableSequence['SensorFaultType']: ...

class MeasurementDeviceBaseClass(jneqsim.util.NamedBaseClass, MeasurementDeviceInterface):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def acknowledgeAlarm(self, double: float) -> jneqsim.process.alarm.AlarmEvent: ...
    def clearFault(self) -> None: ...
    def displayResult(self) -> None: ...
    def doConditionAnalysis(self) -> bool: ...
    def evaluateAlarm(self, double: float, double2: float, double3: float) -> java.util.List[jneqsim.process.alarm.AlarmEvent]: ...
    def getAlarmConfig(self) -> jneqsim.process.alarm.AlarmConfig: ...
    def getAlarmState(self) -> jneqsim.process.alarm.AlarmState: ...
    def getConditionAnalysisMaxDeviation(self) -> float: ...
    def getConditionAnalysisMessage(self) -> java.lang.String: ...
    def getDelaySteps(self) -> int: ...
    def getFaultParameter(self) -> float: ...
    def getFaultType(self) -> SensorFaultType: ...
    def getFieldValue(self) -> float: ...
    def getFirstOrderTimeConstant(self) -> float: ...
    def getMaximumValue(self) -> float: ...
    def getMeasuredPercentValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMinimumValue(self) -> float: ...
    def getNoiseStdDev(self) -> float: ...
    def getOnlineMeasurementValue(self) -> float: ...
    def getOnlineSignal(self) -> jneqsim.process.measurementdevice.online.OnlineSignal: ...
    def getTag(self) -> java.lang.String: ...
    def getTagRole(self) -> InstrumentTagRole: ...
    def getUnit(self) -> java.lang.String: ...
    def hasFieldValue(self) -> bool: ...
    def isAlarmShelved(self) -> bool: ...
    def isLogging(self) -> bool: ...
    def isOnlineSignal(self) -> bool: ...
    def runConditionAnalysis(self) -> None: ...
    def setAlarmConfig(self, alarmConfig: jneqsim.process.alarm.AlarmConfig) -> None: ...
    def setConditionAnalysis(self, boolean: bool) -> None: ...
    def setConditionAnalysisMaxDeviation(self, double: float) -> None: ...
    def setDelaySteps(self, int: int) -> None: ...
    def setFault(self, sensorFaultType: SensorFaultType, double: float) -> None: ...
    def setFieldValue(self, double: float) -> None: ...
    def setFirstOrderTimeConstant(self, double: float) -> None: ...
    def setIsOnlineSignal(self, boolean: bool, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> None: ...
    def setLogging(self, boolean: bool) -> None: ...
    def setMaximumValue(self, double: float) -> None: ...
    def setMinimumValue(self, double: float) -> None: ...
    def setNoiseStdDev(self, double: float) -> None: ...
    def setOnlineMeasurementValue(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setOnlineSignal(self, onlineSignal: jneqsim.process.measurementdevice.online.OnlineSignal) -> None: ...
    def setQualityCheckMessage(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRandomSeed(self, long: int) -> None: ...
    def setTag(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTagRole(self, instrumentTagRole: InstrumentTagRole) -> None: ...
    def setUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def shelveAlarm(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def shelveAlarm(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def unshelveAlarm(self) -> None: ...

class CompressorMonitor(MeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], compressor: jneqsim.process.equipment.compressor.Compressor): ...
    @typing.overload
    def __init__(self, compressor: jneqsim.process.equipment.compressor.Compressor): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...

class DifferentialPressureTransmitter(MeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['DifferentialPressureTransmitter.DifferentialPressureTransmitterState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface): ...
    def captureTransientState(self) -> 'DifferentialPressureTransmitter.DifferentialPressureTransmitterState': ...
    def displayResult(self) -> None: ...
    def getHighPressureStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getLowPressureStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, differentialPressureTransmitterState: 'DifferentialPressureTransmitter.DifferentialPressureTransmitterState') -> None: ...
    class DifferentialPressureTransmitterState(java.io.Serializable): ...

class FireDetector(MeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['FireDetector.FireDetectorState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def captureTransientState(self) -> 'FireDetector.FireDetectorState': ...
    def detectFire(self) -> None: ...
    def displayResult(self) -> None: ...
    def getDetectionDelay(self) -> float: ...
    def getDetectionThreshold(self) -> float: ...
    def getLocation(self) -> java.lang.String: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getSignalLevel(self) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def isFireDetected(self) -> bool: ...
    def reset(self) -> None: ...
    def restoreTransientState(self, fireDetectorState: 'FireDetector.FireDetectorState') -> None: ...
    def setDetectionDelay(self, double: float) -> None: ...
    def setDetectionThreshold(self, double: float) -> None: ...
    def setLocation(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSignalLevel(self, double: float) -> None: ...
    def toString(self) -> java.lang.String: ...
    class FireDetectorState(java.io.Serializable): ...

class FlowInducedVibrationAnalyser(MeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['FlowInducedVibrationAnalyser.FlowInducedVibrationAnalyserState']):
    VALID_SUPPORT_ARRANGEMENTS: typing.ClassVar[typing.MutableSequence[java.lang.String]] = ...
    REFERENCE_VISCOSITY_CP: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills): ...
    @typing.overload
    def __init__(self, pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills): ...
    def captureTransientState(self) -> 'FlowInducedVibrationAnalyser.FlowInducedVibrationAnalyserState': ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMethod(self) -> java.lang.String: ...
    def getSupportArrangement(self) -> java.lang.String: ...
    def getSupportDistance(self) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, flowInducedVibrationAnalyserState: 'FlowInducedVibrationAnalyser.FlowInducedVibrationAnalyserState') -> None: ...
    def setFRMSConstant(self, double: float) -> None: ...
    def setMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSegment(self, int: int) -> None: ...
    def setSupportArrangement(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSupportDistance(self, double: float) -> None: ...
    class FlowInducedVibrationAnalyserState(java.io.Serializable): ...

class FlowRatioMeter(MeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['FlowRatioMeter.FlowRatioMeterState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface, flowBasis: 'FlowRatioMeter.FlowBasis'): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface, flowBasis: 'FlowRatioMeter.FlowBasis'): ...
    def captureTransientState(self) -> 'FlowRatioMeter.FlowRatioMeterState': ...
    def displayResult(self) -> None: ...
    def getDenominatorStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getFlowBasis(self) -> 'FlowRatioMeter.FlowBasis': ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getNumeratorStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, flowRatioMeterState: 'FlowRatioMeter.FlowRatioMeterState') -> None: ...
    class FlowBasis(java.lang.Enum['FlowRatioMeter.FlowBasis']):
        MASS: typing.ClassVar['FlowRatioMeter.FlowBasis'] = ...
        MOLE: typing.ClassVar['FlowRatioMeter.FlowBasis'] = ...
        VOLUME: typing.ClassVar['FlowRatioMeter.FlowBasis'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FlowRatioMeter.FlowBasis': ...
        @staticmethod
        def values() -> typing.MutableSequence['FlowRatioMeter.FlowBasis']: ...
    class FlowRatioMeterState(java.io.Serializable): ...

class GasDetector(MeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['GasDetector.GasDetectorState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], gasType: 'GasDetector.GasType'): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], gasType: 'GasDetector.GasType', string2: typing.Union[java.lang.String, str]): ...
    def captureTransientState(self) -> 'GasDetector.GasDetectorState': ...
    def convertPercentLELToPpm(self, double: float) -> float: ...
    def convertPpmToPercentLEL(self, double: float) -> float: ...
    def displayResult(self) -> None: ...
    def getGasConcentration(self) -> float: ...
    def getGasSpecies(self) -> java.lang.String: ...
    def getGasType(self) -> 'GasDetector.GasType': ...
    def getLocation(self) -> java.lang.String: ...
    def getLowerExplosiveLimit(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getResponseTime(self) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def isGasDetected(self, double: float) -> bool: ...
    def isHighAlarm(self, double: float) -> bool: ...
    def reset(self) -> None: ...
    def restoreTransientState(self, gasDetectorState: 'GasDetector.GasDetectorState') -> None: ...
    def setGasConcentration(self, double: float) -> None: ...
    def setGasSpecies(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLocation(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLowerExplosiveLimit(self, double: float) -> None: ...
    def setResponseTime(self, double: float) -> None: ...
    def toString(self) -> java.lang.String: ...
    class GasDetectorState(java.io.Serializable): ...
    class GasType(java.lang.Enum['GasDetector.GasType']):
        COMBUSTIBLE: typing.ClassVar['GasDetector.GasType'] = ...
        TOXIC: typing.ClassVar['GasDetector.GasType'] = ...
        OXYGEN: typing.ClassVar['GasDetector.GasType'] = ...
        def getDefaultUnit(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'GasDetector.GasType': ...
        @staticmethod
        def values() -> typing.MutableSequence['GasDetector.GasType']: ...

class LevelTransmitter(MeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], separator: jneqsim.process.equipment.separator.Separator): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], tank: jneqsim.process.equipment.tank.Tank): ...
    @typing.overload
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    @typing.overload
    def __init__(self, separator: jneqsim.process.equipment.separator.Separator): ...
    @typing.overload
    def __init__(self, tank: jneqsim.process.equipment.tank.Tank): ...
    def displayResult(self) -> None: ...
    def getLevelEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getSeparator(self) -> jneqsim.process.equipment.separator.Separator: ...
    def getTank(self) -> jneqsim.process.equipment.tank.Tank: ...
    def getVessel(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...

class OilLevelTransmitter(MeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], threePhaseSeparator: jneqsim.process.equipment.separator.ThreePhaseSeparator): ...
    @typing.overload
    def __init__(self, threePhaseSeparator: jneqsim.process.equipment.separator.ThreePhaseSeparator): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getOilThickness(self) -> float: ...
    def getSeparator(self) -> jneqsim.process.equipment.separator.ThreePhaseSeparator: ...

class PushButton(MeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['PushButton.PushButtonState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], blowdownValve: jneqsim.process.equipment.valve.BlowdownValve): ...
    def captureTransientState(self) -> 'PushButton.PushButtonState': ...
    def displayResult(self) -> None: ...
    def getLinkedBlowdownValve(self) -> jneqsim.process.equipment.valve.BlowdownValve: ...
    def getLinkedLogics(self) -> java.util.List[jneqsim.process.logic.ProcessLogic]: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def isAutoActivateValve(self) -> bool: ...
    def isPushed(self) -> bool: ...
    def linkToBlowdownValve(self, blowdownValve: jneqsim.process.equipment.valve.BlowdownValve) -> None: ...
    def linkToLogic(self, processLogic: jneqsim.process.logic.ProcessLogic) -> None: ...
    def push(self) -> None: ...
    def reset(self) -> None: ...
    def restoreTransientState(self, pushButtonState: 'PushButton.PushButtonState') -> None: ...
    def setAutoActivateValve(self, boolean: bool) -> None: ...
    def toString(self) -> java.lang.String: ...
    class PushButtonState(java.io.Serializable): ...

class StreamMeasurementDeviceBaseClass(MeasurementDeviceBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def setStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...

class WaterLevelTransmitter(MeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], threePhaseSeparator: jneqsim.process.equipment.separator.ThreePhaseSeparator): ...
    @typing.overload
    def __init__(self, threePhaseSeparator: jneqsim.process.equipment.separator.ThreePhaseSeparator): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getSeparator(self) -> jneqsim.process.equipment.separator.ThreePhaseSeparator: ...

class CombustionEmissionsCalculator(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @staticmethod
    def calculateCO2Emissions(map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]]) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def setComponents(self) -> None: ...

class CompositionAnalyzer(StreamMeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['CompositionAnalyzer.CompositionAnalyzerState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, string2: typing.Union[java.lang.String, str], analyzerPhase: 'CompositionAnalyzer.AnalyzerPhase'): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface, string: typing.Union[java.lang.String, str], analyzerPhase: 'CompositionAnalyzer.AnalyzerPhase'): ...
    def captureTransientState(self) -> 'CompositionAnalyzer.CompositionAnalyzerState': ...
    def displayResult(self) -> None: ...
    def getAnalyzerPhase(self) -> 'CompositionAnalyzer.AnalyzerPhase': ...
    def getComponentName(self) -> java.lang.String: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, compositionAnalyzerState: 'CompositionAnalyzer.CompositionAnalyzerState') -> None: ...
    class AnalyzerPhase(java.lang.Enum['CompositionAnalyzer.AnalyzerPhase']):
        OVERALL: typing.ClassVar['CompositionAnalyzer.AnalyzerPhase'] = ...
        GAS: typing.ClassVar['CompositionAnalyzer.AnalyzerPhase'] = ...
        LIQUID: typing.ClassVar['CompositionAnalyzer.AnalyzerPhase'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'CompositionAnalyzer.AnalyzerPhase': ...
        @staticmethod
        def values() -> typing.MutableSequence['CompositionAnalyzer.AnalyzerPhase']: ...
    class CompositionAnalyzerState(java.io.Serializable): ...

class CricondenbarAnalyser(StreamMeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['CricondenbarAnalyser.CricondenbarAnalyserState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def captureTransientState(self) -> 'CricondenbarAnalyser.CricondenbarAnalyserState': ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMeasuredValue2(self, string: typing.Union[java.lang.String, str], double: float) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, cricondenbarAnalyserState: 'CricondenbarAnalyser.CricondenbarAnalyserState') -> None: ...
    class CricondenbarAnalyserState(java.io.Serializable): ...

class DifferentialPressureFlowMeter(StreamMeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['DifferentialPressureFlowMeter.DifferentialPressureFlowMeterState']):
    MAX_PRESSURE_DROP_RATIO: typing.ClassVar[float] = ...
    def captureTransientState(self) -> 'DifferentialPressureFlowMeter.DifferentialPressureFlowMeterState': ...
    def displayResult(self) -> None: ...
    def getBetaRatio(self) -> float: ...
    def getDifferentialPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getDifferentialPressureTransmitter(self) -> DifferentialPressureTransmitter: ...
    def getExpansibilityFactor(self) -> float: ...
    def getIsentropicExponent(self) -> float: ...
    def getMassFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getPipeDiameter(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getReynoldsNumberPipe(self) -> float: ...
    def getReynoldsNumberThroat(self) -> float: ...
    def getStandardVolumeFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getThroatDiameter(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def getValidityViolations(self) -> java.util.List[java.lang.String]: ...
    def getVolumeFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def isWithinExpansibilityPressureRatio(self) -> bool: ...
    def isWithinValidityRange(self) -> bool: ...
    def restoreTransientState(self, differentialPressureFlowMeterState: 'DifferentialPressureFlowMeter.DifferentialPressureFlowMeterState') -> None: ...
    def setDifferentialPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDifferentialPressureTransmitter(self, differentialPressureTransmitter: DifferentialPressureTransmitter) -> None: ...
    def setDynamicViscosity(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setGasDensity(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setGeometry(self, double: float, double2: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setIsentropicExponent(self, double: float) -> None: ...
    def setPipeDiameter(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setThroatDiameter(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    class DifferentialPressureFlowMeterState(java.io.Serializable): ...

class HydrateEquilibriumTemperatureAnalyser(StreamMeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['HydrateEquilibriumTemperatureAnalyser.HydrateAnalyserState']):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def captureTransientState(self) -> 'HydrateEquilibriumTemperatureAnalyser.HydrateAnalyserState': ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getReferencePressure(self) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, hydrateAnalyserState: 'HydrateEquilibriumTemperatureAnalyser.HydrateAnalyserState') -> None: ...
    def setReferencePressure(self, double: float) -> None: ...
    class HydrateAnalyserState(java.io.Serializable): ...

class HydrocarbonDewPointAnalyser(StreamMeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['HydrocarbonDewPointAnalyser.HydrocarbonDewPointAnalyserState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def captureTransientState(self) -> 'HydrocarbonDewPointAnalyser.HydrocarbonDewPointAnalyserState': ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMethod(self) -> java.lang.String: ...
    def getReferencePressure(self) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, hydrocarbonDewPointAnalyserState: 'HydrocarbonDewPointAnalyser.HydrocarbonDewPointAnalyserState') -> None: ...
    def setMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReferencePressure(self, double: float) -> None: ...
    class HydrocarbonDewPointAnalyserState(java.io.Serializable): ...

class ImpurityMonitor(StreamMeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['ImpurityMonitor.ImpurityMonitorState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def addTrackedComponent(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def addTrackedComponent(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def captureTransientState(self) -> 'ImpurityMonitor.ImpurityMonitorState': ...
    def displayResult(self) -> None: ...
    def getBulkMoleFraction(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getEnrichmentFactor(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getFullReport(self) -> java.util.Map[java.lang.String, java.util.Map[java.lang.String, float]]: ...
    def getGasPhaseFraction(self) -> float: ...
    def getGasPhaseMoleFraction(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getLiquidPhaseMoleFraction(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getNumberOfPhases(self) -> int: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def isAlarmExceeded(self, string: typing.Union[java.lang.String, str]) -> bool: ...
    def restoreTransientState(self, impurityMonitorState: 'ImpurityMonitor.ImpurityMonitorState') -> None: ...
    def setPrimaryComponent(self, string: typing.Union[java.lang.String, str]) -> None: ...
    class ImpurityMonitorState(java.io.Serializable): ...

class MolarMassAnalyser(StreamMeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['MolarMassAnalyser.MolarMassAnalyserState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def captureTransientState(self) -> 'MolarMassAnalyser.MolarMassAnalyserState': ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, molarMassAnalyserState: 'MolarMassAnalyser.MolarMassAnalyserState') -> None: ...
    class MolarMassAnalyserState(java.io.Serializable): ...

class MultiPhaseMeter(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> float: ...
    def getPressure(self) -> float: ...
    def getTemperature(self) -> float: ...
    def setPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class NMVOCAnalyser(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getnmVOCFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...

class PressureTransmitter(StreamMeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['PressureTransmitter.PressureTransmitterState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def applyFieldValue(self) -> None: ...
    def captureTransientState(self) -> 'PressureTransmitter.PressureTransmitterState': ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, pressureTransmitterState: 'PressureTransmitter.PressureTransmitterState') -> None: ...
    class PressureTransmitterState(java.io.Serializable): ...

class TemperatureTransmitter(StreamMeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['TemperatureTransmitter.TemperatureTransmitterState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def applyFieldValue(self) -> None: ...
    def captureTransientState(self) -> 'TemperatureTransmitter.TemperatureTransmitterState': ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, temperatureTransmitterState: 'TemperatureTransmitter.TemperatureTransmitterState') -> None: ...
    class TemperatureTransmitterState(java.io.Serializable): ...

class VolumeFlowTransmitter(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def applyFieldValue(self) -> None: ...
    def displayResult(self) -> None: ...
    def getMeasuredPhaseNumber(self) -> int: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def setMeasuredPhaseNumber(self, int: int) -> None: ...

class WaterContentAnalyser(StreamMeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['WaterContentAnalyser.WaterContentAnalyserState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def captureTransientState(self) -> 'WaterContentAnalyser.WaterContentAnalyserState': ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, waterContentAnalyserState: 'WaterContentAnalyser.WaterContentAnalyserState') -> None: ...
    class WaterContentAnalyserState(java.io.Serializable): ...

class WaterDewPointAnalyser(StreamMeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['WaterDewPointAnalyser.WaterDewPointAnalyserState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def captureTransientState(self) -> 'WaterDewPointAnalyser.WaterDewPointAnalyserState': ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMethod(self) -> java.lang.String: ...
    def getReferencePressure(self) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, waterDewPointAnalyserState: 'WaterDewPointAnalyser.WaterDewPointAnalyserState') -> None: ...
    def setMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReferencePressure(self, double: float) -> None: ...
    class WaterDewPointAnalyserState(java.io.Serializable): ...

class WellAllocator(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> float: ...
    def setExportGasStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setExportOilStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...

class pHProbe(StreamMeasurementDeviceBaseClass, jneqsim.process.dynamics.TransientStateParticipant['pHProbe.PHProbeState']):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def captureTransientState(self) -> 'pHProbe.PHProbeState': ...
    def getAlkalinity(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTransientStateCoverageIssue(self) -> java.lang.String: ...
    def getTransientStateIdentity(self) -> java.lang.String: ...
    def restoreTransientState(self, pHProbeState: 'pHProbe.PHProbeState') -> None: ...
    def run(self) -> None: ...
    def setAlkalinity(self, double: float) -> None: ...
    class PHProbeState(java.io.Serializable): ...

class ConeFlowMeter(DifferentialPressureFlowMeter):
    DISCHARGE_COEFFICIENT: typing.ClassVar[float] = ...
    MIN_PIPE_DIAMETER_MM: typing.ClassVar[float] = ...
    MAX_PIPE_DIAMETER_MM: typing.ClassVar[float] = ...
    MIN_BETA: typing.ClassVar[float] = ...
    MAX_BETA: typing.ClassVar[float] = ...
    MIN_REYNOLDS_NUMBER: typing.ClassVar[float] = ...
    MAX_REYNOLDS_NUMBER: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getConeDiameter(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getValidityViolations(self) -> java.util.List[java.lang.String]: ...
    def setGeometry(self, double: float, double2: float, string: typing.Union[java.lang.String, str]) -> None: ...

class NozzleFlowMeter(DifferentialPressureFlowMeter):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getNozzleType(self) -> 'NozzleFlowMeter.NozzleType': ...
    def getValidityViolations(self) -> java.util.List[java.lang.String]: ...
    def setNozzleType(self, nozzleType: 'NozzleFlowMeter.NozzleType') -> None: ...
    class NozzleType(java.lang.Enum['NozzleFlowMeter.NozzleType']):
        ISA_1932: typing.ClassVar['NozzleFlowMeter.NozzleType'] = ...
        LONG_RADIUS: typing.ClassVar['NozzleFlowMeter.NozzleType'] = ...
        THROAT_TAPPED: typing.ClassVar['NozzleFlowMeter.NozzleType'] = ...
        VENTURI_NOZZLE: typing.ClassVar['NozzleFlowMeter.NozzleType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'NozzleFlowMeter.NozzleType': ...
        @staticmethod
        def values() -> typing.MutableSequence['NozzleFlowMeter.NozzleType']: ...

class OrificeFlowMeter(DifferentialPressureFlowMeter):
    MIN_ORIFICE_DIAMETER_MM: typing.ClassVar[float] = ...
    MIN_PIPE_DIAMETER_MM: typing.ClassVar[float] = ...
    MAX_PIPE_DIAMETER_MM: typing.ClassVar[float] = ...
    MIN_BETA: typing.ClassVar[float] = ...
    MAX_BETA: typing.ClassVar[float] = ...
    WET_GAS_MIN_BETA: typing.ClassVar[float] = ...
    WET_GAS_MAX_BETA: typing.ClassVar[float] = ...
    MIN_FROUDE_NUMBER: typing.ClassVar[float] = ...
    MIN_DENSITY_RATIO: typing.ClassVar[float] = ...
    PRESSURE_LOSS_ROUTE_MIN_BETA: typing.ClassVar[float] = ...
    PRESSURE_LOSS_ROUTE_MAX_BETA: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getChisholmCoefficient(self) -> float: ...
    def getChisholmExponent(self) -> float: ...
    def getGasDensiometricFroudeNumber(self) -> float: ...
    def getLockhartMartinelliParameter(self) -> float: ...
    def getOverReadingFactor(self) -> float: ...
    def getPressureLoss(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getTappingArrangement(self) -> 'OrificeFlowMeter.TappingArrangement': ...
    def getValidityViolations(self) -> java.util.List[java.lang.String]: ...
    def getWetGasCorrelation(self) -> 'OrificeFlowMeter.WetGasCorrelation': ...
    def isLiquidFromStream(self) -> bool: ...
    def setGravitationalAcceleration(self, double: float) -> None: ...
    def setLiquidDensity(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLiquidFromStream(self, boolean: bool) -> None: ...
    def setLiquidMassFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLiquidToGasMassRatio(self, double: float) -> None: ...
    def setPressureLoss(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTappingArrangement(self, tappingArrangement: 'OrificeFlowMeter.TappingArrangement') -> None: ...
    def setWetGasCorrelation(self, wetGasCorrelation: 'OrificeFlowMeter.WetGasCorrelation') -> None: ...
    class TappingArrangement(java.lang.Enum['OrificeFlowMeter.TappingArrangement']):
        CORNER: typing.ClassVar['OrificeFlowMeter.TappingArrangement'] = ...
        D_AND_D_HALF: typing.ClassVar['OrificeFlowMeter.TappingArrangement'] = ...
        FLANGE: typing.ClassVar['OrificeFlowMeter.TappingArrangement'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'OrificeFlowMeter.TappingArrangement': ...
        @staticmethod
        def values() -> typing.MutableSequence['OrificeFlowMeter.TappingArrangement']: ...
    class WetGasCorrelation(java.lang.Enum['OrificeFlowMeter.WetGasCorrelation']):
        NONE: typing.ClassVar['OrificeFlowMeter.WetGasCorrelation'] = ...
        ISO_TR_11583: typing.ClassVar['OrificeFlowMeter.WetGasCorrelation'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'OrificeFlowMeter.WetGasCorrelation': ...
        @staticmethod
        def values() -> typing.MutableSequence['OrificeFlowMeter.WetGasCorrelation']: ...

class VenturiFlowMeter(DifferentialPressureFlowMeter):
    ISO_5167_4_MAX_PRESSURE_DROP_RATIO: typing.ClassVar[float] = ...
    DEFAULT_DISCHARGE_COEFFICIENT: typing.ClassVar[float] = ...
    H_HYDROCARBON: typing.ClassVar[float] = ...
    H_WATER_AMBIENT: typing.ClassVar[float] = ...
    H_WATER_WET_STEAM: typing.ClassVar[float] = ...
    DE_LEEUW_MIN_FROUDE_NUMBER: typing.ClassVar[float] = ...
    DE_LEEUW_REFERENCE_BETA: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getChisholmCoefficient(self) -> float: ...
    def getChisholmExponent(self) -> float: ...
    def getDischargeCoefficient(self) -> float: ...
    def getEffectiveDischargeCoefficient(self) -> float: ...
    def getGasDensiometricFroudeNumber(self) -> float: ...
    def getLockhartMartinelliParameter(self) -> float: ...
    def getOverReadingFactor(self) -> float: ...
    def getPressureLoss(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getRelativeUncertaintyOfCOverPhi(self) -> float: ...
    def getSurfaceTensionFactor(self) -> float: ...
    def getThroatFroudeNumber(self) -> float: ...
    def getValidityViolations(self) -> java.util.List[java.lang.String]: ...
    def getWetGasCorrelation(self) -> 'VenturiFlowMeter.WetGasCorrelation': ...
    def isLiquidFromStream(self) -> bool: ...
    def isUseWetGasDischargeCoefficient(self) -> bool: ...
    def isWithinDeLeeuwValidityRange(self) -> bool: ...
    def isWithinIso11583ValidityRange(self) -> bool: ...
    def isWithinIso5167ValidityRange(self) -> bool: ...
    def setDischargeCoefficient(self, double: float) -> None: ...
    def setGravitationalAcceleration(self, double: float) -> None: ...
    def setLiquidDensity(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLiquidFromStream(self, boolean: bool) -> None: ...
    def setLiquidMassFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLiquidToGasMassRatio(self, double: float) -> None: ...
    def setPressureLoss(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSurfaceTensionFactor(self, double: float) -> None: ...
    def setUseWetGasDischargeCoefficient(self, boolean: bool) -> None: ...
    def setWetGasCorrelation(self, wetGasCorrelation: 'VenturiFlowMeter.WetGasCorrelation') -> None: ...
    class WetGasCorrelation(java.lang.Enum['VenturiFlowMeter.WetGasCorrelation']):
        NONE: typing.ClassVar['VenturiFlowMeter.WetGasCorrelation'] = ...
        ISO_TR_11583: typing.ClassVar['VenturiFlowMeter.WetGasCorrelation'] = ...
        DE_LEEUW: typing.ClassVar['VenturiFlowMeter.WetGasCorrelation'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'VenturiFlowMeter.WetGasCorrelation': ...
        @staticmethod
        def values() -> typing.MutableSequence['VenturiFlowMeter.WetGasCorrelation']: ...

class WedgeFlowMeter(DifferentialPressureFlowMeter):
    MIN_PIPE_DIAMETER_MM: typing.ClassVar[float] = ...
    MAX_PIPE_DIAMETER_MM: typing.ClassVar[float] = ...
    MIN_BETA: typing.ClassVar[float] = ...
    MAX_BETA: typing.ClassVar[float] = ...
    MIN_REYNOLDS_NUMBER: typing.ClassVar[float] = ...
    MAX_REYNOLDS_NUMBER: typing.ClassVar[float] = ...
    DISCHARGE_COEFFICIENT_UNCERTAINTY: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getValidityViolations(self) -> java.util.List[java.lang.String]: ...
    def getWedgeRatio(self) -> float: ...
    def setGeometry(self, double: float, double2: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setWedgeRatio(self, double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.measurementdevice")``.

    CombustionEmissionsCalculator: typing.Type[CombustionEmissionsCalculator]
    CompositionAnalyzer: typing.Type[CompositionAnalyzer]
    CompressorMonitor: typing.Type[CompressorMonitor]
    ConeFlowMeter: typing.Type[ConeFlowMeter]
    CricondenbarAnalyser: typing.Type[CricondenbarAnalyser]
    DifferentialPressureFlowMeter: typing.Type[DifferentialPressureFlowMeter]
    DifferentialPressureTransmitter: typing.Type[DifferentialPressureTransmitter]
    ExpansibilityModel: typing.Type[ExpansibilityModel]
    FireDetector: typing.Type[FireDetector]
    FlowInducedVibrationAnalyser: typing.Type[FlowInducedVibrationAnalyser]
    FlowRatioMeter: typing.Type[FlowRatioMeter]
    GasDetector: typing.Type[GasDetector]
    HydrateEquilibriumTemperatureAnalyser: typing.Type[HydrateEquilibriumTemperatureAnalyser]
    HydrocarbonDewPointAnalyser: typing.Type[HydrocarbonDewPointAnalyser]
    ImpurityMonitor: typing.Type[ImpurityMonitor]
    InstrumentTagRole: typing.Type[InstrumentTagRole]
    LevelTransmitter: typing.Type[LevelTransmitter]
    MeasurementDeviceBaseClass: typing.Type[MeasurementDeviceBaseClass]
    MeasurementDeviceInterface: typing.Type[MeasurementDeviceInterface]
    MolarMassAnalyser: typing.Type[MolarMassAnalyser]
    MultiPhaseMeter: typing.Type[MultiPhaseMeter]
    NMVOCAnalyser: typing.Type[NMVOCAnalyser]
    NozzleFlowMeter: typing.Type[NozzleFlowMeter]
    OilLevelTransmitter: typing.Type[OilLevelTransmitter]
    OrificeFlowMeter: typing.Type[OrificeFlowMeter]
    PressureTransmitter: typing.Type[PressureTransmitter]
    PushButton: typing.Type[PushButton]
    SensorFaultType: typing.Type[SensorFaultType]
    StreamMeasurementDeviceBaseClass: typing.Type[StreamMeasurementDeviceBaseClass]
    TemperatureTransmitter: typing.Type[TemperatureTransmitter]
    VenturiFlowMeter: typing.Type[VenturiFlowMeter]
    VolumeFlowTransmitter: typing.Type[VolumeFlowTransmitter]
    WaterContentAnalyser: typing.Type[WaterContentAnalyser]
    WaterDewPointAnalyser: typing.Type[WaterDewPointAnalyser]
    WaterLevelTransmitter: typing.Type[WaterLevelTransmitter]
    WedgeFlowMeter: typing.Type[WedgeFlowMeter]
    WellAllocator: typing.Type[WellAllocator]
    pHProbe: typing.Type[pHProbe]
    online: jneqsim.process.measurementdevice.online.__module_protocol__
    simpleflowregime: jneqsim.process.measurementdevice.simpleflowregime.__module_protocol__
    vfm: jneqsim.process.measurementdevice.vfm.__module_protocol__
