
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.alarm
import jneqsim.process.equipment.compressor
import jneqsim.process.equipment.pipeline
import jneqsim.process.equipment.separator
import jneqsim.process.equipment.stream
import jneqsim.process.equipment.valve
import jneqsim.process.logic
import jneqsim.process.measurementdevice.online
import jneqsim.process.measurementdevice.simpleflowregime
import jneqsim.util
import typing



class MeasurementDeviceInterface(jneqsim.util.NamedInterface, java.io.Serializable):
    def acknowledgeAlarm(self, double: float) -> jneqsim.process.alarm.AlarmEvent: ...
    def displayResult(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def evaluateAlarm(self, double: float, double2: float, double3: float) -> java.util.List[jneqsim.process.alarm.AlarmEvent]: ...
    def getAlarmConfig(self) -> jneqsim.process.alarm.AlarmConfig: ...
    def getAlarmState(self) -> jneqsim.process.alarm.AlarmState: ...
    def getMaximumValue(self) -> float: ...
    def getMeasuredPercentValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    def getMinimumValue(self) -> float: ...
    def getOnlineSignal(self) -> jneqsim.process.measurementdevice.online.OnlineSignal: ...
    def getOnlineValue(self) -> float: ...
    def getUnit(self) -> java.lang.String: ...
    def hashCode(self) -> int: ...
    def isLogging(self) -> bool: ...
    def isOnlineSignal(self) -> bool: ...
    def setAlarmConfig(self, alarmConfig: jneqsim.process.alarm.AlarmConfig) -> None: ...
    def setLogging(self, boolean: bool) -> None: ...
    def setMaximumValue(self, double: float) -> None: ...
    def setMinimumValue(self, double: float) -> None: ...
    def setUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...

class MeasurementDeviceBaseClass(jneqsim.util.NamedBaseClass, MeasurementDeviceInterface):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def acknowledgeAlarm(self, double: float) -> jneqsim.process.alarm.AlarmEvent: ...
    def displayResult(self) -> None: ...
    def doConditionAnalysis(self) -> bool: ...
    def evaluateAlarm(self, double: float, double2: float, double3: float) -> java.util.List[jneqsim.process.alarm.AlarmEvent]: ...
    def getAlarmConfig(self) -> jneqsim.process.alarm.AlarmConfig: ...
    def getAlarmState(self) -> jneqsim.process.alarm.AlarmState: ...
    def getConditionAnalysisMaxDeviation(self) -> float: ...
    def getConditionAnalysisMessage(self) -> java.lang.String: ...
    def getDelaySteps(self) -> int: ...
    def getMaximumValue(self) -> float: ...
    def getMeasuredPercentValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMinimumValue(self) -> float: ...
    def getNoiseStdDev(self) -> float: ...
    def getOnlineMeasurementValue(self) -> float: ...
    def getOnlineSignal(self) -> jneqsim.process.measurementdevice.online.OnlineSignal: ...
    def getUnit(self) -> java.lang.String: ...
    def isLogging(self) -> bool: ...
    def isOnlineSignal(self) -> bool: ...
    def runConditionAnalysis(self) -> None: ...
    def setAlarmConfig(self, alarmConfig: jneqsim.process.alarm.AlarmConfig) -> None: ...
    def setConditionAnalysis(self, boolean: bool) -> None: ...
    def setConditionAnalysisMaxDeviation(self, double: float) -> None: ...
    def setDelaySteps(self, int: int) -> None: ...
    def setIsOnlineSignal(self, boolean: bool, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> None: ...
    def setLogging(self, boolean: bool) -> None: ...
    def setMaximumValue(self, double: float) -> None: ...
    def setMinimumValue(self, double: float) -> None: ...
    def setNoiseStdDev(self, double: float) -> None: ...
    def setOnlineMeasurementValue(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setOnlineSignal(self, onlineSignal: jneqsim.process.measurementdevice.online.OnlineSignal) -> None: ...
    def setQualityCheckMessage(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRandomSeed(self, long: int) -> None: ...
    def setUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...

class CompressorMonitor(MeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], compressor: jneqsim.process.equipment.compressor.Compressor): ...
    @typing.overload
    def __init__(self, compressor: jneqsim.process.equipment.compressor.Compressor): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...

class FireDetector(MeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def detectFire(self) -> None: ...
    def displayResult(self) -> None: ...
    def getDetectionDelay(self) -> float: ...
    def getDetectionThreshold(self) -> float: ...
    def getLocation(self) -> java.lang.String: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getSignalLevel(self) -> float: ...
    def isFireDetected(self) -> bool: ...
    def reset(self) -> None: ...
    def setDetectionDelay(self, double: float) -> None: ...
    def setDetectionThreshold(self, double: float) -> None: ...
    def setLocation(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSignalLevel(self, double: float) -> None: ...
    def toString(self) -> java.lang.String: ...

class FlowInducedVibrationAnalyser(MeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills): ...
    @typing.overload
    def __init__(self, pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMethod(self) -> java.lang.String: ...
    def setFRMSConstant(self, double: float) -> None: ...
    def setMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSegment(self, int: int) -> None: ...
    def setSupportArrangement(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSupportDistance(self, double: float) -> None: ...

class GasDetector(MeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], gasType: 'GasDetector.GasType'): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], gasType: 'GasDetector.GasType', string2: typing.Union[java.lang.String, str]): ...
    def convertPercentLELToPpm(self, double: float) -> float: ...
    def convertPpmToPercentLEL(self, double: float) -> float: ...
    def displayResult(self) -> None: ...
    def getGasConcentration(self) -> float: ...
    def getGasSpecies(self) -> java.lang.String: ...
    def getGasType(self) -> 'GasDetector.GasType': ...
    def getLocation(self) -> java.lang.String: ...
    def getLowerExplosiveLimit(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getResponseTime(self) -> float: ...
    def isGasDetected(self, double: float) -> bool: ...
    def isHighAlarm(self, double: float) -> bool: ...
    def reset(self) -> None: ...
    def setGasConcentration(self, double: float) -> None: ...
    def setGasSpecies(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLocation(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLowerExplosiveLimit(self, double: float) -> None: ...
    def setResponseTime(self, double: float) -> None: ...
    def toString(self) -> java.lang.String: ...
    class GasType(java.lang.Enum['GasDetector.GasType']):
        COMBUSTIBLE: typing.ClassVar['GasDetector.GasType'] = ...
        TOXIC: typing.ClassVar['GasDetector.GasType'] = ...
        OXYGEN: typing.ClassVar['GasDetector.GasType'] = ...
        def getDefaultUnit(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'GasDetector.GasType': ...
        @staticmethod
        def values() -> typing.MutableSequence['GasDetector.GasType']: ...

class LevelTransmitter(MeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], separator: jneqsim.process.equipment.separator.Separator): ...
    @typing.overload
    def __init__(self, separator: jneqsim.process.equipment.separator.Separator): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...

class OilLevelTransmitter(MeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], threePhaseSeparator: jneqsim.process.equipment.separator.ThreePhaseSeparator): ...
    @typing.overload
    def __init__(self, threePhaseSeparator: jneqsim.process.equipment.separator.ThreePhaseSeparator): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getOilThickness(self) -> float: ...

class PushButton(MeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], blowdownValve: jneqsim.process.equipment.valve.BlowdownValve): ...
    def displayResult(self) -> None: ...
    def getLinkedBlowdownValve(self) -> jneqsim.process.equipment.valve.BlowdownValve: ...
    def getLinkedLogics(self) -> java.util.List[jneqsim.process.logic.ProcessLogic]: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def isAutoActivateValve(self) -> bool: ...
    def isPushed(self) -> bool: ...
    def linkToBlowdownValve(self, blowdownValve: jneqsim.process.equipment.valve.BlowdownValve) -> None: ...
    def linkToLogic(self, processLogic: jneqsim.process.logic.ProcessLogic) -> None: ...
    def push(self) -> None: ...
    def reset(self) -> None: ...
    def setAutoActivateValve(self, boolean: bool) -> None: ...
    def toString(self) -> java.lang.String: ...

class StreamMeasurementDeviceBaseClass(MeasurementDeviceBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def setStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...

class WaterLevelTransmitter(MeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], threePhaseSeparator: jneqsim.process.equipment.separator.ThreePhaseSeparator): ...
    @typing.overload
    def __init__(self, threePhaseSeparator: jneqsim.process.equipment.separator.ThreePhaseSeparator): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...

class CombustionEmissionsCalculator(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @staticmethod
    def calculateCO2Emissions(map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]]) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def setComponents(self) -> None: ...

class CricondenbarAnalyser(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMeasuredValue2(self, string: typing.Union[java.lang.String, str], double: float) -> float: ...

class HydrateEquilibriumTemperatureAnalyser(StreamMeasurementDeviceBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getReferencePressure(self) -> float: ...
    def setReferencePressure(self, double: float) -> None: ...

class HydrocarbonDewPointAnalyser(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMethod(self) -> java.lang.String: ...
    def getReferencePressure(self) -> float: ...
    def setMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReferencePressure(self, double: float) -> None: ...

class MolarMassAnalyser(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...

class MultiPhaseMeter(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> float: ...
    def getPressure(self) -> float: ...
    def getTemperature(self) -> float: ...
    def setPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class NMVOCAnalyser(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getnmVOCFlowRate(self, string: typing.Union[java.lang.String, str]) -> float: ...

class PressureTransmitter(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...

class TemperatureTransmitter(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...

class VolumeFlowTransmitter(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    def getMeasuredPhaseNumber(self) -> int: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def setMeasuredPhaseNumber(self, int: int) -> None: ...

class WaterContentAnalyser(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...

class WaterDewPointAnalyser(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def displayResult(self) -> None: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getMethod(self) -> java.lang.String: ...
    def getReferencePressure(self) -> float: ...
    def setMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReferencePressure(self, double: float) -> None: ...

class WellAllocator(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> float: ...
    def setExportGasStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def setExportOilStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...

class pHProbe(StreamMeasurementDeviceBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getAlkalinity(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def run(self) -> None: ...
    def setAlkalinity(self, double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.measurementdevice")``.

    CombustionEmissionsCalculator: typing.Type[CombustionEmissionsCalculator]
    CompressorMonitor: typing.Type[CompressorMonitor]
    CricondenbarAnalyser: typing.Type[CricondenbarAnalyser]
    FireDetector: typing.Type[FireDetector]
    FlowInducedVibrationAnalyser: typing.Type[FlowInducedVibrationAnalyser]
    GasDetector: typing.Type[GasDetector]
    HydrateEquilibriumTemperatureAnalyser: typing.Type[HydrateEquilibriumTemperatureAnalyser]
    HydrocarbonDewPointAnalyser: typing.Type[HydrocarbonDewPointAnalyser]
    LevelTransmitter: typing.Type[LevelTransmitter]
    MeasurementDeviceBaseClass: typing.Type[MeasurementDeviceBaseClass]
    MeasurementDeviceInterface: typing.Type[MeasurementDeviceInterface]
    MolarMassAnalyser: typing.Type[MolarMassAnalyser]
    MultiPhaseMeter: typing.Type[MultiPhaseMeter]
    NMVOCAnalyser: typing.Type[NMVOCAnalyser]
    OilLevelTransmitter: typing.Type[OilLevelTransmitter]
    PressureTransmitter: typing.Type[PressureTransmitter]
    PushButton: typing.Type[PushButton]
    StreamMeasurementDeviceBaseClass: typing.Type[StreamMeasurementDeviceBaseClass]
    TemperatureTransmitter: typing.Type[TemperatureTransmitter]
    VolumeFlowTransmitter: typing.Type[VolumeFlowTransmitter]
    WaterContentAnalyser: typing.Type[WaterContentAnalyser]
    WaterDewPointAnalyser: typing.Type[WaterDewPointAnalyser]
    WaterLevelTransmitter: typing.Type[WaterLevelTransmitter]
    WellAllocator: typing.Type[WellAllocator]
    pHProbe: typing.Type[pHProbe]
    online: jneqsim.process.measurementdevice.online.__module_protocol__
    simpleflowregime: jneqsim.process.measurementdevice.simpleflowregime.__module_protocol__
