import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jneqsim.process.electricaldesign
import jneqsim.process.equipment
import typing

class HeatExchangerElectricalDesign(jneqsim.process.electricaldesign.ElectricalDesign):
    def __init__(
        self,
        processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface,
    ): ...
    def calcDesign(self) -> None: ...
    def getCoolingWaterPumpKW(self) -> float: ...
    def getFanEfficiency(self) -> float: ...
    def getHeatExchangerType(
        self,
    ) -> "HeatExchangerElectricalDesign.HeatExchangerType": ...
    def getInstrumentationKW(self) -> float: ...
    def getNumberOfFans(self) -> int: ...
    def getTotalAuxiliaryKW(self) -> float: ...
    def getTotalConnectedLoadKW(self) -> float: ...
    def readDesignSpecifications(self) -> None: ...
    def setCoolingWaterPumpKW(self, double: float) -> None: ...
    def setFanEfficiency(self, double: float) -> None: ...
    def setHeatExchangerType(
        self, heatExchangerType: "HeatExchangerElectricalDesign.HeatExchangerType"
    ) -> None: ...
    def setInstrumentationKW(self, double: float) -> None: ...
    def setNumberOfFans(self, int: int) -> None: ...

    class HeatExchangerType(
        java.lang.Enum["HeatExchangerElectricalDesign.HeatExchangerType"]
    ):
        ELECTRIC_HEATER: typing.ClassVar[
            "HeatExchangerElectricalDesign.HeatExchangerType"
        ] = ...
        AIR_COOLER: typing.ClassVar[
            "HeatExchangerElectricalDesign.HeatExchangerType"
        ] = ...
        SHELL_AND_TUBE: typing.ClassVar[
            "HeatExchangerElectricalDesign.HeatExchangerType"
        ] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str]
        ) -> "HeatExchangerElectricalDesign.HeatExchangerType": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["HeatExchangerElectricalDesign.HeatExchangerType"]
        ): ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.electricaldesign.heatexchanger")``.

    HeatExchangerElectricalDesign: typing.Type[HeatExchangerElectricalDesign]
