import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import java.util.function
import jneqsim.process
import jneqsim.process.controllerdevice.structure
import jneqsim.process.equipment.iec81346
import jneqsim.process.measurementdevice
import jneqsim.util
import typing

class ControllerDeviceInterface(jneqsim.process.ProcessElementInterface):
    def addGainSchedulePoint(
        self, double: float, double2: float, double3: float, double4: float
    ) -> None: ...
    @typing.overload
    def autoTune(self, double: float, double2: float) -> None: ...
    @typing.overload
    def autoTune(self, double: float, double2: float, boolean: bool) -> None: ...
    @typing.overload
    def autoTuneFromEventLog(self) -> bool: ...
    @typing.overload
    def autoTuneFromEventLog(self, boolean: bool) -> bool: ...
    @typing.overload
    def autoTuneStepResponse(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    @typing.overload
    def autoTuneStepResponse(
        self, double: float, double2: float, double3: float, boolean: bool
    ) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getControllerSetPoint(self) -> float: ...
    def getEventLog(self) -> java.util.List["ControllerEvent"]: ...
    def getIntegralAbsoluteError(self) -> float: ...
    def getManualOutput(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getMode(self) -> "ControllerDeviceInterface.ControllerMode": ...
    def getResponse(self) -> float: ...
    def getSetpointWeight(self) -> float: ...
    def getSettlingTime(self) -> float: ...
    def getStepResponseTuningMethod(
        self,
    ) -> "ControllerDeviceInterface.StepResponseTuningMethod": ...
    def getUnit(self) -> java.lang.String: ...
    def hashCode(self) -> int: ...
    def isActive(self) -> bool: ...
    def isReverseActing(self) -> bool: ...
    def resetEventLog(self) -> None: ...
    def resetPerformanceMetrics(self) -> None: ...
    @typing.overload
    def runTransient(
        self, double: float, double2: float, uUID: java.util.UUID
    ) -> None: ...
    @typing.overload
    def runTransient(self, double: float, double2: float) -> None: ...
    def setActive(self, boolean: bool) -> None: ...
    def setControllerParameters(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    @typing.overload
    def setControllerSetPoint(self, double: float) -> None: ...
    @typing.overload
    def setControllerSetPoint(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setDerivativeFilterTime(self, double: float) -> None: ...
    def setManualOutput(self, double: float) -> None: ...
    def setMode(
        self, controllerMode: "ControllerDeviceInterface.ControllerMode"
    ) -> None: ...
    def setOutputLimits(self, double: float, double2: float) -> None: ...
    def setReverseActing(self, boolean: bool) -> None: ...
    def setSetpointWeight(self, double: float) -> None: ...
    def setStepResponseTuningMethod(
        self,
        stepResponseTuningMethod: "ControllerDeviceInterface.StepResponseTuningMethod",
    ) -> None: ...
    def setTransmitter(
        self,
        measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface,
    ) -> None: ...
    def setUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...

    class ControllerMode(java.lang.Enum["ControllerDeviceInterface.ControllerMode"]):
        AUTO: typing.ClassVar["ControllerDeviceInterface.ControllerMode"] = ...
        MANUAL: typing.ClassVar["ControllerDeviceInterface.ControllerMode"] = ...
        CASCADE: typing.ClassVar["ControllerDeviceInterface.ControllerMode"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "ControllerDeviceInterface.ControllerMode": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["ControllerDeviceInterface.ControllerMode"]
        ): ...

    class StepResponseTuningMethod(
        java.lang.Enum["ControllerDeviceInterface.StepResponseTuningMethod"]
    ):
        CLASSIC: typing.ClassVar[
            "ControllerDeviceInterface.StepResponseTuningMethod"
        ] = ...
        SIMC: typing.ClassVar["ControllerDeviceInterface.StepResponseTuningMethod"] = (
            ...
        )
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "ControllerDeviceInterface.StepResponseTuningMethod": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["ControllerDeviceInterface.StepResponseTuningMethod"]
        ): ...

class ControllerEvent(java.io.Serializable):
    def __init__(
        self,
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
    ): ...
    def getError(self) -> float: ...
    def getMeasuredValue(self) -> float: ...
    def getResponse(self) -> float: ...
    def getSetPoint(self) -> float: ...
    def getTime(self) -> float: ...

class SequentialFunctionChart(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addStep(self, sfcStep: "SequentialFunctionChart.SfcStep") -> None: ...
    def addTimedTransition(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        double: float,
    ) -> None: ...
    def addTransition(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        booleanSupplier: typing.Union[
            java.util.function.BooleanSupplier, typing.Callable
        ],
    ) -> None: ...
    def getActiveStepName(self) -> java.lang.String: ...
    def getElapsedTimeInStep(self) -> float: ...
    def getEventHistory(self) -> java.util.List[java.lang.String]: ...
    def getName(self) -> java.lang.String: ...
    def getStepNames(self) -> java.util.List[java.lang.String]: ...
    def getTotalElapsedTime(self) -> float: ...
    def isRunning(self) -> bool: ...
    def runStep(self, double: float) -> None: ...
    def setInitialStep(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

    class SfcStep(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def getActiveAction(self) -> java.lang.Runnable: ...
        def getEntryAction(self) -> java.lang.Runnable: ...
        def getExitAction(self) -> java.lang.Runnable: ...
        def getName(self) -> java.lang.String: ...
        def setActiveAction(
            self, runnable: typing.Union[java.lang.Runnable, typing.Callable]
        ) -> None: ...
        def setEntryAction(
            self, runnable: typing.Union[java.lang.Runnable, typing.Callable]
        ) -> None: ...
        def setExitAction(
            self, runnable: typing.Union[java.lang.Runnable, typing.Callable]
        ) -> None: ...

    class SfcTransition(java.io.Serializable):
        def __init__(
            self,
            string: typing.Union[java.lang.String, str],
            string2: typing.Union[java.lang.String, str],
            booleanSupplier: typing.Union[
                java.util.function.BooleanSupplier, typing.Callable
            ],
        ): ...
        def getFromStep(self) -> java.lang.String: ...
        def getGuard(self) -> java.util.function.BooleanSupplier: ...
        def getToStep(self) -> java.lang.String: ...

class ControllerDeviceBaseClass(jneqsim.util.NamedBaseClass, ControllerDeviceInterface):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addGainSchedulePoint(
        self, double: float, double2: float, double3: float, double4: float
    ) -> None: ...
    @typing.overload
    def autoTune(self, double: float, double2: float) -> None: ...
    @typing.overload
    def autoTune(self, double: float, double2: float, boolean: bool) -> None: ...
    @typing.overload
    def autoTuneFromEventLog(self) -> bool: ...
    @typing.overload
    def autoTuneFromEventLog(self, boolean: bool) -> bool: ...
    @typing.overload
    def autoTuneStepResponse(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    @typing.overload
    def autoTuneStepResponse(
        self, double: float, double2: float, double3: float, boolean: bool
    ) -> None: ...
    def getControllerSetPoint(self) -> float: ...
    def getEventLog(self) -> java.util.List[ControllerEvent]: ...
    def getIntegralAbsoluteError(self) -> float: ...
    def getKp(self) -> float: ...
    def getManualOutput(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getMode(self) -> ControllerDeviceInterface.ControllerMode: ...
    def getReferenceDesignation(
        self,
    ) -> jneqsim.process.equipment.iec81346.ReferenceDesignation: ...
    def getReferenceDesignationString(self) -> java.lang.String: ...
    def getResponse(self) -> float: ...
    def getSetpointWeight(self) -> float: ...
    def getSettlingTime(self) -> float: ...
    def getStepResponseTuningMethod(
        self,
    ) -> ControllerDeviceInterface.StepResponseTuningMethod: ...
    def getTd(self) -> float: ...
    def getTi(self) -> float: ...
    def getUnit(self) -> java.lang.String: ...
    def isActive(self) -> bool: ...
    def isReverseActing(self) -> bool: ...
    def resetEventLog(self) -> None: ...
    def resetPerformanceMetrics(self) -> None: ...
    @typing.overload
    def runTransient(self, double: float, double2: float) -> None: ...
    @typing.overload
    def runTransient(
        self, double: float, double2: float, uUID: java.util.UUID
    ) -> None: ...
    def setActive(self, boolean: bool) -> None: ...
    def setControllerParameters(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    @typing.overload
    def setControllerSetPoint(self, double: float) -> None: ...
    @typing.overload
    def setControllerSetPoint(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setDerivativeFilterTime(self, double: float) -> None: ...
    def setKp(self, double: float) -> None: ...
    def setManualOutput(self, double: float) -> None: ...
    def setMode(
        self, controllerMode: ControllerDeviceInterface.ControllerMode
    ) -> None: ...
    def setOutputLimits(self, double: float, double2: float) -> None: ...
    def setReferenceDesignation(
        self,
        referenceDesignation: jneqsim.process.equipment.iec81346.ReferenceDesignation,
    ) -> None: ...
    def setReverseActing(self, boolean: bool) -> None: ...
    def setSetpointWeight(self, double: float) -> None: ...
    def setStepResponseTuningMethod(
        self,
        stepResponseTuningMethod: ControllerDeviceInterface.StepResponseTuningMethod,
    ) -> None: ...
    def setTd(self, double: float) -> None: ...
    def setTi(self, double: float) -> None: ...
    def setTransmitter(
        self,
        measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface,
    ) -> None: ...
    def setUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...

class LogicBlock(jneqsim.util.NamedBaseClass, ControllerDeviceInterface):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        operator: "LogicBlock.Operator",
    ): ...
    def addFixedInput(self, boolean: bool) -> None: ...
    @typing.overload
    def addInput(self, logicBlock: "LogicBlock") -> None: ...
    @typing.overload
    def addInput(
        self,
        measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface,
        double: float,
        comparator: "LogicBlock.Comparator",
    ) -> None: ...
    def getControllerSetPoint(self) -> float: ...
    def getInputs(self) -> java.util.List["LogicBlock.LogicInput"]: ...
    @typing.overload
    def getMeasuredValue(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    def getOperator(self) -> "LogicBlock.Operator": ...
    def getOutput(self) -> float: ...
    def getOutputBoolean(self) -> bool: ...
    def getResponse(self) -> float: ...
    def getUnit(self) -> java.lang.String: ...
    def isActive(self) -> bool: ...
    def isReverseActing(self) -> bool: ...
    @typing.overload
    def runTransient(self, double: float, double2: float) -> None: ...
    @typing.overload
    def runTransient(
        self, double: float, double2: float, uUID: java.util.UUID
    ) -> None: ...
    def setActive(self, boolean: bool) -> None: ...
    def setControllerParameters(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    @typing.overload
    def setControllerSetPoint(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    @typing.overload
    def setControllerSetPoint(self, double: float) -> None: ...
    def setEqualityTolerance(self, double: float) -> None: ...
    def setReverseActing(self, boolean: bool) -> None: ...
    def setTransmitter(
        self,
        measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface,
    ) -> None: ...
    def setUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...

    class Comparator(java.lang.Enum["LogicBlock.Comparator"]):
        GREATER_THAN: typing.ClassVar["LogicBlock.Comparator"] = ...
        GREATER_EQUAL: typing.ClassVar["LogicBlock.Comparator"] = ...
        LESS_THAN: typing.ClassVar["LogicBlock.Comparator"] = ...
        LESS_EQUAL: typing.ClassVar["LogicBlock.Comparator"] = ...
        EQUAL: typing.ClassVar["LogicBlock.Comparator"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "LogicBlock.Comparator": ...
        @staticmethod
        def values() -> typing.MutableSequence["LogicBlock.Comparator"]: ...

    class LogicInput(java.io.Serializable):
        def __init__(
            self,
            measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface,
            double: float,
            comparator: "LogicBlock.Comparator",
        ): ...
        def evaluate(self, double: float) -> bool: ...
        def getComparator(self) -> "LogicBlock.Comparator": ...
        def getDevice(
            self,
        ) -> jneqsim.process.measurementdevice.MeasurementDeviceInterface: ...
        def getThreshold(self) -> float: ...

    class Operator(java.lang.Enum["LogicBlock.Operator"]):
        AND: typing.ClassVar["LogicBlock.Operator"] = ...
        OR: typing.ClassVar["LogicBlock.Operator"] = ...
        NOT: typing.ClassVar["LogicBlock.Operator"] = ...
        NAND: typing.ClassVar["LogicBlock.Operator"] = ...
        NOR: typing.ClassVar["LogicBlock.Operator"] = ...
        XOR: typing.ClassVar["LogicBlock.Operator"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "LogicBlock.Operator": ...
        @staticmethod
        def values() -> typing.MutableSequence["LogicBlock.Operator"]: ...

class ModelPredictiveController(jneqsim.util.NamedBaseClass, ControllerDeviceInterface):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addQualityConstraint(
        self, qualityConstraint: "ModelPredictiveController.QualityConstraint"
    ) -> None: ...
    @typing.overload
    def autoTune(self, double: float, double2: float) -> None: ...
    @typing.overload
    def autoTune(self, double: float, double2: float, boolean: bool) -> None: ...
    @typing.overload
    def autoTune(self) -> "ModelPredictiveController.AutoTuneResult": ...
    @typing.overload
    def autoTune(
        self,
        list: java.util.List[float],
        list2: java.util.List[float],
        list3: java.util.List[float],
        autoTuneConfiguration: "ModelPredictiveController.AutoTuneConfiguration",
    ) -> "ModelPredictiveController.AutoTuneResult": ...
    @typing.overload
    def autoTune(
        self, autoTuneConfiguration: "ModelPredictiveController.AutoTuneConfiguration"
    ) -> "ModelPredictiveController.AutoTuneResult": ...
    def clearMovingHorizonHistory(self) -> None: ...
    def clearQualityConstraints(self) -> None: ...
    def configureControls(
        self, *string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def disableMovingHorizonEstimation(self) -> None: ...
    def enableMovingHorizonEstimation(self, int: int) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCalcIdentifier(self) -> java.util.UUID: ...
    def getControlNames(self) -> java.util.List[java.lang.String]: ...
    @typing.overload
    def getControlValue(self, int: int) -> float: ...
    @typing.overload
    def getControlValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getControlVector(self) -> typing.MutableSequence[float]: ...
    def getControlWeight(self) -> float: ...
    def getControllerSetPoint(self) -> float: ...
    def getLastAppliedControl(self) -> float: ...
    def getLastMovingHorizonEstimate(
        self,
    ) -> "ModelPredictiveController.MovingHorizonEstimate": ...
    def getLastSampleTime(self) -> float: ...
    def getLastSampledValue(self) -> float: ...
    def getMaxResponse(self) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    @typing.overload
    def getMeasuredValue(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getMinResponse(self) -> float: ...
    def getMoveWeight(self) -> float: ...
    def getMovingHorizonEstimationWindow(self) -> int: ...
    def getOutputWeight(self) -> float: ...
    def getPredictedQuality(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    def getPredictedTrajectory(
        self, int: int, double: float
    ) -> typing.MutableSequence[float]: ...
    def getPredictionHorizon(self) -> int: ...
    def getProcessBias(self) -> float: ...
    def getProcessGain(self) -> float: ...
    def getResponse(self) -> float: ...
    def getTimeConstant(self) -> float: ...
    def getUnit(self) -> java.lang.String: ...
    def hashCode(self) -> int: ...
    @typing.overload
    def ingestPlantSample(self, double: float, double2: float) -> None: ...
    @typing.overload
    def ingestPlantSample(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    def isActive(self) -> bool: ...
    def isMovingHorizonEstimationEnabled(self) -> bool: ...
    def isReverseActing(self) -> bool: ...
    @typing.overload
    def runTransient(self, double: float, double2: float) -> None: ...
    @typing.overload
    def runTransient(
        self, double: float, double2: float, uUID: java.util.UUID
    ) -> None: ...
    def setActive(self, boolean: bool) -> None: ...
    @typing.overload
    def setControlLimits(self, int: int, double: float, double2: float) -> None: ...
    @typing.overload
    def setControlLimits(
        self, string: typing.Union[java.lang.String, str], double: float, double2: float
    ) -> None: ...
    @typing.overload
    def setControlMoveLimits(self, int: int, double: float, double2: float) -> None: ...
    @typing.overload
    def setControlMoveLimits(
        self, string: typing.Union[java.lang.String, str], double: float, double2: float
    ) -> None: ...
    def setControlWeights(self, *double: float) -> None: ...
    def setControllerParameters(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    @typing.overload
    def setControllerSetPoint(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    @typing.overload
    def setControllerSetPoint(self, double: float) -> None: ...
    def setEnergyReference(self, double: float) -> None: ...
    def setEnergyReferenceVector(self, *double: float) -> None: ...
    def setInitialControlValues(self, *double: float) -> None: ...
    def setMoveLimits(self, double: float, double2: float) -> None: ...
    def setMoveWeights(self, *double: float) -> None: ...
    def setOutputLimits(self, double: float, double2: float) -> None: ...
    def setPredictionHorizon(self, int: int) -> None: ...
    def setPreferredControlValue(self, double: float) -> None: ...
    def setPreferredControlVector(self, *double: float) -> None: ...
    def setPrimaryControlIndex(self, int: int) -> None: ...
    def setProcessBias(self, double: float) -> None: ...
    @typing.overload
    def setProcessModel(self, double: float, double2: float) -> None: ...
    @typing.overload
    def setProcessModel(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    def setReverseActing(self, boolean: bool) -> None: ...
    def setTransmitter(
        self,
        measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface,
    ) -> None: ...
    def setUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setWeights(self, double: float, double2: float, double3: float) -> None: ...
    def updateFeedConditions(
        self,
        map: typing.Union[
            java.util.Map[typing.Union[java.lang.String, str], float],
            typing.Mapping[typing.Union[java.lang.String, str], float],
        ],
        double: float,
    ) -> None: ...
    def updateQualityMeasurement(
        self, string: typing.Union[java.lang.String, str], double: float
    ) -> bool: ...
    def updateQualityMeasurements(
        self,
        map: typing.Union[
            java.util.Map[typing.Union[java.lang.String, str], float],
            typing.Mapping[typing.Union[java.lang.String, str], float],
        ],
    ) -> None: ...

    class AutoTuneConfiguration:
        @staticmethod
        def builder() -> "ModelPredictiveController.AutoTuneConfiguration.Builder": ...
        def getClosedLoopTimeConstantRatio(self) -> float: ...
        def getControlWeightFactor(self) -> float: ...
        def getMaximumHorizon(self) -> int: ...
        def getMinimumHorizon(self) -> int: ...
        def getMoveWeightFactor(self) -> float: ...
        def getOutputWeight(self) -> float: ...
        def getPredictionHorizonMultiple(self) -> float: ...
        def getSampleTimeOverride(self) -> float: ...
        def isApplyImmediately(self) -> bool: ...

        class Builder:
            def applyImmediately(
                self, boolean: bool
            ) -> "ModelPredictiveController.AutoTuneConfiguration.Builder": ...
            def build(self) -> "ModelPredictiveController.AutoTuneConfiguration": ...
            def closedLoopTimeConstantRatio(
                self, double: float
            ) -> "ModelPredictiveController.AutoTuneConfiguration.Builder": ...
            def controlWeightFactor(
                self, double: float
            ) -> "ModelPredictiveController.AutoTuneConfiguration.Builder": ...
            def defaults(
                self,
            ) -> "ModelPredictiveController.AutoTuneConfiguration.Builder": ...
            def maximumHorizon(
                self, int: int
            ) -> "ModelPredictiveController.AutoTuneConfiguration.Builder": ...
            def minimumHorizon(
                self, int: int
            ) -> "ModelPredictiveController.AutoTuneConfiguration.Builder": ...
            def moveWeightFactor(
                self, double: float
            ) -> "ModelPredictiveController.AutoTuneConfiguration.Builder": ...
            def outputWeight(
                self, double: float
            ) -> "ModelPredictiveController.AutoTuneConfiguration.Builder": ...
            def predictionHorizonMultiple(
                self, double: float
            ) -> "ModelPredictiveController.AutoTuneConfiguration.Builder": ...
            def sampleTimeOverride(
                self, double: float
            ) -> "ModelPredictiveController.AutoTuneConfiguration.Builder": ...

    class AutoTuneResult:
        def getClosedLoopTimeConstant(self) -> float: ...
        def getControlWeight(self) -> float: ...
        def getMeanSquaredError(self) -> float: ...
        def getMoveWeight(self) -> float: ...
        def getOutputWeight(self) -> float: ...
        def getPredictionHorizon(self) -> int: ...
        def getProcessBias(self) -> float: ...
        def getProcessGain(self) -> float: ...
        def getSampleCount(self) -> int: ...
        def getSampleTime(self) -> float: ...
        def getTimeConstant(self) -> float: ...
        def isApplied(self) -> bool: ...

    class MovingHorizonEstimate:
        def getMeanSquaredError(self) -> float: ...
        def getProcessBias(self) -> float: ...
        def getProcessGain(self) -> float: ...
        def getSampleCount(self) -> int: ...
        def getTimeConstant(self) -> float: ...

    class QualityConstraint:
        @staticmethod
        def builder(
            string: typing.Union[java.lang.String, str],
        ) -> "ModelPredictiveController.QualityConstraint.Builder": ...

        class Builder:
            def build(self) -> "ModelPredictiveController.QualityConstraint": ...
            def compositionSensitivities(
                self,
                map: typing.Union[
                    java.util.Map[typing.Union[java.lang.String, str], float],
                    typing.Mapping[typing.Union[java.lang.String, str], float],
                ],
            ) -> "ModelPredictiveController.QualityConstraint.Builder": ...
            def compositionSensitivity(
                self, string: typing.Union[java.lang.String, str], double: float
            ) -> "ModelPredictiveController.QualityConstraint.Builder": ...
            def controlSensitivity(
                self, *double: float
            ) -> "ModelPredictiveController.QualityConstraint.Builder": ...
            def limit(
                self, double: float
            ) -> "ModelPredictiveController.QualityConstraint.Builder": ...
            def margin(
                self, double: float
            ) -> "ModelPredictiveController.QualityConstraint.Builder": ...
            def measurement(
                self,
                measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface,
            ) -> "ModelPredictiveController.QualityConstraint.Builder": ...
            def rateSensitivity(
                self, double: float
            ) -> "ModelPredictiveController.QualityConstraint.Builder": ...
            def unit(
                self, string: typing.Union[java.lang.String, str]
            ) -> "ModelPredictiveController.QualityConstraint.Builder": ...

class TransferFunctionBlock(jneqsim.util.NamedBaseClass, ControllerDeviceInterface):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        type: "TransferFunctionBlock.Type",
    ): ...
    def getControllerSetPoint(self) -> float: ...
    def getDeadTime(self) -> float: ...
    def getGain(self) -> float: ...
    def getInputBias(self) -> float: ...
    def getLagTime(self) -> float: ...
    def getLagTime2(self) -> float: ...
    def getLeadTime(self) -> float: ...
    @typing.overload
    def getMeasuredValue(
        self, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    @typing.overload
    def getMeasuredValue(self) -> float: ...
    def getOutput(self) -> float: ...
    def getOutputBias(self) -> float: ...
    def getResponse(self) -> float: ...
    def getType(self) -> "TransferFunctionBlock.Type": ...
    def getUnit(self) -> java.lang.String: ...
    def isActive(self) -> bool: ...
    def isReverseActing(self) -> bool: ...
    def reset(self) -> None: ...
    @typing.overload
    def runTransient(self, double: float, double2: float) -> None: ...
    @typing.overload
    def runTransient(
        self, double: float, double2: float, uUID: java.util.UUID
    ) -> None: ...
    def setActive(self, boolean: bool) -> None: ...
    def setControllerParameters(
        self, double: float, double2: float, double3: float
    ) -> None: ...
    @typing.overload
    def setControllerSetPoint(
        self, double: float, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    @typing.overload
    def setControllerSetPoint(self, double: float) -> None: ...
    def setDeadTime(self, double: float) -> None: ...
    def setGain(self, double: float) -> None: ...
    def setInputBias(self, double: float) -> None: ...
    def setLagTime(self, double: float) -> None: ...
    def setLagTime2(self, double: float) -> None: ...
    def setLeadTime(self, double: float) -> None: ...
    def setOutputBias(self, double: float) -> None: ...
    def setReverseActing(self, boolean: bool) -> None: ...
    def setTransmitter(
        self,
        measurementDeviceInterface: jneqsim.process.measurementdevice.MeasurementDeviceInterface,
    ) -> None: ...
    def setUnit(self, string: typing.Union[java.lang.String, str]) -> None: ...

    class Type(java.lang.Enum["TransferFunctionBlock.Type"]):
        FIRST_ORDER_LAG: typing.ClassVar["TransferFunctionBlock.Type"] = ...
        LEAD_LAG: typing.ClassVar["TransferFunctionBlock.Type"] = ...
        DEAD_TIME: typing.ClassVar["TransferFunctionBlock.Type"] = ...
        SECOND_ORDER: typing.ClassVar["TransferFunctionBlock.Type"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "TransferFunctionBlock.Type": ...
        @staticmethod
        def values() -> typing.MutableSequence["TransferFunctionBlock.Type"]: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.controllerdevice")``.

    ControllerDeviceBaseClass: typing.Type[ControllerDeviceBaseClass]
    ControllerDeviceInterface: typing.Type[ControllerDeviceInterface]
    ControllerEvent: typing.Type[ControllerEvent]
    LogicBlock: typing.Type[LogicBlock]
    ModelPredictiveController: typing.Type[ModelPredictiveController]
    SequentialFunctionChart: typing.Type[SequentialFunctionChart]
    TransferFunctionBlock: typing.Type[TransferFunctionBlock]
    structure: jneqsim.process.controllerdevice.structure.__module_protocol__
