import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import jpype
import jneqsim.fluidmechanics.flownode
import jneqsim.fluidmechanics.flownode.fluidboundary.heatmasstransfercalc
import jneqsim.fluidmechanics.flownode.twophasenode.twophasepipeflownode
import jneqsim.fluidmechanics.flownode.twophasenode.twophasereactorflownode
import jneqsim.fluidmechanics.flownode.twophasenode.twophasestirredcellnode
import jneqsim.fluidmechanics.geometrydefinitions
import jneqsim.thermo.system
import typing

class TwoPhaseFlowNode(jneqsim.fluidmechanics.flownode.FlowNode):
    MIN_PHASE_FRACTION: typing.ClassVar[float] = ...
    NUCLEATION_PHASE_FRACTION: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        systemInterface: jneqsim.thermo.system.SystemInterface,
        geometryDefinitionInterface: jneqsim.fluidmechanics.geometrydefinitions.GeometryDefinitionInterface,
    ): ...
    def calcContactLength(self) -> float: ...
    def calcFluxes(self) -> None: ...
    def calcGasLiquidContactArea(self) -> float: ...
    def calcHydraulicDiameter(self) -> float: ...
    def calcInterfacialAreaPerVolume(self) -> float: ...
    def calcReynoldNumber(self) -> float: ...
    def calcWallFrictionFactor(self) -> float: ...
    def canCalculateMassTransfer(self) -> bool: ...
    def checkAndInitiatePhaseTransition(self) -> bool: ...
    def checkPhaseFormation(self) -> None: ...
    def clone(self) -> "TwoPhaseFlowNode": ...
    def enforceMinimumPhaseFractions(self) -> None: ...
    def getInterfacialAreaModel(
        self,
    ) -> (
        jneqsim.fluidmechanics.flownode.fluidboundary.heatmasstransfercalc.InterfacialAreaModel
    ): ...
    def getInterfacialAreaPerVolume(self) -> float: ...
    def getNucleationDiameter(self, boolean: bool) -> float: ...
    def init(self) -> None: ...
    def initFlowCalc(self) -> None: ...
    def initVelocity(self) -> float: ...
    def initiateBubbleNucleation(self) -> None: ...
    def initiateCondensation(self) -> None: ...
    def isBubbleNucleationLikely(self) -> bool: ...
    def isCondensationLikely(self) -> bool: ...
    def isEffectivelySinglePhaseGas(self) -> bool: ...
    def isEffectivelySinglePhaseLiquid(self) -> bool: ...
    def setFluxes(
        self, doubleArray: typing.Union[typing.List[float], jpype.JArray]
    ) -> None: ...
    def setInterfacialAreaModel(
        self,
        interfacialAreaModel: jneqsim.fluidmechanics.flownode.fluidboundary.heatmasstransfercalc.InterfacialAreaModel,
    ) -> None: ...
    def setUserDefinedInterfacialAreaPerVolume(self, double: float) -> None: ...
    @typing.overload
    def update(self) -> None: ...
    @typing.overload
    def update(self, double: float) -> None: ...
    def updateMolarFlow(self) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.fluidmechanics.flownode.twophasenode")``.

    TwoPhaseFlowNode: typing.Type[TwoPhaseFlowNode]
    twophasepipeflownode: (
        jneqsim.fluidmechanics.flownode.twophasenode.twophasepipeflownode.__module_protocol__
    )
    twophasereactorflownode: (
        jneqsim.fluidmechanics.flownode.twophasenode.twophasereactorflownode.__module_protocol__
    )
    twophasestirredcellnode: (
        jneqsim.fluidmechanics.flownode.twophasenode.twophasestirredcellnode.__module_protocol__
    )
