import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.mechanicaldesign
import typing

class CUIRiskAssessment(java.io.Serializable):
    def __init__(self): ...
    @staticmethod
    def assessRisk(
        double: float,
        boolean: bool,
        insulationType: "CUIRiskAssessment.InsulationType",
        double2: float,
        boolean2: bool,
    ) -> "CUIRiskAssessment.CUIRisk": ...
    @staticmethod
    def estimateRemainingLife(
        double: float, double2: float, double3: float
    ) -> float: ...
    @staticmethod
    def isInsulationSuitable(
        insulationType: "CUIRiskAssessment.InsulationType", double: float
    ) -> bool: ...
    @staticmethod
    def recommendedInspectionIntervalYears(
        cUIRisk: "CUIRiskAssessment.CUIRisk",
    ) -> int: ...
    @staticmethod
    def recommendedInspectionMethods(
        cUIRisk: "CUIRiskAssessment.CUIRisk",
    ) -> java.util.List[java.lang.String]: ...
    @staticmethod
    def temperatureRiskScore(double: float, boolean: bool) -> float: ...

    class CUIRisk(java.lang.Enum["CUIRiskAssessment.CUIRisk"]):
        LOW: typing.ClassVar["CUIRiskAssessment.CUIRisk"] = ...
        MEDIUM: typing.ClassVar["CUIRiskAssessment.CUIRisk"] = ...
        HIGH: typing.ClassVar["CUIRiskAssessment.CUIRisk"] = ...
        VERY_HIGH: typing.ClassVar["CUIRiskAssessment.CUIRisk"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "CUIRiskAssessment.CUIRisk": ...
        @staticmethod
        def values() -> typing.MutableSequence["CUIRiskAssessment.CUIRisk"]: ...

    class InsulationType(java.lang.Enum["CUIRiskAssessment.InsulationType"]):
        MINERAL_WOOL: typing.ClassVar["CUIRiskAssessment.InsulationType"] = ...
        CALCIUM_SILICATE: typing.ClassVar["CUIRiskAssessment.InsulationType"] = ...
        CELLULAR_GLASS: typing.ClassVar["CUIRiskAssessment.InsulationType"] = ...
        PIR_FOAM: typing.ClassVar["CUIRiskAssessment.InsulationType"] = ...
        PERLITE: typing.ClassVar["CUIRiskAssessment.InsulationType"] = ...
        AEROGEL: typing.ClassVar["CUIRiskAssessment.InsulationType"] = ...
        def absorbsMoisture(self) -> bool: ...
        def getCuiMultiplier(self) -> float: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "CUIRiskAssessment.InsulationType": ...
        @staticmethod
        def values() -> typing.MutableSequence["CUIRiskAssessment.InsulationType"]: ...

class DesignStandard(java.io.Serializable):
    equipment: jneqsim.process.mechanicaldesign.MechanicalDesign = ...
    standardName: java.lang.String = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def computeSafetyMargins(
        self,
    ) -> jneqsim.process.mechanicaldesign.MechanicalDesignMarginResult: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getEquipment(self) -> jneqsim.process.mechanicaldesign.MechanicalDesign: ...
    def getStandardName(self) -> java.lang.String: ...
    def hashCode(self) -> int: ...
    def setDesignStandardName(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setEquipment(
        self, mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign
    ) -> None: ...
    def setStandardName(self, string: typing.Union[java.lang.String, str]) -> None: ...

class FireProtectionDesign(java.io.Serializable):
    def __init__(self): ...
    @staticmethod
    def assessFireScenarios(
        string: typing.Union[java.lang.String, str],
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
    ) -> "FireProtectionDesign.FireScenarioResult": ...
    @staticmethod
    def bleveFireballDiameter(double: float) -> float: ...
    @staticmethod
    def bleveFireballDuration(double: float) -> float: ...
    @staticmethod
    def bleveOverpressure(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def blowdownTime(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
    ) -> float: ...
    @staticmethod
    def fireScenarioReport(
        list: java.util.List["FireProtectionDesign.FireScenarioResult"],
    ) -> java.lang.String: ...
    @staticmethod
    def firewaterDemand(
        double: float, double2: float, int: int, double3: float
    ) -> float: ...
    @staticmethod
    def jetFireFlameLength(double: float, double2: float) -> float: ...
    @staticmethod
    def meetsBlowdownRequirement(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
    ) -> bool: ...
    @staticmethod
    def pfpThickness(
        double: float, double2: float, double3: float, double4: float, double5: float
    ) -> float: ...
    @staticmethod
    def pointSourceRadiation(
        double: float, double2: float, double3: float
    ) -> float: ...
    @staticmethod
    def poolFireHeatRelease(
        double: float, double2: float, double3: float, double4: float
    ) -> float: ...
    @staticmethod
    def safeDistance(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def vesselPfpThickness(
        double: float, double2: float, double3: float, double4: float
    ) -> float: ...

    class FireScenarioResult(java.io.Serializable):
        equipmentName: java.lang.String = ...
        poolFireHeatReleaseKW: float = ...
        poolFireSafeDistanceM: float = ...
        jetFireFlameLengthM: float = ...
        jetFireSafeDistanceM: float = ...
        bleveFireballDiameterM: float = ...
        bleveFireballDurationS: float = ...
        bleveOverpressureAt50mKPa: float = ...
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def toJson(self) -> java.lang.String: ...

class InsulationDesign(java.io.Serializable):
    MAX_PERSONNEL_PROTECTION_TEMP_C: typing.ClassVar[float] = ...
    def __init__(self): ...
    @staticmethod
    def flatSurfaceThickness(
        double: float,
        double2: float,
        insulationMaterial: "InsulationDesign.InsulationMaterial",
        insulationPurpose: "InsulationDesign.InsulationPurpose",
        double3: float,
    ) -> float: ...
    @staticmethod
    def pipeHeatLossPerMeter(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        insulationMaterial: "InsulationDesign.InsulationMaterial",
        double5: float,
    ) -> float: ...
    @staticmethod
    def pipeInsulationWeightPerMeter(
        double: float,
        double2: float,
        insulationMaterial: "InsulationDesign.InsulationMaterial",
    ) -> float: ...
    @staticmethod
    def pipeThickness(
        double: float,
        double2: float,
        double3: float,
        insulationMaterial: "InsulationDesign.InsulationMaterial",
        insulationPurpose: "InsulationDesign.InsulationPurpose",
        double4: float,
    ) -> float: ...
    @staticmethod
    def selectMaterial(
        double: float, insulationPurpose: "InsulationDesign.InsulationPurpose"
    ) -> "InsulationDesign.InsulationMaterial": ...

    class InsulationMaterial(java.lang.Enum["InsulationDesign.InsulationMaterial"]):
        MINERAL_WOOL: typing.ClassVar["InsulationDesign.InsulationMaterial"] = ...
        CALCIUM_SILICATE: typing.ClassVar["InsulationDesign.InsulationMaterial"] = ...
        PIR_FOAM: typing.ClassVar["InsulationDesign.InsulationMaterial"] = ...
        AEROGEL: typing.ClassVar["InsulationDesign.InsulationMaterial"] = ...
        CELLULAR_GLASS: typing.ClassVar["InsulationDesign.InsulationMaterial"] = ...
        EXPANDED_PERLITE: typing.ClassVar["InsulationDesign.InsulationMaterial"] = ...
        def getConductivity(self, double: float) -> float: ...
        def getMaxTempC(self) -> float: ...
        def getTypicalDensityKgM3(self) -> float: ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "InsulationDesign.InsulationMaterial": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["InsulationDesign.InsulationMaterial"]
        ): ...

    class InsulationPurpose(java.lang.Enum["InsulationDesign.InsulationPurpose"]):
        HEAT_CONSERVATION: typing.ClassVar["InsulationDesign.InsulationPurpose"] = ...
        PERSONNEL_PROTECTION: typing.ClassVar["InsulationDesign.InsulationPurpose"] = (
            ...
        )
        PROCESS_MAINTENANCE: typing.ClassVar["InsulationDesign.InsulationPurpose"] = ...
        FROST_PROTECTION: typing.ClassVar["InsulationDesign.InsulationPurpose"] = ...
        FIRE_PROTECTION: typing.ClassVar["InsulationDesign.InsulationPurpose"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "InsulationDesign.InsulationPurpose": ...
        @staticmethod
        def values() -> (
            typing.MutableSequence["InsulationDesign.InsulationPurpose"]
        ): ...

class NoiseAssessment(java.io.Serializable):
    NORSOK_MAX_CONTINUOUS_DBA: typing.ClassVar[float] = ...
    NORSOK_MAX_EQUIPMENT_AREA_DBA: typing.ClassVar[float] = ...
    def __init__(self): ...
    @staticmethod
    def aggregateNoise(
        doubleArray: typing.Union[typing.List[float], jpype.JArray],
    ) -> float: ...
    @staticmethod
    def atmosphericAbsorption(
        double: float, double2: float, double3: float
    ) -> float: ...
    @staticmethod
    def compressorNoise(
        double: float, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    @staticmethod
    def exceedsNorsokLimit(double: float) -> bool: ...
    @staticmethod
    def flareNoise(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def pumpNoise(
        double: float, string: typing.Union[java.lang.String, str]
    ) -> float: ...
    @staticmethod
    def splAtDistance(double: float, double2: float) -> float: ...
    @staticmethod
    def splAtDistanceOctaveBand(
        double: float, double2: float, double3: float, double4: float
    ) -> float: ...
    @staticmethod
    def splAtDistanceWithAttenuation(
        double: float, double2: float, double3: float, double4: float
    ) -> float: ...
    @staticmethod
    def valveNoise(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
    ) -> float: ...

class PipingStressAnalysis(java.io.Serializable):
    def __init__(self): ...
    @staticmethod
    def allowableExpansionStressRange(
        double: float, double2: float, double3: float
    ) -> float: ...
    @staticmethod
    def codeStressCheck(
        double: float, double2: float, double3: float, double4: float
    ) -> bool: ...
    @staticmethod
    def expansionLoopLength(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def maxSupportSpan(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
    ) -> float: ...
    @staticmethod
    def momentOfInertia(double: float, double2: float) -> float: ...
    @staticmethod
    def sectionModulus(double: float, double2: float) -> float: ...
    @staticmethod
    def sustainedStress(
        double: float, double2: float, double3: float, double4: float, double5: float
    ) -> float: ...
    @typing.overload
    @staticmethod
    def thermalExpansion(double: float, double2: float, double3: float) -> float: ...
    @typing.overload
    @staticmethod
    def thermalExpansion(
        double: float, double2: float, double3: float, double4: float
    ) -> float: ...

class StandardRegistry:
    @staticmethod
    def clearVersionOverrides() -> None: ...
    @typing.overload
    @staticmethod
    def createStandard(
        standardType: "StandardType",
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ) -> DesignStandard: ...
    @typing.overload
    @staticmethod
    def createStandard(
        standardType: "StandardType",
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ) -> DesignStandard: ...
    @staticmethod
    def findByCode(string: typing.Union[java.lang.String, str]) -> "StandardType": ...
    @staticmethod
    def getAllCategories() -> java.util.List[java.lang.String]: ...
    @staticmethod
    def getAllStandards() -> typing.MutableSequence["StandardType"]: ...
    @staticmethod
    def getApplicableStandards(
        string: typing.Union[java.lang.String, str],
    ) -> java.util.List["StandardType"]: ...
    @staticmethod
    def getEffectiveVersion(standardType: "StandardType") -> java.lang.String: ...
    @staticmethod
    def getRecommendedStandards(
        string: typing.Union[java.lang.String, str],
    ) -> java.util.Map[java.lang.String, java.util.List["StandardType"]]: ...
    @staticmethod
    def getStandardsByCategory(
        string: typing.Union[java.lang.String, str],
    ) -> java.util.List["StandardType"]: ...
    @staticmethod
    def getStandardsByOrganization(
        string: typing.Union[java.lang.String, str],
    ) -> java.util.List["StandardType"]: ...
    @staticmethod
    def getSummary() -> java.lang.String: ...
    @staticmethod
    def isApplicable(
        standardType: "StandardType", string: typing.Union[java.lang.String, str]
    ) -> bool: ...
    @staticmethod
    def setVersionOverride(
        standardType: "StandardType", string: typing.Union[java.lang.String, str]
    ) -> None: ...

class StandardType(java.lang.Enum["StandardType"]):
    NORSOK_L_001: typing.ClassVar["StandardType"] = ...
    NORSOK_P_001: typing.ClassVar["StandardType"] = ...
    NORSOK_P_002: typing.ClassVar["StandardType"] = ...
    NORSOK_M_001: typing.ClassVar["StandardType"] = ...
    NORSOK_M_630: typing.ClassVar["StandardType"] = ...
    ASME_VIII_DIV1: typing.ClassVar["StandardType"] = ...
    ASME_VIII_DIV2: typing.ClassVar["StandardType"] = ...
    ASME_B31_3: typing.ClassVar["StandardType"] = ...
    ASME_B31_4: typing.ClassVar["StandardType"] = ...
    ASME_B31_8: typing.ClassVar["StandardType"] = ...
    API_617: typing.ClassVar["StandardType"] = ...
    API_610: typing.ClassVar["StandardType"] = ...
    API_650: typing.ClassVar["StandardType"] = ...
    API_620: typing.ClassVar["StandardType"] = ...
    API_660: typing.ClassVar["StandardType"] = ...
    API_661: typing.ClassVar["StandardType"] = ...
    API_521: typing.ClassVar["StandardType"] = ...
    API_526: typing.ClassVar["StandardType"] = ...
    API_5L: typing.ClassVar["StandardType"] = ...
    API_12J: typing.ClassVar["StandardType"] = ...
    DNV_ST_F101: typing.ClassVar["StandardType"] = ...
    DNV_OS_F101: typing.ClassVar["StandardType"] = ...
    DNV_RP_F105: typing.ClassVar["StandardType"] = ...
    ISO_13623: typing.ClassVar["StandardType"] = ...
    ISO_15649: typing.ClassVar["StandardType"] = ...
    ISO_16812: typing.ClassVar["StandardType"] = ...
    ASTM_A106: typing.ClassVar["StandardType"] = ...
    ASTM_A516: typing.ClassVar["StandardType"] = ...
    ASTM_A333: typing.ClassVar["StandardType"] = ...
    EN_13480: typing.ClassVar["StandardType"] = ...
    EN_13445: typing.ClassVar["StandardType"] = ...
    PD_5500: typing.ClassVar["StandardType"] = ...
    def appliesTo(self, string: typing.Union[java.lang.String, str]) -> bool: ...
    @staticmethod
    def fromCode(string: typing.Union[java.lang.String, str]) -> "StandardType": ...
    @staticmethod
    def getAllCategories() -> java.util.List[java.lang.String]: ...
    @staticmethod
    def getApiStandards() -> java.util.List["StandardType"]: ...
    def getApplicableEquipmentTypes(
        self,
    ) -> typing.MutableSequence[java.lang.String]: ...
    @staticmethod
    def getApplicableStandards(
        string: typing.Union[java.lang.String, str],
    ) -> java.util.List["StandardType"]: ...
    @staticmethod
    def getAsmeStandards() -> java.util.List["StandardType"]: ...
    @staticmethod
    def getAstmStandards() -> java.util.List["StandardType"]: ...
    @staticmethod
    def getByCategory(
        string: typing.Union[java.lang.String, str],
    ) -> java.util.List["StandardType"]: ...
    def getCode(self) -> java.lang.String: ...
    def getDefaultVersion(self) -> java.lang.String: ...
    def getDesignStandardCategory(self) -> java.lang.String: ...
    @staticmethod
    def getDnvStandards() -> java.util.List["StandardType"]: ...
    @staticmethod
    def getEnStandards() -> java.util.List["StandardType"]: ...
    @staticmethod
    def getIsoStandards() -> java.util.List["StandardType"]: ...
    def getName(self) -> java.lang.String: ...
    @staticmethod
    def getNorsokStandards() -> java.util.List["StandardType"]: ...
    def toString(self) -> java.lang.String: ...
    _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(
        class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]
    ) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> "StandardType": ...
    @staticmethod
    def values() -> typing.MutableSequence["StandardType"]: ...

class VibrationAssessment(java.io.Serializable):
    def __init__(self): ...
    @staticmethod
    def acousticPowerLevel(
        double: float, double2: float, double3: float, double4: float, double5: float
    ) -> float: ...
    @staticmethod
    def aivScreening(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
        double7: float,
    ) -> "VibrationAssessment.VibrationRisk": ...
    @staticmethod
    def aivScreeningLimit(double: float, double2: float) -> float: ...
    @staticmethod
    def fivHeatExchangerScreening(
        double: float,
        double2: float,
        double3: float,
        double4: float,
        double5: float,
        double6: float,
    ) -> "VibrationAssessment.VibrationRisk": ...
    @staticmethod
    def reciprocatingPulsationScreening(
        double: float, double2: float, double3: float, double4: float
    ) -> "VibrationAssessment.VibrationRisk": ...

    class VibrationRisk(java.lang.Enum["VibrationAssessment.VibrationRisk"]):
        LOW: typing.ClassVar["VibrationAssessment.VibrationRisk"] = ...
        MEDIUM: typing.ClassVar["VibrationAssessment.VibrationRisk"] = ...
        HIGH: typing.ClassVar["VibrationAssessment.VibrationRisk"] = ...
        _valueOf_0__T = typing.TypeVar("_valueOf_0__T", bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(
            class_: typing.Type[_valueOf_0__T],
            string: typing.Union[java.lang.String, str],
        ) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(
            string: typing.Union[java.lang.String, str],
        ) -> "VibrationAssessment.VibrationRisk": ...
        @staticmethod
        def values() -> typing.MutableSequence["VibrationAssessment.VibrationRisk"]: ...

class AbsorptionColumnDesignStandard(DesignStandard):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def getMolecularSieveWaterCapacity(self) -> float: ...
    def setMolecularSieveWaterCapacity(self, double: float) -> None: ...

class AdsorptionDehydrationDesignStandard(DesignStandard):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def getMolecularSieveWaterCapacity(self) -> float: ...
    def setMolecularSieveWaterCapacity(self, double: float) -> None: ...

class CompressorDesignStandard(DesignStandard):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def getCompressorFactor(self) -> float: ...
    def setCompressorFactor(self, double: float) -> None: ...

class GasScrubberDesignStandard(DesignStandard):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def getGasLoadFactor(self) -> float: ...
    def getVolumetricDesignFactor(self) -> float: ...

class JointEfficiencyPipelineStandard(DesignStandard):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def getJEFactor(self) -> float: ...
    def readJointEfficiencyStandard(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> None: ...
    def setJEFactor(self, double: float) -> None: ...

class JointEfficiencyPlateStandard(DesignStandard):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def getJEFactor(self) -> float: ...
    def readJointEfficiencyStandard(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> None: ...
    def setJEFactor(self, double: float) -> None: ...

class MaterialPipeDesignStandard(DesignStandard):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def getDesignFactor(self) -> float: ...
    def getEfactor(self) -> float: ...
    def getMinimumYeildStrength(self) -> float: ...
    def getTemperatureDeratingFactor(self) -> float: ...
    def readMaterialDesignStandard(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> None: ...
    def setDesignFactor(self, double: float) -> None: ...
    def setEfactor(self, double: float) -> None: ...
    def setMinimumYeildStrength(self, double: float) -> None: ...
    def setTemperatureDeratingFactor(self, double: float) -> None: ...

class MaterialPlateDesignStandard(DesignStandard):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def getDivisionClass(self) -> float: ...
    def readMaterialDesignStandard(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        string3: typing.Union[java.lang.String, str],
        int: int,
    ) -> None: ...
    def setDivisionClass(self, double: float) -> None: ...

class PipelineDesignStandard(DesignStandard):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def calcPipelineWallThickness(self) -> float: ...
    def getSafetyMargins(
        self,
    ) -> jneqsim.process.mechanicaldesign.MechanicalDesignMarginResult: ...

class PipingDesignStandard(DesignStandard):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...

class PressureVesselDesignStandard(DesignStandard):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def calcWallThickness(self) -> float: ...
    def getSafetyMargins(
        self,
    ) -> jneqsim.process.mechanicaldesign.MechanicalDesignMarginResult: ...

class ProcessDesignStandard(DesignStandard):
    DEFAULT_DESIGN_PRESSURE_MARGIN: typing.ClassVar[float] = ...
    DEFAULT_DESIGN_TEMPERATURE_MARGIN_C: typing.ClassVar[float] = ...
    DEFAULT_MIN_DESIGN_TEMPERATURE_C: typing.ClassVar[float] = ...
    DEFAULT_FLOW_SAFETY_FACTOR: typing.ClassVar[float] = ...
    DEFAULT_DUTY_MARGIN: typing.ClassVar[float] = ...
    DEFAULT_AREA_MARGIN: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    @typing.overload
    def __init__(
        self, mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign
    ): ...
    def calculateDesignArea(self, double: float) -> float: ...
    def calculateDesignDuty(self, double: float) -> float: ...
    def calculateDesignFlowRate(self, double: float) -> float: ...
    def calculateDesignPressure(self, double: float) -> float: ...
    def calculateDesignTemperature(self, double: float) -> float: ...
    def calculateMinDesignTemperature(self, double: float) -> float: ...
    def getAreaMargin(self) -> float: ...
    def getDesignPressureMargin(self) -> float: ...
    def getDesignTemperatureMarginC(self) -> float: ...
    def getDutyMargin(self) -> float: ...
    def getEquipmentType(self) -> java.lang.String: ...
    def getFlowSafetyFactor(self) -> float: ...
    def getMechanicalDesign(
        self,
    ) -> jneqsim.process.mechanicaldesign.MechanicalDesign: ...
    def getMinDesignTemperatureC(self) -> float: ...
    def getStandardName(self) -> java.lang.String: ...
    def setAreaMargin(self, double: float) -> None: ...
    def setDesignPressureMargin(self, double: float) -> None: ...
    def setDesignTemperatureMarginC(self, double: float) -> None: ...
    def setDutyMargin(self, double: float) -> None: ...
    def setEquipmentType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setFlowSafetyFactor(self, double: float) -> None: ...
    def setMinDesignTemperatureC(self, double: float) -> None: ...

class SeparatorDesignStandard(DesignStandard):
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def getFg(self) -> float: ...
    def getGasLoadFactor(self) -> float: ...
    def getLiquidRetentionTime(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ) -> float: ...
    def getSafetyMargins(
        self,
    ) -> jneqsim.process.mechanicaldesign.MechanicalDesignMarginResult: ...
    def getVolumetricDesignFactor(self) -> float: ...
    def setFg(self, double: float) -> None: ...
    def setVolumetricDesignFactor(self, double: float) -> None: ...

class ValveDesignStandard(DesignStandard):
    valveCvMax: float = ...
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign,
    ): ...
    def getValveCvMax(self) -> float: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.designstandards")``.

    AbsorptionColumnDesignStandard: typing.Type[AbsorptionColumnDesignStandard]
    AdsorptionDehydrationDesignStandard: typing.Type[
        AdsorptionDehydrationDesignStandard
    ]
    CUIRiskAssessment: typing.Type[CUIRiskAssessment]
    CompressorDesignStandard: typing.Type[CompressorDesignStandard]
    DesignStandard: typing.Type[DesignStandard]
    FireProtectionDesign: typing.Type[FireProtectionDesign]
    GasScrubberDesignStandard: typing.Type[GasScrubberDesignStandard]
    InsulationDesign: typing.Type[InsulationDesign]
    JointEfficiencyPipelineStandard: typing.Type[JointEfficiencyPipelineStandard]
    JointEfficiencyPlateStandard: typing.Type[JointEfficiencyPlateStandard]
    MaterialPipeDesignStandard: typing.Type[MaterialPipeDesignStandard]
    MaterialPlateDesignStandard: typing.Type[MaterialPlateDesignStandard]
    NoiseAssessment: typing.Type[NoiseAssessment]
    PipelineDesignStandard: typing.Type[PipelineDesignStandard]
    PipingDesignStandard: typing.Type[PipingDesignStandard]
    PipingStressAnalysis: typing.Type[PipingStressAnalysis]
    PressureVesselDesignStandard: typing.Type[PressureVesselDesignStandard]
    ProcessDesignStandard: typing.Type[ProcessDesignStandard]
    SeparatorDesignStandard: typing.Type[SeparatorDesignStandard]
    StandardRegistry: typing.Type[StandardRegistry]
    StandardType: typing.Type[StandardType]
    ValveDesignStandard: typing.Type[ValveDesignStandard]
    VibrationAssessment: typing.Type[VibrationAssessment]
