
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.process.mechanicaldesign
import jneqsim.process.util.report
import jneqsim.util.nucleation
import typing



class Filter(jneqsim.process.equipment.TwoPortEquipment):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getCvFactor(self) -> float: ...
    def getDeltaP(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def runConditionAnalysis(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    def setCvFactor(self, double: float) -> None: ...
    @typing.overload
    def setDeltaP(self, double: float) -> None: ...
    @typing.overload
    def setDeltaP(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...

class CharCoalFilter(Filter):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...

class SulfurFilter(Filter):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getChangeIntervalDays(self) -> float: ...
    def getChangeIntervalHours(self) -> float: ...
    def getEstimatedCaptureEfficiency(self) -> float: ...
    def getFilterElementCapacity(self) -> float: ...
    def getFilterType(self) -> java.lang.String: ...
    def getFiltrationRating(self) -> float: ...
    def getGasFlowRate(self) -> float: ...
    def getMeanParticleDiameterMicrons(self) -> float: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.MechanicalDesign: ...
    def getNucleationModel(self) -> jneqsim.util.nucleation.ClassicalNucleationTheory: ...
    def getNumberOfElements(self) -> int: ...
    def getParticleSizePercentilesUM(self) -> typing.MutableSequence[float]: ...
    def getRemovalEfficiency(self) -> float: ...
    def getResidenceTime(self) -> float: ...
    def getSolidS8MassFractionInlet(self) -> float: ...
    @typing.overload
    def getSolidSulfurRemovalRate(self) -> float: ...
    @typing.overload
    def getSolidSulfurRemovalRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getSupersaturationRatio(self) -> float: ...
    def initMechanicalDesign(self) -> None: ...
    def isSolidS8Detected(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setFilterElementCapacity(self, double: float) -> None: ...
    def setFilterType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setFiltrationRating(self, double: float) -> None: ...
    def setNumberOfElements(self, int: int) -> None: ...
    def setRemovalEfficiency(self, double: float) -> None: ...
    def setResidenceTime(self, double: float) -> None: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.filter")``.

    CharCoalFilter: typing.Type[CharCoalFilter]
    Filter: typing.Type[Filter]
    SulfurFilter: typing.Type[SulfurFilter]
