
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.process.equipment.heatexchanger
import jneqsim.process.mechanicaldesign
import typing



class HeatExchangerMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def getApproachTemperature(self) -> float: ...
    def getCalculatedUA(self) -> float: ...
    def getCandidateTypes(self) -> java.util.List['HeatExchangerType']: ...
    def getLogMeanTemperatureDifference(self) -> float: ...
    def getManualSelection(self) -> 'HeatExchangerType': ...
    def getSelectedSizingResult(self) -> 'HeatExchangerSizingResult': ...
    def getSelectedType(self) -> 'HeatExchangerType': ...
    def getSelectionCriterion(self) -> 'HeatExchangerMechanicalDesign.SelectionCriterion': ...
    def getSizingResults(self) -> java.util.List['HeatExchangerSizingResult']: ...
    def getSizingSummary(self) -> java.lang.String: ...
    def getUsedOverallHeatTransferCoefficient(self) -> float: ...
    @typing.overload
    def setCandidateTypes(self, list: java.util.List['HeatExchangerType']) -> None: ...
    @typing.overload
    def setCandidateTypes(self, *heatExchangerType: 'HeatExchangerType') -> None: ...
    def setManualSelection(self, heatExchangerType: 'HeatExchangerType') -> None: ...
    def setSelectionCriterion(self, selectionCriterion: 'HeatExchangerMechanicalDesign.SelectionCriterion') -> None: ...
    class SelectionCriterion(java.lang.Enum['HeatExchangerMechanicalDesign.SelectionCriterion']):
        MIN_AREA: typing.ClassVar['HeatExchangerMechanicalDesign.SelectionCriterion'] = ...
        MIN_WEIGHT: typing.ClassVar['HeatExchangerMechanicalDesign.SelectionCriterion'] = ...
        MIN_PRESSURE_DROP: typing.ClassVar['HeatExchangerMechanicalDesign.SelectionCriterion'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'HeatExchangerMechanicalDesign.SelectionCriterion': ...
        @staticmethod
        def values() -> typing.MutableSequence['HeatExchangerMechanicalDesign.SelectionCriterion']: ...

class HeatExchangerMechanicalDesignResponse(jneqsim.process.mechanicaldesign.MechanicalDesignResponse):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, heatExchangerMechanicalDesign: HeatExchangerMechanicalDesign): ...
    def getAreaMargin(self) -> float: ...
    def getBaffleCut(self) -> float: ...
    def getBaffleSpacing(self) -> float: ...
    def getBaffleThickness(self) -> float: ...
    def getBaffleType(self) -> java.lang.String: ...
    def getBundleWeight(self) -> float: ...
    def getChannelWeight(self) -> float: ...
    def getHeatDuty(self) -> float: ...
    def getHeatExchangerType(self) -> java.lang.String: ...
    def getHeatTransferArea(self) -> float: ...
    def getLmtd(self) -> float: ...
    def getLmtdCorrectionFactor(self) -> float: ...
    def getNumberOfBaffles(self) -> int: ...
    def getNumberOfShellPasses(self) -> int: ...
    def getNumberOfShells(self) -> int: ...
    def getNumberOfTubePasses(self) -> int: ...
    def getNumberOfTubes(self) -> int: ...
    def getOverallHeatTransferCoeff(self) -> float: ...
    def getRequiredArea(self) -> float: ...
    def getShellDesignPressure(self) -> float: ...
    def getShellDesignTemperature(self) -> float: ...
    def getShellFoulingResistance(self) -> float: ...
    def getShellInnerDiameter(self) -> float: ...
    def getShellMaterial(self) -> java.lang.String: ...
    def getShellPressureDrop(self) -> float: ...
    def getShellWallThickness(self) -> float: ...
    def getTemaType(self) -> java.lang.String: ...
    def getTubeDesignPressure(self) -> float: ...
    def getTubeDesignTemperature(self) -> float: ...
    def getTubeFoulingResistance(self) -> float: ...
    def getTubeLayoutAngle(self) -> int: ...
    def getTubeLength(self) -> float: ...
    def getTubeMaterial(self) -> java.lang.String: ...
    def getTubeOuterDiameter(self) -> float: ...
    def getTubePitch(self) -> float: ...
    def getTubePressureDrop(self) -> float: ...
    def getTubeWallThickness(self) -> float: ...
    def populateFromHeatExchangerDesign(self, heatExchangerMechanicalDesign: HeatExchangerMechanicalDesign) -> None: ...
    def setAreaMargin(self, double: float) -> None: ...
    def setBaffleCut(self, double: float) -> None: ...
    def setBaffleSpacing(self, double: float) -> None: ...
    def setBaffleThickness(self, double: float) -> None: ...
    def setBaffleType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setBundleWeight(self, double: float) -> None: ...
    def setChannelWeight(self, double: float) -> None: ...
    def setHeatDuty(self, double: float) -> None: ...
    def setHeatExchangerType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setHeatTransferArea(self, double: float) -> None: ...
    def setLmtd(self, double: float) -> None: ...
    def setLmtdCorrectionFactor(self, double: float) -> None: ...
    def setNumberOfBaffles(self, int: int) -> None: ...
    def setNumberOfShellPasses(self, int: int) -> None: ...
    def setNumberOfShells(self, int: int) -> None: ...
    def setNumberOfTubePasses(self, int: int) -> None: ...
    def setNumberOfTubes(self, int: int) -> None: ...
    def setOverallHeatTransferCoeff(self, double: float) -> None: ...
    def setRequiredArea(self, double: float) -> None: ...
    def setShellDesignPressure(self, double: float) -> None: ...
    def setShellDesignTemperature(self, double: float) -> None: ...
    def setShellFoulingResistance(self, double: float) -> None: ...
    def setShellInnerDiameter(self, double: float) -> None: ...
    def setShellMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setShellPressureDrop(self, double: float) -> None: ...
    def setShellWallThickness(self, double: float) -> None: ...
    def setTemaType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTubeDesignPressure(self, double: float) -> None: ...
    def setTubeDesignTemperature(self, double: float) -> None: ...
    def setTubeFoulingResistance(self, double: float) -> None: ...
    def setTubeLayoutAngle(self, int: int) -> None: ...
    def setTubeLength(self, double: float) -> None: ...
    def setTubeMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTubeOuterDiameter(self, double: float) -> None: ...
    def setTubePitch(self, double: float) -> None: ...
    def setTubePressureDrop(self, double: float) -> None: ...
    def setTubeWallThickness(self, double: float) -> None: ...

class HeatExchangerSizingResult:
    @staticmethod
    def builder() -> 'HeatExchangerSizingResult.Builder': ...
    def getApproachTemperature(self) -> float: ...
    def getEstimatedLength(self) -> float: ...
    def getEstimatedPressureDrop(self) -> float: ...
    def getEstimatedWeight(self) -> float: ...
    def getFinSurfaceArea(self) -> float: ...
    def getInnerDiameter(self) -> float: ...
    def getMetric(self, selectionCriterion: HeatExchangerMechanicalDesign.SelectionCriterion) -> float: ...
    def getModuleHeight(self) -> float: ...
    def getModuleLength(self) -> float: ...
    def getModuleWidth(self) -> float: ...
    def getOuterDiameter(self) -> float: ...
    def getOverallHeatTransferCoefficient(self) -> float: ...
    def getRequiredArea(self) -> float: ...
    def getRequiredUA(self) -> float: ...
    def getTubeCount(self) -> int: ...
    def getTubePasses(self) -> int: ...
    def getType(self) -> 'HeatExchangerType': ...
    def getWallThickness(self) -> float: ...
    def toString(self) -> java.lang.String: ...
    class Builder:
        def approachTemperature(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def build(self) -> 'HeatExchangerSizingResult': ...
        def estimatedLength(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def estimatedPressureDrop(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def estimatedWeight(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def finSurfaceArea(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def innerDiameter(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def moduleHeight(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def moduleLength(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def moduleWidth(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def outerDiameter(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def overallHeatTransferCoefficient(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def requiredArea(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def requiredUA(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...
        def tubeCount(self, int: int) -> 'HeatExchangerSizingResult.Builder': ...
        def tubePasses(self, int: int) -> 'HeatExchangerSizingResult.Builder': ...
        def type(self, heatExchangerType: 'HeatExchangerType') -> 'HeatExchangerSizingResult.Builder': ...
        def wallThickness(self, double: float) -> 'HeatExchangerSizingResult.Builder': ...

class HeatExchangerType(java.lang.Enum['HeatExchangerType']):
    SHELL_AND_TUBE: typing.ClassVar['HeatExchangerType'] = ...
    PLATE_AND_FRAME: typing.ClassVar['HeatExchangerType'] = ...
    AIR_COOLER: typing.ClassVar['HeatExchangerType'] = ...
    DOUBLE_PIPE: typing.ClassVar['HeatExchangerType'] = ...
    def createSizingResult(self, heatExchanger: jneqsim.process.equipment.heatexchanger.HeatExchanger, double: float, double2: float, double3: float) -> HeatExchangerSizingResult: ...
    def getAllowableApproachTemperature(self) -> float: ...
    def getDisplayName(self) -> java.lang.String: ...
    def getTypicalOverallHeatTransferCoefficient(self) -> float: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'HeatExchangerType': ...
    @staticmethod
    def values() -> typing.MutableSequence['HeatExchangerType']: ...

class ShellAndTubeDesignCalculator:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calculate(self) -> None: ...
    def getActualArea(self) -> float: ...
    def getBaffleCount(self) -> int: ...
    def getBaffleSpacing(self) -> float: ...
    def getOperatingWeight(self) -> float: ...
    def getRequiredArea(self) -> float: ...
    def getShellInsideDiameter(self) -> float: ...
    def getShellOutsideDiameter(self) -> float: ...
    def getShellWallThickness(self) -> float: ...
    def getTemaClass(self) -> 'TEMAStandard.TEMAClass': ...
    def getTemaDesignation(self) -> java.lang.String: ...
    def getTotalCost(self) -> float: ...
    def getTotalDryWeight(self) -> float: ...
    def getTubeCount(self) -> int: ...
    def setDesignTemperature(self, double: float) -> None: ...
    def setRequiredArea(self, double: float) -> None: ...
    def setShellSidePressure(self, double: float) -> None: ...
    def setTemaClass(self, tEMAClass: 'TEMAStandard.TEMAClass') -> None: ...
    def setTemaDesignation(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTubeLength(self, double: float) -> None: ...
    def setTubePasses(self, int: int) -> None: ...
    def setTubeSidePressure(self, double: float) -> None: ...
    def setTubeSize(self, standardTubeSize: 'TEMAStandard.StandardTubeSize') -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class TEMAStandard:
    @staticmethod
    def calculateMinTubePitch(double: float, tubePitchPattern: 'TEMAStandard.TubePitchPattern') -> float: ...
    @staticmethod
    def createConfiguration(char: str, char2: str, char3: str) -> 'TEMAStandard.TEMAConfiguration': ...
    @staticmethod
    def estimateTubeCount(double: float, double2: float, double3: float, tubePitchPattern: 'TEMAStandard.TubePitchPattern', int: int) -> int: ...
    @staticmethod
    def getCommonConfigurations() -> java.util.Map[java.lang.String, 'TEMAStandard.TEMAConfiguration']: ...
    @staticmethod
    def getConfiguration(string: typing.Union[java.lang.String, str]) -> 'TEMAStandard.TEMAConfiguration': ...
    @staticmethod
    def getMaxBaffleSpacing(double: float) -> float: ...
    @staticmethod
    def getMaxUnsupportedSpan(double: float, string: typing.Union[java.lang.String, str]) -> float: ...
    @staticmethod
    def getMinBaffleSpacing(double: float, tEMAClass: 'TEMAStandard.TEMAClass') -> float: ...
    @staticmethod
    def recommendConfiguration(boolean: bool, boolean2: bool, boolean3: bool, boolean4: bool) -> java.lang.String: ...
    class BaffleType(java.lang.Enum['TEMAStandard.BaffleType']):
        SINGLE_SEGMENTAL: typing.ClassVar['TEMAStandard.BaffleType'] = ...
        DOUBLE_SEGMENTAL: typing.ClassVar['TEMAStandard.BaffleType'] = ...
        TRIPLE_SEGMENTAL: typing.ClassVar['TEMAStandard.BaffleType'] = ...
        NO_TUBES_IN_WINDOW: typing.ClassVar['TEMAStandard.BaffleType'] = ...
        DISC_AND_DOUGHNUT: typing.ClassVar['TEMAStandard.BaffleType'] = ...
        ROD_BAFFLES: typing.ClassVar['TEMAStandard.BaffleType'] = ...
        def getDescription(self) -> java.lang.String: ...
        def getHeatTransferFactor(self) -> float: ...
        def getPressureDropFactor(self) -> float: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TEMAStandard.BaffleType': ...
        @staticmethod
        def values() -> typing.MutableSequence['TEMAStandard.BaffleType']: ...
    class FrontHeadType(java.lang.Enum['TEMAStandard.FrontHeadType']):
        A: typing.ClassVar['TEMAStandard.FrontHeadType'] = ...
        B: typing.ClassVar['TEMAStandard.FrontHeadType'] = ...
        C: typing.ClassVar['TEMAStandard.FrontHeadType'] = ...
        N: typing.ClassVar['TEMAStandard.FrontHeadType'] = ...
        D: typing.ClassVar['TEMAStandard.FrontHeadType'] = ...
        def getDescription(self) -> java.lang.String: ...
        def getNotes(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TEMAStandard.FrontHeadType': ...
        @staticmethod
        def values() -> typing.MutableSequence['TEMAStandard.FrontHeadType']: ...
    class RearHeadType(java.lang.Enum['TEMAStandard.RearHeadType']):
        L: typing.ClassVar['TEMAStandard.RearHeadType'] = ...
        M: typing.ClassVar['TEMAStandard.RearHeadType'] = ...
        N: typing.ClassVar['TEMAStandard.RearHeadType'] = ...
        P: typing.ClassVar['TEMAStandard.RearHeadType'] = ...
        S: typing.ClassVar['TEMAStandard.RearHeadType'] = ...
        T: typing.ClassVar['TEMAStandard.RearHeadType'] = ...
        U: typing.ClassVar['TEMAStandard.RearHeadType'] = ...
        W: typing.ClassVar['TEMAStandard.RearHeadType'] = ...
        def getDescription(self) -> java.lang.String: ...
        def getNotes(self) -> java.lang.String: ...
        def isFloating(self) -> bool: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TEMAStandard.RearHeadType': ...
        @staticmethod
        def values() -> typing.MutableSequence['TEMAStandard.RearHeadType']: ...
    class ShellType(java.lang.Enum['TEMAStandard.ShellType']):
        E: typing.ClassVar['TEMAStandard.ShellType'] = ...
        F: typing.ClassVar['TEMAStandard.ShellType'] = ...
        G: typing.ClassVar['TEMAStandard.ShellType'] = ...
        H: typing.ClassVar['TEMAStandard.ShellType'] = ...
        J: typing.ClassVar['TEMAStandard.ShellType'] = ...
        K: typing.ClassVar['TEMAStandard.ShellType'] = ...
        X: typing.ClassVar['TEMAStandard.ShellType'] = ...
        def getDescription(self) -> java.lang.String: ...
        def getNotes(self) -> java.lang.String: ...
        def getPressureDropFactor(self) -> float: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TEMAStandard.ShellType': ...
        @staticmethod
        def values() -> typing.MutableSequence['TEMAStandard.ShellType']: ...
    class StandardTubeSize(java.lang.Enum['TEMAStandard.StandardTubeSize']):
        TUBE_3_8_INCH: typing.ClassVar['TEMAStandard.StandardTubeSize'] = ...
        TUBE_1_2_INCH: typing.ClassVar['TEMAStandard.StandardTubeSize'] = ...
        TUBE_5_8_INCH: typing.ClassVar['TEMAStandard.StandardTubeSize'] = ...
        TUBE_3_4_INCH: typing.ClassVar['TEMAStandard.StandardTubeSize'] = ...
        TUBE_1_INCH: typing.ClassVar['TEMAStandard.StandardTubeSize'] = ...
        def getAvailableWallThicknessesMm(self) -> typing.MutableSequence[float]: ...
        def getOuterDiameterInch(self) -> float: ...
        def getOuterDiameterMm(self) -> float: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TEMAStandard.StandardTubeSize': ...
        @staticmethod
        def values() -> typing.MutableSequence['TEMAStandard.StandardTubeSize']: ...
    class TEMAClass(java.lang.Enum['TEMAStandard.TEMAClass']):
        R: typing.ClassVar['TEMAStandard.TEMAClass'] = ...
        C: typing.ClassVar['TEMAStandard.TEMAClass'] = ...
        B: typing.ClassVar['TEMAStandard.TEMAClass'] = ...
        def getCostFactor(self) -> float: ...
        def getDescription(self) -> java.lang.String: ...
        def getMinCorrosionAllowanceMm(self) -> float: ...
        def getMinTubeWallMm(self) -> float: ...
        def getNotes(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TEMAStandard.TEMAClass': ...
        @staticmethod
        def values() -> typing.MutableSequence['TEMAStandard.TEMAClass']: ...
    class TEMAConfiguration:
        def __init__(self, frontHeadType: 'TEMAStandard.FrontHeadType', shellType: 'TEMAStandard.ShellType', rearHeadType: 'TEMAStandard.RearHeadType', string: typing.Union[java.lang.String, str], set: java.util.Set['TEMAStandard.TEMAClass']): ...
        def getApplicableClasses(self) -> java.util.Set['TEMAStandard.TEMAClass']: ...
        def getCostFactor(self) -> float: ...
        def getDescription(self) -> java.lang.String: ...
        def getDesignation(self) -> java.lang.String: ...
        def getFrontHead(self) -> 'TEMAStandard.FrontHeadType': ...
        def getRearHead(self) -> 'TEMAStandard.RearHeadType': ...
        def getShell(self) -> 'TEMAStandard.ShellType': ...
        def hasGoodThermalExpansion(self) -> bool: ...
        def isBundleRemovable(self) -> bool: ...
    class TubePitchPattern(java.lang.Enum['TEMAStandard.TubePitchPattern']):
        TRIANGULAR_30: typing.ClassVar['TEMAStandard.TubePitchPattern'] = ...
        TRIANGULAR_60: typing.ClassVar['TEMAStandard.TubePitchPattern'] = ...
        SQUARE_90: typing.ClassVar['TEMAStandard.TubePitchPattern'] = ...
        SQUARE_45: typing.ClassVar['TEMAStandard.TubePitchPattern'] = ...
        def getDescription(self) -> java.lang.String: ...
        def getHeatTransferFactor(self) -> float: ...
        def getLayoutAngle(self) -> int: ...
        def getMinPitchRatio(self) -> float: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'TEMAStandard.TubePitchPattern': ...
        @staticmethod
        def values() -> typing.MutableSequence['TEMAStandard.TubePitchPattern']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.heatexchanger")``.

    HeatExchangerMechanicalDesign: typing.Type[HeatExchangerMechanicalDesign]
    HeatExchangerMechanicalDesignResponse: typing.Type[HeatExchangerMechanicalDesignResponse]
    HeatExchangerSizingResult: typing.Type[HeatExchangerSizingResult]
    HeatExchangerType: typing.Type[HeatExchangerType]
    ShellAndTubeDesignCalculator: typing.Type[ShellAndTubeDesignCalculator]
    TEMAStandard: typing.Type[TEMAStandard]
