
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.automation
import jneqsim.process.equipment.heatexchanger
import jneqsim.process.equipment.util
import jneqsim.process.processmodel
import jneqsim.thermo.system
import typing



class Boiler(java.io.Serializable):
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addSteamDuty(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def calculate(self) -> None: ...
    def getAnnualOperatingCost(self) -> float: ...
    def getBlowdownFlowKgh(self) -> float: ...
    def getCo2TonnePerYear(self) -> float: ...
    def getFanPowerKW(self) -> float: ...
    def getFeedwaterFlowKgh(self) -> float: ...
    def getFuelMassDemandKgh(self) -> float: ...
    def getFuelThermalKW(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getSteamGenerationKgh(self) -> float: ...
    def getTotalSteamDutyKW(self) -> float: ...
    def setAnnualOperatingHours(self, double: float) -> None: ...
    def setBlowdownFraction(self, double: float) -> None: ...
    def setBoilerEfficiency(self, double: float) -> None: ...
    def setCarbonTaxPerTonne(self, double: float) -> None: ...
    def setCo2FuelFactorKgPerKg(self, double: float) -> None: ...
    def setElectricityCostPerKWh(self, double: float) -> None: ...
    def setFanPowerFraction(self, double: float) -> None: ...
    def setFuelGasCostPerKg(self, double: float) -> None: ...
    def setFuelLowHeatingValueMJperKg(self, double: float) -> None: ...
    def setSteamEnthalpyRiseKJperKg(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toResultsMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class SteamDuty(java.io.Serializable):
        name: java.lang.String = ...
        dutyKW: float = ...
        def __init__(self, string: typing.Union[java.lang.String, str], double: float): ...

class Deaerator(java.io.Serializable):
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def calculate(self) -> None: ...
    def getDeaeratorTempC(self) -> float: ...
    def getHeatDutyKW(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getStrippingSteamKgh(self) -> float: ...
    def getVentRateKgh(self) -> float: ...
    def setFeedwaterFlowKgh(self, double: float) -> None: ...
    def setFeedwaterInletTempC(self, double: float) -> None: ...
    def setOperatingPressureBara(self, double: float) -> None: ...
    def setStrippingSteamLatentHeatKJperKg(self, double: float) -> None: ...
    def setVentFraction(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toResultsMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class NitrogenSystem(java.io.Serializable):
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def calculate(self) -> None: ...
    def getAirFeedNm3h(self) -> float: ...
    def getAnnualOperatingCost(self) -> float: ...
    def getCo2TonnePerYear(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getPowerKW(self) -> float: ...
    def getSpecificEnergyKWhPerNm3(self) -> float: ...
    def setAnnualOperatingHours(self, double: float) -> None: ...
    def setCarbonTaxPerTonne(self, double: float) -> None: ...
    def setCo2GridFactorKgPerKWh(self, double: float) -> None: ...
    def setDeliveryPressureBarg(self, double: float) -> None: ...
    def setElectricityCostPerKWh(self, double: float) -> None: ...
    def setGenerationMethod(self, generationMethod: 'NitrogenSystem.GenerationMethod') -> None: ...
    def setNitrogenDemandNm3h(self, double: float) -> None: ...
    def setPurityPercent(self, double: float) -> None: ...
    def setSpecificEnergyOverride(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toResultsMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class GenerationMethod(java.lang.Enum['NitrogenSystem.GenerationMethod']):
        MEMBRANE: typing.ClassVar['NitrogenSystem.GenerationMethod'] = ...
        PSA: typing.ClassVar['NitrogenSystem.GenerationMethod'] = ...
        CRYOGENIC: typing.ClassVar['NitrogenSystem.GenerationMethod'] = ...
        def getAirToProductRatio(self) -> float: ...
        def getLabel(self) -> java.lang.String: ...
        def getSpecificEnergyKWhPerNm3(self) -> float: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'NitrogenSystem.GenerationMethod': ...
        @staticmethod
        def values() -> typing.MutableSequence['NitrogenSystem.GenerationMethod']: ...

class RefrigerationCycle(java.io.Serializable):
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addRefrigerationDuty(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def calculate(self) -> None: ...
    def getAnnualOperatingCost(self) -> float: ...
    def getCarnotCop(self) -> float: ...
    def getCo2TonnePerYear(self) -> float: ...
    def getCompressorPowerKW(self) -> float: ...
    def getCondenserDutyKW(self) -> float: ...
    def getCop(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getTotalRefrigerationDutyKW(self) -> float: ...
    def setAnnualOperatingHours(self, double: float) -> None: ...
    def setCarbonTaxPerTonne(self, double: float) -> None: ...
    def setCo2GridFactorKgPerKWh(self, double: float) -> None: ...
    def setCondenserTempC(self, double: float) -> None: ...
    def setCycleEfficiency(self, double: float) -> None: ...
    def setElectricityCostPerKWh(self, double: float) -> None: ...
    def setEvaporatorTempC(self, double: float) -> None: ...
    def setRefrigerant(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toResultsMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class RefrigerationDuty(java.io.Serializable):
        name: java.lang.String = ...
        dutyKW: float = ...
        def __init__(self, string: typing.Union[java.lang.String, str], double: float): ...

class SteamNetwork(java.io.Serializable):
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addDemand(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def addLevel(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def calculate(self) -> None: ...
    def getBoiler(self) -> Boiler: ...
    def getBoilerGenerationKgh(self) -> float: ...
    def getDeaerator(self) -> Deaerator: ...
    def getHeaderCount(self) -> int: ...
    def getName(self) -> java.lang.String: ...
    def getTotalDemandKgh(self) -> float: ...
    def getTotalLocalGenerationKgh(self) -> float: ...
    def setCondensateReturnFraction(self, double: float) -> None: ...
    def setLocalGeneration(self, string: typing.Union[java.lang.String, str], double: float) -> None: ...
    def setSteamEnthalpyRiseKJperKg(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toResultsMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class SteamHeader(java.io.Serializable):
        name: java.lang.String = ...
        pressureBara: float = ...
        saturationTempC: float = ...
        demandKgh: float = ...
        localGenerationKgh: float = ...
        inflowFromAboveKgh: float = ...
        letdownToBelowKgh: float = ...
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float): ...

class UtilityCompressionOptimizer(java.io.Serializable):
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def getEvaluations(self) -> int: ...
    def getGeometricMeanPressureBara(self) -> float: ...
    def getMinTotalPowerKW(self) -> float: ...
    def getOptimumInterstagePressureBara(self) -> float: ...
    def getResult(self) -> jneqsim.process.automation.AgenticProcessOptimizer.OptimizationResult: ...
    def isFeasible(self) -> bool: ...
    def optimize(self) -> 'UtilityCompressionOptimizer': ...
    def setDeliveryPressureBara(self, double: float) -> 'UtilityCompressionOptimizer': ...
    def setFlowRateKgh(self, double: float) -> 'UtilityCompressionOptimizer': ...
    def setFluid(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> 'UtilityCompressionOptimizer': ...
    def setInletPressureBara(self, double: float) -> 'UtilityCompressionOptimizer': ...
    def setInletTempC(self, double: float) -> 'UtilityCompressionOptimizer': ...
    def setIntercoolerTempC(self, double: float) -> 'UtilityCompressionOptimizer': ...
    def setMaxEvaluations(self, int: int) -> 'UtilityCompressionOptimizer': ...
    def setSeed(self, long: int) -> 'UtilityCompressionOptimizer': ...
    def toJson(self) -> java.lang.String: ...
    def toResultsMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class UtilitySystemDesigner(java.io.Serializable):
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def design(self) -> 'UtilitySystemDesigner': ...
    @staticmethod
    def fromProcessModel(processModel: jneqsim.process.processmodel.ProcessModel) -> 'UtilitySystemDesigner': ...
    @staticmethod
    def fromProcessSystem(processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'UtilitySystemDesigner': ...
    def getActuatorCount(self) -> int: ...
    def getAirCoolerDutyKW(self) -> float: ...
    def getCoolingWaterDutyKW(self) -> float: ...
    def getCoolingWaterFlowM3h(self) -> float: ...
    def getCoolingWaterSystem(self) -> jneqsim.process.equipment.heatexchanger.CoolingWaterSystem: ...
    def getFuelMassDemandKgh(self) -> float: ...
    def getFuelThermalDemandKW(self) -> float: ...
    def getInstrumentAirCompressorKW(self) -> float: ...
    def getInstrumentAirDemandNm3h(self) -> float: ...
    def getInstrumentAirSystem(self) -> jneqsim.process.equipment.util.UtilityAirSystem: ...
    def getTotalCo2TonnePerYear(self) -> float: ...
    def getTotalCoolingDutyKW(self) -> float: ...
    def getTotalElectricalLoadKW(self) -> float: ...
    def getTotalHeatingDutyKW(self) -> float: ...
    def getTotalOpex(self) -> float: ...
    def getTotalShaftPowerKW(self) -> float: ...
    def setAnnualOperatingHours(self, double: float) -> None: ...
    def setBoilerEfficiency(self, double: float) -> None: ...
    def setCarbonTaxPerTonne(self, double: float) -> None: ...
    def setCo2GridFactorKgPerKWh(self, double: float) -> None: ...
    def setCoolingWaterCutoverTempC(self, double: float) -> None: ...
    def setCoolingWaterReturnTempC(self, double: float) -> None: ...
    def setCoolingWaterSupplyTempC(self, double: float) -> None: ...
    def setElectricityCostPerKWh(self, double: float) -> None: ...
    def setElectrifyDrivers(self, boolean: bool) -> None: ...
    def setFuelGasCostPerKg(self, double: float) -> None: ...
    def setFuelLowHeatingValueMJperKg(self, double: float) -> None: ...
    def setMinimumApproachTempC(self, double: float) -> None: ...
    def setSteamLevels(self, list: java.util.List['UtilitySystemDesigner.SteamLevel']) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toResultsMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def validate(self) -> java.util.List[java.lang.String]: ...
    class SteamLevel(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float): ...
        def getAllocatedDutyKW(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getPressureBara(self) -> float: ...
        def getSaturationTempC(self) -> float: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.util.utilitydesign")``.

    Boiler: typing.Type[Boiler]
    Deaerator: typing.Type[Deaerator]
    NitrogenSystem: typing.Type[NitrogenSystem]
    RefrigerationCycle: typing.Type[RefrigerationCycle]
    SteamNetwork: typing.Type[SteamNetwork]
    UtilityCompressionOptimizer: typing.Type[UtilityCompressionOptimizer]
    UtilitySystemDesigner: typing.Type[UtilitySystemDesigner]
