
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.thermo.system
import typing



class VacuumCollapseAnalyzer(java.io.Serializable):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float): ...
    def analyze(self) -> 'VacuumCollapseResult': ...
    def setAtmosphericPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> 'VacuumCollapseAnalyzer': ...
    def setColdEndTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> 'VacuumCollapseAnalyzer': ...
    def setCoolingSteps(self, int: int) -> 'VacuumCollapseAnalyzer': ...
    def setExternalPressureRating(self, double: float, string: typing.Union[java.lang.String, str]) -> 'VacuumCollapseAnalyzer': ...
    def setInitialConditions(self, double: float, string: typing.Union[java.lang.String, str], double2: float, string2: typing.Union[java.lang.String, str]) -> 'VacuumCollapseAnalyzer': ...
    def setMakeupGasMolarMass(self, double: float) -> 'VacuumCollapseAnalyzer': ...
    def setMakeupSetpoint(self, double: float, string: typing.Union[java.lang.String, str]) -> 'VacuumCollapseAnalyzer': ...
    class CoolingPoint(java.io.Serializable):
        temperatureK: float = ...
        pressureBara: float = ...
        vaporMoleFraction: float = ...
        def __init__(self, double: float, double2: float, double3: float): ...
    class VacuumVerdict(java.lang.Enum['VacuumCollapseAnalyzer.VacuumVerdict']):
        NO_VACUUM: typing.ClassVar['VacuumCollapseAnalyzer.VacuumVerdict'] = ...
        VACUUM_WITHIN_RATING: typing.ClassVar['VacuumCollapseAnalyzer.VacuumVerdict'] = ...
        VACUUM_EXCEEDS_RATING: typing.ClassVar['VacuumCollapseAnalyzer.VacuumVerdict'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'VacuumCollapseAnalyzer.VacuumVerdict': ...
        @staticmethod
        def values() -> typing.MutableSequence['VacuumCollapseAnalyzer.VacuumVerdict']: ...

class VacuumCollapseResult(java.io.Serializable):
    def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, boolean: bool, double9: float, double10: float, boolean2: bool, boolean3: bool, vacuumVerdict: VacuumCollapseAnalyzer.VacuumVerdict, double11: float, double12: float, double13: float, double14: float, list: java.util.List[VacuumCollapseAnalyzer.CoolingPoint], list2: java.util.List[typing.Union[java.lang.String, str]]): ...
    def getAtmosphericPressureBara(self) -> float: ...
    def getColdEndTemperatureK(self) -> float: ...
    def getCoolingCurve(self) -> java.util.List[VacuumCollapseAnalyzer.CoolingPoint]: ...
    def getExternalRatingBara(self) -> float: ...
    def getFinalPressureBara(self) -> float: ...
    def getInitialPressureBara(self) -> float: ...
    def getInitialTemperatureK(self) -> float: ...
    def getMakeupGasMassKg(self) -> float: ...
    def getMakeupGasMolarMass(self) -> float: ...
    def getMakeupGasMoles(self) -> float: ...
    def getMakeupSetpointBara(self) -> float: ...
    def getMarginToRatingBar(self) -> float: ...
    def getMinimumPressureBara(self) -> float: ...
    def getMinimumPressureTemperatureK(self) -> float: ...
    def getVacuumDepthBar(self) -> float: ...
    def getVerdict(self) -> VacuumCollapseAnalyzer.VacuumVerdict: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isRatingProvided(self) -> bool: ...
    def isVacuumPresent(self) -> bool: ...
    def isWithinRating(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.vacuum")``.

    VacuumCollapseAnalyzer: typing.Type[VacuumCollapseAnalyzer]
    VacuumCollapseResult: typing.Type[VacuumCollapseResult]
