
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import neqsim.process.equipment
import neqsim.process.logic
import typing



class ESDLogic(neqsim.process.logic.ProcessLogic):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def activate(self) -> None: ...
    def addAction(self, logicAction: neqsim.process.logic.LogicAction, double: float) -> None: ...
    def deactivate(self) -> None: ...
    def execute(self, double: float) -> None: ...
    def getActionCount(self) -> int: ...
    def getCurrentActionIndex(self) -> int: ...
    def getElapsedTime(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getState(self) -> neqsim.process.logic.LogicState: ...
    def getStatusDescription(self) -> java.lang.String: ...
    def getTargetEquipment(self) -> java.util.List[neqsim.process.equipment.ProcessEquipmentInterface]: ...
    def isActive(self) -> bool: ...
    def isComplete(self) -> bool: ...
    def reset(self) -> bool: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("neqsim.process.logic.esd")``.

    ESDLogic: typing.Type[ESDLogic]
