
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.costestimation
import jneqsim.process.mechanicaldesign
import typing



class ColumnCostEstimate(jneqsim.process.costestimation.UnitCostEstimateBaseClass):
    def __init__(self, mechanicalDesign: jneqsim.process.mechanicaldesign.MechanicalDesign): ...
    def calcAnnualUtilityCost(self, double: float, double2: float, double3: float) -> float: ...
    def calcColumnWeight(self) -> float: ...
    def getColumnDiameter(self) -> float: ...
    def getColumnType(self) -> java.lang.String: ...
    def getCostBreakdown(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getTotalCost(self) -> float: ...
    def setColumnDiameter(self, double: float) -> None: ...
    def setColumnHeight(self, double: float) -> None: ...
    def setColumnType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setCondenserDuty(self, double: float) -> None: ...
    def setDesignPressure(self, double: float) -> None: ...
    def setIncludeCondenser(self, boolean: bool) -> None: ...
    def setIncludeReboiler(self, boolean: bool) -> None: ...
    def setNumberOfTrays(self, int: int) -> None: ...
    def setPackingHeight(self, double: float) -> None: ...
    def setPackingType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReboilerDuty(self, double: float) -> None: ...
    def setTrayType(self, string: typing.Union[java.lang.String, str]) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.costestimation.column")``.

    ColumnCostEstimate: typing.Type[ColumnCostEstimate]
