import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jneqsim.process.equipment
import jneqsim.process.mechanicaldesign
import typing

class SplitterMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(
        self,
        processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface,
    ): ...
    def calcDesign(self) -> None: ...
    def calculateSplitterCost(self) -> float: ...
    def calculateWeights(self) -> None: ...
    def getBranchDiameter(self) -> float: ...
    def getDesignStandardCode(self) -> java.lang.String: ...
    def getDesignVelocity(self) -> float: ...
    def getHeaderDiameter(self) -> float: ...
    def getHeaderLength(self) -> float: ...
    def getHeaderWallThickness(self) -> float: ...
    def getManifoldVolume(self) -> float: ...
    def getMaterialGrade(self) -> java.lang.String: ...
    def getMaxAllowableVelocity(self) -> float: ...
    def getNumberOfBranches(self) -> int: ...
    def getSplitRatios(self) -> typing.MutableSequence[float]: ...
    def getSplitterType(self) -> java.lang.String: ...
    def getTotalPressureDrop(self) -> float: ...
    def readDesignSpecifications(self) -> None: ...
    def setBranchDiameter(self, double: float) -> None: ...
    def setDesignStandardCode(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setDesignVelocity(self, double: float) -> None: ...
    def setHeaderDiameter(self, double: float) -> None: ...
    def setHeaderLength(self, double: float) -> None: ...
    def setMaterialGrade(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setMaxAllowableVelocity(self, double: float) -> None: ...
    def setSplitterType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def toJson(self) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.splitter")``.

    SplitterMechanicalDesign: typing.Type[SplitterMechanicalDesign]
