
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import typing



class ALARPAuditReport(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addMeasure(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> 'ALARPAuditReport': ...
    def evaluate(self) -> java.util.List['ALARPAuditReport.EvaluationResult']: ...
    def report(self) -> java.lang.String: ...
    def setDisproportionFactor(self, double: float) -> 'ALARPAuditReport': ...
    def setValueOfStatisticalLife(self, double: float) -> 'ALARPAuditReport': ...
    class EvaluationResult(java.io.Serializable):
        description: java.lang.String = ...
        riskReductionPerYear: float = ...
        annualisedCostNOK: float = ...
        icaf: float = ...
        verdict: java.lang.String = ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.alarp")``.

    ALARPAuditReport: typing.Type[ALARPAuditReport]
