import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jneqsim.process.equipment
import jneqsim.process.mechanicaldesign
import typing

class ElectrolyzerMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(
        self,
        processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface,
    ): ...
    def calcDesign(self) -> None: ...
    def getCellsPerStack(self) -> int: ...
    def getCurrentDensity(self) -> float: ...
    def getElectrolyzerType(self) -> java.lang.String: ...
    def getH2ProductionRateKgHr(self) -> float: ...
    def getModuleFootprintM2(self) -> float: ...
    def getNumberOfStacks(self) -> int: ...
    def getSpecificEnergyKWhPerKg(self) -> float: ...
    def getStackEfficiency(self) -> float: ...
    def getStackWeightKg(self) -> float: ...
    def getTotalMembraneArea(self) -> float: ...
    def getTotalPowerKW(self) -> float: ...
    def getTotalSystemWeightKg(self) -> float: ...
    def getWaterConsumptionKgHr(self) -> float: ...
    def setCellActiveArea(self, double: float) -> None: ...
    def setCurrentDensity(self, double: float) -> None: ...
    def setElectrolyzerType(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setH2ProductionRateKgHr(self, double: float) -> None: ...
    def setStackPressure(self, double: float) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.electrolyzer")``.

    ElectrolyzerMechanicalDesign: typing.Type[ElectrolyzerMechanicalDesign]
