
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.pipeline
import jneqsim.process.equipment.stream
import jneqsim.process.equipment.valve
import jneqsim.process.mechanicaldesign
import jneqsim.process.mechanicaldesign.subsea
import jneqsim.process.util.report
import jneqsim.thermo.system
import typing



class FlexiblePipe(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @staticmethod
    def createDynamicRiser(string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, riserConfiguration: 'FlexiblePipe.RiserConfiguration') -> 'FlexiblePipe': ...
    @staticmethod
    def createStaticFlowline(string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, double: float) -> 'FlexiblePipe': ...
    def getApplication(self) -> 'FlexiblePipe.Application': ...
    def getBendStiffenerLength(self) -> float: ...
    def getBurstPressure(self) -> float: ...
    def getCarcassMaterial(self) -> java.lang.String: ...
    def getCo2ContentPercent(self) -> float: ...
    def getCollapsePressure(self) -> float: ...
    def getDesignPressure(self) -> float: ...
    def getDesignTemperature(self) -> float: ...
    def getDryWeightPerMeter(self) -> float: ...
    def getEndFittingFlangeRating(self) -> java.lang.String: ...
    def getEndFittingType(self) -> java.lang.String: ...
    def getH2sContentPercent(self) -> float: ...
    def getInnerDiameterInches(self) -> float: ...
    def getInternalSheathMaterial(self) -> java.lang.String: ...
    def getLength(self) -> float: ...
    def getMaxTensionKN(self) -> float: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.subsea.FlexiblePipeMechanicalDesign: ...
    def getMinDesignTemperature(self) -> float: ...
    def getMinimumBendRadius(self) -> float: ...
    def getOuterDiameterMm(self) -> float: ...
    def getPipeType(self) -> 'FlexiblePipe.PipeType': ...
    def getRiserConfiguration(self) -> 'FlexiblePipe.RiserConfiguration': ...
    def getServiceType(self) -> 'FlexiblePipe.ServiceType': ...
    def getSubmergedWeightPerMeter(self) -> float: ...
    def getTensileArmorLayers(self) -> int: ...
    def getWaterDepth(self) -> float: ...
    def hasBendStiffener(self) -> bool: ...
    def hasCarcass(self) -> bool: ...
    def hasPressureArmor(self) -> bool: ...
    def initMechanicalDesign(self) -> None: ...
    def isSourService(self) -> bool: ...
    def isSuitableForSourService(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setApplication(self, application: 'FlexiblePipe.Application') -> None: ...
    def setBendStiffenerLength(self, double: float) -> None: ...
    def setBurstPressure(self, double: float) -> None: ...
    def setCO2Content(self, double: float) -> None: ...
    def setCarcassMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setCollapsePressure(self, double: float) -> None: ...
    def setDesignPressure(self, double: float) -> None: ...
    def setDesignTemperature(self, double: float) -> None: ...
    def setDryWeightPerMeter(self, double: float) -> None: ...
    def setEndFittingFlangeRating(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setEndFittingType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setH2SContent(self, double: float) -> None: ...
    def setHasBendStiffener(self, boolean: bool) -> None: ...
    def setHasCarcass(self, boolean: bool) -> None: ...
    def setHasPressureArmor(self, boolean: bool) -> None: ...
    def setInnerDiameterInches(self, double: float) -> None: ...
    def setInternalSheathMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLength(self, double: float) -> None: ...
    def setMaxTensionKN(self, double: float) -> None: ...
    def setMinDesignTemperature(self, double: float) -> None: ...
    def setMinimumBendRadius(self, double: float) -> None: ...
    def setOuterDiameterMm(self, double: float) -> None: ...
    def setPipeType(self, pipeType: 'FlexiblePipe.PipeType') -> None: ...
    def setRiserConfiguration(self, riserConfiguration: 'FlexiblePipe.RiserConfiguration') -> None: ...
    def setServiceType(self, serviceType: 'FlexiblePipe.ServiceType') -> None: ...
    def setSubmergedWeightPerMeter(self, double: float) -> None: ...
    def setTensileArmorLayers(self, int: int) -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    class Application(java.lang.Enum['FlexiblePipe.Application']):
        DYNAMIC_RISER: typing.ClassVar['FlexiblePipe.Application'] = ...
        STATIC_RISER: typing.ClassVar['FlexiblePipe.Application'] = ...
        FLOWLINE: typing.ClassVar['FlexiblePipe.Application'] = ...
        JUMPER: typing.ClassVar['FlexiblePipe.Application'] = ...
        EXPORT: typing.ClassVar['FlexiblePipe.Application'] = ...
        INJECTION: typing.ClassVar['FlexiblePipe.Application'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FlexiblePipe.Application': ...
        @staticmethod
        def values() -> typing.MutableSequence['FlexiblePipe.Application']: ...
    class PipeType(java.lang.Enum['FlexiblePipe.PipeType']):
        UNBONDED: typing.ClassVar['FlexiblePipe.PipeType'] = ...
        BONDED: typing.ClassVar['FlexiblePipe.PipeType'] = ...
        HYBRID_COMPOSITE: typing.ClassVar['FlexiblePipe.PipeType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FlexiblePipe.PipeType': ...
        @staticmethod
        def values() -> typing.MutableSequence['FlexiblePipe.PipeType']: ...
    class RiserConfiguration(java.lang.Enum['FlexiblePipe.RiserConfiguration']):
        FREE_HANGING: typing.ClassVar['FlexiblePipe.RiserConfiguration'] = ...
        LAZY_WAVE: typing.ClassVar['FlexiblePipe.RiserConfiguration'] = ...
        STEEP_WAVE: typing.ClassVar['FlexiblePipe.RiserConfiguration'] = ...
        LAZY_S: typing.ClassVar['FlexiblePipe.RiserConfiguration'] = ...
        STEEP_S: typing.ClassVar['FlexiblePipe.RiserConfiguration'] = ...
        PLIANT_WAVE: typing.ClassVar['FlexiblePipe.RiserConfiguration'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FlexiblePipe.RiserConfiguration': ...
        @staticmethod
        def values() -> typing.MutableSequence['FlexiblePipe.RiserConfiguration']: ...
    class ServiceType(java.lang.Enum['FlexiblePipe.ServiceType']):
        OIL: typing.ClassVar['FlexiblePipe.ServiceType'] = ...
        GAS: typing.ClassVar['FlexiblePipe.ServiceType'] = ...
        MULTIPHASE: typing.ClassVar['FlexiblePipe.ServiceType'] = ...
        WATER_INJECTION: typing.ClassVar['FlexiblePipe.ServiceType'] = ...
        GAS_INJECTION: typing.ClassVar['FlexiblePipe.ServiceType'] = ...
        GAS_LIFT: typing.ClassVar['FlexiblePipe.ServiceType'] = ...
        CHEMICAL: typing.ClassVar['FlexiblePipe.ServiceType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FlexiblePipe.ServiceType': ...
        @staticmethod
        def values() -> typing.MutableSequence['FlexiblePipe.ServiceType']: ...

class FloatingSubstructure(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def getBallastMass(self) -> float: ...
    def getCenterOfBuoyancy(self) -> float: ...
    def getCenterOfGravity(self) -> float: ...
    def getConceptType(self) -> 'FloatingSubstructure.ConceptType': ...
    def getDesignResults(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDisplacedVolume(self) -> float: ...
    def getDisplacement(self) -> float: ...
    def getDraft(self) -> float: ...
    def getEstimatedCost(self) -> float: ...
    def getExcessBuoyancy(self) -> float: ...
    def getFreeboard(self) -> float: ...
    def getHeaveNaturalPeriod(self) -> float: ...
    def getMetacentricHeight(self) -> float: ...
    def getMetacentricRadius(self) -> float: ...
    def getPitchNaturalPeriod(self) -> float: ...
    def getStaticTiltAngle(self) -> float: ...
    def getSteelWeight(self) -> float: ...
    def getTotalMass(self) -> float: ...
    def getWaterplaneArea(self) -> float: ...
    def getWaterplaneSecondMoment(self) -> float: ...
    def isStabilityAdequate(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setBallastCogAboveKeel(self, double: float) -> None: ...
    def setBallastMass(self, double: float) -> None: ...
    def setBargeDepth(self, double: float) -> None: ...
    def setBargeLength(self, double: float) -> None: ...
    def setBargeWidth(self, double: float) -> None: ...
    def setColumnDiameter(self, double: float) -> None: ...
    def setColumnHeight(self, double: float) -> None: ...
    def setColumnSpacing(self, double: float) -> None: ...
    def setConceptType(self, conceptType: 'FloatingSubstructure.ConceptType') -> None: ...
    def setDesignWindThrust(self, double: float) -> None: ...
    def setHubHeight(self, double: float) -> None: ...
    def setNumberOfColumns(self, int: int) -> None: ...
    def setPeakSpectralPeriod(self, double: float) -> None: ...
    def setPontoonHeight(self, double: float) -> None: ...
    def setPontoonWidth(self, double: float) -> None: ...
    def setSeawaterDensity(self, double: float) -> None: ...
    def setSignificantWaveHeight(self, double: float) -> None: ...
    def setSparHeight(self, double: float) -> None: ...
    def setTowerMass(self, double: float) -> None: ...
    def setTurbineMass(self, double: float) -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    class ConceptType(java.lang.Enum['FloatingSubstructure.ConceptType']):
        SEMI_SUBMERSIBLE: typing.ClassVar['FloatingSubstructure.ConceptType'] = ...
        SPAR: typing.ClassVar['FloatingSubstructure.ConceptType'] = ...
        BARGE: typing.ClassVar['FloatingSubstructure.ConceptType'] = ...
        TLP: typing.ClassVar['FloatingSubstructure.ConceptType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FloatingSubstructure.ConceptType': ...
        @staticmethod
        def values() -> typing.MutableSequence['FloatingSubstructure.ConceptType']: ...

class MooringSystem(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def getAnchorTension(self) -> float: ...
    def getBreakingStrengthSafetyFactor(self) -> float: ...
    def getCatenaryProfile(self, int: int) -> java.util.List[typing.MutableSequence[float]]: ...
    def getDesignResults(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getEstimatedCost(self) -> float: ...
    def getFairleadAngle(self) -> float: ...
    def getFairleadTension(self) -> float: ...
    def getLineLength(self) -> float: ...
    def getLineWeightPerMeter(self) -> float: ...
    def getMaxLineTension(self) -> float: ...
    def getMaxOffset(self) -> float: ...
    def getMinimumBreakingLoad(self) -> float: ...
    def getRequiredAnchorCapacity(self) -> float: ...
    def getRestoringStiffness(self) -> float: ...
    def getTotalWeight(self) -> float: ...
    def getTouchdownLength(self) -> float: ...
    def isSafetyFactorAdequate(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setAnchorRadius(self, double: float) -> None: ...
    def setAnchorType(self, anchorType: 'MooringSystem.AnchorType') -> None: ...
    def setChainDiameter(self, double: float) -> None: ...
    def setChainGrade(self, int: int) -> None: ...
    def setDesignHorizontalForce(self, double: float) -> None: ...
    def setDesignVerticalForce(self, double: float) -> None: ...
    def setFairleadDepth(self, double: float) -> None: ...
    def setLineType(self, lineType: 'MooringSystem.LineType') -> None: ...
    def setNumberOfLines(self, int: int) -> None: ...
    def setPolyesterDiameter(self, double: float) -> None: ...
    def setRequiredSafetyFactor(self, double: float) -> None: ...
    def setSeawaterDensity(self, double: float) -> None: ...
    def setSoilType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    class AnchorType(java.lang.Enum['MooringSystem.AnchorType']):
        DRAG_EMBEDMENT: typing.ClassVar['MooringSystem.AnchorType'] = ...
        SUCTION_PILE: typing.ClassVar['MooringSystem.AnchorType'] = ...
        DRIVEN_PILE: typing.ClassVar['MooringSystem.AnchorType'] = ...
        GRAVITY: typing.ClassVar['MooringSystem.AnchorType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'MooringSystem.AnchorType': ...
        @staticmethod
        def values() -> typing.MutableSequence['MooringSystem.AnchorType']: ...
    class LineType(java.lang.Enum['MooringSystem.LineType']):
        CHAIN: typing.ClassVar['MooringSystem.LineType'] = ...
        WIRE_ROPE: typing.ClassVar['MooringSystem.LineType'] = ...
        POLYESTER: typing.ClassVar['MooringSystem.LineType'] = ...
        CHAIN_POLYESTER_CHAIN: typing.ClassVar['MooringSystem.LineType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'MooringSystem.LineType': ...
        @staticmethod
        def values() -> typing.MutableSequence['MooringSystem.LineType']: ...

class PLEM(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], int: int): ...
    def addInletStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
    def closeBranch(self, int: int) -> None: ...
    def getBranchSizeInches(self) -> float: ...
    def getBranchValves(self) -> java.util.List[jneqsim.process.equipment.valve.ThrottlingValve]: ...
    def getConfigurationType(self) -> 'PLEM.ConfigurationType': ...
    def getDesignPressure(self) -> float: ...
    def getDesignTemperature(self) -> float: ...
    def getDryWeight(self) -> float: ...
    def getFoundationType(self) -> java.lang.String: ...
    def getHeaderSizeInches(self) -> float: ...
    def getInletStreams(self) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.subsea.PLEMMechanicalDesign: ...
    def getNumberOfSlots(self) -> int: ...
    def getOutletStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getStructureHeight(self) -> float: ...
    def getStructureLength(self) -> float: ...
    def getStructureWidth(self) -> float: ...
    def getSubmergedWeight(self) -> float: ...
    def getWaterDepth(self) -> float: ...
    def hasBranchIsolationValves(self) -> bool: ...
    def hasHeaderIsolationValves(self) -> bool: ...
    def initMechanicalDesign(self) -> None: ...
    def openBranch(self, int: int) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setBranchIsolationValves(self, boolean: bool) -> None: ...
    def setBranchSizeInches(self, double: float) -> None: ...
    def setBranchValveOpening(self, int: int, double: float) -> None: ...
    def setConfigurationType(self, configurationType: 'PLEM.ConfigurationType') -> None: ...
    def setDesignPressure(self, double: float) -> None: ...
    def setDesignTemperature(self, double: float) -> None: ...
    def setDryWeight(self, double: float) -> None: ...
    def setFoundationType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setHeaderIsolationValves(self, boolean: bool) -> None: ...
    def setHeaderSizeInches(self, double: float) -> None: ...
    def setNumberOfSlots(self, int: int) -> None: ...
    def setStructureHeight(self, double: float) -> None: ...
    def setStructureLength(self, double: float) -> None: ...
    def setStructureWidth(self, double: float) -> None: ...
    def setSubmergedWeight(self, double: float) -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    class ConfigurationType(java.lang.Enum['PLEM.ConfigurationType']):
        THROUGH_FLOW: typing.ClassVar['PLEM.ConfigurationType'] = ...
        COMMINGLING: typing.ClassVar['PLEM.ConfigurationType'] = ...
        DISTRIBUTION: typing.ClassVar['PLEM.ConfigurationType'] = ...
        CROSSOVER: typing.ClassVar['PLEM.ConfigurationType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PLEM.ConfigurationType': ...
        @staticmethod
        def values() -> typing.MutableSequence['PLEM.ConfigurationType']: ...

class PLET(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def closeIsolationValve(self) -> None: ...
    def getActuatorType(self) -> java.lang.String: ...
    def getConnectionType(self) -> 'PLET.ConnectionType': ...
    def getDesignPressure(self) -> float: ...
    def getDesignTemperature(self) -> float: ...
    def getDryWeight(self) -> float: ...
    def getIsolationValve(self) -> jneqsim.process.equipment.valve.ThrottlingValve: ...
    def getIsolationValveOpening(self) -> float: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.subsea.PLETMechanicalDesign: ...
    def getNominalBoreInches(self) -> float: ...
    def getNumberOfHubs(self) -> int: ...
    def getPiggingType(self) -> java.lang.String: ...
    def getSpareHubs(self) -> int: ...
    def getStructureHeight(self) -> float: ...
    def getStructureLength(self) -> float: ...
    def getStructureType(self) -> 'PLET.StructureType': ...
    def getStructureWidth(self) -> float: ...
    def getSubmergedWeight(self) -> float: ...
    def getValveType(self) -> java.lang.String: ...
    def getWaterDepth(self) -> float: ...
    def hasFutureTieIn(self) -> bool: ...
    def hasIsolationValve(self) -> bool: ...
    def hasPiggingFacility(self) -> bool: ...
    def initMechanicalDesign(self) -> None: ...
    def openIsolationValve(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setActuatorType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setConnectionType(self, connectionType: 'PLET.ConnectionType') -> None: ...
    def setDesignPressure(self, double: float) -> None: ...
    def setDesignTemperature(self, double: float) -> None: ...
    def setDryWeight(self, double: float) -> None: ...
    def setHasFutureTieIn(self, boolean: bool) -> None: ...
    def setHasIsolationValve(self, boolean: bool) -> None: ...
    def setHasPiggingFacility(self, boolean: bool) -> None: ...
    def setIsolationValveOpening(self, double: float) -> None: ...
    def setNominalBoreInches(self, double: float) -> None: ...
    def setNumberOfHubs(self, int: int) -> None: ...
    def setPiggingType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSpareHubs(self, int: int) -> None: ...
    def setStructureHeight(self, double: float) -> None: ...
    def setStructureLength(self, double: float) -> None: ...
    def setStructureType(self, structureType: 'PLET.StructureType') -> None: ...
    def setStructureWidth(self, double: float) -> None: ...
    def setSubmergedWeight(self, double: float) -> None: ...
    def setValveType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    class ConnectionType(java.lang.Enum['PLET.ConnectionType']):
        VERTICAL_HUB: typing.ClassVar['PLET.ConnectionType'] = ...
        HORIZONTAL_HUB: typing.ClassVar['PLET.ConnectionType'] = ...
        CLAMP_CONNECTOR: typing.ClassVar['PLET.ConnectionType'] = ...
        COLLET_CONNECTOR: typing.ClassVar['PLET.ConnectionType'] = ...
        DIVER_FLANGE: typing.ClassVar['PLET.ConnectionType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PLET.ConnectionType': ...
        @staticmethod
        def values() -> typing.MutableSequence['PLET.ConnectionType']: ...
    class StructureType(java.lang.Enum['PLET.StructureType']):
        GRAVITY_BASE: typing.ClassVar['PLET.StructureType'] = ...
        PILED: typing.ClassVar['PLET.StructureType'] = ...
        SUCTION_ANCHOR: typing.ClassVar['PLET.StructureType'] = ...
        MUDMAT: typing.ClassVar['PLET.StructureType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PLET.StructureType': ...
        @staticmethod
        def values() -> typing.MutableSequence['PLET.StructureType']: ...

class SimpleFlowLine(jneqsim.process.equipment.TwoPortEquipment):
    length: float = ...
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getHeight(self) -> float: ...
    def getPipeline(self) -> jneqsim.process.equipment.pipeline.AdiabaticTwoPhasePipe: ...
    def getThermoSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setHeight(self, double: float) -> None: ...

class SubseaBooster(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def calculateRequiredPower(self) -> float: ...
    @staticmethod
    def createMultiphasePump(string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, double: float) -> 'SubseaBooster': ...
    @staticmethod
    def createWetGasCompressor(string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, double: float) -> 'SubseaBooster': ...
    def getBoosterType(self) -> 'SubseaBooster.BoosterType': ...
    def getCompressorType(self) -> 'SubseaBooster.CompressorType': ...
    def getDesignFlowRate(self) -> float: ...
    def getDesignGVF(self) -> float: ...
    def getDesignInletPressure(self) -> float: ...
    def getDesignLifeYears(self) -> int: ...
    def getDesignTemperature(self) -> float: ...
    def getDifferentialPressure(self) -> float: ...
    def getDriveType(self) -> 'SubseaBooster.DriveType': ...
    def getEfficiency(self) -> float: ...
    def getInletConnectionInches(self) -> float: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.subsea.SubseaBoosterMechanicalDesign: ...
    def getModuleDryWeight(self) -> float: ...
    def getMtbfHours(self) -> float: ...
    def getNumberOfStages(self) -> int: ...
    def getOperatingVoltage(self) -> float: ...
    def getOutletConnectionInches(self) -> float: ...
    @typing.overload
    def getOutletPressure(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def getOutletPressure(self) -> float: ...
    def getPowerRatingMW(self) -> float: ...
    def getPressureRatio(self) -> float: ...
    def getPumpType(self) -> 'SubseaBooster.PumpType': ...
    def getSpeedRPM(self) -> float: ...
    def getWaterDepth(self) -> float: ...
    def hasRedundantMotor(self) -> bool: ...
    def initMechanicalDesign(self) -> None: ...
    def isCompressor(self) -> bool: ...
    def isRetrievable(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setBoosterType(self, boosterType: 'SubseaBooster.BoosterType') -> None: ...
    def setCompressorType(self, compressorType: 'SubseaBooster.CompressorType') -> None: ...
    def setDesignFlowRate(self, double: float) -> None: ...
    def setDesignGVF(self, double: float) -> None: ...
    def setDesignInletPressure(self, double: float) -> None: ...
    def setDesignLifeYears(self, int: int) -> None: ...
    def setDesignTemperature(self, double: float) -> None: ...
    def setDifferentialPressure(self, double: float) -> None: ...
    def setDriveType(self, driveType: 'SubseaBooster.DriveType') -> None: ...
    def setEfficiency(self, double: float) -> None: ...
    def setInletConnectionInches(self, double: float) -> None: ...
    def setModuleDryWeight(self, double: float) -> None: ...
    def setMtbfHours(self, double: float) -> None: ...
    def setNumberOfStages(self, int: int) -> None: ...
    def setOperatingVoltage(self, double: float) -> None: ...
    def setOutletConnectionInches(self, double: float) -> None: ...
    @typing.overload
    def setOutletPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def setOutletPressure(self, double: float) -> None: ...
    def setPowerRatingMW(self, double: float) -> None: ...
    def setPressureRatio(self, double: float) -> None: ...
    def setPumpType(self, pumpType: 'SubseaBooster.PumpType') -> None: ...
    def setRedundantMotor(self, boolean: bool) -> None: ...
    def setRetrievable(self, boolean: bool) -> None: ...
    def setSpeedRPM(self, double: float) -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    class BoosterType(java.lang.Enum['SubseaBooster.BoosterType']):
        MULTIPHASE_PUMP: typing.ClassVar['SubseaBooster.BoosterType'] = ...
        LIQUID_PUMP: typing.ClassVar['SubseaBooster.BoosterType'] = ...
        WET_GAS_COMPRESSOR: typing.ClassVar['SubseaBooster.BoosterType'] = ...
        DRY_GAS_COMPRESSOR: typing.ClassVar['SubseaBooster.BoosterType'] = ...
        SEPARATOR_BOOSTER: typing.ClassVar['SubseaBooster.BoosterType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaBooster.BoosterType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaBooster.BoosterType']: ...
    class CompressorType(java.lang.Enum['SubseaBooster.CompressorType']):
        CENTRIFUGAL: typing.ClassVar['SubseaBooster.CompressorType'] = ...
        AXIAL: typing.ClassVar['SubseaBooster.CompressorType'] = ...
        SCREW: typing.ClassVar['SubseaBooster.CompressorType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaBooster.CompressorType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaBooster.CompressorType']: ...
    class DriveType(java.lang.Enum['SubseaBooster.DriveType']):
        PERMANENT_MAGNET: typing.ClassVar['SubseaBooster.DriveType'] = ...
        INDUCTION: typing.ClassVar['SubseaBooster.DriveType'] = ...
        HIGH_SPEED_PM: typing.ClassVar['SubseaBooster.DriveType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaBooster.DriveType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaBooster.DriveType']: ...
    class PumpType(java.lang.Enum['SubseaBooster.PumpType']):
        HELICO_AXIAL: typing.ClassVar['SubseaBooster.PumpType'] = ...
        TWIN_SCREW: typing.ClassVar['SubseaBooster.PumpType'] = ...
        COUNTER_ROTATING_AXIAL: typing.ClassVar['SubseaBooster.PumpType'] = ...
        ESP: typing.ClassVar['SubseaBooster.PumpType'] = ...
        CENTRIFUGAL_SINGLE: typing.ClassVar['SubseaBooster.PumpType'] = ...
        CENTRIFUGAL_MULTI: typing.ClassVar['SubseaBooster.PumpType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaBooster.PumpType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaBooster.PumpType']: ...

class SubseaJumper(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    @staticmethod
    def createFlexibleStatic(string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, double: float) -> 'SubseaJumper': ...
    @staticmethod
    def createRigidMShape(string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface, double: float) -> 'SubseaJumper': ...
    def getDesignPressure(self) -> float: ...
    def getDesignTemperature(self) -> float: ...
    def getDryWeight(self) -> float: ...
    def getFlexibleMinBendRadius(self) -> float: ...
    def getFlexibleStructure(self) -> java.lang.String: ...
    def getHorizontalSpan(self) -> float: ...
    def getInletHubSizeInches(self) -> float: ...
    def getInletHubType(self) -> 'SubseaJumper.HubType': ...
    def getInstallationMethod(self) -> java.lang.String: ...
    def getJumperType(self) -> 'SubseaJumper.JumperType': ...
    def getLength(self) -> float: ...
    def getMaterialGrade(self) -> java.lang.String: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.subsea.SubseaJumperMechanicalDesign: ...
    def getMinimumBendRadius(self) -> float: ...
    def getNominalBoreInches(self) -> float: ...
    def getNumberOfBends(self) -> int: ...
    def getOuterDiameterInches(self) -> float: ...
    def getOutletHubSizeInches(self) -> float: ...
    def getOutletHubType(self) -> 'SubseaJumper.HubType': ...
    def getSubmergedWeight(self) -> float: ...
    def getVerticalRise(self) -> float: ...
    def getWallThicknessMm(self) -> float: ...
    def getWaterDepth(self) -> float: ...
    def initMechanicalDesign(self) -> None: ...
    def isFlexible(self) -> bool: ...
    def isRetrievable(self) -> bool: ...
    def isRigid(self) -> bool: ...
    def isRovInstalled(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setDesignPressure(self, double: float) -> None: ...
    def setDesignTemperature(self, double: float) -> None: ...
    def setDryWeight(self, double: float) -> None: ...
    def setFlexibleMinBendRadius(self, double: float) -> None: ...
    def setFlexibleStructure(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setHorizontalSpan(self, double: float) -> None: ...
    def setInletHubSizeInches(self, double: float) -> None: ...
    def setInletHubType(self, hubType: 'SubseaJumper.HubType') -> None: ...
    def setInstallationMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setJumperType(self, jumperType: 'SubseaJumper.JumperType') -> None: ...
    def setLength(self, double: float) -> None: ...
    def setMaterialGrade(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setMinimumBendRadius(self, double: float) -> None: ...
    def setNominalBoreInches(self, double: float) -> None: ...
    def setNumberOfBends(self, int: int) -> None: ...
    def setOuterDiameterInches(self, double: float) -> None: ...
    def setOutletHubSizeInches(self, double: float) -> None: ...
    def setOutletHubType(self, hubType: 'SubseaJumper.HubType') -> None: ...
    def setRetrievable(self, boolean: bool) -> None: ...
    def setRovInstalled(self, boolean: bool) -> None: ...
    def setSubmergedWeight(self, double: float) -> None: ...
    def setVerticalRise(self, double: float) -> None: ...
    def setWallThicknessMm(self, double: float) -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    class HubType(java.lang.Enum['SubseaJumper.HubType']):
        VERTICAL: typing.ClassVar['SubseaJumper.HubType'] = ...
        HORIZONTAL: typing.ClassVar['SubseaJumper.HubType'] = ...
        CLAMP: typing.ClassVar['SubseaJumper.HubType'] = ...
        COLLET: typing.ClassVar['SubseaJumper.HubType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaJumper.HubType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaJumper.HubType']: ...
    class JumperType(java.lang.Enum['SubseaJumper.JumperType']):
        RIGID_M_SHAPE: typing.ClassVar['SubseaJumper.JumperType'] = ...
        RIGID_INVERTED_U: typing.ClassVar['SubseaJumper.JumperType'] = ...
        RIGID_Z_SHAPE: typing.ClassVar['SubseaJumper.JumperType'] = ...
        RIGID_STRAIGHT: typing.ClassVar['SubseaJumper.JumperType'] = ...
        FLEXIBLE_STATIC: typing.ClassVar['SubseaJumper.JumperType'] = ...
        FLEXIBLE_DYNAMIC: typing.ClassVar['SubseaJumper.JumperType'] = ...
        HYBRID: typing.ClassVar['SubseaJumper.JumperType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaJumper.JumperType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaJumper.JumperType']: ...

class SubseaManifold(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], int: int): ...
    @typing.overload
    def addWellStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> int: ...
    @typing.overload
    def addWellStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface, string: typing.Union[java.lang.String, str]) -> int: ...
    def getActiveWellCount(self) -> int: ...
    def getBranchSizeInches(self) -> float: ...
    def getDesignPressure(self) -> float: ...
    def getDesignTemperature(self) -> float: ...
    def getDryWeight(self) -> float: ...
    def getFoundationType(self) -> java.lang.String: ...
    def getInletStreams(self) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getManifoldType(self) -> 'SubseaManifold.ManifoldType': ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.subsea.SubseaManifoldMechanicalDesign: ...
    def getNumberOfSlots(self) -> int: ...
    def getOutletStreams(self) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getProductionHeaderSizeInches(self) -> float: ...
    def getProductionStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getStructureHeight(self) -> float: ...
    def getStructureLength(self) -> float: ...
    def getStructureWidth(self) -> float: ...
    def getSubmergedWeight(self) -> float: ...
    def getTestHeaderSizeInches(self) -> float: ...
    def getTestStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getValveSkids(self) -> java.util.List['SubseaManifold.ValveSkid']: ...
    def getWaterDepth(self) -> float: ...
    def hasInjectionHeader(self) -> bool: ...
    def hasServiceHeader(self) -> bool: ...
    def hasTestHeader(self) -> bool: ...
    def initMechanicalDesign(self) -> None: ...
    def routeToProduction(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def routeToTest(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setBranchSizeInches(self, double: float) -> None: ...
    def setDesignPressure(self, double: float) -> None: ...
    def setDesignTemperature(self, double: float) -> None: ...
    def setDryWeight(self, double: float) -> None: ...
    def setFoundationType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setHasInjectionHeader(self, boolean: bool) -> None: ...
    def setHasServiceHeader(self, boolean: bool) -> None: ...
    def setHasTestHeader(self, boolean: bool) -> None: ...
    def setManifoldType(self, manifoldType: 'SubseaManifold.ManifoldType') -> None: ...
    def setNumberOfSlots(self, int: int) -> None: ...
    def setProductionHeaderSizeInches(self, double: float) -> None: ...
    def setStructureHeight(self, double: float) -> None: ...
    def setStructureLength(self, double: float) -> None: ...
    def setStructureWidth(self, double: float) -> None: ...
    def setSubmergedWeight(self, double: float) -> None: ...
    def setTestHeaderSizeInches(self, double: float) -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    def shutInWell(self, string: typing.Union[java.lang.String, str]) -> None: ...
    class ManifoldType(java.lang.Enum['SubseaManifold.ManifoldType']):
        PRODUCTION_ONLY: typing.ClassVar['SubseaManifold.ManifoldType'] = ...
        PRODUCTION_TEST: typing.ClassVar['SubseaManifold.ManifoldType'] = ...
        FULL_SERVICE: typing.ClassVar['SubseaManifold.ManifoldType'] = ...
        INJECTION: typing.ClassVar['SubseaManifold.ManifoldType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaManifold.ManifoldType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaManifold.ManifoldType']: ...
    class ValveSkid:
        def __init__(self, int: int): ...
        def getConnectedStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
        def getProductionValve(self) -> jneqsim.process.equipment.valve.ThrottlingValve: ...
        def getRouting(self) -> java.lang.String: ...
        def getSlotNumber(self) -> int: ...
        def getTestValve(self) -> jneqsim.process.equipment.valve.ThrottlingValve: ...
        def getWellName(self) -> java.lang.String: ...
        def isActive(self) -> bool: ...
        def setActive(self, boolean: bool) -> None: ...
        def setConnectedStream(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> None: ...
        def setProductionValve(self, throttlingValve: jneqsim.process.equipment.valve.ThrottlingValve) -> None: ...
        def setRouting(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setTestValve(self, throttlingValve: jneqsim.process.equipment.valve.ThrottlingValve) -> None: ...
        def setWellName(self, string: typing.Union[java.lang.String, str]) -> None: ...

class SubseaPowerCable(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def getAmpacity(self) -> float: ...
    def getCableCost(self) -> float: ...
    def getCableType(self) -> 'SubseaPowerCable.CableType': ...
    def getConductorArea(self) -> float: ...
    def getDesignResults(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getDielectricLoss(self) -> float: ...
    def getEfficiency(self) -> float: ...
    def getLength(self) -> float: ...
    def getOperatingCurrent(self) -> float: ...
    def getPowerRating(self) -> float: ...
    def getReactivePower(self) -> float: ...
    def getResistiveLoss(self) -> float: ...
    def getTotalPowerLoss(self) -> float: ...
    def getVoltage(self) -> float: ...
    def getVoltageDrop(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setBurialDepth(self, double: float) -> None: ...
    def setCableType(self, cableType: 'SubseaPowerCable.CableType') -> None: ...
    def setConductorArea(self, double: float) -> None: ...
    def setConductorResistivity(self, double: float) -> None: ...
    def setConductorTemperature(self, double: float) -> None: ...
    def setFrequency(self, double: float) -> None: ...
    def setLength(self, double: float) -> None: ...
    def setNumberOfCables(self, int: int) -> None: ...
    def setPowerFactor(self, double: float) -> None: ...
    def setPowerRating(self, double: float) -> None: ...
    def setSeawaterTemperature(self, double: float) -> None: ...
    def setVoltage(self, double: float) -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    class CableType(java.lang.Enum['SubseaPowerCable.CableType']):
        XLPE_AC: typing.ClassVar['SubseaPowerCable.CableType'] = ...
        XLPE_HVDC: typing.ClassVar['SubseaPowerCable.CableType'] = ...
        MI_HVDC: typing.ClassVar['SubseaPowerCable.CableType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaPowerCable.CableType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaPowerCable.CableType']: ...

class SubseaTree(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def emergencyShutdown(self) -> None: ...
    def getActuatorType(self) -> java.lang.String: ...
    def getBoreSizeInches(self) -> float: ...
    def getChemicalInjectionPoints(self) -> int: ...
    def getChokeOpening(self) -> float: ...
    def getConnectorType(self) -> java.lang.String: ...
    def getDesignPressure(self) -> float: ...
    def getDesignTemperature(self) -> float: ...
    def getDryWeight(self) -> float: ...
    def getFlowlineConnectionSizeInches(self) -> float: ...
    def getFlowlineConnectionType(self) -> java.lang.String: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.subsea.SubseaTreeMechanicalDesign: ...
    def getPressureRating(self) -> 'SubseaTree.PressureRating': ...
    def getProductionChoke(self) -> jneqsim.process.equipment.valve.ThrottlingValve: ...
    def getSubmergedWeight(self) -> float: ...
    def getTreeDiameter(self) -> float: ...
    def getTreeHeight(self) -> float: ...
    def getTreeType(self) -> 'SubseaTree.TreeType': ...
    def getWaterDepth(self) -> float: ...
    def hasDownholePressure(self) -> bool: ...
    def hasDownholeTemperature(self) -> bool: ...
    def initMechanicalDesign(self) -> None: ...
    def isAnnulusMasterValveOpen(self) -> bool: ...
    def isAnnulusWingValveOpen(self) -> bool: ...
    def isCrossoverValveOpen(self) -> bool: ...
    def isFailSafeClose(self) -> bool: ...
    def isProductionMasterValveOpen(self) -> bool: ...
    def isProductionWingValveOpen(self) -> bool: ...
    def openForProduction(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setActuatorType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setAnnulusMasterValveOpen(self, boolean: bool) -> None: ...
    def setAnnulusWingValveOpen(self, boolean: bool) -> None: ...
    def setBoreSizeInches(self, double: float) -> None: ...
    def setChemicalInjectionPoints(self, int: int) -> None: ...
    def setChokeOpening(self, double: float) -> None: ...
    def setConnectorType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setCrossoverValveOpen(self, boolean: bool) -> None: ...
    def setDesignPressure(self, double: float) -> None: ...
    def setDesignTemperature(self, double: float) -> None: ...
    def setDryWeight(self, double: float) -> None: ...
    def setFailSafeClose(self, boolean: bool) -> None: ...
    def setFlowlineConnectionSizeInches(self, double: float) -> None: ...
    def setFlowlineConnectionType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setHasDownholePressure(self, boolean: bool) -> None: ...
    def setHasDownholeTemperature(self, boolean: bool) -> None: ...
    def setPressureRating(self, pressureRating: 'SubseaTree.PressureRating') -> None: ...
    def setProductionMasterValveOpen(self, boolean: bool) -> None: ...
    def setProductionWingValveOpen(self, boolean: bool) -> None: ...
    def setSubmergedWeight(self, double: float) -> None: ...
    def setTreeDiameter(self, double: float) -> None: ...
    def setTreeHeight(self, double: float) -> None: ...
    def setTreeType(self, treeType: 'SubseaTree.TreeType') -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    class PressureRating(java.lang.Enum['SubseaTree.PressureRating']):
        PR5000: typing.ClassVar['SubseaTree.PressureRating'] = ...
        PR10000: typing.ClassVar['SubseaTree.PressureRating'] = ...
        PR15000: typing.ClassVar['SubseaTree.PressureRating'] = ...
        PR20000: typing.ClassVar['SubseaTree.PressureRating'] = ...
        def getBar(self) -> int: ...
        def getPsi(self) -> int: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaTree.PressureRating': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaTree.PressureRating']: ...
    class TreeType(java.lang.Enum['SubseaTree.TreeType']):
        VERTICAL: typing.ClassVar['SubseaTree.TreeType'] = ...
        HORIZONTAL: typing.ClassVar['SubseaTree.TreeType'] = ...
        DUAL_BORE: typing.ClassVar['SubseaTree.TreeType'] = ...
        MUDLINE: typing.ClassVar['SubseaTree.TreeType'] = ...
        SPOOL: typing.ClassVar['SubseaTree.TreeType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaTree.TreeType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaTree.TreeType']: ...

class SubseaWell(jneqsim.process.equipment.TwoPortEquipment):
    height: float = ...
    length: float = ...
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getCompletionDays(self) -> float: ...
    def getCompletionType(self) -> 'SubseaWell.CompletionType': ...
    def getConductorDepth(self) -> float: ...
    def getConductorOD(self) -> float: ...
    def getDrillingDays(self) -> float: ...
    def getIntermediateCasingDepth(self) -> float: ...
    def getIntermediateCasingOD(self) -> float: ...
    def getKickOffPoint(self) -> float: ...
    def getMaxBottomholeTemperature(self) -> float: ...
    def getMaxInclination(self) -> float: ...
    def getMaxWellheadPressure(self) -> float: ...
    def getMeasuredDepth(self) -> float: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.MechanicalDesign: ...
    def getNumberOfCasingStrings(self) -> int: ...
    def getPipeline(self) -> jneqsim.process.equipment.pipeline.AdiabaticTwoPhasePipe: ...
    def getPrimaryBarrierElements(self) -> int: ...
    def getProductionCasingDepth(self) -> float: ...
    def getProductionCasingOD(self) -> float: ...
    def getProductionLinerDepth(self) -> float: ...
    def getProductionLinerOD(self) -> float: ...
    def getReservoirPressure(self) -> float: ...
    def getReservoirTemperature(self) -> float: ...
    def getRigDayRate(self) -> float: ...
    def getRigType(self) -> 'SubseaWell.RigType': ...
    def getSecondaryBarrierElements(self) -> int: ...
    def getSurfaceCasingDepth(self) -> float: ...
    def getSurfaceCasingOD(self) -> float: ...
    def getTrueVerticalDepth(self) -> float: ...
    def getTubingGrade(self) -> java.lang.String: ...
    def getTubingOD(self) -> float: ...
    def getTubingWeight(self) -> float: ...
    def getWaterDepth(self) -> float: ...
    def getWellLocationType(self) -> jneqsim.process.mechanicaldesign.subsea.WellCostEstimator.WellLocationType: ...
    def getWellType(self) -> 'SubseaWell.WellType': ...
    def hasDHSV(self) -> bool: ...
    def initMechanicalDesign(self) -> None: ...
    def isInjector(self) -> bool: ...
    def isProducer(self) -> bool: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setCompletionDays(self, double: float) -> None: ...
    def setCompletionType(self, completionType: 'SubseaWell.CompletionType') -> None: ...
    def setConductorDepth(self, double: float) -> None: ...
    def setConductorOD(self, double: float) -> None: ...
    def setDrillingDays(self, double: float) -> None: ...
    def setHasDHSV(self, boolean: bool) -> None: ...
    def setIntermediateCasingDepth(self, double: float) -> None: ...
    def setIntermediateCasingOD(self, double: float) -> None: ...
    def setKickOffPoint(self, double: float) -> None: ...
    def setMaxBottomholeTemperature(self, double: float) -> None: ...
    def setMaxInclination(self, double: float) -> None: ...
    def setMaxWellheadPressure(self, double: float) -> None: ...
    def setMeasuredDepth(self, double: float) -> None: ...
    def setPrimaryBarrierElements(self, int: int) -> None: ...
    def setProductionCasingDepth(self, double: float) -> None: ...
    def setProductionCasingOD(self, double: float) -> None: ...
    def setProductionLinerDepth(self, double: float) -> None: ...
    def setProductionLinerOD(self, double: float) -> None: ...
    def setReservoirPressure(self, double: float) -> None: ...
    def setReservoirTemperature(self, double: float) -> None: ...
    def setRigDayRate(self, double: float) -> None: ...
    def setRigType(self, rigType: 'SubseaWell.RigType') -> None: ...
    def setSecondaryBarrierElements(self, int: int) -> None: ...
    def setSurfaceCasingDepth(self, double: float) -> None: ...
    def setSurfaceCasingOD(self, double: float) -> None: ...
    def setTrueVerticalDepth(self, double: float) -> None: ...
    def setTubingDiameter(self, double: float) -> None: ...
    def setTubingGrade(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setTubingOD(self, double: float) -> None: ...
    def setTubingWeight(self, double: float) -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    def setWellLocationType(self, wellLocationType: jneqsim.process.mechanicaldesign.subsea.WellCostEstimator.WellLocationType) -> None: ...
    def setWellType(self, wellType: 'SubseaWell.WellType') -> None: ...
    class CompletionType(java.lang.Enum['SubseaWell.CompletionType']):
        CASED_PERFORATED: typing.ClassVar['SubseaWell.CompletionType'] = ...
        OPEN_HOLE: typing.ClassVar['SubseaWell.CompletionType'] = ...
        GRAVEL_PACK: typing.ClassVar['SubseaWell.CompletionType'] = ...
        ICD: typing.ClassVar['SubseaWell.CompletionType'] = ...
        AICD: typing.ClassVar['SubseaWell.CompletionType'] = ...
        MULTI_ZONE: typing.ClassVar['SubseaWell.CompletionType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaWell.CompletionType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaWell.CompletionType']: ...
    class RigType(java.lang.Enum['SubseaWell.RigType']):
        SEMI_SUBMERSIBLE: typing.ClassVar['SubseaWell.RigType'] = ...
        DRILLSHIP: typing.ClassVar['SubseaWell.RigType'] = ...
        JACK_UP: typing.ClassVar['SubseaWell.RigType'] = ...
        PLATFORM_RIG: typing.ClassVar['SubseaWell.RigType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaWell.RigType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaWell.RigType']: ...
    class WellType(java.lang.Enum['SubseaWell.WellType']):
        OIL_PRODUCER: typing.ClassVar['SubseaWell.WellType'] = ...
        GAS_PRODUCER: typing.ClassVar['SubseaWell.WellType'] = ...
        WATER_INJECTOR: typing.ClassVar['SubseaWell.WellType'] = ...
        GAS_INJECTOR: typing.ClassVar['SubseaWell.WellType'] = ...
        OBSERVATION: typing.ClassVar['SubseaWell.WellType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubseaWell.WellType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubseaWell.WellType']: ...

class Umbilical(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addChemicalLine(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def addElectricalCable(self, string: typing.Union[java.lang.String, str], int: int, double: float) -> None: ...
    def addFiberOptic(self, string: typing.Union[java.lang.String, str], int: int) -> None: ...
    def addHydraulicLine(self, string: typing.Union[java.lang.String, str], double: float, double2: float) -> None: ...
    def calculateTotalCrossSection(self) -> float: ...
    def estimateOverallDiameter(self) -> float: ...
    def getArmorWireMaterial(self) -> java.lang.String: ...
    def getChemicalLineCount(self) -> int: ...
    def getCrossSectionType(self) -> 'Umbilical.CrossSectionType': ...
    def getDryWeightPerMeter(self) -> float: ...
    def getElectricalCableCount(self) -> int: ...
    def getElements(self) -> java.util.List['Umbilical.UmbilicalElement']: ...
    def getFiberOpticCount(self) -> int: ...
    def getHydraulicLineCount(self) -> int: ...
    def getInstallationMethod(self) -> java.lang.String: ...
    def getLength(self) -> float: ...
    def getMaxInstallationTensionKN(self) -> float: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.subsea.UmbilicalMechanicalDesign: ...
    def getMinimumBendRadius(self) -> float: ...
    def getOuterSheathMaterial(self) -> java.lang.String: ...
    def getOuterSheathThicknessMm(self) -> float: ...
    def getOverallDiameterMm(self) -> float: ...
    def getSubmergedWeightPerMeter(self) -> float: ...
    def getTotalElementCount(self) -> int: ...
    def getUmbilicalType(self) -> 'Umbilical.UmbilicalType': ...
    def getWaterDepth(self) -> float: ...
    def hasArmorWires(self) -> bool: ...
    def initMechanicalDesign(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setArmorWireMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setCrossSectionType(self, crossSectionType: 'Umbilical.CrossSectionType') -> None: ...
    def setHasArmorWires(self, boolean: bool) -> None: ...
    def setInstallationMethod(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setLength(self, double: float) -> None: ...
    def setMaxInstallationTensionKN(self, double: float) -> None: ...
    def setMinimumBendRadius(self, double: float) -> None: ...
    def setOuterSheathMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setOuterSheathThicknessMm(self, double: float) -> None: ...
    def setOverallDiameterMm(self, double: float) -> None: ...
    def setUmbilicalType(self, umbilicalType: 'Umbilical.UmbilicalType') -> None: ...
    def setWaterDepth(self, double: float) -> None: ...
    class CrossSectionType(java.lang.Enum['Umbilical.CrossSectionType']):
        CIRCULAR: typing.ClassVar['Umbilical.CrossSectionType'] = ...
        FLAT: typing.ClassVar['Umbilical.CrossSectionType'] = ...
        BUNDLED: typing.ClassVar['Umbilical.CrossSectionType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Umbilical.CrossSectionType': ...
        @staticmethod
        def values() -> typing.MutableSequence['Umbilical.CrossSectionType']: ...
    class UmbilicalElement:
        @typing.overload
        def __init__(self, string: typing.Union[java.lang.String, str], int: int, double: float): ...
        @typing.overload
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float): ...
        def getDesignPressureBar(self) -> float: ...
        def getElementType(self) -> java.lang.String: ...
        def getInnerDiameterMm(self) -> float: ...
        def getMaterial(self) -> java.lang.String: ...
        def getName(self) -> java.lang.String: ...
        def getNumberOfCores(self) -> int: ...
        def getNumberOfFibers(self) -> int: ...
        def getOuterDiameterMm(self) -> float: ...
        def getVoltageRating(self) -> float: ...
        def setMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setNumberOfFibers(self, int: int) -> None: ...
        def setOuterDiameterMm(self, double: float) -> None: ...
    class UmbilicalType(java.lang.Enum['Umbilical.UmbilicalType']):
        STEEL_TUBE: typing.ClassVar['Umbilical.UmbilicalType'] = ...
        THERMOPLASTIC: typing.ClassVar['Umbilical.UmbilicalType'] = ...
        INTEGRATED_PRODUCTION: typing.ClassVar['Umbilical.UmbilicalType'] = ...
        ELECTRO_HYDRAULIC: typing.ClassVar['Umbilical.UmbilicalType'] = ...
        ELECTRIC_ONLY: typing.ClassVar['Umbilical.UmbilicalType'] = ...
        def getDisplayName(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Umbilical.UmbilicalType': ...
        @staticmethod
        def values() -> typing.MutableSequence['Umbilical.UmbilicalType']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.subsea")``.

    FlexiblePipe: typing.Type[FlexiblePipe]
    FloatingSubstructure: typing.Type[FloatingSubstructure]
    MooringSystem: typing.Type[MooringSystem]
    PLEM: typing.Type[PLEM]
    PLET: typing.Type[PLET]
    SimpleFlowLine: typing.Type[SimpleFlowLine]
    SubseaBooster: typing.Type[SubseaBooster]
    SubseaJumper: typing.Type[SubseaJumper]
    SubseaManifold: typing.Type[SubseaManifold]
    SubseaPowerCable: typing.Type[SubseaPowerCable]
    SubseaTree: typing.Type[SubseaTree]
    SubseaWell: typing.Type[SubseaWell]
    Umbilical: typing.Type[Umbilical]
