import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import com.google.gson
import java.lang
import java.util
import jneqsim.process.processmodel
import jneqsim.process.util.monitor
import typing

_ApiEnvelope__T = typing.TypeVar("_ApiEnvelope__T")  # <T>

class ApiEnvelope(typing.Generic[_ApiEnvelope__T]):
    API_VERSION: typing.ClassVar[java.lang.String] = ...
    def addWarning(self, string: typing.Union[java.lang.String, str]) -> None: ...
    @staticmethod
    def applyStandardFields(
        jsonObject: com.google.gson.JsonObject,
        string: typing.Union[java.lang.String, str],
        resultProvenance: "ResultProvenance",
        jsonObject2: com.google.gson.JsonObject,
        jsonObject3: com.google.gson.JsonObject,
    ) -> None: ...
    _error__T = typing.TypeVar("_error__T")  # <T>
    @staticmethod
    def error(
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        string3: typing.Union[java.lang.String, str],
    ) -> "ApiEnvelope"[_error__T]: ...
    _errors__T = typing.TypeVar("_errors__T")  # <T>
    @staticmethod
    def errors(
        list: java.util.List["DiagnosticIssue"],
    ) -> "ApiEnvelope"[_errors__T]: ...
    def getApiVersion(self) -> java.lang.String: ...
    def getData(self) -> _ApiEnvelope__T: ...
    def getErrors(self) -> java.util.List["DiagnosticIssue"]: ...
    def getProvenance(self) -> "ResultProvenance": ...
    def getQualityGate(self) -> com.google.gson.JsonObject: ...
    def getStatus(self) -> java.lang.String: ...
    def getTool(self) -> java.lang.String: ...
    def getValidation(self) -> com.google.gson.JsonObject: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isSuccess(self) -> bool: ...
    @staticmethod
    def qualityGate(
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        boolean: bool,
    ) -> com.google.gson.JsonObject: ...
    _success_0__T = typing.TypeVar("_success_0__T")  # <T>
    _success_1__T = typing.TypeVar("_success_1__T")  # <T>
    @typing.overload
    @staticmethod
    def success(t: _success_0__T) -> "ApiEnvelope"[_success_0__T]: ...
    @typing.overload
    @staticmethod
    def success(
        t: _success_1__T, list: java.util.List[typing.Union[java.lang.String, str]]
    ) -> "ApiEnvelope"[_success_1__T]: ...
    def toJson(self) -> java.lang.String: ...
    @staticmethod
    def validationStatus(
        boolean: bool,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
    ) -> com.google.gson.JsonObject: ...
    def withProvenance(
        self, resultProvenance: "ResultProvenance"
    ) -> "ApiEnvelope"[_ApiEnvelope__T]: ...
    def withQualityGate(
        self, jsonObject: com.google.gson.JsonObject
    ) -> "ApiEnvelope"[_ApiEnvelope__T]: ...
    def withTool(
        self, string: typing.Union[java.lang.String, str]
    ) -> "ApiEnvelope"[_ApiEnvelope__T]: ...
    def withValidation(
        self, jsonObject: com.google.gson.JsonObject
    ) -> "ApiEnvelope"[_ApiEnvelope__T]: ...

class DiagnosticIssue:
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        string3: typing.Union[java.lang.String, str],
        string4: typing.Union[java.lang.String, str],
    ): ...
    @staticmethod
    def error(
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        string3: typing.Union[java.lang.String, str],
    ) -> "DiagnosticIssue": ...
    def getCode(self) -> java.lang.String: ...
    def getMessage(self) -> java.lang.String: ...
    def getRemediation(self) -> java.lang.String: ...
    def getSeverity(self) -> java.lang.String: ...
    def isError(self) -> bool: ...
    def toJson(self) -> com.google.gson.JsonObject: ...
    def toString(self) -> java.lang.String: ...
    @staticmethod
    def warning(
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        string3: typing.Union[java.lang.String, str],
    ) -> "DiagnosticIssue": ...

class FlashRequest:
    def __init__(self): ...
    def addComponent(
        self, string: typing.Union[java.lang.String, str], double: float
    ) -> "FlashRequest": ...
    @staticmethod
    def fromJson(jsonObject: com.google.gson.JsonObject) -> "FlashRequest": ...
    def getComponents(self) -> java.util.Map[java.lang.String, float]: ...
    def getEnthalpy(self) -> "ValueWithUnit": ...
    def getEntropy(self) -> "ValueWithUnit": ...
    def getFlashType(self) -> java.lang.String: ...
    def getMixingRule(self) -> java.lang.String: ...
    def getModel(self) -> java.lang.String: ...
    def getPressure(self) -> "ValueWithUnit": ...
    def getTemperature(self) -> "ValueWithUnit": ...
    def getVolume(self) -> "ValueWithUnit": ...
    def setComponents(
        self,
        map: typing.Union[
            java.util.Map[typing.Union[java.lang.String, str], float],
            typing.Mapping[typing.Union[java.lang.String, str], float],
        ],
    ) -> "FlashRequest": ...
    def setEnthalpy(self, valueWithUnit: "ValueWithUnit") -> "FlashRequest": ...
    def setEntropy(self, valueWithUnit: "ValueWithUnit") -> "FlashRequest": ...
    def setFlashType(
        self, string: typing.Union[java.lang.String, str]
    ) -> "FlashRequest": ...
    def setMixingRule(
        self, string: typing.Union[java.lang.String, str]
    ) -> "FlashRequest": ...
    def setModel(
        self, string: typing.Union[java.lang.String, str]
    ) -> "FlashRequest": ...
    def setPressure(self, valueWithUnit: "ValueWithUnit") -> "FlashRequest": ...
    def setTemperature(self, valueWithUnit: "ValueWithUnit") -> "FlashRequest": ...
    def setVolume(self, valueWithUnit: "ValueWithUnit") -> "FlashRequest": ...

class FlashResult:
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        int: int,
        list: java.util.List[typing.Union[java.lang.String, str]],
        fluidResponse: jneqsim.process.util.monitor.FluidResponse,
    ): ...
    def getFlashType(self) -> java.lang.String: ...
    def getFluidResponse(self) -> jneqsim.process.util.monitor.FluidResponse: ...
    def getModel(self) -> java.lang.String: ...
    def getNumberOfPhases(self) -> int: ...
    def getPhases(self) -> java.util.List[java.lang.String]: ...

class ProcessResult:
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        processModel: jneqsim.process.processmodel.ProcessModel,
        string2: typing.Union[java.lang.String, str],
        list: java.util.List[typing.Union[java.lang.String, str]],
    ): ...
    @typing.overload
    def __init__(
        self,
        string: typing.Union[java.lang.String, str],
        processSystem: jneqsim.process.processmodel.ProcessSystem,
        string2: typing.Union[java.lang.String, str],
    ): ...
    def getAreaNames(self) -> java.util.List[java.lang.String]: ...
    def getProcessModel(self) -> jneqsim.process.processmodel.ProcessModel: ...
    def getProcessModelName(self) -> java.lang.String: ...
    def getProcessSystem(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getProcessSystemName(self) -> java.lang.String: ...
    def getReportJson(self) -> java.lang.String: ...
    def isProcessModel(self) -> bool: ...

class ResultProvenance:
    def __init__(self): ...
    def addApplicabilityWarning(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def addAssumption(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def addLimitation(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def addValidationPassed(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    @staticmethod
    def forBatch(
        string: typing.Union[java.lang.String, str], int: int, int2: int
    ) -> "ResultProvenance": ...
    @staticmethod
    def forFlash(
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        string3: typing.Union[java.lang.String, str],
    ) -> "ResultProvenance": ...
    @staticmethod
    def forPhaseEnvelope(
        string: typing.Union[java.lang.String, str],
    ) -> "ResultProvenance": ...
    @staticmethod
    def forProcess(
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        int: int,
    ) -> "ResultProvenance": ...
    @staticmethod
    def forPropertyTable(
        string: typing.Union[java.lang.String, str],
        string2: typing.Union[java.lang.String, str],
        int: int,
    ) -> "ResultProvenance": ...
    def getApplicabilityWarnings(self) -> java.util.List[java.lang.String]: ...
    def getAssumptions(self) -> java.util.List[java.lang.String]: ...
    def getBenchmarkTrustLevel(self) -> java.lang.String: ...
    def getCalculationType(self) -> java.lang.String: ...
    def getComputationTimeMs(self) -> int: ...
    def getConvergence(self) -> "ResultProvenance.Convergence": ...
    def getEngine(self) -> java.lang.String: ...
    def getLimitations(self) -> java.util.List[java.lang.String]: ...
    def getMixingRule(self) -> java.lang.String: ...
    def getModel(self) -> java.lang.String: ...
    def getResultOrigin(self) -> java.lang.String: ...
    def getThermodynamicModel(self) -> java.lang.String: ...
    def getTimestamp(self) -> java.lang.String: ...
    def getValidationsPassed(self) -> java.util.List[java.lang.String]: ...
    def isConverged(self) -> bool: ...
    def setBenchmarkTrustLevel(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setCalculationType(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...
    def setComputationTimeMs(self, long: int) -> None: ...
    def setConverged(self, boolean: bool) -> None: ...
    def setMixingRule(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setResultOrigin(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setThermodynamicModel(
        self, string: typing.Union[java.lang.String, str]
    ) -> None: ...

    class Convergence:
        def __init__(
            self, boolean: bool, string: typing.Union[java.lang.String, str]
        ): ...
        def getMessage(self) -> java.lang.String: ...
        def isConverged(self) -> bool: ...

class ValueWithUnit:
    def __init__(self, double: float, string: typing.Union[java.lang.String, str]): ...
    @staticmethod
    def fromJson(
        jsonElement: com.google.gson.JsonElement,
        string: typing.Union[java.lang.String, str],
    ) -> "ValueWithUnit": ...
    def getUnit(self) -> java.lang.String: ...
    def getValue(self) -> float: ...
    def toJson(self) -> com.google.gson.JsonElement: ...
    def toString(self) -> java.lang.String: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.mcp.model")``.

    ApiEnvelope: typing.Type[ApiEnvelope]
    DiagnosticIssue: typing.Type[DiagnosticIssue]
    FlashRequest: typing.Type[FlashRequest]
    FlashResult: typing.Type[FlashResult]
    ProcessResult: typing.Type[ProcessResult]
    ResultProvenance: typing.Type[ResultProvenance]
    ValueWithUnit: typing.Type[ValueWithUnit]
