name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        version: [3.9, 3.12, 3.13]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        run: pipx install uv

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        run: uv sync

      - name: Run tests with pytest
        run: uv run pytest -p no:faulthandler
