import sys

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jneqsim.process.equipment
import jneqsim.process.mechanicaldesign
import typing

class PowerGenerationMechanicalDesign(
    jneqsim.process.mechanicaldesign.MechanicalDesign
):
    def __init__(
        self,
        processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface,
    ): ...
    def calcDesign(self) -> None: ...
    def getCo2EmissionTonnesHr(self) -> float: ...
    def getExhaustMassFlowKgS(self) -> float: ...
    def getExhaustTemperatureC(self) -> float: ...
    def getFuelConsumptionKgHr(self) -> float: ...
    def getHeatRateKJkWh(self) -> float: ...
    def getNoiseLevelDbA(self) -> float: ...
    def getNoxPpm(self) -> float: ...
    def getRatedPowerMW(self) -> float: ...
    def getThermalEfficiency(self) -> float: ...
    def getTotalSystemWeightTonnes(self) -> float: ...
    def getTurbineClass(self) -> java.lang.String: ...
    def getTurbinePackageWeightTonnes(self) -> float: ...
    def getWhruDutyMW(self) -> float: ...
    def setIncludeWHRU(self, boolean: bool) -> None: ...
    def setNoxPpm(self, double: float) -> None: ...
    def setWhruOutletTemperatureC(self, double: float) -> None: ...

class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.powergeneration")``.

    PowerGenerationMechanicalDesign: typing.Type[PowerGenerationMechanicalDesign]
