
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.costestimation
import jneqsim.process.equipment
import jneqsim.process.mechanicaldesign.absorber
import jneqsim.process.mechanicaldesign.adsorber
import jneqsim.process.mechanicaldesign.compressor
import jneqsim.process.mechanicaldesign.data
import jneqsim.process.mechanicaldesign.designstandards
import jneqsim.process.mechanicaldesign.ejector
import jneqsim.process.mechanicaldesign.expander
import jneqsim.process.mechanicaldesign.heatexchanger
import jneqsim.process.mechanicaldesign.pipeline
import jneqsim.process.mechanicaldesign.pump
import jneqsim.process.mechanicaldesign.separator
import jneqsim.process.mechanicaldesign.tank
import jneqsim.process.mechanicaldesign.torg
import jneqsim.process.mechanicaldesign.valve
import jneqsim.process.processmodel
import typing



class DesignCase(java.lang.Enum['DesignCase']):
    NORMAL: typing.ClassVar['DesignCase'] = ...
    MAXIMUM: typing.ClassVar['DesignCase'] = ...
    MINIMUM: typing.ClassVar['DesignCase'] = ...
    STARTUP: typing.ClassVar['DesignCase'] = ...
    SHUTDOWN: typing.ClassVar['DesignCase'] = ...
    UPSET: typing.ClassVar['DesignCase'] = ...
    EMERGENCY: typing.ClassVar['DesignCase'] = ...
    WINTER: typing.ClassVar['DesignCase'] = ...
    SUMMER: typing.ClassVar['DesignCase'] = ...
    EARLY_LIFE: typing.ClassVar['DesignCase'] = ...
    LATE_LIFE: typing.ClassVar['DesignCase'] = ...
    def getDescription(self) -> java.lang.String: ...
    def getDisplayName(self) -> java.lang.String: ...
    def getTypicalLoadFactor(self) -> float: ...
    def isSizingCritical(self) -> bool: ...
    def isTurndownCase(self) -> bool: ...
    def requiresReliefSizing(self) -> bool: ...
    def toString(self) -> java.lang.String: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'DesignCase': ...
    @staticmethod
    def values() -> typing.MutableSequence['DesignCase']: ...

class DesignLimitData(java.io.Serializable):
    EMPTY: typing.ClassVar['DesignLimitData'] = ...
    @staticmethod
    def builder() -> 'DesignLimitData.Builder': ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCorrosionAllowance(self) -> float: ...
    def getJointEfficiency(self) -> float: ...
    def getMaxPressure(self) -> float: ...
    def getMaxTemperature(self) -> float: ...
    def getMinPressure(self) -> float: ...
    def getMinTemperature(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> java.lang.String: ...
    class Builder:
        def build(self) -> 'DesignLimitData': ...
        def corrosionAllowance(self, double: float) -> 'DesignLimitData.Builder': ...
        def jointEfficiency(self, double: float) -> 'DesignLimitData.Builder': ...
        def maxPressure(self, double: float) -> 'DesignLimitData.Builder': ...
        def maxTemperature(self, double: float) -> 'DesignLimitData.Builder': ...
        def minPressure(self, double: float) -> 'DesignLimitData.Builder': ...
        def minTemperature(self, double: float) -> 'DesignLimitData.Builder': ...

class DesignPhase(java.lang.Enum['DesignPhase']):
    SCREENING: typing.ClassVar['DesignPhase'] = ...
    CONCEPT_SELECT: typing.ClassVar['DesignPhase'] = ...
    PRE_FEED: typing.ClassVar['DesignPhase'] = ...
    FEED: typing.ClassVar['DesignPhase'] = ...
    DETAIL_DESIGN: typing.ClassVar['DesignPhase'] = ...
    AS_BUILT: typing.ClassVar['DesignPhase'] = ...
    def getAccuracyRange(self) -> java.lang.String: ...
    def getDescription(self) -> java.lang.String: ...
    def getDisplayName(self) -> java.lang.String: ...
    def getMaxAccuracy(self) -> float: ...
    def getMinAccuracy(self) -> float: ...
    def requiresDetailedCompliance(self) -> bool: ...
    def requiresFullMechanicalDesign(self) -> bool: ...
    def toString(self) -> java.lang.String: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'DesignPhase': ...
    @staticmethod
    def values() -> typing.MutableSequence['DesignPhase']: ...

class DesignValidationResult(java.io.Serializable):
    def __init__(self): ...
    def addCritical(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> 'DesignValidationResult': ...
    def addError(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> 'DesignValidationResult': ...
    def addInfo(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'DesignValidationResult': ...
    def addMessage(self, severity: 'DesignValidationResult.Severity', string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> 'DesignValidationResult': ...
    def addMetric(self, string: typing.Union[java.lang.String, str], object: typing.Any) -> 'DesignValidationResult': ...
    def addWarning(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> 'DesignValidationResult': ...
    def getCount(self, severity: 'DesignValidationResult.Severity') -> int: ...
    @typing.overload
    def getMessages(self) -> java.util.List['DesignValidationResult.ValidationMessage']: ...
    @typing.overload
    def getMessages(self, severity: 'DesignValidationResult.Severity') -> java.util.List['DesignValidationResult.ValidationMessage']: ...
    def getMetrics(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getSummary(self) -> java.lang.String: ...
    def getSummaryCounts(self) -> java.util.Map['DesignValidationResult.Severity', int]: ...
    def hasErrors(self) -> bool: ...
    def hasRun(self) -> bool: ...
    def hasWarnings(self) -> bool: ...
    def isValid(self) -> bool: ...
    def merge(self, designValidationResult: 'DesignValidationResult') -> 'DesignValidationResult': ...
    def toString(self) -> java.lang.String: ...
    class Severity(java.lang.Enum['DesignValidationResult.Severity']):
        INFO: typing.ClassVar['DesignValidationResult.Severity'] = ...
        WARNING: typing.ClassVar['DesignValidationResult.Severity'] = ...
        ERROR: typing.ClassVar['DesignValidationResult.Severity'] = ...
        CRITICAL: typing.ClassVar['DesignValidationResult.Severity'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'DesignValidationResult.Severity': ...
        @staticmethod
        def values() -> typing.MutableSequence['DesignValidationResult.Severity']: ...
    class ValidationMessage(java.io.Serializable):
        def __init__(self, severity: 'DesignValidationResult.Severity', string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
        def getCategory(self) -> java.lang.String: ...
        def getEquipmentName(self) -> java.lang.String: ...
        def getMessage(self) -> java.lang.String: ...
        def getRemediation(self) -> java.lang.String: ...
        def getSeverity(self) -> 'DesignValidationResult.Severity': ...
        def toString(self) -> java.lang.String: ...

class FieldDevelopmentDesignOrchestrator(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem, string: typing.Union[java.lang.String, str]): ...
    def addDesignCase(self, designCase: DesignCase) -> 'FieldDevelopmentDesignOrchestrator': ...
    def addTorgDataSource(self, torgDataSource: jneqsim.process.mechanicaldesign.torg.TorgDataSource) -> 'FieldDevelopmentDesignOrchestrator': ...
    def generateDesignReport(self) -> java.lang.String: ...
    def getActiveTorg(self) -> jneqsim.process.mechanicaldesign.torg.TechnicalRequirementsDocument: ...
    def getCaseResults(self) -> java.util.Map[DesignCase, 'FieldDevelopmentDesignOrchestrator.DesignCaseResult']: ...
    def getDesignCases(self) -> java.util.List[DesignCase]: ...
    def getDesignPhase(self) -> DesignPhase: ...
    def getProcessSystem(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getProjectId(self) -> java.lang.String: ...
    def getRunId(self) -> java.util.UUID: ...
    def getSystemMechanicalDesign(self) -> 'SystemMechanicalDesign': ...
    def getTorgManager(self) -> jneqsim.process.mechanicaldesign.torg.TorgManager: ...
    def getValidationResult(self) -> DesignValidationResult: ...
    def getWorkflowHistory(self) -> java.util.List['FieldDevelopmentDesignOrchestrator.WorkflowStep']: ...
    @typing.overload
    def loadTorg(self, string: typing.Union[java.lang.String, str]) -> bool: ...
    @typing.overload
    def loadTorg(self, string: typing.Union[java.lang.String, str], torgDataSource: jneqsim.process.mechanicaldesign.torg.TorgDataSource) -> bool: ...
    def runCompleteDesignWorkflow(self) -> bool: ...
    def setDesignCases(self, list: java.util.List[DesignCase]) -> 'FieldDevelopmentDesignOrchestrator': ...
    def setDesignPhase(self, designPhase: DesignPhase) -> 'FieldDevelopmentDesignOrchestrator': ...
    class DesignCaseResult(java.io.Serializable):
        def __init__(self, designCase: DesignCase): ...
        def getDesignCase(self) -> DesignCase: ...
        def getTotalVolume(self) -> float: ...
        def getTotalWeight(self) -> float: ...
        def getValidation(self) -> DesignValidationResult: ...
        def isConverged(self) -> bool: ...
        def setConverged(self, boolean: bool) -> None: ...
        def setTotalVolume(self, double: float) -> None: ...
        def setTotalWeight(self, double: float) -> None: ...
        def setValidation(self, designValidationResult: DesignValidationResult) -> None: ...
    class WorkflowStep(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def complete(self, boolean: bool, string: typing.Union[java.lang.String, str]) -> None: ...
        def getDurationMs(self) -> int: ...
        def getMessage(self) -> java.lang.String: ...
        def getStepName(self) -> java.lang.String: ...
        def isSuccess(self) -> bool: ...

class MechanicalDesign(java.io.Serializable):
    maxDesignVolumeFlow: float = ...
    minDesignVolumeFLow: float = ...
    maxDesignGassVolumeFlow: float = ...
    minDesignGassVolumeFLow: float = ...
    maxDesignOilVolumeFlow: float = ...
    minDesignOilFLow: float = ...
    maxDesignWaterVolumeFlow: float = ...
    minDesignWaterVolumeFLow: float = ...
    maxDesignPower: float = ...
    minDesignPower: float = ...
    maxDesignDuty: float = ...
    minDesignDuty: float = ...
    innerDiameter: float = ...
    outerDiameter: float = ...
    wallThickness: float = ...
    tantanLength: float = ...
    weigthInternals: float = ...
    weightNozzle: float = ...
    weightPiping: float = ...
    weightElectroInstrument: float = ...
    weightStructualSteel: float = ...
    weightVessel: float = ...
    weigthVesselShell: float = ...
    moduleHeight: float = ...
    moduleWidth: float = ...
    moduleLength: float = ...
    designStandard: java.util.Hashtable = ...
    costEstimate: jneqsim.process.costestimation.UnitCostEstimateBaseClass = ...
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def addDesignDataSource(self, mechanicalDesignDataSource: typing.Union[jneqsim.process.mechanicaldesign.data.MechanicalDesignDataSource, typing.Callable]) -> None: ...
    def calcDesign(self) -> None: ...
    def displayResults(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getApplicableStandards(self) -> java.util.List[jneqsim.process.mechanicaldesign.designstandards.StandardType]: ...
    def getCompanySpecificDesignStandards(self) -> java.lang.String: ...
    def getConstrutionMaterial(self) -> java.lang.String: ...
    def getCorrosionAllowance(self) -> float: ...
    def getCostEstimate(self) -> jneqsim.process.costestimation.UnitCostEstimateBaseClass: ...
    def getDefaultLiquidDensity(self) -> float: ...
    def getDefaultLiquidViscosity(self) -> float: ...
    def getDesignCorrosionAllowance(self) -> float: ...
    def getDesignDataSources(self) -> java.util.List[jneqsim.process.mechanicaldesign.data.MechanicalDesignDataSource]: ...
    def getDesignJointEfficiency(self) -> float: ...
    def getDesignLimitData(self) -> DesignLimitData: ...
    def getDesignMaxPressureLimit(self) -> float: ...
    def getDesignMaxTemperatureLimit(self) -> float: ...
    def getDesignMinPressureLimit(self) -> float: ...
    def getDesignMinTemperatureLimit(self) -> float: ...
    def getDesignStandard(self) -> java.util.Hashtable[java.lang.String, jneqsim.process.mechanicaldesign.designstandards.DesignStandard]: ...
    def getInnerDiameter(self) -> float: ...
    def getJointEfficiency(self) -> float: ...
    def getLastMarginResult(self) -> 'MechanicalDesignMarginResult': ...
    def getMaterialDesignStandard(self) -> jneqsim.process.mechanicaldesign.designstandards.MaterialPlateDesignStandard: ...
    def getMaterialPipeDesignStandard(self) -> jneqsim.process.mechanicaldesign.designstandards.MaterialPipeDesignStandard: ...
    def getMaxAllowableStress(self) -> float: ...
    def getMaxDesignGassVolumeFlow(self) -> float: ...
    def getMaxDesignOilVolumeFlow(self) -> float: ...
    def getMaxDesignPressure(self) -> float: ...
    def getMaxDesignVolumeFlow(self) -> float: ...
    def getMaxDesignWaterVolumeFlow(self) -> float: ...
    def getMaxOperationPressure(self) -> float: ...
    def getMaxOperationTemperature(self) -> float: ...
    def getMinDesignGassVolumeFLow(self) -> float: ...
    def getMinDesignOilFLow(self) -> float: ...
    def getMinDesignPressure(self) -> float: ...
    def getMinDesignVolumeFLow(self) -> float: ...
    def getMinDesignWaterVolumeFLow(self) -> float: ...
    def getMinOperationPressure(self) -> float: ...
    def getMinOperationTemperature(self) -> float: ...
    def getModuleHeight(self) -> float: ...
    def getModuleLength(self) -> float: ...
    def getModuleWidth(self) -> float: ...
    def getOuterDiameter(self) -> float: ...
    def getPressureMarginFactor(self) -> float: ...
    def getProcessEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...
    def getRecommendedStandards(self) -> java.util.Map[java.lang.String, java.util.List[jneqsim.process.mechanicaldesign.designstandards.StandardType]]: ...
    def getResponse(self) -> 'MechanicalDesignResponse': ...
    def getTantanLength(self) -> float: ...
    def getTensileStrength(self) -> float: ...
    def getVolumeTotal(self) -> float: ...
    def getWallThickness(self) -> float: ...
    def getWeightElectroInstrument(self) -> float: ...
    def getWeightNozzle(self) -> float: ...
    def getWeightPiping(self) -> float: ...
    def getWeightStructualSteel(self) -> float: ...
    def getWeightTotal(self) -> float: ...
    def getWeightVessel(self) -> float: ...
    def getWeigthInternals(self) -> float: ...
    def getWeigthVesselShell(self) -> float: ...
    def hasDesignStandard(self) -> bool: ...
    def hashCode(self) -> int: ...
    def initMechanicalDesign(self) -> None: ...
    def isHasSetCompanySpecificDesignStandards(self) -> bool: ...
    def readDesignSpecifications(self) -> None: ...
    def setCompanySpecificDesignStandards(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setConstrutionMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setCorrosionAllowance(self, double: float) -> None: ...
    def setDefaultLiquidDensity(self, double: float) -> None: ...
    def setDefaultLiquidViscosity(self, double: float) -> None: ...
    def setDesign(self) -> None: ...
    def setDesignDataSource(self, mechanicalDesignDataSource: typing.Union[jneqsim.process.mechanicaldesign.data.MechanicalDesignDataSource, typing.Callable]) -> None: ...
    def setDesignDataSources(self, list: java.util.List[typing.Union[jneqsim.process.mechanicaldesign.data.MechanicalDesignDataSource, typing.Callable]]) -> None: ...
    @typing.overload
    def setDesignStandard(self, string: typing.Union[java.lang.String, str], designStandard: jneqsim.process.mechanicaldesign.designstandards.DesignStandard) -> None: ...
    @typing.overload
    def setDesignStandard(self, hashtable: java.util.Hashtable[typing.Union[java.lang.String, str], jneqsim.process.mechanicaldesign.designstandards.DesignStandard]) -> None: ...
    @typing.overload
    def setDesignStandard(self, standardType: jneqsim.process.mechanicaldesign.designstandards.StandardType) -> None: ...
    @typing.overload
    def setDesignStandard(self, standardType: jneqsim.process.mechanicaldesign.designstandards.StandardType, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDesignStandards(self, list: java.util.List[jneqsim.process.mechanicaldesign.designstandards.StandardType]) -> None: ...
    def setHasSetCompanySpecificDesignStandards(self, boolean: bool) -> None: ...
    def setInnerDiameter(self, double: float) -> None: ...
    def setJointEfficiency(self, double: float) -> None: ...
    def setMaterialDesignStandard(self, materialPlateDesignStandard: jneqsim.process.mechanicaldesign.designstandards.MaterialPlateDesignStandard) -> None: ...
    def setMaterialPipeDesignStandard(self, materialPipeDesignStandard: jneqsim.process.mechanicaldesign.designstandards.MaterialPipeDesignStandard) -> None: ...
    def setMaxDesignDuty(self, double: float) -> None: ...
    def setMaxDesignGassVolumeFlow(self, double: float) -> None: ...
    def setMaxDesignOilVolumeFlow(self, double: float) -> None: ...
    def setMaxDesignPower(self, double: float) -> None: ...
    def setMaxDesignVolumeFlow(self, double: float) -> None: ...
    def setMaxDesignWaterVolumeFlow(self, double: float) -> None: ...
    def setMaxOperationPressure(self, double: float) -> None: ...
    def setMaxOperationTemperature(self, double: float) -> None: ...
    def setMinDesignDuty(self, double: float) -> None: ...
    def setMinDesignGassVolumeFLow(self, double: float) -> None: ...
    def setMinDesignOilFLow(self, double: float) -> None: ...
    def setMinDesignPower(self, double: float) -> None: ...
    def setMinDesignVolumeFLow(self, double: float) -> None: ...
    def setMinDesignWaterVolumeFLow(self, double: float) -> None: ...
    def setMinOperationPressure(self, double: float) -> None: ...
    def setMinOperationTemperature(self, double: float) -> None: ...
    def setModuleHeight(self, double: float) -> None: ...
    def setModuleLength(self, double: float) -> None: ...
    def setModuleWidth(self, double: float) -> None: ...
    def setOuterDiameter(self, double: float) -> None: ...
    def setPressureMarginFactor(self, double: float) -> None: ...
    def setProcessEquipment(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    def setTantanLength(self, double: float) -> None: ...
    def setTensileStrength(self, double: float) -> None: ...
    def setWallThickness(self, double: float) -> None: ...
    def setWeightElectroInstrument(self, double: float) -> None: ...
    def setWeightNozzle(self, double: float) -> None: ...
    def setWeightPiping(self, double: float) -> None: ...
    def setWeightStructualSteel(self, double: float) -> None: ...
    def setWeightTotal(self, double: float) -> None: ...
    def setWeightVessel(self, double: float) -> None: ...
    def setWeigthInternals(self, double: float) -> None: ...
    def setWeigthVesselShell(self, double: float) -> None: ...
    def toCompactJson(self) -> java.lang.String: ...
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def validateOperatingEnvelope(self) -> 'MechanicalDesignMarginResult': ...
    @typing.overload
    def validateOperatingEnvelope(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> 'MechanicalDesignMarginResult': ...

class MechanicalDesignMarginResult(java.io.Serializable):
    EMPTY: typing.ClassVar['MechanicalDesignMarginResult'] = ...
    def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCorrosionAllowanceMargin(self) -> float: ...
    def getJointEfficiencyMargin(self) -> float: ...
    def getMaxPressureMargin(self) -> float: ...
    def getMaxTemperatureMargin(self) -> float: ...
    def getMinPressureMargin(self) -> float: ...
    def getMinTemperatureMargin(self) -> float: ...
    def hashCode(self) -> int: ...
    def isWithinDesignEnvelope(self) -> bool: ...
    def toString(self) -> java.lang.String: ...

class MechanicalDesignReport(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def generateCompleteReport(self) -> java.lang.String: ...
    def generateEquipmentDataSheets(self) -> java.lang.String: ...
    def generateEquipmentListCSV(self) -> java.lang.String: ...
    def generatePipingLineListCSV(self) -> java.lang.String: ...
    def generateWeightReport(self) -> java.lang.String: ...
    def getPipingDesign(self) -> 'ProcessInterconnectionDesign': ...
    def getSystemDesign(self) -> 'SystemMechanicalDesign': ...
    def runDesignCalculations(self) -> None: ...
    def writeEquipmentListCSV(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def writePipingLineListCSV(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def writeWeightReport(self, string: typing.Union[java.lang.String, str]) -> None: ...

class MechanicalDesignResponse(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, mechanicalDesign: MechanicalDesign): ...
    @typing.overload
    def __init__(self, systemMechanicalDesign: 'SystemMechanicalDesign'): ...
    def addSpecificParameter(self, string: typing.Union[java.lang.String, str], object: typing.Any) -> None: ...
    @staticmethod
    def fromJson(string: typing.Union[java.lang.String, str]) -> 'MechanicalDesignResponse': ...
    def getCorrosionAllowance(self) -> float: ...
    def getCountByType(self) -> java.util.Map[java.lang.String, int]: ...
    def getDesignStandard(self) -> java.lang.String: ...
    def getDuty(self) -> float: ...
    def getEiWeight(self) -> float: ...
    def getEquipmentClass(self) -> java.lang.String: ...
    def getEquipmentCount(self) -> int: ...
    def getEquipmentList(self) -> java.util.List['MechanicalDesignResponse.EquipmentSummary']: ...
    def getEquipmentType(self) -> java.lang.String: ...
    def getFootprintLength(self) -> float: ...
    def getFootprintWidth(self) -> float: ...
    def getHeadMaterial(self) -> java.lang.String: ...
    def getInnerDiameter(self) -> float: ...
    def getInternalsWeight(self) -> float: ...
    def getMaxDesignPressure(self) -> float: ...
    def getMaxDesignTemperature(self) -> float: ...
    def getMaxHeight(self) -> float: ...
    def getMaxOperatingPressure(self) -> float: ...
    def getMaxOperatingTemperature(self) -> float: ...
    def getMinDesignPressure(self) -> float: ...
    def getMinDesignTemperature(self) -> float: ...
    def getModuleHeight(self) -> float: ...
    def getModuleLength(self) -> float: ...
    def getModuleWidth(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getNetPower(self) -> float: ...
    def getNozzlesWeight(self) -> float: ...
    def getOperatingWeight(self) -> float: ...
    def getOuterDiameter(self) -> float: ...
    def getPipingWeight(self) -> float: ...
    def getPower(self) -> float: ...
    def getProcessName(self) -> java.lang.String: ...
    def getShellMaterial(self) -> java.lang.String: ...
    def getSpecificParameters(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getStructuralWeight(self) -> float: ...
    def getTangentLength(self) -> float: ...
    def getTotalCoolingDuty(self) -> float: ...
    def getTotalHeatingDuty(self) -> float: ...
    def getTotalPlotSpace(self) -> float: ...
    def getTotalPowerRecovered(self) -> float: ...
    def getTotalPowerRequired(self) -> float: ...
    def getTotalVolume(self) -> float: ...
    def getTotalWeight(self) -> float: ...
    def getVesselWeight(self) -> float: ...
    def getWallThickness(self) -> float: ...
    def getWeightByDiscipline(self) -> java.util.Map[java.lang.String, float]: ...
    def getWeightByType(self) -> java.util.Map[java.lang.String, float]: ...
    def isSystemLevel(self) -> bool: ...
    def mergeWithEquipmentJson(self, string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    def populateFromMechanicalDesign(self, mechanicalDesign: MechanicalDesign) -> None: ...
    def populateFromSystemMechanicalDesign(self, systemMechanicalDesign: 'SystemMechanicalDesign') -> None: ...
    def setCorrosionAllowance(self, double: float) -> None: ...
    def setCountByType(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], int], typing.Mapping[typing.Union[java.lang.String, str], int]]) -> None: ...
    def setDesignStandard(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDuty(self, double: float) -> None: ...
    def setEiWeight(self, double: float) -> None: ...
    def setEquipmentClass(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setEquipmentCount(self, int: int) -> None: ...
    def setEquipmentList(self, list: java.util.List['MechanicalDesignResponse.EquipmentSummary']) -> None: ...
    def setEquipmentType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setFootprintLength(self, double: float) -> None: ...
    def setFootprintWidth(self, double: float) -> None: ...
    def setHeadMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setInnerDiameter(self, double: float) -> None: ...
    def setInternalsWeight(self, double: float) -> None: ...
    def setMaxDesignPressure(self, double: float) -> None: ...
    def setMaxDesignTemperature(self, double: float) -> None: ...
    def setMaxHeight(self, double: float) -> None: ...
    def setMaxOperatingPressure(self, double: float) -> None: ...
    def setMaxOperatingTemperature(self, double: float) -> None: ...
    def setMinDesignPressure(self, double: float) -> None: ...
    def setMinDesignTemperature(self, double: float) -> None: ...
    def setModuleHeight(self, double: float) -> None: ...
    def setModuleLength(self, double: float) -> None: ...
    def setModuleWidth(self, double: float) -> None: ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setNetPower(self, double: float) -> None: ...
    def setNozzlesWeight(self, double: float) -> None: ...
    def setOperatingWeight(self, double: float) -> None: ...
    def setOuterDiameter(self, double: float) -> None: ...
    def setPipingWeight(self, double: float) -> None: ...
    def setPower(self, double: float) -> None: ...
    def setProcessName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setShellMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSpecificParameters(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Any], typing.Mapping[typing.Union[java.lang.String, str], typing.Any]]) -> None: ...
    def setStructuralWeight(self, double: float) -> None: ...
    def setSystemLevel(self, boolean: bool) -> None: ...
    def setTangentLength(self, double: float) -> None: ...
    def setTotalCoolingDuty(self, double: float) -> None: ...
    def setTotalHeatingDuty(self, double: float) -> None: ...
    def setTotalPlotSpace(self, double: float) -> None: ...
    def setTotalPowerRecovered(self, double: float) -> None: ...
    def setTotalPowerRequired(self, double: float) -> None: ...
    def setTotalVolume(self, double: float) -> None: ...
    def setTotalWeight(self, double: float) -> None: ...
    def setVesselWeight(self, double: float) -> None: ...
    def setWallThickness(self, double: float) -> None: ...
    def setWeightByDiscipline(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]]) -> None: ...
    def setWeightByType(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]]) -> None: ...
    def toCompactJson(self) -> java.lang.String: ...
    def toJson(self) -> java.lang.String: ...
    class EquipmentSummary(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
        def getDesignPressure(self) -> float: ...
        def getDesignTemperature(self) -> float: ...
        def getDimensions(self) -> java.lang.String: ...
        def getDuty(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getPower(self) -> float: ...
        def getType(self) -> java.lang.String: ...
        def getWeight(self) -> float: ...
        def setDesignPressure(self, double: float) -> None: ...
        def setDesignTemperature(self, double: float) -> None: ...
        def setDimensions(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setDuty(self, double: float) -> None: ...
        def setPower(self, double: float) -> None: ...
        def setWeight(self, double: float) -> None: ...

class ProcessInterconnectionDesign(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def calculatePipingEstimates(self) -> None: ...
    def generatePipingReport(self) -> java.lang.String: ...
    def getFittingWeight(self) -> float: ...
    def getFlangeWeight(self) -> float: ...
    def getLengthBySize(self) -> java.util.Map[java.lang.String, float]: ...
    def getPipeSegments(self) -> java.util.List['ProcessInterconnectionDesign.PipeSegment']: ...
    def getTotalElbowCount(self) -> int: ...
    def getTotalFlangeCount(self) -> int: ...
    def getTotalPipingLength(self) -> float: ...
    def getTotalPipingWeight(self) -> float: ...
    def getTotalTeeCount(self) -> int: ...
    def getTotalValveCount(self) -> int: ...
    def getValveWeight(self) -> float: ...
    def getWeightBySize(self) -> java.util.Map[java.lang.String, float]: ...
    class PipeSegment(java.io.Serializable):
        def __init__(self): ...
        def getDesignPressureBara(self) -> float: ...
        def getDesignTemperatureC(self) -> float: ...
        def getFromEquipment(self) -> java.lang.String: ...
        def getLengthM(self) -> float: ...
        def getMaterial(self) -> java.lang.String: ...
        def getNominalSizeInch(self) -> float: ...
        def getOutsideDiameterMm(self) -> float: ...
        def getSchedule(self) -> java.lang.String: ...
        def getStreamName(self) -> java.lang.String: ...
        def getToEquipment(self) -> java.lang.String: ...
        def getWallThicknessMm(self) -> float: ...
        def getWeightKg(self) -> float: ...
        def isGasService(self) -> bool: ...
        def setDesignPressureBara(self, double: float) -> None: ...
        def setDesignTemperatureC(self, double: float) -> None: ...
        def setFromEquipment(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setGasService(self, boolean: bool) -> None: ...
        def setLengthM(self, double: float) -> None: ...
        def setMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setNominalSizeInch(self, double: float) -> None: ...
        def setOutsideDiameterMm(self, double: float) -> None: ...
        def setSchedule(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setStreamName(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setToEquipment(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setWallThicknessMm(self, double: float) -> None: ...
        def setWeightKg(self, double: float) -> None: ...
        def toString(self) -> java.lang.String: ...

class SystemMechanicalDesign(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def equals(self, object: typing.Any) -> bool: ...
    def generateJsonSummary(self) -> java.lang.String: ...
    def generateSummaryReport(self) -> java.lang.String: ...
    def getEquipmentCountByType(self) -> java.util.Map[java.lang.String, int]: ...
    def getEquipmentList(self) -> java.util.List['SystemMechanicalDesign.EquipmentDesignSummary']: ...
    def getMaxEquipmentHeight(self) -> float: ...
    def getMechanicalWeight(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getNetPowerRequirement(self) -> float: ...
    def getProcess(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getResponse(self) -> MechanicalDesignResponse: ...
    def getTotalCoolingDuty(self) -> float: ...
    def getTotalFootprintLength(self) -> float: ...
    def getTotalFootprintWidth(self) -> float: ...
    def getTotalHeatingDuty(self) -> float: ...
    def getTotalNumberOfModules(self) -> int: ...
    def getTotalPlotSpace(self) -> float: ...
    def getTotalPowerRecovered(self) -> float: ...
    def getTotalPowerRequired(self) -> float: ...
    def getTotalVolume(self) -> float: ...
    def getTotalWeight(self) -> float: ...
    def getWeightByDiscipline(self) -> java.util.Map[java.lang.String, float]: ...
    def getWeightByEquipmentType(self) -> java.util.Map[java.lang.String, float]: ...
    def hashCode(self) -> int: ...
    def runDesignCalculation(self) -> None: ...
    def setCompanySpecificDesignStandards(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDesign(self) -> None: ...
    def toCompactJson(self) -> java.lang.String: ...
    def toJson(self) -> java.lang.String: ...
    class EquipmentDesignSummary(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
        def getDesignPressure(self) -> float: ...
        def getDesignTemperature(self) -> float: ...
        def getDimensions(self) -> java.lang.String: ...
        def getDuty(self) -> float: ...
        def getHeight(self) -> float: ...
        def getLength(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getPower(self) -> float: ...
        def getType(self) -> java.lang.String: ...
        def getWeight(self) -> float: ...
        def getWidth(self) -> float: ...
        def setDesignPressure(self, double: float) -> None: ...
        def setDesignTemperature(self, double: float) -> None: ...
        def setDimensions(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def setDuty(self, double: float) -> None: ...
        def setHeight(self, double: float) -> None: ...
        def setLength(self, double: float) -> None: ...
        def setPower(self, double: float) -> None: ...
        def setWeight(self, double: float) -> None: ...
        def setWidth(self, double: float) -> None: ...
        def toString(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign")``.

    DesignCase: typing.Type[DesignCase]
    DesignLimitData: typing.Type[DesignLimitData]
    DesignPhase: typing.Type[DesignPhase]
    DesignValidationResult: typing.Type[DesignValidationResult]
    FieldDevelopmentDesignOrchestrator: typing.Type[FieldDevelopmentDesignOrchestrator]
    MechanicalDesign: typing.Type[MechanicalDesign]
    MechanicalDesignMarginResult: typing.Type[MechanicalDesignMarginResult]
    MechanicalDesignReport: typing.Type[MechanicalDesignReport]
    MechanicalDesignResponse: typing.Type[MechanicalDesignResponse]
    ProcessInterconnectionDesign: typing.Type[ProcessInterconnectionDesign]
    SystemMechanicalDesign: typing.Type[SystemMechanicalDesign]
    absorber: jneqsim.process.mechanicaldesign.absorber.__module_protocol__
    adsorber: jneqsim.process.mechanicaldesign.adsorber.__module_protocol__
    compressor: jneqsim.process.mechanicaldesign.compressor.__module_protocol__
    data: jneqsim.process.mechanicaldesign.data.__module_protocol__
    designstandards: jneqsim.process.mechanicaldesign.designstandards.__module_protocol__
    ejector: jneqsim.process.mechanicaldesign.ejector.__module_protocol__
    expander: jneqsim.process.mechanicaldesign.expander.__module_protocol__
    heatexchanger: jneqsim.process.mechanicaldesign.heatexchanger.__module_protocol__
    pipeline: jneqsim.process.mechanicaldesign.pipeline.__module_protocol__
    pump: jneqsim.process.mechanicaldesign.pump.__module_protocol__
    separator: jneqsim.process.mechanicaldesign.separator.__module_protocol__
    tank: jneqsim.process.mechanicaldesign.tank.__module_protocol__
    torg: jneqsim.process.mechanicaldesign.torg.__module_protocol__
    valve: jneqsim.process.mechanicaldesign.valve.__module_protocol__
