
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.costestimation
import jneqsim.process.equipment
import jneqsim.process.mechanicaldesign.absorber
import jneqsim.process.mechanicaldesign.adsorber
import jneqsim.process.mechanicaldesign.compressor
import jneqsim.process.mechanicaldesign.data
import jneqsim.process.mechanicaldesign.designstandards
import jneqsim.process.mechanicaldesign.ejector
import jneqsim.process.mechanicaldesign.heatexchanger
import jneqsim.process.mechanicaldesign.pipeline
import jneqsim.process.mechanicaldesign.separator
import jneqsim.process.mechanicaldesign.valve
import jneqsim.process.processmodel
import typing



class DesignLimitData(java.io.Serializable):
    EMPTY: typing.ClassVar['DesignLimitData'] = ...
    @staticmethod
    def builder() -> 'DesignLimitData.Builder': ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCorrosionAllowance(self) -> float: ...
    def getJointEfficiency(self) -> float: ...
    def getMaxPressure(self) -> float: ...
    def getMaxTemperature(self) -> float: ...
    def getMinPressure(self) -> float: ...
    def getMinTemperature(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> java.lang.String: ...
    class Builder:
        def build(self) -> 'DesignLimitData': ...
        def corrosionAllowance(self, double: float) -> 'DesignLimitData.Builder': ...
        def jointEfficiency(self, double: float) -> 'DesignLimitData.Builder': ...
        def maxPressure(self, double: float) -> 'DesignLimitData.Builder': ...
        def maxTemperature(self, double: float) -> 'DesignLimitData.Builder': ...
        def minPressure(self, double: float) -> 'DesignLimitData.Builder': ...
        def minTemperature(self, double: float) -> 'DesignLimitData.Builder': ...

class MechanicalDesign(java.io.Serializable):
    maxDesignVolumeFlow: float = ...
    minDesignVolumeFLow: float = ...
    maxDesignGassVolumeFlow: float = ...
    minDesignGassVolumeFLow: float = ...
    maxDesignOilVolumeFlow: float = ...
    minDesignOilFLow: float = ...
    maxDesignWaterVolumeFlow: float = ...
    minDesignWaterVolumeFLow: float = ...
    maxDesignPower: float = ...
    minDesignPower: float = ...
    maxDesignDuty: float = ...
    minDesignDuty: float = ...
    innerDiameter: float = ...
    outerDiameter: float = ...
    wallThickness: float = ...
    tantanLength: float = ...
    weigthInternals: float = ...
    weightNozzle: float = ...
    weightPiping: float = ...
    weightElectroInstrument: float = ...
    weightStructualSteel: float = ...
    weightVessel: float = ...
    weigthVesselShell: float = ...
    moduleHeight: float = ...
    moduleWidth: float = ...
    moduleLength: float = ...
    designStandard: java.util.Hashtable = ...
    costEstimate: jneqsim.process.costestimation.UnitCostEstimateBaseClass = ...
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def addDesignDataSource(self, mechanicalDesignDataSource: typing.Union[jneqsim.process.mechanicaldesign.data.MechanicalDesignDataSource, typing.Callable]) -> None: ...
    def calcDesign(self) -> None: ...
    def displayResults(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCompanySpecificDesignStandards(self) -> java.lang.String: ...
    def getConstrutionMaterial(self) -> java.lang.String: ...
    def getCorrosionAllowance(self) -> float: ...
    def getCostEstimate(self) -> jneqsim.process.costestimation.UnitCostEstimateBaseClass: ...
    def getDefaultLiquidDensity(self) -> float: ...
    def getDefaultLiquidViscosity(self) -> float: ...
    def getDesignCorrosionAllowance(self) -> float: ...
    def getDesignDataSources(self) -> java.util.List[jneqsim.process.mechanicaldesign.data.MechanicalDesignDataSource]: ...
    def getDesignJointEfficiency(self) -> float: ...
    def getDesignLimitData(self) -> DesignLimitData: ...
    def getDesignMaxPressureLimit(self) -> float: ...
    def getDesignMaxTemperatureLimit(self) -> float: ...
    def getDesignMinPressureLimit(self) -> float: ...
    def getDesignMinTemperatureLimit(self) -> float: ...
    def getDesignStandard(self) -> java.util.Hashtable[java.lang.String, jneqsim.process.mechanicaldesign.designstandards.DesignStandard]: ...
    def getInnerDiameter(self) -> float: ...
    def getJointEfficiency(self) -> float: ...
    def getLastMarginResult(self) -> 'MechanicalDesignMarginResult': ...
    def getMaterialDesignStandard(self) -> jneqsim.process.mechanicaldesign.designstandards.MaterialPlateDesignStandard: ...
    def getMaterialPipeDesignStandard(self) -> jneqsim.process.mechanicaldesign.designstandards.MaterialPipeDesignStandard: ...
    def getMaxAllowableStress(self) -> float: ...
    def getMaxDesignGassVolumeFlow(self) -> float: ...
    def getMaxDesignOilVolumeFlow(self) -> float: ...
    def getMaxDesignPressure(self) -> float: ...
    def getMaxDesignVolumeFlow(self) -> float: ...
    def getMaxDesignWaterVolumeFlow(self) -> float: ...
    def getMaxOperationPressure(self) -> float: ...
    def getMaxOperationTemperature(self) -> float: ...
    def getMinDesignGassVolumeFLow(self) -> float: ...
    def getMinDesignOilFLow(self) -> float: ...
    def getMinDesignPressure(self) -> float: ...
    def getMinDesignVolumeFLow(self) -> float: ...
    def getMinDesignWaterVolumeFLow(self) -> float: ...
    def getMinOperationPressure(self) -> float: ...
    def getMinOperationTemperature(self) -> float: ...
    def getModuleHeight(self) -> float: ...
    def getModuleLength(self) -> float: ...
    def getModuleWidth(self) -> float: ...
    def getOuterDiameter(self) -> float: ...
    def getPressureMarginFactor(self) -> float: ...
    def getProcessEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...
    def getTantanLength(self) -> float: ...
    def getTensileStrength(self) -> float: ...
    def getVolumeTotal(self) -> float: ...
    def getWallThickness(self) -> float: ...
    def getWeightElectroInstrument(self) -> float: ...
    def getWeightNozzle(self) -> float: ...
    def getWeightPiping(self) -> float: ...
    def getWeightStructualSteel(self) -> float: ...
    def getWeightTotal(self) -> float: ...
    def getWeightVessel(self) -> float: ...
    def getWeigthInternals(self) -> float: ...
    def getWeigthVesselShell(self) -> float: ...
    def hashCode(self) -> int: ...
    def initMechanicalDesign(self) -> None: ...
    def isHasSetCompanySpecificDesignStandards(self) -> bool: ...
    def readDesignSpecifications(self) -> None: ...
    def setCompanySpecificDesignStandards(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setConstrutionMaterial(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setCorrosionAllowance(self, double: float) -> None: ...
    def setDefaultLiquidDensity(self, double: float) -> None: ...
    def setDefaultLiquidViscosity(self, double: float) -> None: ...
    def setDesign(self) -> None: ...
    def setDesignDataSource(self, mechanicalDesignDataSource: typing.Union[jneqsim.process.mechanicaldesign.data.MechanicalDesignDataSource, typing.Callable]) -> None: ...
    def setDesignDataSources(self, list: java.util.List[typing.Union[jneqsim.process.mechanicaldesign.data.MechanicalDesignDataSource, typing.Callable]]) -> None: ...
    def setDesignStandard(self, hashtable: java.util.Hashtable[typing.Union[java.lang.String, str], jneqsim.process.mechanicaldesign.designstandards.DesignStandard]) -> None: ...
    def setHasSetCompanySpecificDesignStandards(self, boolean: bool) -> None: ...
    def setInnerDiameter(self, double: float) -> None: ...
    def setJointEfficiency(self, double: float) -> None: ...
    def setMaterialDesignStandard(self, materialPlateDesignStandard: jneqsim.process.mechanicaldesign.designstandards.MaterialPlateDesignStandard) -> None: ...
    def setMaterialPipeDesignStandard(self, materialPipeDesignStandard: jneqsim.process.mechanicaldesign.designstandards.MaterialPipeDesignStandard) -> None: ...
    def setMaxDesignDuty(self, double: float) -> None: ...
    def setMaxDesignGassVolumeFlow(self, double: float) -> None: ...
    def setMaxDesignOilVolumeFlow(self, double: float) -> None: ...
    def setMaxDesignPower(self, double: float) -> None: ...
    def setMaxDesignVolumeFlow(self, double: float) -> None: ...
    def setMaxDesignWaterVolumeFlow(self, double: float) -> None: ...
    def setMaxOperationPressure(self, double: float) -> None: ...
    def setMaxOperationTemperature(self, double: float) -> None: ...
    def setMinDesignDuty(self, double: float) -> None: ...
    def setMinDesignGassVolumeFLow(self, double: float) -> None: ...
    def setMinDesignOilFLow(self, double: float) -> None: ...
    def setMinDesignPower(self, double: float) -> None: ...
    def setMinDesignVolumeFLow(self, double: float) -> None: ...
    def setMinDesignWaterVolumeFLow(self, double: float) -> None: ...
    def setMinOperationPressure(self, double: float) -> None: ...
    def setMinOperationTemperature(self, double: float) -> None: ...
    def setModuleHeight(self, double: float) -> None: ...
    def setModuleLength(self, double: float) -> None: ...
    def setModuleWidth(self, double: float) -> None: ...
    def setOuterDiameter(self, double: float) -> None: ...
    def setPressureMarginFactor(self, double: float) -> None: ...
    def setProcessEquipment(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    def setTantanLength(self, double: float) -> None: ...
    def setTensileStrength(self, double: float) -> None: ...
    def setWallThickness(self, double: float) -> None: ...
    def setWeightElectroInstrument(self, double: float) -> None: ...
    def setWeightNozzle(self, double: float) -> None: ...
    def setWeightPiping(self, double: float) -> None: ...
    def setWeightStructualSteel(self, double: float) -> None: ...
    def setWeightTotal(self, double: float) -> None: ...
    def setWeightVessel(self, double: float) -> None: ...
    def setWeigthInternals(self, double: float) -> None: ...
    def setWeigthVesselShell(self, double: float) -> None: ...
    @typing.overload
    def validateOperatingEnvelope(self) -> 'MechanicalDesignMarginResult': ...
    @typing.overload
    def validateOperatingEnvelope(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> 'MechanicalDesignMarginResult': ...

class MechanicalDesignMarginResult(java.io.Serializable):
    EMPTY: typing.ClassVar['MechanicalDesignMarginResult'] = ...
    def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCorrosionAllowanceMargin(self) -> float: ...
    def getJointEfficiencyMargin(self) -> float: ...
    def getMaxPressureMargin(self) -> float: ...
    def getMaxTemperatureMargin(self) -> float: ...
    def getMinPressureMargin(self) -> float: ...
    def getMinTemperatureMargin(self) -> float: ...
    def hashCode(self) -> int: ...
    def isWithinDesignEnvelope(self) -> bool: ...
    def toString(self) -> java.lang.String: ...

class SystemMechanicalDesign(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getMechanicalWeight(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getProcess(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getTotalNumberOfModules(self) -> int: ...
    def getTotalPlotSpace(self) -> float: ...
    def getTotalVolume(self) -> float: ...
    def getTotalWeight(self) -> float: ...
    def hashCode(self) -> int: ...
    def runDesignCalculation(self) -> None: ...
    def setCompanySpecificDesignStandards(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setDesign(self) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign")``.

    DesignLimitData: typing.Type[DesignLimitData]
    MechanicalDesign: typing.Type[MechanicalDesign]
    MechanicalDesignMarginResult: typing.Type[MechanicalDesignMarginResult]
    SystemMechanicalDesign: typing.Type[SystemMechanicalDesign]
    absorber: jneqsim.process.mechanicaldesign.absorber.__module_protocol__
    adsorber: jneqsim.process.mechanicaldesign.adsorber.__module_protocol__
    compressor: jneqsim.process.mechanicaldesign.compressor.__module_protocol__
    data: jneqsim.process.mechanicaldesign.data.__module_protocol__
    designstandards: jneqsim.process.mechanicaldesign.designstandards.__module_protocol__
    ejector: jneqsim.process.mechanicaldesign.ejector.__module_protocol__
    heatexchanger: jneqsim.process.mechanicaldesign.heatexchanger.__module_protocol__
    pipeline: jneqsim.process.mechanicaldesign.pipeline.__module_protocol__
    separator: jneqsim.process.mechanicaldesign.separator.__module_protocol__
    valve: jneqsim.process.mechanicaldesign.valve.__module_protocol__
